import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_42_eq

CREATE TABLE COURSE («COURSE_ID» INT, «TITLE» INT, «DEPT_NAME» INT, «CREDITS» INT)
CREATE TABLE DEPARTMENT («DEPT_NAME» INT, «BUILDING» INT, «BUDGET» INT)
CREATE TABLE INSTRUCTOR («ID» INT, «NAME» INT, «SALARY» INT, «DEPT_NAME» INT)
CREATE TABLE TEACHES («ID» INT, «COURSE_ID» INT, «SEC_ID» INT, «YEAR» INT, «INSTRUCTOR» INT)
CREATE TABLE SECTION («COURSE_ID» INT, «SEC_ID» INT, «YEAR» INT, «BUILDING» INT, «ROOM_NUMBER» INT, «TIME_SLOT_ID» INT)
CREATE TABLE TAKES («ID» INT, «COURSE_ID» INT, «SEC_ID» INT, «YEAR» INT, «GRADE» INT)
CREATE TABLE STUDENT («ID» INT, «NAME» INT, «DEPT_NAME» INT, «TOT_CRED» INT)

theorem eq :
    sql%([COURSE_schema, DEPARTMENT_schema, INSTRUCTOR_schema, TEACHES_schema, SECTION_schema, TAKES_schema, STUDENT_schema]) "SELECT STUDENT.ID, STUDENT.NAME FROM STUDENT JOIN (SELECT TAKES.ID, S.TIME_SLOT_ID, S.YEAR FROM TAKES JOIN SECTION AS S ON TAKES.COURSE_ID = S.COURSE_ID AND TAKES.SEC_ID = S.SEC_ID GROUP BY TAKES.ID, S.TIME_SLOT_ID, S.YEAR HAVING COUNT(S.TIME_SLOT_ID) > 1) AS A ON STUDENT.ID = A.ID GROUP BY STUDENT.ID, STUDENT.NAME HAVING COUNT(DISTINCT STUDENT.ID) > 2"
  = sql%([COURSE_schema, DEPARTMENT_schema, INSTRUCTOR_schema, TEACHES_schema, SECTION_schema, TAKES_schema, STUDENT_schema]) "SELECT STUDENT.ID, STUDENT.NAME FROM STUDENT JOIN (SELECT TAKES.ID, S.TIME_SLOT_ID, S.YEAR FROM TAKES JOIN SECTION AS S ON TAKES.COURSE_ID = S.COURSE_ID AND TAKES.SEC_ID = S.SEC_ID GROUP BY TAKES.ID, S.TIME_SLOT_ID, S.YEAR HAVING SUM(S.TIME_SLOT_ID) > 1) AS A ON STUDENT.ID = A.ID GROUP BY STUDENT.ID, STUDENT.NAME HAVING COUNT(DISTINCT STUDENT.ID) > 2"
  := by first | sql_equiv | sorry

end N_42_eq
