import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace Literature_49

CREATE TABLE MONTHS («MID» INT, «MONTH» INT)
CREATE TABLE WEEKDAYS («DID» INT, «DAY_OF_WEEK» INT)
CREATE TABLE CARRIERS («CID» INT, «NAME» INT)
CREATE TABLE FLIGHTS («FID» INT, «ORIGIN_CITY» INT, «DEST_CITY» INT, «ACTUAL_TIME» INT)

theorem eq :
    sql%([MONTHS_schema, WEEKDAYS_schema, CARRIERS_schema, FLIGHTS_schema]) "SELECT DISTINCT F.ORIGIN_CITY, F.DEST_CITY, F.ACTUAL_TIME FROM FLIGHTS AS F JOIN (SELECT A.ORIGIN_CITY, MAX(A.ACTUAL_TIME) AS MAX_TIME FROM FLIGHTS AS A GROUP BY A.ORIGIN_CITY) AS X ON F.ORIGIN_CITY = X.ORIGIN_CITY AND F.ACTUAL_TIME = X.MAX_TIME"
  = sql%([MONTHS_schema, WEEKDAYS_schema, CARRIERS_schema, FLIGHTS_schema]) "SELECT F1.ORIGIN_CITY, F1.DEST_CITY, F1.ACTUAL_TIME FROM FLIGHTS AS F1 JOIN FLIGHTS AS F2 ON F1.ORIGIN_CITY = F2.ORIGIN_CITY GROUP BY F1.ORIGIN_CITY, F1.DEST_CITY, F1.ACTUAL_TIME HAVING F1.ACTUAL_TIME = MAX(F2.ACTUAL_TIME)"
  := by first | sql_equiv | sorry

end Literature_49
