import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 4000000
set_option maxRecDepth 1000000

namespace Gen_sf035

CREATE TABLE USERS_BEHAVIORS_APP_SESSIONSTART_VIEW («APP_GROUP_ID» STRING, «PLATFORM» STRING, «DEVICE_MODEL» STRING, «DEVICE_ID» STRING, «TIME» INT, «APP_GROUP_API_ID» STRING, «OS_VERSION» STRING, «EXTERNAL_USER_ID» STRING, «APP_ID» STRING, «SESSION_ID» STRING, «APP_API_ID» STRING, «SDK_VERSION» STRING, «ID» STRING, «USER_ID» STRING, «SF_CREATED_AT» STRING)

theorem eq_0_1 :
    sql%([USERS_BEHAVIORS_APP_SESSIONSTART_VIEW_schema]) "SELECT \"APP_GROUP_ID\", CAST(TO_TIMESTAMP(\"TIME\") AS DATE) AS \"SESSION_START_DAY\", COUNT(DISTINCT \"USER_ID\") AS \"COUNT_DISTINCT_USERS\" FROM \"BRAZE_USER_EVENT_DEMO_DATASET\".\"PUBLIC\".\"USERS_BEHAVIORS_APP_SESSIONSTART_VIEW\" WHERE CAST(TO_TIMESTAMP(\"TIME\") AS DATE) BETWEEN '2023-06-01' AND '2023-06-07' GROUP BY \"APP_GROUP_ID\", \"SESSION_START_DAY\" ORDER BY \"SESSION_START_DAY\", \"COUNT_DISTINCT_USERS\" DESC" = sql%([USERS_BEHAVIORS_APP_SESSIONSTART_VIEW_schema]) "SELECT \"APP_GROUP_ID\", CAST(TO_TIMESTAMP(\"TIME\") AS DATE) AS SESSION_START_DAY, COUNT(DISTINCT \"USER_ID\") AS COUNT_DISTINCT_USERS FROM \"BRAZE_USER_EVENT_DEMO_DATASET\".\"PUBLIC\".\"USERS_BEHAVIORS_APP_SESSIONSTART_VIEW\" WHERE CAST(TO_TIMESTAMP(\"TIME\") AS DATE) BETWEEN '2023-06-01' AND '2023-06-07' GROUP BY \"APP_GROUP_ID\", SESSION_START_DAY ORDER BY SESSION_START_DAY, COUNT_DISTINCT_USERS DESC" := by sql_equiv

theorem eq_0_2 :
    sql%([USERS_BEHAVIORS_APP_SESSIONSTART_VIEW_schema]) "SELECT \"APP_GROUP_ID\", CAST(TO_TIMESTAMP(\"TIME\") AS DATE) AS \"SESSION_START_DAY\", COUNT(DISTINCT \"USER_ID\") AS \"COUNT_DISTINCT_USERS\" FROM \"BRAZE_USER_EVENT_DEMO_DATASET\".\"PUBLIC\".\"USERS_BEHAVIORS_APP_SESSIONSTART_VIEW\" WHERE CAST(TO_TIMESTAMP(\"TIME\") AS DATE) BETWEEN '2023-06-01' AND '2023-06-07' GROUP BY \"APP_GROUP_ID\", \"SESSION_START_DAY\" ORDER BY \"SESSION_START_DAY\", \"COUNT_DISTINCT_USERS\" DESC" = sql%([USERS_BEHAVIORS_APP_SESSIONSTART_VIEW_schema]) "SELECT \"APP_GROUP_ID\" AS \"APP_GROUP_ID\", CAST(TO_TIMESTAMP(\"TIME\") AS DATE) AS \"SESSION_START_DAY\", COUNT(DISTINCT \"USER_ID\") AS \"COUNT_DISTINCT_USERS\" FROM \"BRAZE_USER_EVENT_DEMO_DATASET\".\"PUBLIC\".\"USERS_BEHAVIORS_APP_SESSIONSTART_VIEW\" WHERE CAST(TO_TIMESTAMP(\"TIME\") AS DATE) BETWEEN '2023-06-01' AND '2023-06-07' GROUP BY \"APP_GROUP_ID\", CAST(TO_TIMESTAMP(\"TIME\") AS DATE) ORDER BY \"SESSION_START_DAY\", \"COUNT_DISTINCT_USERS\" DESC" := by sql_equiv

theorem eq_1_2 :
    sql%([USERS_BEHAVIORS_APP_SESSIONSTART_VIEW_schema]) "SELECT \"APP_GROUP_ID\", CAST(TO_TIMESTAMP(\"TIME\") AS DATE) AS SESSION_START_DAY, COUNT(DISTINCT \"USER_ID\") AS COUNT_DISTINCT_USERS FROM \"BRAZE_USER_EVENT_DEMO_DATASET\".\"PUBLIC\".\"USERS_BEHAVIORS_APP_SESSIONSTART_VIEW\" WHERE CAST(TO_TIMESTAMP(\"TIME\") AS DATE) BETWEEN '2023-06-01' AND '2023-06-07' GROUP BY \"APP_GROUP_ID\", SESSION_START_DAY ORDER BY SESSION_START_DAY, COUNT_DISTINCT_USERS DESC" = sql%([USERS_BEHAVIORS_APP_SESSIONSTART_VIEW_schema]) "SELECT \"APP_GROUP_ID\" AS \"APP_GROUP_ID\", CAST(TO_TIMESTAMP(\"TIME\") AS DATE) AS \"SESSION_START_DAY\", COUNT(DISTINCT \"USER_ID\") AS \"COUNT_DISTINCT_USERS\" FROM \"BRAZE_USER_EVENT_DEMO_DATASET\".\"PUBLIC\".\"USERS_BEHAVIORS_APP_SESSIONSTART_VIEW\" WHERE CAST(TO_TIMESTAMP(\"TIME\") AS DATE) BETWEEN '2023-06-01' AND '2023-06-07' GROUP BY \"APP_GROUP_ID\", CAST(TO_TIMESTAMP(\"TIME\") AS DATE) ORDER BY \"SESSION_START_DAY\", \"COUNT_DISTINCT_USERS\" DESC" := by sql_equiv

end Gen_sf035
