import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_local058 — crossskill equivalence(s)

Question: Can you provide a list of hardware product segments along with their unique product counts for 2020 in the output, ordered by the highest percentage increase in unique fact sales products from 2020 to 2021?

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_local058

CREATE TABLE HARDWARE_DIM_PRODUCT («product_code» STRING, «division» STRING, «segment» STRING, «category» STRING, «product» STRING, «variant» STRING)
CREATE TABLE HARDWARE_FACT_SALES_MONTHLY («date» STRING, «product_code» STRING, «customer_code» INT, «sold_quantity» INT, «fiscal_year» INT)

theorem eq_0_1 : ∀ t,
    (sql%([HARDWARE_DIM_PRODUCT_schema, HARDWARE_FACT_SALES_MONTHLY_schema]) "WITH product_counts AS (\n    SELECT \n        d.\"segment\",\n        f.\"fiscal_year\",\n        COUNT(DISTINCT f.\"product_code\") AS unique_products\n    FROM \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_FACT_SALES_MONTHLY\" f\n    JOIN \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_DIM_PRODUCT\" d\n        ON f.\"product_code\" = d.\"product_code\"\n    WHERE f.\"fiscal_year\" IN (2020, 2021)\n    GROUP BY d.\"segment\", f.\"fiscal_year\"\n),\npct_change AS (\n    SELECT \n        c2020.\"segment\",\n        c2020.unique_products AS PRODUCT_COUNT_2020,\n        (c2021.unique_products - c2020.unique_products)::FLOAT / c2020.unique_products * 100 AS pct_increase\n    FROM product_counts c2020\n    JOIN product_counts c2021 \n        ON c2020.\"segment\" = c2021.\"segment\"\n    WHERE c2020.\"fiscal_year\" = 2020 \n      AND c2021.\"fiscal_year\" = 2021\n)\nSELECT \n    \"segment\",\n    PRODUCT_COUNT_2020\nFROM pct_change\nORDER BY pct_increase DESC;") t ~= (sql%([HARDWARE_DIM_PRODUCT_schema, HARDWARE_FACT_SALES_MONTHLY_schema]) "SELECT\n    p.\"segment\",\n    COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2020 THEN f.\"product_code\" END) AS PRODUCT_COUNT_2020\nFROM \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_FACT_SALES_MONTHLY\" f\nJOIN \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_DIM_PRODUCT\" p\n    ON f.\"product_code\" = p.\"product_code\"\nWHERE f.\"fiscal_year\" IN (2020, 2021)\nGROUP BY p.\"segment\"\nORDER BY\n    (COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2021 THEN f.\"product_code\" END)\n     - COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2020 THEN f.\"product_code\" END)) * 100.0\n     / NULLIF(COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2020 THEN f.\"product_code\" END), 0) DESC;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_0_2 : ∀ t,
    (sql%([HARDWARE_DIM_PRODUCT_schema, HARDWARE_FACT_SALES_MONTHLY_schema]) "WITH product_counts AS (\n    SELECT \n        d.\"segment\",\n        f.\"fiscal_year\",\n        COUNT(DISTINCT f.\"product_code\") AS unique_products\n    FROM \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_FACT_SALES_MONTHLY\" f\n    JOIN \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_DIM_PRODUCT\" d\n        ON f.\"product_code\" = d.\"product_code\"\n    WHERE f.\"fiscal_year\" IN (2020, 2021)\n    GROUP BY d.\"segment\", f.\"fiscal_year\"\n),\npct_change AS (\n    SELECT \n        c2020.\"segment\",\n        c2020.unique_products AS PRODUCT_COUNT_2020,\n        (c2021.unique_products - c2020.unique_products)::FLOAT / c2020.unique_products * 100 AS pct_increase\n    FROM product_counts c2020\n    JOIN product_counts c2021 \n        ON c2020.\"segment\" = c2021.\"segment\"\n    WHERE c2020.\"fiscal_year\" = 2020 \n      AND c2021.\"fiscal_year\" = 2021\n)\nSELECT \n    \"segment\",\n    PRODUCT_COUNT_2020\nFROM pct_change\nORDER BY pct_increase DESC;") t ~= (sql%([HARDWARE_DIM_PRODUCT_schema, HARDWARE_FACT_SALES_MONTHLY_schema]) "WITH product_counts AS (\n    SELECT\n        p.\"segment\",\n        f.\"fiscal_year\",\n        COUNT(DISTINCT f.\"product_code\") AS product_count\n    FROM \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_FACT_SALES_MONTHLY\" f\n    JOIN \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_DIM_PRODUCT\" p\n        ON f.\"product_code\" = p.\"product_code\"\n    WHERE f.\"fiscal_year\" IN (2020, 2021)\n    GROUP BY p.\"segment\", f.\"fiscal_year\"\n),\npivoted AS (\n    SELECT\n        \"segment\",\n        MAX(CASE WHEN \"fiscal_year\" = 2020 THEN product_count END) AS product_count_2020,\n        MAX(CASE WHEN \"fiscal_year\" = 2021 THEN product_count END) AS product_count_2021\n    FROM product_counts\n    GROUP BY \"segment\"\n)\nSELECT\n    \"segment\",\n    product_count_2020 AS \"PRODUCT_COUNT_2020\"\nFROM pivoted\nORDER BY ((product_count_2021 - product_count_2020) * 100.0 / product_count_2020) DESC;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_0_3 : ∀ t,
    (sql%([HARDWARE_DIM_PRODUCT_schema, HARDWARE_FACT_SALES_MONTHLY_schema]) "WITH product_counts AS (\n    SELECT \n        d.\"segment\",\n        f.\"fiscal_year\",\n        COUNT(DISTINCT f.\"product_code\") AS unique_products\n    FROM \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_FACT_SALES_MONTHLY\" f\n    JOIN \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_DIM_PRODUCT\" d\n        ON f.\"product_code\" = d.\"product_code\"\n    WHERE f.\"fiscal_year\" IN (2020, 2021)\n    GROUP BY d.\"segment\", f.\"fiscal_year\"\n),\npct_change AS (\n    SELECT \n        c2020.\"segment\",\n        c2020.unique_products AS PRODUCT_COUNT_2020,\n        (c2021.unique_products - c2020.unique_products)::FLOAT / c2020.unique_products * 100 AS pct_increase\n    FROM product_counts c2020\n    JOIN product_counts c2021 \n        ON c2020.\"segment\" = c2021.\"segment\"\n    WHERE c2020.\"fiscal_year\" = 2020 \n      AND c2021.\"fiscal_year\" = 2021\n)\nSELECT \n    \"segment\",\n    PRODUCT_COUNT_2020\nFROM pct_change\nORDER BY pct_increase DESC;") t ~= (sql%([HARDWARE_DIM_PRODUCT_schema, HARDWARE_FACT_SALES_MONTHLY_schema]) "WITH product_counts AS (\n    SELECT\n        p.\"segment\",\n        COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2020 THEN f.\"product_code\" END) AS unique_products_2020,\n        COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2021 THEN f.\"product_code\" END) AS unique_products_2021\n    FROM \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_FACT_SALES_MONTHLY\" f\n    JOIN \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_DIM_PRODUCT\" p\n        ON f.\"product_code\" = p.\"product_code\"\n    WHERE f.\"fiscal_year\" IN (2020, 2021)\n    GROUP BY p.\"segment\"\n)\nSELECT\n    \"segment\",\n    unique_products_2020\nFROM product_counts\nORDER BY ((unique_products_2021 - unique_products_2020) * 100.0 / unique_products_2020) DESC;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_1_2 : ∀ t,
    (sql%([HARDWARE_DIM_PRODUCT_schema, HARDWARE_FACT_SALES_MONTHLY_schema]) "SELECT\n    p.\"segment\",\n    COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2020 THEN f.\"product_code\" END) AS PRODUCT_COUNT_2020\nFROM \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_FACT_SALES_MONTHLY\" f\nJOIN \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_DIM_PRODUCT\" p\n    ON f.\"product_code\" = p.\"product_code\"\nWHERE f.\"fiscal_year\" IN (2020, 2021)\nGROUP BY p.\"segment\"\nORDER BY\n    (COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2021 THEN f.\"product_code\" END)\n     - COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2020 THEN f.\"product_code\" END)) * 100.0\n     / NULLIF(COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2020 THEN f.\"product_code\" END), 0) DESC;") t ~= (sql%([HARDWARE_DIM_PRODUCT_schema, HARDWARE_FACT_SALES_MONTHLY_schema]) "WITH product_counts AS (\n    SELECT\n        p.\"segment\",\n        f.\"fiscal_year\",\n        COUNT(DISTINCT f.\"product_code\") AS product_count\n    FROM \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_FACT_SALES_MONTHLY\" f\n    JOIN \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_DIM_PRODUCT\" p\n        ON f.\"product_code\" = p.\"product_code\"\n    WHERE f.\"fiscal_year\" IN (2020, 2021)\n    GROUP BY p.\"segment\", f.\"fiscal_year\"\n),\npivoted AS (\n    SELECT\n        \"segment\",\n        MAX(CASE WHEN \"fiscal_year\" = 2020 THEN product_count END) AS product_count_2020,\n        MAX(CASE WHEN \"fiscal_year\" = 2021 THEN product_count END) AS product_count_2021\n    FROM product_counts\n    GROUP BY \"segment\"\n)\nSELECT\n    \"segment\",\n    product_count_2020 AS \"PRODUCT_COUNT_2020\"\nFROM pivoted\nORDER BY ((product_count_2021 - product_count_2020) * 100.0 / product_count_2020) DESC;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_1_3 : ∀ t,
    (sql%([HARDWARE_DIM_PRODUCT_schema, HARDWARE_FACT_SALES_MONTHLY_schema]) "SELECT\n    p.\"segment\",\n    COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2020 THEN f.\"product_code\" END) AS PRODUCT_COUNT_2020\nFROM \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_FACT_SALES_MONTHLY\" f\nJOIN \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_DIM_PRODUCT\" p\n    ON f.\"product_code\" = p.\"product_code\"\nWHERE f.\"fiscal_year\" IN (2020, 2021)\nGROUP BY p.\"segment\"\nORDER BY\n    (COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2021 THEN f.\"product_code\" END)\n     - COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2020 THEN f.\"product_code\" END)) * 100.0\n     / NULLIF(COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2020 THEN f.\"product_code\" END), 0) DESC;") t ~= (sql%([HARDWARE_DIM_PRODUCT_schema, HARDWARE_FACT_SALES_MONTHLY_schema]) "WITH product_counts AS (\n    SELECT\n        p.\"segment\",\n        COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2020 THEN f.\"product_code\" END) AS unique_products_2020,\n        COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2021 THEN f.\"product_code\" END) AS unique_products_2021\n    FROM \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_FACT_SALES_MONTHLY\" f\n    JOIN \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_DIM_PRODUCT\" p\n        ON f.\"product_code\" = p.\"product_code\"\n    WHERE f.\"fiscal_year\" IN (2020, 2021)\n    GROUP BY p.\"segment\"\n)\nSELECT\n    \"segment\",\n    unique_products_2020\nFROM product_counts\nORDER BY ((unique_products_2021 - unique_products_2020) * 100.0 / unique_products_2020) DESC;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_2_3 : ∀ t,
    (sql%([HARDWARE_DIM_PRODUCT_schema, HARDWARE_FACT_SALES_MONTHLY_schema]) "WITH product_counts AS (\n    SELECT\n        p.\"segment\",\n        f.\"fiscal_year\",\n        COUNT(DISTINCT f.\"product_code\") AS product_count\n    FROM \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_FACT_SALES_MONTHLY\" f\n    JOIN \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_DIM_PRODUCT\" p\n        ON f.\"product_code\" = p.\"product_code\"\n    WHERE f.\"fiscal_year\" IN (2020, 2021)\n    GROUP BY p.\"segment\", f.\"fiscal_year\"\n),\npivoted AS (\n    SELECT\n        \"segment\",\n        MAX(CASE WHEN \"fiscal_year\" = 2020 THEN product_count END) AS product_count_2020,\n        MAX(CASE WHEN \"fiscal_year\" = 2021 THEN product_count END) AS product_count_2021\n    FROM product_counts\n    GROUP BY \"segment\"\n)\nSELECT\n    \"segment\",\n    product_count_2020 AS \"PRODUCT_COUNT_2020\"\nFROM pivoted\nORDER BY ((product_count_2021 - product_count_2020) * 100.0 / product_count_2020) DESC;") t ~= (sql%([HARDWARE_DIM_PRODUCT_schema, HARDWARE_FACT_SALES_MONTHLY_schema]) "WITH product_counts AS (\n    SELECT\n        p.\"segment\",\n        COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2020 THEN f.\"product_code\" END) AS unique_products_2020,\n        COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2021 THEN f.\"product_code\" END) AS unique_products_2021\n    FROM \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_FACT_SALES_MONTHLY\" f\n    JOIN \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_DIM_PRODUCT\" p\n        ON f.\"product_code\" = p.\"product_code\"\n    WHERE f.\"fiscal_year\" IN (2020, 2021)\n    GROUP BY p.\"segment\"\n)\nSELECT\n    \"segment\",\n    unique_products_2020\nFROM product_counts\nORDER BY ((unique_products_2021 - unique_products_2020) * 100.0 / unique_products_2020) DESC;") t := by
  intro t; first | sql_equiv | sorry

end Bench_sf_local058
