import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_bq124 — crossskill equivalence(s)

Question: Among all patients, how many individuals remain alive (i.e., with no recorded deceased.dateTime), have a diagnosis of either Diabetes or Hypertension, and are prescribed at least seven distinct active medications?

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_bq124

CREATE TABLE PATIENT («active» BOOL, «animal» STRING, «contact» STRING, «generalPractitioner» STRING, «implicitRules» STRING, «language» STRING, «link» STRING, «managingOrganization» STRING, «photo» STRING, «birthPlace» STRING, «disability_adjusted_life_years» STRING, «patient_mothersMaidenName» STRING, «quality_adjusted_life_years» STRING, «shr_actor_FictionalPerson_extension» STRING, «shr_demographics_SocialSecurityNumber_extension» STRING, «shr_entity_FathersName_extension» STRING, «shr_entity_Person_extension» STRING, «us_core_birthsex» STRING, «us_core_ethnicity» STRING, «us_core_race» STRING, «address» STRING, «birthDate» STRING, «communication» STRING, «deceased» STRING, «gender» STRING, «id» STRING, «identifier» STRING, «maritalStatus» STRING, «meta» STRING, «multipleBirth» STRING, «name» STRING, «telecom» STRING, «text» STRING)
CREATE TABLE CONDITION («asserter» STRING, «bodySite» STRING, «evidence» STRING, «identifier» STRING, «implicitRules» STRING, «language» STRING, «note» STRING, «severity» STRING, «stage» STRING, «text» STRING, «abatement» STRING, «assertedDate» STRING, «category» STRING, «clinicalStatus» STRING, «code» STRING, «context» STRING, «id» STRING, «meta» STRING, «onset» STRING, «subject» STRING, «verificationStatus» STRING)
CREATE TABLE MEDICATION_REQUEST («basedOn» STRING, «category» STRING, «definition» STRING, «detectedIssue» STRING, «dispenseRequest» STRING, «eventHistory» STRING, «groupIdentifier» STRING, «identifier» STRING, «implicitRules» STRING, «language» STRING, «note» STRING, «priorPrescription» STRING, «priority» STRING, «reasonCode» STRING, «recorder» STRING, «substitution» STRING, «supportingInformation» STRING, «text» STRING, «shr_action_RequestedContext_extension» STRING, «shr_base_ActionCode_extension» STRING, «authoredOn» STRING, «context» STRING, «dosageInstruction» STRING, «id» STRING, «intent» STRING, «medication» STRING, «meta» STRING, «reasonReference» STRING, «requester» STRING, «status» STRING, «subject» STRING)

-- eq_0_1: needs a data hypothesis over multiple tables (not stated); likely `sorry`.
theorem eq_0_1 : ∀ t,
    (sql%([PATIENT_schema, CONDITION_schema, MEDICATION_REQUEST_schema]) "-- sf_bq124: Count alive patients with Diabetes or Hypertension diagnosis \n-- and at least 7 distinct active medications\nWITH alive_patients AS (\n  SELECT \"id\" AS patient_id\n  FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"PATIENT\"\n  WHERE \"deceased\":dateTime IS NULL\n),\ndiabetes_or_hypertension_patients AS (\n  SELECT DISTINCT \"subject\":patientId::STRING AS patient_id\n  FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"CONDITION\"\n  WHERE \"code\":coding[0]:display::STRING IN ('Diabetes', 'Hypertension')\n),\npatients_with_7_plus_active_meds AS (\n  SELECT \"subject\":patientId::STRING AS patient_id\n  FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"MEDICATION_REQUEST\"\n  WHERE \"status\" = 'active'\n  GROUP BY patient_id\n  HAVING COUNT(DISTINCT \"medication\":codeableConcept:coding[0]:code::STRING) >= 7\n)\nSELECT COUNT(*) AS OUTPUT\nFROM alive_patients a\nJOIN diabetes_or_hypertension_patients d ON a.patient_id = d.patient_id\nJOIN patients_with_7_plus_active_meds m ON a.patient_id = m.patient_id;") t ~= (sql%([PATIENT_schema, CONDITION_schema, MEDICATION_REQUEST_schema]) "SELECT COUNT(*) AS OUTPUT\nFROM (\n  SELECT mr.\"subject\":patientId::STRING AS patient_id\n  FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"MEDICATION_REQUEST\" mr\n  JOIN \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"PATIENT\" p\n    ON p.\"id\" = mr.\"subject\":patientId::STRING\n  WHERE p.\"deceased\":dateTime IS NULL\n    AND mr.\"status\"::STRING = 'active'\n    AND EXISTS (\n      SELECT 1\n      FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"CONDITION\" c\n      WHERE c.\"subject\":patientId::STRING = mr.\"subject\":patientId::STRING\n        AND c.\"code\":coding[0]:display::STRING IN ('Diabetes', 'Hypertension')\n    )\n  GROUP BY mr.\"subject\":patientId::STRING\n  HAVING COUNT(DISTINCT mr.\"medication\":codeableConcept:coding[0]:code::STRING) >= 7\n);") t := by
  intro t; first | sql_equiv | sorry

theorem eq_0_2 :
    sql%([PATIENT_schema, CONDITION_schema, MEDICATION_REQUEST_schema]) "-- sf_bq124: Count alive patients with Diabetes or Hypertension diagnosis \n-- and at least 7 distinct active medications\nWITH alive_patients AS (\n  SELECT \"id\" AS patient_id\n  FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"PATIENT\"\n  WHERE \"deceased\":dateTime IS NULL\n),\ndiabetes_or_hypertension_patients AS (\n  SELECT DISTINCT \"subject\":patientId::STRING AS patient_id\n  FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"CONDITION\"\n  WHERE \"code\":coding[0]:display::STRING IN ('Diabetes', 'Hypertension')\n),\npatients_with_7_plus_active_meds AS (\n  SELECT \"subject\":patientId::STRING AS patient_id\n  FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"MEDICATION_REQUEST\"\n  WHERE \"status\" = 'active'\n  GROUP BY patient_id\n  HAVING COUNT(DISTINCT \"medication\":codeableConcept:coding[0]:code::STRING) >= 7\n)\nSELECT COUNT(*) AS OUTPUT\nFROM alive_patients a\nJOIN diabetes_or_hypertension_patients d ON a.patient_id = d.patient_id\nJOIN patients_with_7_plus_active_meds m ON a.patient_id = m.patient_id;" = sql%([PATIENT_schema, CONDITION_schema, MEDICATION_REQUEST_schema]) "WITH alive_patients AS (\n    SELECT \"id\" AS patient_id\n    FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"PATIENT\"\n    WHERE \"deceased\" IS NULL\n),\ndiabetes_hypertension_patients AS (\n    SELECT DISTINCT c.\"subject\":patientId::STRING AS patient_id\n    FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"CONDITION\" c\n    WHERE c.\"code\":coding[0]:display::STRING IN ('Diabetes', 'Hypertension')\n),\npatients_with_7plus_active_meds AS (\n    SELECT mr.\"subject\":patientId::STRING AS patient_id\n    FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"MEDICATION_REQUEST\" mr\n    WHERE mr.\"status\" = 'active'\n    GROUP BY mr.\"subject\":patientId::STRING\n    HAVING COUNT(DISTINCT mr.\"medication\":codeableConcept:coding[0]:display::STRING) >= 7\n)\nSELECT COUNT(*) AS \"OUTPUT\"\nFROM alive_patients ap\nJOIN diabetes_hypertension_patients dh ON ap.patient_id = dh.patient_id\nJOIN patients_with_7plus_active_meds m ON ap.patient_id = m.patient_id;" := by
  first | sql_equiv | sorry

theorem eq_0_3 : ∀ t,
    (sql%([PATIENT_schema, CONDITION_schema, MEDICATION_REQUEST_schema]) "-- sf_bq124: Count alive patients with Diabetes or Hypertension diagnosis \n-- and at least 7 distinct active medications\nWITH alive_patients AS (\n  SELECT \"id\" AS patient_id\n  FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"PATIENT\"\n  WHERE \"deceased\":dateTime IS NULL\n),\ndiabetes_or_hypertension_patients AS (\n  SELECT DISTINCT \"subject\":patientId::STRING AS patient_id\n  FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"CONDITION\"\n  WHERE \"code\":coding[0]:display::STRING IN ('Diabetes', 'Hypertension')\n),\npatients_with_7_plus_active_meds AS (\n  SELECT \"subject\":patientId::STRING AS patient_id\n  FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"MEDICATION_REQUEST\"\n  WHERE \"status\" = 'active'\n  GROUP BY patient_id\n  HAVING COUNT(DISTINCT \"medication\":codeableConcept:coding[0]:code::STRING) >= 7\n)\nSELECT COUNT(*) AS OUTPUT\nFROM alive_patients a\nJOIN diabetes_or_hypertension_patients d ON a.patient_id = d.patient_id\nJOIN patients_with_7_plus_active_meds m ON a.patient_id = m.patient_id;") t ~= (sql%([PATIENT_schema, CONDITION_schema, MEDICATION_REQUEST_schema]) "-- Count alive patients with Diabetes or Hypertension diagnosis\n-- and at least 7 distinct active medications\nSELECT COUNT(*) AS OUTPUT\nFROM (\n    -- Get patients who are alive, have diabetes/hypertension, and >= 7 distinct active meds\n    SELECT mr.\"subject\":patientId::STRING AS patient_id\n    FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"MEDICATION_REQUEST\" mr\n    -- Join to patient to check alive status\n    INNER JOIN \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"PATIENT\" p\n        ON mr.\"subject\":patientId::STRING = p.\"id\"\n    -- Join to condition to check diabetes/hypertension\n    INNER JOIN (\n        SELECT DISTINCT \"subject\":patientId::STRING AS patient_id\n        FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"CONDITION\"\n        WHERE LOWER(\"code\":coding[0]:display::STRING) LIKE '%diabetes%'\n           OR LOWER(\"code\":coding[0]:display::STRING) LIKE '%hypertension%'\n    ) c\n        ON mr.\"subject\":patientId::STRING = c.patient_id\n    WHERE p.\"deceased\":dateTime IS NULL\n      AND mr.\"status\" = 'active'\n    GROUP BY mr.\"subject\":patientId::STRING\n    HAVING COUNT(DISTINCT mr.\"medication\":codeableConcept:coding[0]:display::STRING) >= 7\n) subq;") t := by
  intro t; first | sql_equiv | sorry

-- eq_1_2: needs a data hypothesis over multiple tables (not stated); likely `sorry`.
theorem eq_1_2 : ∀ t,
    (sql%([PATIENT_schema, CONDITION_schema, MEDICATION_REQUEST_schema]) "SELECT COUNT(*) AS OUTPUT\nFROM (\n  SELECT mr.\"subject\":patientId::STRING AS patient_id\n  FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"MEDICATION_REQUEST\" mr\n  JOIN \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"PATIENT\" p\n    ON p.\"id\" = mr.\"subject\":patientId::STRING\n  WHERE p.\"deceased\":dateTime IS NULL\n    AND mr.\"status\"::STRING = 'active'\n    AND EXISTS (\n      SELECT 1\n      FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"CONDITION\" c\n      WHERE c.\"subject\":patientId::STRING = mr.\"subject\":patientId::STRING\n        AND c.\"code\":coding[0]:display::STRING IN ('Diabetes', 'Hypertension')\n    )\n  GROUP BY mr.\"subject\":patientId::STRING\n  HAVING COUNT(DISTINCT mr.\"medication\":codeableConcept:coding[0]:code::STRING) >= 7\n);") t ~= (sql%([PATIENT_schema, CONDITION_schema, MEDICATION_REQUEST_schema]) "WITH alive_patients AS (\n    SELECT \"id\" AS patient_id\n    FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"PATIENT\"\n    WHERE \"deceased\" IS NULL\n),\ndiabetes_hypertension_patients AS (\n    SELECT DISTINCT c.\"subject\":patientId::STRING AS patient_id\n    FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"CONDITION\" c\n    WHERE c.\"code\":coding[0]:display::STRING IN ('Diabetes', 'Hypertension')\n),\npatients_with_7plus_active_meds AS (\n    SELECT mr.\"subject\":patientId::STRING AS patient_id\n    FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"MEDICATION_REQUEST\" mr\n    WHERE mr.\"status\" = 'active'\n    GROUP BY mr.\"subject\":patientId::STRING\n    HAVING COUNT(DISTINCT mr.\"medication\":codeableConcept:coding[0]:display::STRING) >= 7\n)\nSELECT COUNT(*) AS \"OUTPUT\"\nFROM alive_patients ap\nJOIN diabetes_hypertension_patients dh ON ap.patient_id = dh.patient_id\nJOIN patients_with_7plus_active_meds m ON ap.patient_id = m.patient_id;") t := by
  intro t; first | sql_equiv | sorry

-- eq_1_3: needs a data hypothesis over multiple tables (not stated); likely `sorry`.
theorem eq_1_3 :
    sql%([PATIENT_schema, CONDITION_schema, MEDICATION_REQUEST_schema]) "SELECT COUNT(*) AS OUTPUT\nFROM (\n  SELECT mr.\"subject\":patientId::STRING AS patient_id\n  FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"MEDICATION_REQUEST\" mr\n  JOIN \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"PATIENT\" p\n    ON p.\"id\" = mr.\"subject\":patientId::STRING\n  WHERE p.\"deceased\":dateTime IS NULL\n    AND mr.\"status\"::STRING = 'active'\n    AND EXISTS (\n      SELECT 1\n      FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"CONDITION\" c\n      WHERE c.\"subject\":patientId::STRING = mr.\"subject\":patientId::STRING\n        AND c.\"code\":coding[0]:display::STRING IN ('Diabetes', 'Hypertension')\n    )\n  GROUP BY mr.\"subject\":patientId::STRING\n  HAVING COUNT(DISTINCT mr.\"medication\":codeableConcept:coding[0]:code::STRING) >= 7\n);" = sql%([PATIENT_schema, CONDITION_schema, MEDICATION_REQUEST_schema]) "-- Count alive patients with Diabetes or Hypertension diagnosis\n-- and at least 7 distinct active medications\nSELECT COUNT(*) AS OUTPUT\nFROM (\n    -- Get patients who are alive, have diabetes/hypertension, and >= 7 distinct active meds\n    SELECT mr.\"subject\":patientId::STRING AS patient_id\n    FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"MEDICATION_REQUEST\" mr\n    -- Join to patient to check alive status\n    INNER JOIN \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"PATIENT\" p\n        ON mr.\"subject\":patientId::STRING = p.\"id\"\n    -- Join to condition to check diabetes/hypertension\n    INNER JOIN (\n        SELECT DISTINCT \"subject\":patientId::STRING AS patient_id\n        FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"CONDITION\"\n        WHERE LOWER(\"code\":coding[0]:display::STRING) LIKE '%diabetes%'\n           OR LOWER(\"code\":coding[0]:display::STRING) LIKE '%hypertension%'\n    ) c\n        ON mr.\"subject\":patientId::STRING = c.patient_id\n    WHERE p.\"deceased\":dateTime IS NULL\n      AND mr.\"status\" = 'active'\n    GROUP BY mr.\"subject\":patientId::STRING\n    HAVING COUNT(DISTINCT mr.\"medication\":codeableConcept:coding[0]:display::STRING) >= 7\n) subq;" := by
  first | sql_equiv | sorry

theorem eq_2_3 : ∀ t,
    (sql%([PATIENT_schema, CONDITION_schema, MEDICATION_REQUEST_schema]) "WITH alive_patients AS (\n    SELECT \"id\" AS patient_id\n    FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"PATIENT\"\n    WHERE \"deceased\" IS NULL\n),\ndiabetes_hypertension_patients AS (\n    SELECT DISTINCT c.\"subject\":patientId::STRING AS patient_id\n    FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"CONDITION\" c\n    WHERE c.\"code\":coding[0]:display::STRING IN ('Diabetes', 'Hypertension')\n),\npatients_with_7plus_active_meds AS (\n    SELECT mr.\"subject\":patientId::STRING AS patient_id\n    FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"MEDICATION_REQUEST\" mr\n    WHERE mr.\"status\" = 'active'\n    GROUP BY mr.\"subject\":patientId::STRING\n    HAVING COUNT(DISTINCT mr.\"medication\":codeableConcept:coding[0]:display::STRING) >= 7\n)\nSELECT COUNT(*) AS \"OUTPUT\"\nFROM alive_patients ap\nJOIN diabetes_hypertension_patients dh ON ap.patient_id = dh.patient_id\nJOIN patients_with_7plus_active_meds m ON ap.patient_id = m.patient_id;") t ~= (sql%([PATIENT_schema, CONDITION_schema, MEDICATION_REQUEST_schema]) "-- Count alive patients with Diabetes or Hypertension diagnosis\n-- and at least 7 distinct active medications\nSELECT COUNT(*) AS OUTPUT\nFROM (\n    -- Get patients who are alive, have diabetes/hypertension, and >= 7 distinct active meds\n    SELECT mr.\"subject\":patientId::STRING AS patient_id\n    FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"MEDICATION_REQUEST\" mr\n    -- Join to patient to check alive status\n    INNER JOIN \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"PATIENT\" p\n        ON mr.\"subject\":patientId::STRING = p.\"id\"\n    -- Join to condition to check diabetes/hypertension\n    INNER JOIN (\n        SELECT DISTINCT \"subject\":patientId::STRING AS patient_id\n        FROM \"FHIR_SYNTHEA\".\"FHIR_SYNTHEA\".\"CONDITION\"\n        WHERE LOWER(\"code\":coding[0]:display::STRING) LIKE '%diabetes%'\n           OR LOWER(\"code\":coding[0]:display::STRING) LIKE '%hypertension%'\n    ) c\n        ON mr.\"subject\":patientId::STRING = c.patient_id\n    WHERE p.\"deceased\":dateTime IS NULL\n      AND mr.\"status\" = 'active'\n    GROUP BY mr.\"subject\":patientId::STRING\n    HAVING COUNT(DISTINCT mr.\"medication\":codeableConcept:coding[0]:display::STRING) >= 7\n) subq;") t := by
  intro t; first | sql_equiv | sorry

end Bench_sf_bq124
