import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_local202 — crossskill equivalence(s)

Question: For alien data, how many of the top 10 states by alien population have a higher percentage of friendly aliens than hostile aliens, with an average alien age exceeding 200?

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_local202

CREATE TABLE ALIEN_DATA («id» INT, «first_name» STRING, «last_name» STRING, «email» STRING, «gender» STRING, «type» STRING, «birth_year» INT, «age» INT, «favorite_food» STRING, «feeding_frequency» STRING, «aggressive» INT, «occupation» STRING, «current_location» STRING, «state» STRING, «us_region» STRING, «country» STRING)

theorem eq_0_1 : ∀ t,
    (sql%([ALIEN_DATA_schema]) "WITH top_states AS (\n    SELECT \"state\", COUNT(*) AS total_pop\n    FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"ALIEN_DATA\"\n    GROUP BY \"state\"\n    ORDER BY total_pop DESC\n    LIMIT 10\n),\nstate_stats AS (\n    SELECT \n        ts.\"state\",\n        ts.total_pop,\n        SUM(CASE WHEN ad.\"aggressive\" = 0 THEN 1 ELSE 0 END) AS friendly_count,\n        SUM(CASE WHEN ad.\"aggressive\" = 1 THEN 1 ELSE 0 END) AS hostile_count,\n        AVG(ad.\"age\") AS avg_age\n    FROM top_states ts\n    JOIN \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"ALIEN_DATA\" ad ON ts.\"state\" = ad.\"state\"\n    GROUP BY ts.\"state\", ts.total_pop\n)\nSELECT COUNT(*) AS \"NUMBER_OF_STATES\"\nFROM state_stats\nWHERE friendly_count * 1.0 / total_pop > hostile_count * 1.0 / total_pop\n  AND avg_age > 200;") t ~= (sql%([ALIEN_DATA_schema]) "WITH top10_states AS (\n    SELECT \"state\", COUNT(*) AS alien_population\n    FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"ALIEN_DATA\"\n    GROUP BY \"state\"\n    ORDER BY alien_population DESC\n    LIMIT 10\n),\nstate_stats AS (\n    SELECT\n        t.\"state\",\n        SUM(CASE WHEN a.\"aggressive\" = 0 THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS pct_friendly,\n        SUM(CASE WHEN a.\"aggressive\" = 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS pct_hostile,\n        AVG(a.\"age\") AS avg_age\n    FROM top10_states t\n    JOIN \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"ALIEN_DATA\" a\n        ON t.\"state\" = a.\"state\"\n    GROUP BY t.\"state\"\n)\nSELECT COUNT(*) AS NUMBER_OF_STATES\nFROM state_stats\nWHERE pct_friendly > pct_hostile\n  AND avg_age > 200;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_0_2 : ∀ t,
    (sql%([ALIEN_DATA_schema]) "WITH top_states AS (\n    SELECT \"state\", COUNT(*) AS total_pop\n    FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"ALIEN_DATA\"\n    GROUP BY \"state\"\n    ORDER BY total_pop DESC\n    LIMIT 10\n),\nstate_stats AS (\n    SELECT \n        ts.\"state\",\n        ts.total_pop,\n        SUM(CASE WHEN ad.\"aggressive\" = 0 THEN 1 ELSE 0 END) AS friendly_count,\n        SUM(CASE WHEN ad.\"aggressive\" = 1 THEN 1 ELSE 0 END) AS hostile_count,\n        AVG(ad.\"age\") AS avg_age\n    FROM top_states ts\n    JOIN \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"ALIEN_DATA\" ad ON ts.\"state\" = ad.\"state\"\n    GROUP BY ts.\"state\", ts.total_pop\n)\nSELECT COUNT(*) AS \"NUMBER_OF_STATES\"\nFROM state_stats\nWHERE friendly_count * 1.0 / total_pop > hostile_count * 1.0 / total_pop\n  AND avg_age > 200;") t ~= (sql%([ALIEN_DATA_schema]) "WITH state_stats AS (\n    SELECT\n        \"state\",\n        COUNT(*) AS alien_population,\n        SUM(CASE WHEN \"aggressive\" = 0 THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS pct_friendly,\n        SUM(CASE WHEN \"aggressive\" = 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS pct_hostile,\n        AVG(\"age\") AS avg_age\n    FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"ALIEN_DATA\"\n    GROUP BY \"state\"\n    ORDER BY alien_population DESC\n    LIMIT 10\n)\nSELECT COUNT(*) AS \"NUMBER_OF_STATES\"\nFROM state_stats\nWHERE pct_friendly > pct_hostile\n  AND avg_age > 200;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_0_3 : ∀ t,
    (sql%([ALIEN_DATA_schema]) "WITH top_states AS (\n    SELECT \"state\", COUNT(*) AS total_pop\n    FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"ALIEN_DATA\"\n    GROUP BY \"state\"\n    ORDER BY total_pop DESC\n    LIMIT 10\n),\nstate_stats AS (\n    SELECT \n        ts.\"state\",\n        ts.total_pop,\n        SUM(CASE WHEN ad.\"aggressive\" = 0 THEN 1 ELSE 0 END) AS friendly_count,\n        SUM(CASE WHEN ad.\"aggressive\" = 1 THEN 1 ELSE 0 END) AS hostile_count,\n        AVG(ad.\"age\") AS avg_age\n    FROM top_states ts\n    JOIN \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"ALIEN_DATA\" ad ON ts.\"state\" = ad.\"state\"\n    GROUP BY ts.\"state\", ts.total_pop\n)\nSELECT COUNT(*) AS \"NUMBER_OF_STATES\"\nFROM state_stats\nWHERE friendly_count * 1.0 / total_pop > hostile_count * 1.0 / total_pop\n  AND avg_age > 200;") t ~= (sql%([ALIEN_DATA_schema]) "WITH top10_states AS (\n    SELECT \"state\", COUNT(*) AS alien_pop\n    FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"ALIEN_DATA\"\n    GROUP BY \"state\"\n    ORDER BY alien_pop DESC\n    LIMIT 10\n),\nstate_stats AS (\n    SELECT\n        t.\"state\",\n        AVG(a.\"age\") AS avg_age,\n        SUM(CASE WHEN a.\"aggressive\" = 0 THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS friendly_pct,\n        SUM(CASE WHEN a.\"aggressive\" = 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS hostile_pct\n    FROM top10_states t\n    JOIN \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"ALIEN_DATA\" a ON t.\"state\" = a.\"state\"\n    GROUP BY t.\"state\"\n)\nSELECT COUNT(*) AS NUM_STATES\nFROM state_stats\nWHERE friendly_pct > hostile_pct\n  AND avg_age > 200;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_1_2 : ∀ t,
    (sql%([ALIEN_DATA_schema]) "WITH top10_states AS (\n    SELECT \"state\", COUNT(*) AS alien_population\n    FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"ALIEN_DATA\"\n    GROUP BY \"state\"\n    ORDER BY alien_population DESC\n    LIMIT 10\n),\nstate_stats AS (\n    SELECT\n        t.\"state\",\n        SUM(CASE WHEN a.\"aggressive\" = 0 THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS pct_friendly,\n        SUM(CASE WHEN a.\"aggressive\" = 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS pct_hostile,\n        AVG(a.\"age\") AS avg_age\n    FROM top10_states t\n    JOIN \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"ALIEN_DATA\" a\n        ON t.\"state\" = a.\"state\"\n    GROUP BY t.\"state\"\n)\nSELECT COUNT(*) AS NUMBER_OF_STATES\nFROM state_stats\nWHERE pct_friendly > pct_hostile\n  AND avg_age > 200;") t ~= (sql%([ALIEN_DATA_schema]) "WITH state_stats AS (\n    SELECT\n        \"state\",\n        COUNT(*) AS alien_population,\n        SUM(CASE WHEN \"aggressive\" = 0 THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS pct_friendly,\n        SUM(CASE WHEN \"aggressive\" = 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS pct_hostile,\n        AVG(\"age\") AS avg_age\n    FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"ALIEN_DATA\"\n    GROUP BY \"state\"\n    ORDER BY alien_population DESC\n    LIMIT 10\n)\nSELECT COUNT(*) AS \"NUMBER_OF_STATES\"\nFROM state_stats\nWHERE pct_friendly > pct_hostile\n  AND avg_age > 200;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_1_3 : ∀ t,
    (sql%([ALIEN_DATA_schema]) "WITH top10_states AS (\n    SELECT \"state\", COUNT(*) AS alien_population\n    FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"ALIEN_DATA\"\n    GROUP BY \"state\"\n    ORDER BY alien_population DESC\n    LIMIT 10\n),\nstate_stats AS (\n    SELECT\n        t.\"state\",\n        SUM(CASE WHEN a.\"aggressive\" = 0 THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS pct_friendly,\n        SUM(CASE WHEN a.\"aggressive\" = 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS pct_hostile,\n        AVG(a.\"age\") AS avg_age\n    FROM top10_states t\n    JOIN \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"ALIEN_DATA\" a\n        ON t.\"state\" = a.\"state\"\n    GROUP BY t.\"state\"\n)\nSELECT COUNT(*) AS NUMBER_OF_STATES\nFROM state_stats\nWHERE pct_friendly > pct_hostile\n  AND avg_age > 200;") t ~= (sql%([ALIEN_DATA_schema]) "WITH top10_states AS (\n    SELECT \"state\", COUNT(*) AS alien_pop\n    FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"ALIEN_DATA\"\n    GROUP BY \"state\"\n    ORDER BY alien_pop DESC\n    LIMIT 10\n),\nstate_stats AS (\n    SELECT\n        t.\"state\",\n        AVG(a.\"age\") AS avg_age,\n        SUM(CASE WHEN a.\"aggressive\" = 0 THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS friendly_pct,\n        SUM(CASE WHEN a.\"aggressive\" = 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS hostile_pct\n    FROM top10_states t\n    JOIN \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"ALIEN_DATA\" a ON t.\"state\" = a.\"state\"\n    GROUP BY t.\"state\"\n)\nSELECT COUNT(*) AS NUM_STATES\nFROM state_stats\nWHERE friendly_pct > hostile_pct\n  AND avg_age > 200;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_2_3 : ∀ t,
    (sql%([ALIEN_DATA_schema]) "WITH state_stats AS (\n    SELECT\n        \"state\",\n        COUNT(*) AS alien_population,\n        SUM(CASE WHEN \"aggressive\" = 0 THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS pct_friendly,\n        SUM(CASE WHEN \"aggressive\" = 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS pct_hostile,\n        AVG(\"age\") AS avg_age\n    FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"ALIEN_DATA\"\n    GROUP BY \"state\"\n    ORDER BY alien_population DESC\n    LIMIT 10\n)\nSELECT COUNT(*) AS \"NUMBER_OF_STATES\"\nFROM state_stats\nWHERE pct_friendly > pct_hostile\n  AND avg_age > 200;") t ~= (sql%([ALIEN_DATA_schema]) "WITH top10_states AS (\n    SELECT \"state\", COUNT(*) AS alien_pop\n    FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"ALIEN_DATA\"\n    GROUP BY \"state\"\n    ORDER BY alien_pop DESC\n    LIMIT 10\n),\nstate_stats AS (\n    SELECT\n        t.\"state\",\n        AVG(a.\"age\") AS avg_age,\n        SUM(CASE WHEN a.\"aggressive\" = 0 THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS friendly_pct,\n        SUM(CASE WHEN a.\"aggressive\" = 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS hostile_pct\n    FROM top10_states t\n    JOIN \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"ALIEN_DATA\" a ON t.\"state\" = a.\"state\"\n    GROUP BY t.\"state\"\n)\nSELECT COUNT(*) AS NUM_STATES\nFROM state_stats\nWHERE friendly_pct > hostile_pct\n  AND avg_age > 200;") t := by
  intro t; first | sql_equiv | sorry

end Bench_sf_local202
