import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_bq005 — crossskill equivalence(s)

Question: Calculate the daily average Bitcoin block interval (in seconds) for 2023 by joining consecutive blocks via row-numbered self-joins (including cross-day intervals), excluding the genesis block, and list the first 10 dates with their unadjusted averages.

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_bq005

CREATE TABLE BLOCKS («block_height» INT, «block_timestamp» STRING, «block_timestamp_truncated» INT, «block_hash» STRING, «proposer_address» STRING, «last_commit_hash» STRING, «data_hash» STRING, «validators_hash» STRING, «next_validators_hash» STRING, «consensus_hash» STRING, «app_hash» STRING, «last_results_hash» STRING, «evidence_hash» STRING, «signatures» STRING)

theorem eq_0_1 : ∀ t,
    (sql%([BLOCKS_schema]) "WITH numbered AS (SELECT \"number\", \"timestamp\", ROW_NUMBER() OVER (ORDER BY \"number\") AS rn FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"BLOCKS\" WHERE \"number\" > 0), intervals AS (SELECT CAST(TO_TIMESTAMP_NTZ(CAST(a.\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) AS DATE, CAST((a.\"timestamp\" - b.\"timestamp\") AS DOUBLE PRECISION) / 1000000.0 AS block_interval_seconds FROM numbered AS a JOIN numbered AS b ON a.rn = b.rn + 1 WHERE CAST(TO_TIMESTAMP_NTZ(CAST(a.\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) >= '2023-01-01' AND CAST(TO_TIMESTAMP_NTZ(CAST(a.\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) < '2024-01-01') SELECT DATE, AVG(block_interval_seconds) AS MEAN_BLOCK_INTERVAL FROM intervals GROUP BY DATE ORDER BY DATE LIMIT 10") t ~= (sql%([BLOCKS_schema]) "WITH numbered AS (SELECT \"number\", \"timestamp\", CAST(TO_TIMESTAMP(CAST(\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) AS block_date, ROW_NUMBER() OVER (ORDER BY \"number\") AS rn FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"BLOCKS\" WHERE \"number\" > 0 /* exclude genesis block */) SELECT b.block_date AS \"DATE\", AVG(CAST((b.\"timestamp\" - a.\"timestamp\") AS DOUBLE PRECISION) / 1000000) AS \"MEAN_BLOCK_INTERVAL\" FROM numbered AS a JOIN numbered AS b ON b.rn = a.rn + 1 WHERE EXTRACT(YEAR FROM b.block_date) = 2023 GROUP BY b.block_date ORDER BY b.block_date LIMIT 10") t := by
  intro t; first | sql_equiv | sorry

theorem eq_0_2 :
    sql%([BLOCKS_schema]) "WITH numbered AS (SELECT \"number\", \"timestamp\", ROW_NUMBER() OVER (ORDER BY \"number\") AS rn FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"BLOCKS\" WHERE \"number\" > 0), intervals AS (SELECT CAST(TO_TIMESTAMP_NTZ(CAST(a.\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) AS DATE, CAST((a.\"timestamp\" - b.\"timestamp\") AS DOUBLE PRECISION) / 1000000.0 AS block_interval_seconds FROM numbered AS a JOIN numbered AS b ON a.rn = b.rn + 1 WHERE CAST(TO_TIMESTAMP_NTZ(CAST(a.\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) >= '2023-01-01' AND CAST(TO_TIMESTAMP_NTZ(CAST(a.\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) < '2024-01-01') SELECT DATE, AVG(block_interval_seconds) AS MEAN_BLOCK_INTERVAL FROM intervals GROUP BY DATE ORDER BY DATE LIMIT 10" = sql%([BLOCKS_schema]) "WITH numbered_blocks AS (SELECT \"number\", \"timestamp\", ROW_NUMBER() OVER (ORDER BY \"number\") AS rn FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"BLOCKS\" WHERE \"number\" > 0), block_intervals AS (SELECT b2.\"number\", b2.\"timestamp\", CAST((b2.\"timestamp\" - b1.\"timestamp\") AS DOUBLE PRECISION) / 1000000.0 AS interval_seconds FROM numbered_blocks AS b1 JOIN numbered_blocks AS b2 ON b2.rn = b1.rn + 1), daily_avg AS (SELECT CAST(TO_TIMESTAMP(CAST(bi.\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) AS \"DATE\", AVG(bi.interval_seconds) AS \"MEAN_BLOCK_INTERVAL\" FROM block_intervals AS bi WHERE CAST(TO_TIMESTAMP(CAST(bi.\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) >= '2023-01-01' AND CAST(TO_TIMESTAMP(CAST(bi.\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) < '2024-01-01' GROUP BY CAST(TO_TIMESTAMP(CAST(bi.\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE)) SELECT \"DATE\", \"MEAN_BLOCK_INTERVAL\" FROM daily_avg ORDER BY \"DATE\" LIMIT 10" := by
  first | sql_equiv | sorry

theorem eq_0_3 :
    sql%([BLOCKS_schema]) "WITH numbered AS (SELECT \"number\", \"timestamp\", ROW_NUMBER() OVER (ORDER BY \"number\") AS rn FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"BLOCKS\" WHERE \"number\" > 0), intervals AS (SELECT CAST(TO_TIMESTAMP_NTZ(CAST(a.\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) AS DATE, CAST((a.\"timestamp\" - b.\"timestamp\") AS DOUBLE PRECISION) / 1000000.0 AS block_interval_seconds FROM numbered AS a JOIN numbered AS b ON a.rn = b.rn + 1 WHERE CAST(TO_TIMESTAMP_NTZ(CAST(a.\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) >= '2023-01-01' AND CAST(TO_TIMESTAMP_NTZ(CAST(a.\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) < '2024-01-01') SELECT DATE, AVG(block_interval_seconds) AS MEAN_BLOCK_INTERVAL FROM intervals GROUP BY DATE ORDER BY DATE LIMIT 10" = sql%([BLOCKS_schema]) "WITH numbered_blocks AS (SELECT \"number\", \"timestamp\", ROW_NUMBER() OVER (ORDER BY \"number\") AS rn FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"BLOCKS\" WHERE \"number\" > 0), block_intervals AS (SELECT CAST(TO_TIMESTAMP(CAST(b.\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) AS \"DATE\", CAST((b.\"timestamp\" - a.\"timestamp\") AS DOUBLE PRECISION) / 1000000.0 AS interval_seconds FROM numbered_blocks AS b JOIN numbered_blocks AS a ON b.rn = a.rn + 1) SELECT \"DATE\", AVG(interval_seconds) AS \"MEAN_BLOCK_INTERVAL\" FROM block_intervals WHERE \"DATE\" >= '2023-01-01' AND \"DATE\" < '2024-01-01' GROUP BY \"DATE\" ORDER BY \"DATE\" LIMIT 10" := by
  first | sql_equiv | sorry

theorem eq_1_2 : ∀ t,
    (sql%([BLOCKS_schema]) "WITH numbered AS (SELECT \"number\", \"timestamp\", CAST(TO_TIMESTAMP(CAST(\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) AS block_date, ROW_NUMBER() OVER (ORDER BY \"number\") AS rn FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"BLOCKS\" WHERE \"number\" > 0 /* exclude genesis block */) SELECT b.block_date AS \"DATE\", AVG(CAST((b.\"timestamp\" - a.\"timestamp\") AS DOUBLE PRECISION) / 1000000) AS \"MEAN_BLOCK_INTERVAL\" FROM numbered AS a JOIN numbered AS b ON b.rn = a.rn + 1 WHERE EXTRACT(YEAR FROM b.block_date) = 2023 GROUP BY b.block_date ORDER BY b.block_date LIMIT 10") t ~= (sql%([BLOCKS_schema]) "WITH numbered_blocks AS (SELECT \"number\", \"timestamp\", ROW_NUMBER() OVER (ORDER BY \"number\") AS rn FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"BLOCKS\" WHERE \"number\" > 0), block_intervals AS (SELECT b2.\"number\", b2.\"timestamp\", CAST((b2.\"timestamp\" - b1.\"timestamp\") AS DOUBLE PRECISION) / 1000000.0 AS interval_seconds FROM numbered_blocks AS b1 JOIN numbered_blocks AS b2 ON b2.rn = b1.rn + 1), daily_avg AS (SELECT CAST(TO_TIMESTAMP(CAST(bi.\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) AS \"DATE\", AVG(bi.interval_seconds) AS \"MEAN_BLOCK_INTERVAL\" FROM block_intervals AS bi WHERE CAST(TO_TIMESTAMP(CAST(bi.\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) >= '2023-01-01' AND CAST(TO_TIMESTAMP(CAST(bi.\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) < '2024-01-01' GROUP BY CAST(TO_TIMESTAMP(CAST(bi.\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE)) SELECT \"DATE\", \"MEAN_BLOCK_INTERVAL\" FROM daily_avg ORDER BY \"DATE\" LIMIT 10") t := by
  intro t; first | sql_equiv | sorry

theorem eq_1_3 : ∀ t,
    (sql%([BLOCKS_schema]) "WITH numbered AS (SELECT \"number\", \"timestamp\", CAST(TO_TIMESTAMP(CAST(\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) AS block_date, ROW_NUMBER() OVER (ORDER BY \"number\") AS rn FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"BLOCKS\" WHERE \"number\" > 0 /* exclude genesis block */) SELECT b.block_date AS \"DATE\", AVG(CAST((b.\"timestamp\" - a.\"timestamp\") AS DOUBLE PRECISION) / 1000000) AS \"MEAN_BLOCK_INTERVAL\" FROM numbered AS a JOIN numbered AS b ON b.rn = a.rn + 1 WHERE EXTRACT(YEAR FROM b.block_date) = 2023 GROUP BY b.block_date ORDER BY b.block_date LIMIT 10") t ~= (sql%([BLOCKS_schema]) "WITH numbered_blocks AS (SELECT \"number\", \"timestamp\", ROW_NUMBER() OVER (ORDER BY \"number\") AS rn FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"BLOCKS\" WHERE \"number\" > 0), block_intervals AS (SELECT CAST(TO_TIMESTAMP(CAST(b.\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) AS \"DATE\", CAST((b.\"timestamp\" - a.\"timestamp\") AS DOUBLE PRECISION) / 1000000.0 AS interval_seconds FROM numbered_blocks AS b JOIN numbered_blocks AS a ON b.rn = a.rn + 1) SELECT \"DATE\", AVG(interval_seconds) AS \"MEAN_BLOCK_INTERVAL\" FROM block_intervals WHERE \"DATE\" >= '2023-01-01' AND \"DATE\" < '2024-01-01' GROUP BY \"DATE\" ORDER BY \"DATE\" LIMIT 10") t := by
  intro t; first | sql_equiv | sorry

theorem eq_2_3 :
    sql%([BLOCKS_schema]) "WITH numbered_blocks AS (SELECT \"number\", \"timestamp\", ROW_NUMBER() OVER (ORDER BY \"number\") AS rn FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"BLOCKS\" WHERE \"number\" > 0), block_intervals AS (SELECT b2.\"number\", b2.\"timestamp\", CAST((b2.\"timestamp\" - b1.\"timestamp\") AS DOUBLE PRECISION) / 1000000.0 AS interval_seconds FROM numbered_blocks AS b1 JOIN numbered_blocks AS b2 ON b2.rn = b1.rn + 1), daily_avg AS (SELECT CAST(TO_TIMESTAMP(CAST(bi.\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) AS \"DATE\", AVG(bi.interval_seconds) AS \"MEAN_BLOCK_INTERVAL\" FROM block_intervals AS bi WHERE CAST(TO_TIMESTAMP(CAST(bi.\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) >= '2023-01-01' AND CAST(TO_TIMESTAMP(CAST(bi.\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) < '2024-01-01' GROUP BY CAST(TO_TIMESTAMP(CAST(bi.\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE)) SELECT \"DATE\", \"MEAN_BLOCK_INTERVAL\" FROM daily_avg ORDER BY \"DATE\" LIMIT 10" = sql%([BLOCKS_schema]) "WITH numbered_blocks AS (SELECT \"number\", \"timestamp\", ROW_NUMBER() OVER (ORDER BY \"number\") AS rn FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"BLOCKS\" WHERE \"number\" > 0), block_intervals AS (SELECT CAST(TO_TIMESTAMP(CAST(b.\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) AS \"DATE\", CAST((b.\"timestamp\" - a.\"timestamp\") AS DOUBLE PRECISION) / 1000000.0 AS interval_seconds FROM numbered_blocks AS b JOIN numbered_blocks AS a ON b.rn = a.rn + 1) SELECT \"DATE\", AVG(interval_seconds) AS \"MEAN_BLOCK_INTERVAL\" FROM block_intervals WHERE \"DATE\" >= '2023-01-01' AND \"DATE\" < '2024-01-01' GROUP BY \"DATE\" ORDER BY \"DATE\" LIMIT 10" := by
  first | sql_equiv | sorry

end Bench_sf_bq005
