import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_bq045 — crossskill equivalence(s)

Question: Which weather stations in Washington State recorded more than 150 rainy days in 2023 but fewer rainy days compared to 2022? Defining a “rainy day” as one having precipitation greater than zero millimeters and not equal to 99.99. Only include stations with valid precipitation data.

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_bq045

CREATE TABLE STATIONS («usaf» STRING, «wban» STRING, «name» STRING, «country» STRING, «state» STRING, «call» STRING, «lat» FLOAT, «lon» FLOAT, «elev» STRING, «begin» STRING, «end» STRING)
CREATE TABLE GSOD2023 («stn» STRING, «wban» STRING, «date» STRING, «year» STRING, «mo» STRING, «da» STRING, «temp» FLOAT, «count_temp» INT, «dewp» FLOAT, «count_dewp» INT, «slp» FLOAT, «count_slp» INT, «stp» FLOAT, «count_stp» INT, «visib» FLOAT, «count_visib» INT, «wdsp» STRING, «count_wdsp» STRING, «mxpsd» STRING, «gust» FLOAT, «max» FLOAT, «flag_max» STRING, «min» FLOAT, «flag_min» STRING, «prcp» FLOAT, «flag_prcp» STRING, «sndp» FLOAT, «fog» STRING, «rain_drizzle» STRING, «snow_ice_pellets» STRING, «hail» STRING, «thunder» STRING, «tornado_funnel_cloud» STRING)
CREATE TABLE GSOD2022 («stn» STRING, «wban» STRING, «date» STRING, «year» STRING, «mo» STRING, «da» STRING, «temp» FLOAT, «count_temp» INT, «dewp» FLOAT, «count_dewp» INT, «slp» FLOAT, «count_slp» INT, «stp» FLOAT, «count_stp» INT, «visib» FLOAT, «count_visib» INT, «wdsp» STRING, «count_wdsp» STRING, «mxpsd» STRING, «gust» FLOAT, «max» FLOAT, «flag_max» STRING, «min» FLOAT, «flag_min» STRING, «prcp» FLOAT, «flag_prcp» STRING, «sndp» FLOAT, «fog» STRING, «rain_drizzle» STRING, «snow_ice_pellets» STRING, «hail» STRING, «thunder» STRING, «tornado_funnel_cloud» STRING)

theorem eq_0_1 : ∀ t,
    (sql%([STATIONS_schema, GSOD2023_schema, GSOD2022_schema]) "WITH wa_2023 AS (SELECT g.\"stn\" AS STATION_ID, g.\"wban\" AS WBAN_ID, s.\"name\" AS STATION_NAME, COUNT(CASE WHEN g.\"prcp\" > 0 AND g.\"prcp\" <> 99.99 THEN 1 END) AS RAINY_DAYS_2023 FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"GSOD2023\" AS g JOIN \"NOAA_DATA\".\"NOAA_GSOD\".\"STATIONS\" AS s ON g.\"stn\" = s.\"usaf\" AND g.\"wban\" = s.\"wban\" WHERE s.\"state\" = 'WA' GROUP BY g.\"stn\", g.\"wban\", s.\"name\" HAVING RAINY_DAYS_2023 > 150), wa_2022 AS (SELECT g.\"stn\" AS STATION_ID, g.\"wban\" AS WBAN_ID, COUNT(CASE WHEN g.\"prcp\" > 0 AND g.\"prcp\" <> 99.99 THEN 1 END) AS RAINY_DAYS_2022 FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"GSOD2022\" AS g JOIN \"NOAA_DATA\".\"NOAA_GSOD\".\"STATIONS\" AS s ON g.\"stn\" = s.\"usaf\" AND g.\"wban\" = s.\"wban\" WHERE s.\"state\" = 'WA' GROUP BY g.\"stn\", g.\"wban\") SELECT t23.STATION_ID, t23.STATION_NAME, t23.RAINY_DAYS_2023, t22.RAINY_DAYS_2022 FROM wa_2023 AS t23 JOIN wa_2022 AS t22 ON t23.STATION_ID = t22.STATION_ID AND t23.WBAN_ID = t22.WBAN_ID WHERE t23.RAINY_DAYS_2023 < t22.RAINY_DAYS_2022 ORDER BY t23.RAINY_DAYS_2023 DESC") t ~= (sql%([STATIONS_schema, GSOD2023_schema, GSOD2022_schema]) "WITH rainy_2023 AS (SELECT g.\"stn\" AS STATION_ID, g.\"wban\" AS WBAN, s.\"name\" AS STATION_NAME, COUNT(CASE WHEN g.\"prcp\" > 0 AND g.\"prcp\" <> 99.99 THEN 1 END) AS RAINY_DAYS_2023 FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"GSOD2023\" AS g JOIN \"NOAA_DATA\".\"NOAA_GSOD\".\"STATIONS\" AS s ON g.\"stn\" = s.\"usaf\" AND g.\"wban\" = s.\"wban\" WHERE s.\"state\" = 'WA' GROUP BY g.\"stn\", g.\"wban\", s.\"name\" HAVING COUNT(CASE WHEN g.\"prcp\" > 0 AND g.\"prcp\" <> 99.99 THEN 1 END) > 150), rainy_2022 AS (SELECT g.\"stn\" AS STATION_ID, g.\"wban\" AS WBAN, COUNT(CASE WHEN g.\"prcp\" > 0 AND g.\"prcp\" <> 99.99 THEN 1 END) AS RAINY_DAYS_2022 FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"GSOD2022\" AS g JOIN \"NOAA_DATA\".\"NOAA_GSOD\".\"STATIONS\" AS s ON g.\"stn\" = s.\"usaf\" AND g.\"wban\" = s.\"wban\" WHERE s.\"state\" = 'WA' GROUP BY g.\"stn\", g.\"wban\") SELECT r23.STATION_ID, r23.STATION_NAME, r23.RAINY_DAYS_2023, r22.RAINY_DAYS_2022 FROM rainy_2023 AS r23 JOIN rainy_2022 AS r22 ON r23.STATION_ID = r22.STATION_ID AND r23.WBAN = r22.WBAN WHERE r23.RAINY_DAYS_2023 < r22.RAINY_DAYS_2022 ORDER BY r23.RAINY_DAYS_2023 DESC") t := by
  intro t; first | sql_equiv | sorry

-- eq_0_2: needs a data hypothesis over multiple tables (not stated); likely `sorry`.
theorem eq_0_2 : ∀ t,
    (sql%([STATIONS_schema, GSOD2023_schema, GSOD2022_schema]) "WITH wa_2023 AS (SELECT g.\"stn\" AS STATION_ID, g.\"wban\" AS WBAN_ID, s.\"name\" AS STATION_NAME, COUNT(CASE WHEN g.\"prcp\" > 0 AND g.\"prcp\" <> 99.99 THEN 1 END) AS RAINY_DAYS_2023 FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"GSOD2023\" AS g JOIN \"NOAA_DATA\".\"NOAA_GSOD\".\"STATIONS\" AS s ON g.\"stn\" = s.\"usaf\" AND g.\"wban\" = s.\"wban\" WHERE s.\"state\" = 'WA' GROUP BY g.\"stn\", g.\"wban\", s.\"name\" HAVING RAINY_DAYS_2023 > 150), wa_2022 AS (SELECT g.\"stn\" AS STATION_ID, g.\"wban\" AS WBAN_ID, COUNT(CASE WHEN g.\"prcp\" > 0 AND g.\"prcp\" <> 99.99 THEN 1 END) AS RAINY_DAYS_2022 FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"GSOD2022\" AS g JOIN \"NOAA_DATA\".\"NOAA_GSOD\".\"STATIONS\" AS s ON g.\"stn\" = s.\"usaf\" AND g.\"wban\" = s.\"wban\" WHERE s.\"state\" = 'WA' GROUP BY g.\"stn\", g.\"wban\") SELECT t23.STATION_ID, t23.STATION_NAME, t23.RAINY_DAYS_2023, t22.RAINY_DAYS_2022 FROM wa_2023 AS t23 JOIN wa_2022 AS t22 ON t23.STATION_ID = t22.STATION_ID AND t23.WBAN_ID = t22.WBAN_ID WHERE t23.RAINY_DAYS_2023 < t22.RAINY_DAYS_2022 ORDER BY t23.RAINY_DAYS_2023 DESC") t ~= (sql%([STATIONS_schema, GSOD2023_schema, GSOD2022_schema]) "WITH rainy_2023 AS (SELECT g.\"stn\" AS station_id, g.\"wban\", COUNT(*) AS rainy_days_2023 FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"GSOD2023\" AS g WHERE g.\"prcp\" > 0 AND g.\"prcp\" <> 99.99 GROUP BY g.\"stn\", g.\"wban\"), rainy_2022 AS (SELECT g.\"stn\" AS station_id, g.\"wban\", COUNT(*) AS rainy_days_2022 FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"GSOD2022\" AS g WHERE g.\"prcp\" > 0 AND g.\"prcp\" <> 99.99 GROUP BY g.\"stn\", g.\"wban\") SELECT s.\"usaf\" AS \"STATION_ID\", s.\"name\" AS \"STATION_NAME\", r23.rainy_days_2023 AS \"RAINY_DAYS_2023\", r22.rainy_days_2022 AS \"RAINY_DAYS_2022\" FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"STATIONS\" AS s JOIN rainy_2023 AS r23 ON s.\"usaf\" = r23.station_id AND s.\"wban\" = r23.\"wban\" JOIN rainy_2022 AS r22 ON s.\"usaf\" = r22.station_id AND s.\"wban\" = r22.\"wban\" WHERE s.\"state\" = 'WA' AND r23.rainy_days_2023 > 150 AND r23.rainy_days_2023 < r22.rainy_days_2022 ORDER BY r23.rainy_days_2023 DESC") t := by
  intro t; first | sql_equiv | sorry

-- eq_0_3: needs a data hypothesis over multiple tables (not stated); likely `sorry`.
theorem eq_0_3 : ∀ t,
    (sql%([STATIONS_schema, GSOD2023_schema, GSOD2022_schema]) "WITH wa_2023 AS (SELECT g.\"stn\" AS STATION_ID, g.\"wban\" AS WBAN_ID, s.\"name\" AS STATION_NAME, COUNT(CASE WHEN g.\"prcp\" > 0 AND g.\"prcp\" <> 99.99 THEN 1 END) AS RAINY_DAYS_2023 FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"GSOD2023\" AS g JOIN \"NOAA_DATA\".\"NOAA_GSOD\".\"STATIONS\" AS s ON g.\"stn\" = s.\"usaf\" AND g.\"wban\" = s.\"wban\" WHERE s.\"state\" = 'WA' GROUP BY g.\"stn\", g.\"wban\", s.\"name\" HAVING RAINY_DAYS_2023 > 150), wa_2022 AS (SELECT g.\"stn\" AS STATION_ID, g.\"wban\" AS WBAN_ID, COUNT(CASE WHEN g.\"prcp\" > 0 AND g.\"prcp\" <> 99.99 THEN 1 END) AS RAINY_DAYS_2022 FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"GSOD2022\" AS g JOIN \"NOAA_DATA\".\"NOAA_GSOD\".\"STATIONS\" AS s ON g.\"stn\" = s.\"usaf\" AND g.\"wban\" = s.\"wban\" WHERE s.\"state\" = 'WA' GROUP BY g.\"stn\", g.\"wban\") SELECT t23.STATION_ID, t23.STATION_NAME, t23.RAINY_DAYS_2023, t22.RAINY_DAYS_2022 FROM wa_2023 AS t23 JOIN wa_2022 AS t22 ON t23.STATION_ID = t22.STATION_ID AND t23.WBAN_ID = t22.WBAN_ID WHERE t23.RAINY_DAYS_2023 < t22.RAINY_DAYS_2022 ORDER BY t23.RAINY_DAYS_2023 DESC") t ~= (sql%([STATIONS_schema, GSOD2023_schema, GSOD2022_schema]) "WITH wa_stations AS (SELECT DISTINCT \"usaf\", \"wban\", \"name\" FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"STATIONS\" WHERE \"state\" = 'WA'), rainy_2023 AS (SELECT g.\"stn\" AS STATION_ID, g.\"wban\" AS WBAN, s.\"name\" AS STATION_NAME, COUNT(*) AS RAINY_DAYS_2023 FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"GSOD2023\" AS g JOIN wa_stations AS s ON g.\"stn\" = s.\"usaf\" AND g.\"wban\" = s.\"wban\" WHERE g.\"prcp\" > 0 AND g.\"prcp\" <> 99.99 GROUP BY g.\"stn\", g.\"wban\", s.\"name\"), rainy_2022 AS (SELECT g.\"stn\" AS STATION_ID, g.\"wban\" AS WBAN, COUNT(*) AS RAINY_DAYS_2022 FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"GSOD2022\" AS g JOIN wa_stations AS s ON g.\"stn\" = s.\"usaf\" AND g.\"wban\" = s.\"wban\" WHERE g.\"prcp\" > 0 AND g.\"prcp\" <> 99.99 GROUP BY g.\"stn\", g.\"wban\") SELECT r23.STATION_ID, r23.STATION_NAME, r23.RAINY_DAYS_2023, r22.RAINY_DAYS_2022 FROM rainy_2023 AS r23 JOIN rainy_2022 AS r22 ON r23.STATION_ID = r22.STATION_ID AND r23.WBAN = r22.WBAN WHERE r23.RAINY_DAYS_2023 > 150 AND r23.RAINY_DAYS_2023 < r22.RAINY_DAYS_2022 ORDER BY r23.RAINY_DAYS_2023 DESC") t := by
  intro t; first | sql_equiv | sorry

-- eq_1_2: needs a data hypothesis over multiple tables (not stated); likely `sorry`.
theorem eq_1_2 : ∀ t,
    (sql%([STATIONS_schema, GSOD2023_schema, GSOD2022_schema]) "WITH rainy_2023 AS (SELECT g.\"stn\" AS STATION_ID, g.\"wban\" AS WBAN, s.\"name\" AS STATION_NAME, COUNT(CASE WHEN g.\"prcp\" > 0 AND g.\"prcp\" <> 99.99 THEN 1 END) AS RAINY_DAYS_2023 FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"GSOD2023\" AS g JOIN \"NOAA_DATA\".\"NOAA_GSOD\".\"STATIONS\" AS s ON g.\"stn\" = s.\"usaf\" AND g.\"wban\" = s.\"wban\" WHERE s.\"state\" = 'WA' GROUP BY g.\"stn\", g.\"wban\", s.\"name\" HAVING COUNT(CASE WHEN g.\"prcp\" > 0 AND g.\"prcp\" <> 99.99 THEN 1 END) > 150), rainy_2022 AS (SELECT g.\"stn\" AS STATION_ID, g.\"wban\" AS WBAN, COUNT(CASE WHEN g.\"prcp\" > 0 AND g.\"prcp\" <> 99.99 THEN 1 END) AS RAINY_DAYS_2022 FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"GSOD2022\" AS g JOIN \"NOAA_DATA\".\"NOAA_GSOD\".\"STATIONS\" AS s ON g.\"stn\" = s.\"usaf\" AND g.\"wban\" = s.\"wban\" WHERE s.\"state\" = 'WA' GROUP BY g.\"stn\", g.\"wban\") SELECT r23.STATION_ID, r23.STATION_NAME, r23.RAINY_DAYS_2023, r22.RAINY_DAYS_2022 FROM rainy_2023 AS r23 JOIN rainy_2022 AS r22 ON r23.STATION_ID = r22.STATION_ID AND r23.WBAN = r22.WBAN WHERE r23.RAINY_DAYS_2023 < r22.RAINY_DAYS_2022 ORDER BY r23.RAINY_DAYS_2023 DESC") t ~= (sql%([STATIONS_schema, GSOD2023_schema, GSOD2022_schema]) "WITH rainy_2023 AS (SELECT g.\"stn\" AS station_id, g.\"wban\", COUNT(*) AS rainy_days_2023 FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"GSOD2023\" AS g WHERE g.\"prcp\" > 0 AND g.\"prcp\" <> 99.99 GROUP BY g.\"stn\", g.\"wban\"), rainy_2022 AS (SELECT g.\"stn\" AS station_id, g.\"wban\", COUNT(*) AS rainy_days_2022 FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"GSOD2022\" AS g WHERE g.\"prcp\" > 0 AND g.\"prcp\" <> 99.99 GROUP BY g.\"stn\", g.\"wban\") SELECT s.\"usaf\" AS \"STATION_ID\", s.\"name\" AS \"STATION_NAME\", r23.rainy_days_2023 AS \"RAINY_DAYS_2023\", r22.rainy_days_2022 AS \"RAINY_DAYS_2022\" FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"STATIONS\" AS s JOIN rainy_2023 AS r23 ON s.\"usaf\" = r23.station_id AND s.\"wban\" = r23.\"wban\" JOIN rainy_2022 AS r22 ON s.\"usaf\" = r22.station_id AND s.\"wban\" = r22.\"wban\" WHERE s.\"state\" = 'WA' AND r23.rainy_days_2023 > 150 AND r23.rainy_days_2023 < r22.rainy_days_2022 ORDER BY r23.rainy_days_2023 DESC") t := by
  intro t; first | sql_equiv | sorry

-- eq_1_3: needs a data hypothesis over multiple tables (not stated); likely `sorry`.
theorem eq_1_3 : ∀ t,
    (sql%([STATIONS_schema, GSOD2023_schema, GSOD2022_schema]) "WITH rainy_2023 AS (SELECT g.\"stn\" AS STATION_ID, g.\"wban\" AS WBAN, s.\"name\" AS STATION_NAME, COUNT(CASE WHEN g.\"prcp\" > 0 AND g.\"prcp\" <> 99.99 THEN 1 END) AS RAINY_DAYS_2023 FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"GSOD2023\" AS g JOIN \"NOAA_DATA\".\"NOAA_GSOD\".\"STATIONS\" AS s ON g.\"stn\" = s.\"usaf\" AND g.\"wban\" = s.\"wban\" WHERE s.\"state\" = 'WA' GROUP BY g.\"stn\", g.\"wban\", s.\"name\" HAVING COUNT(CASE WHEN g.\"prcp\" > 0 AND g.\"prcp\" <> 99.99 THEN 1 END) > 150), rainy_2022 AS (SELECT g.\"stn\" AS STATION_ID, g.\"wban\" AS WBAN, COUNT(CASE WHEN g.\"prcp\" > 0 AND g.\"prcp\" <> 99.99 THEN 1 END) AS RAINY_DAYS_2022 FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"GSOD2022\" AS g JOIN \"NOAA_DATA\".\"NOAA_GSOD\".\"STATIONS\" AS s ON g.\"stn\" = s.\"usaf\" AND g.\"wban\" = s.\"wban\" WHERE s.\"state\" = 'WA' GROUP BY g.\"stn\", g.\"wban\") SELECT r23.STATION_ID, r23.STATION_NAME, r23.RAINY_DAYS_2023, r22.RAINY_DAYS_2022 FROM rainy_2023 AS r23 JOIN rainy_2022 AS r22 ON r23.STATION_ID = r22.STATION_ID AND r23.WBAN = r22.WBAN WHERE r23.RAINY_DAYS_2023 < r22.RAINY_DAYS_2022 ORDER BY r23.RAINY_DAYS_2023 DESC") t ~= (sql%([STATIONS_schema, GSOD2023_schema, GSOD2022_schema]) "WITH wa_stations AS (SELECT DISTINCT \"usaf\", \"wban\", \"name\" FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"STATIONS\" WHERE \"state\" = 'WA'), rainy_2023 AS (SELECT g.\"stn\" AS STATION_ID, g.\"wban\" AS WBAN, s.\"name\" AS STATION_NAME, COUNT(*) AS RAINY_DAYS_2023 FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"GSOD2023\" AS g JOIN wa_stations AS s ON g.\"stn\" = s.\"usaf\" AND g.\"wban\" = s.\"wban\" WHERE g.\"prcp\" > 0 AND g.\"prcp\" <> 99.99 GROUP BY g.\"stn\", g.\"wban\", s.\"name\"), rainy_2022 AS (SELECT g.\"stn\" AS STATION_ID, g.\"wban\" AS WBAN, COUNT(*) AS RAINY_DAYS_2022 FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"GSOD2022\" AS g JOIN wa_stations AS s ON g.\"stn\" = s.\"usaf\" AND g.\"wban\" = s.\"wban\" WHERE g.\"prcp\" > 0 AND g.\"prcp\" <> 99.99 GROUP BY g.\"stn\", g.\"wban\") SELECT r23.STATION_ID, r23.STATION_NAME, r23.RAINY_DAYS_2023, r22.RAINY_DAYS_2022 FROM rainy_2023 AS r23 JOIN rainy_2022 AS r22 ON r23.STATION_ID = r22.STATION_ID AND r23.WBAN = r22.WBAN WHERE r23.RAINY_DAYS_2023 > 150 AND r23.RAINY_DAYS_2023 < r22.RAINY_DAYS_2022 ORDER BY r23.RAINY_DAYS_2023 DESC") t := by
  intro t; first | sql_equiv | sorry

-- eq_2_3: needs a data hypothesis over multiple tables (not stated); likely `sorry`.
theorem eq_2_3 : ∀ t,
    (sql%([STATIONS_schema, GSOD2023_schema, GSOD2022_schema]) "WITH rainy_2023 AS (SELECT g.\"stn\" AS station_id, g.\"wban\", COUNT(*) AS rainy_days_2023 FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"GSOD2023\" AS g WHERE g.\"prcp\" > 0 AND g.\"prcp\" <> 99.99 GROUP BY g.\"stn\", g.\"wban\"), rainy_2022 AS (SELECT g.\"stn\" AS station_id, g.\"wban\", COUNT(*) AS rainy_days_2022 FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"GSOD2022\" AS g WHERE g.\"prcp\" > 0 AND g.\"prcp\" <> 99.99 GROUP BY g.\"stn\", g.\"wban\") SELECT s.\"usaf\" AS \"STATION_ID\", s.\"name\" AS \"STATION_NAME\", r23.rainy_days_2023 AS \"RAINY_DAYS_2023\", r22.rainy_days_2022 AS \"RAINY_DAYS_2022\" FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"STATIONS\" AS s JOIN rainy_2023 AS r23 ON s.\"usaf\" = r23.station_id AND s.\"wban\" = r23.\"wban\" JOIN rainy_2022 AS r22 ON s.\"usaf\" = r22.station_id AND s.\"wban\" = r22.\"wban\" WHERE s.\"state\" = 'WA' AND r23.rainy_days_2023 > 150 AND r23.rainy_days_2023 < r22.rainy_days_2022 ORDER BY r23.rainy_days_2023 DESC") t ~= (sql%([STATIONS_schema, GSOD2023_schema, GSOD2022_schema]) "WITH wa_stations AS (SELECT DISTINCT \"usaf\", \"wban\", \"name\" FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"STATIONS\" WHERE \"state\" = 'WA'), rainy_2023 AS (SELECT g.\"stn\" AS STATION_ID, g.\"wban\" AS WBAN, s.\"name\" AS STATION_NAME, COUNT(*) AS RAINY_DAYS_2023 FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"GSOD2023\" AS g JOIN wa_stations AS s ON g.\"stn\" = s.\"usaf\" AND g.\"wban\" = s.\"wban\" WHERE g.\"prcp\" > 0 AND g.\"prcp\" <> 99.99 GROUP BY g.\"stn\", g.\"wban\", s.\"name\"), rainy_2022 AS (SELECT g.\"stn\" AS STATION_ID, g.\"wban\" AS WBAN, COUNT(*) AS RAINY_DAYS_2022 FROM \"NOAA_DATA\".\"NOAA_GSOD\".\"GSOD2022\" AS g JOIN wa_stations AS s ON g.\"stn\" = s.\"usaf\" AND g.\"wban\" = s.\"wban\" WHERE g.\"prcp\" > 0 AND g.\"prcp\" <> 99.99 GROUP BY g.\"stn\", g.\"wban\") SELECT r23.STATION_ID, r23.STATION_NAME, r23.RAINY_DAYS_2023, r22.RAINY_DAYS_2022 FROM rainy_2023 AS r23 JOIN rainy_2022 AS r22 ON r23.STATION_ID = r22.STATION_ID AND r23.WBAN = r22.WBAN WHERE r23.RAINY_DAYS_2023 > 150 AND r23.RAINY_DAYS_2023 < r22.RAINY_DAYS_2022 ORDER BY r23.RAINY_DAYS_2023 DESC") t := by
  intro t; first | sql_equiv | sorry

end Bench_sf_bq045
