import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_local058 — crossskill equivalence(s)

Question: Can you provide a list of hardware product segments along with their unique product counts for 2020 in the output, ordered by the highest percentage increase in unique fact sales products from 2020 to 2021?

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_local058

CREATE TABLE HARDWARE_DIM_PRODUCT («product_code» STRING, «division» STRING, «segment» STRING, «category» STRING, «product» STRING, «variant» STRING)
CREATE TABLE HARDWARE_FACT_SALES_MONTHLY («date» STRING, «product_code» STRING, «customer_code» INT, «sold_quantity» INT, «fiscal_year» INT)

theorem eq_0_1 : ∀ t,
    (sql%([HARDWARE_DIM_PRODUCT_schema, HARDWARE_FACT_SALES_MONTHLY_schema]) "WITH product_counts AS (SELECT d.\"segment\", f.\"fiscal_year\", COUNT(DISTINCT f.\"product_code\") AS unique_products FROM \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_FACT_SALES_MONTHLY\" AS f JOIN \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_DIM_PRODUCT\" AS d ON f.\"product_code\" = d.\"product_code\" WHERE f.\"fiscal_year\" IN (2020, 2021) GROUP BY d.\"segment\", f.\"fiscal_year\"), pct_change AS (SELECT c2020.\"segment\", c2020.unique_products AS PRODUCT_COUNT_2020, CAST((c2021.unique_products - c2020.unique_products) AS DOUBLE PRECISION) / c2020.unique_products * 100 AS pct_increase FROM product_counts AS c2020 JOIN product_counts AS c2021 ON c2020.\"segment\" = c2021.\"segment\" WHERE c2020.\"fiscal_year\" = 2020 AND c2021.\"fiscal_year\" = 2021) SELECT \"segment\", PRODUCT_COUNT_2020 FROM pct_change ORDER BY pct_increase DESC") t ~= (sql%([HARDWARE_DIM_PRODUCT_schema, HARDWARE_FACT_SALES_MONTHLY_schema]) "SELECT p.\"segment\", COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2020 THEN f.\"product_code\" END) AS PRODUCT_COUNT_2020 FROM \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_FACT_SALES_MONTHLY\" AS f JOIN \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_DIM_PRODUCT\" AS p ON f.\"product_code\" = p.\"product_code\" WHERE f.\"fiscal_year\" IN (2020, 2021) GROUP BY p.\"segment\" ORDER BY CAST((COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2021 THEN f.\"product_code\" END) - COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2020 THEN f.\"product_code\" END)) * 100.0 AS DOUBLE PRECISION) / NULLIF(COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2020 THEN f.\"product_code\" END), 0) DESC") t := by
  intro t; first | sql_equiv | sorry

theorem eq_0_2 : ∀ t,
    (sql%([HARDWARE_DIM_PRODUCT_schema, HARDWARE_FACT_SALES_MONTHLY_schema]) "WITH product_counts AS (SELECT d.\"segment\", f.\"fiscal_year\", COUNT(DISTINCT f.\"product_code\") AS unique_products FROM \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_FACT_SALES_MONTHLY\" AS f JOIN \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_DIM_PRODUCT\" AS d ON f.\"product_code\" = d.\"product_code\" WHERE f.\"fiscal_year\" IN (2020, 2021) GROUP BY d.\"segment\", f.\"fiscal_year\"), pct_change AS (SELECT c2020.\"segment\", c2020.unique_products AS PRODUCT_COUNT_2020, CAST((c2021.unique_products - c2020.unique_products) AS DOUBLE PRECISION) / c2020.unique_products * 100 AS pct_increase FROM product_counts AS c2020 JOIN product_counts AS c2021 ON c2020.\"segment\" = c2021.\"segment\" WHERE c2020.\"fiscal_year\" = 2020 AND c2021.\"fiscal_year\" = 2021) SELECT \"segment\", PRODUCT_COUNT_2020 FROM pct_change ORDER BY pct_increase DESC") t ~= (sql%([HARDWARE_DIM_PRODUCT_schema, HARDWARE_FACT_SALES_MONTHLY_schema]) "WITH product_counts AS (SELECT p.\"segment\", f.\"fiscal_year\", COUNT(DISTINCT f.\"product_code\") AS product_count FROM \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_FACT_SALES_MONTHLY\" AS f JOIN \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_DIM_PRODUCT\" AS p ON f.\"product_code\" = p.\"product_code\" WHERE f.\"fiscal_year\" IN (2020, 2021) GROUP BY p.\"segment\", f.\"fiscal_year\"), pivoted AS (SELECT \"segment\", MAX(CASE WHEN \"fiscal_year\" = 2020 THEN product_count END) AS product_count_2020, MAX(CASE WHEN \"fiscal_year\" = 2021 THEN product_count END) AS product_count_2021 FROM product_counts GROUP BY \"segment\") SELECT \"segment\", product_count_2020 AS \"PRODUCT_COUNT_2020\" FROM pivoted ORDER BY (CAST((product_count_2021 - product_count_2020) * 100.0 AS DOUBLE PRECISION) / product_count_2020) DESC") t := by
  intro t; first | sql_equiv | sorry

theorem eq_0_3 : ∀ t,
    (sql%([HARDWARE_DIM_PRODUCT_schema, HARDWARE_FACT_SALES_MONTHLY_schema]) "WITH product_counts AS (SELECT d.\"segment\", f.\"fiscal_year\", COUNT(DISTINCT f.\"product_code\") AS unique_products FROM \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_FACT_SALES_MONTHLY\" AS f JOIN \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_DIM_PRODUCT\" AS d ON f.\"product_code\" = d.\"product_code\" WHERE f.\"fiscal_year\" IN (2020, 2021) GROUP BY d.\"segment\", f.\"fiscal_year\"), pct_change AS (SELECT c2020.\"segment\", c2020.unique_products AS PRODUCT_COUNT_2020, CAST((c2021.unique_products - c2020.unique_products) AS DOUBLE PRECISION) / c2020.unique_products * 100 AS pct_increase FROM product_counts AS c2020 JOIN product_counts AS c2021 ON c2020.\"segment\" = c2021.\"segment\" WHERE c2020.\"fiscal_year\" = 2020 AND c2021.\"fiscal_year\" = 2021) SELECT \"segment\", PRODUCT_COUNT_2020 FROM pct_change ORDER BY pct_increase DESC") t ~= (sql%([HARDWARE_DIM_PRODUCT_schema, HARDWARE_FACT_SALES_MONTHLY_schema]) "WITH product_counts AS (SELECT p.\"segment\", COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2020 THEN f.\"product_code\" END) AS unique_products_2020, COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2021 THEN f.\"product_code\" END) AS unique_products_2021 FROM \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_FACT_SALES_MONTHLY\" AS f JOIN \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_DIM_PRODUCT\" AS p ON f.\"product_code\" = p.\"product_code\" WHERE f.\"fiscal_year\" IN (2020, 2021) GROUP BY p.\"segment\") SELECT \"segment\", unique_products_2020 FROM product_counts ORDER BY (CAST((unique_products_2021 - unique_products_2020) * 100.0 AS DOUBLE PRECISION) / unique_products_2020) DESC") t := by
  intro t; first | sql_equiv | sorry

theorem eq_1_2 : ∀ t,
    (sql%([HARDWARE_DIM_PRODUCT_schema, HARDWARE_FACT_SALES_MONTHLY_schema]) "SELECT p.\"segment\", COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2020 THEN f.\"product_code\" END) AS PRODUCT_COUNT_2020 FROM \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_FACT_SALES_MONTHLY\" AS f JOIN \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_DIM_PRODUCT\" AS p ON f.\"product_code\" = p.\"product_code\" WHERE f.\"fiscal_year\" IN (2020, 2021) GROUP BY p.\"segment\" ORDER BY CAST((COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2021 THEN f.\"product_code\" END) - COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2020 THEN f.\"product_code\" END)) * 100.0 AS DOUBLE PRECISION) / NULLIF(COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2020 THEN f.\"product_code\" END), 0) DESC") t ~= (sql%([HARDWARE_DIM_PRODUCT_schema, HARDWARE_FACT_SALES_MONTHLY_schema]) "WITH product_counts AS (SELECT p.\"segment\", f.\"fiscal_year\", COUNT(DISTINCT f.\"product_code\") AS product_count FROM \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_FACT_SALES_MONTHLY\" AS f JOIN \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_DIM_PRODUCT\" AS p ON f.\"product_code\" = p.\"product_code\" WHERE f.\"fiscal_year\" IN (2020, 2021) GROUP BY p.\"segment\", f.\"fiscal_year\"), pivoted AS (SELECT \"segment\", MAX(CASE WHEN \"fiscal_year\" = 2020 THEN product_count END) AS product_count_2020, MAX(CASE WHEN \"fiscal_year\" = 2021 THEN product_count END) AS product_count_2021 FROM product_counts GROUP BY \"segment\") SELECT \"segment\", product_count_2020 AS \"PRODUCT_COUNT_2020\" FROM pivoted ORDER BY (CAST((product_count_2021 - product_count_2020) * 100.0 AS DOUBLE PRECISION) / product_count_2020) DESC") t := by
  intro t; first | sql_equiv | sorry

theorem eq_1_3 : ∀ t,
    (sql%([HARDWARE_DIM_PRODUCT_schema, HARDWARE_FACT_SALES_MONTHLY_schema]) "SELECT p.\"segment\", COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2020 THEN f.\"product_code\" END) AS PRODUCT_COUNT_2020 FROM \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_FACT_SALES_MONTHLY\" AS f JOIN \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_DIM_PRODUCT\" AS p ON f.\"product_code\" = p.\"product_code\" WHERE f.\"fiscal_year\" IN (2020, 2021) GROUP BY p.\"segment\" ORDER BY CAST((COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2021 THEN f.\"product_code\" END) - COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2020 THEN f.\"product_code\" END)) * 100.0 AS DOUBLE PRECISION) / NULLIF(COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2020 THEN f.\"product_code\" END), 0) DESC") t ~= (sql%([HARDWARE_DIM_PRODUCT_schema, HARDWARE_FACT_SALES_MONTHLY_schema]) "WITH product_counts AS (SELECT p.\"segment\", COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2020 THEN f.\"product_code\" END) AS unique_products_2020, COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2021 THEN f.\"product_code\" END) AS unique_products_2021 FROM \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_FACT_SALES_MONTHLY\" AS f JOIN \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_DIM_PRODUCT\" AS p ON f.\"product_code\" = p.\"product_code\" WHERE f.\"fiscal_year\" IN (2020, 2021) GROUP BY p.\"segment\") SELECT \"segment\", unique_products_2020 FROM product_counts ORDER BY (CAST((unique_products_2021 - unique_products_2020) * 100.0 AS DOUBLE PRECISION) / unique_products_2020) DESC") t := by
  intro t; first | sql_equiv | sorry

theorem eq_2_3 : ∀ t,
    (sql%([HARDWARE_DIM_PRODUCT_schema, HARDWARE_FACT_SALES_MONTHLY_schema]) "WITH product_counts AS (SELECT p.\"segment\", f.\"fiscal_year\", COUNT(DISTINCT f.\"product_code\") AS product_count FROM \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_FACT_SALES_MONTHLY\" AS f JOIN \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_DIM_PRODUCT\" AS p ON f.\"product_code\" = p.\"product_code\" WHERE f.\"fiscal_year\" IN (2020, 2021) GROUP BY p.\"segment\", f.\"fiscal_year\"), pivoted AS (SELECT \"segment\", MAX(CASE WHEN \"fiscal_year\" = 2020 THEN product_count END) AS product_count_2020, MAX(CASE WHEN \"fiscal_year\" = 2021 THEN product_count END) AS product_count_2021 FROM product_counts GROUP BY \"segment\") SELECT \"segment\", product_count_2020 AS \"PRODUCT_COUNT_2020\" FROM pivoted ORDER BY (CAST((product_count_2021 - product_count_2020) * 100.0 AS DOUBLE PRECISION) / product_count_2020) DESC") t ~= (sql%([HARDWARE_DIM_PRODUCT_schema, HARDWARE_FACT_SALES_MONTHLY_schema]) "WITH product_counts AS (SELECT p.\"segment\", COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2020 THEN f.\"product_code\" END) AS unique_products_2020, COUNT(DISTINCT CASE WHEN f.\"fiscal_year\" = 2021 THEN f.\"product_code\" END) AS unique_products_2021 FROM \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_FACT_SALES_MONTHLY\" AS f JOIN \"EDUCATION_BUSINESS\".\"EDUCATION_BUSINESS\".\"HARDWARE_DIM_PRODUCT\" AS p ON f.\"product_code\" = p.\"product_code\" WHERE f.\"fiscal_year\" IN (2020, 2021) GROUP BY p.\"segment\") SELECT \"segment\", unique_products_2020 FROM product_counts ORDER BY (CAST((unique_products_2021 - unique_products_2020) * 100.0 AS DOUBLE PRECISION) / unique_products_2020) DESC") t := by
  intro t; first | sql_equiv | sorry

end Bench_sf_local058
