import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_ga031 — crossskill equivalence(s)

Question: I want to know the user session conversion rate on January 2nd, 2021, using only 'page_view' events. The conversion rate should be calculated as the percentage of user visits that reached both the Home and Checkout Confirmation pages in one session, relative to those that landed on the Home page.

NOTE: uses WITH RECURSIVE / LATERAL / FLATTEN — may not elaborate yet.

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_ga031

CREATE TABLE EVENTS_20210102 («EVENT_DATE» STRING, «EVENT_TIMESTAMP» INT, «EVENT_NAME» STRING, «EVENT_PARAMS» STRING, «EVENT_PREVIOUS_TIMESTAMP» INT, «EVENT_VALUE_IN_USD» FLOAT, «EVENT_BUNDLE_SEQUENCE_ID» INT, «EVENT_SERVER_TIMESTAMP_OFFSET» INT, «USER_ID» STRING, «USER_PSEUDO_ID» STRING, «PRIVACY_INFO» STRING, «USER_PROPERTIES» STRING, «USER_FIRST_TOUCH_TIMESTAMP» INT, «USER_LTV» STRING, «DEVICE» STRING, «GEO» STRING, «APP_INFO» STRING, «TRAFFIC_SOURCE» STRING, «STREAM_ID» INT, «PLATFORM» STRING, «EVENT_DIMENSIONS» STRING, «ECOMMERCE» STRING, «ITEMS» STRING)

HYPOTHESIS hyp0_1_0 : EVENTS_20210102 "\"EVENT_NAME\" = 'page_view'"
HYPOTHESIS hyp0_1_1 : EVENTS_20210102 "e.EVENT_NAME = 'page_view'"
HYPOTHESIS hyp0_1_2 : EVENTS_20210102 "\"USER_PSEUDO_ID\" = e.USER_PSEUDO_ID"
theorem eq_0_1 (t : TableRel EVENTS_20210102_schema) (h0 : hyp0_1_0 t) (h1 : hyp0_1_1 t) (h2 : hyp0_1_2 t) :
    (sql%([EVENTS_20210102_schema]) "WITH event_data AS (\n  SELECT \n    e.\"USER_PSEUDO_ID\",\n    e.\"EVENT_TIMESTAMP\",\n    MAX(CASE WHEN f.value:key::STRING = 'ga_session_id' THEN f.value:value:int_value::STRING END) AS session_id,\n    MAX(CASE WHEN f.value:key::STRING = 'page_title' THEN f.value:value:string_value::STRING END) AS page_title,\n    MAX(CASE WHEN f.value:key::STRING = 'entrances' THEN f.value:value:int_value END) AS entrances\n  FROM \"GA4\".\"GA4_OBFUSCATED_SAMPLE_ECOMMERCE\".\"EVENTS_20210102\" e,\n  LATERAL FLATTEN(input => e.\"EVENT_PARAMS\") f\n  WHERE e.\"EVENT_NAME\" = 'page_view'\n  GROUP BY e.\"USER_PSEUDO_ID\", e.\"EVENT_TIMESTAMP\"\n),\nsession_summary AS (\n  SELECT \n    USER_PSEUDO_ID,\n    session_id,\n    MAX(CASE WHEN entrances = 1 AND page_title = 'Home' THEN 1 ELSE 0 END) AS landed_on_home,\n    MAX(CASE WHEN page_title = 'Home' THEN 1 ELSE 0 END) AS has_home,\n    MAX(CASE WHEN page_title = 'Checkout Confirmation' THEN 1 ELSE 0 END) AS has_checkout\n  FROM event_data\n  GROUP BY USER_PSEUDO_ID, session_id\n)\nSELECT \n  ROUND(100.0 * SUM(CASE WHEN landed_on_home = 1 AND has_home = 1 AND has_checkout = 1 THEN 1 ELSE 0 END) \n    / NULLIF(SUM(landed_on_home), 0), 6) AS CONVERSION_RATE\nFROM session_summary;") t ~= (sql%([EVENTS_20210102_schema]) "WITH page_views AS (\n  SELECT \n    e.USER_PSEUDO_ID,\n    MAX(CASE WHEN ep.VALUE:key::STRING = 'ga_session_id' THEN ep.VALUE:value:int_value::STRING END) AS ga_session_id,\n    MAX(CASE WHEN ep.VALUE:key::STRING = 'page_title' THEN ep.VALUE:value:string_value::STRING END) AS page_title,\n    MAX(CASE WHEN ep.VALUE:key::STRING = 'entrances' THEN ep.VALUE:value:int_value::INTEGER END) AS entrances\n  FROM \"GA4\".\"GA4_OBFUSCATED_SAMPLE_ECOMMERCE\".\"EVENTS_20210102\" e,\n  LATERAL FLATTEN(input => e.EVENT_PARAMS) ep\n  WHERE e.EVENT_NAME = 'page_view'\n  GROUP BY e.USER_PSEUDO_ID, e.EVENT_TIMESTAMP, e.EVENT_PARAMS\n),\nsession_pages AS (\n  SELECT \n    USER_PSEUDO_ID,\n    ga_session_id,\n    MAX(CASE WHEN page_title = 'Home' THEN 1 ELSE 0 END) AS has_home,\n    MAX(CASE WHEN page_title = 'Checkout Confirmation' THEN 1 ELSE 0 END) AS has_checkout,\n    MAX(CASE WHEN page_title = 'Home' AND entrances = 1 THEN 1 ELSE 0 END) AS landed_home\n  FROM page_views\n  GROUP BY USER_PSEUDO_ID, ga_session_id\n)\nSELECT \n  ROUND(\n    SUM(CASE WHEN landed_home = 1 AND has_home = 1 AND has_checkout = 1 THEN 1 ELSE 0 END) * 100.0 \n    / NULLIF(SUM(landed_home), 0),\n    6\n  ) AS CONVERSION_RATE\nFROM session_pages;") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp0_2_0 : EVENTS_20210102 "\"EVENT_NAME\" = 'page_view'"
HYPOTHESIS hyp0_2_1 : EVENTS_20210102 "e.EVENT_NAME = 'page_view'"
HYPOTHESIS hyp0_2_2 : EVENTS_20210102 "\"USER_PSEUDO_ID\" = e.USER_PSEUDO_ID"
HYPOTHESIS hyp0_2_3 : EVENTS_20210102 "\"EVENT_TIMESTAMP\" = e.EVENT_TIMESTAMP"
theorem eq_0_2 (t : TableRel EVENTS_20210102_schema) (h0 : hyp0_2_0 t) (h1 : hyp0_2_1 t) (h2 : hyp0_2_2 t) (h3 : hyp0_2_3 t) :
    (sql%([EVENTS_20210102_schema]) "WITH event_data AS (\n  SELECT \n    e.\"USER_PSEUDO_ID\",\n    e.\"EVENT_TIMESTAMP\",\n    MAX(CASE WHEN f.value:key::STRING = 'ga_session_id' THEN f.value:value:int_value::STRING END) AS session_id,\n    MAX(CASE WHEN f.value:key::STRING = 'page_title' THEN f.value:value:string_value::STRING END) AS page_title,\n    MAX(CASE WHEN f.value:key::STRING = 'entrances' THEN f.value:value:int_value END) AS entrances\n  FROM \"GA4\".\"GA4_OBFUSCATED_SAMPLE_ECOMMERCE\".\"EVENTS_20210102\" e,\n  LATERAL FLATTEN(input => e.\"EVENT_PARAMS\") f\n  WHERE e.\"EVENT_NAME\" = 'page_view'\n  GROUP BY e.\"USER_PSEUDO_ID\", e.\"EVENT_TIMESTAMP\"\n),\nsession_summary AS (\n  SELECT \n    USER_PSEUDO_ID,\n    session_id,\n    MAX(CASE WHEN entrances = 1 AND page_title = 'Home' THEN 1 ELSE 0 END) AS landed_on_home,\n    MAX(CASE WHEN page_title = 'Home' THEN 1 ELSE 0 END) AS has_home,\n    MAX(CASE WHEN page_title = 'Checkout Confirmation' THEN 1 ELSE 0 END) AS has_checkout\n  FROM event_data\n  GROUP BY USER_PSEUDO_ID, session_id\n)\nSELECT \n  ROUND(100.0 * SUM(CASE WHEN landed_on_home = 1 AND has_home = 1 AND has_checkout = 1 THEN 1 ELSE 0 END) \n    / NULLIF(SUM(landed_on_home), 0), 6) AS CONVERSION_RATE\nFROM session_summary;") t ~= (sql%([EVENTS_20210102_schema]) "WITH page_views AS (\n  SELECT\n    e.USER_PSEUDO_ID,\n    e.EVENT_TIMESTAMP,\n    MAX(CASE WHEN ep.value:key::STRING = 'ga_session_id' THEN ep.value:value:int_value::INTEGER END) AS ga_session_id,\n    MAX(CASE WHEN ep.value:key::STRING = 'page_title' THEN ep.value:value:string_value::STRING END) AS page_title,\n    MAX(CASE WHEN ep.value:key::STRING = 'entrances' THEN ep.value:value:int_value::INTEGER END) AS entrances\n  FROM \"GA4\".\"GA4_OBFUSCATED_SAMPLE_ECOMMERCE\".\"EVENTS_20210102\" e,\n       LATERAL FLATTEN(input => e.EVENT_PARAMS) ep\n  WHERE e.EVENT_NAME = 'page_view'\n  GROUP BY e.USER_PSEUDO_ID, e.EVENT_TIMESTAMP\n),\nhome_landing_sessions AS (\n  SELECT DISTINCT USER_PSEUDO_ID, ga_session_id\n  FROM page_views\n  WHERE page_title = 'Home' AND entrances = 1\n),\nsession_checkout AS (\n  SELECT DISTINCT USER_PSEUDO_ID, ga_session_id\n  FROM page_views\n  WHERE page_title = 'Checkout Confirmation'\n)\nSELECT\n  100.0 * \n    (SELECT COUNT(*) FROM home_landing_sessions h \n     INNER JOIN session_checkout c \n       ON h.USER_PSEUDO_ID = c.USER_PSEUDO_ID AND h.ga_session_id = c.ga_session_id)\n  / NULLIF((SELECT COUNT(*) FROM home_landing_sessions), 0) AS \"CONVERSION_RATE\";") t := by
  first | sql_equiv | sorry

theorem eq_1_2 : ∀ t,
    (sql%([EVENTS_20210102_schema]) "WITH page_views AS (\n  SELECT \n    e.USER_PSEUDO_ID,\n    MAX(CASE WHEN ep.VALUE:key::STRING = 'ga_session_id' THEN ep.VALUE:value:int_value::STRING END) AS ga_session_id,\n    MAX(CASE WHEN ep.VALUE:key::STRING = 'page_title' THEN ep.VALUE:value:string_value::STRING END) AS page_title,\n    MAX(CASE WHEN ep.VALUE:key::STRING = 'entrances' THEN ep.VALUE:value:int_value::INTEGER END) AS entrances\n  FROM \"GA4\".\"GA4_OBFUSCATED_SAMPLE_ECOMMERCE\".\"EVENTS_20210102\" e,\n  LATERAL FLATTEN(input => e.EVENT_PARAMS) ep\n  WHERE e.EVENT_NAME = 'page_view'\n  GROUP BY e.USER_PSEUDO_ID, e.EVENT_TIMESTAMP, e.EVENT_PARAMS\n),\nsession_pages AS (\n  SELECT \n    USER_PSEUDO_ID,\n    ga_session_id,\n    MAX(CASE WHEN page_title = 'Home' THEN 1 ELSE 0 END) AS has_home,\n    MAX(CASE WHEN page_title = 'Checkout Confirmation' THEN 1 ELSE 0 END) AS has_checkout,\n    MAX(CASE WHEN page_title = 'Home' AND entrances = 1 THEN 1 ELSE 0 END) AS landed_home\n  FROM page_views\n  GROUP BY USER_PSEUDO_ID, ga_session_id\n)\nSELECT \n  ROUND(\n    SUM(CASE WHEN landed_home = 1 AND has_home = 1 AND has_checkout = 1 THEN 1 ELSE 0 END) * 100.0 \n    / NULLIF(SUM(landed_home), 0),\n    6\n  ) AS CONVERSION_RATE\nFROM session_pages;") t ~= (sql%([EVENTS_20210102_schema]) "WITH page_views AS (\n  SELECT\n    e.USER_PSEUDO_ID,\n    e.EVENT_TIMESTAMP,\n    MAX(CASE WHEN ep.value:key::STRING = 'ga_session_id' THEN ep.value:value:int_value::INTEGER END) AS ga_session_id,\n    MAX(CASE WHEN ep.value:key::STRING = 'page_title' THEN ep.value:value:string_value::STRING END) AS page_title,\n    MAX(CASE WHEN ep.value:key::STRING = 'entrances' THEN ep.value:value:int_value::INTEGER END) AS entrances\n  FROM \"GA4\".\"GA4_OBFUSCATED_SAMPLE_ECOMMERCE\".\"EVENTS_20210102\" e,\n       LATERAL FLATTEN(input => e.EVENT_PARAMS) ep\n  WHERE e.EVENT_NAME = 'page_view'\n  GROUP BY e.USER_PSEUDO_ID, e.EVENT_TIMESTAMP\n),\nhome_landing_sessions AS (\n  SELECT DISTINCT USER_PSEUDO_ID, ga_session_id\n  FROM page_views\n  WHERE page_title = 'Home' AND entrances = 1\n),\nsession_checkout AS (\n  SELECT DISTINCT USER_PSEUDO_ID, ga_session_id\n  FROM page_views\n  WHERE page_title = 'Checkout Confirmation'\n)\nSELECT\n  100.0 * \n    (SELECT COUNT(*) FROM home_landing_sessions h \n     INNER JOIN session_checkout c \n       ON h.USER_PSEUDO_ID = c.USER_PSEUDO_ID AND h.ga_session_id = c.ga_session_id)\n  / NULLIF((SELECT COUNT(*) FROM home_landing_sessions), 0) AS \"CONVERSION_RATE\";") t := by
  intro t; first | sql_equiv | sorry

end Bench_sf_ga031
