import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_bq402 — crossskill equivalence(s)

Question: Calculate the conversion rate from unique visitors to purchasers by using data exclusively from the `web_analytics` table in the `data-to-insights.ecommerce` dataset. A visitor is defined as a unique `fullVisitorId` present in the table, while a purchaser is a visitor who has at least one transaction recorded (`totals.transactions` is not null). The conversion rate is computed by dividing the number of unique purchasers by the total number of unique visitors. Additionally, calculate the average number of transactions per purchaser, considering only those visitors who have made at least one transaction.

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_bq402

CREATE TABLE WEB_ANALYTICS («visitorId» INT, «visitNumber» INT, «visitId» INT, «visitStartTime» INT, «date» STRING, «totals» STRING, «trafficSource» STRING, «device» STRING, «geoNetwork» STRING, «customDimensions» STRING, «hits» STRING, «fullVisitorId» STRING, «userId» STRING, «channelGrouping» STRING, «socialEngagementType» STRING)

theorem eq_0_1 :
    sql%([WEB_ANALYTICS_schema]) "SELECT\n  COUNT(DISTINCT \"fullVisitorId\") AS TOTAL_UNIQUE_VISITORS,\n  COUNT(DISTINCT CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"fullVisitorId\" END) AS UNIQUE_PURCHASERS,\n  SUM(CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"totals\":\"transactions\"::INT ELSE 0 END) AS TOTAL_TRANSACTIONS,\n  ROUND(\n    COUNT(DISTINCT CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"fullVisitorId\" END)::FLOAT\n    / COUNT(DISTINCT \"fullVisitorId\")::FLOAT * 100,\n    1\n  ) AS CONVERSION_RATE_PERCENTAGE,\n  ROUND(\n    SUM(CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"totals\":\"transactions\"::INT ELSE 0 END)::FLOAT\n    / COUNT(DISTINCT CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"fullVisitorId\" END)::FLOAT,\n    2\n  ) AS AVG_TRANSACTIONS_PER_PURCHASER\nFROM \"ECOMMERCE\".\"ECOMMERCE\".\"WEB_ANALYTICS\";" = sql%([WEB_ANALYTICS_schema]) "SELECT \n  COUNT(DISTINCT \"fullVisitorId\") AS TOTAL_UNIQUE_VISITORS,\n  COUNT(DISTINCT CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"fullVisitorId\" END) AS UNIQUE_PURCHASERS,\n  SUM(CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"totals\":\"transactions\"::INT ELSE 0 END) AS TOTAL_TRANSACTIONS,\n  ROUND(\n    COUNT(DISTINCT CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"fullVisitorId\" END) * 100.0\n    / COUNT(DISTINCT \"fullVisitorId\"),\n    1\n  ) AS CONVERSION_RATE_PERCENTAGE,\n  ROUND(\n    SUM(CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"totals\":\"transactions\"::INT ELSE 0 END) * 1.0\n    / NULLIF(COUNT(DISTINCT CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"fullVisitorId\" END), 0),\n    2\n  ) AS AVG_TRANSACTIONS_PER_PURCHASER\nFROM \"ECOMMERCE\".\"ECOMMERCE\".\"WEB_ANALYTICS\";" := by
  first | sql_equiv | sorry

theorem eq_0_2 :
    sql%([WEB_ANALYTICS_schema]) "SELECT\n  COUNT(DISTINCT \"fullVisitorId\") AS TOTAL_UNIQUE_VISITORS,\n  COUNT(DISTINCT CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"fullVisitorId\" END) AS UNIQUE_PURCHASERS,\n  SUM(CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"totals\":\"transactions\"::INT ELSE 0 END) AS TOTAL_TRANSACTIONS,\n  ROUND(\n    COUNT(DISTINCT CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"fullVisitorId\" END)::FLOAT\n    / COUNT(DISTINCT \"fullVisitorId\")::FLOAT * 100,\n    1\n  ) AS CONVERSION_RATE_PERCENTAGE,\n  ROUND(\n    SUM(CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"totals\":\"transactions\"::INT ELSE 0 END)::FLOAT\n    / COUNT(DISTINCT CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"fullVisitorId\" END)::FLOAT,\n    2\n  ) AS AVG_TRANSACTIONS_PER_PURCHASER\nFROM \"ECOMMERCE\".\"ECOMMERCE\".\"WEB_ANALYTICS\";" = sql%([WEB_ANALYTICS_schema]) "SELECT\n    COUNT(DISTINCT \"fullVisitorId\") AS \"TOTAL_UNIQUE_VISITORS\",\n    COUNT(DISTINCT CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"fullVisitorId\" END) AS \"UNIQUE_PURCHASERS\",\n    SUM(CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"totals\":\"transactions\"::INT ELSE 0 END) AS \"TOTAL_TRANSACTIONS\",\n    ROUND(\n        COUNT(DISTINCT CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"fullVisitorId\" END) * 100.0\n        / COUNT(DISTINCT \"fullVisitorId\"),\n        2\n    ) AS \"CONVERSION_RATE_PERCENTAGE\",\n    ROUND(\n        SUM(CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"totals\":\"transactions\"::INT ELSE 0 END) * 1.0\n        / COUNT(DISTINCT CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"fullVisitorId\" END),\n        2\n    ) AS \"AVG_TRANSACTIONS_PER_PURCHASER\"\nFROM \"ECOMMERCE\".\"ECOMMERCE\".\"WEB_ANALYTICS\";" := by
  first | sql_equiv | sorry

theorem eq_0_3 :
    sql%([WEB_ANALYTICS_schema]) "SELECT\n  COUNT(DISTINCT \"fullVisitorId\") AS TOTAL_UNIQUE_VISITORS,\n  COUNT(DISTINCT CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"fullVisitorId\" END) AS UNIQUE_PURCHASERS,\n  SUM(CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"totals\":\"transactions\"::INT ELSE 0 END) AS TOTAL_TRANSACTIONS,\n  ROUND(\n    COUNT(DISTINCT CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"fullVisitorId\" END)::FLOAT\n    / COUNT(DISTINCT \"fullVisitorId\")::FLOAT * 100,\n    1\n  ) AS CONVERSION_RATE_PERCENTAGE,\n  ROUND(\n    SUM(CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"totals\":\"transactions\"::INT ELSE 0 END)::FLOAT\n    / COUNT(DISTINCT CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"fullVisitorId\" END)::FLOAT,\n    2\n  ) AS AVG_TRANSACTIONS_PER_PURCHASER\nFROM \"ECOMMERCE\".\"ECOMMERCE\".\"WEB_ANALYTICS\";" = sql%([WEB_ANALYTICS_schema]) "SELECT\n  COUNT(DISTINCT \"fullVisitorId\") AS TOTAL_UNIQUE_VISITORS,\n  COUNT(DISTINCT CASE WHEN \"totals\":transactions IS NOT NULL THEN \"fullVisitorId\" END) AS UNIQUE_PURCHASERS,\n  SUM(CASE WHEN \"totals\":transactions IS NOT NULL THEN \"totals\":transactions::INT ELSE 0 END) AS TOTAL_TRANSACTIONS,\n  ROUND(\n    COUNT(DISTINCT CASE WHEN \"totals\":transactions IS NOT NULL THEN \"fullVisitorId\" END) * 100.0\n    / COUNT(DISTINCT \"fullVisitorId\"),\n    1\n  ) AS CONVERSION_RATE_PERCENTAGE,\n  ROUND(\n    SUM(CASE WHEN \"totals\":transactions IS NOT NULL THEN \"totals\":transactions::INT ELSE 0 END) * 1.0\n    / COUNT(DISTINCT CASE WHEN \"totals\":transactions IS NOT NULL THEN \"fullVisitorId\" END),\n    2\n  ) AS AVG_TRANSACTIONS_PER_PURCHASER\nFROM \"ECOMMERCE\".\"ECOMMERCE\".\"WEB_ANALYTICS\";" := by
  first | sql_equiv | sorry

theorem eq_1_2 :
    sql%([WEB_ANALYTICS_schema]) "SELECT \n  COUNT(DISTINCT \"fullVisitorId\") AS TOTAL_UNIQUE_VISITORS,\n  COUNT(DISTINCT CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"fullVisitorId\" END) AS UNIQUE_PURCHASERS,\n  SUM(CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"totals\":\"transactions\"::INT ELSE 0 END) AS TOTAL_TRANSACTIONS,\n  ROUND(\n    COUNT(DISTINCT CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"fullVisitorId\" END) * 100.0\n    / COUNT(DISTINCT \"fullVisitorId\"),\n    1\n  ) AS CONVERSION_RATE_PERCENTAGE,\n  ROUND(\n    SUM(CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"totals\":\"transactions\"::INT ELSE 0 END) * 1.0\n    / NULLIF(COUNT(DISTINCT CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"fullVisitorId\" END), 0),\n    2\n  ) AS AVG_TRANSACTIONS_PER_PURCHASER\nFROM \"ECOMMERCE\".\"ECOMMERCE\".\"WEB_ANALYTICS\";" = sql%([WEB_ANALYTICS_schema]) "SELECT\n    COUNT(DISTINCT \"fullVisitorId\") AS \"TOTAL_UNIQUE_VISITORS\",\n    COUNT(DISTINCT CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"fullVisitorId\" END) AS \"UNIQUE_PURCHASERS\",\n    SUM(CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"totals\":\"transactions\"::INT ELSE 0 END) AS \"TOTAL_TRANSACTIONS\",\n    ROUND(\n        COUNT(DISTINCT CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"fullVisitorId\" END) * 100.0\n        / COUNT(DISTINCT \"fullVisitorId\"),\n        2\n    ) AS \"CONVERSION_RATE_PERCENTAGE\",\n    ROUND(\n        SUM(CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"totals\":\"transactions\"::INT ELSE 0 END) * 1.0\n        / COUNT(DISTINCT CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"fullVisitorId\" END),\n        2\n    ) AS \"AVG_TRANSACTIONS_PER_PURCHASER\"\nFROM \"ECOMMERCE\".\"ECOMMERCE\".\"WEB_ANALYTICS\";" := by
  first | sql_equiv | sorry

theorem eq_1_3 :
    sql%([WEB_ANALYTICS_schema]) "SELECT \n  COUNT(DISTINCT \"fullVisitorId\") AS TOTAL_UNIQUE_VISITORS,\n  COUNT(DISTINCT CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"fullVisitorId\" END) AS UNIQUE_PURCHASERS,\n  SUM(CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"totals\":\"transactions\"::INT ELSE 0 END) AS TOTAL_TRANSACTIONS,\n  ROUND(\n    COUNT(DISTINCT CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"fullVisitorId\" END) * 100.0\n    / COUNT(DISTINCT \"fullVisitorId\"),\n    1\n  ) AS CONVERSION_RATE_PERCENTAGE,\n  ROUND(\n    SUM(CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"totals\":\"transactions\"::INT ELSE 0 END) * 1.0\n    / NULLIF(COUNT(DISTINCT CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"fullVisitorId\" END), 0),\n    2\n  ) AS AVG_TRANSACTIONS_PER_PURCHASER\nFROM \"ECOMMERCE\".\"ECOMMERCE\".\"WEB_ANALYTICS\";" = sql%([WEB_ANALYTICS_schema]) "SELECT\n  COUNT(DISTINCT \"fullVisitorId\") AS TOTAL_UNIQUE_VISITORS,\n  COUNT(DISTINCT CASE WHEN \"totals\":transactions IS NOT NULL THEN \"fullVisitorId\" END) AS UNIQUE_PURCHASERS,\n  SUM(CASE WHEN \"totals\":transactions IS NOT NULL THEN \"totals\":transactions::INT ELSE 0 END) AS TOTAL_TRANSACTIONS,\n  ROUND(\n    COUNT(DISTINCT CASE WHEN \"totals\":transactions IS NOT NULL THEN \"fullVisitorId\" END) * 100.0\n    / COUNT(DISTINCT \"fullVisitorId\"),\n    1\n  ) AS CONVERSION_RATE_PERCENTAGE,\n  ROUND(\n    SUM(CASE WHEN \"totals\":transactions IS NOT NULL THEN \"totals\":transactions::INT ELSE 0 END) * 1.0\n    / COUNT(DISTINCT CASE WHEN \"totals\":transactions IS NOT NULL THEN \"fullVisitorId\" END),\n    2\n  ) AS AVG_TRANSACTIONS_PER_PURCHASER\nFROM \"ECOMMERCE\".\"ECOMMERCE\".\"WEB_ANALYTICS\";" := by
  first | sql_equiv | sorry

theorem eq_2_3 :
    sql%([WEB_ANALYTICS_schema]) "SELECT\n    COUNT(DISTINCT \"fullVisitorId\") AS \"TOTAL_UNIQUE_VISITORS\",\n    COUNT(DISTINCT CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"fullVisitorId\" END) AS \"UNIQUE_PURCHASERS\",\n    SUM(CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"totals\":\"transactions\"::INT ELSE 0 END) AS \"TOTAL_TRANSACTIONS\",\n    ROUND(\n        COUNT(DISTINCT CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"fullVisitorId\" END) * 100.0\n        / COUNT(DISTINCT \"fullVisitorId\"),\n        2\n    ) AS \"CONVERSION_RATE_PERCENTAGE\",\n    ROUND(\n        SUM(CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"totals\":\"transactions\"::INT ELSE 0 END) * 1.0\n        / COUNT(DISTINCT CASE WHEN \"totals\":\"transactions\" IS NOT NULL THEN \"fullVisitorId\" END),\n        2\n    ) AS \"AVG_TRANSACTIONS_PER_PURCHASER\"\nFROM \"ECOMMERCE\".\"ECOMMERCE\".\"WEB_ANALYTICS\";" = sql%([WEB_ANALYTICS_schema]) "SELECT\n  COUNT(DISTINCT \"fullVisitorId\") AS TOTAL_UNIQUE_VISITORS,\n  COUNT(DISTINCT CASE WHEN \"totals\":transactions IS NOT NULL THEN \"fullVisitorId\" END) AS UNIQUE_PURCHASERS,\n  SUM(CASE WHEN \"totals\":transactions IS NOT NULL THEN \"totals\":transactions::INT ELSE 0 END) AS TOTAL_TRANSACTIONS,\n  ROUND(\n    COUNT(DISTINCT CASE WHEN \"totals\":transactions IS NOT NULL THEN \"fullVisitorId\" END) * 100.0\n    / COUNT(DISTINCT \"fullVisitorId\"),\n    1\n  ) AS CONVERSION_RATE_PERCENTAGE,\n  ROUND(\n    SUM(CASE WHEN \"totals\":transactions IS NOT NULL THEN \"totals\":transactions::INT ELSE 0 END) * 1.0\n    / COUNT(DISTINCT CASE WHEN \"totals\":transactions IS NOT NULL THEN \"fullVisitorId\" END),\n    2\n  ) AS AVG_TRANSACTIONS_PER_PURCHASER\nFROM \"ECOMMERCE\".\"ECOMMERCE\".\"WEB_ANALYTICS\";" := by
  first | sql_equiv | sorry

end Bench_sf_bq402
