import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_bq198 — crossskill equivalence(s)

Question: List the top 5 universities with the most seasons where they achieved the maximum wins in their respective NCAA basketball seasons between 1900-2000, showing each team's total number of such peak-performance seasons, while excluding entries with missing team names.

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_bq198

CREATE TABLE MBB_HISTORICAL_TEAMS_SEASONS («season» INT, «market» STRING, «name» STRING, «team_code» INT, «team_id» STRING, «alias» STRING, «division» INT, «current_division» STRING, «wins» INT, «losses» INT, «ties» INT)

theorem eq_0_1 :
    sql%([MBB_HISTORICAL_TEAMS_SEASONS_schema]) "WITH max_wins_per_season AS (\n  SELECT \"season\", MAX(\"wins\") AS max_wins\n  FROM \"NCAA_BASKETBALL\".\"NCAA_BASKETBALL\".\"MBB_HISTORICAL_TEAMS_SEASONS\"\n  WHERE \"season\" BETWEEN 1900 AND 2000\n  GROUP BY \"season\"\n),\nteams_with_max_wins AS (\n  SELECT t.\"market\" AS TEAM_NAME, t.\"season\"\n  FROM \"NCAA_BASKETBALL\".\"NCAA_BASKETBALL\".\"MBB_HISTORICAL_TEAMS_SEASONS\" t\n  JOIN max_wins_per_season m\n    ON t.\"season\" = m.\"season\" AND t.\"wins\" = m.max_wins\n  WHERE t.\"market\" IS NOT NULL\n)\nSELECT TEAM_NAME, COUNT(*) AS TOP_PERFORMER_COUNT\nFROM teams_with_max_wins\nGROUP BY TEAM_NAME\nORDER BY TOP_PERFORMER_COUNT DESC, TEAM_NAME ASC\nLIMIT 5;" = sql%([MBB_HISTORICAL_TEAMS_SEASONS_schema]) "WITH season_max AS (\n  SELECT \"season\", MAX(\"wins\") AS max_wins\n  FROM \"NCAA_BASKETBALL\".\"NCAA_BASKETBALL\".\"MBB_HISTORICAL_TEAMS_SEASONS\"\n  WHERE \"season\" BETWEEN 1900 AND 2000\n  GROUP BY \"season\"\n),\npeak_teams AS (\n  SELECT t.\"market\" AS TEAM_NAME, t.\"season\"\n  FROM \"NCAA_BASKETBALL\".\"NCAA_BASKETBALL\".\"MBB_HISTORICAL_TEAMS_SEASONS\" t\n  INNER JOIN season_max s\n    ON t.\"season\" = s.\"season\"\n    AND t.\"wins\" = s.max_wins\n  WHERE t.\"season\" BETWEEN 1900 AND 2000\n    AND t.\"name\" IS NOT NULL\n)\nSELECT TEAM_NAME, COUNT(*) AS TOP_PERFORMER_COUNT\nFROM peak_teams\nGROUP BY TEAM_NAME\nORDER BY TOP_PERFORMER_COUNT DESC, TEAM_NAME ASC\nLIMIT 5;" := by
  first | sql_equiv | sorry

theorem eq_0_2 :
    sql%([MBB_HISTORICAL_TEAMS_SEASONS_schema]) "WITH max_wins_per_season AS (\n  SELECT \"season\", MAX(\"wins\") AS max_wins\n  FROM \"NCAA_BASKETBALL\".\"NCAA_BASKETBALL\".\"MBB_HISTORICAL_TEAMS_SEASONS\"\n  WHERE \"season\" BETWEEN 1900 AND 2000\n  GROUP BY \"season\"\n),\nteams_with_max_wins AS (\n  SELECT t.\"market\" AS TEAM_NAME, t.\"season\"\n  FROM \"NCAA_BASKETBALL\".\"NCAA_BASKETBALL\".\"MBB_HISTORICAL_TEAMS_SEASONS\" t\n  JOIN max_wins_per_season m\n    ON t.\"season\" = m.\"season\" AND t.\"wins\" = m.max_wins\n  WHERE t.\"market\" IS NOT NULL\n)\nSELECT TEAM_NAME, COUNT(*) AS TOP_PERFORMER_COUNT\nFROM teams_with_max_wins\nGROUP BY TEAM_NAME\nORDER BY TOP_PERFORMER_COUNT DESC, TEAM_NAME ASC\nLIMIT 5;" = sql%([MBB_HISTORICAL_TEAMS_SEASONS_schema]) "WITH season_max AS (\n    SELECT\n        \"season\",\n        MAX(\"wins\") AS max_wins\n    FROM \"NCAA_BASKETBALL\".\"NCAA_BASKETBALL\".\"MBB_HISTORICAL_TEAMS_SEASONS\"\n    WHERE \"season\" BETWEEN 1900 AND 2000\n    GROUP BY \"season\"\n),\npeak_teams AS (\n    SELECT\n        t.\"market\" AS TEAM_NAME,\n        t.\"season\"\n    FROM \"NCAA_BASKETBALL\".\"NCAA_BASKETBALL\".\"MBB_HISTORICAL_TEAMS_SEASONS\" t\n    JOIN season_max sm\n        ON t.\"season\" = sm.\"season\"\n        AND t.\"wins\" = sm.max_wins\n    WHERE t.\"season\" BETWEEN 1900 AND 2000\n      AND t.\"market\" IS NOT NULL\n)\nSELECT\n    TEAM_NAME,\n    COUNT(*) AS TOP_PERFORMER_COUNT\nFROM peak_teams\nGROUP BY TEAM_NAME\nORDER BY TOP_PERFORMER_COUNT DESC, TEAM_NAME ASC\nLIMIT 5;" := by
  first | sql_equiv | sorry

theorem eq_0_3 :
    sql%([MBB_HISTORICAL_TEAMS_SEASONS_schema]) "WITH max_wins_per_season AS (\n  SELECT \"season\", MAX(\"wins\") AS max_wins\n  FROM \"NCAA_BASKETBALL\".\"NCAA_BASKETBALL\".\"MBB_HISTORICAL_TEAMS_SEASONS\"\n  WHERE \"season\" BETWEEN 1900 AND 2000\n  GROUP BY \"season\"\n),\nteams_with_max_wins AS (\n  SELECT t.\"market\" AS TEAM_NAME, t.\"season\"\n  FROM \"NCAA_BASKETBALL\".\"NCAA_BASKETBALL\".\"MBB_HISTORICAL_TEAMS_SEASONS\" t\n  JOIN max_wins_per_season m\n    ON t.\"season\" = m.\"season\" AND t.\"wins\" = m.max_wins\n  WHERE t.\"market\" IS NOT NULL\n)\nSELECT TEAM_NAME, COUNT(*) AS TOP_PERFORMER_COUNT\nFROM teams_with_max_wins\nGROUP BY TEAM_NAME\nORDER BY TOP_PERFORMER_COUNT DESC, TEAM_NAME ASC\nLIMIT 5;" = sql%([MBB_HISTORICAL_TEAMS_SEASONS_schema]) "WITH season_max_wins AS (\n    SELECT\n        \"season\",\n        MAX(\"wins\") AS max_wins\n    FROM \"NCAA_BASKETBALL\".\"NCAA_BASKETBALL\".\"MBB_HISTORICAL_TEAMS_SEASONS\"\n    WHERE \"season\" BETWEEN 1900 AND 2000\n    GROUP BY \"season\"\n),\npeak_teams AS (\n    SELECT\n        t.\"market\" AS TEAM_NAME,\n        t.\"season\"\n    FROM \"NCAA_BASKETBALL\".\"NCAA_BASKETBALL\".\"MBB_HISTORICAL_TEAMS_SEASONS\" t\n    INNER JOIN season_max_wins s\n        ON t.\"season\" = s.\"season\"\n        AND t.\"wins\" = s.max_wins\n    WHERE t.\"season\" BETWEEN 1900 AND 2000\n      AND t.\"market\" IS NOT NULL\n)\nSELECT\n    TEAM_NAME,\n    COUNT(*) AS TOP_PERFORMER_COUNT\nFROM peak_teams\nGROUP BY TEAM_NAME\nORDER BY TOP_PERFORMER_COUNT DESC, TEAM_NAME ASC\nLIMIT 5;" := by
  first | sql_equiv | sorry

theorem eq_1_2 :
    sql%([MBB_HISTORICAL_TEAMS_SEASONS_schema]) "WITH season_max AS (\n  SELECT \"season\", MAX(\"wins\") AS max_wins\n  FROM \"NCAA_BASKETBALL\".\"NCAA_BASKETBALL\".\"MBB_HISTORICAL_TEAMS_SEASONS\"\n  WHERE \"season\" BETWEEN 1900 AND 2000\n  GROUP BY \"season\"\n),\npeak_teams AS (\n  SELECT t.\"market\" AS TEAM_NAME, t.\"season\"\n  FROM \"NCAA_BASKETBALL\".\"NCAA_BASKETBALL\".\"MBB_HISTORICAL_TEAMS_SEASONS\" t\n  INNER JOIN season_max s\n    ON t.\"season\" = s.\"season\"\n    AND t.\"wins\" = s.max_wins\n  WHERE t.\"season\" BETWEEN 1900 AND 2000\n    AND t.\"name\" IS NOT NULL\n)\nSELECT TEAM_NAME, COUNT(*) AS TOP_PERFORMER_COUNT\nFROM peak_teams\nGROUP BY TEAM_NAME\nORDER BY TOP_PERFORMER_COUNT DESC, TEAM_NAME ASC\nLIMIT 5;" = sql%([MBB_HISTORICAL_TEAMS_SEASONS_schema]) "WITH season_max AS (\n    SELECT\n        \"season\",\n        MAX(\"wins\") AS max_wins\n    FROM \"NCAA_BASKETBALL\".\"NCAA_BASKETBALL\".\"MBB_HISTORICAL_TEAMS_SEASONS\"\n    WHERE \"season\" BETWEEN 1900 AND 2000\n    GROUP BY \"season\"\n),\npeak_teams AS (\n    SELECT\n        t.\"market\" AS TEAM_NAME,\n        t.\"season\"\n    FROM \"NCAA_BASKETBALL\".\"NCAA_BASKETBALL\".\"MBB_HISTORICAL_TEAMS_SEASONS\" t\n    JOIN season_max sm\n        ON t.\"season\" = sm.\"season\"\n        AND t.\"wins\" = sm.max_wins\n    WHERE t.\"season\" BETWEEN 1900 AND 2000\n      AND t.\"market\" IS NOT NULL\n)\nSELECT\n    TEAM_NAME,\n    COUNT(*) AS TOP_PERFORMER_COUNT\nFROM peak_teams\nGROUP BY TEAM_NAME\nORDER BY TOP_PERFORMER_COUNT DESC, TEAM_NAME ASC\nLIMIT 5;" := by
  first | sql_equiv | sorry

theorem eq_1_3 :
    sql%([MBB_HISTORICAL_TEAMS_SEASONS_schema]) "WITH season_max AS (\n  SELECT \"season\", MAX(\"wins\") AS max_wins\n  FROM \"NCAA_BASKETBALL\".\"NCAA_BASKETBALL\".\"MBB_HISTORICAL_TEAMS_SEASONS\"\n  WHERE \"season\" BETWEEN 1900 AND 2000\n  GROUP BY \"season\"\n),\npeak_teams AS (\n  SELECT t.\"market\" AS TEAM_NAME, t.\"season\"\n  FROM \"NCAA_BASKETBALL\".\"NCAA_BASKETBALL\".\"MBB_HISTORICAL_TEAMS_SEASONS\" t\n  INNER JOIN season_max s\n    ON t.\"season\" = s.\"season\"\n    AND t.\"wins\" = s.max_wins\n  WHERE t.\"season\" BETWEEN 1900 AND 2000\n    AND t.\"name\" IS NOT NULL\n)\nSELECT TEAM_NAME, COUNT(*) AS TOP_PERFORMER_COUNT\nFROM peak_teams\nGROUP BY TEAM_NAME\nORDER BY TOP_PERFORMER_COUNT DESC, TEAM_NAME ASC\nLIMIT 5;" = sql%([MBB_HISTORICAL_TEAMS_SEASONS_schema]) "WITH season_max_wins AS (\n    SELECT\n        \"season\",\n        MAX(\"wins\") AS max_wins\n    FROM \"NCAA_BASKETBALL\".\"NCAA_BASKETBALL\".\"MBB_HISTORICAL_TEAMS_SEASONS\"\n    WHERE \"season\" BETWEEN 1900 AND 2000\n    GROUP BY \"season\"\n),\npeak_teams AS (\n    SELECT\n        t.\"market\" AS TEAM_NAME,\n        t.\"season\"\n    FROM \"NCAA_BASKETBALL\".\"NCAA_BASKETBALL\".\"MBB_HISTORICAL_TEAMS_SEASONS\" t\n    INNER JOIN season_max_wins s\n        ON t.\"season\" = s.\"season\"\n        AND t.\"wins\" = s.max_wins\n    WHERE t.\"season\" BETWEEN 1900 AND 2000\n      AND t.\"market\" IS NOT NULL\n)\nSELECT\n    TEAM_NAME,\n    COUNT(*) AS TOP_PERFORMER_COUNT\nFROM peak_teams\nGROUP BY TEAM_NAME\nORDER BY TOP_PERFORMER_COUNT DESC, TEAM_NAME ASC\nLIMIT 5;" := by
  first | sql_equiv | sorry

theorem eq_2_3 :
    sql%([MBB_HISTORICAL_TEAMS_SEASONS_schema]) "WITH season_max AS (\n    SELECT\n        \"season\",\n        MAX(\"wins\") AS max_wins\n    FROM \"NCAA_BASKETBALL\".\"NCAA_BASKETBALL\".\"MBB_HISTORICAL_TEAMS_SEASONS\"\n    WHERE \"season\" BETWEEN 1900 AND 2000\n    GROUP BY \"season\"\n),\npeak_teams AS (\n    SELECT\n        t.\"market\" AS TEAM_NAME,\n        t.\"season\"\n    FROM \"NCAA_BASKETBALL\".\"NCAA_BASKETBALL\".\"MBB_HISTORICAL_TEAMS_SEASONS\" t\n    JOIN season_max sm\n        ON t.\"season\" = sm.\"season\"\n        AND t.\"wins\" = sm.max_wins\n    WHERE t.\"season\" BETWEEN 1900 AND 2000\n      AND t.\"market\" IS NOT NULL\n)\nSELECT\n    TEAM_NAME,\n    COUNT(*) AS TOP_PERFORMER_COUNT\nFROM peak_teams\nGROUP BY TEAM_NAME\nORDER BY TOP_PERFORMER_COUNT DESC, TEAM_NAME ASC\nLIMIT 5;" = sql%([MBB_HISTORICAL_TEAMS_SEASONS_schema]) "WITH season_max_wins AS (\n    SELECT\n        \"season\",\n        MAX(\"wins\") AS max_wins\n    FROM \"NCAA_BASKETBALL\".\"NCAA_BASKETBALL\".\"MBB_HISTORICAL_TEAMS_SEASONS\"\n    WHERE \"season\" BETWEEN 1900 AND 2000\n    GROUP BY \"season\"\n),\npeak_teams AS (\n    SELECT\n        t.\"market\" AS TEAM_NAME,\n        t.\"season\"\n    FROM \"NCAA_BASKETBALL\".\"NCAA_BASKETBALL\".\"MBB_HISTORICAL_TEAMS_SEASONS\" t\n    INNER JOIN season_max_wins s\n        ON t.\"season\" = s.\"season\"\n        AND t.\"wins\" = s.max_wins\n    WHERE t.\"season\" BETWEEN 1900 AND 2000\n      AND t.\"market\" IS NOT NULL\n)\nSELECT\n    TEAM_NAME,\n    COUNT(*) AS TOP_PERFORMER_COUNT\nFROM peak_teams\nGROUP BY TEAM_NAME\nORDER BY TOP_PERFORMER_COUNT DESC, TEAM_NAME ASC\nLIMIT 5;" := by
  first | sql_equiv | sorry

end Bench_sf_bq198
