import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_bq331 — crossskill equivalence(s)

Question: Find the top three users who have authored the first message in forum topics, ranked in descending order by their message scores, where a message score is defined as the number of distinct users who voted on that message. For each of these users, provide their username and the absolute difference between their message score and the average message score across all first messages in forum topics.

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_bq331

CREATE TABLE FORUMMESSAGEVOTES («Id» INT, «ForumMessageId» INT, «FromUserId» INT, «ToUserId» INT, «VoteDate» STRING)
CREATE TABLE FORUMTOPICS («TotalReplies» INT, «LastCommentDate» INT, «FirstForumMessageId» FLOAT, «IsSticky» BOOL, «ForumId» INT, «Title» STRING, «TotalMessages» INT, «Id» INT, «LastForumMessageId» FLOAT, «CreationDate» INT, «TotalViews» INT, «KernelId» FLOAT, «Score» INT)
CREATE TABLE USERS («Id» INT, «UserName» STRING, «DisplayName» STRING, «RegisterDate» STRING, «PerformanceTier» INT, «Country» STRING)
CREATE TABLE FORUMMESSAGES («Id» INT, «ForumTopicId» INT, «PostUserId» INT, «PostDate» STRING, «ReplyToForumMessageId» FLOAT, «Message» STRING, «RawMarkdown» STRING, «Medal» FLOAT, «MedalAwardDate» STRING)

theorem eq_0_1 : ∀ t,
    (sql%([FORUMMESSAGEVOTES_schema, FORUMTOPICS_schema, USERS_schema, FORUMMESSAGES_schema]) "WITH first_messages AS (\n  SELECT \n    fm.\"Id\" AS message_id, \n    fm.\"PostUserId\",\n    COUNT(DISTINCT fmv.\"FromUserId\") AS message_score\n  FROM \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMTOPICS\" ft\n  JOIN \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMMESSAGES\" fm \n    ON ft.\"FirstForumMessageId\" = fm.\"Id\"\n  LEFT JOIN \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMMESSAGEVOTES\" fmv \n    ON fm.\"Id\" = fmv.\"ForumMessageId\"\n  GROUP BY fm.\"Id\", fm.\"PostUserId\"\n),\navg_score AS (\n  SELECT AVG(message_score) AS avg_msg_score FROM first_messages\n)\nSELECT \n  u.\"UserName\",\n  ABS(fm.message_score - a.avg_msg_score) AS ABS_DIFF\nFROM first_messages fm\nJOIN \"META_KAGGLE\".\"META_KAGGLE\".\"USERS\" u ON fm.\"PostUserId\" = u.\"Id\"\nCROSS JOIN avg_score a\nORDER BY fm.message_score DESC\nLIMIT 3;") t ~= (sql%([FORUMMESSAGEVOTES_schema, FORUMTOPICS_schema, USERS_schema, FORUMMESSAGES_schema]) "WITH first_msgs AS (\n    SELECT fm.\"Id\" AS msg_id, fm.\"PostUserId\"\n    FROM \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMTOPICS\" ft\n    JOIN \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMMESSAGES\" fm \n        ON ft.\"FirstForumMessageId\" = fm.\"Id\"\n),\nmsg_scores AS (\n    SELECT \n        fm.msg_id, \n        fm.\"PostUserId\", \n        COUNT(DISTINCT fmv.\"FromUserId\") AS msg_score\n    FROM first_msgs fm\n    LEFT JOIN \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMMESSAGEVOTES\" fmv \n        ON fm.msg_id = fmv.\"ForumMessageId\"\n    GROUP BY fm.msg_id, fm.\"PostUserId\"\n),\navg_score AS (\n    SELECT AVG(msg_score) AS avg_msg_score FROM msg_scores\n)\nSELECT \n    u.\"UserName\", \n    ABS(ms.msg_score - a.avg_msg_score) AS ABS_DIFF\nFROM msg_scores ms\nJOIN \"META_KAGGLE\".\"META_KAGGLE\".\"USERS\" u \n    ON ms.\"PostUserId\" = u.\"Id\"\nCROSS JOIN avg_score a\nORDER BY ms.msg_score DESC\nLIMIT 3;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_0_2 : ∀ t,
    (sql%([FORUMMESSAGEVOTES_schema, FORUMTOPICS_schema, USERS_schema, FORUMMESSAGES_schema]) "WITH first_messages AS (\n  SELECT \n    fm.\"Id\" AS message_id, \n    fm.\"PostUserId\",\n    COUNT(DISTINCT fmv.\"FromUserId\") AS message_score\n  FROM \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMTOPICS\" ft\n  JOIN \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMMESSAGES\" fm \n    ON ft.\"FirstForumMessageId\" = fm.\"Id\"\n  LEFT JOIN \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMMESSAGEVOTES\" fmv \n    ON fm.\"Id\" = fmv.\"ForumMessageId\"\n  GROUP BY fm.\"Id\", fm.\"PostUserId\"\n),\navg_score AS (\n  SELECT AVG(message_score) AS avg_msg_score FROM first_messages\n)\nSELECT \n  u.\"UserName\",\n  ABS(fm.message_score - a.avg_msg_score) AS ABS_DIFF\nFROM first_messages fm\nJOIN \"META_KAGGLE\".\"META_KAGGLE\".\"USERS\" u ON fm.\"PostUserId\" = u.\"Id\"\nCROSS JOIN avg_score a\nORDER BY fm.message_score DESC\nLIMIT 3;") t ~= (sql%([FORUMMESSAGEVOTES_schema, FORUMTOPICS_schema, USERS_schema, FORUMMESSAGES_schema]) "WITH first_messages AS (\n    -- Get the first message of each forum topic\n    SELECT ft.\"FirstForumMessageId\" AS message_id\n    FROM \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMTOPICS\" ft\n    WHERE ft.\"FirstForumMessageId\" IS NOT NULL\n),\nmessage_scores AS (\n    -- For each first message, compute message score = count of distinct voters\n    SELECT \n        fm.\"Id\" AS message_id,\n        fm.\"PostUserId\",\n        COUNT(DISTINCT fmv.\"FromUserId\") AS message_score\n    FROM first_messages fmsg\n    JOIN \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMMESSAGES\" fm\n        ON fm.\"Id\" = fmsg.message_id\n    LEFT JOIN \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMMESSAGEVOTES\" fmv\n        ON fmv.\"ForumMessageId\" = fm.\"Id\"\n    GROUP BY fm.\"Id\", fm.\"PostUserId\"\n),\navg_score AS (\n    SELECT AVG(message_score) AS avg_message_score\n    FROM message_scores\n),\nranked AS (\n    SELECT \n        ms.\"PostUserId\",\n        ms.message_score,\n        ROW_NUMBER() OVER (ORDER BY ms.message_score DESC) AS rn\n    FROM message_scores ms\n)\nSELECT \n    u.\"UserName\" AS \"UserName\",\n    ABS(r.message_score - a.avg_message_score) AS \"ABS_DIFF\"\nFROM ranked r\nCROSS JOIN avg_score a\nJOIN \"META_KAGGLE\".\"META_KAGGLE\".\"USERS\" u\n    ON u.\"Id\" = r.\"PostUserId\"\nWHERE r.rn <= 3\nORDER BY r.rn;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_0_3 : ∀ t,
    (sql%([FORUMMESSAGEVOTES_schema, FORUMTOPICS_schema, USERS_schema, FORUMMESSAGES_schema]) "WITH first_messages AS (\n  SELECT \n    fm.\"Id\" AS message_id, \n    fm.\"PostUserId\",\n    COUNT(DISTINCT fmv.\"FromUserId\") AS message_score\n  FROM \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMTOPICS\" ft\n  JOIN \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMMESSAGES\" fm \n    ON ft.\"FirstForumMessageId\" = fm.\"Id\"\n  LEFT JOIN \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMMESSAGEVOTES\" fmv \n    ON fm.\"Id\" = fmv.\"ForumMessageId\"\n  GROUP BY fm.\"Id\", fm.\"PostUserId\"\n),\navg_score AS (\n  SELECT AVG(message_score) AS avg_msg_score FROM first_messages\n)\nSELECT \n  u.\"UserName\",\n  ABS(fm.message_score - a.avg_msg_score) AS ABS_DIFF\nFROM first_messages fm\nJOIN \"META_KAGGLE\".\"META_KAGGLE\".\"USERS\" u ON fm.\"PostUserId\" = u.\"Id\"\nCROSS JOIN avg_score a\nORDER BY fm.message_score DESC\nLIMIT 3;") t ~= (sql%([FORUMMESSAGEVOTES_schema, FORUMTOPICS_schema, USERS_schema, FORUMMESSAGES_schema]) "WITH first_messages AS (\n    SELECT fm.\"Id\" AS message_id,\n           fm.\"PostUserId\" AS user_id\n    FROM \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMTOPICS\" ft\n    JOIN \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMMESSAGES\" fm \n        ON ft.\"FirstForumMessageId\" = fm.\"Id\"\n),\nmessage_scores AS (\n    SELECT fmsg.message_id,\n           fmsg.user_id,\n           COUNT(DISTINCT fmv.\"FromUserId\") AS message_score\n    FROM first_messages fmsg\n    LEFT JOIN \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMMESSAGEVOTES\" fmv\n        ON fmsg.message_id = fmv.\"ForumMessageId\"\n    GROUP BY fmsg.message_id, fmsg.user_id\n),\navg_score AS (\n    SELECT AVG(message_score) AS avg_message_score\n    FROM message_scores\n),\nuser_max_scores AS (\n    SELECT ms.user_id,\n           MAX(ms.message_score) AS user_message_score\n    FROM message_scores ms\n    GROUP BY ms.user_id\n)\nSELECT u.\"UserName\" AS UserName,\n       ABS(us.user_message_score - a.avg_message_score) AS ABS_DIFF\nFROM user_max_scores us\nCROSS JOIN avg_score a\nJOIN \"META_KAGGLE\".\"META_KAGGLE\".\"USERS\" u\n    ON us.user_id = u.\"Id\"\nORDER BY us.user_message_score DESC\nLIMIT 3;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_1_2 : ∀ t,
    (sql%([FORUMMESSAGEVOTES_schema, FORUMTOPICS_schema, USERS_schema, FORUMMESSAGES_schema]) "WITH first_msgs AS (\n    SELECT fm.\"Id\" AS msg_id, fm.\"PostUserId\"\n    FROM \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMTOPICS\" ft\n    JOIN \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMMESSAGES\" fm \n        ON ft.\"FirstForumMessageId\" = fm.\"Id\"\n),\nmsg_scores AS (\n    SELECT \n        fm.msg_id, \n        fm.\"PostUserId\", \n        COUNT(DISTINCT fmv.\"FromUserId\") AS msg_score\n    FROM first_msgs fm\n    LEFT JOIN \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMMESSAGEVOTES\" fmv \n        ON fm.msg_id = fmv.\"ForumMessageId\"\n    GROUP BY fm.msg_id, fm.\"PostUserId\"\n),\navg_score AS (\n    SELECT AVG(msg_score) AS avg_msg_score FROM msg_scores\n)\nSELECT \n    u.\"UserName\", \n    ABS(ms.msg_score - a.avg_msg_score) AS ABS_DIFF\nFROM msg_scores ms\nJOIN \"META_KAGGLE\".\"META_KAGGLE\".\"USERS\" u \n    ON ms.\"PostUserId\" = u.\"Id\"\nCROSS JOIN avg_score a\nORDER BY ms.msg_score DESC\nLIMIT 3;") t ~= (sql%([FORUMMESSAGEVOTES_schema, FORUMTOPICS_schema, USERS_schema, FORUMMESSAGES_schema]) "WITH first_messages AS (\n    -- Get the first message of each forum topic\n    SELECT ft.\"FirstForumMessageId\" AS message_id\n    FROM \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMTOPICS\" ft\n    WHERE ft.\"FirstForumMessageId\" IS NOT NULL\n),\nmessage_scores AS (\n    -- For each first message, compute message score = count of distinct voters\n    SELECT \n        fm.\"Id\" AS message_id,\n        fm.\"PostUserId\",\n        COUNT(DISTINCT fmv.\"FromUserId\") AS message_score\n    FROM first_messages fmsg\n    JOIN \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMMESSAGES\" fm\n        ON fm.\"Id\" = fmsg.message_id\n    LEFT JOIN \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMMESSAGEVOTES\" fmv\n        ON fmv.\"ForumMessageId\" = fm.\"Id\"\n    GROUP BY fm.\"Id\", fm.\"PostUserId\"\n),\navg_score AS (\n    SELECT AVG(message_score) AS avg_message_score\n    FROM message_scores\n),\nranked AS (\n    SELECT \n        ms.\"PostUserId\",\n        ms.message_score,\n        ROW_NUMBER() OVER (ORDER BY ms.message_score DESC) AS rn\n    FROM message_scores ms\n)\nSELECT \n    u.\"UserName\" AS \"UserName\",\n    ABS(r.message_score - a.avg_message_score) AS \"ABS_DIFF\"\nFROM ranked r\nCROSS JOIN avg_score a\nJOIN \"META_KAGGLE\".\"META_KAGGLE\".\"USERS\" u\n    ON u.\"Id\" = r.\"PostUserId\"\nWHERE r.rn <= 3\nORDER BY r.rn;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_1_3 : ∀ t,
    (sql%([FORUMMESSAGEVOTES_schema, FORUMTOPICS_schema, USERS_schema, FORUMMESSAGES_schema]) "WITH first_msgs AS (\n    SELECT fm.\"Id\" AS msg_id, fm.\"PostUserId\"\n    FROM \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMTOPICS\" ft\n    JOIN \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMMESSAGES\" fm \n        ON ft.\"FirstForumMessageId\" = fm.\"Id\"\n),\nmsg_scores AS (\n    SELECT \n        fm.msg_id, \n        fm.\"PostUserId\", \n        COUNT(DISTINCT fmv.\"FromUserId\") AS msg_score\n    FROM first_msgs fm\n    LEFT JOIN \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMMESSAGEVOTES\" fmv \n        ON fm.msg_id = fmv.\"ForumMessageId\"\n    GROUP BY fm.msg_id, fm.\"PostUserId\"\n),\navg_score AS (\n    SELECT AVG(msg_score) AS avg_msg_score FROM msg_scores\n)\nSELECT \n    u.\"UserName\", \n    ABS(ms.msg_score - a.avg_msg_score) AS ABS_DIFF\nFROM msg_scores ms\nJOIN \"META_KAGGLE\".\"META_KAGGLE\".\"USERS\" u \n    ON ms.\"PostUserId\" = u.\"Id\"\nCROSS JOIN avg_score a\nORDER BY ms.msg_score DESC\nLIMIT 3;") t ~= (sql%([FORUMMESSAGEVOTES_schema, FORUMTOPICS_schema, USERS_schema, FORUMMESSAGES_schema]) "WITH first_messages AS (\n    SELECT fm.\"Id\" AS message_id,\n           fm.\"PostUserId\" AS user_id\n    FROM \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMTOPICS\" ft\n    JOIN \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMMESSAGES\" fm \n        ON ft.\"FirstForumMessageId\" = fm.\"Id\"\n),\nmessage_scores AS (\n    SELECT fmsg.message_id,\n           fmsg.user_id,\n           COUNT(DISTINCT fmv.\"FromUserId\") AS message_score\n    FROM first_messages fmsg\n    LEFT JOIN \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMMESSAGEVOTES\" fmv\n        ON fmsg.message_id = fmv.\"ForumMessageId\"\n    GROUP BY fmsg.message_id, fmsg.user_id\n),\navg_score AS (\n    SELECT AVG(message_score) AS avg_message_score\n    FROM message_scores\n),\nuser_max_scores AS (\n    SELECT ms.user_id,\n           MAX(ms.message_score) AS user_message_score\n    FROM message_scores ms\n    GROUP BY ms.user_id\n)\nSELECT u.\"UserName\" AS UserName,\n       ABS(us.user_message_score - a.avg_message_score) AS ABS_DIFF\nFROM user_max_scores us\nCROSS JOIN avg_score a\nJOIN \"META_KAGGLE\".\"META_KAGGLE\".\"USERS\" u\n    ON us.user_id = u.\"Id\"\nORDER BY us.user_message_score DESC\nLIMIT 3;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_2_3 : ∀ t,
    (sql%([FORUMMESSAGEVOTES_schema, FORUMTOPICS_schema, USERS_schema, FORUMMESSAGES_schema]) "WITH first_messages AS (\n    -- Get the first message of each forum topic\n    SELECT ft.\"FirstForumMessageId\" AS message_id\n    FROM \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMTOPICS\" ft\n    WHERE ft.\"FirstForumMessageId\" IS NOT NULL\n),\nmessage_scores AS (\n    -- For each first message, compute message score = count of distinct voters\n    SELECT \n        fm.\"Id\" AS message_id,\n        fm.\"PostUserId\",\n        COUNT(DISTINCT fmv.\"FromUserId\") AS message_score\n    FROM first_messages fmsg\n    JOIN \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMMESSAGES\" fm\n        ON fm.\"Id\" = fmsg.message_id\n    LEFT JOIN \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMMESSAGEVOTES\" fmv\n        ON fmv.\"ForumMessageId\" = fm.\"Id\"\n    GROUP BY fm.\"Id\", fm.\"PostUserId\"\n),\navg_score AS (\n    SELECT AVG(message_score) AS avg_message_score\n    FROM message_scores\n),\nranked AS (\n    SELECT \n        ms.\"PostUserId\",\n        ms.message_score,\n        ROW_NUMBER() OVER (ORDER BY ms.message_score DESC) AS rn\n    FROM message_scores ms\n)\nSELECT \n    u.\"UserName\" AS \"UserName\",\n    ABS(r.message_score - a.avg_message_score) AS \"ABS_DIFF\"\nFROM ranked r\nCROSS JOIN avg_score a\nJOIN \"META_KAGGLE\".\"META_KAGGLE\".\"USERS\" u\n    ON u.\"Id\" = r.\"PostUserId\"\nWHERE r.rn <= 3\nORDER BY r.rn;") t ~= (sql%([FORUMMESSAGEVOTES_schema, FORUMTOPICS_schema, USERS_schema, FORUMMESSAGES_schema]) "WITH first_messages AS (\n    SELECT fm.\"Id\" AS message_id,\n           fm.\"PostUserId\" AS user_id\n    FROM \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMTOPICS\" ft\n    JOIN \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMMESSAGES\" fm \n        ON ft.\"FirstForumMessageId\" = fm.\"Id\"\n),\nmessage_scores AS (\n    SELECT fmsg.message_id,\n           fmsg.user_id,\n           COUNT(DISTINCT fmv.\"FromUserId\") AS message_score\n    FROM first_messages fmsg\n    LEFT JOIN \"META_KAGGLE\".\"META_KAGGLE\".\"FORUMMESSAGEVOTES\" fmv\n        ON fmsg.message_id = fmv.\"ForumMessageId\"\n    GROUP BY fmsg.message_id, fmsg.user_id\n),\navg_score AS (\n    SELECT AVG(message_score) AS avg_message_score\n    FROM message_scores\n),\nuser_max_scores AS (\n    SELECT ms.user_id,\n           MAX(ms.message_score) AS user_message_score\n    FROM message_scores ms\n    GROUP BY ms.user_id\n)\nSELECT u.\"UserName\" AS UserName,\n       ABS(us.user_message_score - a.avg_message_score) AS ABS_DIFF\nFROM user_max_scores us\nCROSS JOIN avg_score a\nJOIN \"META_KAGGLE\".\"META_KAGGLE\".\"USERS\" u\n    ON us.user_id = u.\"Id\"\nORDER BY us.user_message_score DESC\nLIMIT 3;") t := by
  intro t; first | sql_equiv | sorry

end Bench_sf_bq331
