import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_bq114 — crossskill equivalence(s)

Question: Which three cities have the largest difference between their 1990 EPA PM2.5 measurements (using units_of_measure = 'Micrograms/cubic meter (LC)' and parameter_name = 'Acceptable PM2.5 AQI & Speciation Mass') and their 2020 OpenAQ PM2.5 measurements (where pollutant = 'pm25' based on the year extracted from the timestamp), with both datasets matched by latitude and longitude rounded to two decimals, and the difference ordered from greatest to least?

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_bq114

CREATE TABLE PM25_NONFRM_DAILY_SUMMARY («state_code» STRING, «county_code» STRING, «site_num» STRING, «parameter_code» INT, «poc» INT, «latitude» FLOAT, «longitude» FLOAT, «datum» STRING, «parameter_name» STRING, «sample_duration» STRING, «pollutant_standard» STRING, «date_local» STRING, «units_of_measure» STRING, «event_type» STRING, «observation_count» INT, «observation_percent» FLOAT, «arithmetic_mean» FLOAT, «first_max_value» FLOAT, «first_max_hour» INT, «aqi» INT, «method_code» INT, «method_name» STRING, «local_site_name» STRING, «address» STRING, «state_name» STRING, «county_name» STRING, «city_name» STRING, «cbsa_name» STRING, «date_of_last_change» STRING)
CREATE TABLE AIR_QUALITY_ANNUAL_SUMMARY («state_code» STRING, «county_code» STRING, «site_num» STRING, «parameter_code» INT, «poc» INT, «latitude» FLOAT, «longitude» FLOAT, «datum» STRING, «parameter_name» STRING, «sample_duration» STRING, «pollutant_standard» STRING, «metric_used» STRING, «method_name» STRING, «year» INT, «units_of_measure» STRING, «event_type» STRING, «observation_count» INT, «observation_percent» FLOAT, «completeness_indicator» STRING, «valid_day_count» INT, «required_day_count» INT, «exceptional_data_count» INT, «null_data_count» INT, «primary_exceedance_count» INT, «secondary_exceedance_count» INT, «certification_indicator» STRING, «num_obs_below_mdl» INT, «arithmetic_mean» FLOAT, «arithmetic_standard_dev» FLOAT, «first_max_value» FLOAT, «first_max_datetime» INT, «second_max_value» FLOAT, «second_max_datetime» INT, «third_max_value» FLOAT, «third_max_datetime» INT, «fourth_max_value» FLOAT, «fourth_max_datetime» INT, «first_max_non_overlapping_value» FLOAT, «first_no_max_datetime» INT, «second_max_non_overlapping_value» FLOAT, «second_no_max_datetime» INT, «ninety_nine_percentile» FLOAT, «ninety_eight_percentile» FLOAT, «ninety_five_percentile» FLOAT, «ninety_percentile» FLOAT, «seventy_five_percentile» FLOAT, «fifty_percentile» FLOAT, «ten_percentile» FLOAT, «local_site_name» STRING, «address» STRING, «state_name» STRING, «county_name» STRING, «city_name» STRING, «cbsa_name» STRING, «date_of_last_change» STRING)
CREATE TABLE GLOBAL_AIR_QUALITY («location» STRING, «city» STRING, «country» STRING, «pollutant» STRING, «value» FLOAT, «timestamp» INT, «unit» STRING, «source_name» STRING, «latitude» FLOAT, «longitude» FLOAT, «averaged_over_in_hours» FLOAT, «location_geom» STRING)

theorem eq_0_1 : ∀ t,
    (sql%([PM25_NONFRM_DAILY_SUMMARY_schema, AIR_QUALITY_ANNUAL_SUMMARY_schema, GLOBAL_AIR_QUALITY_schema]) "WITH epa AS (SELECT ROUND(\"latitude\", 2) AS lat, ROUND(\"longitude\", 2) AS lon, AVG(\"arithmetic_mean\") AS arithmetic_mean FROM \"OPENAQ\".\"EPA_HISTORICAL_AIR_QUALITY\".\"PM25_NONFRM_DAILY_SUMMARY\" WHERE \"parameter_name\" = 'Acceptable PM2.5 AQI & Speciation Mass' AND \"units_of_measure\" = 'Micrograms/cubic meter (LC)' AND EXTRACT(YEAR FROM \"date_local\") = 1990 GROUP BY ROUND(\"latitude\", 2), ROUND(\"longitude\", 2)), oaq AS (SELECT \"city\", \"value\", TO_TIMESTAMP(CAST(\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS ts, ROUND(\"latitude\", 2) AS lat, ROUND(\"longitude\", 2) AS lon FROM \"OPENAQ\".\"OPENAQ\".\"GLOBAL_AIR_QUALITY\" WHERE \"pollutant\" = 'pm25' AND EXTRACT(YEAR FROM TO_TIMESTAMP(CAST(\"timestamp\" AS DOUBLE PRECISION) / 1000000)) = 2020) SELECT oaq.\"city\" AS city, epa.arithmetic_mean, oaq.\"value\" AS value, CAST(oaq.ts AS DATE) AS timestamp, epa.arithmetic_mean - oaq.\"value\" AS f0_ FROM epa JOIN oaq ON epa.lat = oaq.lat AND epa.lon = oaq.lon ORDER BY f0_ DESC LIMIT 3") t ~= (sql%([PM25_NONFRM_DAILY_SUMMARY_schema, AIR_QUALITY_ANNUAL_SUMMARY_schema, GLOBAL_AIR_QUALITY_schema]) "SELECT oaq.\"city\", epa.arithmetic_mean, oaq.\"value\", CAST(TO_TIMESTAMP(CAST(oaq.\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) AS timestamp, ABS(epa.arithmetic_mean - oaq.\"value\") AS f0_ FROM (SELECT ROUND(\"latitude\", 2) AS lat, ROUND(\"longitude\", 2) AS lon, AVG(\"arithmetic_mean\") AS arithmetic_mean FROM \"OPENAQ\".\"EPA_HISTORICAL_AIR_QUALITY\".\"PM25_NONFRM_DAILY_SUMMARY\" WHERE \"parameter_name\" = 'Acceptable PM2.5 AQI & Speciation Mass' AND \"units_of_measure\" = 'Micrograms/cubic meter (LC)' AND EXTRACT(YEAR FROM \"date_local\") = 1990 GROUP BY ROUND(\"latitude\", 2), ROUND(\"longitude\", 2)) AS epa INNER JOIN (SELECT \"city\", \"value\", \"timestamp\", ROUND(\"latitude\", 2) AS lat, ROUND(\"longitude\", 2) AS lon FROM \"OPENAQ\".\"OPENAQ\".\"GLOBAL_AIR_QUALITY\" WHERE \"pollutant\" = 'pm25' AND \"unit\" = 'µg/m³' AND \"country\" = 'US' AND EXTRACT(YEAR FROM TO_TIMESTAMP(CAST(\"timestamp\" AS DOUBLE PRECISION) / 1000000)) = 2020) AS oaq ON epa.lat = oaq.lat AND epa.lon = oaq.lon ORDER BY f0_ DESC LIMIT 3") t := by
  intro t; first | sql_equiv | sorry

-- eq_0_2: needs a data hypothesis over multiple tables (not stated); likely `sorry`.
theorem eq_0_2 : ∀ t,
    (sql%([PM25_NONFRM_DAILY_SUMMARY_schema, AIR_QUALITY_ANNUAL_SUMMARY_schema, GLOBAL_AIR_QUALITY_schema]) "WITH epa AS (SELECT ROUND(\"latitude\", 2) AS lat, ROUND(\"longitude\", 2) AS lon, AVG(\"arithmetic_mean\") AS arithmetic_mean FROM \"OPENAQ\".\"EPA_HISTORICAL_AIR_QUALITY\".\"PM25_NONFRM_DAILY_SUMMARY\" WHERE \"parameter_name\" = 'Acceptable PM2.5 AQI & Speciation Mass' AND \"units_of_measure\" = 'Micrograms/cubic meter (LC)' AND EXTRACT(YEAR FROM \"date_local\") = 1990 GROUP BY ROUND(\"latitude\", 2), ROUND(\"longitude\", 2)), oaq AS (SELECT \"city\", \"value\", TO_TIMESTAMP(CAST(\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS ts, ROUND(\"latitude\", 2) AS lat, ROUND(\"longitude\", 2) AS lon FROM \"OPENAQ\".\"OPENAQ\".\"GLOBAL_AIR_QUALITY\" WHERE \"pollutant\" = 'pm25' AND EXTRACT(YEAR FROM TO_TIMESTAMP(CAST(\"timestamp\" AS DOUBLE PRECISION) / 1000000)) = 2020) SELECT oaq.\"city\" AS city, epa.arithmetic_mean, oaq.\"value\" AS value, CAST(oaq.ts AS DATE) AS timestamp, epa.arithmetic_mean - oaq.\"value\" AS f0_ FROM epa JOIN oaq ON epa.lat = oaq.lat AND epa.lon = oaq.lon ORDER BY f0_ DESC LIMIT 3") t ~= (sql%([PM25_NONFRM_DAILY_SUMMARY_schema, AIR_QUALITY_ANNUAL_SUMMARY_schema, GLOBAL_AIR_QUALITY_schema]) "WITH epa AS (SELECT \"city_name\", \"arithmetic_mean\", ROUND(\"latitude\", 2) AS lat, ROUND(\"longitude\", 2) AS lon FROM \"OPENAQ\".\"EPA_HISTORICAL_AIR_QUALITY\".\"AIR_QUALITY_ANNUAL_SUMMARY\" WHERE \"year\" = 1990 AND \"units_of_measure\" = 'Micrograms/cubic meter (LC)' AND \"parameter_name\" = 'Acceptable PM2.5 AQI & Speciation Mass'), openaq AS (SELECT \"city\", \"value\", CAST(TO_TIMESTAMP(CAST(\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) AS \"timestamp\", ROUND(\"latitude\", 2) AS lat, ROUND(\"longitude\", 2) AS lon FROM \"OPENAQ\".\"OPENAQ\".\"GLOBAL_AIR_QUALITY\" WHERE \"pollutant\" = 'pm25' AND EXTRACT(YEAR FROM TO_TIMESTAMP(CAST(\"timestamp\" AS DOUBLE PRECISION) / 1000000)) = 2020) SELECT openaq.\"city\" AS \"city\", epa.\"arithmetic_mean\" AS \"arithmetic_mean\", openaq.\"value\" AS \"value\", openaq.\"timestamp\" AS \"timestamp\", (epa.\"arithmetic_mean\" - openaq.\"value\") AS \"f0_\" FROM epa JOIN openaq ON epa.lat = openaq.lat AND epa.lon = openaq.lon ORDER BY \"f0_\" DESC LIMIT 3") t := by
  intro t; first | sql_equiv | sorry

-- eq_0_3: needs a data hypothesis over multiple tables (not stated); likely `sorry`.
theorem eq_0_3 :
    sql%([PM25_NONFRM_DAILY_SUMMARY_schema, AIR_QUALITY_ANNUAL_SUMMARY_schema, GLOBAL_AIR_QUALITY_schema]) "WITH epa AS (SELECT ROUND(\"latitude\", 2) AS lat, ROUND(\"longitude\", 2) AS lon, AVG(\"arithmetic_mean\") AS arithmetic_mean FROM \"OPENAQ\".\"EPA_HISTORICAL_AIR_QUALITY\".\"PM25_NONFRM_DAILY_SUMMARY\" WHERE \"parameter_name\" = 'Acceptable PM2.5 AQI & Speciation Mass' AND \"units_of_measure\" = 'Micrograms/cubic meter (LC)' AND EXTRACT(YEAR FROM \"date_local\") = 1990 GROUP BY ROUND(\"latitude\", 2), ROUND(\"longitude\", 2)), oaq AS (SELECT \"city\", \"value\", TO_TIMESTAMP(CAST(\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS ts, ROUND(\"latitude\", 2) AS lat, ROUND(\"longitude\", 2) AS lon FROM \"OPENAQ\".\"OPENAQ\".\"GLOBAL_AIR_QUALITY\" WHERE \"pollutant\" = 'pm25' AND EXTRACT(YEAR FROM TO_TIMESTAMP(CAST(\"timestamp\" AS DOUBLE PRECISION) / 1000000)) = 2020) SELECT oaq.\"city\" AS city, epa.arithmetic_mean, oaq.\"value\" AS value, CAST(oaq.ts AS DATE) AS timestamp, epa.arithmetic_mean - oaq.\"value\" AS f0_ FROM epa JOIN oaq ON epa.lat = oaq.lat AND epa.lon = oaq.lon ORDER BY f0_ DESC LIMIT 3" = sql%([PM25_NONFRM_DAILY_SUMMARY_schema, AIR_QUALITY_ANNUAL_SUMMARY_schema, GLOBAL_AIR_QUALITY_schema]) "WITH epa AS (SELECT ROUND(\"latitude\", 2) AS lat, ROUND(\"longitude\", 2) AS lon, AVG(\"arithmetic_mean\") AS arithmetic_mean FROM \"OPENAQ\".\"EPA_HISTORICAL_AIR_QUALITY\".\"PM25_NONFRM_DAILY_SUMMARY\" WHERE \"parameter_name\" = 'Acceptable PM2.5 AQI & Speciation Mass' AND \"units_of_measure\" = 'Micrograms/cubic meter (LC)' AND EXTRACT(YEAR FROM \"date_local\") = 1990 AND \"sample_duration\" = '24 HOUR' GROUP BY lat, lon), openaq AS (SELECT \"city\", \"value\", CAST(TO_TIMESTAMP(CAST(\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) AS timestamp, ROUND(\"latitude\", 2) AS lat, ROUND(\"longitude\", 2) AS lon FROM \"OPENAQ\".\"OPENAQ\".\"GLOBAL_AIR_QUALITY\" WHERE \"pollutant\" = 'pm25' AND \"country\" = 'US' AND \"unit\" = 'µg/m³' AND EXTRACT(YEAR FROM TO_TIMESTAMP(CAST(\"timestamp\" AS DOUBLE PRECISION) / 1000000)) = 2020) SELECT o.\"city\", e.arithmetic_mean, o.\"value\", o.timestamp, (e.arithmetic_mean - o.\"value\") AS f0_ FROM epa AS e JOIN openaq AS o ON e.lat = o.lat AND e.lon = o.lon ORDER BY f0_ DESC LIMIT 3" := by
  first | sql_equiv | sorry

-- eq_1_2: needs a data hypothesis over multiple tables (not stated); likely `sorry`.
theorem eq_1_2 : ∀ t,
    (sql%([PM25_NONFRM_DAILY_SUMMARY_schema, AIR_QUALITY_ANNUAL_SUMMARY_schema, GLOBAL_AIR_QUALITY_schema]) "SELECT oaq.\"city\", epa.arithmetic_mean, oaq.\"value\", CAST(TO_TIMESTAMP(CAST(oaq.\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) AS timestamp, ABS(epa.arithmetic_mean - oaq.\"value\") AS f0_ FROM (SELECT ROUND(\"latitude\", 2) AS lat, ROUND(\"longitude\", 2) AS lon, AVG(\"arithmetic_mean\") AS arithmetic_mean FROM \"OPENAQ\".\"EPA_HISTORICAL_AIR_QUALITY\".\"PM25_NONFRM_DAILY_SUMMARY\" WHERE \"parameter_name\" = 'Acceptable PM2.5 AQI & Speciation Mass' AND \"units_of_measure\" = 'Micrograms/cubic meter (LC)' AND EXTRACT(YEAR FROM \"date_local\") = 1990 GROUP BY ROUND(\"latitude\", 2), ROUND(\"longitude\", 2)) AS epa INNER JOIN (SELECT \"city\", \"value\", \"timestamp\", ROUND(\"latitude\", 2) AS lat, ROUND(\"longitude\", 2) AS lon FROM \"OPENAQ\".\"OPENAQ\".\"GLOBAL_AIR_QUALITY\" WHERE \"pollutant\" = 'pm25' AND \"unit\" = 'µg/m³' AND \"country\" = 'US' AND EXTRACT(YEAR FROM TO_TIMESTAMP(CAST(\"timestamp\" AS DOUBLE PRECISION) / 1000000)) = 2020) AS oaq ON epa.lat = oaq.lat AND epa.lon = oaq.lon ORDER BY f0_ DESC LIMIT 3") t ~= (sql%([PM25_NONFRM_DAILY_SUMMARY_schema, AIR_QUALITY_ANNUAL_SUMMARY_schema, GLOBAL_AIR_QUALITY_schema]) "WITH epa AS (SELECT \"city_name\", \"arithmetic_mean\", ROUND(\"latitude\", 2) AS lat, ROUND(\"longitude\", 2) AS lon FROM \"OPENAQ\".\"EPA_HISTORICAL_AIR_QUALITY\".\"AIR_QUALITY_ANNUAL_SUMMARY\" WHERE \"year\" = 1990 AND \"units_of_measure\" = 'Micrograms/cubic meter (LC)' AND \"parameter_name\" = 'Acceptable PM2.5 AQI & Speciation Mass'), openaq AS (SELECT \"city\", \"value\", CAST(TO_TIMESTAMP(CAST(\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) AS \"timestamp\", ROUND(\"latitude\", 2) AS lat, ROUND(\"longitude\", 2) AS lon FROM \"OPENAQ\".\"OPENAQ\".\"GLOBAL_AIR_QUALITY\" WHERE \"pollutant\" = 'pm25' AND EXTRACT(YEAR FROM TO_TIMESTAMP(CAST(\"timestamp\" AS DOUBLE PRECISION) / 1000000)) = 2020) SELECT openaq.\"city\" AS \"city\", epa.\"arithmetic_mean\" AS \"arithmetic_mean\", openaq.\"value\" AS \"value\", openaq.\"timestamp\" AS \"timestamp\", (epa.\"arithmetic_mean\" - openaq.\"value\") AS \"f0_\" FROM epa JOIN openaq ON epa.lat = openaq.lat AND epa.lon = openaq.lon ORDER BY \"f0_\" DESC LIMIT 3") t := by
  intro t; first | sql_equiv | sorry

-- eq_1_3: needs a data hypothesis over multiple tables (not stated); likely `sorry`.
theorem eq_1_3 : ∀ t,
    (sql%([PM25_NONFRM_DAILY_SUMMARY_schema, AIR_QUALITY_ANNUAL_SUMMARY_schema, GLOBAL_AIR_QUALITY_schema]) "SELECT oaq.\"city\", epa.arithmetic_mean, oaq.\"value\", CAST(TO_TIMESTAMP(CAST(oaq.\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) AS timestamp, ABS(epa.arithmetic_mean - oaq.\"value\") AS f0_ FROM (SELECT ROUND(\"latitude\", 2) AS lat, ROUND(\"longitude\", 2) AS lon, AVG(\"arithmetic_mean\") AS arithmetic_mean FROM \"OPENAQ\".\"EPA_HISTORICAL_AIR_QUALITY\".\"PM25_NONFRM_DAILY_SUMMARY\" WHERE \"parameter_name\" = 'Acceptable PM2.5 AQI & Speciation Mass' AND \"units_of_measure\" = 'Micrograms/cubic meter (LC)' AND EXTRACT(YEAR FROM \"date_local\") = 1990 GROUP BY ROUND(\"latitude\", 2), ROUND(\"longitude\", 2)) AS epa INNER JOIN (SELECT \"city\", \"value\", \"timestamp\", ROUND(\"latitude\", 2) AS lat, ROUND(\"longitude\", 2) AS lon FROM \"OPENAQ\".\"OPENAQ\".\"GLOBAL_AIR_QUALITY\" WHERE \"pollutant\" = 'pm25' AND \"unit\" = 'µg/m³' AND \"country\" = 'US' AND EXTRACT(YEAR FROM TO_TIMESTAMP(CAST(\"timestamp\" AS DOUBLE PRECISION) / 1000000)) = 2020) AS oaq ON epa.lat = oaq.lat AND epa.lon = oaq.lon ORDER BY f0_ DESC LIMIT 3") t ~= (sql%([PM25_NONFRM_DAILY_SUMMARY_schema, AIR_QUALITY_ANNUAL_SUMMARY_schema, GLOBAL_AIR_QUALITY_schema]) "WITH epa AS (SELECT ROUND(\"latitude\", 2) AS lat, ROUND(\"longitude\", 2) AS lon, AVG(\"arithmetic_mean\") AS arithmetic_mean FROM \"OPENAQ\".\"EPA_HISTORICAL_AIR_QUALITY\".\"PM25_NONFRM_DAILY_SUMMARY\" WHERE \"parameter_name\" = 'Acceptable PM2.5 AQI & Speciation Mass' AND \"units_of_measure\" = 'Micrograms/cubic meter (LC)' AND EXTRACT(YEAR FROM \"date_local\") = 1990 AND \"sample_duration\" = '24 HOUR' GROUP BY lat, lon), openaq AS (SELECT \"city\", \"value\", CAST(TO_TIMESTAMP(CAST(\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) AS timestamp, ROUND(\"latitude\", 2) AS lat, ROUND(\"longitude\", 2) AS lon FROM \"OPENAQ\".\"OPENAQ\".\"GLOBAL_AIR_QUALITY\" WHERE \"pollutant\" = 'pm25' AND \"country\" = 'US' AND \"unit\" = 'µg/m³' AND EXTRACT(YEAR FROM TO_TIMESTAMP(CAST(\"timestamp\" AS DOUBLE PRECISION) / 1000000)) = 2020) SELECT o.\"city\", e.arithmetic_mean, o.\"value\", o.timestamp, (e.arithmetic_mean - o.\"value\") AS f0_ FROM epa AS e JOIN openaq AS o ON e.lat = o.lat AND e.lon = o.lon ORDER BY f0_ DESC LIMIT 3") t := by
  intro t; first | sql_equiv | sorry

-- eq_2_3: needs a data hypothesis over multiple tables (not stated); likely `sorry`.
theorem eq_2_3 : ∀ t,
    (sql%([PM25_NONFRM_DAILY_SUMMARY_schema, AIR_QUALITY_ANNUAL_SUMMARY_schema, GLOBAL_AIR_QUALITY_schema]) "WITH epa AS (SELECT \"city_name\", \"arithmetic_mean\", ROUND(\"latitude\", 2) AS lat, ROUND(\"longitude\", 2) AS lon FROM \"OPENAQ\".\"EPA_HISTORICAL_AIR_QUALITY\".\"AIR_QUALITY_ANNUAL_SUMMARY\" WHERE \"year\" = 1990 AND \"units_of_measure\" = 'Micrograms/cubic meter (LC)' AND \"parameter_name\" = 'Acceptable PM2.5 AQI & Speciation Mass'), openaq AS (SELECT \"city\", \"value\", CAST(TO_TIMESTAMP(CAST(\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) AS \"timestamp\", ROUND(\"latitude\", 2) AS lat, ROUND(\"longitude\", 2) AS lon FROM \"OPENAQ\".\"OPENAQ\".\"GLOBAL_AIR_QUALITY\" WHERE \"pollutant\" = 'pm25' AND EXTRACT(YEAR FROM TO_TIMESTAMP(CAST(\"timestamp\" AS DOUBLE PRECISION) / 1000000)) = 2020) SELECT openaq.\"city\" AS \"city\", epa.\"arithmetic_mean\" AS \"arithmetic_mean\", openaq.\"value\" AS \"value\", openaq.\"timestamp\" AS \"timestamp\", (epa.\"arithmetic_mean\" - openaq.\"value\") AS \"f0_\" FROM epa JOIN openaq ON epa.lat = openaq.lat AND epa.lon = openaq.lon ORDER BY \"f0_\" DESC LIMIT 3") t ~= (sql%([PM25_NONFRM_DAILY_SUMMARY_schema, AIR_QUALITY_ANNUAL_SUMMARY_schema, GLOBAL_AIR_QUALITY_schema]) "WITH epa AS (SELECT ROUND(\"latitude\", 2) AS lat, ROUND(\"longitude\", 2) AS lon, AVG(\"arithmetic_mean\") AS arithmetic_mean FROM \"OPENAQ\".\"EPA_HISTORICAL_AIR_QUALITY\".\"PM25_NONFRM_DAILY_SUMMARY\" WHERE \"parameter_name\" = 'Acceptable PM2.5 AQI & Speciation Mass' AND \"units_of_measure\" = 'Micrograms/cubic meter (LC)' AND EXTRACT(YEAR FROM \"date_local\") = 1990 AND \"sample_duration\" = '24 HOUR' GROUP BY lat, lon), openaq AS (SELECT \"city\", \"value\", CAST(TO_TIMESTAMP(CAST(\"timestamp\" AS DOUBLE PRECISION) / 1000000) AS DATE) AS timestamp, ROUND(\"latitude\", 2) AS lat, ROUND(\"longitude\", 2) AS lon FROM \"OPENAQ\".\"OPENAQ\".\"GLOBAL_AIR_QUALITY\" WHERE \"pollutant\" = 'pm25' AND \"country\" = 'US' AND \"unit\" = 'µg/m³' AND EXTRACT(YEAR FROM TO_TIMESTAMP(CAST(\"timestamp\" AS DOUBLE PRECISION) / 1000000)) = 2020) SELECT o.\"city\", e.arithmetic_mean, o.\"value\", o.timestamp, (e.arithmetic_mean - o.\"value\") AS f0_ FROM epa AS e JOIN openaq AS o ON e.lat = o.lat AND e.lon = o.lon ORDER BY f0_ DESC LIMIT 3") t := by
  intro t; first | sql_equiv | sorry

end Bench_sf_bq114
