import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_bq185 — crossskill equivalence(s)

Question: What is the average trip duration in minutes for all valid Yellow taxi trips that took place between February 1, 2016, and February 7, 2016 (inclusive), with a positive trip duration, more than three passengers, and a trip distance of at least ten miles, where both the pickup and dropoff locations are in Brooklyn?

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_bq185

CREATE TABLE TAXI_ZONE_GEOM («zone_id» STRING, «zone_name» STRING, «borough» STRING, «zone_geom» STRING)
CREATE TABLE TLC_YELLOW_TRIPS_2016 («vendor_id» STRING, «pickup_datetime» INT, «dropoff_datetime» INT, «passenger_count» INT, «trip_distance» INT, «rate_code» STRING, «store_and_fwd_flag» STRING, «payment_type» STRING, «fare_amount» INT, «extra» INT, «mta_tax» INT, «tip_amount» INT, «tolls_amount» INT, «imp_surcharge» INT, «airport_fee» INT, «total_amount» INT, «pickup_location_id» STRING, «dropoff_location_id» STRING, «data_file_year» INT, «data_file_month» INT)

-- eq_0_1: needs a data hypothesis over multiple tables (not stated); likely `sorry`.
theorem eq_0_1 :
    sql%([TAXI_ZONE_GEOM_schema, TLC_YELLOW_TRIPS_2016_schema]) "SELECT \n  AVG(DATEDIFF('minute', \n    TO_TIMESTAMP(t.\"pickup_datetime\"::NUMBER, 6), \n    TO_TIMESTAMP(t.\"dropoff_datetime\"::NUMBER, 6)\n  )) AS AVG_DURATION\nFROM \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TLC_YELLOW_TRIPS_2016\" t\nJOIN \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TAXI_ZONE_GEOM\" pz \n  ON t.\"pickup_location_id\" = pz.\"zone_id\"\nJOIN \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TAXI_ZONE_GEOM\" dz \n  ON t.\"dropoff_location_id\" = dz.\"zone_id\"\nWHERE TO_TIMESTAMP(t.\"pickup_datetime\"::NUMBER, 6) >= '2016-02-01'\n  AND TO_TIMESTAMP(t.\"pickup_datetime\"::NUMBER, 6) < '2016-02-08'\n  AND t.\"dropoff_datetime\" > t.\"pickup_datetime\"\n  AND t.\"passenger_count\" > 3\n  AND t.\"trip_distance\" >= 10\n  AND pz.\"borough\" = 'Brooklyn'\n  AND dz.\"borough\" = 'Brooklyn';" = sql%([TAXI_ZONE_GEOM_schema, TLC_YELLOW_TRIPS_2016_schema]) "SELECT \n  AVG(TIMESTAMPDIFF('MINUTE', TO_TIMESTAMP(t.\"pickup_datetime\" / 1000000), TO_TIMESTAMP(t.\"dropoff_datetime\" / 1000000))) AS AVG_DURATION\nFROM \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TLC_YELLOW_TRIPS_2016\" t\nJOIN \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TAXI_ZONE_GEOM\" pu \n  ON t.\"pickup_location_id\" = pu.\"zone_id\"\nJOIN \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TAXI_ZONE_GEOM\" do \n  ON t.\"dropoff_location_id\" = do.\"zone_id\"\nWHERE TO_TIMESTAMP(t.\"pickup_datetime\" / 1000000) >= '2016-02-01'\n  AND TO_TIMESTAMP(t.\"pickup_datetime\" / 1000000) < '2016-02-08'\n  AND t.\"passenger_count\" > 3\n  AND t.\"trip_distance\" >= 10\n  AND pu.\"borough\" = 'Brooklyn'\n  AND do.\"borough\" = 'Brooklyn'\n  AND (t.\"dropoff_datetime\" - t.\"pickup_datetime\") > 0;" := by
  first | sql_equiv | sorry

theorem eq_0_2 :
    sql%([TAXI_ZONE_GEOM_schema, TLC_YELLOW_TRIPS_2016_schema]) "SELECT \n  AVG(DATEDIFF('minute', \n    TO_TIMESTAMP(t.\"pickup_datetime\"::NUMBER, 6), \n    TO_TIMESTAMP(t.\"dropoff_datetime\"::NUMBER, 6)\n  )) AS AVG_DURATION\nFROM \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TLC_YELLOW_TRIPS_2016\" t\nJOIN \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TAXI_ZONE_GEOM\" pz \n  ON t.\"pickup_location_id\" = pz.\"zone_id\"\nJOIN \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TAXI_ZONE_GEOM\" dz \n  ON t.\"dropoff_location_id\" = dz.\"zone_id\"\nWHERE TO_TIMESTAMP(t.\"pickup_datetime\"::NUMBER, 6) >= '2016-02-01'\n  AND TO_TIMESTAMP(t.\"pickup_datetime\"::NUMBER, 6) < '2016-02-08'\n  AND t.\"dropoff_datetime\" > t.\"pickup_datetime\"\n  AND t.\"passenger_count\" > 3\n  AND t.\"trip_distance\" >= 10\n  AND pz.\"borough\" = 'Brooklyn'\n  AND dz.\"borough\" = 'Brooklyn';" = sql%([TAXI_ZONE_GEOM_schema, TLC_YELLOW_TRIPS_2016_schema]) "SELECT\n    AVG(\n        (\"dropoff_datetime\" - \"pickup_datetime\") / 1000000.0 / 60.0\n    ) AS \"AVG_DURATION\"\nFROM \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TLC_YELLOW_TRIPS_2016\" t\nJOIN \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TAXI_ZONE_GEOM\" pz\n    ON CAST(t.\"pickup_location_id\" AS VARCHAR) = pz.\"zone_id\"\nJOIN \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TAXI_ZONE_GEOM\" dz\n    ON CAST(t.\"dropoff_location_id\" AS VARCHAR) = dz.\"zone_id\"\nWHERE\n    TO_TIMESTAMP(t.\"pickup_datetime\" / 1000000) >= '2016-02-01'\n    AND TO_TIMESTAMP(t.\"pickup_datetime\" / 1000000) < '2016-02-08'\n    AND t.\"dropoff_datetime\" > t.\"pickup_datetime\"\n    AND t.\"passenger_count\" > 3\n    AND t.\"trip_distance\" >= 10\n    AND pz.\"borough\" = 'Brooklyn'\n    AND dz.\"borough\" = 'Brooklyn';" := by
  first | sql_equiv | sorry

theorem eq_0_3 :
    sql%([TAXI_ZONE_GEOM_schema, TLC_YELLOW_TRIPS_2016_schema]) "SELECT \n  AVG(DATEDIFF('minute', \n    TO_TIMESTAMP(t.\"pickup_datetime\"::NUMBER, 6), \n    TO_TIMESTAMP(t.\"dropoff_datetime\"::NUMBER, 6)\n  )) AS AVG_DURATION\nFROM \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TLC_YELLOW_TRIPS_2016\" t\nJOIN \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TAXI_ZONE_GEOM\" pz \n  ON t.\"pickup_location_id\" = pz.\"zone_id\"\nJOIN \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TAXI_ZONE_GEOM\" dz \n  ON t.\"dropoff_location_id\" = dz.\"zone_id\"\nWHERE TO_TIMESTAMP(t.\"pickup_datetime\"::NUMBER, 6) >= '2016-02-01'\n  AND TO_TIMESTAMP(t.\"pickup_datetime\"::NUMBER, 6) < '2016-02-08'\n  AND t.\"dropoff_datetime\" > t.\"pickup_datetime\"\n  AND t.\"passenger_count\" > 3\n  AND t.\"trip_distance\" >= 10\n  AND pz.\"borough\" = 'Brooklyn'\n  AND dz.\"borough\" = 'Brooklyn';" = sql%([TAXI_ZONE_GEOM_schema, TLC_YELLOW_TRIPS_2016_schema]) "SELECT \n    AVG(TIMESTAMPDIFF('MINUTE', TO_TIMESTAMP(t.\"pickup_datetime\" / 1000000), TO_TIMESTAMP(t.\"dropoff_datetime\" / 1000000))) AS AVG_DURATION\nFROM \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TLC_YELLOW_TRIPS_2016\" t\nJOIN \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TAXI_ZONE_GEOM\" pz\n    ON t.\"pickup_location_id\" = pz.\"zone_id\"\nJOIN \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TAXI_ZONE_GEOM\" dz\n    ON t.\"dropoff_location_id\" = dz.\"zone_id\"\nWHERE DATE(TO_TIMESTAMP(t.\"pickup_datetime\" / 1000000)) BETWEEN '2016-02-01' AND '2016-02-07'\n  AND (t.\"dropoff_datetime\" - t.\"pickup_datetime\") > 0\n  AND t.\"passenger_count\" > 3\n  AND t.\"trip_distance\" >= 10\n  AND pz.\"borough\" = 'Brooklyn'\n  AND dz.\"borough\" = 'Brooklyn';" := by
  first | sql_equiv | sorry

-- eq_1_2: needs a data hypothesis over multiple tables (not stated); likely `sorry`.
theorem eq_1_2 :
    sql%([TAXI_ZONE_GEOM_schema, TLC_YELLOW_TRIPS_2016_schema]) "SELECT \n  AVG(TIMESTAMPDIFF('MINUTE', TO_TIMESTAMP(t.\"pickup_datetime\" / 1000000), TO_TIMESTAMP(t.\"dropoff_datetime\" / 1000000))) AS AVG_DURATION\nFROM \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TLC_YELLOW_TRIPS_2016\" t\nJOIN \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TAXI_ZONE_GEOM\" pu \n  ON t.\"pickup_location_id\" = pu.\"zone_id\"\nJOIN \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TAXI_ZONE_GEOM\" do \n  ON t.\"dropoff_location_id\" = do.\"zone_id\"\nWHERE TO_TIMESTAMP(t.\"pickup_datetime\" / 1000000) >= '2016-02-01'\n  AND TO_TIMESTAMP(t.\"pickup_datetime\" / 1000000) < '2016-02-08'\n  AND t.\"passenger_count\" > 3\n  AND t.\"trip_distance\" >= 10\n  AND pu.\"borough\" = 'Brooklyn'\n  AND do.\"borough\" = 'Brooklyn'\n  AND (t.\"dropoff_datetime\" - t.\"pickup_datetime\") > 0;" = sql%([TAXI_ZONE_GEOM_schema, TLC_YELLOW_TRIPS_2016_schema]) "SELECT\n    AVG(\n        (\"dropoff_datetime\" - \"pickup_datetime\") / 1000000.0 / 60.0\n    ) AS \"AVG_DURATION\"\nFROM \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TLC_YELLOW_TRIPS_2016\" t\nJOIN \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TAXI_ZONE_GEOM\" pz\n    ON CAST(t.\"pickup_location_id\" AS VARCHAR) = pz.\"zone_id\"\nJOIN \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TAXI_ZONE_GEOM\" dz\n    ON CAST(t.\"dropoff_location_id\" AS VARCHAR) = dz.\"zone_id\"\nWHERE\n    TO_TIMESTAMP(t.\"pickup_datetime\" / 1000000) >= '2016-02-01'\n    AND TO_TIMESTAMP(t.\"pickup_datetime\" / 1000000) < '2016-02-08'\n    AND t.\"dropoff_datetime\" > t.\"pickup_datetime\"\n    AND t.\"passenger_count\" > 3\n    AND t.\"trip_distance\" >= 10\n    AND pz.\"borough\" = 'Brooklyn'\n    AND dz.\"borough\" = 'Brooklyn';" := by
  first | sql_equiv | sorry

-- eq_1_3: needs a data hypothesis over multiple tables (not stated); likely `sorry`.
theorem eq_1_3 :
    sql%([TAXI_ZONE_GEOM_schema, TLC_YELLOW_TRIPS_2016_schema]) "SELECT \n  AVG(TIMESTAMPDIFF('MINUTE', TO_TIMESTAMP(t.\"pickup_datetime\" / 1000000), TO_TIMESTAMP(t.\"dropoff_datetime\" / 1000000))) AS AVG_DURATION\nFROM \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TLC_YELLOW_TRIPS_2016\" t\nJOIN \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TAXI_ZONE_GEOM\" pu \n  ON t.\"pickup_location_id\" = pu.\"zone_id\"\nJOIN \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TAXI_ZONE_GEOM\" do \n  ON t.\"dropoff_location_id\" = do.\"zone_id\"\nWHERE TO_TIMESTAMP(t.\"pickup_datetime\" / 1000000) >= '2016-02-01'\n  AND TO_TIMESTAMP(t.\"pickup_datetime\" / 1000000) < '2016-02-08'\n  AND t.\"passenger_count\" > 3\n  AND t.\"trip_distance\" >= 10\n  AND pu.\"borough\" = 'Brooklyn'\n  AND do.\"borough\" = 'Brooklyn'\n  AND (t.\"dropoff_datetime\" - t.\"pickup_datetime\") > 0;" = sql%([TAXI_ZONE_GEOM_schema, TLC_YELLOW_TRIPS_2016_schema]) "SELECT \n    AVG(TIMESTAMPDIFF('MINUTE', TO_TIMESTAMP(t.\"pickup_datetime\" / 1000000), TO_TIMESTAMP(t.\"dropoff_datetime\" / 1000000))) AS AVG_DURATION\nFROM \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TLC_YELLOW_TRIPS_2016\" t\nJOIN \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TAXI_ZONE_GEOM\" pz\n    ON t.\"pickup_location_id\" = pz.\"zone_id\"\nJOIN \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TAXI_ZONE_GEOM\" dz\n    ON t.\"dropoff_location_id\" = dz.\"zone_id\"\nWHERE DATE(TO_TIMESTAMP(t.\"pickup_datetime\" / 1000000)) BETWEEN '2016-02-01' AND '2016-02-07'\n  AND (t.\"dropoff_datetime\" - t.\"pickup_datetime\") > 0\n  AND t.\"passenger_count\" > 3\n  AND t.\"trip_distance\" >= 10\n  AND pz.\"borough\" = 'Brooklyn'\n  AND dz.\"borough\" = 'Brooklyn';" := by
  first | sql_equiv | sorry

theorem eq_2_3 :
    sql%([TAXI_ZONE_GEOM_schema, TLC_YELLOW_TRIPS_2016_schema]) "SELECT\n    AVG(\n        (\"dropoff_datetime\" - \"pickup_datetime\") / 1000000.0 / 60.0\n    ) AS \"AVG_DURATION\"\nFROM \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TLC_YELLOW_TRIPS_2016\" t\nJOIN \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TAXI_ZONE_GEOM\" pz\n    ON CAST(t.\"pickup_location_id\" AS VARCHAR) = pz.\"zone_id\"\nJOIN \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TAXI_ZONE_GEOM\" dz\n    ON CAST(t.\"dropoff_location_id\" AS VARCHAR) = dz.\"zone_id\"\nWHERE\n    TO_TIMESTAMP(t.\"pickup_datetime\" / 1000000) >= '2016-02-01'\n    AND TO_TIMESTAMP(t.\"pickup_datetime\" / 1000000) < '2016-02-08'\n    AND t.\"dropoff_datetime\" > t.\"pickup_datetime\"\n    AND t.\"passenger_count\" > 3\n    AND t.\"trip_distance\" >= 10\n    AND pz.\"borough\" = 'Brooklyn'\n    AND dz.\"borough\" = 'Brooklyn';" = sql%([TAXI_ZONE_GEOM_schema, TLC_YELLOW_TRIPS_2016_schema]) "SELECT \n    AVG(TIMESTAMPDIFF('MINUTE', TO_TIMESTAMP(t.\"pickup_datetime\" / 1000000), TO_TIMESTAMP(t.\"dropoff_datetime\" / 1000000))) AS AVG_DURATION\nFROM \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TLC_YELLOW_TRIPS_2016\" t\nJOIN \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TAXI_ZONE_GEOM\" pz\n    ON t.\"pickup_location_id\" = pz.\"zone_id\"\nJOIN \"NEW_YORK_PLUS\".\"NEW_YORK_TAXI_TRIPS\".\"TAXI_ZONE_GEOM\" dz\n    ON t.\"dropoff_location_id\" = dz.\"zone_id\"\nWHERE DATE(TO_TIMESTAMP(t.\"pickup_datetime\" / 1000000)) BETWEEN '2016-02-01' AND '2016-02-07'\n  AND (t.\"dropoff_datetime\" - t.\"pickup_datetime\") > 0\n  AND t.\"passenger_count\" > 3\n  AND t.\"trip_distance\" >= 10\n  AND pz.\"borough\" = 'Brooklyn'\n  AND dz.\"borough\" = 'Brooklyn';" := by
  first | sql_equiv | sorry

end Bench_sf_bq185
