import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_bq100 — crossskill equivalence(s)

Question: How can we identify the top 10 most frequently used packages in GitHub repository contents by looking for import statements enclosed in parentheses, splitting any multi-line imports by newlines, extracting package names that appear within double quotes, counting how often these packages appear, ignoring any null results, and finally ordering them in descending order of their frequency? The final answer should remove the quotation marks.

NOTE: uses WITH RECURSIVE / LATERAL / FLATTEN — may not elaborate yet.

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_bq100

CREATE TABLE SAMPLE_CONTENTS («id» STRING, «size» INT, «content» STRING, «binary» BOOL, «copies» INT, «sample_repo_name» STRING, «sample_ref» STRING, «sample_path» STRING, «sample_mode» INT, «sample_symlink_target» STRING)

HYPOTHESIS hyp0_1_0 : SAMPLE_CONTENTS "(\"content\" LIKE '%import (%' OR \"content\" LIKE '%import(%')"
HYPOTHESIS hyp0_1_1 : SAMPLE_CONTENTS "REGEXP_SUBSTR(\"content\", 'import\\\\s*\\\\([^)]+\\\\)', 1, 1, 's') IS NOT NULL"
theorem eq_0_1 (t : TableRel SAMPLE_CONTENTS_schema) (h0 : hyp0_1_0 t) (h1 : hyp0_1_1 t) :
    (sql%([SAMPLE_CONTENTS_schema]) "-- sf_bq100: Top 10 most frequently used packages from Go import statements\n-- Approach: Extract import blocks enclosed in parentheses, split by newlines,\n-- extract double-quoted package names, count frequency, remove quotes\nSELECT \n  REPLACE(REGEXP_SUBSTR(line.VALUE::STRING, '\"[^\"]+\"'), '\"', '') AS package,\n  COUNT(*) AS f0_\nFROM \"GITHUB_REPOS\".\"GITHUB_REPOS\".\"SAMPLE_CONTENTS\",\n  LATERAL FLATTEN(input => SPLIT(\n    REGEXP_SUBSTR(\"content\", 'import\\\\s*\\\\([^)]+\\\\)', 1, 1, 's'), \n    '\\n'\n  )) AS line\nWHERE (\"content\" LIKE '%import (%' OR \"content\" LIKE '%import(%')\n  AND REGEXP_SUBSTR(\"content\", 'import\\\\s*\\\\([^)]+\\\\)', 1, 1, 's') IS NOT NULL\n  AND REPLACE(REGEXP_SUBSTR(line.VALUE::STRING, '\"[^\"]+\"'), '\"', '') IS NOT NULL\nGROUP BY package\nORDER BY f0_ DESC, package ASC\nLIMIT 10;") t ~= (sql%([SAMPLE_CONTENTS_schema]) "WITH import_blocks AS (\n  SELECT REGEXP_SUBSTR(\"content\", 'import \\\\(([^)]+)\\\\)', 1, 1, 's', 1) AS import_block\n  FROM \"GITHUB_REPOS\".\"GITHUB_REPOS\".\"SAMPLE_CONTENTS\"\n  WHERE \"content\" LIKE '%import (%'\n),\nsplit_lines AS (\n  SELECT TRIM(value) AS line\n  FROM import_blocks, LATERAL SPLIT_TO_TABLE(import_block, '\\n')\n  WHERE TRIM(value) != ''\n),\npackages AS (\n  SELECT REGEXP_SUBSTR(line, '\"([^\"]+)\"', 1, 1, '', 1) AS package\n  FROM split_lines\n)\nSELECT package AS \"PACKAGE\", COUNT(*) AS \"F0_\"\nFROM packages\nWHERE package IS NOT NULL\nGROUP BY package\nORDER BY \"F0_\" DESC\nLIMIT 10;") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp0_2_0 : SAMPLE_CONTENTS "(\"content\" LIKE '%import (%' OR \"content\" LIKE '%import(%')"
HYPOTHESIS hyp0_2_1 : SAMPLE_CONTENTS "REGEXP_SUBSTR(\"content\", 'import\\\\s*\\\\([^)]+\\\\)', 1, 1, 's') IS NOT NULL"
theorem eq_0_2 (t : TableRel SAMPLE_CONTENTS_schema) (h0 : hyp0_2_0 t) (h1 : hyp0_2_1 t) :
    (sql%([SAMPLE_CONTENTS_schema]) "-- sf_bq100: Top 10 most frequently used packages from Go import statements\n-- Approach: Extract import blocks enclosed in parentheses, split by newlines,\n-- extract double-quoted package names, count frequency, remove quotes\nSELECT \n  REPLACE(REGEXP_SUBSTR(line.VALUE::STRING, '\"[^\"]+\"'), '\"', '') AS package,\n  COUNT(*) AS f0_\nFROM \"GITHUB_REPOS\".\"GITHUB_REPOS\".\"SAMPLE_CONTENTS\",\n  LATERAL FLATTEN(input => SPLIT(\n    REGEXP_SUBSTR(\"content\", 'import\\\\s*\\\\([^)]+\\\\)', 1, 1, 's'), \n    '\\n'\n  )) AS line\nWHERE (\"content\" LIKE '%import (%' OR \"content\" LIKE '%import(%')\n  AND REGEXP_SUBSTR(\"content\", 'import\\\\s*\\\\([^)]+\\\\)', 1, 1, 's') IS NOT NULL\n  AND REPLACE(REGEXP_SUBSTR(line.VALUE::STRING, '\"[^\"]+\"'), '\"', '') IS NOT NULL\nGROUP BY package\nORDER BY f0_ DESC, package ASC\nLIMIT 10;") t ~= (sql%([SAMPLE_CONTENTS_schema]) "WITH import_blocks AS (\n    SELECT REGEXP_SUBSTR(\"content\", 'import \\\\([^)]*\\\\)', 1, 1, 's') AS block\n    FROM \"GITHUB_REPOS\".\"GITHUB_REPOS\".\"SAMPLE_CONTENTS\" \n    WHERE \"content\" LIKE '%import (%' \n),\nsplit_lines AS (\n    SELECT TRIM(pkg.VALUE::STRING) AS line\n    FROM import_blocks,\n    LATERAL FLATTEN(INPUT => SPLIT(block, '\\n')) pkg\n    WHERE block IS NOT NULL\n),\npackages AS (\n    SELECT REGEXP_SUBSTR(line, '\"([^\"]*)\"', 1, 1, 'e') AS package\n    FROM split_lines\n)\nSELECT package AS \"PACKAGE\", COUNT(*) AS \"F0_\"\nFROM packages\nWHERE package IS NOT NULL\nGROUP BY package\nORDER BY \"F0_\" DESC, \"PACKAGE\" ASC\nLIMIT 10;") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp0_3_0 : SAMPLE_CONTENTS "(\"content\" LIKE '%import (%' OR \"content\" LIKE '%import(%')"
HYPOTHESIS hyp0_3_1 : SAMPLE_CONTENTS "REGEXP_SUBSTR(\"content\", 'import\\\\s*\\\\([^)]+\\\\)', 1, 1, 's') IS NOT NULL"
theorem eq_0_3 (t : TableRel SAMPLE_CONTENTS_schema) (h0 : hyp0_3_0 t) (h1 : hyp0_3_1 t) :
    (sql%([SAMPLE_CONTENTS_schema]) "-- sf_bq100: Top 10 most frequently used packages from Go import statements\n-- Approach: Extract import blocks enclosed in parentheses, split by newlines,\n-- extract double-quoted package names, count frequency, remove quotes\nSELECT \n  REPLACE(REGEXP_SUBSTR(line.VALUE::STRING, '\"[^\"]+\"'), '\"', '') AS package,\n  COUNT(*) AS f0_\nFROM \"GITHUB_REPOS\".\"GITHUB_REPOS\".\"SAMPLE_CONTENTS\",\n  LATERAL FLATTEN(input => SPLIT(\n    REGEXP_SUBSTR(\"content\", 'import\\\\s*\\\\([^)]+\\\\)', 1, 1, 's'), \n    '\\n'\n  )) AS line\nWHERE (\"content\" LIKE '%import (%' OR \"content\" LIKE '%import(%')\n  AND REGEXP_SUBSTR(\"content\", 'import\\\\s*\\\\([^)]+\\\\)', 1, 1, 's') IS NOT NULL\n  AND REPLACE(REGEXP_SUBSTR(line.VALUE::STRING, '\"[^\"]+\"'), '\"', '') IS NOT NULL\nGROUP BY package\nORDER BY f0_ DESC, package ASC\nLIMIT 10;") t ~= (sql%([SAMPLE_CONTENTS_schema]) "WITH import_blocks AS (\n    SELECT REGEXP_SUBSTR(\"content\", 'import \\\\(([^)]+)\\\\)', 1, 1, 'es', 1) AS import_block\n    FROM \"GITHUB_REPOS\".\"GITHUB_REPOS\".\"SAMPLE_CONTENTS\"\n    WHERE \"content\" LIKE '%import (%'\n),\nlines AS (\n    SELECT TRIM(f.value::STRING) AS line\n    FROM import_blocks, \n    LATERAL FLATTEN(input => SPLIT(import_block, '\\n')) f\n    WHERE TRIM(f.value::STRING) <> ''\n),\npackages AS (\n    SELECT REGEXP_SUBSTR(line, '\"([^\"]+)\"', 1, 1, 'e', 1) AS package\n    FROM lines\n    WHERE line LIKE '%\"%'\n)\nSELECT package, COUNT(*) AS f0_\nFROM packages\nWHERE package IS NOT NULL\nGROUP BY package\nORDER BY f0_ DESC, package ASC\nLIMIT 10;") t := by
  first | sql_equiv | sorry

theorem eq_1_2 : ∀ t,
    (sql%([SAMPLE_CONTENTS_schema]) "WITH import_blocks AS (\n  SELECT REGEXP_SUBSTR(\"content\", 'import \\\\(([^)]+)\\\\)', 1, 1, 's', 1) AS import_block\n  FROM \"GITHUB_REPOS\".\"GITHUB_REPOS\".\"SAMPLE_CONTENTS\"\n  WHERE \"content\" LIKE '%import (%'\n),\nsplit_lines AS (\n  SELECT TRIM(value) AS line\n  FROM import_blocks, LATERAL SPLIT_TO_TABLE(import_block, '\\n')\n  WHERE TRIM(value) != ''\n),\npackages AS (\n  SELECT REGEXP_SUBSTR(line, '\"([^\"]+)\"', 1, 1, '', 1) AS package\n  FROM split_lines\n)\nSELECT package AS \"PACKAGE\", COUNT(*) AS \"F0_\"\nFROM packages\nWHERE package IS NOT NULL\nGROUP BY package\nORDER BY \"F0_\" DESC\nLIMIT 10;") t ~= (sql%([SAMPLE_CONTENTS_schema]) "WITH import_blocks AS (\n    SELECT REGEXP_SUBSTR(\"content\", 'import \\\\([^)]*\\\\)', 1, 1, 's') AS block\n    FROM \"GITHUB_REPOS\".\"GITHUB_REPOS\".\"SAMPLE_CONTENTS\" \n    WHERE \"content\" LIKE '%import (%' \n),\nsplit_lines AS (\n    SELECT TRIM(pkg.VALUE::STRING) AS line\n    FROM import_blocks,\n    LATERAL FLATTEN(INPUT => SPLIT(block, '\\n')) pkg\n    WHERE block IS NOT NULL\n),\npackages AS (\n    SELECT REGEXP_SUBSTR(line, '\"([^\"]*)\"', 1, 1, 'e') AS package\n    FROM split_lines\n)\nSELECT package AS \"PACKAGE\", COUNT(*) AS \"F0_\"\nFROM packages\nWHERE package IS NOT NULL\nGROUP BY package\nORDER BY \"F0_\" DESC, \"PACKAGE\" ASC\nLIMIT 10;") t := by
  intro t; first | sql_equiv | sorry

HYPOTHESIS hyp1_3_0 : SAMPLE_CONTENTS "REGEXP_SUBSTR(\"content\", 'import \\\\(([^)]+)\\\\)', 1, 1, 's', 1) = REGEXP_SUBSTR(\"content\", 'import \\\\(([^)]+)\\\\)', 1, 1, 'es', 1)"
theorem eq_1_3 (t : TableRel SAMPLE_CONTENTS_schema) (h0 : hyp1_3_0 t) :
    (sql%([SAMPLE_CONTENTS_schema]) "WITH import_blocks AS (\n  SELECT REGEXP_SUBSTR(\"content\", 'import \\\\(([^)]+)\\\\)', 1, 1, 's', 1) AS import_block\n  FROM \"GITHUB_REPOS\".\"GITHUB_REPOS\".\"SAMPLE_CONTENTS\"\n  WHERE \"content\" LIKE '%import (%'\n),\nsplit_lines AS (\n  SELECT TRIM(value) AS line\n  FROM import_blocks, LATERAL SPLIT_TO_TABLE(import_block, '\\n')\n  WHERE TRIM(value) != ''\n),\npackages AS (\n  SELECT REGEXP_SUBSTR(line, '\"([^\"]+)\"', 1, 1, '', 1) AS package\n  FROM split_lines\n)\nSELECT package AS \"PACKAGE\", COUNT(*) AS \"F0_\"\nFROM packages\nWHERE package IS NOT NULL\nGROUP BY package\nORDER BY \"F0_\" DESC\nLIMIT 10;") t = (sql%([SAMPLE_CONTENTS_schema]) "WITH import_blocks AS (\n    SELECT REGEXP_SUBSTR(\"content\", 'import \\\\(([^)]+)\\\\)', 1, 1, 'es', 1) AS import_block\n    FROM \"GITHUB_REPOS\".\"GITHUB_REPOS\".\"SAMPLE_CONTENTS\"\n    WHERE \"content\" LIKE '%import (%'\n),\nlines AS (\n    SELECT TRIM(f.value::STRING) AS line\n    FROM import_blocks, \n    LATERAL FLATTEN(input => SPLIT(import_block, '\\n')) f\n    WHERE TRIM(f.value::STRING) <> ''\n),\npackages AS (\n    SELECT REGEXP_SUBSTR(line, '\"([^\"]+)\"', 1, 1, 'e', 1) AS package\n    FROM lines\n    WHERE line LIKE '%\"%'\n)\nSELECT package, COUNT(*) AS f0_\nFROM packages\nWHERE package IS NOT NULL\nGROUP BY package\nORDER BY f0_ DESC, package ASC\nLIMIT 10;") t := by
  first | sql_equiv | sorry

theorem eq_2_3 : ∀ t,
    (sql%([SAMPLE_CONTENTS_schema]) "WITH import_blocks AS (\n    SELECT REGEXP_SUBSTR(\"content\", 'import \\\\([^)]*\\\\)', 1, 1, 's') AS block\n    FROM \"GITHUB_REPOS\".\"GITHUB_REPOS\".\"SAMPLE_CONTENTS\" \n    WHERE \"content\" LIKE '%import (%' \n),\nsplit_lines AS (\n    SELECT TRIM(pkg.VALUE::STRING) AS line\n    FROM import_blocks,\n    LATERAL FLATTEN(INPUT => SPLIT(block, '\\n')) pkg\n    WHERE block IS NOT NULL\n),\npackages AS (\n    SELECT REGEXP_SUBSTR(line, '\"([^\"]*)\"', 1, 1, 'e') AS package\n    FROM split_lines\n)\nSELECT package AS \"PACKAGE\", COUNT(*) AS \"F0_\"\nFROM packages\nWHERE package IS NOT NULL\nGROUP BY package\nORDER BY \"F0_\" DESC, \"PACKAGE\" ASC\nLIMIT 10;") t ~= (sql%([SAMPLE_CONTENTS_schema]) "WITH import_blocks AS (\n    SELECT REGEXP_SUBSTR(\"content\", 'import \\\\(([^)]+)\\\\)', 1, 1, 'es', 1) AS import_block\n    FROM \"GITHUB_REPOS\".\"GITHUB_REPOS\".\"SAMPLE_CONTENTS\"\n    WHERE \"content\" LIKE '%import (%'\n),\nlines AS (\n    SELECT TRIM(f.value::STRING) AS line\n    FROM import_blocks, \n    LATERAL FLATTEN(input => SPLIT(import_block, '\\n')) f\n    WHERE TRIM(f.value::STRING) <> ''\n),\npackages AS (\n    SELECT REGEXP_SUBSTR(line, '\"([^\"]+)\"', 1, 1, 'e', 1) AS package\n    FROM lines\n    WHERE line LIKE '%\"%'\n)\nSELECT package, COUNT(*) AS f0_\nFROM packages\nWHERE package IS NOT NULL\nGROUP BY package\nORDER BY f0_ DESC, package ASC\nLIMIT 10;") t := by
  intro t; first | sql_equiv | sorry

end Bench_sf_bq100
