import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_bq199 — crossskill equivalence(s)

Question: Identify the top 10 liquor categories in Iowa in 2021 by calculating, for each category, the average of the per-liter retail prices across all sales transactions in that category during 2021. For these top categories, provide their average per-liter retail prices calculated in the same manner for the years 2019, 2020, and 2021.

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_bq199

CREATE TABLE SALES («invoice_and_item_number» STRING, «date» STRING, «store_number» STRING, «store_name» STRING, «address» STRING, «city» STRING, «zip_code» STRING, «store_location» STRING, «county_number» STRING, «county» STRING, «category» STRING, «category_name» STRING, «vendor_number» STRING, «vendor_name» STRING, «item_number» STRING, «item_description» STRING, «pack» INT, «bottle_volume_ml» INT, «state_bottle_cost» FLOAT, «state_bottle_retail» FLOAT, «bottles_sold» INT, «sale_dollars» FLOAT, «volume_sold_liters» FLOAT, «volume_sold_gallons» FLOAT)

HYPOTHESIS hyp0_1_0 : SALES "EXTRACT(YEAR FROM \"date\") IN (2019, 2020, 2021)"
HYPOTHESIS hyp0_1_1 : SALES "NOT \"category_name\" IS NULL"
HYPOTHESIS hyp0_1_2 : SALES "EXTRACT(YEAR FROM \"date\") = 2021"
HYPOTHESIS hyp0_1_3 : SALES "\"bottle_volume_ml\" > 0"
theorem eq_0_1 (t : TableRel SALES_schema) (h0 : hyp0_1_0 t) (h1 : hyp0_1_1 t) (h2 : hyp0_1_2 t) (h3 : hyp0_1_3 t) :
    (sql%([SALES_schema]) "WITH per_liter_prices AS (SELECT \"category_name\", EXTRACT(YEAR FROM \"date\") AS sale_year, CAST(\"state_bottle_retail\" AS DOUBLE PRECISION) / (CAST(\"bottle_volume_ml\" AS DOUBLE PRECISION) / 1000.0) AS per_liter_retail_price FROM \"IOWA_LIQUOR_SALES\".\"IOWA_LIQUOR_SALES\".\"SALES\" WHERE EXTRACT(YEAR FROM \"date\") IN (2019, 2020, 2021) AND NOT \"category_name\" IS NULL AND \"bottle_volume_ml\" > 0), top10_2021 AS (SELECT \"category_name\", AVG(per_liter_retail_price) AS avg_price_2021 FROM per_liter_prices WHERE sale_year = 2021 GROUP BY \"category_name\" ORDER BY avg_price_2021 DESC LIMIT 10) SELECT t.\"category_name\" AS category, AVG(CASE WHEN p.sale_year = 2019 THEN p.per_liter_retail_price END) AS avg_price_liter_2019, AVG(CASE WHEN p.sale_year = 2020 THEN p.per_liter_retail_price END) AS avg_price_liter_2020, AVG(CASE WHEN p.sale_year = 2021 THEN p.per_liter_retail_price END) AS avg_price_liter_2021 FROM top10_2021 AS t LEFT JOIN per_liter_prices AS p ON t.\"category_name\" = p.\"category_name\" GROUP BY t.\"category_name\" ORDER BY avg_price_liter_2021 DESC") t ~= (sql%([SALES_schema]) "WITH top10_2021 AS (SELECT \"category_name\" AS category, AVG(CAST(\"state_bottle_retail\" AS DOUBLE PRECISION) / (CAST(\"bottle_volume_ml\" AS DOUBLE PRECISION) / 1000.0)) AS avg_price_liter_2021 FROM \"IOWA_LIQUOR_SALES\".\"IOWA_LIQUOR_SALES\".\"SALES\" WHERE EXTRACT(YEAR FROM \"date\") = 2021 AND \"bottle_volume_ml\" > 0 GROUP BY \"category_name\" ORDER BY avg_price_liter_2021 DESC LIMIT 10), all_years AS (SELECT \"category_name\" AS category, EXTRACT(YEAR FROM \"date\") AS yr, AVG(CAST(\"state_bottle_retail\" AS DOUBLE PRECISION) / (CAST(\"bottle_volume_ml\" AS DOUBLE PRECISION) / 1000.0)) AS avg_price_per_liter FROM \"IOWA_LIQUOR_SALES\".\"IOWA_LIQUOR_SALES\".\"SALES\" WHERE EXTRACT(YEAR FROM \"date\") IN (2019, 2020, 2021) AND \"bottle_volume_ml\" > 0 AND \"category_name\" IN (SELECT category FROM top10_2021) GROUP BY \"category_name\", yr) SELECT t.category, MAX(CASE WHEN a.yr = 2019 THEN a.avg_price_per_liter END) AS avg_price_liter_2019, MAX(CASE WHEN a.yr = 2020 THEN a.avg_price_per_liter END) AS avg_price_liter_2020, t.avg_price_liter_2021 FROM top10_2021 AS t LEFT JOIN all_years AS a ON t.category = a.category GROUP BY t.category, t.avg_price_liter_2021 ORDER BY t.avg_price_liter_2021 DESC") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp0_2_0 : SALES "EXTRACT(YEAR FROM \"date\") IN (2019, 2020, 2021)"
HYPOTHESIS hyp0_2_1 : SALES "EXTRACT(YEAR FROM \"date\") = 2021"
HYPOTHESIS hyp0_2_2 : SALES "\"bottle_volume_ml\" > 0"
theorem eq_0_2 (t : TableRel SALES_schema) (h0 : hyp0_2_0 t) (h1 : hyp0_2_1 t) (h2 : hyp0_2_2 t) :
    (sql%([SALES_schema]) "WITH per_liter_prices AS (SELECT \"category_name\", EXTRACT(YEAR FROM \"date\") AS sale_year, CAST(\"state_bottle_retail\" AS DOUBLE PRECISION) / (CAST(\"bottle_volume_ml\" AS DOUBLE PRECISION) / 1000.0) AS per_liter_retail_price FROM \"IOWA_LIQUOR_SALES\".\"IOWA_LIQUOR_SALES\".\"SALES\" WHERE EXTRACT(YEAR FROM \"date\") IN (2019, 2020, 2021) AND NOT \"category_name\" IS NULL AND \"bottle_volume_ml\" > 0), top10_2021 AS (SELECT \"category_name\", AVG(per_liter_retail_price) AS avg_price_2021 FROM per_liter_prices WHERE sale_year = 2021 GROUP BY \"category_name\" ORDER BY avg_price_2021 DESC LIMIT 10) SELECT t.\"category_name\" AS category, AVG(CASE WHEN p.sale_year = 2019 THEN p.per_liter_retail_price END) AS avg_price_liter_2019, AVG(CASE WHEN p.sale_year = 2020 THEN p.per_liter_retail_price END) AS avg_price_liter_2020, AVG(CASE WHEN p.sale_year = 2021 THEN p.per_liter_retail_price END) AS avg_price_liter_2021 FROM top10_2021 AS t LEFT JOIN per_liter_prices AS p ON t.\"category_name\" = p.\"category_name\" GROUP BY t.\"category_name\" ORDER BY avg_price_liter_2021 DESC") t ~= (sql%([SALES_schema]) "WITH top_categories AS (SELECT \"category_name\", AVG(CAST(\"state_bottle_retail\" AS DOUBLE PRECISION) / \"bottle_volume_ml\" * 1000) AS avg_price_2021 FROM \"IOWA_LIQUOR_SALES\".\"IOWA_LIQUOR_SALES\".\"SALES\" WHERE EXTRACT(YEAR FROM \"date\") = 2021 AND \"bottle_volume_ml\" > 0 AND NOT \"category_name\" IS NULL GROUP BY \"category_name\" ORDER BY avg_price_2021 DESC LIMIT 10) SELECT s.\"category_name\" AS \"category\", ROUND(CAST(AVG(CASE WHEN EXTRACT(YEAR FROM s.\"date\") = 2019 THEN CAST(s.\"state_bottle_retail\" AS DOUBLE PRECISION) / s.\"bottle_volume_ml\" * 1000 END) AS DECIMAL), 2) AS \"avg_price_liter_2019\", ROUND(CAST(AVG(CASE WHEN EXTRACT(YEAR FROM s.\"date\") = 2020 THEN CAST(s.\"state_bottle_retail\" AS DOUBLE PRECISION) / s.\"bottle_volume_ml\" * 1000 END) AS DECIMAL), 2) AS \"avg_price_liter_2020\", ROUND(CAST(AVG(CASE WHEN EXTRACT(YEAR FROM s.\"date\") = 2021 THEN CAST(s.\"state_bottle_retail\" AS DOUBLE PRECISION) / s.\"bottle_volume_ml\" * 1000 END) AS DECIMAL), 2) AS \"avg_price_liter_2021\" FROM \"IOWA_LIQUOR_SALES\".\"IOWA_LIQUOR_SALES\".\"SALES\" AS s JOIN top_categories AS tc ON s.\"category_name\" = tc.\"category_name\" WHERE EXTRACT(YEAR FROM s.\"date\") IN (2019, 2020, 2021) AND s.\"bottle_volume_ml\" > 0 GROUP BY s.\"category_name\" ORDER BY \"avg_price_liter_2021\" DESC") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp0_3_0 : SALES "EXTRACT(YEAR FROM \"date\") IN (2019, 2020, 2021)"
HYPOTHESIS hyp0_3_1 : SALES "NOT \"category_name\" IS NULL"
theorem eq_0_3 (t : TableRel SALES_schema) (h0 : hyp0_3_0 t) (h1 : hyp0_3_1 t) :
    (sql%([SALES_schema]) "WITH per_liter_prices AS (SELECT \"category_name\", EXTRACT(YEAR FROM \"date\") AS sale_year, CAST(\"state_bottle_retail\" AS DOUBLE PRECISION) / (CAST(\"bottle_volume_ml\" AS DOUBLE PRECISION) / 1000.0) AS per_liter_retail_price FROM \"IOWA_LIQUOR_SALES\".\"IOWA_LIQUOR_SALES\".\"SALES\" WHERE EXTRACT(YEAR FROM \"date\") IN (2019, 2020, 2021) AND NOT \"category_name\" IS NULL AND \"bottle_volume_ml\" > 0), top10_2021 AS (SELECT \"category_name\", AVG(per_liter_retail_price) AS avg_price_2021 FROM per_liter_prices WHERE sale_year = 2021 GROUP BY \"category_name\" ORDER BY avg_price_2021 DESC LIMIT 10) SELECT t.\"category_name\" AS category, AVG(CASE WHEN p.sale_year = 2019 THEN p.per_liter_retail_price END) AS avg_price_liter_2019, AVG(CASE WHEN p.sale_year = 2020 THEN p.per_liter_retail_price END) AS avg_price_liter_2020, AVG(CASE WHEN p.sale_year = 2021 THEN p.per_liter_retail_price END) AS avg_price_liter_2021 FROM top10_2021 AS t LEFT JOIN per_liter_prices AS p ON t.\"category_name\" = p.\"category_name\" GROUP BY t.\"category_name\" ORDER BY avg_price_liter_2021 DESC") t ~= (sql%([SALES_schema]) "WITH per_liter AS (SELECT \"category_name\" AS category, EXTRACT(YEAR FROM \"date\") AS yr, CAST(\"state_bottle_retail\" AS DOUBLE PRECISION) / (CAST(\"bottle_volume_ml\" AS DOUBLE PRECISION) / 1000.0) AS price_per_liter FROM \"IOWA_LIQUOR_SALES\".\"IOWA_LIQUOR_SALES\".\"SALES\" WHERE EXTRACT(YEAR FROM \"date\") IN (2019, 2020, 2021)), top10 AS (SELECT category FROM per_liter WHERE yr = 2021 GROUP BY category ORDER BY AVG(price_per_liter) DESC LIMIT 10) SELECT t.category, AVG(CASE WHEN p.yr = 2019 THEN p.price_per_liter END) AS avg_price_liter_2019, AVG(CASE WHEN p.yr = 2020 THEN p.price_per_liter END) AS avg_price_liter_2020, AVG(CASE WHEN p.yr = 2021 THEN p.price_per_liter END) AS avg_price_liter_2021 FROM top10 AS t JOIN per_liter AS p ON t.category = p.category GROUP BY t.category ORDER BY avg_price_liter_2021 DESC") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp1_2_0 : SALES "NOT \"category_name\" IS NULL"
theorem eq_1_2 (t : TableRel SALES_schema) (h0 : hyp1_2_0 t) :
    (sql%([SALES_schema]) "WITH top10_2021 AS (SELECT \"category_name\" AS category, AVG(CAST(\"state_bottle_retail\" AS DOUBLE PRECISION) / (CAST(\"bottle_volume_ml\" AS DOUBLE PRECISION) / 1000.0)) AS avg_price_liter_2021 FROM \"IOWA_LIQUOR_SALES\".\"IOWA_LIQUOR_SALES\".\"SALES\" WHERE EXTRACT(YEAR FROM \"date\") = 2021 AND \"bottle_volume_ml\" > 0 GROUP BY \"category_name\" ORDER BY avg_price_liter_2021 DESC LIMIT 10), all_years AS (SELECT \"category_name\" AS category, EXTRACT(YEAR FROM \"date\") AS yr, AVG(CAST(\"state_bottle_retail\" AS DOUBLE PRECISION) / (CAST(\"bottle_volume_ml\" AS DOUBLE PRECISION) / 1000.0)) AS avg_price_per_liter FROM \"IOWA_LIQUOR_SALES\".\"IOWA_LIQUOR_SALES\".\"SALES\" WHERE EXTRACT(YEAR FROM \"date\") IN (2019, 2020, 2021) AND \"bottle_volume_ml\" > 0 AND \"category_name\" IN (SELECT category FROM top10_2021) GROUP BY \"category_name\", yr) SELECT t.category, MAX(CASE WHEN a.yr = 2019 THEN a.avg_price_per_liter END) AS avg_price_liter_2019, MAX(CASE WHEN a.yr = 2020 THEN a.avg_price_per_liter END) AS avg_price_liter_2020, t.avg_price_liter_2021 FROM top10_2021 AS t LEFT JOIN all_years AS a ON t.category = a.category GROUP BY t.category, t.avg_price_liter_2021 ORDER BY t.avg_price_liter_2021 DESC") t ~= (sql%([SALES_schema]) "WITH top_categories AS (SELECT \"category_name\", AVG(CAST(\"state_bottle_retail\" AS DOUBLE PRECISION) / \"bottle_volume_ml\" * 1000) AS avg_price_2021 FROM \"IOWA_LIQUOR_SALES\".\"IOWA_LIQUOR_SALES\".\"SALES\" WHERE EXTRACT(YEAR FROM \"date\") = 2021 AND \"bottle_volume_ml\" > 0 AND NOT \"category_name\" IS NULL GROUP BY \"category_name\" ORDER BY avg_price_2021 DESC LIMIT 10) SELECT s.\"category_name\" AS \"category\", ROUND(CAST(AVG(CASE WHEN EXTRACT(YEAR FROM s.\"date\") = 2019 THEN CAST(s.\"state_bottle_retail\" AS DOUBLE PRECISION) / s.\"bottle_volume_ml\" * 1000 END) AS DECIMAL), 2) AS \"avg_price_liter_2019\", ROUND(CAST(AVG(CASE WHEN EXTRACT(YEAR FROM s.\"date\") = 2020 THEN CAST(s.\"state_bottle_retail\" AS DOUBLE PRECISION) / s.\"bottle_volume_ml\" * 1000 END) AS DECIMAL), 2) AS \"avg_price_liter_2020\", ROUND(CAST(AVG(CASE WHEN EXTRACT(YEAR FROM s.\"date\") = 2021 THEN CAST(s.\"state_bottle_retail\" AS DOUBLE PRECISION) / s.\"bottle_volume_ml\" * 1000 END) AS DECIMAL), 2) AS \"avg_price_liter_2021\" FROM \"IOWA_LIQUOR_SALES\".\"IOWA_LIQUOR_SALES\".\"SALES\" AS s JOIN top_categories AS tc ON s.\"category_name\" = tc.\"category_name\" WHERE EXTRACT(YEAR FROM s.\"date\") IN (2019, 2020, 2021) AND s.\"bottle_volume_ml\" > 0 GROUP BY s.\"category_name\" ORDER BY \"avg_price_liter_2021\" DESC") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp1_3_0 : SALES "EXTRACT(YEAR FROM \"date\") = 2021"
HYPOTHESIS hyp1_3_1 : SALES "\"bottle_volume_ml\" > 0"
theorem eq_1_3 (t : TableRel SALES_schema) (h0 : hyp1_3_0 t) (h1 : hyp1_3_1 t) :
    (sql%([SALES_schema]) "WITH top10_2021 AS (SELECT \"category_name\" AS category, AVG(CAST(\"state_bottle_retail\" AS DOUBLE PRECISION) / (CAST(\"bottle_volume_ml\" AS DOUBLE PRECISION) / 1000.0)) AS avg_price_liter_2021 FROM \"IOWA_LIQUOR_SALES\".\"IOWA_LIQUOR_SALES\".\"SALES\" WHERE EXTRACT(YEAR FROM \"date\") = 2021 AND \"bottle_volume_ml\" > 0 GROUP BY \"category_name\" ORDER BY avg_price_liter_2021 DESC LIMIT 10), all_years AS (SELECT \"category_name\" AS category, EXTRACT(YEAR FROM \"date\") AS yr, AVG(CAST(\"state_bottle_retail\" AS DOUBLE PRECISION) / (CAST(\"bottle_volume_ml\" AS DOUBLE PRECISION) / 1000.0)) AS avg_price_per_liter FROM \"IOWA_LIQUOR_SALES\".\"IOWA_LIQUOR_SALES\".\"SALES\" WHERE EXTRACT(YEAR FROM \"date\") IN (2019, 2020, 2021) AND \"bottle_volume_ml\" > 0 AND \"category_name\" IN (SELECT category FROM top10_2021) GROUP BY \"category_name\", yr) SELECT t.category, MAX(CASE WHEN a.yr = 2019 THEN a.avg_price_per_liter END) AS avg_price_liter_2019, MAX(CASE WHEN a.yr = 2020 THEN a.avg_price_per_liter END) AS avg_price_liter_2020, t.avg_price_liter_2021 FROM top10_2021 AS t LEFT JOIN all_years AS a ON t.category = a.category GROUP BY t.category, t.avg_price_liter_2021 ORDER BY t.avg_price_liter_2021 DESC") t ~= (sql%([SALES_schema]) "WITH per_liter AS (SELECT \"category_name\" AS category, EXTRACT(YEAR FROM \"date\") AS yr, CAST(\"state_bottle_retail\" AS DOUBLE PRECISION) / (CAST(\"bottle_volume_ml\" AS DOUBLE PRECISION) / 1000.0) AS price_per_liter FROM \"IOWA_LIQUOR_SALES\".\"IOWA_LIQUOR_SALES\".\"SALES\" WHERE EXTRACT(YEAR FROM \"date\") IN (2019, 2020, 2021)), top10 AS (SELECT category FROM per_liter WHERE yr = 2021 GROUP BY category ORDER BY AVG(price_per_liter) DESC LIMIT 10) SELECT t.category, AVG(CASE WHEN p.yr = 2019 THEN p.price_per_liter END) AS avg_price_liter_2019, AVG(CASE WHEN p.yr = 2020 THEN p.price_per_liter END) AS avg_price_liter_2020, AVG(CASE WHEN p.yr = 2021 THEN p.price_per_liter END) AS avg_price_liter_2021 FROM top10 AS t JOIN per_liter AS p ON t.category = p.category GROUP BY t.category ORDER BY avg_price_liter_2021 DESC") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp2_3_0 : SALES "EXTRACT(YEAR FROM \"date\") = 2021"
HYPOTHESIS hyp2_3_1 : SALES "\"bottle_volume_ml\" > 0"
HYPOTHESIS hyp2_3_2 : SALES "NOT \"category_name\" IS NULL"
theorem eq_2_3 (t : TableRel SALES_schema) (h0 : hyp2_3_0 t) (h1 : hyp2_3_1 t) (h2 : hyp2_3_2 t) :
    (sql%([SALES_schema]) "WITH top_categories AS (SELECT \"category_name\", AVG(CAST(\"state_bottle_retail\" AS DOUBLE PRECISION) / \"bottle_volume_ml\" * 1000) AS avg_price_2021 FROM \"IOWA_LIQUOR_SALES\".\"IOWA_LIQUOR_SALES\".\"SALES\" WHERE EXTRACT(YEAR FROM \"date\") = 2021 AND \"bottle_volume_ml\" > 0 AND NOT \"category_name\" IS NULL GROUP BY \"category_name\" ORDER BY avg_price_2021 DESC LIMIT 10) SELECT s.\"category_name\" AS \"category\", ROUND(CAST(AVG(CASE WHEN EXTRACT(YEAR FROM s.\"date\") = 2019 THEN CAST(s.\"state_bottle_retail\" AS DOUBLE PRECISION) / s.\"bottle_volume_ml\" * 1000 END) AS DECIMAL), 2) AS \"avg_price_liter_2019\", ROUND(CAST(AVG(CASE WHEN EXTRACT(YEAR FROM s.\"date\") = 2020 THEN CAST(s.\"state_bottle_retail\" AS DOUBLE PRECISION) / s.\"bottle_volume_ml\" * 1000 END) AS DECIMAL), 2) AS \"avg_price_liter_2020\", ROUND(CAST(AVG(CASE WHEN EXTRACT(YEAR FROM s.\"date\") = 2021 THEN CAST(s.\"state_bottle_retail\" AS DOUBLE PRECISION) / s.\"bottle_volume_ml\" * 1000 END) AS DECIMAL), 2) AS \"avg_price_liter_2021\" FROM \"IOWA_LIQUOR_SALES\".\"IOWA_LIQUOR_SALES\".\"SALES\" AS s JOIN top_categories AS tc ON s.\"category_name\" = tc.\"category_name\" WHERE EXTRACT(YEAR FROM s.\"date\") IN (2019, 2020, 2021) AND s.\"bottle_volume_ml\" > 0 GROUP BY s.\"category_name\" ORDER BY \"avg_price_liter_2021\" DESC") t ~= (sql%([SALES_schema]) "WITH per_liter AS (SELECT \"category_name\" AS category, EXTRACT(YEAR FROM \"date\") AS yr, CAST(\"state_bottle_retail\" AS DOUBLE PRECISION) / (CAST(\"bottle_volume_ml\" AS DOUBLE PRECISION) / 1000.0) AS price_per_liter FROM \"IOWA_LIQUOR_SALES\".\"IOWA_LIQUOR_SALES\".\"SALES\" WHERE EXTRACT(YEAR FROM \"date\") IN (2019, 2020, 2021)), top10 AS (SELECT category FROM per_liter WHERE yr = 2021 GROUP BY category ORDER BY AVG(price_per_liter) DESC LIMIT 10) SELECT t.category, AVG(CASE WHEN p.yr = 2019 THEN p.price_per_liter END) AS avg_price_liter_2019, AVG(CASE WHEN p.yr = 2020 THEN p.price_per_liter END) AS avg_price_liter_2020, AVG(CASE WHEN p.yr = 2021 THEN p.price_per_liter END) AS avg_price_liter_2021 FROM top10 AS t JOIN per_liter AS p ON t.category = p.category GROUP BY t.category ORDER BY avg_price_liter_2021 DESC") t := by
  first | sql_equiv | sorry

end Bench_sf_bq199
