import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_local040 — crossskill equivalence(s)

Question: In the combined dataset that unifies the trees data with the income data by ZIP code, filling missing ZIP values where necessary, which three boroughs, restricted to records with median and mean income both greater than zero and a valid borough name, contain the highest number of trees, and what is the average mean income for each of these three boroughs?

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_local040

CREATE TABLE INCOME_TREES («zipcode» INT, «Estimate_Total» INT, «Margin_of_Error_Total» INT, «Estimate_Median_income» INT, «Margin_of_Error_Median_income» INT, «Estimate_Mean_income» INT, «Margin_of_Error_Mean_income» INT)
CREATE TABLE TREES («idx» INT, «tree_id» INT, «tree_dbh» INT, «stump_diam» INT, «status» STRING, «health» STRING, «spc_latin» STRING, «spc_common» STRING, «address» STRING, «zipcode» INT, «borocode» INT, «boroname» STRING, «nta_name» STRING, «state» STRING, «latitude» FLOAT, «longitude» FLOAT)

theorem eq_0_1 : ∀ t,
    (sql%([INCOME_TREES_schema, TREES_schema]) "WITH combined AS (\n    SELECT \n        t.\"boroname\",\n        i.\"Estimate_Mean_income\",\n        i.\"Estimate_Median_income\"\n    FROM \"MODERN_DATA\".\"MODERN_DATA\".\"TREES\" t\n    LEFT JOIN \"MODERN_DATA\".\"MODERN_DATA\".\"INCOME_TREES\" i \n        ON t.\"zipcode\" = i.\"zipcode\"\n    WHERE i.\"Estimate_Median_income\" > 0\n      AND i.\"Estimate_Mean_income\" > 0\n      AND t.\"boroname\" IS NOT NULL\n      AND t.\"boroname\" != ''\n),\nborough_stats AS (\n    SELECT \n        \"boroname\",\n        COUNT(*) AS tree_count,\n        ROUND(AVG(\"Estimate_Mean_income\"), 4) AS mean_income\n    FROM combined\n    GROUP BY \"boroname\"\n    ORDER BY tree_count DESC\n    LIMIT 3\n)\nSELECT \n    \"boroname\",\n    mean_income\nFROM borough_stats\nORDER BY mean_income DESC;") t ~= (sql%([INCOME_TREES_schema, TREES_schema]) "WITH borough_stats AS (\n  SELECT t.\"boroname\",\n         COUNT(*) AS tree_count,\n         ROUND(AVG(i.\"Estimate_Mean_income\"), 4) AS mean_income\n  FROM \"MODERN_DATA\".\"MODERN_DATA\".\"TREES\" t\n  INNER JOIN \"MODERN_DATA\".\"MODERN_DATA\".\"INCOME_TREES\" i\n    ON t.\"zipcode\" = i.\"zipcode\"\n  WHERE i.\"Estimate_Median_income\" > 0\n    AND i.\"Estimate_Mean_income\" > 0\n    AND t.\"boroname\" IS NOT NULL\n    AND t.\"boroname\" != ''\n  GROUP BY t.\"boroname\"\n  ORDER BY tree_count DESC\n  LIMIT 3\n)\nSELECT \"boroname\", mean_income\nFROM borough_stats\nORDER BY mean_income DESC;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_0_2 : ∀ t,
    (sql%([INCOME_TREES_schema, TREES_schema]) "WITH combined AS (\n    SELECT \n        t.\"boroname\",\n        i.\"Estimate_Mean_income\",\n        i.\"Estimate_Median_income\"\n    FROM \"MODERN_DATA\".\"MODERN_DATA\".\"TREES\" t\n    LEFT JOIN \"MODERN_DATA\".\"MODERN_DATA\".\"INCOME_TREES\" i \n        ON t.\"zipcode\" = i.\"zipcode\"\n    WHERE i.\"Estimate_Median_income\" > 0\n      AND i.\"Estimate_Mean_income\" > 0\n      AND t.\"boroname\" IS NOT NULL\n      AND t.\"boroname\" != ''\n),\nborough_stats AS (\n    SELECT \n        \"boroname\",\n        COUNT(*) AS tree_count,\n        ROUND(AVG(\"Estimate_Mean_income\"), 4) AS mean_income\n    FROM combined\n    GROUP BY \"boroname\"\n    ORDER BY tree_count DESC\n    LIMIT 3\n)\nSELECT \n    \"boroname\",\n    mean_income\nFROM borough_stats\nORDER BY mean_income DESC;") t ~= (sql%([INCOME_TREES_schema, TREES_schema]) "WITH top3 AS (\n    SELECT\n        t.\"boroname\",\n        COUNT(*) AS tree_count,\n        ROUND(AVG(i.\"Estimate_Mean_income\"), 4) AS \"mean_income\"\n    FROM \"MODERN_DATA\".\"MODERN_DATA\".\"TREES\" t\n    JOIN \"MODERN_DATA\".\"MODERN_DATA\".\"INCOME_TREES\" i\n        ON t.\"zipcode\" = i.\"zipcode\"\n    WHERE i.\"Estimate_Median_income\" > 0\n      AND i.\"Estimate_Mean_income\" > 0\n      AND t.\"boroname\" IS NOT NULL\n      AND t.\"boroname\" != ''\n    GROUP BY t.\"boroname\"\n    ORDER BY tree_count DESC\n    LIMIT 3\n)\nSELECT \"boroname\", \"mean_income\"\nFROM top3\nORDER BY \"mean_income\" DESC;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_0_3 : ∀ t,
    (sql%([INCOME_TREES_schema, TREES_schema]) "WITH combined AS (\n    SELECT \n        t.\"boroname\",\n        i.\"Estimate_Mean_income\",\n        i.\"Estimate_Median_income\"\n    FROM \"MODERN_DATA\".\"MODERN_DATA\".\"TREES\" t\n    LEFT JOIN \"MODERN_DATA\".\"MODERN_DATA\".\"INCOME_TREES\" i \n        ON t.\"zipcode\" = i.\"zipcode\"\n    WHERE i.\"Estimate_Median_income\" > 0\n      AND i.\"Estimate_Mean_income\" > 0\n      AND t.\"boroname\" IS NOT NULL\n      AND t.\"boroname\" != ''\n),\nborough_stats AS (\n    SELECT \n        \"boroname\",\n        COUNT(*) AS tree_count,\n        ROUND(AVG(\"Estimate_Mean_income\"), 4) AS mean_income\n    FROM combined\n    GROUP BY \"boroname\"\n    ORDER BY tree_count DESC\n    LIMIT 3\n)\nSELECT \n    \"boroname\",\n    mean_income\nFROM borough_stats\nORDER BY mean_income DESC;") t ~= (sql%([INCOME_TREES_schema, TREES_schema]) "WITH combined AS (\n    SELECT \n        t.\"boroname\",\n        t.\"zipcode\",\n        i.\"Estimate_Median_income\",\n        i.\"Estimate_Mean_income\"\n    FROM \"MODERN_DATA\".\"MODERN_DATA\".\"TREES\" t\n    JOIN \"MODERN_DATA\".\"MODERN_DATA\".\"INCOME_TREES\" i\n        ON t.\"zipcode\" = i.\"zipcode\"\n    WHERE i.\"Estimate_Median_income\" > 0\n      AND i.\"Estimate_Mean_income\" > 0\n      AND t.\"boroname\" IS NOT NULL\n),\ntop3_boroughs AS (\n    SELECT \"boroname\"\n    FROM combined\n    GROUP BY \"boroname\"\n    ORDER BY COUNT(*) DESC\n    LIMIT 3\n)\nSELECT \n    c.\"boroname\",\n    AVG(c.\"Estimate_Mean_income\") AS \"mean_income\"\nFROM combined c\nWHERE c.\"boroname\" IN (SELECT \"boroname\" FROM top3_boroughs)\nGROUP BY c.\"boroname\"\nORDER BY \"mean_income\" DESC;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_1_2 :
    sql%([INCOME_TREES_schema, TREES_schema]) "WITH borough_stats AS (\n  SELECT t.\"boroname\",\n         COUNT(*) AS tree_count,\n         ROUND(AVG(i.\"Estimate_Mean_income\"), 4) AS mean_income\n  FROM \"MODERN_DATA\".\"MODERN_DATA\".\"TREES\" t\n  INNER JOIN \"MODERN_DATA\".\"MODERN_DATA\".\"INCOME_TREES\" i\n    ON t.\"zipcode\" = i.\"zipcode\"\n  WHERE i.\"Estimate_Median_income\" > 0\n    AND i.\"Estimate_Mean_income\" > 0\n    AND t.\"boroname\" IS NOT NULL\n    AND t.\"boroname\" != ''\n  GROUP BY t.\"boroname\"\n  ORDER BY tree_count DESC\n  LIMIT 3\n)\nSELECT \"boroname\", mean_income\nFROM borough_stats\nORDER BY mean_income DESC;" = sql%([INCOME_TREES_schema, TREES_schema]) "WITH top3 AS (\n    SELECT\n        t.\"boroname\",\n        COUNT(*) AS tree_count,\n        ROUND(AVG(i.\"Estimate_Mean_income\"), 4) AS \"mean_income\"\n    FROM \"MODERN_DATA\".\"MODERN_DATA\".\"TREES\" t\n    JOIN \"MODERN_DATA\".\"MODERN_DATA\".\"INCOME_TREES\" i\n        ON t.\"zipcode\" = i.\"zipcode\"\n    WHERE i.\"Estimate_Median_income\" > 0\n      AND i.\"Estimate_Mean_income\" > 0\n      AND t.\"boroname\" IS NOT NULL\n      AND t.\"boroname\" != ''\n    GROUP BY t.\"boroname\"\n    ORDER BY tree_count DESC\n    LIMIT 3\n)\nSELECT \"boroname\", \"mean_income\"\nFROM top3\nORDER BY \"mean_income\" DESC;" := by
  first | sql_equiv | sorry

theorem eq_1_3 : ∀ t,
    (sql%([INCOME_TREES_schema, TREES_schema]) "WITH borough_stats AS (\n  SELECT t.\"boroname\",\n         COUNT(*) AS tree_count,\n         ROUND(AVG(i.\"Estimate_Mean_income\"), 4) AS mean_income\n  FROM \"MODERN_DATA\".\"MODERN_DATA\".\"TREES\" t\n  INNER JOIN \"MODERN_DATA\".\"MODERN_DATA\".\"INCOME_TREES\" i\n    ON t.\"zipcode\" = i.\"zipcode\"\n  WHERE i.\"Estimate_Median_income\" > 0\n    AND i.\"Estimate_Mean_income\" > 0\n    AND t.\"boroname\" IS NOT NULL\n    AND t.\"boroname\" != ''\n  GROUP BY t.\"boroname\"\n  ORDER BY tree_count DESC\n  LIMIT 3\n)\nSELECT \"boroname\", mean_income\nFROM borough_stats\nORDER BY mean_income DESC;") t ~= (sql%([INCOME_TREES_schema, TREES_schema]) "WITH combined AS (\n    SELECT \n        t.\"boroname\",\n        t.\"zipcode\",\n        i.\"Estimate_Median_income\",\n        i.\"Estimate_Mean_income\"\n    FROM \"MODERN_DATA\".\"MODERN_DATA\".\"TREES\" t\n    JOIN \"MODERN_DATA\".\"MODERN_DATA\".\"INCOME_TREES\" i\n        ON t.\"zipcode\" = i.\"zipcode\"\n    WHERE i.\"Estimate_Median_income\" > 0\n      AND i.\"Estimate_Mean_income\" > 0\n      AND t.\"boroname\" IS NOT NULL\n),\ntop3_boroughs AS (\n    SELECT \"boroname\"\n    FROM combined\n    GROUP BY \"boroname\"\n    ORDER BY COUNT(*) DESC\n    LIMIT 3\n)\nSELECT \n    c.\"boroname\",\n    AVG(c.\"Estimate_Mean_income\") AS \"mean_income\"\nFROM combined c\nWHERE c.\"boroname\" IN (SELECT \"boroname\" FROM top3_boroughs)\nGROUP BY c.\"boroname\"\nORDER BY \"mean_income\" DESC;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_2_3 : ∀ t,
    (sql%([INCOME_TREES_schema, TREES_schema]) "WITH top3 AS (\n    SELECT\n        t.\"boroname\",\n        COUNT(*) AS tree_count,\n        ROUND(AVG(i.\"Estimate_Mean_income\"), 4) AS \"mean_income\"\n    FROM \"MODERN_DATA\".\"MODERN_DATA\".\"TREES\" t\n    JOIN \"MODERN_DATA\".\"MODERN_DATA\".\"INCOME_TREES\" i\n        ON t.\"zipcode\" = i.\"zipcode\"\n    WHERE i.\"Estimate_Median_income\" > 0\n      AND i.\"Estimate_Mean_income\" > 0\n      AND t.\"boroname\" IS NOT NULL\n      AND t.\"boroname\" != ''\n    GROUP BY t.\"boroname\"\n    ORDER BY tree_count DESC\n    LIMIT 3\n)\nSELECT \"boroname\", \"mean_income\"\nFROM top3\nORDER BY \"mean_income\" DESC;") t ~= (sql%([INCOME_TREES_schema, TREES_schema]) "WITH combined AS (\n    SELECT \n        t.\"boroname\",\n        t.\"zipcode\",\n        i.\"Estimate_Median_income\",\n        i.\"Estimate_Mean_income\"\n    FROM \"MODERN_DATA\".\"MODERN_DATA\".\"TREES\" t\n    JOIN \"MODERN_DATA\".\"MODERN_DATA\".\"INCOME_TREES\" i\n        ON t.\"zipcode\" = i.\"zipcode\"\n    WHERE i.\"Estimate_Median_income\" > 0\n      AND i.\"Estimate_Mean_income\" > 0\n      AND t.\"boroname\" IS NOT NULL\n),\ntop3_boroughs AS (\n    SELECT \"boroname\"\n    FROM combined\n    GROUP BY \"boroname\"\n    ORDER BY COUNT(*) DESC\n    LIMIT 3\n)\nSELECT \n    c.\"boroname\",\n    AVG(c.\"Estimate_Mean_income\") AS \"mean_income\"\nFROM combined c\nWHERE c.\"boroname\" IN (SELECT \"boroname\" FROM top3_boroughs)\nGROUP BY c.\"boroname\"\nORDER BY \"mean_income\" DESC;") t := by
  intro t; first | sql_equiv | sorry

end Bench_sf_local040
