import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_bq266 — crossskill equivalence(s)

Question: Please provide the names of the products that had sales in each month of 2020 and had the lowest profit, calculated as the difference between their retail price and cost from the products data. Exclude any months where this data isn't available. Please list the products in chronological order based on the month.

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_bq266

CREATE TABLE PRODUCTS («id» INT, «cost» FLOAT, «category» STRING, «name» STRING, «brand» STRING, «retail_price» FLOAT, «department» STRING, «sku» STRING, «distribution_center_id» INT)
CREATE TABLE ORDER_ITEMS («id» INT, «order_id» INT, «user_id» INT, «product_id» INT, «inventory_item_id» INT, «status» STRING, «created_at» INT, «shipped_at» INT, «delivered_at» INT, «returned_at» INT, «sale_price» FLOAT)

theorem eq_0_1 :
    sql%([PRODUCTS_schema, ORDER_ITEMS_schema]) "WITH monthly_sales AS (\n  SELECT \n    EXTRACT(MONTH FROM TO_TIMESTAMP(oi.\"created_at\" / 1000000)) AS month_num,\n    oi.\"product_id\",\n    p.\"name\",\n    (p.\"retail_price\" - p.\"cost\") AS profit\n  FROM \"THELOOK_ECOMMERCE\".\"THELOOK_ECOMMERCE\".\"ORDER_ITEMS\" oi\n  JOIN \"THELOOK_ECOMMERCE\".\"THELOOK_ECOMMERCE\".\"PRODUCTS\" p \n    ON oi.\"product_id\" = p.\"id\"\n  WHERE EXTRACT(YEAR FROM TO_TIMESTAMP(oi.\"created_at\" / 1000000)) = 2020\n),\nranked AS (\n  SELECT \n    month_num,\n    \"name\",\n    profit,\n    ROW_NUMBER() OVER (PARTITION BY month_num ORDER BY profit ASC, \"name\" ASC) AS rn\n  FROM monthly_sales\n)\nSELECT \"name\"\nFROM ranked\nWHERE rn = 1\nORDER BY month_num;" = sql%([PRODUCTS_schema, ORDER_ITEMS_schema]) "WITH monthly_sales AS (\n  SELECT \n    EXTRACT(MONTH FROM TO_TIMESTAMP(oi.\"created_at\"/1000000)) AS month_num,\n    p.\"name\",\n    p.\"retail_price\" - p.\"cost\" AS profit\n  FROM \"THELOOK_ECOMMERCE\".\"THELOOK_ECOMMERCE\".\"ORDER_ITEMS\" oi\n  JOIN \"THELOOK_ECOMMERCE\".\"THELOOK_ECOMMERCE\".\"PRODUCTS\" p ON oi.\"product_id\" = p.\"id\"\n  WHERE EXTRACT(YEAR FROM TO_TIMESTAMP(oi.\"created_at\"/1000000)) = 2020\n),\nranked AS (\n  SELECT \n    month_num,\n    \"name\",\n    profit,\n    ROW_NUMBER() OVER (PARTITION BY month_num ORDER BY profit ASC, \"name\" ASC) AS rn\n  FROM monthly_sales\n)\nSELECT \"name\"\nFROM ranked\nWHERE rn = 1\nORDER BY month_num;" := by
  first | sql_equiv | sorry

theorem eq_0_2 :
    sql%([PRODUCTS_schema, ORDER_ITEMS_schema]) "WITH monthly_sales AS (\n  SELECT \n    EXTRACT(MONTH FROM TO_TIMESTAMP(oi.\"created_at\" / 1000000)) AS month_num,\n    oi.\"product_id\",\n    p.\"name\",\n    (p.\"retail_price\" - p.\"cost\") AS profit\n  FROM \"THELOOK_ECOMMERCE\".\"THELOOK_ECOMMERCE\".\"ORDER_ITEMS\" oi\n  JOIN \"THELOOK_ECOMMERCE\".\"THELOOK_ECOMMERCE\".\"PRODUCTS\" p \n    ON oi.\"product_id\" = p.\"id\"\n  WHERE EXTRACT(YEAR FROM TO_TIMESTAMP(oi.\"created_at\" / 1000000)) = 2020\n),\nranked AS (\n  SELECT \n    month_num,\n    \"name\",\n    profit,\n    ROW_NUMBER() OVER (PARTITION BY month_num ORDER BY profit ASC, \"name\" ASC) AS rn\n  FROM monthly_sales\n)\nSELECT \"name\"\nFROM ranked\nWHERE rn = 1\nORDER BY month_num;" = sql%([PRODUCTS_schema, ORDER_ITEMS_schema]) "WITH monthly_products AS (\n    SELECT\n        EXTRACT(MONTH FROM TO_TIMESTAMP(\"created_at\" / 1000000)) AS month_num,\n        p.\"name\" AS name,\n        (p.\"retail_price\" - p.\"cost\") AS profit\n    FROM \"THELOOK_ECOMMERCE\".\"THELOOK_ECOMMERCE\".\"ORDER_ITEMS\" oi\n    JOIN \"THELOOK_ECOMMERCE\".\"THELOOK_ECOMMERCE\".\"PRODUCTS\" p\n        ON oi.\"product_id\" = p.\"id\"\n    WHERE EXTRACT(YEAR FROM TO_TIMESTAMP(oi.\"created_at\" / 1000000)) = 2020\n),\nmin_profit_per_month AS (\n    SELECT\n        month_num,\n        MIN(profit) AS min_profit\n    FROM monthly_products\n    GROUP BY month_num\n),\nresult AS (\n    SELECT\n        mp.month_num,\n        mp.name\n    FROM monthly_products mp\n    JOIN min_profit_per_month mpm\n        ON mp.month_num = mpm.month_num\n        AND mp.profit = mpm.min_profit\n    GROUP BY mp.month_num, mp.name\n)\nSELECT name AS \"name\"\nFROM result\nORDER BY month_num;" := by
  first | sql_equiv | sorry

theorem eq_0_3 : ∀ t,
    (sql%([PRODUCTS_schema, ORDER_ITEMS_schema]) "WITH monthly_sales AS (\n  SELECT \n    EXTRACT(MONTH FROM TO_TIMESTAMP(oi.\"created_at\" / 1000000)) AS month_num,\n    oi.\"product_id\",\n    p.\"name\",\n    (p.\"retail_price\" - p.\"cost\") AS profit\n  FROM \"THELOOK_ECOMMERCE\".\"THELOOK_ECOMMERCE\".\"ORDER_ITEMS\" oi\n  JOIN \"THELOOK_ECOMMERCE\".\"THELOOK_ECOMMERCE\".\"PRODUCTS\" p \n    ON oi.\"product_id\" = p.\"id\"\n  WHERE EXTRACT(YEAR FROM TO_TIMESTAMP(oi.\"created_at\" / 1000000)) = 2020\n),\nranked AS (\n  SELECT \n    month_num,\n    \"name\",\n    profit,\n    ROW_NUMBER() OVER (PARTITION BY month_num ORDER BY profit ASC, \"name\" ASC) AS rn\n  FROM monthly_sales\n)\nSELECT \"name\"\nFROM ranked\nWHERE rn = 1\nORDER BY month_num;") t ~= (sql%([PRODUCTS_schema, ORDER_ITEMS_schema]) "WITH monthly_sales AS (\n    SELECT\n        DATE_TRUNC('MONTH', TO_TIMESTAMP(oi.\"created_at\" / 1000000)) AS sale_month,\n        p.\"name\",\n        p.\"retail_price\" - p.\"cost\" AS profit\n    FROM \"THELOOK_ECOMMERCE\".\"THELOOK_ECOMMERCE\".\"ORDER_ITEMS\" oi\n    JOIN \"THELOOK_ECOMMERCE\".\"THELOOK_ECOMMERCE\".\"PRODUCTS\" p\n        ON oi.\"product_id\" = p.\"id\"\n    WHERE YEAR(TO_TIMESTAMP(oi.\"created_at\" / 1000000)) = 2020\n),\nranked AS (\n    SELECT\n        sale_month,\n        \"name\",\n        profit,\n        ROW_NUMBER() OVER (PARTITION BY sale_month ORDER BY profit ASC) AS rn\n    FROM monthly_sales\n)\nSELECT \"name\"\nFROM ranked\nWHERE rn = 1\nORDER BY sale_month ASC;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_1_2 :
    sql%([PRODUCTS_schema, ORDER_ITEMS_schema]) "WITH monthly_sales AS (\n  SELECT \n    EXTRACT(MONTH FROM TO_TIMESTAMP(oi.\"created_at\"/1000000)) AS month_num,\n    p.\"name\",\n    p.\"retail_price\" - p.\"cost\" AS profit\n  FROM \"THELOOK_ECOMMERCE\".\"THELOOK_ECOMMERCE\".\"ORDER_ITEMS\" oi\n  JOIN \"THELOOK_ECOMMERCE\".\"THELOOK_ECOMMERCE\".\"PRODUCTS\" p ON oi.\"product_id\" = p.\"id\"\n  WHERE EXTRACT(YEAR FROM TO_TIMESTAMP(oi.\"created_at\"/1000000)) = 2020\n),\nranked AS (\n  SELECT \n    month_num,\n    \"name\",\n    profit,\n    ROW_NUMBER() OVER (PARTITION BY month_num ORDER BY profit ASC, \"name\" ASC) AS rn\n  FROM monthly_sales\n)\nSELECT \"name\"\nFROM ranked\nWHERE rn = 1\nORDER BY month_num;" = sql%([PRODUCTS_schema, ORDER_ITEMS_schema]) "WITH monthly_products AS (\n    SELECT\n        EXTRACT(MONTH FROM TO_TIMESTAMP(\"created_at\" / 1000000)) AS month_num,\n        p.\"name\" AS name,\n        (p.\"retail_price\" - p.\"cost\") AS profit\n    FROM \"THELOOK_ECOMMERCE\".\"THELOOK_ECOMMERCE\".\"ORDER_ITEMS\" oi\n    JOIN \"THELOOK_ECOMMERCE\".\"THELOOK_ECOMMERCE\".\"PRODUCTS\" p\n        ON oi.\"product_id\" = p.\"id\"\n    WHERE EXTRACT(YEAR FROM TO_TIMESTAMP(oi.\"created_at\" / 1000000)) = 2020\n),\nmin_profit_per_month AS (\n    SELECT\n        month_num,\n        MIN(profit) AS min_profit\n    FROM monthly_products\n    GROUP BY month_num\n),\nresult AS (\n    SELECT\n        mp.month_num,\n        mp.name\n    FROM monthly_products mp\n    JOIN min_profit_per_month mpm\n        ON mp.month_num = mpm.month_num\n        AND mp.profit = mpm.min_profit\n    GROUP BY mp.month_num, mp.name\n)\nSELECT name AS \"name\"\nFROM result\nORDER BY month_num;" := by
  first | sql_equiv | sorry

theorem eq_1_3 : ∀ t,
    (sql%([PRODUCTS_schema, ORDER_ITEMS_schema]) "WITH monthly_sales AS (\n  SELECT \n    EXTRACT(MONTH FROM TO_TIMESTAMP(oi.\"created_at\"/1000000)) AS month_num,\n    p.\"name\",\n    p.\"retail_price\" - p.\"cost\" AS profit\n  FROM \"THELOOK_ECOMMERCE\".\"THELOOK_ECOMMERCE\".\"ORDER_ITEMS\" oi\n  JOIN \"THELOOK_ECOMMERCE\".\"THELOOK_ECOMMERCE\".\"PRODUCTS\" p ON oi.\"product_id\" = p.\"id\"\n  WHERE EXTRACT(YEAR FROM TO_TIMESTAMP(oi.\"created_at\"/1000000)) = 2020\n),\nranked AS (\n  SELECT \n    month_num,\n    \"name\",\n    profit,\n    ROW_NUMBER() OVER (PARTITION BY month_num ORDER BY profit ASC, \"name\" ASC) AS rn\n  FROM monthly_sales\n)\nSELECT \"name\"\nFROM ranked\nWHERE rn = 1\nORDER BY month_num;") t ~= (sql%([PRODUCTS_schema, ORDER_ITEMS_schema]) "WITH monthly_sales AS (\n    SELECT\n        DATE_TRUNC('MONTH', TO_TIMESTAMP(oi.\"created_at\" / 1000000)) AS sale_month,\n        p.\"name\",\n        p.\"retail_price\" - p.\"cost\" AS profit\n    FROM \"THELOOK_ECOMMERCE\".\"THELOOK_ECOMMERCE\".\"ORDER_ITEMS\" oi\n    JOIN \"THELOOK_ECOMMERCE\".\"THELOOK_ECOMMERCE\".\"PRODUCTS\" p\n        ON oi.\"product_id\" = p.\"id\"\n    WHERE YEAR(TO_TIMESTAMP(oi.\"created_at\" / 1000000)) = 2020\n),\nranked AS (\n    SELECT\n        sale_month,\n        \"name\",\n        profit,\n        ROW_NUMBER() OVER (PARTITION BY sale_month ORDER BY profit ASC) AS rn\n    FROM monthly_sales\n)\nSELECT \"name\"\nFROM ranked\nWHERE rn = 1\nORDER BY sale_month ASC;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_2_3 : ∀ t,
    (sql%([PRODUCTS_schema, ORDER_ITEMS_schema]) "WITH monthly_products AS (\n    SELECT\n        EXTRACT(MONTH FROM TO_TIMESTAMP(\"created_at\" / 1000000)) AS month_num,\n        p.\"name\" AS name,\n        (p.\"retail_price\" - p.\"cost\") AS profit\n    FROM \"THELOOK_ECOMMERCE\".\"THELOOK_ECOMMERCE\".\"ORDER_ITEMS\" oi\n    JOIN \"THELOOK_ECOMMERCE\".\"THELOOK_ECOMMERCE\".\"PRODUCTS\" p\n        ON oi.\"product_id\" = p.\"id\"\n    WHERE EXTRACT(YEAR FROM TO_TIMESTAMP(oi.\"created_at\" / 1000000)) = 2020\n),\nmin_profit_per_month AS (\n    SELECT\n        month_num,\n        MIN(profit) AS min_profit\n    FROM monthly_products\n    GROUP BY month_num\n),\nresult AS (\n    SELECT\n        mp.month_num,\n        mp.name\n    FROM monthly_products mp\n    JOIN min_profit_per_month mpm\n        ON mp.month_num = mpm.month_num\n        AND mp.profit = mpm.min_profit\n    GROUP BY mp.month_num, mp.name\n)\nSELECT name AS \"name\"\nFROM result\nORDER BY month_num;") t ~= (sql%([PRODUCTS_schema, ORDER_ITEMS_schema]) "WITH monthly_sales AS (\n    SELECT\n        DATE_TRUNC('MONTH', TO_TIMESTAMP(oi.\"created_at\" / 1000000)) AS sale_month,\n        p.\"name\",\n        p.\"retail_price\" - p.\"cost\" AS profit\n    FROM \"THELOOK_ECOMMERCE\".\"THELOOK_ECOMMERCE\".\"ORDER_ITEMS\" oi\n    JOIN \"THELOOK_ECOMMERCE\".\"THELOOK_ECOMMERCE\".\"PRODUCTS\" p\n        ON oi.\"product_id\" = p.\"id\"\n    WHERE YEAR(TO_TIMESTAMP(oi.\"created_at\" / 1000000)) = 2020\n),\nranked AS (\n    SELECT\n        sale_month,\n        \"name\",\n        profit,\n        ROW_NUMBER() OVER (PARTITION BY sale_month ORDER BY profit ASC) AS rn\n    FROM monthly_sales\n)\nSELECT \"name\"\nFROM ranked\nWHERE rn = 1\nORDER BY sale_month ASC;") t := by
  intro t; first | sql_equiv | sorry

end Bench_sf_bq266
