import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_bq363 — crossskill equivalence(s)

Question: Calculate the total number of trips and average fare (formatted to two decimal places) for ten equal-sized quantile groups. Create ten quantile groups by partitioning the trip duration dimension (from 1-50 minutes) into equal sets. Each group should represent a similar number of distinct minute values. Display each group's time range formatted as "XXm to XXm" (where the numbers are zero-padded to two digits), the total trips count, and the average fare. The time ranges should represent the minimum and maximum duration values within each quantile. Sort the results chronologically by time range. Use NTILE(10) to create the quantiles from the ordered trip durations.

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_bq363

CREATE TABLE TAXI_TRIPS («unique_key» STRING, «taxi_id» STRING, «trip_start_timestamp» INT, «trip_end_timestamp» INT, «trip_seconds» INT, «trip_miles» FLOAT, «pickup_census_tract» INT, «dropoff_census_tract» INT, «pickup_community_area» INT, «dropoff_community_area» INT, «fare» FLOAT, «tips» FLOAT, «tolls» FLOAT, «extras» FLOAT, «trip_total» FLOAT, «payment_type» STRING, «company» STRING, «pickup_latitude» FLOAT, «pickup_longitude» FLOAT, «pickup_location» STRING, «dropoff_latitude» FLOAT, «dropoff_longitude» FLOAT, «dropoff_location» STRING)

theorem eq_0_1 : ∀ t,
    (sql%([TAXI_TRIPS_schema]) "WITH duration_minutes AS (\n  SELECT DISTINCT FLOOR(\"trip_seconds\" / 60.0) AS trip_min\n  FROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\"\n  WHERE FLOOR(\"trip_seconds\" / 60.0) BETWEEN 1 AND 50\n),\nntiled AS (\n  SELECT trip_min, NTILE(10) OVER (ORDER BY trip_min) AS quantile_group\n  FROM duration_minutes\n),\ngroups AS (\n  SELECT quantile_group, MIN(trip_min) AS min_min, MAX(trip_min) AS max_min\n  FROM ntiled\n  GROUP BY quantile_group\n)\nSELECT \n  LPAD(CAST(g.min_min AS INT)::VARCHAR, 2, '0') || 'm to ' || LPAD(CAST(g.max_min AS INT)::VARCHAR, 2, '0') || 'm' AS TIME_RANGE,\n  COUNT(*) AS TOTAL_TRIPS,\n  ROUND(AVG(t.\"fare\"), 2) AS AVERAGE_FARE\nFROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\" t\nJOIN groups g ON FLOOR(t.\"trip_seconds\" / 60.0) BETWEEN g.min_min AND g.max_min\nWHERE FLOOR(t.\"trip_seconds\" / 60.0) BETWEEN 1 AND 50\nGROUP BY g.quantile_group, g.min_min, g.max_min\nORDER BY TIME_RANGE;") t ~= (sql%([TAXI_TRIPS_schema]) "WITH minute_quantiles AS (\n  SELECT\n    trip_minutes,\n    NTILE(10) OVER (ORDER BY trip_minutes) AS quantile\n  FROM (\n    SELECT DISTINCT CAST(FLOOR(\"trip_seconds\" / 60) AS INT) AS trip_minutes\n    FROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\"\n    WHERE FLOOR(\"trip_seconds\" / 60) BETWEEN 1 AND 50\n  )\n)\nSELECT\n  LPAD(MIN(q.trip_minutes)::VARCHAR, 2, '0') || 'm to ' || LPAD(MAX(q.trip_minutes)::VARCHAR, 2, '0') || 'm' AS TIME_RANGE,\n  COUNT(*) AS TOTAL_TRIPS,\n  ROUND(AVG(t.\"fare\"), 2) AS AVERAGE_FARE\nFROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\" t\nJOIN minute_quantiles q\n  ON CAST(FLOOR(t.\"trip_seconds\" / 60) AS INT) = q.trip_minutes\nWHERE FLOOR(t.\"trip_seconds\" / 60) BETWEEN 1 AND 50\nGROUP BY q.quantile\nORDER BY MIN(q.trip_minutes);") t := by
  intro t; first | sql_equiv | sorry

theorem eq_0_2 : ∀ t,
    (sql%([TAXI_TRIPS_schema]) "WITH duration_minutes AS (\n  SELECT DISTINCT FLOOR(\"trip_seconds\" / 60.0) AS trip_min\n  FROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\"\n  WHERE FLOOR(\"trip_seconds\" / 60.0) BETWEEN 1 AND 50\n),\nntiled AS (\n  SELECT trip_min, NTILE(10) OVER (ORDER BY trip_min) AS quantile_group\n  FROM duration_minutes\n),\ngroups AS (\n  SELECT quantile_group, MIN(trip_min) AS min_min, MAX(trip_min) AS max_min\n  FROM ntiled\n  GROUP BY quantile_group\n)\nSELECT \n  LPAD(CAST(g.min_min AS INT)::VARCHAR, 2, '0') || 'm to ' || LPAD(CAST(g.max_min AS INT)::VARCHAR, 2, '0') || 'm' AS TIME_RANGE,\n  COUNT(*) AS TOTAL_TRIPS,\n  ROUND(AVG(t.\"fare\"), 2) AS AVERAGE_FARE\nFROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\" t\nJOIN groups g ON FLOOR(t.\"trip_seconds\" / 60.0) BETWEEN g.min_min AND g.max_min\nWHERE FLOOR(t.\"trip_seconds\" / 60.0) BETWEEN 1 AND 50\nGROUP BY g.quantile_group, g.min_min, g.max_min\nORDER BY TIME_RANGE;") t ~= (sql%([TAXI_TRIPS_schema]) "SELECT\n    LPAD(CAST(MIN(trip_minutes) AS VARCHAR), 2, '0') || 'm to ' || LPAD(CAST(MAX(trip_minutes) AS VARCHAR), 2, '0') || 'm' AS \"TIME_RANGE\",\n    COUNT(*) AS \"TOTAL_TRIPS\",\n    ROUND(AVG(fare), 2) AS \"AVERAGE_FARE\"\nFROM (\n    SELECT\n        FLOOR(\"trip_seconds\" / 60) AS trip_minutes,\n        \"fare\" AS fare,\n        CEIL(FLOOR(\"trip_seconds\" / 60) / 5) AS quantile\n    FROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\"\n    WHERE FLOOR(\"trip_seconds\" / 60) BETWEEN 1 AND 50\n)\nGROUP BY quantile\nORDER BY \"TIME_RANGE\";") t := by
  intro t; first | sql_equiv | sorry

HYPOTHESIS hyp0_3_0 : TAXI_TRIPS "\"trip_seconds\" IS NOT NULL"
HYPOTHESIS hyp0_3_1 : TAXI_TRIPS "FLOOR(\"trip_seconds\" / 60) >= 1"
theorem eq_0_3 (t : TableRel TAXI_TRIPS_schema) (h0 : hyp0_3_0 t) (h1 : hyp0_3_1 t) :
    (sql%([TAXI_TRIPS_schema]) "WITH duration_minutes AS (\n  SELECT DISTINCT FLOOR(\"trip_seconds\" / 60.0) AS trip_min\n  FROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\"\n  WHERE FLOOR(\"trip_seconds\" / 60.0) BETWEEN 1 AND 50\n),\nntiled AS (\n  SELECT trip_min, NTILE(10) OVER (ORDER BY trip_min) AS quantile_group\n  FROM duration_minutes\n),\ngroups AS (\n  SELECT quantile_group, MIN(trip_min) AS min_min, MAX(trip_min) AS max_min\n  FROM ntiled\n  GROUP BY quantile_group\n)\nSELECT \n  LPAD(CAST(g.min_min AS INT)::VARCHAR, 2, '0') || 'm to ' || LPAD(CAST(g.max_min AS INT)::VARCHAR, 2, '0') || 'm' AS TIME_RANGE,\n  COUNT(*) AS TOTAL_TRIPS,\n  ROUND(AVG(t.\"fare\"), 2) AS AVERAGE_FARE\nFROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\" t\nJOIN groups g ON FLOOR(t.\"trip_seconds\" / 60.0) BETWEEN g.min_min AND g.max_min\nWHERE FLOOR(t.\"trip_seconds\" / 60.0) BETWEEN 1 AND 50\nGROUP BY g.quantile_group, g.min_min, g.max_min\nORDER BY TIME_RANGE;") t ~= (sql%([TAXI_TRIPS_schema]) "WITH trip_data AS (\n  SELECT\n    FLOOR(\"trip_seconds\" / 60) AS trip_minutes,\n    \"fare\"\n  FROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\"\n  WHERE \"trip_seconds\" IS NOT NULL\n    AND FLOOR(\"trip_seconds\" / 60) >= 1\n    AND FLOOR(\"trip_seconds\" / 60) <= 50\n),\nbucketed AS (\n  SELECT\n    CASE\n      WHEN trip_minutes BETWEEN 1 AND 5 THEN '01m to 05m'\n      WHEN trip_minutes BETWEEN 6 AND 10 THEN '06m to 10m'\n      WHEN trip_minutes BETWEEN 11 AND 15 THEN '11m to 15m'\n      WHEN trip_minutes BETWEEN 16 AND 20 THEN '16m to 20m'\n      WHEN trip_minutes BETWEEN 21 AND 25 THEN '21m to 25m'\n      WHEN trip_minutes BETWEEN 26 AND 30 THEN '26m to 30m'\n      WHEN trip_minutes BETWEEN 31 AND 35 THEN '31m to 35m'\n      WHEN trip_minutes BETWEEN 36 AND 40 THEN '36m to 40m'\n      WHEN trip_minutes BETWEEN 41 AND 45 THEN '41m to 45m'\n      WHEN trip_minutes BETWEEN 46 AND 50 THEN '46m to 50m'\n    END AS TIME_RANGE,\n    \"fare\"\n  FROM trip_data\n)\nSELECT\n  TIME_RANGE,\n  COUNT(*) AS TOTAL_TRIPS,\n  ROUND(AVG(\"fare\"), 2) AS AVERAGE_FARE\nFROM bucketed\nGROUP BY TIME_RANGE\nORDER BY TIME_RANGE;") t := by
  first | sql_equiv | sorry

theorem eq_1_2 : ∀ t,
    (sql%([TAXI_TRIPS_schema]) "WITH minute_quantiles AS (\n  SELECT\n    trip_minutes,\n    NTILE(10) OVER (ORDER BY trip_minutes) AS quantile\n  FROM (\n    SELECT DISTINCT CAST(FLOOR(\"trip_seconds\" / 60) AS INT) AS trip_minutes\n    FROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\"\n    WHERE FLOOR(\"trip_seconds\" / 60) BETWEEN 1 AND 50\n  )\n)\nSELECT\n  LPAD(MIN(q.trip_minutes)::VARCHAR, 2, '0') || 'm to ' || LPAD(MAX(q.trip_minutes)::VARCHAR, 2, '0') || 'm' AS TIME_RANGE,\n  COUNT(*) AS TOTAL_TRIPS,\n  ROUND(AVG(t.\"fare\"), 2) AS AVERAGE_FARE\nFROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\" t\nJOIN minute_quantiles q\n  ON CAST(FLOOR(t.\"trip_seconds\" / 60) AS INT) = q.trip_minutes\nWHERE FLOOR(t.\"trip_seconds\" / 60) BETWEEN 1 AND 50\nGROUP BY q.quantile\nORDER BY MIN(q.trip_minutes);") t ~= (sql%([TAXI_TRIPS_schema]) "SELECT\n    LPAD(CAST(MIN(trip_minutes) AS VARCHAR), 2, '0') || 'm to ' || LPAD(CAST(MAX(trip_minutes) AS VARCHAR), 2, '0') || 'm' AS \"TIME_RANGE\",\n    COUNT(*) AS \"TOTAL_TRIPS\",\n    ROUND(AVG(fare), 2) AS \"AVERAGE_FARE\"\nFROM (\n    SELECT\n        FLOOR(\"trip_seconds\" / 60) AS trip_minutes,\n        \"fare\" AS fare,\n        CEIL(FLOOR(\"trip_seconds\" / 60) / 5) AS quantile\n    FROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\"\n    WHERE FLOOR(\"trip_seconds\" / 60) BETWEEN 1 AND 50\n)\nGROUP BY quantile\nORDER BY \"TIME_RANGE\";") t := by
  intro t; first | sql_equiv | sorry

HYPOTHESIS hyp1_3_0 : TAXI_TRIPS "\"trip_seconds\" IS NOT NULL"
HYPOTHESIS hyp1_3_1 : TAXI_TRIPS "FLOOR(\"trip_seconds\" / 60) >= 1"
theorem eq_1_3 (t : TableRel TAXI_TRIPS_schema) (h0 : hyp1_3_0 t) (h1 : hyp1_3_1 t) :
    (sql%([TAXI_TRIPS_schema]) "WITH minute_quantiles AS (\n  SELECT\n    trip_minutes,\n    NTILE(10) OVER (ORDER BY trip_minutes) AS quantile\n  FROM (\n    SELECT DISTINCT CAST(FLOOR(\"trip_seconds\" / 60) AS INT) AS trip_minutes\n    FROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\"\n    WHERE FLOOR(\"trip_seconds\" / 60) BETWEEN 1 AND 50\n  )\n)\nSELECT\n  LPAD(MIN(q.trip_minutes)::VARCHAR, 2, '0') || 'm to ' || LPAD(MAX(q.trip_minutes)::VARCHAR, 2, '0') || 'm' AS TIME_RANGE,\n  COUNT(*) AS TOTAL_TRIPS,\n  ROUND(AVG(t.\"fare\"), 2) AS AVERAGE_FARE\nFROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\" t\nJOIN minute_quantiles q\n  ON CAST(FLOOR(t.\"trip_seconds\" / 60) AS INT) = q.trip_minutes\nWHERE FLOOR(t.\"trip_seconds\" / 60) BETWEEN 1 AND 50\nGROUP BY q.quantile\nORDER BY MIN(q.trip_minutes);") t ~= (sql%([TAXI_TRIPS_schema]) "WITH trip_data AS (\n  SELECT\n    FLOOR(\"trip_seconds\" / 60) AS trip_minutes,\n    \"fare\"\n  FROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\"\n  WHERE \"trip_seconds\" IS NOT NULL\n    AND FLOOR(\"trip_seconds\" / 60) >= 1\n    AND FLOOR(\"trip_seconds\" / 60) <= 50\n),\nbucketed AS (\n  SELECT\n    CASE\n      WHEN trip_minutes BETWEEN 1 AND 5 THEN '01m to 05m'\n      WHEN trip_minutes BETWEEN 6 AND 10 THEN '06m to 10m'\n      WHEN trip_minutes BETWEEN 11 AND 15 THEN '11m to 15m'\n      WHEN trip_minutes BETWEEN 16 AND 20 THEN '16m to 20m'\n      WHEN trip_minutes BETWEEN 21 AND 25 THEN '21m to 25m'\n      WHEN trip_minutes BETWEEN 26 AND 30 THEN '26m to 30m'\n      WHEN trip_minutes BETWEEN 31 AND 35 THEN '31m to 35m'\n      WHEN trip_minutes BETWEEN 36 AND 40 THEN '36m to 40m'\n      WHEN trip_minutes BETWEEN 41 AND 45 THEN '41m to 45m'\n      WHEN trip_minutes BETWEEN 46 AND 50 THEN '46m to 50m'\n    END AS TIME_RANGE,\n    \"fare\"\n  FROM trip_data\n)\nSELECT\n  TIME_RANGE,\n  COUNT(*) AS TOTAL_TRIPS,\n  ROUND(AVG(\"fare\"), 2) AS AVERAGE_FARE\nFROM bucketed\nGROUP BY TIME_RANGE\nORDER BY TIME_RANGE;") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp2_3_0 : TAXI_TRIPS "\"trip_seconds\" IS NOT NULL"
HYPOTHESIS hyp2_3_1 : TAXI_TRIPS "FLOOR(\"trip_seconds\" / 60) >= 1"
theorem eq_2_3 (t : TableRel TAXI_TRIPS_schema) (h0 : hyp2_3_0 t) (h1 : hyp2_3_1 t) :
    (sql%([TAXI_TRIPS_schema]) "SELECT\n    LPAD(CAST(MIN(trip_minutes) AS VARCHAR), 2, '0') || 'm to ' || LPAD(CAST(MAX(trip_minutes) AS VARCHAR), 2, '0') || 'm' AS \"TIME_RANGE\",\n    COUNT(*) AS \"TOTAL_TRIPS\",\n    ROUND(AVG(fare), 2) AS \"AVERAGE_FARE\"\nFROM (\n    SELECT\n        FLOOR(\"trip_seconds\" / 60) AS trip_minutes,\n        \"fare\" AS fare,\n        CEIL(FLOOR(\"trip_seconds\" / 60) / 5) AS quantile\n    FROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\"\n    WHERE FLOOR(\"trip_seconds\" / 60) BETWEEN 1 AND 50\n)\nGROUP BY quantile\nORDER BY \"TIME_RANGE\";") t ~= (sql%([TAXI_TRIPS_schema]) "WITH trip_data AS (\n  SELECT\n    FLOOR(\"trip_seconds\" / 60) AS trip_minutes,\n    \"fare\"\n  FROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\"\n  WHERE \"trip_seconds\" IS NOT NULL\n    AND FLOOR(\"trip_seconds\" / 60) >= 1\n    AND FLOOR(\"trip_seconds\" / 60) <= 50\n),\nbucketed AS (\n  SELECT\n    CASE\n      WHEN trip_minutes BETWEEN 1 AND 5 THEN '01m to 05m'\n      WHEN trip_minutes BETWEEN 6 AND 10 THEN '06m to 10m'\n      WHEN trip_minutes BETWEEN 11 AND 15 THEN '11m to 15m'\n      WHEN trip_minutes BETWEEN 16 AND 20 THEN '16m to 20m'\n      WHEN trip_minutes BETWEEN 21 AND 25 THEN '21m to 25m'\n      WHEN trip_minutes BETWEEN 26 AND 30 THEN '26m to 30m'\n      WHEN trip_minutes BETWEEN 31 AND 35 THEN '31m to 35m'\n      WHEN trip_minutes BETWEEN 36 AND 40 THEN '36m to 40m'\n      WHEN trip_minutes BETWEEN 41 AND 45 THEN '41m to 45m'\n      WHEN trip_minutes BETWEEN 46 AND 50 THEN '46m to 50m'\n    END AS TIME_RANGE,\n    \"fare\"\n  FROM trip_data\n)\nSELECT\n  TIME_RANGE,\n  COUNT(*) AS TOTAL_TRIPS,\n  ROUND(AVG(\"fare\"), 2) AS AVERAGE_FARE\nFROM bucketed\nGROUP BY TIME_RANGE\nORDER BY TIME_RANGE;") t := by
  first | sql_equiv | sorry

end Bench_sf_bq363
