import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_bq230 — crossskill equivalence(s)

Question: Using the crops dataset, find the total 2022 production figures, measured in bushels, for corn from the 'FIELD CROPS' category and mushrooms from the 'HORTICULTURE' group for each U.S. state. Only include data rows where 'statisticcat_desc' is 'PRODUCTION', 'agg_level_desc' is 'STATE', 'value' is not null, and ensure that for corn the 'unit_desc' is 'BU'. Combine both results so that each state’s 2022 corn and mushroom totals are presented.

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_bq230

CREATE TABLE CROPS («source_desc» STRING, «sector_desc» STRING, «group_desc» STRING, «commodity_desc» STRING, «class_desc» STRING, «prodn_practice_desc» STRING, «util_practice_desc» STRING, «statisticcat_desc» STRING, «unit_desc» STRING, «short_desc» STRING, «domain_desc» STRING, «domaincat_desc» STRING, «agg_level_desc» STRING, «state_ansi» INT, «state_fips_code» INT, «state_alpha» STRING, «state_name» STRING, «asd_code» INT, «asd_desc» STRING, «county_ansi» INT, «county_code» INT, «county_name» STRING, «region_desc» STRING, «zip_5» INT, «watershed_code» INT, «watershed_desc» STRING, «congr_district_code» INT, «country_code» INT, «country_name» STRING, «location_desc» STRING, «year» INT, «freq_desc» STRING, «begin_code» INT, «end_code» INT, «reference_period_desc» STRING, «week_ending» STRING, «load_time» INT, «value» FLOAT, «value_suppression_code» STRING, «cv_percent» FLOAT, «cv_suppression_code» STRING)

theorem eq_0_1 :
    sql%([CROPS_schema]) "WITH corn AS (\n    SELECT\n        \"state_name\",\n        SUM(\"value\") AS CORN_PRODUCTION\n    FROM \"USDA_NASS_AGRICULTURE\".\"USDA_NASS_AGRICULTURE\".\"CROPS\"\n    WHERE \"commodity_desc\" = 'CORN'\n      AND \"group_desc\" = 'FIELD CROPS'\n      AND \"statisticcat_desc\" = 'PRODUCTION'\n      AND \"agg_level_desc\" = 'STATE'\n      AND \"unit_desc\" = 'BU'\n      AND \"year\" = 2022\n      AND \"value\" IS NOT NULL\n    GROUP BY \"state_name\"\n),\nmushrooms AS (\n    SELECT\n        \"state_name\",\n        SUM(\"value\") AS MUSHROOM_PRODUCTION\n    FROM \"USDA_NASS_AGRICULTURE\".\"USDA_NASS_AGRICULTURE\".\"CROPS\"\n    WHERE \"commodity_desc\" = 'MUSHROOMS'\n      AND \"group_desc\" = 'HORTICULTURE'\n      AND \"statisticcat_desc\" = 'PRODUCTION'\n      AND \"agg_level_desc\" = 'STATE'\n      AND \"year\" = 2022\n      AND \"value\" IS NOT NULL\n    GROUP BY \"state_name\"\n)\nSELECT\n    COALESCE(c.\"state_name\", m.\"state_name\") AS state_name,\n    COALESCE(c.CORN_PRODUCTION, 0) AS CORN_PRODUCTION,\n    COALESCE(m.MUSHROOM_PRODUCTION, 0) AS MUSHROOM_PRODUCTION\nFROM corn c\nFULL OUTER JOIN mushrooms m\n    ON c.\"state_name\" = m.\"state_name\"\nORDER BY state_name;" = sql%([CROPS_schema]) "WITH corn AS (\n    SELECT\n        \"state_name\",\n        SUM(\"value\") AS CORN_PRODUCTION\n    FROM \"USDA_NASS_AGRICULTURE\".\"USDA_NASS_AGRICULTURE\".\"CROPS\"\n    WHERE \"commodity_desc\" = 'CORN'\n      AND \"group_desc\" = 'FIELD CROPS'\n      AND \"statisticcat_desc\" = 'PRODUCTION'\n      AND \"agg_level_desc\" = 'STATE'\n      AND \"year\" = 2022\n      AND \"unit_desc\" = 'BU'\n      AND \"value\" IS NOT NULL\n    GROUP BY \"state_name\"\n),\nmushrooms AS (\n    SELECT\n        \"state_name\",\n        SUM(\"value\") AS MUSHROOM_PRODUCTION\n    FROM \"USDA_NASS_AGRICULTURE\".\"USDA_NASS_AGRICULTURE\".\"CROPS\"\n    WHERE \"commodity_desc\" = 'MUSHROOMS'\n      AND \"group_desc\" = 'HORTICULTURE'\n      AND \"statisticcat_desc\" = 'PRODUCTION'\n      AND \"agg_level_desc\" = 'STATE'\n      AND \"year\" = 2022\n      AND \"value\" IS NOT NULL\n    GROUP BY \"state_name\"\n)\nSELECT\n    COALESCE(c.\"state_name\", m.\"state_name\") AS state_name,\n    COALESCE(c.CORN_PRODUCTION, 0) AS CORN_PRODUCTION,\n    COALESCE(m.MUSHROOM_PRODUCTION, 0) AS MUSHROOM_PRODUCTION\nFROM corn c\nFULL OUTER JOIN mushrooms m\n    ON c.\"state_name\" = m.\"state_name\"\nORDER BY state_name;" := by
  first | sql_equiv | sorry

theorem eq_0_2 :
    sql%([CROPS_schema]) "WITH corn AS (\n    SELECT\n        \"state_name\",\n        SUM(\"value\") AS CORN_PRODUCTION\n    FROM \"USDA_NASS_AGRICULTURE\".\"USDA_NASS_AGRICULTURE\".\"CROPS\"\n    WHERE \"commodity_desc\" = 'CORN'\n      AND \"group_desc\" = 'FIELD CROPS'\n      AND \"statisticcat_desc\" = 'PRODUCTION'\n      AND \"agg_level_desc\" = 'STATE'\n      AND \"unit_desc\" = 'BU'\n      AND \"year\" = 2022\n      AND \"value\" IS NOT NULL\n    GROUP BY \"state_name\"\n),\nmushrooms AS (\n    SELECT\n        \"state_name\",\n        SUM(\"value\") AS MUSHROOM_PRODUCTION\n    FROM \"USDA_NASS_AGRICULTURE\".\"USDA_NASS_AGRICULTURE\".\"CROPS\"\n    WHERE \"commodity_desc\" = 'MUSHROOMS'\n      AND \"group_desc\" = 'HORTICULTURE'\n      AND \"statisticcat_desc\" = 'PRODUCTION'\n      AND \"agg_level_desc\" = 'STATE'\n      AND \"year\" = 2022\n      AND \"value\" IS NOT NULL\n    GROUP BY \"state_name\"\n)\nSELECT\n    COALESCE(c.\"state_name\", m.\"state_name\") AS state_name,\n    COALESCE(c.CORN_PRODUCTION, 0) AS CORN_PRODUCTION,\n    COALESCE(m.MUSHROOM_PRODUCTION, 0) AS MUSHROOM_PRODUCTION\nFROM corn c\nFULL OUTER JOIN mushrooms m\n    ON c.\"state_name\" = m.\"state_name\"\nORDER BY state_name;" = sql%([CROPS_schema]) "WITH corn AS (\n  SELECT\n    \"state_name\",\n    SUM(CAST(REPLACE(\"value\", ',', '') AS DOUBLE)) AS CORN_PRODUCTION\n  FROM \"USDA_NASS_AGRICULTURE\".\"USDA_NASS_AGRICULTURE\".\"CROPS\"\n  WHERE \"commodity_desc\" = 'CORN'\n    AND \"group_desc\" = 'FIELD CROPS'\n    AND \"statisticcat_desc\" = 'PRODUCTION'\n    AND \"agg_level_desc\" = 'STATE'\n    AND \"year\" = 2022\n    AND \"unit_desc\" = 'BU'\n    AND \"value\" IS NOT NULL\n  GROUP BY \"state_name\"\n),\nmushroom AS (\n  SELECT\n    \"state_name\",\n    SUM(CAST(REPLACE(\"value\", ',', '') AS DOUBLE)) AS MUSHROOM_PRODUCTION\n  FROM \"USDA_NASS_AGRICULTURE\".\"USDA_NASS_AGRICULTURE\".\"CROPS\"\n  WHERE \"commodity_desc\" = 'MUSHROOMS'\n    AND \"group_desc\" = 'HORTICULTURE'\n    AND \"statisticcat_desc\" = 'PRODUCTION'\n    AND \"agg_level_desc\" = 'STATE'\n    AND \"year\" = 2022\n    AND \"value\" IS NOT NULL\n  GROUP BY \"state_name\"\n)\nSELECT\n  COALESCE(c.\"state_name\", m.\"state_name\") AS \"state_name\",\n  c.CORN_PRODUCTION AS \"CORN_PRODUCTION\",\n  m.MUSHROOM_PRODUCTION AS \"MUSHROOM_PRODUCTION\"\nFROM corn c\nFULL OUTER JOIN mushroom m\n  ON c.\"state_name\" = m.\"state_name\"\nORDER BY \"state_name\";" := by
  first | sql_equiv | sorry

HYPOTHESIS hyp0_3_0 : CROPS "\"commodity_desc\" = 'CORN'"
HYPOTHESIS hyp0_3_1 : CROPS "\"group_desc\" = 'FIELD CROPS'"
HYPOTHESIS hyp0_3_2 : CROPS "\"statisticcat_desc\" = 'PRODUCTION'"
HYPOTHESIS hyp0_3_3 : CROPS "\"agg_level_desc\" = 'STATE'"
HYPOTHESIS hyp0_3_4 : CROPS "\"unit_desc\" = 'BU'"
HYPOTHESIS hyp0_3_5 : CROPS "\"value\" IS NOT NULL"
HYPOTHESIS hyp0_3_6 : CROPS "LOWER(\"commodity_desc\") = 'corn'"
HYPOTHESIS hyp0_3_7 : CROPS "LOWER(\"statisticcat_desc\") = 'production'"
HYPOTHESIS hyp0_3_8 : CROPS "LOWER(\"unit_desc\") = 'bu'"
HYPOTHESIS hyp0_3_9 : CROPS "LOWER(\"agg_level_desc\") = 'state'"
theorem eq_0_3 (t : TableRel CROPS_schema) (h0 : hyp0_3_0 t) (h1 : hyp0_3_1 t) (h2 : hyp0_3_2 t) (h3 : hyp0_3_3 t) (h4 : hyp0_3_4 t) (h5 : hyp0_3_5 t) (h6 : hyp0_3_6 t) (h7 : hyp0_3_7 t) (h8 : hyp0_3_8 t) (h9 : hyp0_3_9 t) :
    (sql%([CROPS_schema]) "WITH corn AS (\n    SELECT\n        \"state_name\",\n        SUM(\"value\") AS CORN_PRODUCTION\n    FROM \"USDA_NASS_AGRICULTURE\".\"USDA_NASS_AGRICULTURE\".\"CROPS\"\n    WHERE \"commodity_desc\" = 'CORN'\n      AND \"group_desc\" = 'FIELD CROPS'\n      AND \"statisticcat_desc\" = 'PRODUCTION'\n      AND \"agg_level_desc\" = 'STATE'\n      AND \"unit_desc\" = 'BU'\n      AND \"year\" = 2022\n      AND \"value\" IS NOT NULL\n    GROUP BY \"state_name\"\n),\nmushrooms AS (\n    SELECT\n        \"state_name\",\n        SUM(\"value\") AS MUSHROOM_PRODUCTION\n    FROM \"USDA_NASS_AGRICULTURE\".\"USDA_NASS_AGRICULTURE\".\"CROPS\"\n    WHERE \"commodity_desc\" = 'MUSHROOMS'\n      AND \"group_desc\" = 'HORTICULTURE'\n      AND \"statisticcat_desc\" = 'PRODUCTION'\n      AND \"agg_level_desc\" = 'STATE'\n      AND \"year\" = 2022\n      AND \"value\" IS NOT NULL\n    GROUP BY \"state_name\"\n)\nSELECT\n    COALESCE(c.\"state_name\", m.\"state_name\") AS state_name,\n    COALESCE(c.CORN_PRODUCTION, 0) AS CORN_PRODUCTION,\n    COALESCE(m.MUSHROOM_PRODUCTION, 0) AS MUSHROOM_PRODUCTION\nFROM corn c\nFULL OUTER JOIN mushrooms m\n    ON c.\"state_name\" = m.\"state_name\"\nORDER BY state_name;") t = (sql%([CROPS_schema]) "WITH corn AS (\n  SELECT\n    \"state_name\",\n    SUM(\"value\") AS CORN_PRODUCTION\n  FROM \"USDA_NASS_AGRICULTURE\".\"USDA_NASS_AGRICULTURE\".\"CROPS\"\n  WHERE LOWER(\"commodity_desc\") = 'corn'\n    AND LOWER(\"statisticcat_desc\") = 'production'\n    AND LOWER(\"unit_desc\") = 'bu'\n    AND LOWER(\"agg_level_desc\") = 'state'\n    AND \"year\" = 2022\n  GROUP BY \"state_name\"\n),\nmushrooms AS (\n  SELECT\n    \"state_name\",\n    SUM(\"value\") AS MUSHROOM_PRODUCTION\n  FROM \"USDA_NASS_AGRICULTURE\".\"USDA_NASS_AGRICULTURE\".\"CROPS\"\n  WHERE LOWER(\"commodity_desc\") = 'mushrooms'\n    AND LOWER(\"statisticcat_desc\") = 'production'\n    AND LOWER(\"unit_desc\") = 'lb'\n    AND LOWER(\"agg_level_desc\") = 'state'\n    AND \"year\" = 2022\n  GROUP BY \"state_name\"\n)\nSELECT\n  COALESCE(c.\"state_name\", m.\"state_name\") AS \"state_name\",\n  COALESCE(c.CORN_PRODUCTION, 0.0) AS \"CORN_PRODUCTION\",\n  COALESCE(m.MUSHROOM_PRODUCTION, 0.0) AS \"MUSHROOM_PRODUCTION\"\nFROM corn c\nFULL OUTER JOIN mushrooms m\n  ON c.\"state_name\" = m.\"state_name\"\nORDER BY \"state_name\";") t := by
  first | sql_equiv | sorry

theorem eq_1_2 :
    sql%([CROPS_schema]) "WITH corn AS (\n    SELECT\n        \"state_name\",\n        SUM(\"value\") AS CORN_PRODUCTION\n    FROM \"USDA_NASS_AGRICULTURE\".\"USDA_NASS_AGRICULTURE\".\"CROPS\"\n    WHERE \"commodity_desc\" = 'CORN'\n      AND \"group_desc\" = 'FIELD CROPS'\n      AND \"statisticcat_desc\" = 'PRODUCTION'\n      AND \"agg_level_desc\" = 'STATE'\n      AND \"year\" = 2022\n      AND \"unit_desc\" = 'BU'\n      AND \"value\" IS NOT NULL\n    GROUP BY \"state_name\"\n),\nmushrooms AS (\n    SELECT\n        \"state_name\",\n        SUM(\"value\") AS MUSHROOM_PRODUCTION\n    FROM \"USDA_NASS_AGRICULTURE\".\"USDA_NASS_AGRICULTURE\".\"CROPS\"\n    WHERE \"commodity_desc\" = 'MUSHROOMS'\n      AND \"group_desc\" = 'HORTICULTURE'\n      AND \"statisticcat_desc\" = 'PRODUCTION'\n      AND \"agg_level_desc\" = 'STATE'\n      AND \"year\" = 2022\n      AND \"value\" IS NOT NULL\n    GROUP BY \"state_name\"\n)\nSELECT\n    COALESCE(c.\"state_name\", m.\"state_name\") AS state_name,\n    COALESCE(c.CORN_PRODUCTION, 0) AS CORN_PRODUCTION,\n    COALESCE(m.MUSHROOM_PRODUCTION, 0) AS MUSHROOM_PRODUCTION\nFROM corn c\nFULL OUTER JOIN mushrooms m\n    ON c.\"state_name\" = m.\"state_name\"\nORDER BY state_name;" = sql%([CROPS_schema]) "WITH corn AS (\n  SELECT\n    \"state_name\",\n    SUM(CAST(REPLACE(\"value\", ',', '') AS DOUBLE)) AS CORN_PRODUCTION\n  FROM \"USDA_NASS_AGRICULTURE\".\"USDA_NASS_AGRICULTURE\".\"CROPS\"\n  WHERE \"commodity_desc\" = 'CORN'\n    AND \"group_desc\" = 'FIELD CROPS'\n    AND \"statisticcat_desc\" = 'PRODUCTION'\n    AND \"agg_level_desc\" = 'STATE'\n    AND \"year\" = 2022\n    AND \"unit_desc\" = 'BU'\n    AND \"value\" IS NOT NULL\n  GROUP BY \"state_name\"\n),\nmushroom AS (\n  SELECT\n    \"state_name\",\n    SUM(CAST(REPLACE(\"value\", ',', '') AS DOUBLE)) AS MUSHROOM_PRODUCTION\n  FROM \"USDA_NASS_AGRICULTURE\".\"USDA_NASS_AGRICULTURE\".\"CROPS\"\n  WHERE \"commodity_desc\" = 'MUSHROOMS'\n    AND \"group_desc\" = 'HORTICULTURE'\n    AND \"statisticcat_desc\" = 'PRODUCTION'\n    AND \"agg_level_desc\" = 'STATE'\n    AND \"year\" = 2022\n    AND \"value\" IS NOT NULL\n  GROUP BY \"state_name\"\n)\nSELECT\n  COALESCE(c.\"state_name\", m.\"state_name\") AS \"state_name\",\n  c.CORN_PRODUCTION AS \"CORN_PRODUCTION\",\n  m.MUSHROOM_PRODUCTION AS \"MUSHROOM_PRODUCTION\"\nFROM corn c\nFULL OUTER JOIN mushroom m\n  ON c.\"state_name\" = m.\"state_name\"\nORDER BY \"state_name\";" := by
  first | sql_equiv | sorry

HYPOTHESIS hyp1_3_0 : CROPS "\"commodity_desc\" = 'CORN'"
HYPOTHESIS hyp1_3_1 : CROPS "\"group_desc\" = 'FIELD CROPS'"
HYPOTHESIS hyp1_3_2 : CROPS "\"statisticcat_desc\" = 'PRODUCTION'"
HYPOTHESIS hyp1_3_3 : CROPS "\"agg_level_desc\" = 'STATE'"
HYPOTHESIS hyp1_3_4 : CROPS "\"unit_desc\" = 'BU'"
HYPOTHESIS hyp1_3_5 : CROPS "\"value\" IS NOT NULL"
HYPOTHESIS hyp1_3_6 : CROPS "LOWER(\"commodity_desc\") = 'corn'"
HYPOTHESIS hyp1_3_7 : CROPS "LOWER(\"statisticcat_desc\") = 'production'"
HYPOTHESIS hyp1_3_8 : CROPS "LOWER(\"unit_desc\") = 'bu'"
HYPOTHESIS hyp1_3_9 : CROPS "LOWER(\"agg_level_desc\") = 'state'"
theorem eq_1_3 (t : TableRel CROPS_schema) (h0 : hyp1_3_0 t) (h1 : hyp1_3_1 t) (h2 : hyp1_3_2 t) (h3 : hyp1_3_3 t) (h4 : hyp1_3_4 t) (h5 : hyp1_3_5 t) (h6 : hyp1_3_6 t) (h7 : hyp1_3_7 t) (h8 : hyp1_3_8 t) (h9 : hyp1_3_9 t) :
    (sql%([CROPS_schema]) "WITH corn AS (\n    SELECT\n        \"state_name\",\n        SUM(\"value\") AS CORN_PRODUCTION\n    FROM \"USDA_NASS_AGRICULTURE\".\"USDA_NASS_AGRICULTURE\".\"CROPS\"\n    WHERE \"commodity_desc\" = 'CORN'\n      AND \"group_desc\" = 'FIELD CROPS'\n      AND \"statisticcat_desc\" = 'PRODUCTION'\n      AND \"agg_level_desc\" = 'STATE'\n      AND \"year\" = 2022\n      AND \"unit_desc\" = 'BU'\n      AND \"value\" IS NOT NULL\n    GROUP BY \"state_name\"\n),\nmushrooms AS (\n    SELECT\n        \"state_name\",\n        SUM(\"value\") AS MUSHROOM_PRODUCTION\n    FROM \"USDA_NASS_AGRICULTURE\".\"USDA_NASS_AGRICULTURE\".\"CROPS\"\n    WHERE \"commodity_desc\" = 'MUSHROOMS'\n      AND \"group_desc\" = 'HORTICULTURE'\n      AND \"statisticcat_desc\" = 'PRODUCTION'\n      AND \"agg_level_desc\" = 'STATE'\n      AND \"year\" = 2022\n      AND \"value\" IS NOT NULL\n    GROUP BY \"state_name\"\n)\nSELECT\n    COALESCE(c.\"state_name\", m.\"state_name\") AS state_name,\n    COALESCE(c.CORN_PRODUCTION, 0) AS CORN_PRODUCTION,\n    COALESCE(m.MUSHROOM_PRODUCTION, 0) AS MUSHROOM_PRODUCTION\nFROM corn c\nFULL OUTER JOIN mushrooms m\n    ON c.\"state_name\" = m.\"state_name\"\nORDER BY state_name;") t = (sql%([CROPS_schema]) "WITH corn AS (\n  SELECT\n    \"state_name\",\n    SUM(\"value\") AS CORN_PRODUCTION\n  FROM \"USDA_NASS_AGRICULTURE\".\"USDA_NASS_AGRICULTURE\".\"CROPS\"\n  WHERE LOWER(\"commodity_desc\") = 'corn'\n    AND LOWER(\"statisticcat_desc\") = 'production'\n    AND LOWER(\"unit_desc\") = 'bu'\n    AND LOWER(\"agg_level_desc\") = 'state'\n    AND \"year\" = 2022\n  GROUP BY \"state_name\"\n),\nmushrooms AS (\n  SELECT\n    \"state_name\",\n    SUM(\"value\") AS MUSHROOM_PRODUCTION\n  FROM \"USDA_NASS_AGRICULTURE\".\"USDA_NASS_AGRICULTURE\".\"CROPS\"\n  WHERE LOWER(\"commodity_desc\") = 'mushrooms'\n    AND LOWER(\"statisticcat_desc\") = 'production'\n    AND LOWER(\"unit_desc\") = 'lb'\n    AND LOWER(\"agg_level_desc\") = 'state'\n    AND \"year\" = 2022\n  GROUP BY \"state_name\"\n)\nSELECT\n  COALESCE(c.\"state_name\", m.\"state_name\") AS \"state_name\",\n  COALESCE(c.CORN_PRODUCTION, 0.0) AS \"CORN_PRODUCTION\",\n  COALESCE(m.MUSHROOM_PRODUCTION, 0.0) AS \"MUSHROOM_PRODUCTION\"\nFROM corn c\nFULL OUTER JOIN mushrooms m\n  ON c.\"state_name\" = m.\"state_name\"\nORDER BY \"state_name\";") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp2_3_0 : CROPS "\"commodity_desc\" = 'CORN'"
HYPOTHESIS hyp2_3_1 : CROPS "\"group_desc\" = 'FIELD CROPS'"
HYPOTHESIS hyp2_3_2 : CROPS "\"statisticcat_desc\" = 'PRODUCTION'"
HYPOTHESIS hyp2_3_3 : CROPS "\"agg_level_desc\" = 'STATE'"
HYPOTHESIS hyp2_3_4 : CROPS "\"unit_desc\" = 'BU'"
HYPOTHESIS hyp2_3_5 : CROPS "\"value\" IS NOT NULL"
HYPOTHESIS hyp2_3_6 : CROPS "LOWER(\"commodity_desc\") = 'corn'"
HYPOTHESIS hyp2_3_7 : CROPS "LOWER(\"statisticcat_desc\") = 'production'"
HYPOTHESIS hyp2_3_8 : CROPS "LOWER(\"unit_desc\") = 'bu'"
HYPOTHESIS hyp2_3_9 : CROPS "LOWER(\"agg_level_desc\") = 'state'"
theorem eq_2_3 (t : TableRel CROPS_schema) (h0 : hyp2_3_0 t) (h1 : hyp2_3_1 t) (h2 : hyp2_3_2 t) (h3 : hyp2_3_3 t) (h4 : hyp2_3_4 t) (h5 : hyp2_3_5 t) (h6 : hyp2_3_6 t) (h7 : hyp2_3_7 t) (h8 : hyp2_3_8 t) (h9 : hyp2_3_9 t) :
    (sql%([CROPS_schema]) "WITH corn AS (\n  SELECT\n    \"state_name\",\n    SUM(CAST(REPLACE(\"value\", ',', '') AS DOUBLE)) AS CORN_PRODUCTION\n  FROM \"USDA_NASS_AGRICULTURE\".\"USDA_NASS_AGRICULTURE\".\"CROPS\"\n  WHERE \"commodity_desc\" = 'CORN'\n    AND \"group_desc\" = 'FIELD CROPS'\n    AND \"statisticcat_desc\" = 'PRODUCTION'\n    AND \"agg_level_desc\" = 'STATE'\n    AND \"year\" = 2022\n    AND \"unit_desc\" = 'BU'\n    AND \"value\" IS NOT NULL\n  GROUP BY \"state_name\"\n),\nmushroom AS (\n  SELECT\n    \"state_name\",\n    SUM(CAST(REPLACE(\"value\", ',', '') AS DOUBLE)) AS MUSHROOM_PRODUCTION\n  FROM \"USDA_NASS_AGRICULTURE\".\"USDA_NASS_AGRICULTURE\".\"CROPS\"\n  WHERE \"commodity_desc\" = 'MUSHROOMS'\n    AND \"group_desc\" = 'HORTICULTURE'\n    AND \"statisticcat_desc\" = 'PRODUCTION'\n    AND \"agg_level_desc\" = 'STATE'\n    AND \"year\" = 2022\n    AND \"value\" IS NOT NULL\n  GROUP BY \"state_name\"\n)\nSELECT\n  COALESCE(c.\"state_name\", m.\"state_name\") AS \"state_name\",\n  c.CORN_PRODUCTION AS \"CORN_PRODUCTION\",\n  m.MUSHROOM_PRODUCTION AS \"MUSHROOM_PRODUCTION\"\nFROM corn c\nFULL OUTER JOIN mushroom m\n  ON c.\"state_name\" = m.\"state_name\"\nORDER BY \"state_name\";") t = (sql%([CROPS_schema]) "WITH corn AS (\n  SELECT\n    \"state_name\",\n    SUM(\"value\") AS CORN_PRODUCTION\n  FROM \"USDA_NASS_AGRICULTURE\".\"USDA_NASS_AGRICULTURE\".\"CROPS\"\n  WHERE LOWER(\"commodity_desc\") = 'corn'\n    AND LOWER(\"statisticcat_desc\") = 'production'\n    AND LOWER(\"unit_desc\") = 'bu'\n    AND LOWER(\"agg_level_desc\") = 'state'\n    AND \"year\" = 2022\n  GROUP BY \"state_name\"\n),\nmushrooms AS (\n  SELECT\n    \"state_name\",\n    SUM(\"value\") AS MUSHROOM_PRODUCTION\n  FROM \"USDA_NASS_AGRICULTURE\".\"USDA_NASS_AGRICULTURE\".\"CROPS\"\n  WHERE LOWER(\"commodity_desc\") = 'mushrooms'\n    AND LOWER(\"statisticcat_desc\") = 'production'\n    AND LOWER(\"unit_desc\") = 'lb'\n    AND LOWER(\"agg_level_desc\") = 'state'\n    AND \"year\" = 2022\n  GROUP BY \"state_name\"\n)\nSELECT\n  COALESCE(c.\"state_name\", m.\"state_name\") AS \"state_name\",\n  COALESCE(c.CORN_PRODUCTION, 0.0) AS \"CORN_PRODUCTION\",\n  COALESCE(m.MUSHROOM_PRODUCTION, 0.0) AS \"MUSHROOM_PRODUCTION\"\nFROM corn c\nFULL OUTER JOIN mushrooms m\n  ON c.\"state_name\" = m.\"state_name\"\nORDER BY \"state_name\";") t := by
  first | sql_equiv | sorry

end Bench_sf_bq230
