import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_local035 — crossskill equivalence(s)

Question: In the “olist_geolocation” table, please identify which two consecutive cities, when sorted by geolocation_state, geolocation_city, geolocation_zip_code_prefix, geolocation_lat, and geolocation_lng, have the greatest distance between them based on the difference in distance computed between each city and its immediate predecessor in that ordering.

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_local035

CREATE TABLE OLIST_GEOLOCATION («geolocation_zip_code_prefix» INT, «geolocation_lat» FLOAT, «geolocation_lng» FLOAT, «geolocation_city» STRING, «geolocation_state» STRING)

theorem eq_0_1 : ∀ t,
    (sql%([OLIST_GEOLOCATION_schema]) "WITH ordered AS (\n  SELECT \n    \"geolocation_city\",\n    \"geolocation_lat\",\n    \"geolocation_lng\",\n    LAG(\"geolocation_city\") OVER (\n      ORDER BY \"geolocation_state\", \"geolocation_city\", \"geolocation_zip_code_prefix\", \"geolocation_lat\", \"geolocation_lng\"\n    ) AS prev_city,\n    LAG(\"geolocation_lat\") OVER (\n      ORDER BY \"geolocation_state\", \"geolocation_city\", \"geolocation_zip_code_prefix\", \"geolocation_lat\", \"geolocation_lng\"\n    ) AS prev_lat,\n    LAG(\"geolocation_lng\") OVER (\n      ORDER BY \"geolocation_state\", \"geolocation_city\", \"geolocation_zip_code_prefix\", \"geolocation_lat\", \"geolocation_lng\"\n    ) AS prev_lng\n  FROM \"BRAZILIAN_E_COMMERCE\".\"BRAZILIAN_E_COMMERCE\".\"OLIST_GEOLOCATION\"\n),\nwith_distance AS (\n  SELECT \n    \"geolocation_city\" AS CITY_ONE,\n    prev_city AS CITY_TWO,\n    6371 * ACOS(\n      LEAST(1.0, GREATEST(-1.0,\n        COS(RADIANS(prev_lat)) * COS(RADIANS(\"geolocation_lat\")) * COS(RADIANS(\"geolocation_lng\") - RADIANS(prev_lng))\n        + SIN(RADIANS(prev_lat)) * SIN(RADIANS(\"geolocation_lat\"))\n      ))\n    ) AS distance_km\n  FROM ordered\n  WHERE prev_lat IS NOT NULL\n    AND prev_city IS NOT NULL\n    AND prev_city != \"geolocation_city\"\n)\nSELECT CITY_ONE, CITY_TWO\nFROM with_distance\nORDER BY distance_km DESC\nLIMIT 1;") t ~= (sql%([OLIST_GEOLOCATION_schema]) "WITH filtered AS (\n    SELECT * FROM \"BRAZILIAN_E_COMMERCE\".\"BRAZILIAN_E_COMMERCE\".\"OLIST_GEOLOCATION\"\n    WHERE \"geolocation_lat\" BETWEEN -35 AND 30 \n      AND \"geolocation_lng\" BETWEEN -80 AND -10\n),\ncity_avg AS (\n    SELECT \n        \"geolocation_city\" AS city,\n        \"geolocation_state\" AS state,\n        AVG(\"geolocation_lat\") AS avg_lat,\n        AVG(\"geolocation_lng\") AS avg_lng\n    FROM filtered\n    GROUP BY \"geolocation_city\", \"geolocation_state\"\n),\nordered AS (\n    SELECT \n        city, state, avg_lat, avg_lng,\n        LAG(city) OVER (ORDER BY state, city) AS prev_city,\n        LAG(avg_lat) OVER (ORDER BY state, city) AS prev_lat,\n        LAG(avg_lng) OVER (ORDER BY state, city) AS prev_lng\n    FROM city_avg\n),\nwith_dist AS (\n    SELECT \n        city AS city_one,\n        prev_city AS city_two,\n        6371 * ACOS(\n            GREATEST(-1, LEAST(1,\n                COS(RADIANS(prev_lat)) * COS(RADIANS(avg_lat)) * COS(RADIANS(avg_lng) - RADIANS(prev_lng)) +\n                SIN(RADIANS(prev_lat)) * SIN(RADIANS(avg_lat))\n            ))\n        ) AS distance_km\n    FROM ordered\n    WHERE prev_city IS NOT NULL AND city != prev_city\n)\nSELECT city_one, city_two\nFROM with_dist\nORDER BY distance_km DESC\nLIMIT 1;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_0_2 :
    sql%([OLIST_GEOLOCATION_schema]) "WITH ordered AS (\n  SELECT \n    \"geolocation_city\",\n    \"geolocation_lat\",\n    \"geolocation_lng\",\n    LAG(\"geolocation_city\") OVER (\n      ORDER BY \"geolocation_state\", \"geolocation_city\", \"geolocation_zip_code_prefix\", \"geolocation_lat\", \"geolocation_lng\"\n    ) AS prev_city,\n    LAG(\"geolocation_lat\") OVER (\n      ORDER BY \"geolocation_state\", \"geolocation_city\", \"geolocation_zip_code_prefix\", \"geolocation_lat\", \"geolocation_lng\"\n    ) AS prev_lat,\n    LAG(\"geolocation_lng\") OVER (\n      ORDER BY \"geolocation_state\", \"geolocation_city\", \"geolocation_zip_code_prefix\", \"geolocation_lat\", \"geolocation_lng\"\n    ) AS prev_lng\n  FROM \"BRAZILIAN_E_COMMERCE\".\"BRAZILIAN_E_COMMERCE\".\"OLIST_GEOLOCATION\"\n),\nwith_distance AS (\n  SELECT \n    \"geolocation_city\" AS CITY_ONE,\n    prev_city AS CITY_TWO,\n    6371 * ACOS(\n      LEAST(1.0, GREATEST(-1.0,\n        COS(RADIANS(prev_lat)) * COS(RADIANS(\"geolocation_lat\")) * COS(RADIANS(\"geolocation_lng\") - RADIANS(prev_lng))\n        + SIN(RADIANS(prev_lat)) * SIN(RADIANS(\"geolocation_lat\"))\n      ))\n    ) AS distance_km\n  FROM ordered\n  WHERE prev_lat IS NOT NULL\n    AND prev_city IS NOT NULL\n    AND prev_city != \"geolocation_city\"\n)\nSELECT CITY_ONE, CITY_TWO\nFROM with_distance\nORDER BY distance_km DESC\nLIMIT 1;" = sql%([OLIST_GEOLOCATION_schema]) "WITH ordered AS (\n    SELECT\n        \"geolocation_city\",\n        \"geolocation_lat\",\n        \"geolocation_lng\",\n        LAG(\"geolocation_city\") OVER (\n            ORDER BY \"geolocation_state\", \"geolocation_city\", \"geolocation_zip_code_prefix\", \"geolocation_lat\", \"geolocation_lng\"\n        ) AS prev_city,\n        LAG(\"geolocation_lat\") OVER (\n            ORDER BY \"geolocation_state\", \"geolocation_city\", \"geolocation_zip_code_prefix\", \"geolocation_lat\", \"geolocation_lng\"\n        ) AS prev_lat,\n        LAG(\"geolocation_lng\") OVER (\n            ORDER BY \"geolocation_state\", \"geolocation_city\", \"geolocation_zip_code_prefix\", \"geolocation_lat\", \"geolocation_lng\"\n        ) AS prev_lng\n    FROM \"BRAZILIAN_E_COMMERCE\".\"BRAZILIAN_E_COMMERCE\".\"OLIST_GEOLOCATION\"\n),\ndistances AS (\n    SELECT\n        prev_city AS city_one,\n        \"geolocation_city\" AS city_two,\n        6371 * ACOS(\n            LEAST(1.0, GREATEST(-1.0,\n                COS(RADIANS(prev_lat)) * COS(RADIANS(\"geolocation_lat\")) * COS(RADIANS(\"geolocation_lng\") - RADIANS(prev_lng))\n                + SIN(RADIANS(prev_lat)) * SIN(RADIANS(\"geolocation_lat\"))\n            ))\n        ) AS distance_km\n    FROM ordered\n    WHERE prev_city IS NOT NULL\n)\nSELECT\n    city_one AS \"CITY_ONE\",\n    city_two AS \"CITY_TWO\"\nFROM distances\nORDER BY distance_km DESC\nLIMIT 1;" := by
  first | sql_equiv | sorry

theorem eq_0_3 :
    sql%([OLIST_GEOLOCATION_schema]) "WITH ordered AS (\n  SELECT \n    \"geolocation_city\",\n    \"geolocation_lat\",\n    \"geolocation_lng\",\n    LAG(\"geolocation_city\") OVER (\n      ORDER BY \"geolocation_state\", \"geolocation_city\", \"geolocation_zip_code_prefix\", \"geolocation_lat\", \"geolocation_lng\"\n    ) AS prev_city,\n    LAG(\"geolocation_lat\") OVER (\n      ORDER BY \"geolocation_state\", \"geolocation_city\", \"geolocation_zip_code_prefix\", \"geolocation_lat\", \"geolocation_lng\"\n    ) AS prev_lat,\n    LAG(\"geolocation_lng\") OVER (\n      ORDER BY \"geolocation_state\", \"geolocation_city\", \"geolocation_zip_code_prefix\", \"geolocation_lat\", \"geolocation_lng\"\n    ) AS prev_lng\n  FROM \"BRAZILIAN_E_COMMERCE\".\"BRAZILIAN_E_COMMERCE\".\"OLIST_GEOLOCATION\"\n),\nwith_distance AS (\n  SELECT \n    \"geolocation_city\" AS CITY_ONE,\n    prev_city AS CITY_TWO,\n    6371 * ACOS(\n      LEAST(1.0, GREATEST(-1.0,\n        COS(RADIANS(prev_lat)) * COS(RADIANS(\"geolocation_lat\")) * COS(RADIANS(\"geolocation_lng\") - RADIANS(prev_lng))\n        + SIN(RADIANS(prev_lat)) * SIN(RADIANS(\"geolocation_lat\"))\n      ))\n    ) AS distance_km\n  FROM ordered\n  WHERE prev_lat IS NOT NULL\n    AND prev_city IS NOT NULL\n    AND prev_city != \"geolocation_city\"\n)\nSELECT CITY_ONE, CITY_TWO\nFROM with_distance\nORDER BY distance_km DESC\nLIMIT 1;" = sql%([OLIST_GEOLOCATION_schema]) "WITH ordered_geo AS (\n    SELECT\n        \"geolocation_city\",\n        \"geolocation_lat\",\n        \"geolocation_lng\",\n        LAG(\"geolocation_city\") OVER (\n            ORDER BY \"geolocation_state\", \"geolocation_city\", \"geolocation_zip_code_prefix\", \"geolocation_lat\", \"geolocation_lng\"\n        ) AS prev_city,\n        LAG(\"geolocation_lat\") OVER (\n            ORDER BY \"geolocation_state\", \"geolocation_city\", \"geolocation_zip_code_prefix\", \"geolocation_lat\", \"geolocation_lng\"\n        ) AS prev_lat,\n        LAG(\"geolocation_lng\") OVER (\n            ORDER BY \"geolocation_state\", \"geolocation_city\", \"geolocation_zip_code_prefix\", \"geolocation_lat\", \"geolocation_lng\"\n        ) AS prev_lng\n    FROM \"BRAZILIAN_E_COMMERCE\".\"BRAZILIAN_E_COMMERCE\".\"OLIST_GEOLOCATION\"\n),\ndistances AS (\n    SELECT\n        prev_city AS \"CITY_ONE\",\n        \"geolocation_city\" AS \"CITY_TWO\",\n        6371 * ACOS(\n            LEAST(1.0, GREATEST(-1.0,\n                COS(RADIANS(prev_lat)) * COS(RADIANS(\"geolocation_lat\")) * COS(RADIANS(\"geolocation_lng\") - RADIANS(prev_lng))\n                + SIN(RADIANS(prev_lat)) * SIN(RADIANS(\"geolocation_lat\"))\n            ))\n        ) AS distance_km\n    FROM ordered_geo\n    WHERE prev_city IS NOT NULL\n)\nSELECT \"CITY_ONE\", \"CITY_TWO\"\nFROM distances\nORDER BY distance_km DESC\nLIMIT 1;" := by
  first | sql_equiv | sorry

theorem eq_1_2 : ∀ t,
    (sql%([OLIST_GEOLOCATION_schema]) "WITH filtered AS (\n    SELECT * FROM \"BRAZILIAN_E_COMMERCE\".\"BRAZILIAN_E_COMMERCE\".\"OLIST_GEOLOCATION\"\n    WHERE \"geolocation_lat\" BETWEEN -35 AND 30 \n      AND \"geolocation_lng\" BETWEEN -80 AND -10\n),\ncity_avg AS (\n    SELECT \n        \"geolocation_city\" AS city,\n        \"geolocation_state\" AS state,\n        AVG(\"geolocation_lat\") AS avg_lat,\n        AVG(\"geolocation_lng\") AS avg_lng\n    FROM filtered\n    GROUP BY \"geolocation_city\", \"geolocation_state\"\n),\nordered AS (\n    SELECT \n        city, state, avg_lat, avg_lng,\n        LAG(city) OVER (ORDER BY state, city) AS prev_city,\n        LAG(avg_lat) OVER (ORDER BY state, city) AS prev_lat,\n        LAG(avg_lng) OVER (ORDER BY state, city) AS prev_lng\n    FROM city_avg\n),\nwith_dist AS (\n    SELECT \n        city AS city_one,\n        prev_city AS city_two,\n        6371 * ACOS(\n            GREATEST(-1, LEAST(1,\n                COS(RADIANS(prev_lat)) * COS(RADIANS(avg_lat)) * COS(RADIANS(avg_lng) - RADIANS(prev_lng)) +\n                SIN(RADIANS(prev_lat)) * SIN(RADIANS(avg_lat))\n            ))\n        ) AS distance_km\n    FROM ordered\n    WHERE prev_city IS NOT NULL AND city != prev_city\n)\nSELECT city_one, city_two\nFROM with_dist\nORDER BY distance_km DESC\nLIMIT 1;") t ~= (sql%([OLIST_GEOLOCATION_schema]) "WITH ordered AS (\n    SELECT\n        \"geolocation_city\",\n        \"geolocation_lat\",\n        \"geolocation_lng\",\n        LAG(\"geolocation_city\") OVER (\n            ORDER BY \"geolocation_state\", \"geolocation_city\", \"geolocation_zip_code_prefix\", \"geolocation_lat\", \"geolocation_lng\"\n        ) AS prev_city,\n        LAG(\"geolocation_lat\") OVER (\n            ORDER BY \"geolocation_state\", \"geolocation_city\", \"geolocation_zip_code_prefix\", \"geolocation_lat\", \"geolocation_lng\"\n        ) AS prev_lat,\n        LAG(\"geolocation_lng\") OVER (\n            ORDER BY \"geolocation_state\", \"geolocation_city\", \"geolocation_zip_code_prefix\", \"geolocation_lat\", \"geolocation_lng\"\n        ) AS prev_lng\n    FROM \"BRAZILIAN_E_COMMERCE\".\"BRAZILIAN_E_COMMERCE\".\"OLIST_GEOLOCATION\"\n),\ndistances AS (\n    SELECT\n        prev_city AS city_one,\n        \"geolocation_city\" AS city_two,\n        6371 * ACOS(\n            LEAST(1.0, GREATEST(-1.0,\n                COS(RADIANS(prev_lat)) * COS(RADIANS(\"geolocation_lat\")) * COS(RADIANS(\"geolocation_lng\") - RADIANS(prev_lng))\n                + SIN(RADIANS(prev_lat)) * SIN(RADIANS(\"geolocation_lat\"))\n            ))\n        ) AS distance_km\n    FROM ordered\n    WHERE prev_city IS NOT NULL\n)\nSELECT\n    city_one AS \"CITY_ONE\",\n    city_two AS \"CITY_TWO\"\nFROM distances\nORDER BY distance_km DESC\nLIMIT 1;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_1_3 : ∀ t,
    (sql%([OLIST_GEOLOCATION_schema]) "WITH filtered AS (\n    SELECT * FROM \"BRAZILIAN_E_COMMERCE\".\"BRAZILIAN_E_COMMERCE\".\"OLIST_GEOLOCATION\"\n    WHERE \"geolocation_lat\" BETWEEN -35 AND 30 \n      AND \"geolocation_lng\" BETWEEN -80 AND -10\n),\ncity_avg AS (\n    SELECT \n        \"geolocation_city\" AS city,\n        \"geolocation_state\" AS state,\n        AVG(\"geolocation_lat\") AS avg_lat,\n        AVG(\"geolocation_lng\") AS avg_lng\n    FROM filtered\n    GROUP BY \"geolocation_city\", \"geolocation_state\"\n),\nordered AS (\n    SELECT \n        city, state, avg_lat, avg_lng,\n        LAG(city) OVER (ORDER BY state, city) AS prev_city,\n        LAG(avg_lat) OVER (ORDER BY state, city) AS prev_lat,\n        LAG(avg_lng) OVER (ORDER BY state, city) AS prev_lng\n    FROM city_avg\n),\nwith_dist AS (\n    SELECT \n        city AS city_one,\n        prev_city AS city_two,\n        6371 * ACOS(\n            GREATEST(-1, LEAST(1,\n                COS(RADIANS(prev_lat)) * COS(RADIANS(avg_lat)) * COS(RADIANS(avg_lng) - RADIANS(prev_lng)) +\n                SIN(RADIANS(prev_lat)) * SIN(RADIANS(avg_lat))\n            ))\n        ) AS distance_km\n    FROM ordered\n    WHERE prev_city IS NOT NULL AND city != prev_city\n)\nSELECT city_one, city_two\nFROM with_dist\nORDER BY distance_km DESC\nLIMIT 1;") t ~= (sql%([OLIST_GEOLOCATION_schema]) "WITH ordered_geo AS (\n    SELECT\n        \"geolocation_city\",\n        \"geolocation_lat\",\n        \"geolocation_lng\",\n        LAG(\"geolocation_city\") OVER (\n            ORDER BY \"geolocation_state\", \"geolocation_city\", \"geolocation_zip_code_prefix\", \"geolocation_lat\", \"geolocation_lng\"\n        ) AS prev_city,\n        LAG(\"geolocation_lat\") OVER (\n            ORDER BY \"geolocation_state\", \"geolocation_city\", \"geolocation_zip_code_prefix\", \"geolocation_lat\", \"geolocation_lng\"\n        ) AS prev_lat,\n        LAG(\"geolocation_lng\") OVER (\n            ORDER BY \"geolocation_state\", \"geolocation_city\", \"geolocation_zip_code_prefix\", \"geolocation_lat\", \"geolocation_lng\"\n        ) AS prev_lng\n    FROM \"BRAZILIAN_E_COMMERCE\".\"BRAZILIAN_E_COMMERCE\".\"OLIST_GEOLOCATION\"\n),\ndistances AS (\n    SELECT\n        prev_city AS \"CITY_ONE\",\n        \"geolocation_city\" AS \"CITY_TWO\",\n        6371 * ACOS(\n            LEAST(1.0, GREATEST(-1.0,\n                COS(RADIANS(prev_lat)) * COS(RADIANS(\"geolocation_lat\")) * COS(RADIANS(\"geolocation_lng\") - RADIANS(prev_lng))\n                + SIN(RADIANS(prev_lat)) * SIN(RADIANS(\"geolocation_lat\"))\n            ))\n        ) AS distance_km\n    FROM ordered_geo\n    WHERE prev_city IS NOT NULL\n)\nSELECT \"CITY_ONE\", \"CITY_TWO\"\nFROM distances\nORDER BY distance_km DESC\nLIMIT 1;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_2_3 :
    sql%([OLIST_GEOLOCATION_schema]) "WITH ordered AS (\n    SELECT\n        \"geolocation_city\",\n        \"geolocation_lat\",\n        \"geolocation_lng\",\n        LAG(\"geolocation_city\") OVER (\n            ORDER BY \"geolocation_state\", \"geolocation_city\", \"geolocation_zip_code_prefix\", \"geolocation_lat\", \"geolocation_lng\"\n        ) AS prev_city,\n        LAG(\"geolocation_lat\") OVER (\n            ORDER BY \"geolocation_state\", \"geolocation_city\", \"geolocation_zip_code_prefix\", \"geolocation_lat\", \"geolocation_lng\"\n        ) AS prev_lat,\n        LAG(\"geolocation_lng\") OVER (\n            ORDER BY \"geolocation_state\", \"geolocation_city\", \"geolocation_zip_code_prefix\", \"geolocation_lat\", \"geolocation_lng\"\n        ) AS prev_lng\n    FROM \"BRAZILIAN_E_COMMERCE\".\"BRAZILIAN_E_COMMERCE\".\"OLIST_GEOLOCATION\"\n),\ndistances AS (\n    SELECT\n        prev_city AS city_one,\n        \"geolocation_city\" AS city_two,\n        6371 * ACOS(\n            LEAST(1.0, GREATEST(-1.0,\n                COS(RADIANS(prev_lat)) * COS(RADIANS(\"geolocation_lat\")) * COS(RADIANS(\"geolocation_lng\") - RADIANS(prev_lng))\n                + SIN(RADIANS(prev_lat)) * SIN(RADIANS(\"geolocation_lat\"))\n            ))\n        ) AS distance_km\n    FROM ordered\n    WHERE prev_city IS NOT NULL\n)\nSELECT\n    city_one AS \"CITY_ONE\",\n    city_two AS \"CITY_TWO\"\nFROM distances\nORDER BY distance_km DESC\nLIMIT 1;" = sql%([OLIST_GEOLOCATION_schema]) "WITH ordered_geo AS (\n    SELECT\n        \"geolocation_city\",\n        \"geolocation_lat\",\n        \"geolocation_lng\",\n        LAG(\"geolocation_city\") OVER (\n            ORDER BY \"geolocation_state\", \"geolocation_city\", \"geolocation_zip_code_prefix\", \"geolocation_lat\", \"geolocation_lng\"\n        ) AS prev_city,\n        LAG(\"geolocation_lat\") OVER (\n            ORDER BY \"geolocation_state\", \"geolocation_city\", \"geolocation_zip_code_prefix\", \"geolocation_lat\", \"geolocation_lng\"\n        ) AS prev_lat,\n        LAG(\"geolocation_lng\") OVER (\n            ORDER BY \"geolocation_state\", \"geolocation_city\", \"geolocation_zip_code_prefix\", \"geolocation_lat\", \"geolocation_lng\"\n        ) AS prev_lng\n    FROM \"BRAZILIAN_E_COMMERCE\".\"BRAZILIAN_E_COMMERCE\".\"OLIST_GEOLOCATION\"\n),\ndistances AS (\n    SELECT\n        prev_city AS \"CITY_ONE\",\n        \"geolocation_city\" AS \"CITY_TWO\",\n        6371 * ACOS(\n            LEAST(1.0, GREATEST(-1.0,\n                COS(RADIANS(prev_lat)) * COS(RADIANS(\"geolocation_lat\")) * COS(RADIANS(\"geolocation_lng\") - RADIANS(prev_lng))\n                + SIN(RADIANS(prev_lat)) * SIN(RADIANS(\"geolocation_lat\"))\n            ))\n        ) AS distance_km\n    FROM ordered_geo\n    WHERE prev_city IS NOT NULL\n)\nSELECT \"CITY_ONE\", \"CITY_TWO\"\nFROM distances\nORDER BY distance_km DESC\nLIMIT 1;" := by
  first | sql_equiv | sorry

end Bench_sf_local035
