import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_bq432 — crossskill equivalence(s)

Question: Please provide the food events data where both \"date_created\" and \"date_started\" are between January 1 and January 31, 2015, apply the following data cleansing steps: split reactions and outcomes fields into arrays by commas, handle special numeric patterns in the products_brand_name field (where a digit is followed by comma and another digit) by preserving those numeric patterns while replacing other ", " with " -- ", replace ", " with " -- " in products_industry_code, products_role, and products_industry_name fields, and calculate industry_code_length and brand_name_length as the array lengths after splitting.

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_bq432

CREATE TABLE FOOD_EVENTS («report_number» STRING, «reactions» STRING, «outcomes» STRING, «products_brand_name» STRING, «products_industry_code» STRING, «products_role» STRING, «products_industry_name» STRING, «date_created» STRING, «date_started» STRING, «consumer_gender» STRING, «consumer_age» FLOAT, «consumer_age_unit» STRING)

HYPOTHESIS hyp0_1_0 : FOOD_EVENTS "REPLACE(\"products_industry_code\", ', ', ' -- ') = \"products_industry_code\""
theorem eq_0_1 (t : TableRel FOOD_EVENTS_schema) (h0 : hyp0_1_0 t) :
    (sql%([FOOD_EVENTS_schema]) "SELECT\n  \"report_number\",\n  SPLIT(\"reactions\", ', ') AS \"REACTIONS\",\n  SPLIT(\"outcomes\", ', ') AS \"OUTCOMES\",\n  REPLACE(\"products_brand_name\", ', ', ' -- ') AS \"PRODUCTS_BRAND_NAME\",\n  REPLACE(\"products_industry_code\", ', ', ' -- ') AS \"PRODUCTS_INDUSTRY_CODE\",\n  \"products_role\" AS \"PRODUCTS_ROLE\",\n  REPLACE(\"products_industry_name\", ', ', ' -- ') AS \"PRODUCTS_INDUSTRY_NAME\",\n  \"date_created\",\n  \"date_started\",\n  \"consumer_gender\",\n  \"consumer_age\",\n  \"consumer_age_unit\",\n  ARRAY_SIZE(SPLIT(REPLACE(\"products_industry_code\", ', ', ' -- '), ' -- ')) AS \"INDUSTRY_CODE_LENGTH\",\n  ARRAY_SIZE(SPLIT(REPLACE(\"products_brand_name\", ', ', ' -- '), ' -- ')) AS \"BRAND_NAME_LENGTH\"\nFROM \"FDA\".\"FDA_FOOD\".\"FOOD_EVENTS\"\nWHERE \"date_started\" >= '2015-01-01' AND \"date_started\" < '2015-02-01'\n  AND \"date_created\" >= '2015-01-01' AND \"date_created\" < '2015-02-01'") t = (sql%([FOOD_EVENTS_schema]) "SELECT\n  \"report_number\",\n  SPLIT(\"reactions\", ', ') AS \"REACTIONS\",\n  SPLIT(\"outcomes\", ', ') AS \"OUTCOMES\",\n  REPLACE(\"products_brand_name\", ', ', ' -- ') AS \"PRODUCTS_BRAND_NAME\",\n  \"products_industry_code\" AS \"PRODUCTS_INDUSTRY_CODE\",\n  \"products_role\" AS \"PRODUCTS_ROLE\",\n  REPLACE(\"products_industry_name\", ', ', ' -- ') AS \"PRODUCTS_INDUSTRY_NAME\",\n  \"date_created\",\n  \"date_started\",\n  \"consumer_gender\",\n  \"consumer_age\",\n  \"consumer_age_unit\",\n  ARRAY_SIZE(SPLIT(\"products_industry_code\", ', ')) AS \"INDUSTRY_CODE_LENGTH\",\n  ARRAY_SIZE(SPLIT(\"products_brand_name\", ', ')) AS \"BRAND_NAME_LENGTH\"\nFROM \"FDA\".\"FDA_FOOD\".\"FOOD_EVENTS\"\nWHERE \"date_created\" >= '2015-01-01' AND \"date_created\" < '2015-02-01'\n  AND \"date_started\" >= '2015-01-01' AND \"date_started\" < '2015-02-01'\nORDER BY \"REACTIONS\", \"consumer_age\"") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp0_2_0 : FOOD_EVENTS "\"date_started\" < '2015-02-01'"
HYPOTHESIS hyp0_2_1 : FOOD_EVENTS "\"date_created\" < '2015-02-01'"
HYPOTHESIS hyp0_2_2 : FOOD_EVENTS "\"date_created\" <= '2015-01-31'"
HYPOTHESIS hyp0_2_3 : FOOD_EVENTS "\"date_started\" <= '2015-01-31'"
HYPOTHESIS hyp0_2_4 : FOOD_EVENTS "\"products_role\" = REPLACE(\"products_role\", ', ', ' -- ')"
theorem eq_0_2 (t : TableRel FOOD_EVENTS_schema) (h0 : hyp0_2_0 t) (h1 : hyp0_2_1 t) (h2 : hyp0_2_2 t) (h3 : hyp0_2_3 t) (h4 : hyp0_2_4 t) :
    (sql%([FOOD_EVENTS_schema]) "SELECT\n  \"report_number\",\n  SPLIT(\"reactions\", ', ') AS \"REACTIONS\",\n  SPLIT(\"outcomes\", ', ') AS \"OUTCOMES\",\n  REPLACE(\"products_brand_name\", ', ', ' -- ') AS \"PRODUCTS_BRAND_NAME\",\n  REPLACE(\"products_industry_code\", ', ', ' -- ') AS \"PRODUCTS_INDUSTRY_CODE\",\n  \"products_role\" AS \"PRODUCTS_ROLE\",\n  REPLACE(\"products_industry_name\", ', ', ' -- ') AS \"PRODUCTS_INDUSTRY_NAME\",\n  \"date_created\",\n  \"date_started\",\n  \"consumer_gender\",\n  \"consumer_age\",\n  \"consumer_age_unit\",\n  ARRAY_SIZE(SPLIT(REPLACE(\"products_industry_code\", ', ', ' -- '), ' -- ')) AS \"INDUSTRY_CODE_LENGTH\",\n  ARRAY_SIZE(SPLIT(REPLACE(\"products_brand_name\", ', ', ' -- '), ' -- ')) AS \"BRAND_NAME_LENGTH\"\nFROM \"FDA\".\"FDA_FOOD\".\"FOOD_EVENTS\"\nWHERE \"date_started\" >= '2015-01-01' AND \"date_started\" < '2015-02-01'\n  AND \"date_created\" >= '2015-01-01' AND \"date_created\" < '2015-02-01'") t = (sql%([FOOD_EVENTS_schema]) "SELECT\n  \"report_number\",\n  SPLIT(\"reactions\", ', ') AS \"REACTIONS\",\n  SPLIT(\"outcomes\", ', ') AS \"OUTCOMES\",\n  REPLACE(\"products_brand_name\", ', ', ' -- ') AS \"PRODUCTS_BRAND_NAME\",\n  REPLACE(\"products_industry_code\", ', ', ' -- ') AS \"PRODUCTS_INDUSTRY_CODE\",\n  REPLACE(\"products_role\", ', ', ' -- ') AS \"PRODUCTS_ROLE\",\n  REPLACE(\"products_industry_name\", ', ', ' -- ') AS \"PRODUCTS_INDUSTRY_NAME\",\n  \"date_created\",\n  \"date_started\",\n  \"consumer_gender\",\n  \"consumer_age\",\n  \"consumer_age_unit\",\n  ARRAY_SIZE(SPLIT(\"products_industry_code\", ', ')) AS \"INDUSTRY_CODE_LENGTH\",\n  ARRAY_SIZE(SPLIT(\"products_brand_name\", ', ')) AS \"BRAND_NAME_LENGTH\"\nFROM \"FDA\".\"FDA_FOOD\".\"FOOD_EVENTS\"\nWHERE \"date_created\" >= '2015-01-01'\n  AND \"date_created\" <= '2015-01-31'\n  AND \"date_started\" >= '2015-01-01'\n  AND \"date_started\" <= '2015-01-31';") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp0_3_0 : FOOD_EVENTS "\"date_started\" < '2015-02-01'"
HYPOTHESIS hyp0_3_1 : FOOD_EVENTS "\"date_created\" < '2015-02-01'"
HYPOTHESIS hyp0_3_2 : FOOD_EVENTS "\"date_created\" <= '2015-01-31'"
HYPOTHESIS hyp0_3_3 : FOOD_EVENTS "\"date_started\" <= '2015-01-31'"
HYPOTHESIS hyp0_3_4 : FOOD_EVENTS "\"products_role\" = REPLACE(\"products_role\", ', ', ' -- ')"
theorem eq_0_3 (t : TableRel FOOD_EVENTS_schema) (h0 : hyp0_3_0 t) (h1 : hyp0_3_1 t) (h2 : hyp0_3_2 t) (h3 : hyp0_3_3 t) (h4 : hyp0_3_4 t) :
    (sql%([FOOD_EVENTS_schema]) "SELECT\n  \"report_number\",\n  SPLIT(\"reactions\", ', ') AS \"REACTIONS\",\n  SPLIT(\"outcomes\", ', ') AS \"OUTCOMES\",\n  REPLACE(\"products_brand_name\", ', ', ' -- ') AS \"PRODUCTS_BRAND_NAME\",\n  REPLACE(\"products_industry_code\", ', ', ' -- ') AS \"PRODUCTS_INDUSTRY_CODE\",\n  \"products_role\" AS \"PRODUCTS_ROLE\",\n  REPLACE(\"products_industry_name\", ', ', ' -- ') AS \"PRODUCTS_INDUSTRY_NAME\",\n  \"date_created\",\n  \"date_started\",\n  \"consumer_gender\",\n  \"consumer_age\",\n  \"consumer_age_unit\",\n  ARRAY_SIZE(SPLIT(REPLACE(\"products_industry_code\", ', ', ' -- '), ' -- ')) AS \"INDUSTRY_CODE_LENGTH\",\n  ARRAY_SIZE(SPLIT(REPLACE(\"products_brand_name\", ', ', ' -- '), ' -- ')) AS \"BRAND_NAME_LENGTH\"\nFROM \"FDA\".\"FDA_FOOD\".\"FOOD_EVENTS\"\nWHERE \"date_started\" >= '2015-01-01' AND \"date_started\" < '2015-02-01'\n  AND \"date_created\" >= '2015-01-01' AND \"date_created\" < '2015-02-01'") t = (sql%([FOOD_EVENTS_schema]) "SELECT\n    \"report_number\",\n    SPLIT(\"reactions\", ', ') AS \"REACTIONS\",\n    SPLIT(\"outcomes\", ', ') AS \"OUTCOMES\",\n    REPLACE(\"products_brand_name\", ', ', ' -- ') AS \"PRODUCTS_BRAND_NAME\",\n    REPLACE(\"products_industry_code\", ', ', ' -- ') AS \"PRODUCTS_INDUSTRY_CODE\",\n    REPLACE(\"products_role\", ', ', ' -- ') AS \"PRODUCTS_ROLE\",\n    REPLACE(\"products_industry_name\", ', ', ' -- ') AS \"PRODUCTS_INDUSTRY_NAME\",\n    \"date_created\",\n    \"date_started\",\n    \"consumer_gender\",\n    \"consumer_age\",\n    \"consumer_age_unit\",\n    ARRAY_SIZE(SPLIT(\"products_industry_code\", ', ')) AS \"INDUSTRY_CODE_LENGTH\",\n    ARRAY_SIZE(SPLIT(\"products_brand_name\", ', ')) AS \"BRAND_NAME_LENGTH\"\nFROM \"FDA\".\"FDA_FOOD\".\"FOOD_EVENTS\"\nWHERE \"date_created\" >= '2015-01-01' AND \"date_created\" <= '2015-01-31'\n  AND \"date_started\" >= '2015-01-01' AND \"date_started\" <= '2015-01-31'\nORDER BY \"consumer_age\" ASC NULLS FIRST, \"reactions\" ASC") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp1_2_0 : FOOD_EVENTS "\"date_created\" < '2015-02-01'"
HYPOTHESIS hyp1_2_1 : FOOD_EVENTS "\"date_started\" < '2015-02-01'"
HYPOTHESIS hyp1_2_2 : FOOD_EVENTS "\"date_created\" <= '2015-01-31'"
HYPOTHESIS hyp1_2_3 : FOOD_EVENTS "\"date_started\" <= '2015-01-31'"
HYPOTHESIS hyp1_2_4 : FOOD_EVENTS "\"products_role\" = REPLACE(\"products_role\", ', ', ' -- ')"
HYPOTHESIS hyp1_2_5 : FOOD_EVENTS "\"products_industry_code\" = REPLACE(\"products_industry_code\", ', ', ' -- ')"
theorem eq_1_2 (t : TableRel FOOD_EVENTS_schema) (h0 : hyp1_2_0 t) (h1 : hyp1_2_1 t) (h2 : hyp1_2_2 t) (h3 : hyp1_2_3 t) (h4 : hyp1_2_4 t) (h5 : hyp1_2_5 t) :
    (sql%([FOOD_EVENTS_schema]) "SELECT\n  \"report_number\",\n  SPLIT(\"reactions\", ', ') AS \"REACTIONS\",\n  SPLIT(\"outcomes\", ', ') AS \"OUTCOMES\",\n  REPLACE(\"products_brand_name\", ', ', ' -- ') AS \"PRODUCTS_BRAND_NAME\",\n  \"products_industry_code\" AS \"PRODUCTS_INDUSTRY_CODE\",\n  \"products_role\" AS \"PRODUCTS_ROLE\",\n  REPLACE(\"products_industry_name\", ', ', ' -- ') AS \"PRODUCTS_INDUSTRY_NAME\",\n  \"date_created\",\n  \"date_started\",\n  \"consumer_gender\",\n  \"consumer_age\",\n  \"consumer_age_unit\",\n  ARRAY_SIZE(SPLIT(\"products_industry_code\", ', ')) AS \"INDUSTRY_CODE_LENGTH\",\n  ARRAY_SIZE(SPLIT(\"products_brand_name\", ', ')) AS \"BRAND_NAME_LENGTH\"\nFROM \"FDA\".\"FDA_FOOD\".\"FOOD_EVENTS\"\nWHERE \"date_created\" >= '2015-01-01' AND \"date_created\" < '2015-02-01'\n  AND \"date_started\" >= '2015-01-01' AND \"date_started\" < '2015-02-01'\nORDER BY \"REACTIONS\", \"consumer_age\"") t = (sql%([FOOD_EVENTS_schema]) "SELECT\n  \"report_number\",\n  SPLIT(\"reactions\", ', ') AS \"REACTIONS\",\n  SPLIT(\"outcomes\", ', ') AS \"OUTCOMES\",\n  REPLACE(\"products_brand_name\", ', ', ' -- ') AS \"PRODUCTS_BRAND_NAME\",\n  REPLACE(\"products_industry_code\", ', ', ' -- ') AS \"PRODUCTS_INDUSTRY_CODE\",\n  REPLACE(\"products_role\", ', ', ' -- ') AS \"PRODUCTS_ROLE\",\n  REPLACE(\"products_industry_name\", ', ', ' -- ') AS \"PRODUCTS_INDUSTRY_NAME\",\n  \"date_created\",\n  \"date_started\",\n  \"consumer_gender\",\n  \"consumer_age\",\n  \"consumer_age_unit\",\n  ARRAY_SIZE(SPLIT(\"products_industry_code\", ', ')) AS \"INDUSTRY_CODE_LENGTH\",\n  ARRAY_SIZE(SPLIT(\"products_brand_name\", ', ')) AS \"BRAND_NAME_LENGTH\"\nFROM \"FDA\".\"FDA_FOOD\".\"FOOD_EVENTS\"\nWHERE \"date_created\" >= '2015-01-01'\n  AND \"date_created\" <= '2015-01-31'\n  AND \"date_started\" >= '2015-01-01'\n  AND \"date_started\" <= '2015-01-31';") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp1_3_0 : FOOD_EVENTS "\"date_created\" < '2015-02-01'"
HYPOTHESIS hyp1_3_1 : FOOD_EVENTS "\"date_started\" < '2015-02-01'"
HYPOTHESIS hyp1_3_2 : FOOD_EVENTS "\"date_created\" <= '2015-01-31'"
HYPOTHESIS hyp1_3_3 : FOOD_EVENTS "\"date_started\" <= '2015-01-31'"
HYPOTHESIS hyp1_3_4 : FOOD_EVENTS "\"products_role\" = REPLACE(\"products_role\", ', ', ' -- ')"
HYPOTHESIS hyp1_3_5 : FOOD_EVENTS "\"products_industry_code\" = REPLACE(\"products_industry_code\", ', ', ' -- ')"
theorem eq_1_3 (t : TableRel FOOD_EVENTS_schema) (h0 : hyp1_3_0 t) (h1 : hyp1_3_1 t) (h2 : hyp1_3_2 t) (h3 : hyp1_3_3 t) (h4 : hyp1_3_4 t) (h5 : hyp1_3_5 t) :
    (sql%([FOOD_EVENTS_schema]) "SELECT\n  \"report_number\",\n  SPLIT(\"reactions\", ', ') AS \"REACTIONS\",\n  SPLIT(\"outcomes\", ', ') AS \"OUTCOMES\",\n  REPLACE(\"products_brand_name\", ', ', ' -- ') AS \"PRODUCTS_BRAND_NAME\",\n  \"products_industry_code\" AS \"PRODUCTS_INDUSTRY_CODE\",\n  \"products_role\" AS \"PRODUCTS_ROLE\",\n  REPLACE(\"products_industry_name\", ', ', ' -- ') AS \"PRODUCTS_INDUSTRY_NAME\",\n  \"date_created\",\n  \"date_started\",\n  \"consumer_gender\",\n  \"consumer_age\",\n  \"consumer_age_unit\",\n  ARRAY_SIZE(SPLIT(\"products_industry_code\", ', ')) AS \"INDUSTRY_CODE_LENGTH\",\n  ARRAY_SIZE(SPLIT(\"products_brand_name\", ', ')) AS \"BRAND_NAME_LENGTH\"\nFROM \"FDA\".\"FDA_FOOD\".\"FOOD_EVENTS\"\nWHERE \"date_created\" >= '2015-01-01' AND \"date_created\" < '2015-02-01'\n  AND \"date_started\" >= '2015-01-01' AND \"date_started\" < '2015-02-01'\nORDER BY \"REACTIONS\", \"consumer_age\"") t = (sql%([FOOD_EVENTS_schema]) "SELECT\n    \"report_number\",\n    SPLIT(\"reactions\", ', ') AS \"REACTIONS\",\n    SPLIT(\"outcomes\", ', ') AS \"OUTCOMES\",\n    REPLACE(\"products_brand_name\", ', ', ' -- ') AS \"PRODUCTS_BRAND_NAME\",\n    REPLACE(\"products_industry_code\", ', ', ' -- ') AS \"PRODUCTS_INDUSTRY_CODE\",\n    REPLACE(\"products_role\", ', ', ' -- ') AS \"PRODUCTS_ROLE\",\n    REPLACE(\"products_industry_name\", ', ', ' -- ') AS \"PRODUCTS_INDUSTRY_NAME\",\n    \"date_created\",\n    \"date_started\",\n    \"consumer_gender\",\n    \"consumer_age\",\n    \"consumer_age_unit\",\n    ARRAY_SIZE(SPLIT(\"products_industry_code\", ', ')) AS \"INDUSTRY_CODE_LENGTH\",\n    ARRAY_SIZE(SPLIT(\"products_brand_name\", ', ')) AS \"BRAND_NAME_LENGTH\"\nFROM \"FDA\".\"FDA_FOOD\".\"FOOD_EVENTS\"\nWHERE \"date_created\" >= '2015-01-01' AND \"date_created\" <= '2015-01-31'\n  AND \"date_started\" >= '2015-01-01' AND \"date_started\" <= '2015-01-31'\nORDER BY \"consumer_age\" ASC NULLS FIRST, \"reactions\" ASC") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp2_3_0 : FOOD_EVENTS "\"date_started\" <= '2015-01-31'"
theorem eq_2_3 (t : TableRel FOOD_EVENTS_schema) (h0 : hyp2_3_0 t) :
    (sql%([FOOD_EVENTS_schema]) "SELECT\n  \"report_number\",\n  SPLIT(\"reactions\", ', ') AS \"REACTIONS\",\n  SPLIT(\"outcomes\", ', ') AS \"OUTCOMES\",\n  REPLACE(\"products_brand_name\", ', ', ' -- ') AS \"PRODUCTS_BRAND_NAME\",\n  REPLACE(\"products_industry_code\", ', ', ' -- ') AS \"PRODUCTS_INDUSTRY_CODE\",\n  REPLACE(\"products_role\", ', ', ' -- ') AS \"PRODUCTS_ROLE\",\n  REPLACE(\"products_industry_name\", ', ', ' -- ') AS \"PRODUCTS_INDUSTRY_NAME\",\n  \"date_created\",\n  \"date_started\",\n  \"consumer_gender\",\n  \"consumer_age\",\n  \"consumer_age_unit\",\n  ARRAY_SIZE(SPLIT(\"products_industry_code\", ', ')) AS \"INDUSTRY_CODE_LENGTH\",\n  ARRAY_SIZE(SPLIT(\"products_brand_name\", ', ')) AS \"BRAND_NAME_LENGTH\"\nFROM \"FDA\".\"FDA_FOOD\".\"FOOD_EVENTS\"\nWHERE \"date_created\" >= '2015-01-01'\n  AND \"date_created\" <= '2015-01-31'\n  AND \"date_started\" >= '2015-01-01'\n  AND \"date_started\" <= '2015-01-31';") t = (sql%([FOOD_EVENTS_schema]) "SELECT\n    \"report_number\",\n    SPLIT(\"reactions\", ', ') AS \"REACTIONS\",\n    SPLIT(\"outcomes\", ', ') AS \"OUTCOMES\",\n    REPLACE(\"products_brand_name\", ', ', ' -- ') AS \"PRODUCTS_BRAND_NAME\",\n    REPLACE(\"products_industry_code\", ', ', ' -- ') AS \"PRODUCTS_INDUSTRY_CODE\",\n    REPLACE(\"products_role\", ', ', ' -- ') AS \"PRODUCTS_ROLE\",\n    REPLACE(\"products_industry_name\", ', ', ' -- ') AS \"PRODUCTS_INDUSTRY_NAME\",\n    \"date_created\",\n    \"date_started\",\n    \"consumer_gender\",\n    \"consumer_age\",\n    \"consumer_age_unit\",\n    ARRAY_SIZE(SPLIT(\"products_industry_code\", ', ')) AS \"INDUSTRY_CODE_LENGTH\",\n    ARRAY_SIZE(SPLIT(\"products_brand_name\", ', ')) AS \"BRAND_NAME_LENGTH\"\nFROM \"FDA\".\"FDA_FOOD\".\"FOOD_EVENTS\"\nWHERE \"date_created\" >= '2015-01-01' AND \"date_created\" <= '2015-01-31'\n  AND \"date_started\" >= '2015-01-01' AND \"date_started\" <= '2015-01-31'\nORDER BY \"consumer_age\" ASC NULLS FIRST, \"reactions\" ASC") t := by
  first | sql_equiv | sorry

end Bench_sf_bq432
