import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_local230 — crossskill equivalence(s)

Question: Determine the top three genres with the most movies rated above 8, and then identify the top four directors who have directed the most films rated above 8 within those genres. List these directors and their respective movie counts.

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_local230

CREATE TABLE GENRE («movie_id» STRING, «genre» STRING)
CREATE TABLE MOVIES («id» STRING, «title» STRING, «year» INT, «date_published» STRING, «duration» INT, «country» STRING, «worlwide_gross_income» STRING, «languages» STRING, «production_company» STRING)
CREATE TABLE DIRECTOR_MAPPING («movie_id» STRING, «name_id» STRING)
CREATE TABLE NAMES («id» STRING, «name» STRING, «height» FLOAT, «date_of_birth» STRING, «known_for_movies» STRING)
CREATE TABLE RATINGS («movie_id» STRING, «avg_rating» FLOAT, «total_votes» INT, «median_rating» FLOAT)

theorem eq_0_1 : ∀ t,
    (sql%([GENRE_schema, MOVIES_schema, DIRECTOR_MAPPING_schema, NAMES_schema, RATINGS_schema]) "WITH top_genres AS (\n    SELECT g.\"genre\", COUNT(DISTINCT g.\"movie_id\") AS movie_count\n    FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" g\n    JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" r ON g.\"movie_id\" = r.\"movie_id\"\n    WHERE r.\"avg_rating\" > 8\n    GROUP BY g.\"genre\"\n    ORDER BY movie_count DESC\n    LIMIT 3\n),\ndirector_movies AS (\n    SELECT n.\"name\" AS DIRECTOR, COUNT(DISTINCT dm.\"movie_id\") AS MOVIE_COUNT\n    FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"DIRECTOR_MAPPING\" dm\n    JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"NAMES\" n ON dm.\"name_id\" = n.\"id\"\n    JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" g ON dm.\"movie_id\" = g.\"movie_id\"\n    JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" r ON dm.\"movie_id\" = r.\"movie_id\"\n    WHERE r.\"avg_rating\" > 8\n      AND g.\"genre\" IN (SELECT \"genre\" FROM top_genres)\n    GROUP BY n.\"name\"\n    ORDER BY MOVIE_COUNT DESC, DIRECTOR ASC\n    LIMIT 4\n)\nSELECT DIRECTOR, MOVIE_COUNT\nFROM director_movies\nORDER BY DIRECTOR ASC;") t ~= (sql%([GENRE_schema, MOVIES_schema, DIRECTOR_MAPPING_schema, NAMES_schema, RATINGS_schema]) "WITH top_genres AS (\n    SELECT g.\"genre\", COUNT(DISTINCT g.\"movie_id\") AS cnt\n    FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" g\n    JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" r ON g.\"movie_id\" = r.\"movie_id\"\n    WHERE r.\"avg_rating\" > 8\n    GROUP BY g.\"genre\"\n    ORDER BY cnt DESC\n    LIMIT 3\n),\nqualified_movies AS (\n    SELECT DISTINCT g.\"movie_id\"\n    FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" g\n    JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" r ON g.\"movie_id\" = r.\"movie_id\"\n    JOIN top_genres tg ON g.\"genre\" = tg.\"genre\"\n    WHERE r.\"avg_rating\" > 8\n)\nSELECT \n    n.\"name\" AS DIRECTOR, \n    COUNT(DISTINCT dm.\"movie_id\") AS MOVIE_COUNT\nFROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"DIRECTOR_MAPPING\" dm\nJOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"NAMES\" n ON dm.\"name_id\" = n.\"id\"\nJOIN qualified_movies qm ON dm.\"movie_id\" = qm.\"movie_id\"\nGROUP BY n.\"name\"\nORDER BY MOVIE_COUNT DESC, DIRECTOR ASC\nLIMIT 4;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_0_2 : ∀ t,
    (sql%([GENRE_schema, MOVIES_schema, DIRECTOR_MAPPING_schema, NAMES_schema, RATINGS_schema]) "WITH top_genres AS (\n    SELECT g.\"genre\", COUNT(DISTINCT g.\"movie_id\") AS movie_count\n    FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" g\n    JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" r ON g.\"movie_id\" = r.\"movie_id\"\n    WHERE r.\"avg_rating\" > 8\n    GROUP BY g.\"genre\"\n    ORDER BY movie_count DESC\n    LIMIT 3\n),\ndirector_movies AS (\n    SELECT n.\"name\" AS DIRECTOR, COUNT(DISTINCT dm.\"movie_id\") AS MOVIE_COUNT\n    FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"DIRECTOR_MAPPING\" dm\n    JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"NAMES\" n ON dm.\"name_id\" = n.\"id\"\n    JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" g ON dm.\"movie_id\" = g.\"movie_id\"\n    JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" r ON dm.\"movie_id\" = r.\"movie_id\"\n    WHERE r.\"avg_rating\" > 8\n      AND g.\"genre\" IN (SELECT \"genre\" FROM top_genres)\n    GROUP BY n.\"name\"\n    ORDER BY MOVIE_COUNT DESC, DIRECTOR ASC\n    LIMIT 4\n)\nSELECT DIRECTOR, MOVIE_COUNT\nFROM director_movies\nORDER BY DIRECTOR ASC;") t ~= (sql%([GENRE_schema, MOVIES_schema, DIRECTOR_MAPPING_schema, NAMES_schema, RATINGS_schema]) "-- Step 1: Find the top 3 genres with the most movies rated above 8\n-- Step 2: Among movies in those genres rated above 8, find top 4 directors by movie count\n\nWITH top_genres AS (\n    SELECT g.\"genre\"\n    FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" g\n    JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" r\n        ON g.\"movie_id\" = r.\"movie_id\"\n    WHERE r.\"avg_rating\" > 8\n    GROUP BY g.\"genre\"\n    ORDER BY COUNT(DISTINCT g.\"movie_id\") DESC\n    LIMIT 3\n)\nSELECT\n    n.\"name\" AS \"DIRECTOR\",\n    COUNT(DISTINCT g.\"movie_id\") AS \"MOVIE_COUNT\"\nFROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" g\nJOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" r\n    ON g.\"movie_id\" = r.\"movie_id\"\nJOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"DIRECTOR_MAPPING\" dm\n    ON g.\"movie_id\" = dm.\"movie_id\"\nJOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"NAMES\" n\n    ON dm.\"name_id\" = n.\"id\"\nWHERE r.\"avg_rating\" > 8\n  AND g.\"genre\" IN (SELECT \"genre\" FROM top_genres)\nGROUP BY n.\"name\"\nORDER BY \"MOVIE_COUNT\" DESC, n.\"name\" ASC\nLIMIT 4;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_0_3 : ∀ t,
    (sql%([GENRE_schema, MOVIES_schema, DIRECTOR_MAPPING_schema, NAMES_schema, RATINGS_schema]) "WITH top_genres AS (\n    SELECT g.\"genre\", COUNT(DISTINCT g.\"movie_id\") AS movie_count\n    FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" g\n    JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" r ON g.\"movie_id\" = r.\"movie_id\"\n    WHERE r.\"avg_rating\" > 8\n    GROUP BY g.\"genre\"\n    ORDER BY movie_count DESC\n    LIMIT 3\n),\ndirector_movies AS (\n    SELECT n.\"name\" AS DIRECTOR, COUNT(DISTINCT dm.\"movie_id\") AS MOVIE_COUNT\n    FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"DIRECTOR_MAPPING\" dm\n    JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"NAMES\" n ON dm.\"name_id\" = n.\"id\"\n    JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" g ON dm.\"movie_id\" = g.\"movie_id\"\n    JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" r ON dm.\"movie_id\" = r.\"movie_id\"\n    WHERE r.\"avg_rating\" > 8\n      AND g.\"genre\" IN (SELECT \"genre\" FROM top_genres)\n    GROUP BY n.\"name\"\n    ORDER BY MOVIE_COUNT DESC, DIRECTOR ASC\n    LIMIT 4\n)\nSELECT DIRECTOR, MOVIE_COUNT\nFROM director_movies\nORDER BY DIRECTOR ASC;") t ~= (sql%([GENRE_schema, MOVIES_schema, DIRECTOR_MAPPING_schema, NAMES_schema, RATINGS_schema]) "WITH top_genres AS (\n    SELECT g.\"genre\"\n    FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" g\n    JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" r\n        ON g.\"movie_id\" = r.\"movie_id\"\n    WHERE r.\"avg_rating\" > 8\n    GROUP BY g.\"genre\"\n    ORDER BY COUNT(*) DESC\n    LIMIT 3\n),\nmovies_in_top_genres AS (\n    SELECT DISTINCT g.\"movie_id\"\n    FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" g\n    JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" r\n        ON g.\"movie_id\" = r.\"movie_id\"\n    WHERE r.\"avg_rating\" > 8\n      AND g.\"genre\" IN (SELECT \"genre\" FROM top_genres)\n)\nSELECT n.\"name\" AS DIRECTOR,\n       COUNT(DISTINCT dm.\"movie_id\") AS MOVIE_COUNT\nFROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"DIRECTOR_MAPPING\" dm\nJOIN movies_in_top_genres m\n    ON dm.\"movie_id\" = m.\"movie_id\"\nJOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"NAMES\" n\n    ON dm.\"name_id\" = n.\"id\"\nGROUP BY n.\"name\"\nORDER BY MOVIE_COUNT DESC, n.\"name\" ASC\nLIMIT 4;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_1_2 : ∀ t,
    (sql%([GENRE_schema, MOVIES_schema, DIRECTOR_MAPPING_schema, NAMES_schema, RATINGS_schema]) "WITH top_genres AS (\n    SELECT g.\"genre\", COUNT(DISTINCT g.\"movie_id\") AS cnt\n    FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" g\n    JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" r ON g.\"movie_id\" = r.\"movie_id\"\n    WHERE r.\"avg_rating\" > 8\n    GROUP BY g.\"genre\"\n    ORDER BY cnt DESC\n    LIMIT 3\n),\nqualified_movies AS (\n    SELECT DISTINCT g.\"movie_id\"\n    FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" g\n    JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" r ON g.\"movie_id\" = r.\"movie_id\"\n    JOIN top_genres tg ON g.\"genre\" = tg.\"genre\"\n    WHERE r.\"avg_rating\" > 8\n)\nSELECT \n    n.\"name\" AS DIRECTOR, \n    COUNT(DISTINCT dm.\"movie_id\") AS MOVIE_COUNT\nFROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"DIRECTOR_MAPPING\" dm\nJOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"NAMES\" n ON dm.\"name_id\" = n.\"id\"\nJOIN qualified_movies qm ON dm.\"movie_id\" = qm.\"movie_id\"\nGROUP BY n.\"name\"\nORDER BY MOVIE_COUNT DESC, DIRECTOR ASC\nLIMIT 4;") t ~= (sql%([GENRE_schema, MOVIES_schema, DIRECTOR_MAPPING_schema, NAMES_schema, RATINGS_schema]) "-- Step 1: Find the top 3 genres with the most movies rated above 8\n-- Step 2: Among movies in those genres rated above 8, find top 4 directors by movie count\n\nWITH top_genres AS (\n    SELECT g.\"genre\"\n    FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" g\n    JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" r\n        ON g.\"movie_id\" = r.\"movie_id\"\n    WHERE r.\"avg_rating\" > 8\n    GROUP BY g.\"genre\"\n    ORDER BY COUNT(DISTINCT g.\"movie_id\") DESC\n    LIMIT 3\n)\nSELECT\n    n.\"name\" AS \"DIRECTOR\",\n    COUNT(DISTINCT g.\"movie_id\") AS \"MOVIE_COUNT\"\nFROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" g\nJOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" r\n    ON g.\"movie_id\" = r.\"movie_id\"\nJOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"DIRECTOR_MAPPING\" dm\n    ON g.\"movie_id\" = dm.\"movie_id\"\nJOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"NAMES\" n\n    ON dm.\"name_id\" = n.\"id\"\nWHERE r.\"avg_rating\" > 8\n  AND g.\"genre\" IN (SELECT \"genre\" FROM top_genres)\nGROUP BY n.\"name\"\nORDER BY \"MOVIE_COUNT\" DESC, n.\"name\" ASC\nLIMIT 4;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_1_3 : ∀ t,
    (sql%([GENRE_schema, MOVIES_schema, DIRECTOR_MAPPING_schema, NAMES_schema, RATINGS_schema]) "WITH top_genres AS (\n    SELECT g.\"genre\", COUNT(DISTINCT g.\"movie_id\") AS cnt\n    FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" g\n    JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" r ON g.\"movie_id\" = r.\"movie_id\"\n    WHERE r.\"avg_rating\" > 8\n    GROUP BY g.\"genre\"\n    ORDER BY cnt DESC\n    LIMIT 3\n),\nqualified_movies AS (\n    SELECT DISTINCT g.\"movie_id\"\n    FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" g\n    JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" r ON g.\"movie_id\" = r.\"movie_id\"\n    JOIN top_genres tg ON g.\"genre\" = tg.\"genre\"\n    WHERE r.\"avg_rating\" > 8\n)\nSELECT \n    n.\"name\" AS DIRECTOR, \n    COUNT(DISTINCT dm.\"movie_id\") AS MOVIE_COUNT\nFROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"DIRECTOR_MAPPING\" dm\nJOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"NAMES\" n ON dm.\"name_id\" = n.\"id\"\nJOIN qualified_movies qm ON dm.\"movie_id\" = qm.\"movie_id\"\nGROUP BY n.\"name\"\nORDER BY MOVIE_COUNT DESC, DIRECTOR ASC\nLIMIT 4;") t ~= (sql%([GENRE_schema, MOVIES_schema, DIRECTOR_MAPPING_schema, NAMES_schema, RATINGS_schema]) "WITH top_genres AS (\n    SELECT g.\"genre\"\n    FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" g\n    JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" r\n        ON g.\"movie_id\" = r.\"movie_id\"\n    WHERE r.\"avg_rating\" > 8\n    GROUP BY g.\"genre\"\n    ORDER BY COUNT(*) DESC\n    LIMIT 3\n),\nmovies_in_top_genres AS (\n    SELECT DISTINCT g.\"movie_id\"\n    FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" g\n    JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" r\n        ON g.\"movie_id\" = r.\"movie_id\"\n    WHERE r.\"avg_rating\" > 8\n      AND g.\"genre\" IN (SELECT \"genre\" FROM top_genres)\n)\nSELECT n.\"name\" AS DIRECTOR,\n       COUNT(DISTINCT dm.\"movie_id\") AS MOVIE_COUNT\nFROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"DIRECTOR_MAPPING\" dm\nJOIN movies_in_top_genres m\n    ON dm.\"movie_id\" = m.\"movie_id\"\nJOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"NAMES\" n\n    ON dm.\"name_id\" = n.\"id\"\nGROUP BY n.\"name\"\nORDER BY MOVIE_COUNT DESC, n.\"name\" ASC\nLIMIT 4;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_2_3 :
    sql%([GENRE_schema, MOVIES_schema, DIRECTOR_MAPPING_schema, NAMES_schema, RATINGS_schema]) "-- Step 1: Find the top 3 genres with the most movies rated above 8\n-- Step 2: Among movies in those genres rated above 8, find top 4 directors by movie count\n\nWITH top_genres AS (\n    SELECT g.\"genre\"\n    FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" g\n    JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" r\n        ON g.\"movie_id\" = r.\"movie_id\"\n    WHERE r.\"avg_rating\" > 8\n    GROUP BY g.\"genre\"\n    ORDER BY COUNT(DISTINCT g.\"movie_id\") DESC\n    LIMIT 3\n)\nSELECT\n    n.\"name\" AS \"DIRECTOR\",\n    COUNT(DISTINCT g.\"movie_id\") AS \"MOVIE_COUNT\"\nFROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" g\nJOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" r\n    ON g.\"movie_id\" = r.\"movie_id\"\nJOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"DIRECTOR_MAPPING\" dm\n    ON g.\"movie_id\" = dm.\"movie_id\"\nJOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"NAMES\" n\n    ON dm.\"name_id\" = n.\"id\"\nWHERE r.\"avg_rating\" > 8\n  AND g.\"genre\" IN (SELECT \"genre\" FROM top_genres)\nGROUP BY n.\"name\"\nORDER BY \"MOVIE_COUNT\" DESC, n.\"name\" ASC\nLIMIT 4;" = sql%([GENRE_schema, MOVIES_schema, DIRECTOR_MAPPING_schema, NAMES_schema, RATINGS_schema]) "WITH top_genres AS (\n    SELECT g.\"genre\"\n    FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" g\n    JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" r\n        ON g.\"movie_id\" = r.\"movie_id\"\n    WHERE r.\"avg_rating\" > 8\n    GROUP BY g.\"genre\"\n    ORDER BY COUNT(*) DESC\n    LIMIT 3\n),\nmovies_in_top_genres AS (\n    SELECT DISTINCT g.\"movie_id\"\n    FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" g\n    JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" r\n        ON g.\"movie_id\" = r.\"movie_id\"\n    WHERE r.\"avg_rating\" > 8\n      AND g.\"genre\" IN (SELECT \"genre\" FROM top_genres)\n)\nSELECT n.\"name\" AS DIRECTOR,\n       COUNT(DISTINCT dm.\"movie_id\") AS MOVIE_COUNT\nFROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"DIRECTOR_MAPPING\" dm\nJOIN movies_in_top_genres m\n    ON dm.\"movie_id\" = m.\"movie_id\"\nJOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"NAMES\" n\n    ON dm.\"name_id\" = n.\"id\"\nGROUP BY n.\"name\"\nORDER BY MOVIE_COUNT DESC, n.\"name\" ASC\nLIMIT 4;" := by
  first | sql_equiv | sorry

end Bench_sf_local230
