import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_local096 — crossskill equivalence(s)

Question: For each year, calculate the percentage of films that had exclusively female actors (meaning no male actors and no actors with unknown/unspecified gender). Consider actors with gender marked as 'Male' or 'None' as non-female. For the results, display the year, the total number of movies in that year, and the percentage of movies with exclusively female actors. Extract the year from the Movie.year field by taking the last 4 characters and converting to a number.

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_local096

CREATE TABLE MOVIE («index» INT, «MID» STRING, «title» STRING, «year» STRING, «rating» FLOAT, «num_votes» INT)
CREATE TABLE PERSON («index» INT, «PID» STRING, «Name» STRING, «Gender» STRING)
CREATE TABLE M_CAST («index» INT, «MID» STRING, «PID» STRING, «ID» INT)

theorem eq_0_1 :
    sql%([MOVIE_schema, PERSON_schema, M_CAST_schema]) "WITH movie_years AS (SELECT \"MID\", CAST(RIGHT(\"year\", 4) AS DOUBLE PRECISION) AS year FROM \"DB_IMDB\".\"DB_IMDB\".\"MOVIE\"), exclusively_female AS (SELECT mc.\"MID\" FROM \"DB_IMDB\".\"DB_IMDB\".\"M_CAST\" AS mc JOIN \"DB_IMDB\".\"DB_IMDB\".\"PERSON\" AS p ON TRIM(mc.\"PID\") = TRIM(p.\"PID\") GROUP BY mc.\"MID\" HAVING SUM(CASE WHEN p.\"Gender\" <> 'Female' THEN 1 ELSE 0 END) = 0) SELECT my.year AS YEAR, COUNT(DISTINCT my.\"MID\") AS TOTAL_MOVIES, ROUND(CAST(CAST(COUNT(DISTINCT ef.\"MID\") * 100.0 AS DOUBLE PRECISION) / COUNT(DISTINCT my.\"MID\") AS DECIMAL), 2) AS PERCENTAGE_EXCLUSIVELY_FEMALE FROM movie_years AS my LEFT JOIN exclusively_female AS ef ON my.\"MID\" = ef.\"MID\" GROUP BY my.year ORDER BY my.year" = sql%([MOVIE_schema, PERSON_schema, M_CAST_schema]) "WITH movie_years AS (SELECT m.\"MID\", CAST(RIGHT(m.\"year\", 4) AS DOUBLE PRECISION) AS \"YEAR\" FROM \"DB_IMDB\".\"DB_IMDB\".\"MOVIE\" AS m WHERE NOT CAST(RIGHT(m.\"year\", 4) AS DOUBLE PRECISION) IS NULL), exclusively_female AS (SELECT my.\"MID\" FROM movie_years AS my WHERE NOT EXISTS(SELECT 1 FROM \"DB_IMDB\".\"DB_IMDB\".\"M_CAST\" AS c JOIN \"DB_IMDB\".\"DB_IMDB\".\"PERSON\" AS p ON TRIM(c.\"PID\") = p.\"PID\" WHERE c.\"MID\" = my.\"MID\" AND p.\"Gender\" <> 'Female')) SELECT my.\"YEAR\", COUNT(*) AS \"TOTAL_MOVIES\", ROUND(CAST(CAST(100.0 * SUM(CASE WHEN NOT ef.\"MID\" IS NULL THEN 1 ELSE 0 END) AS DOUBLE PRECISION) / COUNT(*) AS DECIMAL), 2) AS \"PERCENTAGE_EXCLUSIVELY_FEMALE\" FROM movie_years AS my LEFT JOIN exclusively_female AS ef ON my.\"MID\" = ef.\"MID\" GROUP BY my.\"YEAR\" ORDER BY my.\"YEAR\"" := by
  first | sql_equiv | sorry

-- eq_0_2: needs a data hypothesis over multiple tables (not stated); likely `sorry`.
theorem eq_0_2 :
    sql%([MOVIE_schema, PERSON_schema, M_CAST_schema]) "WITH movie_years AS (SELECT \"MID\", CAST(RIGHT(\"year\", 4) AS DOUBLE PRECISION) AS year FROM \"DB_IMDB\".\"DB_IMDB\".\"MOVIE\"), exclusively_female AS (SELECT mc.\"MID\" FROM \"DB_IMDB\".\"DB_IMDB\".\"M_CAST\" AS mc JOIN \"DB_IMDB\".\"DB_IMDB\".\"PERSON\" AS p ON TRIM(mc.\"PID\") = TRIM(p.\"PID\") GROUP BY mc.\"MID\" HAVING SUM(CASE WHEN p.\"Gender\" <> 'Female' THEN 1 ELSE 0 END) = 0) SELECT my.year AS YEAR, COUNT(DISTINCT my.\"MID\") AS TOTAL_MOVIES, ROUND(CAST(CAST(COUNT(DISTINCT ef.\"MID\") * 100.0 AS DOUBLE PRECISION) / COUNT(DISTINCT my.\"MID\") AS DECIMAL), 2) AS PERCENTAGE_EXCLUSIVELY_FEMALE FROM movie_years AS my LEFT JOIN exclusively_female AS ef ON my.\"MID\" = ef.\"MID\" GROUP BY my.year ORDER BY my.year" = sql%([MOVIE_schema, PERSON_schema, M_CAST_schema]) "WITH movie_year AS (SELECT \"MID\", CAST(RIGHT(\"year\", 4) AS INT) AS \"YEAR\" FROM \"DB_IMDB\".\"DB_IMDB\".\"MOVIE\"), movie_cast_gender AS (SELECT mc.\"MID\", p.\"Gender\" FROM \"DB_IMDB\".\"DB_IMDB\".\"M_CAST\" AS mc JOIN \"DB_IMDB\".\"DB_IMDB\".\"PERSON\" AS p ON TRIM(mc.\"PID\") = TRIM(p.\"PID\")), exclusively_female AS (SELECT \"MID\" FROM movie_cast_gender GROUP BY \"MID\" HAVING SUM(CASE WHEN \"Gender\" <> 'Female' THEN 1 ELSE 0 END) = 0), yearly_stats AS (SELECT my.\"YEAR\", COUNT(DISTINCT my.\"MID\") AS \"TOTAL_MOVIES\", COUNT(DISTINCT ef.\"MID\") AS female_only_count FROM movie_year AS my LEFT JOIN exclusively_female AS ef ON my.\"MID\" = ef.\"MID\" GROUP BY my.\"YEAR\") SELECT \"YEAR\", \"TOTAL_MOVIES\", ROUND(CAST(female_only_count * 100.0 AS DOUBLE PRECISION) / \"TOTAL_MOVIES\", 2) AS \"PERCENTAGE_EXCLUSIVELY_FEMALE\" FROM yearly_stats ORDER BY \"YEAR\"" := by
  first | sql_equiv | sorry

-- eq_0_3: needs a data hypothesis over multiple tables (not stated); likely `sorry`.
theorem eq_0_3 : ∀ t,
    (sql%([MOVIE_schema, PERSON_schema, M_CAST_schema]) "WITH movie_years AS (SELECT \"MID\", CAST(RIGHT(\"year\", 4) AS DOUBLE PRECISION) AS year FROM \"DB_IMDB\".\"DB_IMDB\".\"MOVIE\"), exclusively_female AS (SELECT mc.\"MID\" FROM \"DB_IMDB\".\"DB_IMDB\".\"M_CAST\" AS mc JOIN \"DB_IMDB\".\"DB_IMDB\".\"PERSON\" AS p ON TRIM(mc.\"PID\") = TRIM(p.\"PID\") GROUP BY mc.\"MID\" HAVING SUM(CASE WHEN p.\"Gender\" <> 'Female' THEN 1 ELSE 0 END) = 0) SELECT my.year AS YEAR, COUNT(DISTINCT my.\"MID\") AS TOTAL_MOVIES, ROUND(CAST(CAST(COUNT(DISTINCT ef.\"MID\") * 100.0 AS DOUBLE PRECISION) / COUNT(DISTINCT my.\"MID\") AS DECIMAL), 2) AS PERCENTAGE_EXCLUSIVELY_FEMALE FROM movie_years AS my LEFT JOIN exclusively_female AS ef ON my.\"MID\" = ef.\"MID\" GROUP BY my.year ORDER BY my.year") t ~= (sql%([MOVIE_schema, PERSON_schema, M_CAST_schema]) "WITH movie_years AS (SELECT \"MID\", \"title\", CAST(RIGHT(\"year\", 4) AS INT) AS \"YEAR\" FROM \"DB_IMDB\".\"DB_IMDB\".\"MOVIE\"), movie_cast_gender AS (SELECT mc.\"MID\", p.\"Gender\" FROM \"DB_IMDB\".\"DB_IMDB\".\"M_CAST\" AS mc JOIN \"DB_IMDB\".\"DB_IMDB\".\"PERSON\" AS p ON TRIM(mc.\"PID\") = TRIM(p.\"PID\")), exclusively_female AS (SELECT my.\"MID\", my.\"YEAR\", CASE WHEN COUNT(mcg.\"Gender\") > 0 AND SUM(CASE WHEN mcg.\"Gender\" <> 'Female' THEN 1 ELSE 0 END) = 0 THEN 1 ELSE 0 END AS is_exclusively_female FROM movie_years AS my LEFT JOIN movie_cast_gender AS mcg ON my.\"MID\" = mcg.\"MID\" GROUP BY my.\"MID\", my.\"YEAR\") SELECT \"YEAR\", COUNT(*) AS \"TOTAL_MOVIES\", ROUND(CAST(CAST(100.0 * SUM(is_exclusively_female) AS DOUBLE PRECISION) / COUNT(*) AS DECIMAL), 2) AS \"PERCENTAGE_EXCLUSIVELY_FEMALE\" FROM exclusively_female GROUP BY \"YEAR\" ORDER BY \"YEAR\"") t := by
  intro t; first | sql_equiv | sorry

-- eq_1_2: needs a data hypothesis over multiple tables (not stated); likely `sorry`.
theorem eq_1_2 :
    sql%([MOVIE_schema, PERSON_schema, M_CAST_schema]) "WITH movie_years AS (SELECT m.\"MID\", CAST(RIGHT(m.\"year\", 4) AS DOUBLE PRECISION) AS \"YEAR\" FROM \"DB_IMDB\".\"DB_IMDB\".\"MOVIE\" AS m WHERE NOT CAST(RIGHT(m.\"year\", 4) AS DOUBLE PRECISION) IS NULL), exclusively_female AS (SELECT my.\"MID\" FROM movie_years AS my WHERE NOT EXISTS(SELECT 1 FROM \"DB_IMDB\".\"DB_IMDB\".\"M_CAST\" AS c JOIN \"DB_IMDB\".\"DB_IMDB\".\"PERSON\" AS p ON TRIM(c.\"PID\") = p.\"PID\" WHERE c.\"MID\" = my.\"MID\" AND p.\"Gender\" <> 'Female')) SELECT my.\"YEAR\", COUNT(*) AS \"TOTAL_MOVIES\", ROUND(CAST(CAST(100.0 * SUM(CASE WHEN NOT ef.\"MID\" IS NULL THEN 1 ELSE 0 END) AS DOUBLE PRECISION) / COUNT(*) AS DECIMAL), 2) AS \"PERCENTAGE_EXCLUSIVELY_FEMALE\" FROM movie_years AS my LEFT JOIN exclusively_female AS ef ON my.\"MID\" = ef.\"MID\" GROUP BY my.\"YEAR\" ORDER BY my.\"YEAR\"" = sql%([MOVIE_schema, PERSON_schema, M_CAST_schema]) "WITH movie_year AS (SELECT \"MID\", CAST(RIGHT(\"year\", 4) AS INT) AS \"YEAR\" FROM \"DB_IMDB\".\"DB_IMDB\".\"MOVIE\"), movie_cast_gender AS (SELECT mc.\"MID\", p.\"Gender\" FROM \"DB_IMDB\".\"DB_IMDB\".\"M_CAST\" AS mc JOIN \"DB_IMDB\".\"DB_IMDB\".\"PERSON\" AS p ON TRIM(mc.\"PID\") = TRIM(p.\"PID\")), exclusively_female AS (SELECT \"MID\" FROM movie_cast_gender GROUP BY \"MID\" HAVING SUM(CASE WHEN \"Gender\" <> 'Female' THEN 1 ELSE 0 END) = 0), yearly_stats AS (SELECT my.\"YEAR\", COUNT(DISTINCT my.\"MID\") AS \"TOTAL_MOVIES\", COUNT(DISTINCT ef.\"MID\") AS female_only_count FROM movie_year AS my LEFT JOIN exclusively_female AS ef ON my.\"MID\" = ef.\"MID\" GROUP BY my.\"YEAR\") SELECT \"YEAR\", \"TOTAL_MOVIES\", ROUND(CAST(female_only_count * 100.0 AS DOUBLE PRECISION) / \"TOTAL_MOVIES\", 2) AS \"PERCENTAGE_EXCLUSIVELY_FEMALE\" FROM yearly_stats ORDER BY \"YEAR\"" := by
  first | sql_equiv | sorry

-- eq_1_3: needs a data hypothesis over multiple tables (not stated); likely `sorry`.
theorem eq_1_3 : ∀ t,
    (sql%([MOVIE_schema, PERSON_schema, M_CAST_schema]) "WITH movie_years AS (SELECT m.\"MID\", CAST(RIGHT(m.\"year\", 4) AS DOUBLE PRECISION) AS \"YEAR\" FROM \"DB_IMDB\".\"DB_IMDB\".\"MOVIE\" AS m WHERE NOT CAST(RIGHT(m.\"year\", 4) AS DOUBLE PRECISION) IS NULL), exclusively_female AS (SELECT my.\"MID\" FROM movie_years AS my WHERE NOT EXISTS(SELECT 1 FROM \"DB_IMDB\".\"DB_IMDB\".\"M_CAST\" AS c JOIN \"DB_IMDB\".\"DB_IMDB\".\"PERSON\" AS p ON TRIM(c.\"PID\") = p.\"PID\" WHERE c.\"MID\" = my.\"MID\" AND p.\"Gender\" <> 'Female')) SELECT my.\"YEAR\", COUNT(*) AS \"TOTAL_MOVIES\", ROUND(CAST(CAST(100.0 * SUM(CASE WHEN NOT ef.\"MID\" IS NULL THEN 1 ELSE 0 END) AS DOUBLE PRECISION) / COUNT(*) AS DECIMAL), 2) AS \"PERCENTAGE_EXCLUSIVELY_FEMALE\" FROM movie_years AS my LEFT JOIN exclusively_female AS ef ON my.\"MID\" = ef.\"MID\" GROUP BY my.\"YEAR\" ORDER BY my.\"YEAR\"") t ~= (sql%([MOVIE_schema, PERSON_schema, M_CAST_schema]) "WITH movie_years AS (SELECT \"MID\", \"title\", CAST(RIGHT(\"year\", 4) AS INT) AS \"YEAR\" FROM \"DB_IMDB\".\"DB_IMDB\".\"MOVIE\"), movie_cast_gender AS (SELECT mc.\"MID\", p.\"Gender\" FROM \"DB_IMDB\".\"DB_IMDB\".\"M_CAST\" AS mc JOIN \"DB_IMDB\".\"DB_IMDB\".\"PERSON\" AS p ON TRIM(mc.\"PID\") = TRIM(p.\"PID\")), exclusively_female AS (SELECT my.\"MID\", my.\"YEAR\", CASE WHEN COUNT(mcg.\"Gender\") > 0 AND SUM(CASE WHEN mcg.\"Gender\" <> 'Female' THEN 1 ELSE 0 END) = 0 THEN 1 ELSE 0 END AS is_exclusively_female FROM movie_years AS my LEFT JOIN movie_cast_gender AS mcg ON my.\"MID\" = mcg.\"MID\" GROUP BY my.\"MID\", my.\"YEAR\") SELECT \"YEAR\", COUNT(*) AS \"TOTAL_MOVIES\", ROUND(CAST(CAST(100.0 * SUM(is_exclusively_female) AS DOUBLE PRECISION) / COUNT(*) AS DECIMAL), 2) AS \"PERCENTAGE_EXCLUSIVELY_FEMALE\" FROM exclusively_female GROUP BY \"YEAR\" ORDER BY \"YEAR\"") t := by
  intro t; first | sql_equiv | sorry

theorem eq_2_3 : ∀ t,
    (sql%([MOVIE_schema, PERSON_schema, M_CAST_schema]) "WITH movie_year AS (SELECT \"MID\", CAST(RIGHT(\"year\", 4) AS INT) AS \"YEAR\" FROM \"DB_IMDB\".\"DB_IMDB\".\"MOVIE\"), movie_cast_gender AS (SELECT mc.\"MID\", p.\"Gender\" FROM \"DB_IMDB\".\"DB_IMDB\".\"M_CAST\" AS mc JOIN \"DB_IMDB\".\"DB_IMDB\".\"PERSON\" AS p ON TRIM(mc.\"PID\") = TRIM(p.\"PID\")), exclusively_female AS (SELECT \"MID\" FROM movie_cast_gender GROUP BY \"MID\" HAVING SUM(CASE WHEN \"Gender\" <> 'Female' THEN 1 ELSE 0 END) = 0), yearly_stats AS (SELECT my.\"YEAR\", COUNT(DISTINCT my.\"MID\") AS \"TOTAL_MOVIES\", COUNT(DISTINCT ef.\"MID\") AS female_only_count FROM movie_year AS my LEFT JOIN exclusively_female AS ef ON my.\"MID\" = ef.\"MID\" GROUP BY my.\"YEAR\") SELECT \"YEAR\", \"TOTAL_MOVIES\", ROUND(CAST(female_only_count * 100.0 AS DOUBLE PRECISION) / \"TOTAL_MOVIES\", 2) AS \"PERCENTAGE_EXCLUSIVELY_FEMALE\" FROM yearly_stats ORDER BY \"YEAR\"") t ~= (sql%([MOVIE_schema, PERSON_schema, M_CAST_schema]) "WITH movie_years AS (SELECT \"MID\", \"title\", CAST(RIGHT(\"year\", 4) AS INT) AS \"YEAR\" FROM \"DB_IMDB\".\"DB_IMDB\".\"MOVIE\"), movie_cast_gender AS (SELECT mc.\"MID\", p.\"Gender\" FROM \"DB_IMDB\".\"DB_IMDB\".\"M_CAST\" AS mc JOIN \"DB_IMDB\".\"DB_IMDB\".\"PERSON\" AS p ON TRIM(mc.\"PID\") = TRIM(p.\"PID\")), exclusively_female AS (SELECT my.\"MID\", my.\"YEAR\", CASE WHEN COUNT(mcg.\"Gender\") > 0 AND SUM(CASE WHEN mcg.\"Gender\" <> 'Female' THEN 1 ELSE 0 END) = 0 THEN 1 ELSE 0 END AS is_exclusively_female FROM movie_years AS my LEFT JOIN movie_cast_gender AS mcg ON my.\"MID\" = mcg.\"MID\" GROUP BY my.\"MID\", my.\"YEAR\") SELECT \"YEAR\", COUNT(*) AS \"TOTAL_MOVIES\", ROUND(CAST(CAST(100.0 * SUM(is_exclusively_female) AS DOUBLE PRECISION) / COUNT(*) AS DECIMAL), 2) AS \"PERCENTAGE_EXCLUSIVELY_FEMALE\" FROM exclusively_female GROUP BY \"YEAR\" ORDER BY \"YEAR\"") t := by
  intro t; first | sql_equiv | sorry

end Bench_sf_local096
