import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_bq335 — crossskill equivalence(s)

Question: Among all Bitcoin addresses that have at least one transaction in October 2017 (combining both inputs and outputs), which address conducted its final transaction on the latest date in that month, and, among any addresses sharing that same latest date, which one has the highest sum of transaction values?

NOTE: uses WITH RECURSIVE / LATERAL / FLATTEN — may not elaborate yet.

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_bq335

CREATE TABLE OUTPUTS («transaction_hash» STRING, «block_hash» STRING, «block_number» INT, «block_timestamp» INT, «index» INT, «script_asm» STRING, «script_hex» STRING, «required_signatures» INT, «type» STRING, «addresses» STRING, «value» INT)
CREATE TABLE INPUTS («transaction_hash» STRING, «block_hash» STRING, «block_number» INT, «block_timestamp» INT, «index» INT, «spent_transaction_hash» STRING, «spent_output_index» INT, «script_asm» STRING, «script_hex» STRING, «sequence» INT, «required_signatures» INT, «type» STRING, «addresses» STRING, «value» INT)

-- eq_0_1: needs a data hypothesis over multiple tables (not stated); likely `sorry`.
theorem eq_0_1 : ∀ t,
    (sql%([OUTPUTS_schema, INPUTS_schema]) "WITH all_txns AS (\n  -- Combine inputs and outputs with flattened addresses\n  SELECT \n    f.VALUE::STRING AS address,\n    TO_TIMESTAMP_NTZ(i.\"block_timestamp\", 6) AS ts,\n    i.\"value\"\n  FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"INPUTS\" i,\n  LATERAL FLATTEN(INPUT => i.\"addresses\") f\n  WHERE TO_TIMESTAMP_NTZ(i.\"block_timestamp\", 6) >= '2017-10-01'\n    AND TO_TIMESTAMP_NTZ(i.\"block_timestamp\", 6) < '2017-11-01'\n  \n  UNION ALL\n  \n  SELECT \n    f.VALUE::STRING AS address,\n    TO_TIMESTAMP_NTZ(o.\"block_timestamp\", 6) AS ts,\n    o.\"value\"\n  FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"OUTPUTS\" o,\n  LATERAL FLATTEN(INPUT => o.\"addresses\") f\n  WHERE TO_TIMESTAMP_NTZ(o.\"block_timestamp\", 6) >= '2017-10-01'\n    AND TO_TIMESTAMP_NTZ(o.\"block_timestamp\", 6) < '2017-11-01'\n),\nper_address AS (\n  -- For each address: find their last transaction timestamp and total value\n  SELECT \n    address,\n    MAX(ts) AS last_txn_ts,\n    SUM(\"value\") AS total_value\n  FROM all_txns\n  GROUP BY address\n)\n-- Find the address with the latest final transaction, breaking ties by highest total value\nSELECT address AS OUTPUT\nFROM per_address\nORDER BY last_txn_ts DESC, total_value DESC\nLIMIT 1;") t ~= (sql%([OUTPUTS_schema, INPUTS_schema]) "WITH all_addr AS (\n  SELECT f.VALUE::STRING AS address, \"block_timestamp\", \"value\"\n  FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"INPUTS\",\n    LATERAL FLATTEN(INPUT => \"addresses\") f\n  WHERE \"block_timestamp\" >= 1506816000000000\n    AND \"block_timestamp\" < 1509494400000000\n  UNION ALL\n  SELECT f.VALUE::STRING AS address, \"block_timestamp\", \"value\"\n  FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"OUTPUTS\",\n    LATERAL FLATTEN(INPUT => \"addresses\") f\n  WHERE \"block_timestamp\" >= 1506816000000000\n    AND \"block_timestamp\" < 1509494400000000\n),\naddr_stats AS (\n  SELECT\n    address,\n    MAX(\"block_timestamp\") AS last_ts,\n    SUM(\"value\") AS total_value\n  FROM all_addr\n  GROUP BY address\n)\nSELECT address AS \"OUTPUT\"\nFROM addr_stats\nORDER BY last_ts DESC, total_value DESC\nLIMIT 1;") t := by
  intro t; first | sql_equiv | sorry

-- eq_0_2: needs a data hypothesis over multiple tables (not stated); likely `sorry`.
theorem eq_0_2 : ∀ t,
    (sql%([OUTPUTS_schema, INPUTS_schema]) "WITH all_txns AS (\n  -- Combine inputs and outputs with flattened addresses\n  SELECT \n    f.VALUE::STRING AS address,\n    TO_TIMESTAMP_NTZ(i.\"block_timestamp\", 6) AS ts,\n    i.\"value\"\n  FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"INPUTS\" i,\n  LATERAL FLATTEN(INPUT => i.\"addresses\") f\n  WHERE TO_TIMESTAMP_NTZ(i.\"block_timestamp\", 6) >= '2017-10-01'\n    AND TO_TIMESTAMP_NTZ(i.\"block_timestamp\", 6) < '2017-11-01'\n  \n  UNION ALL\n  \n  SELECT \n    f.VALUE::STRING AS address,\n    TO_TIMESTAMP_NTZ(o.\"block_timestamp\", 6) AS ts,\n    o.\"value\"\n  FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"OUTPUTS\" o,\n  LATERAL FLATTEN(INPUT => o.\"addresses\") f\n  WHERE TO_TIMESTAMP_NTZ(o.\"block_timestamp\", 6) >= '2017-10-01'\n    AND TO_TIMESTAMP_NTZ(o.\"block_timestamp\", 6) < '2017-11-01'\n),\nper_address AS (\n  -- For each address: find their last transaction timestamp and total value\n  SELECT \n    address,\n    MAX(ts) AS last_txn_ts,\n    SUM(\"value\") AS total_value\n  FROM all_txns\n  GROUP BY address\n)\n-- Find the address with the latest final transaction, breaking ties by highest total value\nSELECT address AS OUTPUT\nFROM per_address\nORDER BY last_txn_ts DESC, total_value DESC\nLIMIT 1;") t ~= (sql%([OUTPUTS_schema, INPUTS_schema]) "WITH all_addresses AS (\n    -- Addresses from OUTPUTS in October 2017\n    SELECT\n        f.VALUE::STRING AS address,\n        o.\"value\" AS tx_value,\n        TO_TIMESTAMP(o.\"block_timestamp\" / 1000000) AS block_ts\n    FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"OUTPUTS\" o,\n    LATERAL FLATTEN(input => o.\"addresses\") f\n    WHERE TO_TIMESTAMP(o.\"block_timestamp\" / 1000000) >= '2017-10-01'\n      AND TO_TIMESTAMP(o.\"block_timestamp\" / 1000000) < '2017-11-01'\n\n    UNION ALL\n\n    -- Addresses from INPUTS in October 2017\n    SELECT\n        f.VALUE::STRING AS address,\n        i.\"value\" AS tx_value,\n        TO_TIMESTAMP(i.\"block_timestamp\" / 1000000) AS block_ts\n    FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"INPUTS\" i,\n    LATERAL FLATTEN(input => i.\"addresses\") f\n    WHERE TO_TIMESTAMP(i.\"block_timestamp\" / 1000000) >= '2017-10-01'\n      AND TO_TIMESTAMP(i.\"block_timestamp\" / 1000000) < '2017-11-01'\n),\naddress_stats AS (\n    SELECT\n        address,\n        MAX(block_ts) AS last_tx_date,\n        SUM(tx_value) AS total_value\n    FROM all_addresses\n    GROUP BY address\n)\nSELECT address AS \"OUTPUT\"\nFROM address_stats\nORDER BY last_tx_date DESC, total_value DESC\nLIMIT 1;") t := by
  intro t; first | sql_equiv | sorry

-- eq_0_3: needs a data hypothesis over multiple tables (not stated); likely `sorry`.
theorem eq_0_3 : ∀ t,
    (sql%([OUTPUTS_schema, INPUTS_schema]) "WITH all_txns AS (\n  -- Combine inputs and outputs with flattened addresses\n  SELECT \n    f.VALUE::STRING AS address,\n    TO_TIMESTAMP_NTZ(i.\"block_timestamp\", 6) AS ts,\n    i.\"value\"\n  FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"INPUTS\" i,\n  LATERAL FLATTEN(INPUT => i.\"addresses\") f\n  WHERE TO_TIMESTAMP_NTZ(i.\"block_timestamp\", 6) >= '2017-10-01'\n    AND TO_TIMESTAMP_NTZ(i.\"block_timestamp\", 6) < '2017-11-01'\n  \n  UNION ALL\n  \n  SELECT \n    f.VALUE::STRING AS address,\n    TO_TIMESTAMP_NTZ(o.\"block_timestamp\", 6) AS ts,\n    o.\"value\"\n  FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"OUTPUTS\" o,\n  LATERAL FLATTEN(INPUT => o.\"addresses\") f\n  WHERE TO_TIMESTAMP_NTZ(o.\"block_timestamp\", 6) >= '2017-10-01'\n    AND TO_TIMESTAMP_NTZ(o.\"block_timestamp\", 6) < '2017-11-01'\n),\nper_address AS (\n  -- For each address: find their last transaction timestamp and total value\n  SELECT \n    address,\n    MAX(ts) AS last_txn_ts,\n    SUM(\"value\") AS total_value\n  FROM all_txns\n  GROUP BY address\n)\n-- Find the address with the latest final transaction, breaking ties by highest total value\nSELECT address AS OUTPUT\nFROM per_address\nORDER BY last_txn_ts DESC, total_value DESC\nLIMIT 1;") t ~= (sql%([OUTPUTS_schema, INPUTS_schema]) "WITH all_txns AS (\n    -- Inputs\n    SELECT \n        f.value::STRING AS address,\n        \"block_timestamp\",\n        \"value\" AS tx_value\n    FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"INPUTS\",\n    LATERAL FLATTEN(input => \"addresses\") f\n    WHERE \"block_timestamp\" >= 1506816000000000\n      AND \"block_timestamp\" < 1509494400000000\n\n    UNION ALL\n\n    -- Outputs\n    SELECT \n        f.value::STRING AS address,\n        \"block_timestamp\",\n        \"value\" AS tx_value\n    FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"OUTPUTS\",\n    LATERAL FLATTEN(input => \"addresses\") f\n    WHERE \"block_timestamp\" >= 1506816000000000\n      AND \"block_timestamp\" < 1509494400000000\n),\naddress_stats AS (\n    SELECT\n        address,\n        MAX(\"block_timestamp\") AS last_tx_timestamp,\n        SUM(tx_value) AS total_value\n    FROM all_txns\n    GROUP BY address\n)\nSELECT address AS OUTPUT\nFROM address_stats\nORDER BY last_tx_timestamp DESC, total_value DESC\nLIMIT 1;") t := by
  intro t; first | sql_equiv | sorry

-- eq_1_2: needs a data hypothesis over multiple tables (not stated); likely `sorry`.
theorem eq_1_2 : ∀ t,
    (sql%([OUTPUTS_schema, INPUTS_schema]) "WITH all_addr AS (\n  SELECT f.VALUE::STRING AS address, \"block_timestamp\", \"value\"\n  FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"INPUTS\",\n    LATERAL FLATTEN(INPUT => \"addresses\") f\n  WHERE \"block_timestamp\" >= 1506816000000000\n    AND \"block_timestamp\" < 1509494400000000\n  UNION ALL\n  SELECT f.VALUE::STRING AS address, \"block_timestamp\", \"value\"\n  FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"OUTPUTS\",\n    LATERAL FLATTEN(INPUT => \"addresses\") f\n  WHERE \"block_timestamp\" >= 1506816000000000\n    AND \"block_timestamp\" < 1509494400000000\n),\naddr_stats AS (\n  SELECT\n    address,\n    MAX(\"block_timestamp\") AS last_ts,\n    SUM(\"value\") AS total_value\n  FROM all_addr\n  GROUP BY address\n)\nSELECT address AS \"OUTPUT\"\nFROM addr_stats\nORDER BY last_ts DESC, total_value DESC\nLIMIT 1;") t ~= (sql%([OUTPUTS_schema, INPUTS_schema]) "WITH all_addresses AS (\n    -- Addresses from OUTPUTS in October 2017\n    SELECT\n        f.VALUE::STRING AS address,\n        o.\"value\" AS tx_value,\n        TO_TIMESTAMP(o.\"block_timestamp\" / 1000000) AS block_ts\n    FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"OUTPUTS\" o,\n    LATERAL FLATTEN(input => o.\"addresses\") f\n    WHERE TO_TIMESTAMP(o.\"block_timestamp\" / 1000000) >= '2017-10-01'\n      AND TO_TIMESTAMP(o.\"block_timestamp\" / 1000000) < '2017-11-01'\n\n    UNION ALL\n\n    -- Addresses from INPUTS in October 2017\n    SELECT\n        f.VALUE::STRING AS address,\n        i.\"value\" AS tx_value,\n        TO_TIMESTAMP(i.\"block_timestamp\" / 1000000) AS block_ts\n    FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"INPUTS\" i,\n    LATERAL FLATTEN(input => i.\"addresses\") f\n    WHERE TO_TIMESTAMP(i.\"block_timestamp\" / 1000000) >= '2017-10-01'\n      AND TO_TIMESTAMP(i.\"block_timestamp\" / 1000000) < '2017-11-01'\n),\naddress_stats AS (\n    SELECT\n        address,\n        MAX(block_ts) AS last_tx_date,\n        SUM(tx_value) AS total_value\n    FROM all_addresses\n    GROUP BY address\n)\nSELECT address AS \"OUTPUT\"\nFROM address_stats\nORDER BY last_tx_date DESC, total_value DESC\nLIMIT 1;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_1_3 : ∀ t,
    (sql%([OUTPUTS_schema, INPUTS_schema]) "WITH all_addr AS (\n  SELECT f.VALUE::STRING AS address, \"block_timestamp\", \"value\"\n  FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"INPUTS\",\n    LATERAL FLATTEN(INPUT => \"addresses\") f\n  WHERE \"block_timestamp\" >= 1506816000000000\n    AND \"block_timestamp\" < 1509494400000000\n  UNION ALL\n  SELECT f.VALUE::STRING AS address, \"block_timestamp\", \"value\"\n  FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"OUTPUTS\",\n    LATERAL FLATTEN(INPUT => \"addresses\") f\n  WHERE \"block_timestamp\" >= 1506816000000000\n    AND \"block_timestamp\" < 1509494400000000\n),\naddr_stats AS (\n  SELECT\n    address,\n    MAX(\"block_timestamp\") AS last_ts,\n    SUM(\"value\") AS total_value\n  FROM all_addr\n  GROUP BY address\n)\nSELECT address AS \"OUTPUT\"\nFROM addr_stats\nORDER BY last_ts DESC, total_value DESC\nLIMIT 1;") t ~= (sql%([OUTPUTS_schema, INPUTS_schema]) "WITH all_txns AS (\n    -- Inputs\n    SELECT \n        f.value::STRING AS address,\n        \"block_timestamp\",\n        \"value\" AS tx_value\n    FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"INPUTS\",\n    LATERAL FLATTEN(input => \"addresses\") f\n    WHERE \"block_timestamp\" >= 1506816000000000\n      AND \"block_timestamp\" < 1509494400000000\n\n    UNION ALL\n\n    -- Outputs\n    SELECT \n        f.value::STRING AS address,\n        \"block_timestamp\",\n        \"value\" AS tx_value\n    FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"OUTPUTS\",\n    LATERAL FLATTEN(input => \"addresses\") f\n    WHERE \"block_timestamp\" >= 1506816000000000\n      AND \"block_timestamp\" < 1509494400000000\n),\naddress_stats AS (\n    SELECT\n        address,\n        MAX(\"block_timestamp\") AS last_tx_timestamp,\n        SUM(tx_value) AS total_value\n    FROM all_txns\n    GROUP BY address\n)\nSELECT address AS OUTPUT\nFROM address_stats\nORDER BY last_tx_timestamp DESC, total_value DESC\nLIMIT 1;") t := by
  intro t; first | sql_equiv | sorry

-- eq_2_3: needs a data hypothesis over multiple tables (not stated); likely `sorry`.
theorem eq_2_3 : ∀ t,
    (sql%([OUTPUTS_schema, INPUTS_schema]) "WITH all_addresses AS (\n    -- Addresses from OUTPUTS in October 2017\n    SELECT\n        f.VALUE::STRING AS address,\n        o.\"value\" AS tx_value,\n        TO_TIMESTAMP(o.\"block_timestamp\" / 1000000) AS block_ts\n    FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"OUTPUTS\" o,\n    LATERAL FLATTEN(input => o.\"addresses\") f\n    WHERE TO_TIMESTAMP(o.\"block_timestamp\" / 1000000) >= '2017-10-01'\n      AND TO_TIMESTAMP(o.\"block_timestamp\" / 1000000) < '2017-11-01'\n\n    UNION ALL\n\n    -- Addresses from INPUTS in October 2017\n    SELECT\n        f.VALUE::STRING AS address,\n        i.\"value\" AS tx_value,\n        TO_TIMESTAMP(i.\"block_timestamp\" / 1000000) AS block_ts\n    FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"INPUTS\" i,\n    LATERAL FLATTEN(input => i.\"addresses\") f\n    WHERE TO_TIMESTAMP(i.\"block_timestamp\" / 1000000) >= '2017-10-01'\n      AND TO_TIMESTAMP(i.\"block_timestamp\" / 1000000) < '2017-11-01'\n),\naddress_stats AS (\n    SELECT\n        address,\n        MAX(block_ts) AS last_tx_date,\n        SUM(tx_value) AS total_value\n    FROM all_addresses\n    GROUP BY address\n)\nSELECT address AS \"OUTPUT\"\nFROM address_stats\nORDER BY last_tx_date DESC, total_value DESC\nLIMIT 1;") t ~= (sql%([OUTPUTS_schema, INPUTS_schema]) "WITH all_txns AS (\n    -- Inputs\n    SELECT \n        f.value::STRING AS address,\n        \"block_timestamp\",\n        \"value\" AS tx_value\n    FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"INPUTS\",\n    LATERAL FLATTEN(input => \"addresses\") f\n    WHERE \"block_timestamp\" >= 1506816000000000\n      AND \"block_timestamp\" < 1509494400000000\n\n    UNION ALL\n\n    -- Outputs\n    SELECT \n        f.value::STRING AS address,\n        \"block_timestamp\",\n        \"value\" AS tx_value\n    FROM \"CRYPTO\".\"CRYPTO_BITCOIN\".\"OUTPUTS\",\n    LATERAL FLATTEN(input => \"addresses\") f\n    WHERE \"block_timestamp\" >= 1506816000000000\n      AND \"block_timestamp\" < 1509494400000000\n),\naddress_stats AS (\n    SELECT\n        address,\n        MAX(\"block_timestamp\") AS last_tx_timestamp,\n        SUM(tx_value) AS total_value\n    FROM all_txns\n    GROUP BY address\n)\nSELECT address AS OUTPUT\nFROM address_stats\nORDER BY last_tx_timestamp DESC, total_value DESC\nLIMIT 1;") t := by
  intro t; first | sql_equiv | sorry

end Bench_sf_bq335
