import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_local071 — crossskill equivalence(s)

Question: Could you review our records in June 2022 and identify which countries have the longest streak of consecutive inserted city dates? Please list the 2-letter length country codes of these countries.

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_local071

CREATE TABLE CITIES («city_id» INT, «city_name» STRING, «latitude» FLOAT, «longitude» FLOAT, «country_code_2» STRING, «capital» INT, «population» FLOAT, «insert_date» STRING)

HYPOTHESIS hyp0_1_0 : CITIES "\"insert_date\" < '2022-07-01'\n),\nwith_groups AS (\n    -- Gaps-"
HYPOTHESIS hyp0_1_1 : CITIES "\"insert_date\" <= '2022-06-30'\n),\nranked AS (\n    -- Use gaps-"
theorem eq_0_1 (t : TableRel CITIES_schema) (h0 : hyp0_1_0 t) (h1 : hyp0_1_1 t) :
    (sql%([CITIES_schema]) "WITH june_dates AS (\n    -- Get distinct insert dates per country in June 2022\n    SELECT DISTINCT \"country_code_2\", \"insert_date\"\n    FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"CITIES\"\n    WHERE \"insert_date\" >= '2022-06-01' AND \"insert_date\" < '2022-07-01'\n),\nwith_groups AS (\n    -- Gaps-and-islands: subtract row_number days from date to create group ID\n    SELECT \"country_code_2\", \"insert_date\",\n           DATEADD('day', -ROW_NUMBER() OVER (PARTITION BY \"country_code_2\" ORDER BY \"insert_date\"), \"insert_date\") AS grp\n    FROM june_dates\n),\nstreaks AS (\n    -- Count consecutive days per group per country\n    SELECT \"country_code_2\", grp, COUNT(*) AS streak_len\n    FROM with_groups\n    GROUP BY \"country_code_2\", grp\n),\nmax_streak_per_country AS (\n    -- Get the longest streak per country\n    SELECT \"country_code_2\", MAX(streak_len) AS longest_streak\n    FROM streaks\n    GROUP BY \"country_code_2\"\n)\n-- Return countries with the overall longest streak\nSELECT \"country_code_2\" AS \"COUNTRY\"\nFROM max_streak_per_country\nWHERE longest_streak = (SELECT MAX(longest_streak) FROM max_streak_per_country)\nORDER BY \"country_code_2\";") t ~= (sql%([CITIES_schema]) "-- Find countries with the longest streak of consecutive inserted city dates in June 2022\n-- Approach: gaps-and-islands to compute consecutive date streaks per country,\n-- then return countries tied at the global maximum streak length.\n\nWITH june_dates AS (\n    -- Get distinct dates per country in June 2022\n    SELECT DISTINCT\n        \"country_code_2\",\n        TO_DATE(\"insert_date\", 'YYYY-MM-DD') AS dt\n    FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"CITIES\"\n    WHERE \"insert_date\" >= '2022-06-01' AND \"insert_date\" <= '2022-06-30'\n),\nranked AS (\n    -- Use gaps-and-islands: subtract row_number of days from date to get group identifier\n    SELECT\n        \"country_code_2\",\n        dt,\n        DATEADD('day', -ROW_NUMBER() OVER (PARTITION BY \"country_code_2\" ORDER BY dt), dt) AS grp\n    FROM june_dates\n),\nstreaks AS (\n    -- Count consecutive days in each island\n    SELECT\n        \"country_code_2\",\n        grp,\n        COUNT(*) AS streak_len\n    FROM ranked\n    GROUP BY \"country_code_2\", grp\n),\nmax_streaks AS (\n    -- Get the maximum streak per country\n    SELECT\n        \"country_code_2\",\n        MAX(streak_len) AS max_streak\n    FROM streaks\n    GROUP BY \"country_code_2\"\n)\n-- Return countries whose max streak equals the global maximum\nSELECT \"country_code_2\" AS COUNTRY\nFROM max_streaks\nWHERE max_streak = (SELECT MAX(max_streak) FROM max_streaks)\nORDER BY \"country_code_2\";") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp0_2_0 : CITIES "\"insert_date\" < '2022-07-01'\n),\nwith_groups AS (\n    -- Gaps-"
theorem eq_0_2 (t : TableRel CITIES_schema) (h0 : hyp0_2_0 t) :
    (sql%([CITIES_schema]) "WITH june_dates AS (\n    -- Get distinct insert dates per country in June 2022\n    SELECT DISTINCT \"country_code_2\", \"insert_date\"\n    FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"CITIES\"\n    WHERE \"insert_date\" >= '2022-06-01' AND \"insert_date\" < '2022-07-01'\n),\nwith_groups AS (\n    -- Gaps-and-islands: subtract row_number days from date to create group ID\n    SELECT \"country_code_2\", \"insert_date\",\n           DATEADD('day', -ROW_NUMBER() OVER (PARTITION BY \"country_code_2\" ORDER BY \"insert_date\"), \"insert_date\") AS grp\n    FROM june_dates\n),\nstreaks AS (\n    -- Count consecutive days per group per country\n    SELECT \"country_code_2\", grp, COUNT(*) AS streak_len\n    FROM with_groups\n    GROUP BY \"country_code_2\", grp\n),\nmax_streak_per_country AS (\n    -- Get the longest streak per country\n    SELECT \"country_code_2\", MAX(streak_len) AS longest_streak\n    FROM streaks\n    GROUP BY \"country_code_2\"\n)\n-- Return countries with the overall longest streak\nSELECT \"country_code_2\" AS \"COUNTRY\"\nFROM max_streak_per_country\nWHERE longest_streak = (SELECT MAX(longest_streak) FROM max_streak_per_country)\nORDER BY \"country_code_2\";") t ~= (sql%([CITIES_schema]) "WITH june_dates AS (\n    SELECT DISTINCT \n        \"country_code_2\" AS country,\n        \"insert_date\"::DATE AS dt\n    FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"CITIES\"\n    WHERE \"insert_date\" >= '2022-06-01' AND \"insert_date\" < '2022-07-01'\n),\nstreaks AS (\n    SELECT \n        country,\n        dt,\n        DATEADD('day', -ROW_NUMBER() OVER (PARTITION BY country ORDER BY dt), dt) AS grp\n    FROM june_dates\n),\nstreak_lengths AS (\n    SELECT \n        country,\n        grp,\n        COUNT(*) AS streak_len\n    FROM streaks\n    GROUP BY country, grp\n),\nmax_streak_per_country AS (\n    SELECT \n        country,\n        MAX(streak_len) AS max_streak\n    FROM streak_lengths\n    GROUP BY country\n),\noverall_max AS (\n    SELECT MAX(max_streak) AS longest_streak\n    FROM max_streak_per_country\n)\nSELECT m.country AS \"COUNTRY\"\nFROM max_streak_per_country m\nJOIN overall_max o ON m.max_streak = o.longest_streak\nORDER BY m.country;") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp0_3_0 : CITIES "\"insert_date\" >= '2022-06-01'"
HYPOTHESIS hyp0_3_1 : CITIES "\"insert_date\" < '2022-07-01'\n),\nwith_groups AS (\n    -- Gaps-"
HYPOTHESIS hyp0_3_2 : CITIES "TO_DATE(\"insert_date\", 'YYYY-MM-DD') >= '2022-06-01'"
HYPOTHESIS hyp0_3_3 : CITIES "TO_DATE(\"insert_date\", 'YYYY-MM-DD') <= '2022-06-30'\n),\nwith_rn AS (\n    -- Gaps-"
theorem eq_0_3 (t : TableRel CITIES_schema) (h0 : hyp0_3_0 t) (h1 : hyp0_3_1 t) (h2 : hyp0_3_2 t) (h3 : hyp0_3_3 t) :
    (sql%([CITIES_schema]) "WITH june_dates AS (\n    -- Get distinct insert dates per country in June 2022\n    SELECT DISTINCT \"country_code_2\", \"insert_date\"\n    FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"CITIES\"\n    WHERE \"insert_date\" >= '2022-06-01' AND \"insert_date\" < '2022-07-01'\n),\nwith_groups AS (\n    -- Gaps-and-islands: subtract row_number days from date to create group ID\n    SELECT \"country_code_2\", \"insert_date\",\n           DATEADD('day', -ROW_NUMBER() OVER (PARTITION BY \"country_code_2\" ORDER BY \"insert_date\"), \"insert_date\") AS grp\n    FROM june_dates\n),\nstreaks AS (\n    -- Count consecutive days per group per country\n    SELECT \"country_code_2\", grp, COUNT(*) AS streak_len\n    FROM with_groups\n    GROUP BY \"country_code_2\", grp\n),\nmax_streak_per_country AS (\n    -- Get the longest streak per country\n    SELECT \"country_code_2\", MAX(streak_len) AS longest_streak\n    FROM streaks\n    GROUP BY \"country_code_2\"\n)\n-- Return countries with the overall longest streak\nSELECT \"country_code_2\" AS \"COUNTRY\"\nFROM max_streak_per_country\nWHERE longest_streak = (SELECT MAX(longest_streak) FROM max_streak_per_country)\nORDER BY \"country_code_2\";") t ~= (sql%([CITIES_schema]) "WITH june_dates AS (\n    -- Get distinct insert dates per country in June 2022\n    SELECT DISTINCT\n        \"country_code_2\" AS country,\n        TO_DATE(\"insert_date\", 'YYYY-MM-DD') AS insert_dt\n    FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"CITIES\"\n    WHERE TO_DATE(\"insert_date\", 'YYYY-MM-DD') >= '2022-06-01'\n      AND TO_DATE(\"insert_date\", 'YYYY-MM-DD') <= '2022-06-30'\n),\nwith_rn AS (\n    -- Gaps-and-islands: subtract row_number * interval from date to get group key\n    SELECT\n        country,\n        insert_dt,\n        DATEADD('day', -ROW_NUMBER() OVER (PARTITION BY country ORDER BY insert_dt), insert_dt) AS grp\n    FROM june_dates\n),\nstreaks AS (\n    -- Count consecutive dates per group per country\n    SELECT\n        country,\n        grp,\n        COUNT(*) AS streak_len\n    FROM with_rn\n    GROUP BY country, grp\n),\nmax_streaks AS (\n    -- Get max streak per country\n    SELECT\n        country,\n        MAX(streak_len) AS max_streak\n    FROM streaks\n    GROUP BY country\n),\noverall_max AS (\n    SELECT MAX(max_streak) AS longest_streak\n    FROM max_streaks\n)\nSELECT ms.country AS \"COUNTRY\"\nFROM max_streaks ms\nJOIN overall_max om ON ms.max_streak = om.longest_streak\nORDER BY ms.country;") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp1_2_0 : CITIES "\"insert_date\" <= '2022-06-30'\n),\nranked AS (\n    -- Use gaps-"
theorem eq_1_2 (t : TableRel CITIES_schema) (h0 : hyp1_2_0 t) :
    (sql%([CITIES_schema]) "-- Find countries with the longest streak of consecutive inserted city dates in June 2022\n-- Approach: gaps-and-islands to compute consecutive date streaks per country,\n-- then return countries tied at the global maximum streak length.\n\nWITH june_dates AS (\n    -- Get distinct dates per country in June 2022\n    SELECT DISTINCT\n        \"country_code_2\",\n        TO_DATE(\"insert_date\", 'YYYY-MM-DD') AS dt\n    FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"CITIES\"\n    WHERE \"insert_date\" >= '2022-06-01' AND \"insert_date\" <= '2022-06-30'\n),\nranked AS (\n    -- Use gaps-and-islands: subtract row_number of days from date to get group identifier\n    SELECT\n        \"country_code_2\",\n        dt,\n        DATEADD('day', -ROW_NUMBER() OVER (PARTITION BY \"country_code_2\" ORDER BY dt), dt) AS grp\n    FROM june_dates\n),\nstreaks AS (\n    -- Count consecutive days in each island\n    SELECT\n        \"country_code_2\",\n        grp,\n        COUNT(*) AS streak_len\n    FROM ranked\n    GROUP BY \"country_code_2\", grp\n),\nmax_streaks AS (\n    -- Get the maximum streak per country\n    SELECT\n        \"country_code_2\",\n        MAX(streak_len) AS max_streak\n    FROM streaks\n    GROUP BY \"country_code_2\"\n)\n-- Return countries whose max streak equals the global maximum\nSELECT \"country_code_2\" AS COUNTRY\nFROM max_streaks\nWHERE max_streak = (SELECT MAX(max_streak) FROM max_streaks)\nORDER BY \"country_code_2\";") t ~= (sql%([CITIES_schema]) "WITH june_dates AS (\n    SELECT DISTINCT \n        \"country_code_2\" AS country,\n        \"insert_date\"::DATE AS dt\n    FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"CITIES\"\n    WHERE \"insert_date\" >= '2022-06-01' AND \"insert_date\" < '2022-07-01'\n),\nstreaks AS (\n    SELECT \n        country,\n        dt,\n        DATEADD('day', -ROW_NUMBER() OVER (PARTITION BY country ORDER BY dt), dt) AS grp\n    FROM june_dates\n),\nstreak_lengths AS (\n    SELECT \n        country,\n        grp,\n        COUNT(*) AS streak_len\n    FROM streaks\n    GROUP BY country, grp\n),\nmax_streak_per_country AS (\n    SELECT \n        country,\n        MAX(streak_len) AS max_streak\n    FROM streak_lengths\n    GROUP BY country\n),\noverall_max AS (\n    SELECT MAX(max_streak) AS longest_streak\n    FROM max_streak_per_country\n)\nSELECT m.country AS \"COUNTRY\"\nFROM max_streak_per_country m\nJOIN overall_max o ON m.max_streak = o.longest_streak\nORDER BY m.country;") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp1_3_0 : CITIES "\"insert_date\" >= '2022-06-01'"
HYPOTHESIS hyp1_3_1 : CITIES "\"insert_date\" <= '2022-06-30'\n),\nranked AS (\n    -- Use gaps-"
HYPOTHESIS hyp1_3_2 : CITIES "TO_DATE(\"insert_date\", 'YYYY-MM-DD') >= '2022-06-01'"
HYPOTHESIS hyp1_3_3 : CITIES "TO_DATE(\"insert_date\", 'YYYY-MM-DD') <= '2022-06-30'\n),\nwith_rn AS (\n    -- Gaps-"
theorem eq_1_3 (t : TableRel CITIES_schema) (h0 : hyp1_3_0 t) (h1 : hyp1_3_1 t) (h2 : hyp1_3_2 t) (h3 : hyp1_3_3 t) :
    (sql%([CITIES_schema]) "-- Find countries with the longest streak of consecutive inserted city dates in June 2022\n-- Approach: gaps-and-islands to compute consecutive date streaks per country,\n-- then return countries tied at the global maximum streak length.\n\nWITH june_dates AS (\n    -- Get distinct dates per country in June 2022\n    SELECT DISTINCT\n        \"country_code_2\",\n        TO_DATE(\"insert_date\", 'YYYY-MM-DD') AS dt\n    FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"CITIES\"\n    WHERE \"insert_date\" >= '2022-06-01' AND \"insert_date\" <= '2022-06-30'\n),\nranked AS (\n    -- Use gaps-and-islands: subtract row_number of days from date to get group identifier\n    SELECT\n        \"country_code_2\",\n        dt,\n        DATEADD('day', -ROW_NUMBER() OVER (PARTITION BY \"country_code_2\" ORDER BY dt), dt) AS grp\n    FROM june_dates\n),\nstreaks AS (\n    -- Count consecutive days in each island\n    SELECT\n        \"country_code_2\",\n        grp,\n        COUNT(*) AS streak_len\n    FROM ranked\n    GROUP BY \"country_code_2\", grp\n),\nmax_streaks AS (\n    -- Get the maximum streak per country\n    SELECT\n        \"country_code_2\",\n        MAX(streak_len) AS max_streak\n    FROM streaks\n    GROUP BY \"country_code_2\"\n)\n-- Return countries whose max streak equals the global maximum\nSELECT \"country_code_2\" AS COUNTRY\nFROM max_streaks\nWHERE max_streak = (SELECT MAX(max_streak) FROM max_streaks)\nORDER BY \"country_code_2\";") t ~= (sql%([CITIES_schema]) "WITH june_dates AS (\n    -- Get distinct insert dates per country in June 2022\n    SELECT DISTINCT\n        \"country_code_2\" AS country,\n        TO_DATE(\"insert_date\", 'YYYY-MM-DD') AS insert_dt\n    FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"CITIES\"\n    WHERE TO_DATE(\"insert_date\", 'YYYY-MM-DD') >= '2022-06-01'\n      AND TO_DATE(\"insert_date\", 'YYYY-MM-DD') <= '2022-06-30'\n),\nwith_rn AS (\n    -- Gaps-and-islands: subtract row_number * interval from date to get group key\n    SELECT\n        country,\n        insert_dt,\n        DATEADD('day', -ROW_NUMBER() OVER (PARTITION BY country ORDER BY insert_dt), insert_dt) AS grp\n    FROM june_dates\n),\nstreaks AS (\n    -- Count consecutive dates per group per country\n    SELECT\n        country,\n        grp,\n        COUNT(*) AS streak_len\n    FROM with_rn\n    GROUP BY country, grp\n),\nmax_streaks AS (\n    -- Get max streak per country\n    SELECT\n        country,\n        MAX(streak_len) AS max_streak\n    FROM streaks\n    GROUP BY country\n),\noverall_max AS (\n    SELECT MAX(max_streak) AS longest_streak\n    FROM max_streaks\n)\nSELECT ms.country AS \"COUNTRY\"\nFROM max_streaks ms\nJOIN overall_max om ON ms.max_streak = om.longest_streak\nORDER BY ms.country;") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp2_3_0 : CITIES "\"insert_date\" >= '2022-06-01'"
HYPOTHESIS hyp2_3_1 : CITIES "TO_DATE(\"insert_date\", 'YYYY-MM-DD') >= '2022-06-01'"
HYPOTHESIS hyp2_3_2 : CITIES "TO_DATE(\"insert_date\", 'YYYY-MM-DD') <= '2022-06-30'\n),\nwith_rn AS (\n    -- Gaps-"
theorem eq_2_3 (t : TableRel CITIES_schema) (h0 : hyp2_3_0 t) (h1 : hyp2_3_1 t) (h2 : hyp2_3_2 t) :
    (sql%([CITIES_schema]) "WITH june_dates AS (\n    SELECT DISTINCT \n        \"country_code_2\" AS country,\n        \"insert_date\"::DATE AS dt\n    FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"CITIES\"\n    WHERE \"insert_date\" >= '2022-06-01' AND \"insert_date\" < '2022-07-01'\n),\nstreaks AS (\n    SELECT \n        country,\n        dt,\n        DATEADD('day', -ROW_NUMBER() OVER (PARTITION BY country ORDER BY dt), dt) AS grp\n    FROM june_dates\n),\nstreak_lengths AS (\n    SELECT \n        country,\n        grp,\n        COUNT(*) AS streak_len\n    FROM streaks\n    GROUP BY country, grp\n),\nmax_streak_per_country AS (\n    SELECT \n        country,\n        MAX(streak_len) AS max_streak\n    FROM streak_lengths\n    GROUP BY country\n),\noverall_max AS (\n    SELECT MAX(max_streak) AS longest_streak\n    FROM max_streak_per_country\n)\nSELECT m.country AS \"COUNTRY\"\nFROM max_streak_per_country m\nJOIN overall_max o ON m.max_streak = o.longest_streak\nORDER BY m.country;") t ~= (sql%([CITIES_schema]) "WITH june_dates AS (\n    -- Get distinct insert dates per country in June 2022\n    SELECT DISTINCT\n        \"country_code_2\" AS country,\n        TO_DATE(\"insert_date\", 'YYYY-MM-DD') AS insert_dt\n    FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"CITIES\"\n    WHERE TO_DATE(\"insert_date\", 'YYYY-MM-DD') >= '2022-06-01'\n      AND TO_DATE(\"insert_date\", 'YYYY-MM-DD') <= '2022-06-30'\n),\nwith_rn AS (\n    -- Gaps-and-islands: subtract row_number * interval from date to get group key\n    SELECT\n        country,\n        insert_dt,\n        DATEADD('day', -ROW_NUMBER() OVER (PARTITION BY country ORDER BY insert_dt), insert_dt) AS grp\n    FROM june_dates\n),\nstreaks AS (\n    -- Count consecutive dates per group per country\n    SELECT\n        country,\n        grp,\n        COUNT(*) AS streak_len\n    FROM with_rn\n    GROUP BY country, grp\n),\nmax_streaks AS (\n    -- Get max streak per country\n    SELECT\n        country,\n        MAX(streak_len) AS max_streak\n    FROM streaks\n    GROUP BY country\n),\noverall_max AS (\n    SELECT MAX(max_streak) AS longest_streak\n    FROM max_streaks\n)\nSELECT ms.country AS \"COUNTRY\"\nFROM max_streaks ms\nJOIN overall_max om ON ms.max_streak = om.longest_streak\nORDER BY ms.country;") t := by
  first | sql_equiv | sorry

end Bench_sf_local071
