import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_bq065 — crossskill equivalence(s)

Question: From the oracle requests table, retrieve the 10 most recent oracle requests with script ID 3. For each request, extract all symbol-rate pairs by matching each symbol in the "symbols" array with its corresponding rate at the same position in the "rates" array from the decoded result. Adjust each rate by dividing it by the request's multiplier value. Return the block timestamp, oracle request ID, symbol, and the adjusted rate for each symbol-rate pair. Sort the results in chronological order with the newest records first.

NOTE: uses WITH RECURSIVE / LATERAL / FLATTEN — may not elaborate yet.

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_bq065

CREATE TABLE ORACLE_REQUESTS («block_height» INT, «block_timestamp» STRING, «block_timestamp_truncated» INT, «oracle_request_id» INT, «request» STRING, «reports» STRING, «result» STRING, «decoded_result» STRING, «oracle_script» STRING)

HYPOTHESIS hyp0_1_0 : ORACLE_REQUESTS "\"request\":\"oracle_script_id\" = 3"
theorem eq_0_1 (t : TableRel ORACLE_REQUESTS_schema) (h0 : hyp0_1_0 t) :
    (sql%([ORACLE_REQUESTS_schema]) "WITH top_requests AS (\n  SELECT\n    \"block_timestamp\",\n    \"oracle_request_id\",\n    \"decoded_result\"\n  FROM \"CRYPTO\".\"CRYPTO_BAND\".\"ORACLE_REQUESTS\"\n  WHERE \"request\":\"oracle_script_id\" = 3\n  ORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC\n  LIMIT 10\n)\nSELECT\n  r.\"block_timestamp\" AS BLOCK_TIMESTAMP,\n  r.\"oracle_request_id\" AS ORACLE_REQUEST_ID,\n  sym.VALUE::VARCHAR AS SYMBOL,\n  PARSE_JSON(r.\"decoded_result\":\"result\"::VARCHAR):\"rates\"[sym.INDEX]::FLOAT\n    / PARSE_JSON(r.\"decoded_result\":\"calldata\"::VARCHAR):\"multiplier\"::FLOAT AS ADJUSTED_RATE\nFROM top_requests r,\n  LATERAL FLATTEN(input => PARSE_JSON(r.\"decoded_result\":\"calldata\"::VARCHAR):\"symbols\") sym\nORDER BY r.\"block_timestamp\" DESC, r.\"oracle_request_id\" DESC;") t = (sql%([ORACLE_REQUESTS_schema]) "WITH top_requests AS (\n  SELECT\n    \"block_timestamp\",\n    \"oracle_request_id\",\n    \"decoded_result\"\n  FROM \"CRYPTO\".\"CRYPTO_BAND\".\"ORACLE_REQUESTS\"\n  WHERE \"request\":\"oracle_script_id\"::INT = 3\n  ORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC\n  LIMIT 10\n)\nSELECT\n  \"block_timestamp\" AS BLOCK_TIMESTAMP,\n  \"oracle_request_id\" AS ORACLE_REQUEST_ID,\n  s.VALUE::STRING AS SYMBOL,\n  r.VALUE::DOUBLE / PARSE_JSON(\"decoded_result\":\"calldata\"):\"multiplier\"::DOUBLE AS ADJUSTED_RATE\nFROM top_requests,\n  LATERAL FLATTEN(input => PARSE_JSON(\"decoded_result\":\"calldata\"):\"symbols\") s,\n  LATERAL FLATTEN(input => PARSE_JSON(\"decoded_result\":\"result\"):\"rates\") r\nWHERE s.INDEX = r.INDEX\nORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC, s.INDEX;") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp0_2_0 : ORACLE_REQUESTS "\"request\":\"oracle_script_id\" = 3"
theorem eq_0_2 (t : TableRel ORACLE_REQUESTS_schema) (h0 : hyp0_2_0 t) :
    (sql%([ORACLE_REQUESTS_schema]) "WITH top_requests AS (\n  SELECT\n    \"block_timestamp\",\n    \"oracle_request_id\",\n    \"decoded_result\"\n  FROM \"CRYPTO\".\"CRYPTO_BAND\".\"ORACLE_REQUESTS\"\n  WHERE \"request\":\"oracle_script_id\" = 3\n  ORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC\n  LIMIT 10\n)\nSELECT\n  r.\"block_timestamp\" AS BLOCK_TIMESTAMP,\n  r.\"oracle_request_id\" AS ORACLE_REQUEST_ID,\n  sym.VALUE::VARCHAR AS SYMBOL,\n  PARSE_JSON(r.\"decoded_result\":\"result\"::VARCHAR):\"rates\"[sym.INDEX]::FLOAT\n    / PARSE_JSON(r.\"decoded_result\":\"calldata\"::VARCHAR):\"multiplier\"::FLOAT AS ADJUSTED_RATE\nFROM top_requests r,\n  LATERAL FLATTEN(input => PARSE_JSON(r.\"decoded_result\":\"calldata\"::VARCHAR):\"symbols\") sym\nORDER BY r.\"block_timestamp\" DESC, r.\"oracle_request_id\" DESC;") t ~= (sql%([ORACLE_REQUESTS_schema]) "WITH top10 AS (\n  SELECT\n    \"block_timestamp\",\n    \"oracle_request_id\",\n    PARSE_JSON(\"decoded_result\":\"calldata\") AS calldata,\n    PARSE_JSON(\"decoded_result\":\"result\") AS result_obj\n  FROM \"CRYPTO\".\"CRYPTO_BAND\".\"ORACLE_REQUESTS\"\n  WHERE \"request\":\"oracle_script_id\"::INT = 3\n  ORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC\n  LIMIT 10\n)\nSELECT\n  t.\"block_timestamp\" AS \"BLOCK_TIMESTAMP\",\n  t.\"oracle_request_id\" AS \"ORACLE_REQUEST_ID\",\n  sym.VALUE::STRING AS \"SYMBOL\",\n  rates.VALUE::FLOAT / calldata:\"multiplier\"::FLOAT AS \"ADJUSTED_RATE\"\nFROM top10 t,\n  LATERAL FLATTEN(input => t.calldata:\"symbols\") sym,\n  LATERAL FLATTEN(input => t.result_obj:\"rates\") rates\nWHERE sym.INDEX = rates.INDEX\nORDER BY t.\"block_timestamp\" DESC, t.\"oracle_request_id\" DESC;") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp0_3_0 : ORACLE_REQUESTS "\"request\":\"oracle_script_id\" = 3"
theorem eq_0_3 (t : TableRel ORACLE_REQUESTS_schema) (h0 : hyp0_3_0 t) :
    (sql%([ORACLE_REQUESTS_schema]) "WITH top_requests AS (\n  SELECT\n    \"block_timestamp\",\n    \"oracle_request_id\",\n    \"decoded_result\"\n  FROM \"CRYPTO\".\"CRYPTO_BAND\".\"ORACLE_REQUESTS\"\n  WHERE \"request\":\"oracle_script_id\" = 3\n  ORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC\n  LIMIT 10\n)\nSELECT\n  r.\"block_timestamp\" AS BLOCK_TIMESTAMP,\n  r.\"oracle_request_id\" AS ORACLE_REQUEST_ID,\n  sym.VALUE::VARCHAR AS SYMBOL,\n  PARSE_JSON(r.\"decoded_result\":\"result\"::VARCHAR):\"rates\"[sym.INDEX]::FLOAT\n    / PARSE_JSON(r.\"decoded_result\":\"calldata\"::VARCHAR):\"multiplier\"::FLOAT AS ADJUSTED_RATE\nFROM top_requests r,\n  LATERAL FLATTEN(input => PARSE_JSON(r.\"decoded_result\":\"calldata\"::VARCHAR):\"symbols\") sym\nORDER BY r.\"block_timestamp\" DESC, r.\"oracle_request_id\" DESC;") t = (sql%([ORACLE_REQUESTS_schema]) "WITH top10_requests AS (\n  SELECT\n    \"oracle_request_id\",\n    \"block_timestamp\",\n    \"decoded_result\"\n  FROM \"CRYPTO\".\"CRYPTO_BAND\".\"ORACLE_REQUESTS\"\n  WHERE \"request\":\"oracle_script_id\"::INTEGER = 3\n  ORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC\n  LIMIT 10\n)\nSELECT\n  t.\"block_timestamp\" AS BLOCK_TIMESTAMP,\n  t.\"oracle_request_id\" AS ORACLE_REQUEST_ID,\n  sym.VALUE::STRING AS SYMBOL,\n  PARSE_JSON(t.\"decoded_result\":\"result\"):\"rates\"[sym.INDEX]::FLOAT\n    / PARSE_JSON(t.\"decoded_result\":\"calldata\"):\"multiplier\"::FLOAT AS ADJUSTED_RATE\nFROM top10_requests t,\n  LATERAL FLATTEN(input => PARSE_JSON(t.\"decoded_result\":\"calldata\"):\"symbols\") sym\nORDER BY t.\"block_timestamp\" DESC, t.\"oracle_request_id\" DESC, sym.INDEX ASC;") t := by
  first | sql_equiv | sorry

theorem eq_1_2 : ∀ t,
    (sql%([ORACLE_REQUESTS_schema]) "WITH top_requests AS (\n  SELECT\n    \"block_timestamp\",\n    \"oracle_request_id\",\n    \"decoded_result\"\n  FROM \"CRYPTO\".\"CRYPTO_BAND\".\"ORACLE_REQUESTS\"\n  WHERE \"request\":\"oracle_script_id\"::INT = 3\n  ORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC\n  LIMIT 10\n)\nSELECT\n  \"block_timestamp\" AS BLOCK_TIMESTAMP,\n  \"oracle_request_id\" AS ORACLE_REQUEST_ID,\n  s.VALUE::STRING AS SYMBOL,\n  r.VALUE::DOUBLE / PARSE_JSON(\"decoded_result\":\"calldata\"):\"multiplier\"::DOUBLE AS ADJUSTED_RATE\nFROM top_requests,\n  LATERAL FLATTEN(input => PARSE_JSON(\"decoded_result\":\"calldata\"):\"symbols\") s,\n  LATERAL FLATTEN(input => PARSE_JSON(\"decoded_result\":\"result\"):\"rates\") r\nWHERE s.INDEX = r.INDEX\nORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC, s.INDEX;") t ~= (sql%([ORACLE_REQUESTS_schema]) "WITH top10 AS (\n  SELECT\n    \"block_timestamp\",\n    \"oracle_request_id\",\n    PARSE_JSON(\"decoded_result\":\"calldata\") AS calldata,\n    PARSE_JSON(\"decoded_result\":\"result\") AS result_obj\n  FROM \"CRYPTO\".\"CRYPTO_BAND\".\"ORACLE_REQUESTS\"\n  WHERE \"request\":\"oracle_script_id\"::INT = 3\n  ORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC\n  LIMIT 10\n)\nSELECT\n  t.\"block_timestamp\" AS \"BLOCK_TIMESTAMP\",\n  t.\"oracle_request_id\" AS \"ORACLE_REQUEST_ID\",\n  sym.VALUE::STRING AS \"SYMBOL\",\n  rates.VALUE::FLOAT / calldata:\"multiplier\"::FLOAT AS \"ADJUSTED_RATE\"\nFROM top10 t,\n  LATERAL FLATTEN(input => t.calldata:\"symbols\") sym,\n  LATERAL FLATTEN(input => t.result_obj:\"rates\") rates\nWHERE sym.INDEX = rates.INDEX\nORDER BY t.\"block_timestamp\" DESC, t.\"oracle_request_id\" DESC;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_1_3 :
    sql%([ORACLE_REQUESTS_schema]) "WITH top_requests AS (\n  SELECT\n    \"block_timestamp\",\n    \"oracle_request_id\",\n    \"decoded_result\"\n  FROM \"CRYPTO\".\"CRYPTO_BAND\".\"ORACLE_REQUESTS\"\n  WHERE \"request\":\"oracle_script_id\"::INT = 3\n  ORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC\n  LIMIT 10\n)\nSELECT\n  \"block_timestamp\" AS BLOCK_TIMESTAMP,\n  \"oracle_request_id\" AS ORACLE_REQUEST_ID,\n  s.VALUE::STRING AS SYMBOL,\n  r.VALUE::DOUBLE / PARSE_JSON(\"decoded_result\":\"calldata\"):\"multiplier\"::DOUBLE AS ADJUSTED_RATE\nFROM top_requests,\n  LATERAL FLATTEN(input => PARSE_JSON(\"decoded_result\":\"calldata\"):\"symbols\") s,\n  LATERAL FLATTEN(input => PARSE_JSON(\"decoded_result\":\"result\"):\"rates\") r\nWHERE s.INDEX = r.INDEX\nORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC, s.INDEX;" = sql%([ORACLE_REQUESTS_schema]) "WITH top10_requests AS (\n  SELECT\n    \"oracle_request_id\",\n    \"block_timestamp\",\n    \"decoded_result\"\n  FROM \"CRYPTO\".\"CRYPTO_BAND\".\"ORACLE_REQUESTS\"\n  WHERE \"request\":\"oracle_script_id\"::INTEGER = 3\n  ORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC\n  LIMIT 10\n)\nSELECT\n  t.\"block_timestamp\" AS BLOCK_TIMESTAMP,\n  t.\"oracle_request_id\" AS ORACLE_REQUEST_ID,\n  sym.VALUE::STRING AS SYMBOL,\n  PARSE_JSON(t.\"decoded_result\":\"result\"):\"rates\"[sym.INDEX]::FLOAT\n    / PARSE_JSON(t.\"decoded_result\":\"calldata\"):\"multiplier\"::FLOAT AS ADJUSTED_RATE\nFROM top10_requests t,\n  LATERAL FLATTEN(input => PARSE_JSON(t.\"decoded_result\":\"calldata\"):\"symbols\") sym\nORDER BY t.\"block_timestamp\" DESC, t.\"oracle_request_id\" DESC, sym.INDEX ASC;" := by
  first | sql_equiv | sorry

theorem eq_2_3 : ∀ t,
    (sql%([ORACLE_REQUESTS_schema]) "WITH top10 AS (\n  SELECT\n    \"block_timestamp\",\n    \"oracle_request_id\",\n    PARSE_JSON(\"decoded_result\":\"calldata\") AS calldata,\n    PARSE_JSON(\"decoded_result\":\"result\") AS result_obj\n  FROM \"CRYPTO\".\"CRYPTO_BAND\".\"ORACLE_REQUESTS\"\n  WHERE \"request\":\"oracle_script_id\"::INT = 3\n  ORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC\n  LIMIT 10\n)\nSELECT\n  t.\"block_timestamp\" AS \"BLOCK_TIMESTAMP\",\n  t.\"oracle_request_id\" AS \"ORACLE_REQUEST_ID\",\n  sym.VALUE::STRING AS \"SYMBOL\",\n  rates.VALUE::FLOAT / calldata:\"multiplier\"::FLOAT AS \"ADJUSTED_RATE\"\nFROM top10 t,\n  LATERAL FLATTEN(input => t.calldata:\"symbols\") sym,\n  LATERAL FLATTEN(input => t.result_obj:\"rates\") rates\nWHERE sym.INDEX = rates.INDEX\nORDER BY t.\"block_timestamp\" DESC, t.\"oracle_request_id\" DESC;") t ~= (sql%([ORACLE_REQUESTS_schema]) "WITH top10_requests AS (\n  SELECT\n    \"oracle_request_id\",\n    \"block_timestamp\",\n    \"decoded_result\"\n  FROM \"CRYPTO\".\"CRYPTO_BAND\".\"ORACLE_REQUESTS\"\n  WHERE \"request\":\"oracle_script_id\"::INTEGER = 3\n  ORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC\n  LIMIT 10\n)\nSELECT\n  t.\"block_timestamp\" AS BLOCK_TIMESTAMP,\n  t.\"oracle_request_id\" AS ORACLE_REQUEST_ID,\n  sym.VALUE::STRING AS SYMBOL,\n  PARSE_JSON(t.\"decoded_result\":\"result\"):\"rates\"[sym.INDEX]::FLOAT\n    / PARSE_JSON(t.\"decoded_result\":\"calldata\"):\"multiplier\"::FLOAT AS ADJUSTED_RATE\nFROM top10_requests t,\n  LATERAL FLATTEN(input => PARSE_JSON(t.\"decoded_result\":\"calldata\"):\"symbols\") sym\nORDER BY t.\"block_timestamp\" DESC, t.\"oracle_request_id\" DESC, sym.INDEX ASC;") t := by
  intro t; first | sql_equiv | sorry

end Bench_sf_bq065
