import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_ga003 — crossskill equivalence(s)

Question: I'm trying to evaluate which board types were most effective on September 15, 2018. Can you find out the average scores for each board type from the quick play mode completions on that day?

NOTE: uses WITH RECURSIVE / LATERAL / FLATTEN — may not elaborate yet.

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_ga003

CREATE TABLE EVENTS_20180915 («event_date» STRING, «event_timestamp» INT, «event_name» STRING, «event_params» STRING, «event_previous_timestamp» INT, «event_value_in_usd» FLOAT, «event_bundle_sequence_id» INT, «event_server_timestamp_offset» INT, «user_id» STRING, «user_pseudo_id» STRING, «user_properties» STRING, «user_first_touch_timestamp» INT, «user_ltv» STRING, «device» STRING, «geo» STRING, «app_info» STRING, «traffic_source» STRING, «stream_id» STRING, «platform» STRING, «event_dimensions» STRING)

theorem eq_0_1 :
    sql%([EVENTS_20180915_schema]) "SELECT board_type AS BOARD, ROUND(CAST(AVG(score) AS DECIMAL), 6) AS AVERAGE_SCORE FROM (SELECT MAX(CASE WHEN CAST(JSON_EXTRACT_PATH(f.value, 'key') AS TEXT) = 'board' THEN CAST(JSON_EXTRACT_PATH(f.value, 'value', 'string_value') AS TEXT) END) AS board_type, MAX(CASE WHEN CAST(JSON_EXTRACT_PATH(f.value, 'key') AS TEXT) = 'value' THEN CAST(JSON_EXTRACT_PATH(f.value, 'value', 'int_value') AS INT) END) AS score FROM \"FIREBASE\".\"ANALYTICS_153293282\".\"EVENTS_20180915\" AS e, LATERAL UNNEST(input => e.\"event_params\") AS f(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE e.\"event_name\" = 'level_complete_quickplay' GROUP BY e.\"event_timestamp\", e.\"user_pseudo_id\") GROUP BY board_type ORDER BY board_type" = sql%([EVENTS_20180915_schema]) "SELECT CAST(JSON_EXTRACT_PATH(f_board.value, 'value', 'string_value') AS TEXT) AS BOARD, ROUND(CAST(AVG(CAST(JSON_EXTRACT_PATH(f_val.value, 'value', 'int_value') AS DECIMAL(38, 0))) AS DECIMAL), 6) AS AVERAGE_SCORE FROM \"FIREBASE\".\"ANALYTICS_153293282\".\"EVENTS_20180915\" AS e, LATERAL UNNEST(input => CAST(e.\"event_params\" AS JSON)) AS f_board(SEQ, KEY, PATH, INDEX, VALUE, THIS), LATERAL UNNEST(input => CAST(e.\"event_params\" AS JSON)) AS f_val(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE e.\"event_name\" = 'level_complete_quickplay' AND CAST(JSON_EXTRACT_PATH(f_board.value, 'key') AS TEXT) = 'board' AND CAST(JSON_EXTRACT_PATH(f_val.value, 'key') AS TEXT) = 'value' GROUP BY BOARD ORDER BY AVERAGE_SCORE DESC" := by
  first | sql_equiv | sorry

theorem eq_0_2 :
    sql%([EVENTS_20180915_schema]) "SELECT board_type AS BOARD, ROUND(CAST(AVG(score) AS DECIMAL), 6) AS AVERAGE_SCORE FROM (SELECT MAX(CASE WHEN CAST(JSON_EXTRACT_PATH(f.value, 'key') AS TEXT) = 'board' THEN CAST(JSON_EXTRACT_PATH(f.value, 'value', 'string_value') AS TEXT) END) AS board_type, MAX(CASE WHEN CAST(JSON_EXTRACT_PATH(f.value, 'key') AS TEXT) = 'value' THEN CAST(JSON_EXTRACT_PATH(f.value, 'value', 'int_value') AS INT) END) AS score FROM \"FIREBASE\".\"ANALYTICS_153293282\".\"EVENTS_20180915\" AS e, LATERAL UNNEST(input => e.\"event_params\") AS f(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE e.\"event_name\" = 'level_complete_quickplay' GROUP BY e.\"event_timestamp\", e.\"user_pseudo_id\") GROUP BY board_type ORDER BY board_type" = sql%([EVENTS_20180915_schema]) "SELECT CAST(JSON_EXTRACT_PATH(bp.value, 'value', 'string_value') AS TEXT) AS \"BOARD\", AVG(CAST(JSON_EXTRACT_PATH(sp.value, 'value', 'int_value') AS INT)) AS \"AVERAGE_SCORE\" FROM \"FIREBASE\".\"ANALYTICS_153293282\".\"EVENTS_20180915\" AS e, LATERAL UNNEST(input => e.\"event_params\") AS bp(SEQ, KEY, PATH, INDEX, VALUE, THIS), LATERAL UNNEST(input => e.\"event_params\") AS sp(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE e.\"event_name\" = 'level_complete_quickplay' AND CAST(JSON_EXTRACT_PATH(bp.value, 'key') AS TEXT) = 'board' AND CAST(JSON_EXTRACT_PATH(sp.value, 'key') AS TEXT) = 'value' GROUP BY CAST(JSON_EXTRACT_PATH(bp.value, 'value', 'string_value') AS TEXT) ORDER BY CAST(JSON_EXTRACT_PATH(bp.value, 'value', 'string_value') AS TEXT)" := by
  first | sql_equiv | sorry

HYPOTHESIS hyp0_3_0 : EVENTS_20180915 "\"event_name\" = 'level_complete_quickplay'"
theorem eq_0_3 (t : TableRel EVENTS_20180915_schema) (h0 : hyp0_3_0 t) :
    (sql%([EVENTS_20180915_schema]) "SELECT board_type AS BOARD, ROUND(CAST(AVG(score) AS DECIMAL), 6) AS AVERAGE_SCORE FROM (SELECT MAX(CASE WHEN CAST(JSON_EXTRACT_PATH(f.value, 'key') AS TEXT) = 'board' THEN CAST(JSON_EXTRACT_PATH(f.value, 'value', 'string_value') AS TEXT) END) AS board_type, MAX(CASE WHEN CAST(JSON_EXTRACT_PATH(f.value, 'key') AS TEXT) = 'value' THEN CAST(JSON_EXTRACT_PATH(f.value, 'value', 'int_value') AS INT) END) AS score FROM \"FIREBASE\".\"ANALYTICS_153293282\".\"EVENTS_20180915\" AS e, LATERAL UNNEST(input => e.\"event_params\") AS f(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE e.\"event_name\" = 'level_complete_quickplay' GROUP BY e.\"event_timestamp\", e.\"user_pseudo_id\") GROUP BY board_type ORDER BY board_type") t ~= (sql%([EVENTS_20180915_schema]) "SELECT CAST(JSON_EXTRACT_PATH(f1.value, 'value', 'string_value') AS VARCHAR) AS board_type, AVG(CAST(JSON_EXTRACT_PATH(f2.value, 'value', 'int_value') AS INT)) AS average_score FROM \"FIREBASE\".\"ANALYTICS_153293282\".\"EVENTS_20180915\", LATERAL UNNEST(input => \"event_params\") AS f1(SEQ, KEY, PATH, INDEX, VALUE, THIS), LATERAL UNNEST(input => \"event_params\") AS f2(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE \"event_name\" = 'level_complete_quickplay' AND CAST(JSON_EXTRACT_PATH(f1.value, 'key') AS VARCHAR) = 'board' AND CAST(JSON_EXTRACT_PATH(f2.value, 'key') AS VARCHAR) = 'value' GROUP BY board_type ORDER BY average_score DESC") t := by
  first | sql_equiv | sorry

theorem eq_1_2 :
    sql%([EVENTS_20180915_schema]) "SELECT CAST(JSON_EXTRACT_PATH(f_board.value, 'value', 'string_value') AS TEXT) AS BOARD, ROUND(CAST(AVG(CAST(JSON_EXTRACT_PATH(f_val.value, 'value', 'int_value') AS DECIMAL(38, 0))) AS DECIMAL), 6) AS AVERAGE_SCORE FROM \"FIREBASE\".\"ANALYTICS_153293282\".\"EVENTS_20180915\" AS e, LATERAL UNNEST(input => CAST(e.\"event_params\" AS JSON)) AS f_board(SEQ, KEY, PATH, INDEX, VALUE, THIS), LATERAL UNNEST(input => CAST(e.\"event_params\" AS JSON)) AS f_val(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE e.\"event_name\" = 'level_complete_quickplay' AND CAST(JSON_EXTRACT_PATH(f_board.value, 'key') AS TEXT) = 'board' AND CAST(JSON_EXTRACT_PATH(f_val.value, 'key') AS TEXT) = 'value' GROUP BY BOARD ORDER BY AVERAGE_SCORE DESC" = sql%([EVENTS_20180915_schema]) "SELECT CAST(JSON_EXTRACT_PATH(bp.value, 'value', 'string_value') AS TEXT) AS \"BOARD\", AVG(CAST(JSON_EXTRACT_PATH(sp.value, 'value', 'int_value') AS INT)) AS \"AVERAGE_SCORE\" FROM \"FIREBASE\".\"ANALYTICS_153293282\".\"EVENTS_20180915\" AS e, LATERAL UNNEST(input => e.\"event_params\") AS bp(SEQ, KEY, PATH, INDEX, VALUE, THIS), LATERAL UNNEST(input => e.\"event_params\") AS sp(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE e.\"event_name\" = 'level_complete_quickplay' AND CAST(JSON_EXTRACT_PATH(bp.value, 'key') AS TEXT) = 'board' AND CAST(JSON_EXTRACT_PATH(sp.value, 'key') AS TEXT) = 'value' GROUP BY CAST(JSON_EXTRACT_PATH(bp.value, 'value', 'string_value') AS TEXT) ORDER BY CAST(JSON_EXTRACT_PATH(bp.value, 'value', 'string_value') AS TEXT)" := by
  first | sql_equiv | sorry

HYPOTHESIS hyp1_3_0 : EVENTS_20180915 "\"event_name\" = 'level_complete_quickplay'"
theorem eq_1_3 (t : TableRel EVENTS_20180915_schema) (h0 : hyp1_3_0 t) :
    (sql%([EVENTS_20180915_schema]) "SELECT CAST(JSON_EXTRACT_PATH(f_board.value, 'value', 'string_value') AS TEXT) AS BOARD, ROUND(CAST(AVG(CAST(JSON_EXTRACT_PATH(f_val.value, 'value', 'int_value') AS DECIMAL(38, 0))) AS DECIMAL), 6) AS AVERAGE_SCORE FROM \"FIREBASE\".\"ANALYTICS_153293282\".\"EVENTS_20180915\" AS e, LATERAL UNNEST(input => CAST(e.\"event_params\" AS JSON)) AS f_board(SEQ, KEY, PATH, INDEX, VALUE, THIS), LATERAL UNNEST(input => CAST(e.\"event_params\" AS JSON)) AS f_val(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE e.\"event_name\" = 'level_complete_quickplay' AND CAST(JSON_EXTRACT_PATH(f_board.value, 'key') AS TEXT) = 'board' AND CAST(JSON_EXTRACT_PATH(f_val.value, 'key') AS TEXT) = 'value' GROUP BY BOARD ORDER BY AVERAGE_SCORE DESC") t ~= (sql%([EVENTS_20180915_schema]) "SELECT CAST(JSON_EXTRACT_PATH(f1.value, 'value', 'string_value') AS VARCHAR) AS board_type, AVG(CAST(JSON_EXTRACT_PATH(f2.value, 'value', 'int_value') AS INT)) AS average_score FROM \"FIREBASE\".\"ANALYTICS_153293282\".\"EVENTS_20180915\", LATERAL UNNEST(input => \"event_params\") AS f1(SEQ, KEY, PATH, INDEX, VALUE, THIS), LATERAL UNNEST(input => \"event_params\") AS f2(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE \"event_name\" = 'level_complete_quickplay' AND CAST(JSON_EXTRACT_PATH(f1.value, 'key') AS VARCHAR) = 'board' AND CAST(JSON_EXTRACT_PATH(f2.value, 'key') AS VARCHAR) = 'value' GROUP BY board_type ORDER BY average_score DESC") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp2_3_0 : EVENTS_20180915 "\"event_name\" = 'level_complete_quickplay'"
theorem eq_2_3 (t : TableRel EVENTS_20180915_schema) (h0 : hyp2_3_0 t) :
    (sql%([EVENTS_20180915_schema]) "SELECT CAST(JSON_EXTRACT_PATH(bp.value, 'value', 'string_value') AS TEXT) AS \"BOARD\", AVG(CAST(JSON_EXTRACT_PATH(sp.value, 'value', 'int_value') AS INT)) AS \"AVERAGE_SCORE\" FROM \"FIREBASE\".\"ANALYTICS_153293282\".\"EVENTS_20180915\" AS e, LATERAL UNNEST(input => e.\"event_params\") AS bp(SEQ, KEY, PATH, INDEX, VALUE, THIS), LATERAL UNNEST(input => e.\"event_params\") AS sp(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE e.\"event_name\" = 'level_complete_quickplay' AND CAST(JSON_EXTRACT_PATH(bp.value, 'key') AS TEXT) = 'board' AND CAST(JSON_EXTRACT_PATH(sp.value, 'key') AS TEXT) = 'value' GROUP BY CAST(JSON_EXTRACT_PATH(bp.value, 'value', 'string_value') AS TEXT) ORDER BY CAST(JSON_EXTRACT_PATH(bp.value, 'value', 'string_value') AS TEXT)") t ~= (sql%([EVENTS_20180915_schema]) "SELECT CAST(JSON_EXTRACT_PATH(f1.value, 'value', 'string_value') AS VARCHAR) AS board_type, AVG(CAST(JSON_EXTRACT_PATH(f2.value, 'value', 'int_value') AS INT)) AS average_score FROM \"FIREBASE\".\"ANALYTICS_153293282\".\"EVENTS_20180915\", LATERAL UNNEST(input => \"event_params\") AS f1(SEQ, KEY, PATH, INDEX, VALUE, THIS), LATERAL UNNEST(input => \"event_params\") AS f2(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE \"event_name\" = 'level_complete_quickplay' AND CAST(JSON_EXTRACT_PATH(f1.value, 'key') AS VARCHAR) = 'board' AND CAST(JSON_EXTRACT_PATH(f2.value, 'key') AS VARCHAR) = 'value' GROUP BY board_type ORDER BY average_score DESC") t := by
  first | sql_equiv | sorry

end Bench_sf_ga003
