import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_local133 — crossskill equivalence(s)

Question: Given a database of musical styles and user preferences, where Musical_Preferences contains user rankings of musical styles (PreferenceSeq=1 for first choice, PreferenceSeq=2 for second choice, PreferenceSeq=3 for third choice): Calculate a weighted score for each musical style by assigning 3 points for each time it was ranked as first choice, 2 points for each second choice, and 1 point for each third choice ranking. Calculate the total weighted score for each musical style that has been ranked by at least one user. Then, compute the absolute difference between each style's total weighted score and the average total weighted score across all such styles.

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_local133

CREATE TABLE MUSICAL_STYLES («StyleID» INT, «StyleName» STRING)
CREATE TABLE MUSICAL_PREFERENCES («CustomerID» INT, «StyleID» INT, «PreferenceSeq» INT)

theorem eq_0_1 :
    sql%([MUSICAL_STYLES_schema, MUSICAL_PREFERENCES_schema]) "WITH style_scores AS (\n    SELECT\n        ms.\"StyleName\",\n        SUM(CASE\n            WHEN mp.\"PreferenceSeq\" = 1 THEN 3\n            WHEN mp.\"PreferenceSeq\" = 2 THEN 2\n            WHEN mp.\"PreferenceSeq\" = 3 THEN 1\n            ELSE 0\n        END) AS TOTAL_WEIGHTED_SCORE\n    FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\" mp\n    JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_STYLES\" ms\n        ON mp.\"StyleID\" = ms.\"StyleID\"\n    GROUP BY ms.\"StyleName\"\n),\navg_score AS (\n    SELECT AVG(TOTAL_WEIGHTED_SCORE) AS AVERAGE_SCORE\n    FROM style_scores\n)\nSELECT\n    ss.\"StyleName\",\n    ss.TOTAL_WEIGHTED_SCORE,\n    ROUND(a.AVERAGE_SCORE, 4) AS AVERAGE_SCORE,\n    ROUND(ABS(ss.TOTAL_WEIGHTED_SCORE - a.AVERAGE_SCORE), 4) AS ABSOLUTE_DIFFERENCE_FROM_AVERAGE\nFROM style_scores ss\nCROSS JOIN avg_score a\nORDER BY ss.TOTAL_WEIGHTED_SCORE DESC, ss.\"StyleName\";" = sql%([MUSICAL_STYLES_schema, MUSICAL_PREFERENCES_schema]) "WITH style_scores AS (\n  SELECT\n    ms.\"StyleName\",\n    SUM(CASE\n      WHEN mp.\"PreferenceSeq\" = 1 THEN 3\n      WHEN mp.\"PreferenceSeq\" = 2 THEN 2\n      WHEN mp.\"PreferenceSeq\" = 3 THEN 1\n      ELSE 0\n    END) AS TOTAL_WEIGHTED_SCORE\n  FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\" mp\n  JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_STYLES\" ms\n    ON mp.\"StyleID\" = ms.\"StyleID\"\n  GROUP BY ms.\"StyleName\"\n)\nSELECT\n  \"StyleName\",\n  TOTAL_WEIGHTED_SCORE,\n  ROUND(AVG(TOTAL_WEIGHTED_SCORE) OVER (), 4) AS AVERAGE_SCORE,\n  ROUND(ABS(TOTAL_WEIGHTED_SCORE - AVG(TOTAL_WEIGHTED_SCORE) OVER ()), 4) AS ABSOLUTE_DIFFERENCE_FROM_AVERAGE\nFROM style_scores\nORDER BY TOTAL_WEIGHTED_SCORE DESC, \"StyleName\" ASC;" := by
  first | sql_equiv | sorry

theorem eq_0_2 :
    sql%([MUSICAL_STYLES_schema, MUSICAL_PREFERENCES_schema]) "WITH style_scores AS (\n    SELECT\n        ms.\"StyleName\",\n        SUM(CASE\n            WHEN mp.\"PreferenceSeq\" = 1 THEN 3\n            WHEN mp.\"PreferenceSeq\" = 2 THEN 2\n            WHEN mp.\"PreferenceSeq\" = 3 THEN 1\n            ELSE 0\n        END) AS TOTAL_WEIGHTED_SCORE\n    FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\" mp\n    JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_STYLES\" ms\n        ON mp.\"StyleID\" = ms.\"StyleID\"\n    GROUP BY ms.\"StyleName\"\n),\navg_score AS (\n    SELECT AVG(TOTAL_WEIGHTED_SCORE) AS AVERAGE_SCORE\n    FROM style_scores\n)\nSELECT\n    ss.\"StyleName\",\n    ss.TOTAL_WEIGHTED_SCORE,\n    ROUND(a.AVERAGE_SCORE, 4) AS AVERAGE_SCORE,\n    ROUND(ABS(ss.TOTAL_WEIGHTED_SCORE - a.AVERAGE_SCORE), 4) AS ABSOLUTE_DIFFERENCE_FROM_AVERAGE\nFROM style_scores ss\nCROSS JOIN avg_score a\nORDER BY ss.TOTAL_WEIGHTED_SCORE DESC, ss.\"StyleName\";" = sql%([MUSICAL_STYLES_schema, MUSICAL_PREFERENCES_schema]) "WITH weighted AS (\n    SELECT\n        ms.\"StyleName\",\n        SUM(CASE\n            WHEN mp.\"PreferenceSeq\" = 1 THEN 3\n            WHEN mp.\"PreferenceSeq\" = 2 THEN 2\n            WHEN mp.\"PreferenceSeq\" = 3 THEN 1\n            ELSE 0\n        END) AS TOTAL_WEIGHTED_SCORE\n    FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\" mp\n    JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_STYLES\" ms\n        ON mp.\"StyleID\" = ms.\"StyleID\"\n    GROUP BY ms.\"StyleName\"\n),\navg_score AS (\n    SELECT AVG(TOTAL_WEIGHTED_SCORE) AS AVERAGE_SCORE\n    FROM weighted\n)\nSELECT\n    w.\"StyleName\",\n    w.TOTAL_WEIGHTED_SCORE,\n    a.AVERAGE_SCORE,\n    ABS(w.TOTAL_WEIGHTED_SCORE - a.AVERAGE_SCORE) AS ABSOLUTE_DIFFERENCE_FROM_AVERAGE\nFROM weighted w\nCROSS JOIN avg_score a\nORDER BY w.\"StyleName\";" := by
  first | sql_equiv | sorry

theorem eq_0_3 : ∀ t,
    (sql%([MUSICAL_STYLES_schema, MUSICAL_PREFERENCES_schema]) "WITH style_scores AS (\n    SELECT\n        ms.\"StyleName\",\n        SUM(CASE\n            WHEN mp.\"PreferenceSeq\" = 1 THEN 3\n            WHEN mp.\"PreferenceSeq\" = 2 THEN 2\n            WHEN mp.\"PreferenceSeq\" = 3 THEN 1\n            ELSE 0\n        END) AS TOTAL_WEIGHTED_SCORE\n    FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\" mp\n    JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_STYLES\" ms\n        ON mp.\"StyleID\" = ms.\"StyleID\"\n    GROUP BY ms.\"StyleName\"\n),\navg_score AS (\n    SELECT AVG(TOTAL_WEIGHTED_SCORE) AS AVERAGE_SCORE\n    FROM style_scores\n)\nSELECT\n    ss.\"StyleName\",\n    ss.TOTAL_WEIGHTED_SCORE,\n    ROUND(a.AVERAGE_SCORE, 4) AS AVERAGE_SCORE,\n    ROUND(ABS(ss.TOTAL_WEIGHTED_SCORE - a.AVERAGE_SCORE), 4) AS ABSOLUTE_DIFFERENCE_FROM_AVERAGE\nFROM style_scores ss\nCROSS JOIN avg_score a\nORDER BY ss.TOTAL_WEIGHTED_SCORE DESC, ss.\"StyleName\";") t ~= (sql%([MUSICAL_STYLES_schema, MUSICAL_PREFERENCES_schema]) "WITH max_seq AS (\n    SELECT MAX(\"PreferenceSeq\") AS max_pref\n    FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\"\n),\nweighted AS (\n    SELECT\n        ms.\"StyleName\",\n        SUM(mx.max_pref + 1 - mp.\"PreferenceSeq\") AS \"TOTAL_WEIGHTED_SCORE\"\n    FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\" mp\n    JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_STYLES\" ms\n        ON mp.\"StyleID\" = ms.\"StyleID\"\n    CROSS JOIN max_seq mx\n    GROUP BY ms.\"StyleName\"\n),\navg_score AS (\n    SELECT\n        CAST(SUM(\"TOTAL_WEIGHTED_SCORE\") AS DECIMAL(10,4)) / COUNT(*) AS \"AVERAGE_SCORE\"\n    FROM weighted\n)\nSELECT\n    w.\"StyleName\",\n    w.\"TOTAL_WEIGHTED_SCORE\",\n    ROUND(a.\"AVERAGE_SCORE\", 4) AS \"AVERAGE_SCORE\",\n    ROUND(ABS(w.\"TOTAL_WEIGHTED_SCORE\" - a.\"AVERAGE_SCORE\"), 4) AS \"ABSOLUTE_DIFFERENCE_FROM_AVERAGE\"\nFROM weighted w\nCROSS JOIN avg_score a\nORDER BY w.\"TOTAL_WEIGHTED_SCORE\" DESC, w.\"StyleName\" ASC;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_1_2 :
    sql%([MUSICAL_STYLES_schema, MUSICAL_PREFERENCES_schema]) "WITH style_scores AS (\n  SELECT\n    ms.\"StyleName\",\n    SUM(CASE\n      WHEN mp.\"PreferenceSeq\" = 1 THEN 3\n      WHEN mp.\"PreferenceSeq\" = 2 THEN 2\n      WHEN mp.\"PreferenceSeq\" = 3 THEN 1\n      ELSE 0\n    END) AS TOTAL_WEIGHTED_SCORE\n  FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\" mp\n  JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_STYLES\" ms\n    ON mp.\"StyleID\" = ms.\"StyleID\"\n  GROUP BY ms.\"StyleName\"\n)\nSELECT\n  \"StyleName\",\n  TOTAL_WEIGHTED_SCORE,\n  ROUND(AVG(TOTAL_WEIGHTED_SCORE) OVER (), 4) AS AVERAGE_SCORE,\n  ROUND(ABS(TOTAL_WEIGHTED_SCORE - AVG(TOTAL_WEIGHTED_SCORE) OVER ()), 4) AS ABSOLUTE_DIFFERENCE_FROM_AVERAGE\nFROM style_scores\nORDER BY TOTAL_WEIGHTED_SCORE DESC, \"StyleName\" ASC;" = sql%([MUSICAL_STYLES_schema, MUSICAL_PREFERENCES_schema]) "WITH weighted AS (\n    SELECT\n        ms.\"StyleName\",\n        SUM(CASE\n            WHEN mp.\"PreferenceSeq\" = 1 THEN 3\n            WHEN mp.\"PreferenceSeq\" = 2 THEN 2\n            WHEN mp.\"PreferenceSeq\" = 3 THEN 1\n            ELSE 0\n        END) AS TOTAL_WEIGHTED_SCORE\n    FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\" mp\n    JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_STYLES\" ms\n        ON mp.\"StyleID\" = ms.\"StyleID\"\n    GROUP BY ms.\"StyleName\"\n),\navg_score AS (\n    SELECT AVG(TOTAL_WEIGHTED_SCORE) AS AVERAGE_SCORE\n    FROM weighted\n)\nSELECT\n    w.\"StyleName\",\n    w.TOTAL_WEIGHTED_SCORE,\n    a.AVERAGE_SCORE,\n    ABS(w.TOTAL_WEIGHTED_SCORE - a.AVERAGE_SCORE) AS ABSOLUTE_DIFFERENCE_FROM_AVERAGE\nFROM weighted w\nCROSS JOIN avg_score a\nORDER BY w.\"StyleName\";" := by
  first | sql_equiv | sorry

theorem eq_1_3 : ∀ t,
    (sql%([MUSICAL_STYLES_schema, MUSICAL_PREFERENCES_schema]) "WITH style_scores AS (\n  SELECT\n    ms.\"StyleName\",\n    SUM(CASE\n      WHEN mp.\"PreferenceSeq\" = 1 THEN 3\n      WHEN mp.\"PreferenceSeq\" = 2 THEN 2\n      WHEN mp.\"PreferenceSeq\" = 3 THEN 1\n      ELSE 0\n    END) AS TOTAL_WEIGHTED_SCORE\n  FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\" mp\n  JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_STYLES\" ms\n    ON mp.\"StyleID\" = ms.\"StyleID\"\n  GROUP BY ms.\"StyleName\"\n)\nSELECT\n  \"StyleName\",\n  TOTAL_WEIGHTED_SCORE,\n  ROUND(AVG(TOTAL_WEIGHTED_SCORE) OVER (), 4) AS AVERAGE_SCORE,\n  ROUND(ABS(TOTAL_WEIGHTED_SCORE - AVG(TOTAL_WEIGHTED_SCORE) OVER ()), 4) AS ABSOLUTE_DIFFERENCE_FROM_AVERAGE\nFROM style_scores\nORDER BY TOTAL_WEIGHTED_SCORE DESC, \"StyleName\" ASC;") t ~= (sql%([MUSICAL_STYLES_schema, MUSICAL_PREFERENCES_schema]) "WITH max_seq AS (\n    SELECT MAX(\"PreferenceSeq\") AS max_pref\n    FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\"\n),\nweighted AS (\n    SELECT\n        ms.\"StyleName\",\n        SUM(mx.max_pref + 1 - mp.\"PreferenceSeq\") AS \"TOTAL_WEIGHTED_SCORE\"\n    FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\" mp\n    JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_STYLES\" ms\n        ON mp.\"StyleID\" = ms.\"StyleID\"\n    CROSS JOIN max_seq mx\n    GROUP BY ms.\"StyleName\"\n),\navg_score AS (\n    SELECT\n        CAST(SUM(\"TOTAL_WEIGHTED_SCORE\") AS DECIMAL(10,4)) / COUNT(*) AS \"AVERAGE_SCORE\"\n    FROM weighted\n)\nSELECT\n    w.\"StyleName\",\n    w.\"TOTAL_WEIGHTED_SCORE\",\n    ROUND(a.\"AVERAGE_SCORE\", 4) AS \"AVERAGE_SCORE\",\n    ROUND(ABS(w.\"TOTAL_WEIGHTED_SCORE\" - a.\"AVERAGE_SCORE\"), 4) AS \"ABSOLUTE_DIFFERENCE_FROM_AVERAGE\"\nFROM weighted w\nCROSS JOIN avg_score a\nORDER BY w.\"TOTAL_WEIGHTED_SCORE\" DESC, w.\"StyleName\" ASC;") t := by
  intro t; first | sql_equiv | sorry

theorem eq_2_3 : ∀ t,
    (sql%([MUSICAL_STYLES_schema, MUSICAL_PREFERENCES_schema]) "WITH weighted AS (\n    SELECT\n        ms.\"StyleName\",\n        SUM(CASE\n            WHEN mp.\"PreferenceSeq\" = 1 THEN 3\n            WHEN mp.\"PreferenceSeq\" = 2 THEN 2\n            WHEN mp.\"PreferenceSeq\" = 3 THEN 1\n            ELSE 0\n        END) AS TOTAL_WEIGHTED_SCORE\n    FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\" mp\n    JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_STYLES\" ms\n        ON mp.\"StyleID\" = ms.\"StyleID\"\n    GROUP BY ms.\"StyleName\"\n),\navg_score AS (\n    SELECT AVG(TOTAL_WEIGHTED_SCORE) AS AVERAGE_SCORE\n    FROM weighted\n)\nSELECT\n    w.\"StyleName\",\n    w.TOTAL_WEIGHTED_SCORE,\n    a.AVERAGE_SCORE,\n    ABS(w.TOTAL_WEIGHTED_SCORE - a.AVERAGE_SCORE) AS ABSOLUTE_DIFFERENCE_FROM_AVERAGE\nFROM weighted w\nCROSS JOIN avg_score a\nORDER BY w.\"StyleName\";") t ~= (sql%([MUSICAL_STYLES_schema, MUSICAL_PREFERENCES_schema]) "WITH max_seq AS (\n    SELECT MAX(\"PreferenceSeq\") AS max_pref\n    FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\"\n),\nweighted AS (\n    SELECT\n        ms.\"StyleName\",\n        SUM(mx.max_pref + 1 - mp.\"PreferenceSeq\") AS \"TOTAL_WEIGHTED_SCORE\"\n    FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\" mp\n    JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_STYLES\" ms\n        ON mp.\"StyleID\" = ms.\"StyleID\"\n    CROSS JOIN max_seq mx\n    GROUP BY ms.\"StyleName\"\n),\navg_score AS (\n    SELECT\n        CAST(SUM(\"TOTAL_WEIGHTED_SCORE\") AS DECIMAL(10,4)) / COUNT(*) AS \"AVERAGE_SCORE\"\n    FROM weighted\n)\nSELECT\n    w.\"StyleName\",\n    w.\"TOTAL_WEIGHTED_SCORE\",\n    ROUND(a.\"AVERAGE_SCORE\", 4) AS \"AVERAGE_SCORE\",\n    ROUND(ABS(w.\"TOTAL_WEIGHTED_SCORE\" - a.\"AVERAGE_SCORE\"), 4) AS \"ABSOLUTE_DIFFERENCE_FROM_AVERAGE\"\nFROM weighted w\nCROSS JOIN avg_score a\nORDER BY w.\"TOTAL_WEIGHTED_SCORE\" DESC, w.\"StyleName\" ASC;") t := by
  intro t; first | sql_equiv | sorry

end Bench_sf_local133
