import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf010_eq_1_2

CREATE TABLE FHFA_MORTGAGE_PERFORMANCE_TIMESERIES («DATE» STRING, «UNIT» STRING, «GEO_ID» STRING, «VARIABLE_NAME» STRING, «VARIABLE» STRING, «VALUE» FLOAT)
CREATE TABLE FHFA_MORTGAGE_PERFORMANCE_ATTRIBUTES («VARIABLE_GROUP» STRING, «UNIT» STRING, «FREQUENCY» STRING, «VARIABLE» STRING, «MARKET» STRING, «VARIABLE_NAME» STRING)

theorem eq (t0 : TableRel FHFA_MORTGAGE_PERFORMANCE_TIMESERIES_schema) (t1 : TableRel FHFA_MORTGAGE_PERFORMANCE_ATTRIBUTES_schema) :
    (sql%([FHFA_MORTGAGE_PERFORMANCE_TIMESERIES_schema, FHFA_MORTGAGE_PERFORMANCE_ATTRIBUTES_schema]) "SELECT t.\"DATE\", SUM(t.\"VALUE\") AS \"PCT_NEAR_DEFAULT\" FROM \"US_REAL_ESTATE\".\"CYBERSYN\".\"FHFA_MORTGAGE_PERFORMANCE_TIMESERIES\" AS t JOIN \"US_REAL_ESTATE\".\"CYBERSYN\".\"FHFA_MORTGAGE_PERFORMANCE_ATTRIBUTES\" AS a ON t.\"VARIABLE\" = a.\"VARIABLE\" JOIN \"US_REAL_ESTATE\".\"CYBERSYN\".\"GEOGRAPHY_INDEX\" AS g ON t.\"GEO_ID\" = g.\"GEO_ID\" WHERE g.\"GEO_NAME\" = 'California' AND g.\"LEVEL\" = 'State' AND a.\"MARKET\" = 'All Mortgages' AND EXTRACT(YEAR FROM t.\"DATE\") = 2023 AND (a.\"VARIABLE_GROUP\" = 'Percent 90 or More, Days Past Due Date' OR a.\"VARIABLE_GROUP\" = 'PFORB - Percent in Forbearance' OR a.\"VARIABLE_GROUP\" = 'Percent in the Process of Foreclosure, Bankruptcy, or Deed in Lieu') GROUP BY t.\"DATE\" ORDER BY t.\"DATE\"") t0 t1
  = (sql%([FHFA_MORTGAGE_PERFORMANCE_TIMESERIES_schema, FHFA_MORTGAGE_PERFORMANCE_ATTRIBUTES_schema]) "SELECT t.DATE AS \"DATE\", SUM(t.VALUE) AS \"PCT_NEAR_DEFAULT\" FROM \"US_REAL_ESTATE\".\"CYBERSYN\".\"FHFA_MORTGAGE_PERFORMANCE_TIMESERIES\" AS t JOIN \"US_REAL_ESTATE\".\"CYBERSYN\".\"FHFA_MORTGAGE_PERFORMANCE_ATTRIBUTES\" AS a ON t.VARIABLE = a.VARIABLE JOIN \"US_REAL_ESTATE\".\"CYBERSYN\".\"GEOGRAPHY_INDEX\" AS g ON t.GEO_ID = g.GEO_ID WHERE g.GEO_NAME = 'California' AND g.LEVEL = 'State' AND a.MARKET = 'All Mortgages' AND a.VARIABLE_GROUP IN ('Percent 90 or More, Days Past Due Date', 'Percent in the Process of Foreclosure, Bankruptcy, or Deed in Lieu', 'PFORB - Percent in Forbearance') AND t.DATE >= '2023-01-01' AND t.DATE < '2024-01-01' GROUP BY t.DATE ORDER BY t.DATE") t0 t1
  := by first | sql_equiv | sorry

end N_sf010_eq_1_2
