import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_bq103_eq_0_1

CREATE TABLE V3_GENOMES__CHR1 («reference_name» STRING, «start_position» INT, «end_position» INT, «reference_bases» STRING, «alternate_bases» STRING, «names» STRING, «quality» FLOAT, «filter» STRING, «call» STRING, «AN» INT, «non_par» BOOL, «lcr» BOOL, «variant_type» STRING, «ReadPosRankSum» FLOAT, «MQRankSum» FLOAT, «RAW_MQ» FLOAT, «DP» INT, «MQ_DP» INT, «VarDP» INT, «MQ» FLOAT, «QD» FLOAT, «FS» FLOAT, «SB» STRING, «InbreedingCoeff» FLOAT, «AS_VQSLOD» FLOAT, «NEGATIVE_TRAIN_SITE» BOOL, «POSITIVE_TRAIN_SITE» BOOL, «culprit» STRING, «SOR» FLOAT, «AN_asj_female» INT, «AN_eas_female» INT, «AN_afr_male» INT, «AN_female» INT, «AN_fin_male» INT, «AN_oth_female» INT, «AN_ami» INT, «AN_oth» INT, «AN_male» INT, «AN_ami_female» INT, «AN_afr» INT, «AN_eas_male» INT, «AN_sas» INT, «AN_nfe_female» INT, «AN_asj_male» INT, «AN_raw» INT, «AN_oth_male» INT, «AN_nfe_male» INT, «AN_asj» INT, «AN_amr_male» INT, «AN_amr_female» INT, «AN_sas_female» INT, «AN_fin» INT, «AN_afr_female» INT, «AN_sas_male» INT, «AN_amr» INT, «AN_nfe» INT, «AN_eas» INT, «AN_ami_male» INT, «AN_fin_female» INT, «faf95_adj» FLOAT, «faf99_adj» FLOAT)

theorem eq (t0 : TableRel V3_GENOMES__CHR1_schema) :
    (sql%([V3_GENOMES__CHR1_schema]) "WITH variant_stats AS (SELECT COUNT(*) AS num_variants, SUM(CAST(JSON_EXTRACT_PATH(alt.value, 'AC') AS INT)) AS sum_ac, SUM(CAST(\"AN\" AS INT)) AS sum_an FROM \"GNOMAD\".\"GNOMAD\".\"V3_GENOMES__CHR1\", LATERAL UNNEST(input => \"alternate_bases\") AS alt(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE \"start_position\" BETWEEN 55039447 AND 55064852), gene_symbols AS (SELECT DISTINCT CAST(JSON_EXTRACT_PATH(vep.value, 'SYMBOL') AS TEXT) AS gene_symbol FROM \"GNOMAD\".\"GNOMAD\".\"V3_GENOMES__CHR1\", LATERAL UNNEST(input => \"alternate_bases\") AS alt(SEQ, KEY, PATH, INDEX, VALUE, THIS), LATERAL UNNEST(input => JSON_EXTRACT_PATH(alt.value, 'vep')) AS vep(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE \"start_position\" BETWEEN 55039447 AND 55064852 AND NOT CAST(JSON_EXTRACT_PATH(vep.value, 'SYMBOL') AS TEXT) IS NULL AND CAST(JSON_EXTRACT_PATH(vep.value, 'SYMBOL') AS TEXT) <> 'None') SELECT ROUND(CAST((55064852 - 55039447) / CAST(vs.num_variants AS DOUBLE PRECISION) AS DECIMAL), 3) AS BURDEN_OF_MUTATION, vs.num_variants AS NUM_VARIANTS, vs.sum_ac AS SUM_AC, vs.sum_an AS SUM_AN, (SELECT STRING_AGG(gene_symbol, ', ' ORDER BY gene_symbol) FROM gene_symbols) AS GENES FROM variant_stats AS vs") t0
  ~= (sql%([V3_GENOMES__CHR1_schema]) "WITH variant_data AS (SELECT t.\"start_position\", t.\"AN\", CAST(JSON_EXTRACT_PATH(f.value, 'AC') AS INT) AS \"AC\", JSON_EXTRACT_PATH(f.value, 'vep') AS vep_array FROM \"GNOMAD\".\"GNOMAD\".\"V3_GENOMES__CHR1\" AS t, LATERAL UNNEST(input => t.\"alternate_bases\") AS f(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE t.\"start_position\" BETWEEN 55039447 AND 55064852), gene_symbols AS (SELECT DISTINCT CAST(JSON_EXTRACT_PATH(v.value, 'SYMBOL') AS TEXT) AS gene_symbol FROM variant_data AS vd, LATERAL UNNEST(input => vd.vep_array) AS v(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE NOT CAST(JSON_EXTRACT_PATH(v.value, 'SYMBOL') AS TEXT) IS NULL), aggregated AS (SELECT COUNT(*) AS \"NUM_VARIANTS\", SUM(\"AC\") AS \"SUM_AC\", SUM(\"AN\") AS \"SUM_AN\" FROM variant_data) SELECT ROUND(CAST((55064852 - 55039447) AS DOUBLE PRECISION) / a.\"NUM_VARIANTS\", 3) AS \"BURDEN_OF_MUTATION\", a.\"NUM_VARIANTS\", a.\"SUM_AC\", a.\"SUM_AN\", (SELECT STRING_AGG(gene_symbol, ', ' ORDER BY gene_symbol) FROM gene_symbols) AS \"GENES\" FROM aggregated AS a") t0
  := by first | sql_equiv | sorry

end N_sf_bq103_eq_0_1
