import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_bq325_eq_0_1

CREATE TABLE DISEASE_VARIANT_GENE («study_id» STRING, «source» STRING, «pmid» STRING, «pub_date» STRING, «pub_journal» STRING, «pub_title» STRING, «pub_author» STRING, «has_sumstats» BOOL, «trait_reported» STRING, «trait_efos» STRING, «ancestry_initial» STRING, «ancestry_replication» STRING, «n_initial» INT, «n_replication» INT, «n_cases» INT, «trait_category» STRING, «num_assoc_loci» INT, «lead_chrom» STRING, «lead_pos» INT, «lead_ref» STRING, «lead_alt» STRING, «tag_chrom» STRING, «tag_pos» INT, «tag_ref» STRING, «tag_alt» STRING, «overall_r2» FLOAT, «AFR_1000G_prop» FLOAT, «AMR_1000G_prop» FLOAT, «EAS_1000G_prop» FLOAT, «EUR_1000G_prop» FLOAT, «SAS_1000G_prop» FLOAT, «log10_ABF» FLOAT, «posterior_prob» FLOAT, «odds_ratio» FLOAT, «oddsr_ci_lower» FLOAT, «oddsr_ci_upper» FLOAT, «direction» STRING, «beta» FLOAT, «beta_ci_lower» FLOAT, «beta_ci_upper» FLOAT, «pval_mantissa» FLOAT, «pval_exponent» INT, «pval» FLOAT, «gene_id» STRING, «feature» STRING, «type_id» STRING, «source_id» STRING, «fpred_labels» STRING, «fpred_scores» STRING, «fpred_max_label» STRING, «fpred_max_score» FLOAT, «qtl_beta» FLOAT, «qtl_se» FLOAT, «qtl_pval» FLOAT, «qtl_score» FLOAT, «interval_score» FLOAT, «qtl_score_q» FLOAT, «interval_score_q» FLOAT, «d» INT, «distance_score» FLOAT, «distance_score_q» FLOAT)

theorem eq (t0 : TableRel DISEASE_VARIANT_GENE_schema) :
    (sql%([DISEASE_VARIANT_GENE_schema]) "WITH gene_study_min AS (SELECT \"gene_id\", \"study_id\", MIN(\"pval_exponent\") AS min_exp FROM \"OPEN_TARGETS_GENETICS_2\".\"OPEN_TARGETS_GENETICS\".\"DISEASE_VARIANT_GENE\" GROUP BY \"gene_id\", \"study_id\"), top10 AS (SELECT \"gene_id\", \"study_id\", min_exp FROM gene_study_min ORDER BY min_exp ASC, \"gene_id\" ASC LIMIT 10), get_variant AS (SELECT d.\"gene_id\", d.\"study_id\", d.\"lead_chrom\" AS CHROM, d.\"lead_pos\" AS POS, d.\"lead_ref\" AS REF, d.\"lead_alt\" AS ALT, d.\"pval\", ROW_NUMBER() OVER (PARTITION BY d.\"gene_id\", d.\"study_id\" ORDER BY d.\"pval_exponent\" ASC, d.\"pval_mantissa\" ASC, d.\"lead_chrom\" ASC, d.\"lead_pos\" ASC, d.\"lead_ref\" ASC, d.\"lead_alt\" ASC) AS rn FROM \"OPEN_TARGETS_GENETICS_2\".\"OPEN_TARGETS_GENETICS\".\"DISEASE_VARIANT_GENE\" AS d INNER JOIN top10 AS t ON d.\"gene_id\" = t.\"gene_id\" AND d.\"study_id\" = t.\"study_id\") SELECT \"gene_id\", \"study_id\", CHROM, POS, REF, ALT, \"pval\" FROM get_variant WHERE rn = 1 ORDER BY \"gene_id\" ASC") t0
  = (sql%([DISEASE_VARIANT_GENE_schema]) "WITH best_per_gene_study AS (SELECT \"gene_id\", \"study_id\", MIN(\"pval_exponent\") AS min_exp FROM \"OPEN_TARGETS_GENETICS_2\".\"OPEN_TARGETS_GENETICS\".\"DISEASE_VARIANT_GENE\" GROUP BY \"gene_id\", \"study_id\"), best_mantissa AS (SELECT d.\"gene_id\", d.\"study_id\", b.min_exp, MIN(d.\"pval_mantissa\") AS min_mantissa FROM \"OPEN_TARGETS_GENETICS_2\".\"OPEN_TARGETS_GENETICS\".\"DISEASE_VARIANT_GENE\" AS d JOIN best_per_gene_study AS b ON d.\"gene_id\" = b.\"gene_id\" AND d.\"study_id\" = b.\"study_id\" AND d.\"pval_exponent\" = b.min_exp GROUP BY d.\"gene_id\", d.\"study_id\", b.min_exp), global_top10 AS (SELECT \"gene_id\", \"study_id\", min_exp, min_mantissa FROM best_mantissa ORDER BY min_exp ASC, min_mantissa ASC LIMIT 10), with_variant AS (SELECT \"gene_id\", \"study_id\", \"CHROM\", \"POS\", \"REF\", \"ALT\", \"pval\" FROM (SELECT t.\"gene_id\", t.\"study_id\", d.\"lead_chrom\" AS \"CHROM\", d.\"lead_pos\" AS \"POS\", d.\"lead_ref\" AS \"REF\", d.\"lead_alt\" AS \"ALT\", d.\"pval\", ROW_NUMBER() OVER (PARTITION BY t.\"gene_id\", t.\"study_id\" ORDER BY d.\"lead_chrom\") AS _w, d.\"lead_chrom\" FROM global_top10 AS t JOIN \"OPEN_TARGETS_GENETICS_2\".\"OPEN_TARGETS_GENETICS\".\"DISEASE_VARIANT_GENE\" AS d ON d.\"gene_id\" = t.\"gene_id\" AND d.\"study_id\" = t.\"study_id\" AND d.\"pval_exponent\" = t.min_exp AND d.\"pval_mantissa\" = t.min_mantissa) AS _t WHERE _w = 1) SELECT \"gene_id\", \"study_id\", \"CHROM\", \"POS\", \"REF\", \"ALT\", \"pval\" FROM with_variant ORDER BY \"gene_id\"") t0
  := by first | sql_equiv | sorry

end N_sf_bq325_eq_0_1
