import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_bq118_eq_0_2

CREATE TABLE DEATHRECORDS («HispanicOrigin» INT, «RaceRecode3» INT, «RaceImputationFlag» INT, «HispanicOriginRaceRecode» INT, «NumberOfRecordAxisConditions» INT, «NumberOfEntityAxisConditions» INT, «CauseRecode39» INT, «InfantCauseRecode130» INT, «CauseRecode113» INT, «CauseRecode358» INT, «PlaceOfInjury» INT, «Autopsy» STRING, «RaceRecode5» INT, «InjuryAtWork» STRING, «Id» INT, «AgeRecode27» INT, «MannerOfDeath» INT, «Education2003Revision» INT, «MethodOfDisposition» STRING, «CurrentDataYear» INT, «DayOfWeekOfDeath» INT, «ActivityCode» INT, «AgeRecode52» INT, «MaritalStatus» STRING, «AgeRecode12» INT, «PlaceOfDeathAndDecedentsStatus» INT, «InfantAgeRecode22» INT, «ResidentStatus» INT, «AgeType» INT, «Race» INT, «MonthOfDeath» INT, «Age» INT, «AgeSubstitutionFlag» INT, «BridgedRaceFlag» INT, «Icd10Code» STRING, «Sex» STRING, «Education1989Revision» INT, «EducationReportingFlag» INT)
CREATE TABLE AGERECODE12 («Code» INT, «Description» STRING)
CREATE TABLE RACE («Description» STRING, «Code» INT)
CREATE TABLE ICD10CODE («Description» STRING, «Code» STRING)

theorem eq (t0 : TableRel DEATHRECORDS_schema) (t1 : TableRel AGERECODE12_schema) (t2 : TableRel RACE_schema) (t3 : TableRel ICD10CODE_schema) :
    (sql%([DEATHRECORDS_schema, AGERECODE12_schema, RACE_schema, ICD10CODE_schema]) "WITH discharge_by_age AS (SELECT a12.\"Description\" AS age_group, a12.\"Code\" AS age_code, ROUND(CAST(CAST(COUNT(*) * 1.0 AS DOUBLE PRECISION) / COUNT(DISTINCT d.\"Icd10Code\") AS DECIMAL), 6) AS avg_deaths FROM \"DEATH\".\"DEATH\".\"DEATHRECORDS\" AS d JOIN \"DEATH\".\"DEATH\".\"ICD10CODE\" AS i ON d.\"Icd10Code\" = i.\"Code\" JOIN \"DEATH\".\"DEATH\".\"AGERECODE12\" AS a12 ON d.\"AgeRecode12\" = a12.\"Code\" WHERE d.\"Race\" = 1 AND LOWER(i.\"Description\") LIKE '%discharge%' AND NOT i.\"Description\" LIKE '%Urethral discharge%' AND NOT i.\"Description\" LIKE '%Discharge of firework%' AND NOT i.\"Description\" LIKE '%Legal intervention involving firearm discharge%' GROUP BY a12.\"Code\", a12.\"Description\"), vehicle_by_age AS (SELECT a12.\"Description\" AS age_group, a12.\"Code\" AS age_code, ROUND(CAST(CAST(COUNT(*) * 1.0 AS DOUBLE PRECISION) / COUNT(DISTINCT d.\"Icd10Code\") AS DECIMAL), 6) AS avg_deaths FROM \"DEATH\".\"DEATH\".\"DEATHRECORDS\" AS d JOIN \"DEATH\".\"DEATH\".\"ICD10CODE\" AS i ON d.\"Icd10Code\" = i.\"Code\" JOIN \"DEATH\".\"DEATH\".\"AGERECODE12\" AS a12 ON d.\"AgeRecode12\" = a12.\"Code\" WHERE d.\"Race\" = 1 AND LOWER(i.\"Description\") LIKE '%vehicle%' GROUP BY a12.\"Code\", a12.\"Description\") SELECT COALESCE(dc.age_group, vc.age_group) AS \"Age Group\", dc.avg_deaths AS \"Avg Deaths - Discharge Codes\", vc.avg_deaths AS \"Avg Deaths - Vehicle Codes\", ROUND(dc.avg_deaths - vc.avg_deaths, 6) AS \"Difference (Discharge - Vehicle)\" FROM discharge_by_age AS dc FULL OUTER JOIN vehicle_by_age AS vc ON dc.age_code = vc.age_code ORDER BY COALESCE(dc.age_code, vc.age_code)") t0 t1 t2 t3
  ~= (sql%([DEATHRECORDS_schema, AGERECODE12_schema, RACE_schema, ICD10CODE_schema]) "WITH discharge_codes AS (SELECT \"Code\" FROM \"DEATH\".\"DEATH\".\"ICD10CODE\" WHERE LOWER(\"Description\") LIKE '%discharge%' AND NOT \"Description\" LIKE '%Urethral discharge%' AND NOT \"Description\" LIKE '%Discharge of firework%' AND NOT \"Description\" LIKE '%Legal intervention involving firearm discharge%'), vehicle_codes AS (SELECT \"Code\" FROM \"DEATH\".\"DEATH\".\"ICD10CODE\" WHERE LOWER(\"Description\") LIKE '%vehicle%'), discharge_deaths AS (SELECT d.\"AgeRecode12\", d.\"Icd10Code\", COUNT(*) AS death_count FROM \"DEATH\".\"DEATH\".\"DEATHRECORDS\" AS d JOIN discharge_codes AS dc ON d.\"Icd10Code\" = dc.\"Code\" WHERE d.\"Race\" = 1 GROUP BY d.\"AgeRecode12\", d.\"Icd10Code\"), vehicle_deaths AS (SELECT d.\"AgeRecode12\", d.\"Icd10Code\", COUNT(*) AS death_count FROM \"DEATH\".\"DEATH\".\"DEATHRECORDS\" AS d JOIN vehicle_codes AS vc ON d.\"Icd10Code\" = vc.\"Code\" WHERE d.\"Race\" = 1 GROUP BY d.\"AgeRecode12\", d.\"Icd10Code\"), avg_discharge AS (SELECT \"AgeRecode12\", AVG(death_count) AS avg_deaths FROM discharge_deaths GROUP BY \"AgeRecode12\"), avg_vehicle AS (SELECT \"AgeRecode12\", AVG(death_count) AS avg_deaths FROM vehicle_deaths GROUP BY \"AgeRecode12\") SELECT ar.\"Description\" AS \"Age Group\", COALESCE(ad.avg_deaths, 0) AS \"Avg Deaths - Discharge Codes\", COALESCE(av.avg_deaths, 0) AS \"Avg Deaths - Vehicle Codes\", COALESCE(ad.avg_deaths, 0) - COALESCE(av.avg_deaths, 0) AS \"Difference (Discharge - Vehicle)\" FROM \"DEATH\".\"DEATH\".\"AGERECODE12\" AS ar LEFT JOIN avg_discharge AS ad ON ar.\"Code\" = ad.\"AgeRecode12\" LEFT JOIN avg_vehicle AS av ON ar.\"Code\" = av.\"AgeRecode12\" ORDER BY ar.\"Code\"") t0 t1 t2 t3
  := by first | sql_equiv | sorry

end N_sf_bq118_eq_0_2
