import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_bq156_eq_0_1

CREATE TABLE EBPP_ADJUSTPANCAN_ILLUMINAHISEQ_RNASEQV2_GENEXP_FILTERED («ParticipantBarcode» STRING, «SampleBarcode» STRING, «AliquotBarcode» STRING, «SampleTypeLetterCode» STRING, «SampleType» STRING, «Study» STRING, «Symbol» STRING, «Entrez» STRING, «normalized_count» FLOAT)
CREATE TABLE MC3_MAF_V5_ONE_PER_TUMOR_SAMPLE («ParticipantBarcode» STRING, «Tumor_SampleBarcode» STRING, «Tumor_AliquotBarcode» STRING, «Normal_SampleBarcode» STRING, «Normal_AliquotBarcode» STRING, «Normal_SampleTypeLetterCode» STRING, «Study» STRING, «Hugo_Symbol» STRING, «HGVSp_Short» STRING, «Variant_Classification» STRING, «HGVSc» STRING, «CENTERS» STRING, «FILTER» STRING)

theorem eq (t0 : TableRel EBPP_ADJUSTPANCAN_ILLUMINAHISEQ_RNASEQV2_GENEXP_FILTERED_schema) (t1 : TableRel MC3_MAF_V5_ONE_PER_TUMOR_SAMPLE_schema) :
    (sql%([EBPP_ADJUSTPANCAN_ILLUMINAHISEQ_RNASEQV2_GENEXP_FILTERED_schema, MC3_MAF_V5_ONE_PER_TUMOR_SAMPLE_schema]) "WITH expr /* Step 1: Get all DRG2 expression values for LGG participants */ AS (SELECT \"ParticipantBarcode\", LOG(10, \"normalized_count\" + 1) AS log_expr FROM \"PANCANCER_ATLAS_1\".\"PANCANCER_ATLAS_FILTERED\".\"EBPP_ADJUSTPANCAN_ILLUMINAHISEQ_RNASEQV2_GENEXP_FILTERED\" WHERE \"Symbol\" = 'DRG2' AND \"Study\" = 'LGG'), tp53_mutated /* Step 2: Get participants with TP53 PASS mutations in LGG */ AS (SELECT DISTINCT \"ParticipantBarcode\" FROM \"PANCANCER_ATLAS_1\".\"PANCANCER_ATLAS_FILTERED\".\"MC3_MAF_V5_ONE_PER_TUMOR_SAMPLE\" WHERE \"Hugo_Symbol\" = 'TP53' AND \"Study\" = 'LGG' AND \"FILTER\" = 'PASS'), totals /* Step 3: Compute total sums (S_total, Q_total, N_total) */ AS (SELECT COUNT(*) AS N_total, SUM(log_expr) AS S_total, SUM(log_expr * log_expr) AS Q_total FROM expr), mutated_stats /* Step 4: Compute mutated sums (S_y, Q_y, N_y) */ AS (SELECT COUNT(*) AS N_y, SUM(e.log_expr) AS S_y, SUM(e.log_expr * e.log_expr) AS Q_y FROM expr AS e INNER JOIN tp53_mutated AS m ON e.\"ParticipantBarcode\" = m.\"ParticipantBarcode\"), t_calc /* Step 5: Compute all stats and t-score */ AS (SELECT ms.N_y, ms.S_y, ms.Q_y, t.N_total - ms.N_y AS N_n, t.S_total - ms.S_y AS S_n, t.Q_total - ms.Q_y AS Q_n, CAST(ms.S_y /* Mean for mutated */ AS DOUBLE PRECISION) / ms.N_y AS g_y, CAST((t.S_total - ms.S_y) /* Mean for non-mutated */ AS DOUBLE PRECISION) / (t.N_total - ms.N_y) AS g_n, CAST((ms.Q_y - CAST((ms.S_y * ms.S_y) AS DOUBLE PRECISION) / ms.N_y) /* Variance for mutated: (Q_y - S_y^2/N_y) / (N_y - 1) */ AS DOUBLE PRECISION) / (ms.N_y - 1) AS var_y, CAST(((t.Q_total - ms.Q_y) - CAST(((t.S_total - ms.S_y) * (t.S_total - ms.S_y)) AS DOUBLE PRECISION) / (t.N_total - ms.N_y)) /* Variance for non-mutated: (Q_n - S_n^2/N_n) / (N_n - 1) */ AS DOUBLE PRECISION) / (t.N_total - ms.N_y - 1) AS var_n FROM mutated_stats AS ms CROSS JOIN totals AS t) SELECT CASE WHEN N_y >= 10 AND N_n >= 10 AND var_y > 0 AND var_n > 0 THEN ROUND(CAST(CAST((g_y - g_n) AS DOUBLE PRECISION) / SQRT(CAST(var_y AS DOUBLE PRECISION) / N_y + CAST(var_n AS DOUBLE PRECISION) / N_n) AS DECIMAL), 2) ELSE NULL END AS TSCORE FROM t_calc") t0 t1
  ~= (sql%([EBPP_ADJUSTPANCAN_ILLUMINAHISEQ_RNASEQV2_GENEXP_FILTERED_schema, MC3_MAF_V5_ONE_PER_TUMOR_SAMPLE_schema]) "WITH expr AS (SELECT r.\"ParticipantBarcode\", AVG(LOG(10, r.\"normalized_count\" + 1)) AS log_expr, CASE WHEN r.\"ParticipantBarcode\" IN (SELECT DISTINCT \"ParticipantBarcode\" FROM \"PANCANCER_ATLAS_1\".\"PANCANCER_ATLAS_FILTERED\".\"MC3_MAF_V5_ONE_PER_TUMOR_SAMPLE\" WHERE \"Hugo_Symbol\" = 'TP53' AND \"FILTER\" = 'PASS') THEN 1 ELSE 0 END AS is_mutant FROM \"PANCANCER_ATLAS_1\".\"PANCANCER_ATLAS_FILTERED\".\"EBPP_ADJUSTPANCAN_ILLUMINAHISEQ_RNASEQV2_GENEXP_FILTERED\" AS r WHERE r.\"Study\" = 'LGG' AND r.\"Symbol\" = 'DRG2' GROUP BY r.\"ParticipantBarcode\"), totals AS (SELECT SUM(log_expr) AS S, SUM(log_expr * log_expr) AS Q, COUNT(*) AS N, SUM(CASE WHEN is_mutant = 1 THEN log_expr ELSE 0 END) AS S_y, SUM(CASE WHEN is_mutant = 1 THEN log_expr * log_expr ELSE 0 END) AS Q_y, SUM(is_mutant) AS N_y FROM expr), derived AS (SELECT S_y, Q_y, N_y, S - S_y AS S_n, Q - Q_y AS Q_n, N - N_y AS N_n FROM totals), t_calc AS (SELECT CAST(S_y AS DOUBLE PRECISION) / N_y AS g_y, CAST(S_n AS DOUBLE PRECISION) / N_n AS g_n, CAST((Q_y - CAST(S_y * S_y AS DOUBLE PRECISION) / N_y) AS DOUBLE PRECISION) / (N_y - 1) AS s2_y, CAST((Q_n - CAST(S_n * S_n AS DOUBLE PRECISION) / N_n) AS DOUBLE PRECISION) / (N_n - 1) AS s2_n, N_y, N_n FROM derived WHERE N_y >= 10 AND N_n >= 10) SELECT ROUND(CAST(CAST((g_y - g_n) AS DOUBLE PRECISION) / SQRT(CAST(s2_y AS DOUBLE PRECISION) / N_y + CAST(s2_n AS DOUBLE PRECISION) / N_n) AS DECIMAL), 2) AS TSCORE FROM t_calc WHERE s2_y > 0 AND s2_n > 0") t0 t1
  := by first | sql_equiv | sorry

end N_sf_bq156_eq_0_1
