import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_bq065 — crossskill equivalence(s)

Question: From the oracle requests table, retrieve the 10 most recent oracle requests with script ID 3. For each request, extract all symbol-rate pairs by matching each symbol in the "symbols" array with its corresponding rate at the same position in the "rates" array from the decoded result. Adjust each rate by dividing it by the request's multiplier value. Return the block timestamp, oracle request ID, symbol, and the adjusted rate for each symbol-rate pair. Sort the results in chronological order with the newest records first.

NOTE: uses WITH RECURSIVE / LATERAL / FLATTEN — may not elaborate yet.

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_bq065

CREATE TABLE ORACLE_REQUESTS («block_height» INT, «block_timestamp» STRING, «block_timestamp_truncated» INT, «oracle_request_id» INT, «request» STRING, «reports» STRING, «result» STRING, «decoded_result» STRING, «oracle_script» STRING)

HYPOTHESIS hyp0_1_0 : ORACLE_REQUESTS "JSON_EXTRACT_PATH(\"request\", 'oracle_script_id') = 3"
HYPOTHESIS hyp0_1_1 : ORACLE_REQUESTS "CAST(JSON_EXTRACT_PATH(\"request\", 'oracle_script_id') AS INT) = 3"
theorem eq_0_1 (t : TableRel ORACLE_REQUESTS_schema) (h0 : hyp0_1_0 t) (h1 : hyp0_1_1 t) :
    (sql%([ORACLE_REQUESTS_schema]) "WITH top_requests AS (SELECT \"block_timestamp\", \"oracle_request_id\", \"decoded_result\" FROM \"CRYPTO\".\"CRYPTO_BAND\".\"ORACLE_REQUESTS\" WHERE JSON_EXTRACT_PATH(\"request\", 'oracle_script_id') = 3 ORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC LIMIT 10) SELECT r.\"block_timestamp\" AS BLOCK_TIMESTAMP, r.\"oracle_request_id\" AS ORACLE_REQUEST_ID, CAST(sym.VALUE AS VARCHAR) AS SYMBOL, CAST(JSON_EXTRACT_PATH(CAST(CAST(JSON_EXTRACT_PATH(r.\"decoded_result\", 'result') AS VARCHAR) AS JSON), 'rates')[sym.INDEX] AS DOUBLE PRECISION) / CAST(JSON_EXTRACT_PATH(CAST(CAST(JSON_EXTRACT_PATH(r.\"decoded_result\", 'calldata') AS VARCHAR) AS JSON), 'multiplier') AS DOUBLE PRECISION) AS ADJUSTED_RATE FROM top_requests AS r, LATERAL UNNEST(input => JSON_EXTRACT_PATH(CAST(CAST(JSON_EXTRACT_PATH(r.\"decoded_result\", 'calldata') AS VARCHAR) AS JSON), 'symbols')) AS sym(SEQ, KEY, PATH, INDEX, VALUE, THIS) ORDER BY r.\"block_timestamp\" DESC, r.\"oracle_request_id\" DESC") t = (sql%([ORACLE_REQUESTS_schema]) "WITH top_requests AS (SELECT \"block_timestamp\", \"oracle_request_id\", \"decoded_result\" FROM \"CRYPTO\".\"CRYPTO_BAND\".\"ORACLE_REQUESTS\" WHERE CAST(JSON_EXTRACT_PATH(\"request\", 'oracle_script_id') AS INT) = 3 ORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC LIMIT 10) SELECT \"block_timestamp\" AS BLOCK_TIMESTAMP, \"oracle_request_id\" AS ORACLE_REQUEST_ID, CAST(s.VALUE AS TEXT) AS SYMBOL, CAST(r.VALUE AS DOUBLE PRECISION) / CAST(JSON_EXTRACT_PATH(CAST(JSON_EXTRACT_PATH(\"decoded_result\", 'calldata') AS JSON), 'multiplier') AS DOUBLE PRECISION) AS ADJUSTED_RATE FROM top_requests, LATERAL UNNEST(input => JSON_EXTRACT_PATH(CAST(JSON_EXTRACT_PATH(\"decoded_result\", 'calldata') AS JSON), 'symbols')) AS s(SEQ, KEY, PATH, INDEX, VALUE, THIS), LATERAL UNNEST(input => JSON_EXTRACT_PATH(CAST(JSON_EXTRACT_PATH(\"decoded_result\", 'result') AS JSON), 'rates')) AS r(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE s.INDEX = r.INDEX ORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC, s.INDEX") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp0_2_0 : ORACLE_REQUESTS "JSON_EXTRACT_PATH(\"request\", 'oracle_script_id') = 3"
HYPOTHESIS hyp0_2_1 : ORACLE_REQUESTS "CAST(JSON_EXTRACT_PATH(\"request\", 'oracle_script_id') AS INT) = 3"
theorem eq_0_2 (t : TableRel ORACLE_REQUESTS_schema) (h0 : hyp0_2_0 t) (h1 : hyp0_2_1 t) :
    (sql%([ORACLE_REQUESTS_schema]) "WITH top_requests AS (SELECT \"block_timestamp\", \"oracle_request_id\", \"decoded_result\" FROM \"CRYPTO\".\"CRYPTO_BAND\".\"ORACLE_REQUESTS\" WHERE JSON_EXTRACT_PATH(\"request\", 'oracle_script_id') = 3 ORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC LIMIT 10) SELECT r.\"block_timestamp\" AS BLOCK_TIMESTAMP, r.\"oracle_request_id\" AS ORACLE_REQUEST_ID, CAST(sym.VALUE AS VARCHAR) AS SYMBOL, CAST(JSON_EXTRACT_PATH(CAST(CAST(JSON_EXTRACT_PATH(r.\"decoded_result\", 'result') AS VARCHAR) AS JSON), 'rates')[sym.INDEX] AS DOUBLE PRECISION) / CAST(JSON_EXTRACT_PATH(CAST(CAST(JSON_EXTRACT_PATH(r.\"decoded_result\", 'calldata') AS VARCHAR) AS JSON), 'multiplier') AS DOUBLE PRECISION) AS ADJUSTED_RATE FROM top_requests AS r, LATERAL UNNEST(input => JSON_EXTRACT_PATH(CAST(CAST(JSON_EXTRACT_PATH(r.\"decoded_result\", 'calldata') AS VARCHAR) AS JSON), 'symbols')) AS sym(SEQ, KEY, PATH, INDEX, VALUE, THIS) ORDER BY r.\"block_timestamp\" DESC, r.\"oracle_request_id\" DESC") t ~= (sql%([ORACLE_REQUESTS_schema]) "WITH top10 AS (SELECT \"block_timestamp\", \"oracle_request_id\", CAST(JSON_EXTRACT_PATH(\"decoded_result\", 'calldata') AS JSON) AS calldata, CAST(JSON_EXTRACT_PATH(\"decoded_result\", 'result') AS JSON) AS result_obj FROM \"CRYPTO\".\"CRYPTO_BAND\".\"ORACLE_REQUESTS\" WHERE CAST(JSON_EXTRACT_PATH(\"request\", 'oracle_script_id') AS INT) = 3 ORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC LIMIT 10) SELECT t.\"block_timestamp\" AS \"BLOCK_TIMESTAMP\", t.\"oracle_request_id\" AS \"ORACLE_REQUEST_ID\", CAST(sym.VALUE AS TEXT) AS \"SYMBOL\", CAST(rates.VALUE AS DOUBLE PRECISION) / CAST(JSON_EXTRACT_PATH(calldata, 'multiplier') AS DOUBLE PRECISION) AS \"ADJUSTED_RATE\" FROM top10 AS t, LATERAL UNNEST(input => JSON_EXTRACT_PATH(t.calldata, 'symbols')) AS sym(SEQ, KEY, PATH, INDEX, VALUE, THIS), LATERAL UNNEST(input => JSON_EXTRACT_PATH(t.result_obj, 'rates')) AS rates(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE sym.INDEX = rates.INDEX ORDER BY t.\"block_timestamp\" DESC, t.\"oracle_request_id\" DESC") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp0_3_0 : ORACLE_REQUESTS "JSON_EXTRACT_PATH(\"request\", 'oracle_script_id') = 3"
HYPOTHESIS hyp0_3_1 : ORACLE_REQUESTS "CAST(JSON_EXTRACT_PATH(\"request\", 'oracle_script_id') AS INT) = 3"
theorem eq_0_3 (t : TableRel ORACLE_REQUESTS_schema) (h0 : hyp0_3_0 t) (h1 : hyp0_3_1 t) :
    (sql%([ORACLE_REQUESTS_schema]) "WITH top_requests AS (SELECT \"block_timestamp\", \"oracle_request_id\", \"decoded_result\" FROM \"CRYPTO\".\"CRYPTO_BAND\".\"ORACLE_REQUESTS\" WHERE JSON_EXTRACT_PATH(\"request\", 'oracle_script_id') = 3 ORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC LIMIT 10) SELECT r.\"block_timestamp\" AS BLOCK_TIMESTAMP, r.\"oracle_request_id\" AS ORACLE_REQUEST_ID, CAST(sym.VALUE AS VARCHAR) AS SYMBOL, CAST(JSON_EXTRACT_PATH(CAST(CAST(JSON_EXTRACT_PATH(r.\"decoded_result\", 'result') AS VARCHAR) AS JSON), 'rates')[sym.INDEX] AS DOUBLE PRECISION) / CAST(JSON_EXTRACT_PATH(CAST(CAST(JSON_EXTRACT_PATH(r.\"decoded_result\", 'calldata') AS VARCHAR) AS JSON), 'multiplier') AS DOUBLE PRECISION) AS ADJUSTED_RATE FROM top_requests AS r, LATERAL UNNEST(input => JSON_EXTRACT_PATH(CAST(CAST(JSON_EXTRACT_PATH(r.\"decoded_result\", 'calldata') AS VARCHAR) AS JSON), 'symbols')) AS sym(SEQ, KEY, PATH, INDEX, VALUE, THIS) ORDER BY r.\"block_timestamp\" DESC, r.\"oracle_request_id\" DESC") t = (sql%([ORACLE_REQUESTS_schema]) "WITH top10_requests AS (SELECT \"oracle_request_id\", \"block_timestamp\", \"decoded_result\" FROM \"CRYPTO\".\"CRYPTO_BAND\".\"ORACLE_REQUESTS\" WHERE CAST(JSON_EXTRACT_PATH(\"request\", 'oracle_script_id') AS INT) = 3 ORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC LIMIT 10) SELECT t.\"block_timestamp\" AS BLOCK_TIMESTAMP, t.\"oracle_request_id\" AS ORACLE_REQUEST_ID, CAST(sym.VALUE AS TEXT) AS SYMBOL, CAST(JSON_EXTRACT_PATH(CAST(JSON_EXTRACT_PATH(t.\"decoded_result\", 'result') AS JSON), 'rates')[sym.INDEX] AS DOUBLE PRECISION) / CAST(JSON_EXTRACT_PATH(CAST(JSON_EXTRACT_PATH(t.\"decoded_result\", 'calldata') AS JSON), 'multiplier') AS DOUBLE PRECISION) AS ADJUSTED_RATE FROM top10_requests AS t, LATERAL UNNEST(input => JSON_EXTRACT_PATH(CAST(JSON_EXTRACT_PATH(t.\"decoded_result\", 'calldata') AS JSON), 'symbols')) AS sym(SEQ, KEY, PATH, INDEX, VALUE, THIS) ORDER BY t.\"block_timestamp\" DESC, t.\"oracle_request_id\" DESC, sym.INDEX ASC") t := by
  first | sql_equiv | sorry

theorem eq_1_2 : ∀ t,
    (sql%([ORACLE_REQUESTS_schema]) "WITH top_requests AS (SELECT \"block_timestamp\", \"oracle_request_id\", \"decoded_result\" FROM \"CRYPTO\".\"CRYPTO_BAND\".\"ORACLE_REQUESTS\" WHERE CAST(JSON_EXTRACT_PATH(\"request\", 'oracle_script_id') AS INT) = 3 ORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC LIMIT 10) SELECT \"block_timestamp\" AS BLOCK_TIMESTAMP, \"oracle_request_id\" AS ORACLE_REQUEST_ID, CAST(s.VALUE AS TEXT) AS SYMBOL, CAST(r.VALUE AS DOUBLE PRECISION) / CAST(JSON_EXTRACT_PATH(CAST(JSON_EXTRACT_PATH(\"decoded_result\", 'calldata') AS JSON), 'multiplier') AS DOUBLE PRECISION) AS ADJUSTED_RATE FROM top_requests, LATERAL UNNEST(input => JSON_EXTRACT_PATH(CAST(JSON_EXTRACT_PATH(\"decoded_result\", 'calldata') AS JSON), 'symbols')) AS s(SEQ, KEY, PATH, INDEX, VALUE, THIS), LATERAL UNNEST(input => JSON_EXTRACT_PATH(CAST(JSON_EXTRACT_PATH(\"decoded_result\", 'result') AS JSON), 'rates')) AS r(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE s.INDEX = r.INDEX ORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC, s.INDEX") t ~= (sql%([ORACLE_REQUESTS_schema]) "WITH top10 AS (SELECT \"block_timestamp\", \"oracle_request_id\", CAST(JSON_EXTRACT_PATH(\"decoded_result\", 'calldata') AS JSON) AS calldata, CAST(JSON_EXTRACT_PATH(\"decoded_result\", 'result') AS JSON) AS result_obj FROM \"CRYPTO\".\"CRYPTO_BAND\".\"ORACLE_REQUESTS\" WHERE CAST(JSON_EXTRACT_PATH(\"request\", 'oracle_script_id') AS INT) = 3 ORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC LIMIT 10) SELECT t.\"block_timestamp\" AS \"BLOCK_TIMESTAMP\", t.\"oracle_request_id\" AS \"ORACLE_REQUEST_ID\", CAST(sym.VALUE AS TEXT) AS \"SYMBOL\", CAST(rates.VALUE AS DOUBLE PRECISION) / CAST(JSON_EXTRACT_PATH(calldata, 'multiplier') AS DOUBLE PRECISION) AS \"ADJUSTED_RATE\" FROM top10 AS t, LATERAL UNNEST(input => JSON_EXTRACT_PATH(t.calldata, 'symbols')) AS sym(SEQ, KEY, PATH, INDEX, VALUE, THIS), LATERAL UNNEST(input => JSON_EXTRACT_PATH(t.result_obj, 'rates')) AS rates(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE sym.INDEX = rates.INDEX ORDER BY t.\"block_timestamp\" DESC, t.\"oracle_request_id\" DESC") t := by
  intro t; first | sql_equiv | sorry

theorem eq_1_3 :
    sql%([ORACLE_REQUESTS_schema]) "WITH top_requests AS (SELECT \"block_timestamp\", \"oracle_request_id\", \"decoded_result\" FROM \"CRYPTO\".\"CRYPTO_BAND\".\"ORACLE_REQUESTS\" WHERE CAST(JSON_EXTRACT_PATH(\"request\", 'oracle_script_id') AS INT) = 3 ORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC LIMIT 10) SELECT \"block_timestamp\" AS BLOCK_TIMESTAMP, \"oracle_request_id\" AS ORACLE_REQUEST_ID, CAST(s.VALUE AS TEXT) AS SYMBOL, CAST(r.VALUE AS DOUBLE PRECISION) / CAST(JSON_EXTRACT_PATH(CAST(JSON_EXTRACT_PATH(\"decoded_result\", 'calldata') AS JSON), 'multiplier') AS DOUBLE PRECISION) AS ADJUSTED_RATE FROM top_requests, LATERAL UNNEST(input => JSON_EXTRACT_PATH(CAST(JSON_EXTRACT_PATH(\"decoded_result\", 'calldata') AS JSON), 'symbols')) AS s(SEQ, KEY, PATH, INDEX, VALUE, THIS), LATERAL UNNEST(input => JSON_EXTRACT_PATH(CAST(JSON_EXTRACT_PATH(\"decoded_result\", 'result') AS JSON), 'rates')) AS r(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE s.INDEX = r.INDEX ORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC, s.INDEX" = sql%([ORACLE_REQUESTS_schema]) "WITH top10_requests AS (SELECT \"oracle_request_id\", \"block_timestamp\", \"decoded_result\" FROM \"CRYPTO\".\"CRYPTO_BAND\".\"ORACLE_REQUESTS\" WHERE CAST(JSON_EXTRACT_PATH(\"request\", 'oracle_script_id') AS INT) = 3 ORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC LIMIT 10) SELECT t.\"block_timestamp\" AS BLOCK_TIMESTAMP, t.\"oracle_request_id\" AS ORACLE_REQUEST_ID, CAST(sym.VALUE AS TEXT) AS SYMBOL, CAST(JSON_EXTRACT_PATH(CAST(JSON_EXTRACT_PATH(t.\"decoded_result\", 'result') AS JSON), 'rates')[sym.INDEX] AS DOUBLE PRECISION) / CAST(JSON_EXTRACT_PATH(CAST(JSON_EXTRACT_PATH(t.\"decoded_result\", 'calldata') AS JSON), 'multiplier') AS DOUBLE PRECISION) AS ADJUSTED_RATE FROM top10_requests AS t, LATERAL UNNEST(input => JSON_EXTRACT_PATH(CAST(JSON_EXTRACT_PATH(t.\"decoded_result\", 'calldata') AS JSON), 'symbols')) AS sym(SEQ, KEY, PATH, INDEX, VALUE, THIS) ORDER BY t.\"block_timestamp\" DESC, t.\"oracle_request_id\" DESC, sym.INDEX ASC" := by
  first | sql_equiv | sorry

theorem eq_2_3 : ∀ t,
    (sql%([ORACLE_REQUESTS_schema]) "WITH top10 AS (SELECT \"block_timestamp\", \"oracle_request_id\", CAST(JSON_EXTRACT_PATH(\"decoded_result\", 'calldata') AS JSON) AS calldata, CAST(JSON_EXTRACT_PATH(\"decoded_result\", 'result') AS JSON) AS result_obj FROM \"CRYPTO\".\"CRYPTO_BAND\".\"ORACLE_REQUESTS\" WHERE CAST(JSON_EXTRACT_PATH(\"request\", 'oracle_script_id') AS INT) = 3 ORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC LIMIT 10) SELECT t.\"block_timestamp\" AS \"BLOCK_TIMESTAMP\", t.\"oracle_request_id\" AS \"ORACLE_REQUEST_ID\", CAST(sym.VALUE AS TEXT) AS \"SYMBOL\", CAST(rates.VALUE AS DOUBLE PRECISION) / CAST(JSON_EXTRACT_PATH(calldata, 'multiplier') AS DOUBLE PRECISION) AS \"ADJUSTED_RATE\" FROM top10 AS t, LATERAL UNNEST(input => JSON_EXTRACT_PATH(t.calldata, 'symbols')) AS sym(SEQ, KEY, PATH, INDEX, VALUE, THIS), LATERAL UNNEST(input => JSON_EXTRACT_PATH(t.result_obj, 'rates')) AS rates(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE sym.INDEX = rates.INDEX ORDER BY t.\"block_timestamp\" DESC, t.\"oracle_request_id\" DESC") t ~= (sql%([ORACLE_REQUESTS_schema]) "WITH top10_requests AS (SELECT \"oracle_request_id\", \"block_timestamp\", \"decoded_result\" FROM \"CRYPTO\".\"CRYPTO_BAND\".\"ORACLE_REQUESTS\" WHERE CAST(JSON_EXTRACT_PATH(\"request\", 'oracle_script_id') AS INT) = 3 ORDER BY \"block_timestamp\" DESC, \"oracle_request_id\" DESC LIMIT 10) SELECT t.\"block_timestamp\" AS BLOCK_TIMESTAMP, t.\"oracle_request_id\" AS ORACLE_REQUEST_ID, CAST(sym.VALUE AS TEXT) AS SYMBOL, CAST(JSON_EXTRACT_PATH(CAST(JSON_EXTRACT_PATH(t.\"decoded_result\", 'result') AS JSON), 'rates')[sym.INDEX] AS DOUBLE PRECISION) / CAST(JSON_EXTRACT_PATH(CAST(JSON_EXTRACT_PATH(t.\"decoded_result\", 'calldata') AS JSON), 'multiplier') AS DOUBLE PRECISION) AS ADJUSTED_RATE FROM top10_requests AS t, LATERAL UNNEST(input => JSON_EXTRACT_PATH(CAST(JSON_EXTRACT_PATH(t.\"decoded_result\", 'calldata') AS JSON), 'symbols')) AS sym(SEQ, KEY, PATH, INDEX, VALUE, THIS) ORDER BY t.\"block_timestamp\" DESC, t.\"oracle_request_id\" DESC, sym.INDEX ASC") t := by
  intro t; first | sql_equiv | sorry

end Bench_sf_bq065
