import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_bq105_eq_1_2

CREATE TABLE POPULATION_BY_ZIP_2000 («zipcode» STRING, «geo_id» STRING, «minimum_age» INT, «maximum_age» INT, «gender» STRING, «population» INT)
CREATE TABLE DISTRACT_2016 («state_number» INT, «state_name» STRING, «consecutive_number» INT, «vehicle_number» INT, «driver_distracted_by» INT, «driver_distracted_by_name» STRING)
CREATE TABLE ACCIDENT_2015 («state_number» INT, «state_name» STRING, «consecutive_number» INT, «number_of_vehicle_forms_submitted_all» INT, «number_of_motor_vehicles_in_transport_mvit» INT, «number_of_parked_working_vehicles» INT, «number_of_forms_submitted_for_persons_not_in_motor_vehicles» INT, «number_of_persons_not_in_motor_vehicles_in_transport_mvit» INT, «number_of_persons_in_motor_vehicles_in_transport_mvit» INT, «number_of_forms_submitted_for_persons_in_motor_vehicles» INT, «county» INT, «city» INT, «day_of_crash» INT, «month_of_crash» INT, «year_of_crash» INT, «day_of_week» INT, «hour_of_crash» INT, «minute_of_crash» INT, «national_highway_system» INT, «land_use» INT, «land_use_name» STRING, «functional_system» INT, «functional_system_name» STRING, «ownership» INT, «ownership_name» STRING, «route_signing» INT, «route_signing_name» STRING, «trafficway_identifier» STRING, «trafficway_identifier_2» STRING, «milepoint» INT, «latitude» FLOAT, «longitude» FLOAT, «special_jurisdiction» INT, «special_jurisdiction_name» STRING, «first_harmful_event» INT, «first_harmful_event_name» STRING, «manner_of_collision» INT, «manner_of_collision_name» STRING, «relation_to_junction_within_interchange_area» STRING, «relation_to_junction_specific_location» INT, «relation_to_junction_specific_location_name» STRING, «type_of_intersection» STRING, «work_zone» STRING, «relation_to_trafficway» INT, «relation_to_trafficway_name» STRING, «light_condition» INT, «light_condition_name» STRING, «atmospheric_conditions_1» INT, «atmospheric_conditions_1_name» STRING, «atmospheric_conditions_2» INT, «atmospheric_conditions_2_name» STRING, «atmospheric_conditions» INT, «atmospheric_conditions_name» STRING, «school_bus_related» STRING, «rail_grade_crossing_identifier» STRING, «hour_of_notification» INT, «minute_of_notification» INT, «hour_of_arrival_at_scene» INT, «minute_of_arrival_at_scene» INT, «hour_of_ems_arrival_at_hospital» INT, «minute_of_ems_arrival_at_hospital» INT, «related_factors_crash_level_1» INT, «related_factors_crash_level_1_name» STRING, «related_factors_crash_level_2» INT, «related_factors_crash_level_2_name» STRING, «related_factors_crash_level_3» INT, «related_factors_crash_level_3_name» STRING, «number_of_fatalities» INT, «number_of_drunk_drivers» INT, «timestamp_of_crash» INT)
CREATE TABLE DISTRACT_2015 («state_number» INT, «consecutive_number» INT, «vehicle_number» INT, «driver_distracted_by» INT, «driver_distracted_by_name» STRING)
CREATE TABLE ACCIDENT_2016 («state_number» INT, «state_name» STRING, «consecutive_number» INT, «number_of_vehicle_forms_submitted_all» INT, «number_of_motor_vehicles_in_transport_mvit» INT, «number_of_parked_working_vehicles» INT, «number_of_forms_submitted_for_persons_not_in_motor_vehicles» INT, «number_of_persons_not_in_motor_vehicles_in_transport_mvit» INT, «number_of_persons_in_motor_vehicles_in_transport_mvit» INT, «number_of_forms_submitted_for_persons_in_motor_vehicles» INT, «county» INT, «city» INT, «day_of_crash» INT, «month_of_crash» INT, «year_of_crash» INT, «day_of_week» INT, «hour_of_crash» INT, «minute_of_crash» INT, «national_highway_system» INT, «land_use» INT, «land_use_name» STRING, «functional_system» INT, «functional_system_name» STRING, «ownership» INT, «ownership_name» STRING, «route_signing» INT, «route_signing_name» STRING, «trafficway_identifier» STRING, «trafficway_identifier_2» STRING, «milepoint» INT, «latitude» FLOAT, «longitude» FLOAT, «special_jurisdiction» INT, «special_jurisdiction_name» STRING, «first_harmful_event» INT, «first_harmful_event_name» STRING, «manner_of_collision» INT, «manner_of_collision_name» STRING, «relation_to_junction_within_interchange_area» STRING, «relation_to_junction_specific_location» INT, «relation_to_junction_specific_location_name» STRING, «type_of_intersection» STRING, «work_zone» STRING, «relation_to_trafficway» INT, «relation_to_trafficway_name» STRING, «light_condition» INT, «light_condition_name» STRING, «atmospheric_conditions_1» INT, «atmospheric_conditions_1_name» STRING, «atmospheric_conditions_2» INT, «atmospheric_conditions_2_name» STRING, «atmospheric_conditions» INT, «atmospheric_conditions_name» STRING, «school_bus_related» STRING, «rail_grade_crossing_identifier» STRING, «hour_of_notification» INT, «minute_of_notification» INT, «hour_of_arrival_at_scene» INT, «minute_of_arrival_at_scene» INT, «hour_of_ems_arrival_at_hospital» INT, «minute_of_ems_arrival_at_hospital» INT, «related_factors_crash_level_1» INT, «related_factors_crash_level_1_name» STRING, «related_factors_crash_level_2» INT, «related_factors_crash_level_2_name» STRING, «related_factors_crash_level_3» INT, «related_factors_crash_level_3_name» STRING, «number_of_fatalities» INT, «number_of_drunk_drivers» INT, «timestamp_of_crash» INT)
CREATE TABLE ZIPCODE_AREA («zipcode» STRING, «area_land_meters» INT, «area_water_meters» INT, «area_land_miles» FLOAT, «area_water_miles» FLOAT, «latitude» FLOAT, «longitude» FLOAT, «state_code» STRING, «state_name» STRING, «city» STRING, «county» STRING, «state_fips» STRING, «zipcode_geom» STRING)

theorem eq (t0 : TableRel POPULATION_BY_ZIP_2000_schema) (t1 : TableRel DISTRACT_2016_schema) (t2 : TableRel ACCIDENT_2015_schema) (t3 : TableRel DISTRACT_2015_schema) (t4 : TableRel ACCIDENT_2016_schema) (t5 : TableRel ZIPCODE_AREA_schema) :
    (sql%([POPULATION_BY_ZIP_2000_schema, DISTRACT_2016_schema, ACCIDENT_2015_schema, DISTRACT_2015_schema, ACCIDENT_2016_schema, ZIPCODE_AREA_schema]) "WITH state_population AS (SELECT z.\"state_name\", SUM(p.\"population\") AS population_2010 FROM \"NHTSA_TRAFFIC_FATALITIES_PLUS\".\"CENSUS_BUREAU_USA\".\"POPULATION_BY_ZIP_2000\" AS p JOIN \"NHTSA_TRAFFIC_FATALITIES_PLUS\".\"UTILITY_US\".\"ZIPCODE_AREA\" AS z ON p.\"zipcode\" = z.\"zipcode\" WHERE p.\"gender\" = '' AND p.\"minimum_age\" IS NULL AND p.\"maximum_age\" IS NULL AND NOT z.\"state_name\" LIKE '%,%' GROUP BY z.\"state_name\"), distracted_accidents AS (SELECT a.\"state_name\", 2015 AS year, COUNT(DISTINCT d.\"consecutive_number\") AS accidents FROM \"NHTSA_TRAFFIC_FATALITIES_PLUS\".\"NHTSA_TRAFFIC_FATALITIES\".\"DISTRACT_2015\" AS d JOIN \"NHTSA_TRAFFIC_FATALITIES_PLUS\".\"NHTSA_TRAFFIC_FATALITIES\".\"ACCIDENT_2015\" AS a ON d.\"state_number\" = a.\"state_number\" AND d.\"consecutive_number\" = a.\"consecutive_number\" WHERE NOT d.\"driver_distracted_by_name\" IN ('Not Distracted', 'Unknown if Distracted', 'Not Reported') GROUP BY a.\"state_name\" UNION ALL SELECT a.\"state_name\", 2016 AS year, COUNT(DISTINCT d.\"consecutive_number\") AS accidents FROM \"NHTSA_TRAFFIC_FATALITIES_PLUS\".\"NHTSA_TRAFFIC_FATALITIES\".\"DISTRACT_2016\" AS d JOIN \"NHTSA_TRAFFIC_FATALITIES_PLUS\".\"NHTSA_TRAFFIC_FATALITIES\".\"ACCIDENT_2016\" AS a ON d.\"state_number\" = a.\"state_number\" AND d.\"consecutive_number\" = a.\"consecutive_number\" WHERE NOT d.\"driver_distracted_by_name\" IN ('Not Distracted', 'Unknown if Distracted', 'Not Reported') GROUP BY a.\"state_name\"), ranked AS (SELECT da.year, da.\"state_name\", da.accidents, sp.population_2010, ROUND(CAST(da.accidents AS DOUBLE PRECISION) / sp.population_2010 * 100000, 1) AS accidents_per_100k, RANK() OVER (PARTITION BY da.year ORDER BY ROUND(CAST(da.accidents AS DOUBLE PRECISION) / sp.population_2010 * 100000, 1) DESC) AS year_rank FROM distracted_accidents AS da JOIN state_population AS sp ON da.\"state_name\" = sp.\"state_name\") SELECT year, \"state_name\", accidents, population_2010, accidents_per_100k, year_rank FROM ranked WHERE year_rank <= 5 ORDER BY year, year_rank") t0 t1 t2 t3 t4 t5
  = (sql%([POPULATION_BY_ZIP_2000_schema, DISTRACT_2016_schema, ACCIDENT_2015_schema, DISTRACT_2015_schema, ACCIDENT_2016_schema, ZIPCODE_AREA_schema]) "WITH state_pop AS (SELECT us.\"state_name\", SUM(p.\"population\") AS \"POPULATION_2010\" FROM \"NHTSA_TRAFFIC_FATALITIES_PLUS\".\"CENSUS_BUREAU_USA\".\"POPULATION_BY_ZIP_2000\" AS p JOIN \"NHTSA_TRAFFIC_FATALITIES_PLUS\".\"UTILITY_US\".\"ZIPCODE_AREA\" AS z ON p.\"zipcode\" = z.\"zipcode\" JOIN \"NHTSA_TRAFFIC_FATALITIES_PLUS\".\"UTILITY_US\".\"US_STATES_AREA\" AS us ON z.\"state_code\" = us.\"state_abbreviation\" WHERE p.\"minimum_age\" IS NULL AND p.\"gender\" = '' GROUP BY us.\"state_name\"), accidents_2015 AS (SELECT 2015 AS \"YEAR\", a.\"state_name\", COUNT(DISTINCT d.\"consecutive_number\") AS \"ACCIDENTS\" FROM \"NHTSA_TRAFFIC_FATALITIES_PLUS\".\"NHTSA_TRAFFIC_FATALITIES\".\"DISTRACT_2015\" AS d JOIN \"NHTSA_TRAFFIC_FATALITIES_PLUS\".\"NHTSA_TRAFFIC_FATALITIES\".\"ACCIDENT_2015\" AS a ON d.\"consecutive_number\" = a.\"consecutive_number\" WHERE NOT d.\"driver_distracted_by_name\" IN ('Not Distracted', 'Not Reported', 'Unknown if Distracted') GROUP BY a.\"state_name\"), accidents_2016 AS (SELECT 2016 AS \"YEAR\", a.\"state_name\", COUNT(DISTINCT d.\"consecutive_number\") AS \"ACCIDENTS\" FROM \"NHTSA_TRAFFIC_FATALITIES_PLUS\".\"NHTSA_TRAFFIC_FATALITIES\".\"DISTRACT_2016\" AS d JOIN \"NHTSA_TRAFFIC_FATALITIES_PLUS\".\"NHTSA_TRAFFIC_FATALITIES\".\"ACCIDENT_2016\" AS a ON d.\"consecutive_number\" = a.\"consecutive_number\" WHERE NOT d.\"driver_distracted_by_name\" IN ('Not Distracted', 'Not Reported', 'Unknown if Distracted') GROUP BY a.\"state_name\"), all_accidents AS (SELECT * FROM accidents_2015 UNION ALL SELECT * FROM accidents_2016), ranked AS (SELECT acc.\"YEAR\", acc.\"state_name\", acc.\"ACCIDENTS\", sp.\"POPULATION_2010\", ROUND(CAST(acc.\"ACCIDENTS\" * 100000.0 AS DOUBLE PRECISION) / sp.\"POPULATION_2010\", 1) AS \"ACCIDENTS_PER_100K\", ROW_NUMBER() OVER (PARTITION BY acc.\"YEAR\" ORDER BY CAST(acc.\"ACCIDENTS\" * 100000.0 AS DOUBLE PRECISION) / sp.\"POPULATION_2010\" DESC) AS \"YEAR_RANK\" FROM all_accidents AS acc JOIN state_pop AS sp ON acc.\"state_name\" = sp.\"state_name\") SELECT \"YEAR\", \"state_name\", \"ACCIDENTS\", \"POPULATION_2010\", \"ACCIDENTS_PER_100K\", \"YEAR_RANK\" FROM ranked WHERE \"YEAR_RANK\" <= 5 ORDER BY \"YEAR\", \"YEAR_RANK\"") t0 t1 t2 t3 t4 t5
  := by first | sql_equiv | sorry

end N_sf_bq105_eq_1_2
