import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_bq021_eq_0_1

CREATE TABLE CITIBIKE_TRIPS («tripduration» INT, «starttime» INT, «stoptime» INT, «start_station_id» INT, «start_station_name» STRING, «start_station_latitude» FLOAT, «start_station_longitude» FLOAT, «end_station_id» INT, «end_station_name» STRING, «end_station_latitude» FLOAT, «end_station_longitude» FLOAT, «bikeid» INT, «usertype» STRING, «birth_year» INT, «gender» STRING)
CREATE TABLE TLC_YELLOW_TRIPS_2016 («vendor_id» STRING, «pickup_datetime» INT, «dropoff_datetime» INT, «passenger_count» INT, «trip_distance» FLOAT, «pickup_longitude» FLOAT, «pickup_latitude» FLOAT, «rate_code» INT, «store_and_fwd_flag» STRING, «dropoff_longitude» FLOAT, «dropoff_latitude» FLOAT, «payment_type» STRING, «fare_amount» FLOAT, «extra» FLOAT, «mta_tax» FLOAT, «tip_amount» FLOAT, «tolls_amount» FLOAT, «imp_surcharge» FLOAT, «total_amount» FLOAT)

theorem eq (t0 : TableRel CITIBIKE_TRIPS_schema) (t1 : TableRel TLC_YELLOW_TRIPS_2016_schema) :
    (sql%([CITIBIKE_TRIPS_schema, TLC_YELLOW_TRIPS_2016_schema]) "WITH bike_routes_2016 AS (SELECT \"start_station_name\", \"end_station_name\", ROUND(\"start_station_latitude\", 3) AS start_lat, ROUND(\"start_station_longitude\", 3) AS start_lon, ROUND(\"end_station_latitude\", 3) AS end_lat, ROUND(\"end_station_longitude\", 3) AS end_lon, COUNT(*) AS bike_trip_count, AVG(\"tripduration\") AS avg_bike_duration FROM \"NEW_YORK\".\"NEW_YORK\".\"CITIBIKE_TRIPS\" WHERE EXTRACT(YEAR FROM TO_TIMESTAMP(CAST(\"starttime\" AS DOUBLE PRECISION) / 1000000)) = 2016 GROUP BY \"start_station_name\", \"end_station_name\", ROUND(\"start_station_latitude\", 3), ROUND(\"start_station_longitude\", 3), ROUND(\"end_station_latitude\", 3), ROUND(\"end_station_longitude\", 3) ORDER BY bike_trip_count DESC LIMIT 20), taxi_routes AS (SELECT ROUND(\"pickup_latitude\", 3) AS start_lat, ROUND(\"pickup_longitude\", 3) AS start_lon, ROUND(\"dropoff_latitude\", 3) AS end_lat, ROUND(\"dropoff_longitude\", 3) AS end_lon, AVG(CAST((\"dropoff_datetime\" - \"pickup_datetime\") AS DOUBLE PRECISION) / 1000000) AS avg_taxi_duration FROM \"NEW_YORK\".\"NEW_YORK\".\"TLC_YELLOW_TRIPS_2016\" GROUP BY ROUND(\"pickup_latitude\", 3), ROUND(\"pickup_longitude\", 3), ROUND(\"dropoff_latitude\", 3), ROUND(\"dropoff_longitude\", 3)), bike_faster AS (SELECT b.\"start_station_name\", b.avg_bike_duration FROM bike_routes_2016 AS b INNER JOIN taxi_routes AS t ON b.start_lat = t.start_lat AND b.start_lon = t.start_lon AND b.end_lat = t.end_lat AND b.end_lon = t.end_lon WHERE b.avg_bike_duration < t.avg_taxi_duration) SELECT \"start_station_name\" AS OUTPUT FROM bike_faster ORDER BY avg_bike_duration DESC LIMIT 1") t0 t1
  = (sql%([CITIBIKE_TRIPS_schema, TLC_YELLOW_TRIPS_2016_schema]) "WITH bike_routes AS (SELECT \"start_station_name\", \"end_station_name\", ROUND(\"start_station_latitude\", 3) AS start_lat, ROUND(\"start_station_longitude\", 3) AS start_lon, ROUND(\"end_station_latitude\", 3) AS end_lat, ROUND(\"end_station_longitude\", 3) AS end_lon, COUNT(*) AS bike_trip_count, AVG(\"tripduration\") AS avg_bike_duration FROM \"NEW_YORK\".\"NEW_YORK\".\"CITIBIKE_TRIPS\" WHERE \"starttime\" >= 1451606400000000 AND \"starttime\" < 1483228800000000 GROUP BY \"start_station_name\", \"end_station_name\", ROUND(\"start_station_latitude\", 3), ROUND(\"start_station_longitude\", 3), ROUND(\"end_station_latitude\", 3), ROUND(\"end_station_longitude\", 3) ORDER BY bike_trip_count DESC LIMIT 20), taxi_routes AS (SELECT ROUND(\"pickup_latitude\", 3) AS start_lat, ROUND(\"pickup_longitude\", 3) AS start_lon, ROUND(\"dropoff_latitude\", 3) AS end_lat, ROUND(\"dropoff_longitude\", 3) AS end_lon, COUNT(*) AS taxi_trip_count, AVG(CAST((\"dropoff_datetime\" - \"pickup_datetime\") AS DOUBLE PRECISION) / 1000000) AS avg_taxi_duration FROM \"NEW_YORK\".\"NEW_YORK\".\"TLC_YELLOW_TRIPS_2016\" GROUP BY ROUND(\"pickup_latitude\", 3), ROUND(\"pickup_longitude\", 3), ROUND(\"dropoff_latitude\", 3), ROUND(\"dropoff_longitude\", 3)) SELECT b.\"start_station_name\" AS OUTPUT FROM bike_routes AS b INNER JOIN taxi_routes AS t ON b.start_lat = t.start_lat AND b.start_lon = t.start_lon AND b.end_lat = t.end_lat AND b.end_lon = t.end_lon WHERE b.avg_bike_duration < t.avg_taxi_duration ORDER BY b.avg_bike_duration DESC LIMIT 1") t0 t1
  := by first | sql_equiv | sorry

end N_sf_bq021_eq_0_1
