import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_bq362 — crossskill equivalence(s)

Question: Which three companies had the largest increase in trip numbers between two consecutive months in 2018?

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_bq362

CREATE TABLE TAXI_TRIPS («unique_key» STRING, «taxi_id» STRING, «trip_start_timestamp» INT, «trip_end_timestamp» INT, «trip_seconds» INT, «trip_miles» FLOAT, «pickup_census_tract» INT, «dropoff_census_tract» INT, «pickup_community_area» INT, «dropoff_community_area» INT, «fare» FLOAT, «tips» FLOAT, «tolls» FLOAT, «extras» FLOAT, «trip_total» FLOAT, «payment_type» STRING, «company» STRING, «pickup_latitude» FLOAT, «pickup_longitude» FLOAT, «pickup_location» STRING, «dropoff_latitude» FLOAT, «dropoff_longitude» FLOAT, «dropoff_location» STRING)

theorem eq_0_1 :
    sql%([TAXI_TRIPS_schema]) "WITH monthly_counts AS (SELECT \"company\", EXTRACT(MONTH FROM TO_TIMESTAMP(CAST(\"trip_start_timestamp\" AS DOUBLE PRECISION) / 1000000)) AS trip_month, COUNT(*) AS trip_count FROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\" WHERE EXTRACT(YEAR FROM TO_TIMESTAMP(CAST(\"trip_start_timestamp\" AS DOUBLE PRECISION) / 1000000)) = 2018 GROUP BY \"company\", trip_month), month_over_month AS (SELECT curr.\"company\", curr.trip_count - prev.trip_count AS trip_increase FROM monthly_counts AS curr JOIN monthly_counts AS prev ON curr.\"company\" = prev.\"company\" AND curr.trip_month = prev.trip_month + 1), company_max_increase AS (SELECT \"company\", MAX(trip_increase) AS max_increase FROM month_over_month GROUP BY \"company\") SELECT \"company\" AS \"COMPANY\" FROM company_max_increase ORDER BY max_increase DESC LIMIT 3" = sql%([TAXI_TRIPS_schema]) "WITH monthly_trips AS (SELECT \"company\", EXTRACT(MONTH FROM TO_TIMESTAMP(CAST(\"trip_start_timestamp\" AS DOUBLE PRECISION) / 1000000)) AS month, COUNT(*) AS trip_count FROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\" WHERE EXTRACT(YEAR FROM TO_TIMESTAMP(CAST(\"trip_start_timestamp\" AS DOUBLE PRECISION) / 1000000)) = 2018 GROUP BY \"company\", month), increases AS (SELECT cur.\"company\", cur.trip_count - prev.trip_count AS increase FROM monthly_trips AS cur JOIN monthly_trips AS prev ON cur.\"company\" = prev.\"company\" AND cur.month = prev.month + 1) SELECT \"company\" AS COMPANY FROM increases GROUP BY \"company\" ORDER BY MAX(increase) DESC LIMIT 3" := by
  first | sql_equiv | sorry

HYPOTHESIS hyp0_2_0 : TAXI_TRIPS "EXTRACT(YEAR FROM TO_TIMESTAMP(CAST(\"trip_start_timestamp\" AS DOUBLE PRECISION) / 1000000)) = 2018"
HYPOTHESIS hyp0_2_1 : TAXI_TRIPS "\"trip_start_timestamp\" >= 1514764800000000 /* 2018-01-01 */"
HYPOTHESIS hyp0_2_2 : TAXI_TRIPS "\"trip_start_timestamp\" < 1546300800000000 /* 2019-01-01 */"
HYPOTHESIS hyp0_2_3 : TAXI_TRIPS "NOT \"company\" IS NULL"
theorem eq_0_2 (t : TableRel TAXI_TRIPS_schema) (h0 : hyp0_2_0 t) (h1 : hyp0_2_1 t) (h2 : hyp0_2_2 t) (h3 : hyp0_2_3 t) :
    (sql%([TAXI_TRIPS_schema]) "WITH monthly_counts AS (SELECT \"company\", EXTRACT(MONTH FROM TO_TIMESTAMP(CAST(\"trip_start_timestamp\" AS DOUBLE PRECISION) / 1000000)) AS trip_month, COUNT(*) AS trip_count FROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\" WHERE EXTRACT(YEAR FROM TO_TIMESTAMP(CAST(\"trip_start_timestamp\" AS DOUBLE PRECISION) / 1000000)) = 2018 GROUP BY \"company\", trip_month), month_over_month AS (SELECT curr.\"company\", curr.trip_count - prev.trip_count AS trip_increase FROM monthly_counts AS curr JOIN monthly_counts AS prev ON curr.\"company\" = prev.\"company\" AND curr.trip_month = prev.trip_month + 1), company_max_increase AS (SELECT \"company\", MAX(trip_increase) AS max_increase FROM month_over_month GROUP BY \"company\") SELECT \"company\" AS \"COMPANY\" FROM company_max_increase ORDER BY max_increase DESC LIMIT 3") t = (sql%([TAXI_TRIPS_schema]) "WITH monthly_trips AS (SELECT \"company\" AS COMPANY, EXTRACT(MONTH FROM TO_TIMESTAMP(CAST(\"trip_start_timestamp\" AS DOUBLE PRECISION) / 1000000)) AS trip_month, COUNT(*) AS trip_count FROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\" WHERE \"trip_start_timestamp\" >= 1514764800000000 /* 2018-01-01 */ AND \"trip_start_timestamp\" < 1546300800000000 /* 2019-01-01 */ AND NOT \"company\" IS NULL GROUP BY \"company\", EXTRACT(MONTH FROM TO_TIMESTAMP(CAST(\"trip_start_timestamp\" AS DOUBLE PRECISION) / 1000000))), consecutive_increase AS (SELECT COMPANY, trip_month, trip_count, trip_count - LAG(trip_count) OVER (PARTITION BY COMPANY ORDER BY trip_month) AS increase FROM monthly_trips) SELECT COMPANY FROM consecutive_increase WHERE NOT increase IS NULL ORDER BY increase DESC LIMIT 3") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp0_3_0 : TAXI_TRIPS "NOT \"company\" IS NULL"
theorem eq_0_3 (t : TableRel TAXI_TRIPS_schema) (h0 : hyp0_3_0 t) :
    (sql%([TAXI_TRIPS_schema]) "WITH monthly_counts AS (SELECT \"company\", EXTRACT(MONTH FROM TO_TIMESTAMP(CAST(\"trip_start_timestamp\" AS DOUBLE PRECISION) / 1000000)) AS trip_month, COUNT(*) AS trip_count FROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\" WHERE EXTRACT(YEAR FROM TO_TIMESTAMP(CAST(\"trip_start_timestamp\" AS DOUBLE PRECISION) / 1000000)) = 2018 GROUP BY \"company\", trip_month), month_over_month AS (SELECT curr.\"company\", curr.trip_count - prev.trip_count AS trip_increase FROM monthly_counts AS curr JOIN monthly_counts AS prev ON curr.\"company\" = prev.\"company\" AND curr.trip_month = prev.trip_month + 1), company_max_increase AS (SELECT \"company\", MAX(trip_increase) AS max_increase FROM month_over_month GROUP BY \"company\") SELECT \"company\" AS \"COMPANY\" FROM company_max_increase ORDER BY max_increase DESC LIMIT 3") t = (sql%([TAXI_TRIPS_schema]) "WITH monthly_trips AS (SELECT \"company\", EXTRACT(MONTH FROM TO_TIMESTAMP(CAST(\"trip_start_timestamp\" AS DOUBLE PRECISION) / 1000000)) AS month, COUNT(*) AS trip_count FROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\" WHERE NOT \"company\" IS NULL AND EXTRACT(YEAR FROM TO_TIMESTAMP(CAST(\"trip_start_timestamp\" AS DOUBLE PRECISION) / 1000000)) = 2018 GROUP BY \"company\", month), monthly_with_lag AS (SELECT \"company\", month, trip_count, LAG(trip_count) OVER (PARTITION BY \"company\" ORDER BY month) AS prev_month_count FROM monthly_trips), increases AS (SELECT \"company\", month, trip_count, prev_month_count, trip_count - prev_month_count AS increase FROM monthly_with_lag WHERE NOT prev_month_count IS NULL) SELECT \"company\" FROM increases ORDER BY increase DESC LIMIT 3") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp1_2_0 : TAXI_TRIPS "EXTRACT(YEAR FROM TO_TIMESTAMP(CAST(\"trip_start_timestamp\" AS DOUBLE PRECISION) / 1000000)) = 2018"
HYPOTHESIS hyp1_2_1 : TAXI_TRIPS "\"trip_start_timestamp\" >= 1514764800000000 /* 2018-01-01 */"
HYPOTHESIS hyp1_2_2 : TAXI_TRIPS "\"trip_start_timestamp\" < 1546300800000000 /* 2019-01-01 */"
HYPOTHESIS hyp1_2_3 : TAXI_TRIPS "NOT \"company\" IS NULL"
theorem eq_1_2 (t : TableRel TAXI_TRIPS_schema) (h0 : hyp1_2_0 t) (h1 : hyp1_2_1 t) (h2 : hyp1_2_2 t) (h3 : hyp1_2_3 t) :
    (sql%([TAXI_TRIPS_schema]) "WITH monthly_trips AS (SELECT \"company\", EXTRACT(MONTH FROM TO_TIMESTAMP(CAST(\"trip_start_timestamp\" AS DOUBLE PRECISION) / 1000000)) AS month, COUNT(*) AS trip_count FROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\" WHERE EXTRACT(YEAR FROM TO_TIMESTAMP(CAST(\"trip_start_timestamp\" AS DOUBLE PRECISION) / 1000000)) = 2018 GROUP BY \"company\", month), increases AS (SELECT cur.\"company\", cur.trip_count - prev.trip_count AS increase FROM monthly_trips AS cur JOIN monthly_trips AS prev ON cur.\"company\" = prev.\"company\" AND cur.month = prev.month + 1) SELECT \"company\" AS COMPANY FROM increases GROUP BY \"company\" ORDER BY MAX(increase) DESC LIMIT 3") t = (sql%([TAXI_TRIPS_schema]) "WITH monthly_trips AS (SELECT \"company\" AS COMPANY, EXTRACT(MONTH FROM TO_TIMESTAMP(CAST(\"trip_start_timestamp\" AS DOUBLE PRECISION) / 1000000)) AS trip_month, COUNT(*) AS trip_count FROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\" WHERE \"trip_start_timestamp\" >= 1514764800000000 /* 2018-01-01 */ AND \"trip_start_timestamp\" < 1546300800000000 /* 2019-01-01 */ AND NOT \"company\" IS NULL GROUP BY \"company\", EXTRACT(MONTH FROM TO_TIMESTAMP(CAST(\"trip_start_timestamp\" AS DOUBLE PRECISION) / 1000000))), consecutive_increase AS (SELECT COMPANY, trip_month, trip_count, trip_count - LAG(trip_count) OVER (PARTITION BY COMPANY ORDER BY trip_month) AS increase FROM monthly_trips) SELECT COMPANY FROM consecutive_increase WHERE NOT increase IS NULL ORDER BY increase DESC LIMIT 3") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp1_3_0 : TAXI_TRIPS "NOT \"company\" IS NULL"
theorem eq_1_3 (t : TableRel TAXI_TRIPS_schema) (h0 : hyp1_3_0 t) :
    (sql%([TAXI_TRIPS_schema]) "WITH monthly_trips AS (SELECT \"company\", EXTRACT(MONTH FROM TO_TIMESTAMP(CAST(\"trip_start_timestamp\" AS DOUBLE PRECISION) / 1000000)) AS month, COUNT(*) AS trip_count FROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\" WHERE EXTRACT(YEAR FROM TO_TIMESTAMP(CAST(\"trip_start_timestamp\" AS DOUBLE PRECISION) / 1000000)) = 2018 GROUP BY \"company\", month), increases AS (SELECT cur.\"company\", cur.trip_count - prev.trip_count AS increase FROM monthly_trips AS cur JOIN monthly_trips AS prev ON cur.\"company\" = prev.\"company\" AND cur.month = prev.month + 1) SELECT \"company\" AS COMPANY FROM increases GROUP BY \"company\" ORDER BY MAX(increase) DESC LIMIT 3") t = (sql%([TAXI_TRIPS_schema]) "WITH monthly_trips AS (SELECT \"company\", EXTRACT(MONTH FROM TO_TIMESTAMP(CAST(\"trip_start_timestamp\" AS DOUBLE PRECISION) / 1000000)) AS month, COUNT(*) AS trip_count FROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\" WHERE NOT \"company\" IS NULL AND EXTRACT(YEAR FROM TO_TIMESTAMP(CAST(\"trip_start_timestamp\" AS DOUBLE PRECISION) / 1000000)) = 2018 GROUP BY \"company\", month), monthly_with_lag AS (SELECT \"company\", month, trip_count, LAG(trip_count) OVER (PARTITION BY \"company\" ORDER BY month) AS prev_month_count FROM monthly_trips), increases AS (SELECT \"company\", month, trip_count, prev_month_count, trip_count - prev_month_count AS increase FROM monthly_with_lag WHERE NOT prev_month_count IS NULL) SELECT \"company\" FROM increases ORDER BY increase DESC LIMIT 3") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp2_3_0 : TAXI_TRIPS "\"trip_start_timestamp\" >= 1514764800000000 /* 2018-01-01 */"
HYPOTHESIS hyp2_3_1 : TAXI_TRIPS "\"trip_start_timestamp\" < 1546300800000000 /* 2019-01-01 */"
HYPOTHESIS hyp2_3_2 : TAXI_TRIPS "EXTRACT(YEAR FROM TO_TIMESTAMP(CAST(\"trip_start_timestamp\" AS DOUBLE PRECISION) / 1000000)) = 2018"
theorem eq_2_3 (t : TableRel TAXI_TRIPS_schema) (h0 : hyp2_3_0 t) (h1 : hyp2_3_1 t) (h2 : hyp2_3_2 t) :
    (sql%([TAXI_TRIPS_schema]) "WITH monthly_trips AS (SELECT \"company\" AS COMPANY, EXTRACT(MONTH FROM TO_TIMESTAMP(CAST(\"trip_start_timestamp\" AS DOUBLE PRECISION) / 1000000)) AS trip_month, COUNT(*) AS trip_count FROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\" WHERE \"trip_start_timestamp\" >= 1514764800000000 /* 2018-01-01 */ AND \"trip_start_timestamp\" < 1546300800000000 /* 2019-01-01 */ AND NOT \"company\" IS NULL GROUP BY \"company\", EXTRACT(MONTH FROM TO_TIMESTAMP(CAST(\"trip_start_timestamp\" AS DOUBLE PRECISION) / 1000000))), consecutive_increase AS (SELECT COMPANY, trip_month, trip_count, trip_count - LAG(trip_count) OVER (PARTITION BY COMPANY ORDER BY trip_month) AS increase FROM monthly_trips) SELECT COMPANY FROM consecutive_increase WHERE NOT increase IS NULL ORDER BY increase DESC LIMIT 3") t = (sql%([TAXI_TRIPS_schema]) "WITH monthly_trips AS (SELECT \"company\", EXTRACT(MONTH FROM TO_TIMESTAMP(CAST(\"trip_start_timestamp\" AS DOUBLE PRECISION) / 1000000)) AS month, COUNT(*) AS trip_count FROM \"CHICAGO\".\"CHICAGO_TAXI_TRIPS\".\"TAXI_TRIPS\" WHERE NOT \"company\" IS NULL AND EXTRACT(YEAR FROM TO_TIMESTAMP(CAST(\"trip_start_timestamp\" AS DOUBLE PRECISION) / 1000000)) = 2018 GROUP BY \"company\", month), monthly_with_lag AS (SELECT \"company\", month, trip_count, LAG(trip_count) OVER (PARTITION BY \"company\" ORDER BY month) AS prev_month_count FROM monthly_trips), increases AS (SELECT \"company\", month, trip_count, prev_month_count, trip_count - prev_month_count AS increase FROM monthly_with_lag WHERE NOT prev_month_count IS NULL) SELECT \"company\" FROM increases ORDER BY increase DESC LIMIT 3") t := by
  first | sql_equiv | sorry

end Bench_sf_bq362
