import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_bq361_eq_2_3

CREATE TABLE ORDERS («order_id» INT, «user_id» INT, «status» STRING, «gender» STRING, «created_at» INT, «returned_at» INT, «shipped_at» INT, «delivered_at» INT, «num_of_item» INT)

theorem eq (t0 : TableRel ORDERS_schema) :
    (sql%([ORDERS_schema]) "WITH user_first_order AS (SELECT \"user_id\", MIN(TO_TIMESTAMP(CAST(\"created_at\" AS DOUBLE PRECISION) / 1000000)) AS first_order_date FROM \"THELOOK_ECOMMERCE\".\"THELOOK_ECOMMERCE\".\"ORDERS\" GROUP BY \"user_id\"), jan2020_cohort AS (SELECT \"user_id\", first_order_date FROM user_first_order WHERE DATE_TRUNC('MONTH', first_order_date) = '2020-01-01'), cohort_size AS (SELECT COUNT(DISTINCT \"user_id\") AS cohort_user FROM jan2020_cohort), cohort_orders AS (SELECT c.\"user_id\", CAST(EXTRACT(year FROM AGE(CAST(DATE_TRUNC('MONTH', TO_TIMESTAMP(CAST(o.\"created_at\" AS DOUBLE PRECISION) / 1000000)) AS TIMESTAMP), CAST(DATE_TRUNC('MONTH', c.first_order_date) AS TIMESTAMP))) * 12 + EXTRACT(month FROM AGE(CAST(DATE_TRUNC('MONTH', TO_TIMESTAMP(CAST(o.\"created_at\" AS DOUBLE PRECISION) / 1000000)) AS TIMESTAMP), CAST(DATE_TRUNC('MONTH', c.first_order_date) AS TIMESTAMP))) AS BIGINT) AS month_since_first_order FROM \"THELOOK_ECOMMERCE\".\"THELOOK_ECOMMERCE\".\"ORDERS\" AS o JOIN jan2020_cohort AS c ON o.\"user_id\" = c.\"user_id\" WHERE TO_TIMESTAMP(CAST(o.\"created_at\" AS DOUBLE PRECISION) / 1000000) >= '2020-02-01' AND TO_TIMESTAMP(CAST(o.\"created_at\" AS DOUBLE PRECISION) / 1000000) < '2021-01-01'), monthly_retention AS (SELECT month_since_first_order, COUNT(DISTINCT \"user_id\") AS new_user FROM cohort_orders GROUP BY month_since_first_order) SELECT CAST('2020-01-01' AS DATE) AS \"COHORT\", mr.month_since_first_order AS \"MONTH_SINCE_FIRST_ORDER\", mr.new_user AS \"NEW_USER\", cs.cohort_user AS \"COHORT_USER\", ROUND(CAST(mr.new_user * 1.0 AS DOUBLE PRECISION) / cs.cohort_user, 6) AS \"COHORT_USERS_PERCENTAGE\" FROM monthly_retention AS mr CROSS JOIN cohort_size AS cs ORDER BY mr.month_since_first_order") t0
  ~= (sql%([ORDERS_schema]) "WITH orders_with_ts AS (SELECT \"order_id\", \"user_id\", \"status\", TO_TIMESTAMP(CAST(\"created_at\" AS DOUBLE PRECISION) / 1000000) AS created_ts FROM \"THELOOK_ECOMMERCE\".\"THELOOK_ECOMMERCE\".\"ORDERS\"), first_purchase AS (SELECT \"user_id\", MIN(created_ts) AS first_order_ts FROM orders_with_ts GROUP BY \"user_id\"), jan2020_cohort AS (SELECT \"user_id\", first_order_ts FROM first_purchase WHERE DATE_TRUNC('MONTH', first_order_ts) = CAST('2020-01-01' AS DATE)), cohort_size AS (SELECT COUNT(DISTINCT \"user_id\") AS cohort_user FROM jan2020_cohort), subsequent_orders AS (SELECT o.\"user_id\", CAST(EXTRACT(year FROM AGE(CAST(DATE_TRUNC('MONTH', o.created_ts) AS TIMESTAMP), CAST(DATE_TRUNC('MONTH', c.first_order_ts) AS TIMESTAMP))) * 12 + EXTRACT(month FROM AGE(CAST(DATE_TRUNC('MONTH', o.created_ts) AS TIMESTAMP), CAST(DATE_TRUNC('MONTH', c.first_order_ts) AS TIMESTAMP))) AS BIGINT) AS month_since_first_order FROM orders_with_ts AS o INNER JOIN jan2020_cohort AS c ON o.\"user_id\" = c.\"user_id\" WHERE o.created_ts > c.first_order_ts AND DATE_TRUNC('MONTH', o.created_ts) >= CAST('2020-02-01' AS DATE) AND DATE_TRUNC('MONTH', o.created_ts) <= CAST('2020-12-01' AS DATE)), monthly_retention AS (SELECT month_since_first_order, COUNT(DISTINCT \"user_id\") AS new_user FROM subsequent_orders GROUP BY month_since_first_order) SELECT '2020-01-01' AS cohort, r.month_since_first_order, r.new_user, cs.cohort_user, ROUND(CAST(CAST(r.new_user AS DOUBLE PRECISION) / CAST(cs.cohort_user AS DOUBLE PRECISION) AS DECIMAL), 6) AS cohort_users_percentage FROM monthly_retention AS r CROSS JOIN cohort_size AS cs ORDER BY r.month_since_first_order") t0
  := by first | sql_equiv | sorry

end N_sf_bq361_eq_2_3
