import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_bq054_eq_1_2

CREATE TABLE TREE_CENSUS_1995 («recordid» INT, «address» STRING, «house_number» STRING, «street» STRING, «zip_original» INT, «cb_original» INT, «site» STRING, «species» STRING, «diameter» INT, «status» STRING, «wires» STRING, «sidewalk_condition» STRING, «support_structure» STRING, «borough» STRING, «x» FLOAT, «y» FLOAT, «longitude» FLOAT, «latitude» FLOAT, «cb_new» INT, «zip_new» INT, «censustract_2010» STRING, «censusblock_2010» STRING, «nta_2010» STRING, «segmentid» INT, «spc_common» STRING, «spc_latin» STRING, «location» STRING)
CREATE TABLE TREE_CENSUS_2005 («objectid» INT, «cen_year» INT, «tree_dbh» INT, «tree_loc» STRING, «pit_type» STRING, «soil_lvl» STRING, «status» STRING, «spc_latin» STRING, «spc_common» STRING, «vert_other» STRING, «vert_pgrd» STRING, «vert_tgrd» STRING, «vert_wall» STRING, «horz_blck» STRING, «horz_grate» STRING, «horz_plant» STRING, «horz_other» STRING, «sidw_crack» STRING, «sidw_raise» STRING, «wire_htap» STRING, «wire_prime» STRING, «wire_2nd» STRING, «wire_other» STRING, «inf_canopy» STRING, «inf_guard» STRING, «inf_wires» STRING, «inf_paving» STRING, «inf_outlet» STRING, «inf_shoes» STRING, «inf_lights» STRING, «inf_other» STRING, «trunk_dmg» STRING, «zipcode» INT, «zip_city» STRING, «cb_num» INT, «borocode» INT, «boroname» STRING, «cncldist» INT, «st_assem» INT, «st_senate» INT, «nta» STRING, «nta_name» STRING, «boro_ct» INT, «x_sp» INT, «y_sp» INT, «objectid_1» INT, «location_1» STRING)
CREATE TABLE TREE_CENSUS_2015 («tree_id» INT, «block_id» INT, «created_at» STRING, «tree_dbh» INT, «stump_diam» INT, «curb_loc» STRING, «status» STRING, «health» STRING, «spc_latin» STRING, «spc_common» STRING, «steward» STRING, «guards» STRING, «sidewalk» STRING, «user_type» STRING, «problems» STRING, «root_stone» STRING, «root_grate» STRING, «root_other» STRING, «trunk_wire» STRING, «trnk_light» STRING, «trnk_other» STRING, «brch_light» STRING, «brch_shoe» STRING, «brch_other» STRING, «address» STRING, «zipcode» INT, «zip_city» STRING, «cb_num» INT, «borocode» INT, «boroname» STRING, «cncldist» INT, «st_assem» INT, «st_senate» INT, «nta» STRING, «nta_name» STRING, «boro_ct» INT, «state» STRING, «latitude» FLOAT, «longitude» FLOAT, «x_sp» FLOAT, «y_sp» FLOAT)

theorem eq (t0 : TableRel TREE_CENSUS_1995_schema) (t1 : TableRel TREE_CENSUS_2005_schema) (t2 : TableRel TREE_CENSUS_2015_schema) :
    (sql%([TREE_CENSUS_1995_schema, TREE_CENSUS_2005_schema, TREE_CENSUS_2015_schema]) "WITH census_1995 AS (SELECT UPPER(\"spc_latin\") AS species_latin, MAX(\"spc_common\") AS common_name, SUM(CASE WHEN NOT \"status\" IN ('Dead', 'Stump', 'Shaft') THEN 1 ELSE 0 END) AS alive_1995, SUM(CASE WHEN \"status\" = 'Dead' THEN 1 ELSE 0 END) AS dead_1995 FROM \"NEW_YORK\".\"NEW_YORK\".\"TREE_CENSUS_1995\" WHERE NOT \"spc_latin\" IS NULL AND UPPER(\"spc_latin\") <> '' AND NOT \"status\" IN ('Stump', 'Shaft') GROUP BY UPPER(\"spc_latin\")), census_2005 AS (SELECT UPPER(\"spc_latin\") AS species_latin, MAX(\"spc_common\") AS common_name, SUM(CASE WHEN \"status\" <> 'Dead' THEN 1 ELSE 0 END) AS alive_2005, SUM(CASE WHEN \"status\" = 'Dead' THEN 1 ELSE 0 END) AS dead_2005 FROM \"NEW_YORK\".\"NEW_YORK\".\"TREE_CENSUS_2005\" WHERE NOT \"spc_latin\" IS NULL AND UPPER(\"spc_latin\") <> '' GROUP BY UPPER(\"spc_latin\")), census_2015 AS (SELECT UPPER(\"spc_latin\") AS species_latin, MAX(\"spc_common\") AS common_name, SUM(CASE WHEN \"status\" = 'Alive' THEN 1 ELSE 0 END) AS alive_2015, SUM(CASE WHEN \"status\" = 'Dead' THEN 1 ELSE 0 END) AS dead_2015 FROM \"NEW_YORK\".\"NEW_YORK\".\"TREE_CENSUS_2015\" WHERE NOT \"spc_latin\" IS NULL AND UPPER(\"spc_latin\") <> '' AND \"status\" IN ('Alive', 'Dead') GROUP BY UPPER(\"spc_latin\")), combined AS (SELECT COALESCE(a.species_latin, b.species_latin, c.species_latin) AS species_latin, COALESCE(c.common_name, b.common_name, a.common_name) AS common_name, COALESCE(a.alive_1995, 0) + COALESCE(a.dead_1995, 0) AS total_1995, COALESCE(a.alive_1995, 0) AS alive_1995, COALESCE(a.dead_1995, 0) AS dead_1995, COALESCE(b.alive_2005, 0) + COALESCE(b.dead_2005, 0) AS total_2005, COALESCE(b.alive_2005, 0) AS alive_2005, COALESCE(b.dead_2005, 0) AS dead_2005, COALESCE(c.alive_2015, 0) + COALESCE(c.dead_2015, 0) AS total_2015, COALESCE(c.alive_2015, 0) AS alive_2015, COALESCE(c.dead_2015, 0) AS dead_2015 FROM census_1995 AS a FULL OUTER JOIN census_2005 AS b ON a.species_latin = b.species_latin FULL OUTER JOIN census_2015 AS c ON COALESCE(a.species_latin, b.species_latin) = c.species_latin) SELECT species_latin, common_name, total_1995, alive_1995, dead_1995, total_2005, alive_2005, dead_2005, total_2015, alive_2015, dead_2015, total_2015 - total_1995 AS growth_total_1995_2015, alive_2015 - alive_1995 AS growth_alive_1995_2015, dead_2015 - dead_1995 AS growth_dead_1995_2015 FROM combined ORDER BY growth_total_1995_2015 DESC LIMIT 10") t0 t1 t2
  ~= (sql%([TREE_CENSUS_1995_schema, TREE_CENSUS_2005_schema, TREE_CENSUS_2015_schema]) "WITH census_1995 AS (SELECT UPPER(\"spc_latin\") AS species_latin_upper, COUNT(CASE WHEN NOT \"status\" IN ('Dead', 'Stump', 'Shaft') THEN 1 END) AS alive_1995, COUNT(CASE WHEN \"status\" = 'Dead' THEN 1 END) AS dead_1995, COUNT(CASE WHEN NOT \"status\" IN ('Stump', 'Shaft') THEN 1 END) AS total_1995 FROM \"NEW_YORK\".\"NEW_YORK\".\"TREE_CENSUS_1995\" WHERE NOT \"spc_latin\" IS NULL AND TRIM(\"spc_latin\") <> '' GROUP BY UPPER(\"spc_latin\")), census_2005 AS (SELECT UPPER(\"spc_latin\") AS species_latin_upper, COUNT(CASE WHEN \"status\" <> 'Dead' THEN 1 END) AS alive_2005, COUNT(CASE WHEN \"status\" = 'Dead' THEN 1 END) AS dead_2005, COUNT(*) AS total_2005 FROM \"NEW_YORK\".\"NEW_YORK\".\"TREE_CENSUS_2005\" WHERE NOT \"spc_latin\" IS NULL AND TRIM(\"spc_latin\") <> '' GROUP BY UPPER(\"spc_latin\")), census_2015 AS (SELECT UPPER(\"spc_latin\") AS species_latin_upper, \"spc_common\", COUNT(CASE WHEN \"status\" = 'Alive' THEN 1 END) AS alive_2015, COUNT(CASE WHEN \"status\" = 'Dead' THEN 1 END) AS dead_2015, COUNT(CASE WHEN \"status\" IN ('Alive', 'Dead') THEN 1 END) AS total_2015 FROM \"NEW_YORK\".\"NEW_YORK\".\"TREE_CENSUS_2015\" WHERE NOT \"spc_latin\" IS NULL AND TRIM(\"spc_latin\") <> '' GROUP BY UPPER(\"spc_latin\"), \"spc_common\"), all_species AS (SELECT species_latin_upper FROM census_1995 UNION SELECT species_latin_upper FROM census_2005 UNION SELECT species_latin_upper FROM census_2015) SELECT a.species_latin_upper, c15.\"spc_common\", COALESCE(c95.total_1995, 0) AS total_1995, COALESCE(c95.alive_1995, 0) AS alive_1995, COALESCE(c95.dead_1995, 0) AS dead_1995, COALESCE(c05.total_2005, 0) AS total_2005, COALESCE(c05.alive_2005, 0) AS alive_2005, COALESCE(c05.dead_2005, 0) AS dead_2005, COALESCE(c15.total_2015, 0) AS total_2015, COALESCE(c15.alive_2015, 0) AS alive_2015, COALESCE(c15.dead_2015, 0) AS dead_2015, COALESCE(c15.total_2015, 0) - COALESCE(c95.total_1995, 0) AS growth_total_1995_2015, COALESCE(c15.alive_2015, 0) - COALESCE(c95.alive_1995, 0) AS growth_alive_1995_2015, COALESCE(c15.dead_2015, 0) - COALESCE(c95.dead_1995, 0) AS growth_dead_1995_2015 FROM all_species AS a LEFT JOIN census_1995 AS c95 ON a.species_latin_upper = c95.species_latin_upper LEFT JOIN census_2005 AS c05 ON a.species_latin_upper = c05.species_latin_upper LEFT JOIN census_2015 AS c15 ON a.species_latin_upper = c15.species_latin_upper ORDER BY growth_total_1995_2015 DESC LIMIT 10") t0 t1 t2
  := by first | sql_equiv | sorry

end N_sf_bq054_eq_1_2
