import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_bq046_eq_0_1

CREATE TABLE REL14_CASEDATA («case_gdc_id» STRING, «project_dbgap_accession_number» STRING, «project_disease_type» STRING, «project_name» STRING, «program_dbgap_accession_number» STRING, «program_name» STRING, «project_id» STRING, «case_barcode» STRING, «legacy_file_count» INT, «current_file_count» INT)
CREATE TABLE REL14_GDCFILEID_TO_GCSURL_NEW («file_gdc_id» STRING, «file_gdc_url» STRING)
CREATE TABLE REL14_FILEDATA_CURRENT («dbName» STRING, «file_gdc_id» STRING, «access» STRING, «acl» STRING, «analysis_input_file_gdc_ids» STRING, «analysis_workflow_link» STRING, «analysis_workflow_type» STRING, «associated_entities__case_gdc_id» STRING, «associated_entities__entity_gdc_id» STRING, «associated_entities__entity_submitter_id» STRING, «associated_entities__entity_type» STRING, «case_gdc_id» STRING, «project_dbgap_accession_number» STRING, «project_disease_type» STRING, «project_name» STRING, «program_dbgap_accession_number» STRING, «program_name» STRING, «project_short_name» STRING, «created_datetime» STRING, «data_category» STRING, «data_format» STRING, «data_type» STRING, «downstream_analyses__output_file_gdc_ids» STRING, «downstream_analyses__workflow_link» STRING, «downstream_analyses__workflow_type» STRING, «experimental_strategy» STRING, «file_name» STRING, «file_size» INT, «file_id» STRING, «index_file_gdc_id» STRING, «index_file_name» STRING, «index_file_size» INT, «md5sum» STRING, «platform» STRING, «file_state» STRING, «file_submitter_id» STRING, «file_type» STRING, «updated_datetime» STRING)
CREATE TABLE ANNOTATIONS («project_short_name» STRING, «entity_barcode» STRING, «entity_type» STRING, «category» STRING, «classification» STRING, «notes» STRING, «date_created» STRING, «date_edited» STRING, «case_gdc_id» STRING, «case_barcode» STRING, «sample_barcode» STRING, «aliquot_barcode» STRING)
CREATE TABLE CLINICAL («program_name» STRING, «case_barcode» STRING, «case_gdc_id» STRING, «program_dbgap_accession_number» STRING, «project_short_name» STRING, «project_name» STRING, «disease_code» STRING, «gender» STRING, «vital_status» STRING, «race» STRING, «ethnicity» STRING, «age_at_diagnosis» INT, «days_to_birth» INT, «days_to_death» INT, «days_to_initial_pathologic_diagnosis» INT, «days_to_last_followup» INT, «days_to_last_known_alive» INT, «days_to_submitted_specimen_dx» INT, «clinical_stage» STRING, «clinical_T» STRING, «clinical_N» STRING, «clinical_M» STRING, «pathologic_stage» STRING, «pathologic_T» STRING, «pathologic_N» STRING, «pathologic_M» STRING, «year_of_initial_pathologic_diagnosis» INT, «tumor_tissue_site» STRING, «primary_neoplasm_melanoma_dx» STRING, «anatomic_neoplasm_subdivision» STRING, «country» STRING, «other_dx» STRING, «other_malignancy_anatomic_site» STRING, «other_malignancy_type» STRING, «other_malignancy_histological_type» STRING, «history_of_neoadjuvant_treatment» STRING, «primary_therapy_outcome_success» STRING, «histological_type» STRING, «neoplasm_histologic_grade» STRING, «icd_10» STRING, «icd_o_3_site» STRING, «icd_o_3_histology» STRING, «person_neoplasm_cancer_status» STRING, «residual_tumor» STRING, «tumor_type» STRING, «new_tumor_event_after_initial_treatment» STRING, «lymphnodes_examined» STRING, «number_of_lymphnodes_examined» INT, «number_of_lymphnodes_positive_by_he» INT, «lymphatic_invasion» STRING, «venous_invasion» STRING, «lymphovascular_invasion_present» STRING, «bcr» STRING, «batch_number» INT, «tss_code» STRING, «age_began_smoking_in_years» INT, «year_of_tobacco_smoking_onset» INT, «stopped_smoking_year» INT, «tobacco_smoking_history» INT, «number_pack_years_smoked» FLOAT, «height» FLOAT, «weight» FLOAT, «bmi» FLOAT, «mononucleotide_and_dinucleotide_marker_panel_analysis_status» STRING, «menopause_status» STRING, «pregnancies» STRING, «hpv_status» STRING, «hpv_calls» STRING, «h_pylori_infection» STRING, «gleason_score_combined» INT, «psa_value» FLOAT, «colorectal_cancer» STRING, «history_of_colon_polyps» STRING)

theorem eq (t0 : TableRel REL14_CASEDATA_schema) (t1 : TableRel REL14_GDCFILEID_TO_GCSURL_NEW_schema) (t2 : TableRel REL14_FILEDATA_CURRENT_schema) (t3 : TableRel ANNOTATIONS_schema) (t4 : TableRel CLINICAL_schema) :
    (sql%([REL14_CASEDATA_schema, REL14_GDCFILEID_TO_GCSURL_NEW_schema, REL14_FILEDATA_CURRENT_schema, ANNOTATIONS_schema, CLINICAL_schema]) "WITH annotation_patients AS (SELECT \"case_barcode\", \"category\" AS categoryName, \"classification\" AS classificationName FROM \"TCGA_BIOCLIN_V0\".\"TCGA_BIOCLIN_V0\".\"ANNOTATIONS\" WHERE \"entity_type\" = 'Patient' AND (\"category\" = 'History of unacceptable prior treatment related to a prior/other malignancy' OR \"classification\" = 'Redaction')), clinical_patients AS (SELECT \"case_barcode\" FROM \"TCGA_BIOCLIN_V0\".\"TCGA_BIOCLIN_V0\".\"CLINICAL\" WHERE \"disease_code\" = 'BRCA' AND \"age_at_diagnosis\" <= 30 AND \"gender\" = 'FEMALE'), joined_patients AS (SELECT COALESCE(c.\"case_barcode\", a.\"case_barcode\") AS case_barcode, a.categoryName, a.classificationName FROM clinical_patients AS c FULL JOIN annotation_patients AS a ON c.\"case_barcode\" = a.\"case_barcode\"), filtered_patients AS (SELECT case_barcode FROM joined_patients WHERE categoryName IS NULL AND classificationName IS NULL) SELECT fp.case_barcode, g.\"file_gdc_url\" FROM filtered_patients AS fp JOIN \"TCGA_BIOCLIN_V0\".\"GDC_METADATA\".\"REL14_CASEDATA\" AS cd ON fp.case_barcode = cd.\"case_barcode\" JOIN \"TCGA_BIOCLIN_V0\".\"GDC_METADATA\".\"REL14_FILEDATA_CURRENT\" AS fd ON cd.\"case_gdc_id\" = fd.\"case_gdc_id\" JOIN \"TCGA_BIOCLIN_V0\".\"GDC_METADATA\".\"REL14_GDCFILEID_TO_GCSURL_NEW\" AS g ON fd.\"file_gdc_id\" = g.\"file_gdc_id\" ORDER BY fp.case_barcode, g.\"file_gdc_url\"") t0 t1 t2 t3 t4
  = (sql%([REL14_CASEDATA_schema, REL14_GDCFILEID_TO_GCSURL_NEW_schema, REL14_FILEDATA_CURRENT_schema, ANNOTATIONS_schema, CLINICAL_schema]) "WITH annot AS (SELECT DISTINCT \"case_barcode\", \"category\" AS categoryName, \"classification\" AS classificationName FROM \"TCGA_BIOCLIN_V0\".\"TCGA_BIOCLIN_V0\".\"ANNOTATIONS\" WHERE \"entity_type\" = 'Patient' AND (\"category\" = 'History of unacceptable prior treatment related to a prior/other malignancy' OR \"classification\" = 'Redaction')), clin AS (SELECT DISTINCT \"case_barcode\", \"case_gdc_id\" FROM \"TCGA_BIOCLIN_V0\".\"TCGA_BIOCLIN_V0\".\"CLINICAL\" WHERE \"disease_code\" = 'BRCA' AND \"age_at_diagnosis\" <= 30 AND \"gender\" = 'FEMALE'), filtered AS (SELECT clin.\"case_barcode\", clin.\"case_gdc_id\" FROM clin FULL JOIN annot ON clin.\"case_barcode\" = annot.\"case_barcode\" WHERE annot.categoryName IS NULL AND annot.classificationName IS NULL) SELECT f.\"case_barcode\", gu.\"file_gdc_url\" FROM filtered AS f JOIN \"TCGA_BIOCLIN_V0\".\"GDC_METADATA\".\"REL14_CASEDATA\" AS cd ON f.\"case_barcode\" = cd.\"case_barcode\" JOIN \"TCGA_BIOCLIN_V0\".\"GDC_METADATA\".\"REL14_FILEDATA_CURRENT\" AS fd ON cd.\"case_gdc_id\" = fd.\"case_gdc_id\" JOIN \"TCGA_BIOCLIN_V0\".\"GDC_METADATA\".\"REL14_GDCFILEID_TO_GCSURL_NEW\" AS gu ON fd.\"file_gdc_id\" = gu.\"file_gdc_id\" ORDER BY f.\"case_barcode\", gu.\"file_gdc_url\"") t0 t1 t2 t3 t4
  := by first | sql_equiv | sorry

end N_sf_bq046_eq_0_1
