import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_bq308_eq_0_1

CREATE TABLE POSTS_ANSWERS («id» INT, «title» STRING, «body» STRING, «accepted_answer_id» STRING, «answer_count» STRING, «comment_count» INT, «community_owned_date» INT, «creation_date» INT, «favorite_count» STRING, «last_activity_date» INT, «last_edit_date» INT, «last_editor_display_name» STRING, «last_editor_user_id» INT, «owner_display_name» STRING, «owner_user_id» INT, «parent_id» INT, «post_type_id» INT, «score» INT, «tags» STRING, «view_count» STRING)
CREATE TABLE POSTS_QUESTIONS («id» INT, «title» STRING, «body» STRING, «accepted_answer_id» INT, «answer_count» INT, «comment_count» INT, «community_owned_date» INT, «creation_date» INT, «favorite_count» INT, «last_activity_date» INT, «last_edit_date» INT, «last_editor_display_name» STRING, «last_editor_user_id» INT, «owner_display_name» STRING, «owner_user_id» INT, «parent_id» STRING, «post_type_id» INT, «score» INT, «tags» STRING, «view_count» INT)

theorem eq (t0 : TableRel POSTS_ANSWERS_schema) (t1 : TableRel POSTS_QUESTIONS_schema) :
    (sql%([POSTS_ANSWERS_schema, POSTS_QUESTIONS_schema]) "WITH questions_2021 AS (SELECT \"id\" AS question_id, TO_TIMESTAMP(CAST(\"creation_date\" AS DOUBLE PRECISION) / 1000000) AS question_ts, DAY_OF_WEEK(TO_TIMESTAMP(CAST(\"creation_date\" AS DOUBLE PRECISION) / 1000000)) + 1 AS day_of_week FROM \"STACKOVERFLOW\".\"STACKOVERFLOW\".\"POSTS_QUESTIONS\" WHERE EXTRACT(YEAR FROM TO_TIMESTAMP(CAST(\"creation_date\" AS DOUBLE PRECISION) / 1000000)) = 2021), first_answers AS (SELECT \"parent_id\" AS question_id, MIN(TO_TIMESTAMP(CAST(\"creation_date\" AS DOUBLE PRECISION) / 1000000)) AS first_answer_ts FROM \"STACKOVERFLOW\".\"STACKOVERFLOW\".\"POSTS_ANSWERS\" GROUP BY \"parent_id\"), combined AS (SELECT q.day_of_week, q.question_id, CASE WHEN fa.first_answer_ts <= q.question_ts + INTERVAL '1 HOUR' THEN 1 ELSE 0 END AS answered_in_1h FROM questions_2021 AS q LEFT JOIN first_answers AS fa ON q.question_id = fa.question_id) SELECT day_of_week AS \"Day_of_Week\", COUNT(*) AS \"Num_Questions\", SUM(answered_in_1h) AS \"Num_Answered_in_1H\", ROUND(CAST(CAST(SUM(answered_in_1h) * 100.0 AS DOUBLE PRECISION) / COUNT(*) AS DECIMAL), 6) AS \"Percent_Answered_in_1H\" FROM combined GROUP BY day_of_week ORDER BY day_of_week") t0 t1
  ~= (sql%([POSTS_ANSWERS_schema, POSTS_QUESTIONS_schema]) "SELECT DAY_OF_WEEK(TO_TIMESTAMP(CAST(q.\"creation_date\" AS DOUBLE PRECISION) / 1000000)) + 1 AS \"Day_of_Week\", COUNT(DISTINCT q.\"id\") AS \"Num_Questions\", COUNT(DISTINCT CASE WHEN CAST((a.\"creation_date\" - q.\"creation_date\") AS DOUBLE PRECISION) / 1000000 <= 3600 THEN q.\"id\" END) AS \"Num_Answered_in_1H\", ROUND(CAST(CAST(COUNT(DISTINCT CASE WHEN CAST((a.\"creation_date\" - q.\"creation_date\") AS DOUBLE PRECISION) / 1000000 <= 3600 THEN q.\"id\" END) * 100.0 AS DOUBLE PRECISION) / COUNT(DISTINCT q.\"id\") AS DECIMAL), 6) AS \"Percent_Answered_in_1H\" FROM \"STACKOVERFLOW\".\"STACKOVERFLOW\".\"POSTS_QUESTIONS\" AS q LEFT JOIN \"STACKOVERFLOW\".\"STACKOVERFLOW\".\"POSTS_ANSWERS\" AS a ON a.\"parent_id\" = q.\"id\" AND CAST((a.\"creation_date\" - q.\"creation_date\") AS DOUBLE PRECISION) / 1000000 <= 3600 WHERE EXTRACT(YEAR FROM TO_TIMESTAMP(CAST(q.\"creation_date\" AS DOUBLE PRECISION) / 1000000)) = 2021 GROUP BY \"Day_of_Week\" ORDER BY \"Day_of_Week\"") t0 t1
  := by first | sql_equiv | sorry

end N_sf_bq308_eq_0_1
