import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_bq044_eq_0_1

CREATE TABLE SOMATIC_MUTATION_HG19_DCC_2017_02 («project_short_name» STRING, «case_barcode» STRING, «sample_barcode_tumor» STRING, «sample_barcode_normal» STRING, «aliquot_barcode_tumor» STRING, «aliquot_barcode_normal» STRING, «NCBI_Build» STRING, «HGNC_UniProt_ID_Supplied_By_UniProt» STRING, «Entrez_Gene_Id» INT, «Variant_Classification» STRING, «Variant_Type» STRING, «Chromosome» STRING, «Start_Position» INT, «End_Position» INT, «Mutation_Status» STRING, «Genome_Change» STRING, «cDNA_Change» STRING, «Protein_Change» STRING, «Annotation_Transcript» STRING, «CCLE_ONCOMAP_Total_Mutations_In_Gene» INT, «Center» STRING, «COSMIC_Total_Alterations_In_Gene» INT, «DbSNP_RS» STRING, «DbSNP_Val_Status» STRING, «DNARepairGenes_Role» STRING, «DrugBank» STRING, «GC_Content» FLOAT, «GENCODE_Transcript_Name» STRING, «GENCODE_Transcript_Status» STRING, «GENCODE_Transcript_Type» STRING, «Gene_Type» STRING, «GO_Biological_Process» STRING, «GO_Cellular_Component» STRING, «GO_Molecular_Function» STRING, «HGNC_Accession_Numbers» STRING, «HGNC_CCDS_IDs» STRING, «HGNC_Ensembl_ID_Supplied_By_Ensembl» STRING, «HGNC_HGNC_ID» INT, «HGNC_Locus_Group» STRING, «HGNC_Locus_Type» STRING, «HGNC_OMIM_ID_Supplied_By_NCBI» STRING, «HGNC_RefSeq_Supplied_By_NCBI» STRING, «HGNC_UCSC_ID_Supplied_By_UCSC» STRING, «Hugo_Symbol» STRING, «Normal_Seq_Allele1» STRING, «Normal_Seq_Allele2» STRING, «Normal_Validation_Allele1» STRING, «Normal_Validation_Allele2» STRING, «OREGANNO_ID» STRING, «Ref_Context» STRING, «Reference_Allele» STRING, «Refseq_Prot_Id» STRING, «Secondary_Variant_Classification» STRING, «Sequencer» STRING, «Sequence_Source» STRING, «SwissProt_Acc_Id» STRING, «SwissProt_Entry_Id» STRING, «Transcript_Exon» INT, «Transcript_Position» STRING, «Transcript_Strand» STRING, «Tumor_Seq_Allele1» STRING, «Tumor_Seq_Allele2» STRING, «Tumor_Validation_Allele1» STRING, «Tumor_Validation_Allele2» STRING, «UniProt_AApos» INT, «UniProt_Region» STRING, «Validation_Method» STRING)
CREATE TABLE RNASEQ_HG19_GDC_2017_02 («project_short_name» STRING, «case_barcode» STRING, «sample_barcode» STRING, «aliquot_barcode» STRING, «HGNC_gene_symbol» STRING, «gene_id» INT, «normalized_count» FLOAT, «original_gene_symbol» STRING, «platform» STRING)
CREATE TABLE CLINICAL_GDC_2019_06 («case_gdc_id» STRING, «case_barcode» STRING, «program_name» STRING, «disease_code» STRING, «project_short_name» STRING, «age_at_diagnosis» INT, «age_began_smoking_in_years» STRING, «anatomic_neoplasm_subdivision» STRING, «batch_number» INT, «bcr» STRING, «bmi» FLOAT, «clinical_M» STRING, «clinical_N» STRING, «clinical_stage» STRING, «clinical_T» STRING, «colorectal_cancer» STRING, «country» STRING, «days_to_birth» INT, «days_to_death» INT, «days_to_initial_pathologic_diagnosis» INT, «days_to_last_followup» INT, «days_to_last_known_alive» INT, «days_to_submitted_specimen_dx» STRING, «ethnicity» STRING, «gender» STRING, «gleason_score_combined» STRING, «h_pylori_infection» STRING, «height» INT, «histological_type» STRING, «history_of_colon_polyps» STRING, «history_of_neoadjuvant_treatment» STRING, «hpv_calls» STRING, «hpv_status» STRING, «icd_10» STRING, «icd_o_3_histology» STRING, «icd_o_3_site» STRING, «lymphatic_invasion» STRING, «lymphnodes_examined» STRING, «lymphovascular_invasion_present» STRING, «menopause_status» STRING, «mononucleotide_and_dinucleotide_marker_panel_analysis_status» STRING, «neoplasm_histologic_grade» STRING, «new_tumor_event_after_initial_treatment» BOOL, «number_of_lymphnodes_examined» INT, «number_of_lymphnodes_positive_by_he» STRING, «number_pack_years_smoked» INT, «other_dx» STRING, «other_malignancy_anatomic_site» STRING, «other_malignancy_histological_type» STRING, «other_malignancy_type» STRING, «pathologic_M» STRING, «pathologic_N» STRING, «pathologic_stage» STRING, «pathologic_T» STRING, «person_neoplasm_cancer_status» STRING, «pregnancies» STRING, «primary_neoplasm_melanoma_dx» STRING, «primary_therapy_outcome_success» STRING, «psa_value» STRING, «race» STRING, «residual_tumor» STRING, «stopped_smoking_year» INT, «tobacco_smoking_history» INT, «tss_code» STRING, «tumor_tissue_site» STRING, «tumor_type» STRING, «venous_invasion» STRING, «vital_status» STRING, «weight» INT, «year_of_diagnosis» INT, «year_of_tobacco_smoking_onset» INT)

theorem eq (t0 : TableRel SOMATIC_MUTATION_HG19_DCC_2017_02_schema) (t1 : TableRel RNASEQ_HG19_GDC_2017_02_schema) (t2 : TableRel CLINICAL_GDC_2019_06_schema) :
    (sql%([SOMATIC_MUTATION_HG19_DCC_2017_02_schema, RNASEQ_HG19_GDC_2017_02_schema, CLINICAL_GDC_2019_06_schema]) "WITH mutation_cases AS (SELECT DISTINCT \"case_barcode\", \"Variant_Type\" FROM \"TCGA\".\"TCGA_VERSIONED\".\"SOMATIC_MUTATION_HG19_DCC_2017_02\" WHERE \"Hugo_Symbol\" = 'CDKN2A' AND \"project_short_name\" = 'TCGA-BLCA'), gene_expression AS (SELECT \"case_barcode\", \"HGNC_gene_symbol\", \"normalized_count\" FROM \"TCGA\".\"TCGA_VERSIONED\".\"RNASEQ_HG19_GDC_2017_02\" WHERE \"HGNC_gene_symbol\" IN ('MDM2', 'TP53', 'CDKN1A', 'CCNE1')) SELECT mc.\"case_barcode\", ge.\"HGNC_gene_symbol\", mc.\"Variant_Type\", LOWER(cl.\"gender\") AS \"GENDER\", cl.\"vital_status\", cl.\"days_to_death\", ge.\"normalized_count\" FROM mutation_cases AS mc JOIN gene_expression AS ge ON mc.\"case_barcode\" = ge.\"case_barcode\" JOIN \"TCGA\".\"TCGA_VERSIONED\".\"CLINICAL_GDC_2019_06\" AS cl ON mc.\"case_barcode\" = cl.\"case_barcode\" ORDER BY mc.\"case_barcode\", ge.\"HGNC_gene_symbol\"") t0 t1 t2
  ~= (sql%([SOMATIC_MUTATION_HG19_DCC_2017_02_schema, RNASEQ_HG19_GDC_2017_02_schema, CLINICAL_GDC_2019_06_schema]) "SELECT mut.\"case_barcode\", rna.\"HGNC_gene_symbol\", mut.\"Variant_Type\", clin.\"demo__gender\" AS \"GENDER\", clin.\"demo__vital_status\" AS \"vital_status\", clin.\"demo__days_to_death\" AS \"days_to_death\", rna.\"normalized_count\" FROM \"TCGA\".\"TCGA_VERSIONED\".\"SOMATIC_MUTATION_HG19_DCC_2017_02\" AS mut JOIN \"TCGA\".\"TCGA_VERSIONED\".\"RNASEQ_HG19_GDC_2017_02\" AS rna ON mut.\"case_barcode\" = rna.\"case_barcode\" AND rna.\"HGNC_gene_symbol\" IN ('MDM2', 'TP53', 'CDKN1A', 'CCNE1') JOIN \"TCGA\".\"TCGA_VERSIONED\".\"CLINICAL_GDC_R39\" AS clin ON mut.\"case_barcode\" = clin.\"submitter_id\" WHERE mut.\"project_short_name\" = 'TCGA-BLCA' AND mut.\"Hugo_Symbol\" = 'CDKN2A' ORDER BY mut.\"case_barcode\"") t0 t1 t2
  := by first | sql_equiv | sorry

end N_sf_bq044_eq_0_1
