import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_bq156_eq_1_3

CREATE TABLE EBPP_ADJUSTPANCAN_ILLUMINAHISEQ_RNASEQV2_GENEXP_FILTERED («ParticipantBarcode» STRING, «SampleBarcode» STRING, «AliquotBarcode» STRING, «SampleTypeLetterCode» STRING, «SampleType» STRING, «Study» STRING, «Symbol» STRING, «Entrez» STRING, «normalized_count» FLOAT)
CREATE TABLE MC3_MAF_V5_ONE_PER_TUMOR_SAMPLE («ParticipantBarcode» STRING, «Tumor_SampleBarcode» STRING, «Tumor_AliquotBarcode» STRING, «Normal_SampleBarcode» STRING, «Normal_AliquotBarcode» STRING, «Normal_SampleTypeLetterCode» STRING, «Study» STRING, «Hugo_Symbol» STRING, «HGVSp_Short» STRING, «Variant_Classification» STRING, «HGVSc» STRING, «CENTERS» STRING, «FILTER» STRING)

theorem eq (t0 : TableRel EBPP_ADJUSTPANCAN_ILLUMINAHISEQ_RNASEQV2_GENEXP_FILTERED_schema) (t1 : TableRel MC3_MAF_V5_ONE_PER_TUMOR_SAMPLE_schema) :
    (sql%([EBPP_ADJUSTPANCAN_ILLUMINAHISEQ_RNASEQV2_GENEXP_FILTERED_schema, MC3_MAF_V5_ONE_PER_TUMOR_SAMPLE_schema]) "WITH expr AS (SELECT r.\"ParticipantBarcode\", AVG(LOG(10, r.\"normalized_count\" + 1)) AS log_expr, CASE WHEN r.\"ParticipantBarcode\" IN (SELECT DISTINCT \"ParticipantBarcode\" FROM \"PANCANCER_ATLAS_1\".\"PANCANCER_ATLAS_FILTERED\".\"MC3_MAF_V5_ONE_PER_TUMOR_SAMPLE\" WHERE \"Hugo_Symbol\" = 'TP53' AND \"FILTER\" = 'PASS') THEN 1 ELSE 0 END AS is_mutant FROM \"PANCANCER_ATLAS_1\".\"PANCANCER_ATLAS_FILTERED\".\"EBPP_ADJUSTPANCAN_ILLUMINAHISEQ_RNASEQV2_GENEXP_FILTERED\" AS r WHERE r.\"Study\" = 'LGG' AND r.\"Symbol\" = 'DRG2' GROUP BY r.\"ParticipantBarcode\"), totals AS (SELECT SUM(log_expr) AS S, SUM(log_expr * log_expr) AS Q, COUNT(*) AS N, SUM(CASE WHEN is_mutant = 1 THEN log_expr ELSE 0 END) AS S_y, SUM(CASE WHEN is_mutant = 1 THEN log_expr * log_expr ELSE 0 END) AS Q_y, SUM(is_mutant) AS N_y FROM expr), derived AS (SELECT S_y, Q_y, N_y, S - S_y AS S_n, Q - Q_y AS Q_n, N - N_y AS N_n FROM totals), t_calc AS (SELECT CAST(S_y AS DOUBLE PRECISION) / N_y AS g_y, CAST(S_n AS DOUBLE PRECISION) / N_n AS g_n, CAST((Q_y - CAST(S_y * S_y AS DOUBLE PRECISION) / N_y) AS DOUBLE PRECISION) / (N_y - 1) AS s2_y, CAST((Q_n - CAST(S_n * S_n AS DOUBLE PRECISION) / N_n) AS DOUBLE PRECISION) / (N_n - 1) AS s2_n, N_y, N_n FROM derived WHERE N_y >= 10 AND N_n >= 10) SELECT ROUND(CAST(CAST((g_y - g_n) AS DOUBLE PRECISION) / SQRT(CAST(s2_y AS DOUBLE PRECISION) / N_y + CAST(s2_n AS DOUBLE PRECISION) / N_n) AS DECIMAL), 2) AS TSCORE FROM t_calc WHERE s2_y > 0 AND s2_n > 0") t0 t1
  ~= (sql%([EBPP_ADJUSTPANCAN_ILLUMINAHISEQ_RNASEQV2_GENEXP_FILTERED_schema, MC3_MAF_V5_ONE_PER_TUMOR_SAMPLE_schema]) "WITH drg2_expr AS (/* Get DRG2 gene expression for LGG participants, average LOG10(normalized_count+1) per participant */ SELECT \"ParticipantBarcode\", AVG(LOG(10, \"normalized_count\" + 1)) AS avg_log_expr FROM \"PANCANCER_ATLAS_1\".\"PANCANCER_ATLAS_FILTERED\".\"EBPP_ADJUSTPANCAN_ILLUMINAHISEQ_RNASEQV2_GENEXP_FILTERED\" WHERE \"Study\" = 'LGG' AND \"Symbol\" = 'DRG2' GROUP BY \"ParticipantBarcode\"), tp53_mutants AS (/* Get LGG participants with TP53 PASS mutations */ SELECT DISTINCT \"ParticipantBarcode\" FROM \"PANCANCER_ATLAS_1\".\"PANCANCER_ATLAS_FILTERED\".\"MC3_MAF_V5_ONE_PER_TUMOR_SAMPLE\" WHERE \"Study\" = 'LGG' AND \"Hugo_Symbol\" = 'TP53' AND \"FILTER\" = 'PASS'), classified AS (/* Classify participants as TP53-mutant or TP53-wildtype */ SELECT e.\"ParticipantBarcode\", e.avg_log_expr, CASE WHEN NOT m.\"ParticipantBarcode\" IS NULL THEN 'mutant' ELSE 'wildtype' END AS tp53_status FROM drg2_expr AS e LEFT JOIN tp53_mutants AS m ON e.\"ParticipantBarcode\" = m.\"ParticipantBarcode\"), group_stats AS (/* Compute group means, variances, and counts */ SELECT tp53_status, AVG(avg_log_expr) AS mean_val, VAR_SAMP(avg_log_expr) AS var_val, COUNT(*) AS n FROM classified GROUP BY tp53_status HAVING COUNT(*) >= 10 AND VAR_SAMP(avg_log_expr) > 0) /* Compute Welch's t-score: (mean_mutant - mean_wildtype) / sqrt(var_mutant/n_mutant + var_wildtype/n_wildtype) */ SELECT ROUND(CAST(CAST((MAX(CASE WHEN tp53_status = 'mutant' THEN mean_val END) - MAX(CASE WHEN tp53_status = 'wildtype' THEN mean_val END)) AS DOUBLE PRECISION) / SQRT(MAX(CASE WHEN tp53_status = 'mutant' THEN CAST(var_val AS DOUBLE PRECISION) / n END) + MAX(CASE WHEN tp53_status = 'wildtype' THEN CAST(var_val AS DOUBLE PRECISION) / n END)) AS DECIMAL), 2) AS TSCORE FROM group_stats") t0 t1
  := by first | sql_equiv | sorry

end N_sf_bq156_eq_1_3
