import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_bq454_eq_1_2

CREATE TABLE SAMPLE_INFO («Sample» STRING, «Family_ID» STRING, «Population» STRING, «Population_Description» STRING, «Gender» STRING, «Relationship» STRING, «Unexpected_Parent_Child» STRING, «Non_Paternity» STRING, «Siblings» STRING, «Grandparents» STRING, «Avuncular» STRING, «Half_Siblings» STRING, «Unknown_Second_Order» STRING, «Third_Order» STRING, «In_Low_Coverage_Pilot» BOOL, «LC_Pilot_Platforms» STRING, «LC_Pilot_Centers» STRING, «In_High_Coverage_Pilot» BOOL, «HC_Pilot_Platforms» STRING, «HC_Pilot_Centers» STRING, «In_Exon_Targetted_Pilot» BOOL, «ET_Pilot_Platforms» STRING, «ET_Pilot_Centers» STRING, «Has_Sequence_in_Phase1» BOOL, «Phase1_LC_Platform» STRING, «Phase1_LC_Centers» STRING, «Phase1_E_Platform» STRING, «Phase1_E_Centers» STRING, «In_Phase1_Integrated_Variant_Set» BOOL, «Has_Phase1_chrY_SNPS» BOOL, «Has_phase1_chrY_Deletions» BOOL, «Has_phase1_chrMT_SNPs» BOOL, «Main_project_LC_Centers» STRING, «Main_project_LC_platform» STRING, «Total_LC_Sequence» FLOAT, «LC_Non_Duplicated_Aligned_Coverage» FLOAT, «Main_Project_E_Centers» STRING, «Main_Project_E_Platform» STRING, «Total_Exome_Sequence» FLOAT, «X_Targets_Covered_to_20x_or_greater» FLOAT, «VerifyBam_E_Omni_Free» FLOAT, «VerifyBam_E_Affy_Free» FLOAT, «VerifyBam_E_Omni_Chip» FLOAT, «VerifyBam_E_Affy_Chip» FLOAT, «VerifyBam_LC_Omni_Free» FLOAT, «VerifyBam_LC_Affy_Free» FLOAT, «VerifyBam_LC_Omni_Chip» FLOAT, «VerifyBam_LC_Affy_Chip» FLOAT, «LC_Indel_Ratio» FLOAT, «E_Indel_Ratio» FLOAT, «LC_Passed_QC» BOOL, «E_Passed_QC» BOOL, «In_Final_Phase_Variant_Calling» BOOL, «Has_Omni_Genotypes» BOOL, «Has_Axiom_Genotypes» BOOL, «Has_Affy_6_0_Genotypes» BOOL, «Has_Exome_LOF_Genotypes» BOOL, «EBV_Coverage» FLOAT, «DNA_Source_from_Coriell» STRING, «Has_Sequence_from_Blood_in_Index» BOOL, «Super_Population» STRING, «Super_Population_Description» STRING)
CREATE TABLE PEDIGREE («Family_ID» STRING, «Individual_ID» STRING, «Paternal_ID» STRING, «Maternal_ID» STRING, «Gender» INT, «Phenotype» INT, «Population» STRING, «Relationship» STRING, «Siblings» STRING, «Second_Order» STRING, «Third_Order» STRING, «Other_Comments» STRING)
CREATE TABLE VARIANTS («reference_name» STRING, «start» INT, «end» INT, «reference_bases» STRING, «alternate_bases» STRING, «quality» FLOAT, «filter» STRING, «names» STRING, «call» STRING, «AA» STRING, «AC» STRING, «AC1» INT, «AF» FLOAT, «AF1» FLOAT, «AFR_AF» FLOAT, «AMR_AF» FLOAT, «AN» INT, «ASN_AF» FLOAT, «AVGPOST» FLOAT, «CIEND» STRING, «CIPOS» STRING, «DP» INT, «DP4» STRING, «ERATE» FLOAT, «EUR_AF» FLOAT, «FQ» FLOAT, «G3» STRING, «HOMLEN» INT, «HOMSEQ» STRING, «HWE» FLOAT, «LDAF» FLOAT, «MQ» INT, «PV4» STRING, «RSQ» FLOAT, «SNPSOURCE» STRING, «SOURCE» STRING, «SVLEN» INT, «SVTYPE» STRING, «THETA» FLOAT, «VT» STRING)

theorem eq (t0 : TableRel SAMPLE_INFO_schema) (t1 : TableRel PEDIGREE_schema) (t2 : TableRel VARIANTS_schema) :
    (sql%([SAMPLE_INFO_schema, PEDIGREE_schema, VARIANTS_schema]) "/* Step 1: Get population sizes from SAMPLE_INFO */ WITH pop_sizes AS (SELECT \"Super_Population\", \"Super_Population_Description\", COUNT(*) AS \"TOTAL_POPULATION_SIZE\" FROM \"_1000_GENOMES\".\"_1000_GENOMES\".\"SAMPLE_INFO\" GROUP BY \"Super_Population\", \"Super_Population_Description\"), variant_sample_counts /* Step 2: For each common autosomal variant, flatten calls and count samples with alt allele per super population */ AS (SELECT v.\"reference_name\", v.\"start\", si.\"Super_Population\", COUNT(*) AS samples_with_variant FROM \"_1000_GENOMES\".\"_1000_GENOMES\".\"VARIANTS\" AS v, LATERAL UNNEST(input => v.\"call\") AS c(SEQ, KEY, PATH, INDEX, VALUE, THIS) JOIN \"_1000_GENOMES\".\"_1000_GENOMES\".\"SAMPLE_INFO\" AS si ON CAST(JSON_EXTRACT_PATH(c.value, 'call_set_name') AS TEXT) = si.\"Sample\" WHERE NOT v.\"reference_name\" IN ('X', 'Y', 'MT') AND CAST(v.\"AF\" AS DOUBLE PRECISION) >= 0.05 AND (CAST(JSON_EXTRACT_PATH(c.value, 'genotype', '0') AS INT) > 0 OR CAST(JSON_EXTRACT_PATH(c.value, 'genotype', '1') AS INT) > 0) GROUP BY v.\"reference_name\", v.\"start\", si.\"Super_Population\") /* Step 3: Group by super population and number of samples with variant */ SELECT vsc.\"Super_Population\" AS \"SUPER_POPULATION\", ps.\"Super_Population_Description\" AS \"SUPER_POPULATION_DESCRIPTION\", ps.\"TOTAL_POPULATION_SIZE\", 'Yes' AS \"IS_COMMON_VARIANT\", vsc.samples_with_variant AS \"SAMPLES_WITH_VARIANT\", COUNT(*) AS \"VARIANT_COUNT\" FROM variant_sample_counts AS vsc JOIN pop_sizes AS ps ON vsc.\"Super_Population\" = ps.\"Super_Population\" GROUP BY vsc.\"Super_Population\", ps.\"Super_Population_Description\", ps.\"TOTAL_POPULATION_SIZE\", vsc.samples_with_variant ORDER BY vsc.\"Super_Population\", vsc.samples_with_variant") t0 t1 t2
  ~= (sql%([SAMPLE_INFO_schema, PEDIGREE_schema, VARIANTS_schema]) "WITH variant_sample AS (SELECT v.\"reference_name\", v.\"start\", v.\"reference_bases\", v.\"AF\", CAST(JSON_EXTRACT_PATH(c.value, 'call_set_name') AS TEXT) AS sample_name FROM \"_1000_GENOMES\".\"_1000_GENOMES\".\"VARIANTS\" AS v, LATERAL UNNEST(input => v.\"call\") AS c(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE NOT v.\"reference_name\" IN ('X', 'Y', 'MT') AND v.\"AF\" >= 0.05 AND (CAST(JSON_EXTRACT_PATH(c.value, 'genotype', '0') AS INT) > 0 OR CAST(JSON_EXTRACT_PATH(c.value, 'genotype', '1') AS INT) > 0)), pop_sizes AS (SELECT \"Super_Population\", \"Super_Population_Description\", COUNT(*) AS TOTAL_POPULATION_SIZE FROM \"_1000_GENOMES\".\"_1000_GENOMES\".\"SAMPLE_INFO\" GROUP BY \"Super_Population\", \"Super_Population_Description\"), variant_pop_counts AS (SELECT vs.\"reference_name\", vs.\"start\", vs.\"reference_bases\", si.\"Super_Population\", COUNT(DISTINCT vs.sample_name) AS SAMPLES_WITH_VARIANT FROM variant_sample AS vs JOIN \"_1000_GENOMES\".\"_1000_GENOMES\".\"SAMPLE_INFO\" AS si ON vs.sample_name = si.\"Sample\" GROUP BY vs.\"reference_name\", vs.\"start\", vs.\"reference_bases\", si.\"Super_Population\") SELECT vpc.\"Super_Population\" AS SUPER_POPULATION, ps.\"Super_Population_Description\" AS SUPER_POPULATION_DESCRIPTION, ps.TOTAL_POPULATION_SIZE, 'Yes' AS IS_COMMON_VARIANT, vpc.SAMPLES_WITH_VARIANT, COUNT(*) AS VARIANT_COUNT FROM variant_pop_counts AS vpc JOIN pop_sizes AS ps ON vpc.\"Super_Population\" = ps.\"Super_Population\" GROUP BY vpc.\"Super_Population\", ps.\"Super_Population_Description\", ps.TOTAL_POPULATION_SIZE, vpc.SAMPLES_WITH_VARIANT ORDER BY vpc.\"Super_Population\", vpc.SAMPLES_WITH_VARIANT") t0 t1 t2
  := by first | sql_equiv | sorry

end N_sf_bq454_eq_1_2
