import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_bq156_eq_1_2

CREATE TABLE EBPP_ADJUSTPANCAN_ILLUMINAHISEQ_RNASEQV2_GENEXP_FILTERED («ParticipantBarcode» STRING, «SampleBarcode» STRING, «AliquotBarcode» STRING, «SampleTypeLetterCode» STRING, «SampleType» STRING, «Study» STRING, «Symbol» STRING, «Entrez» STRING, «normalized_count» FLOAT)
CREATE TABLE MC3_MAF_V5_ONE_PER_TUMOR_SAMPLE («ParticipantBarcode» STRING, «Tumor_SampleBarcode» STRING, «Tumor_AliquotBarcode» STRING, «Normal_SampleBarcode» STRING, «Normal_AliquotBarcode» STRING, «Normal_SampleTypeLetterCode» STRING, «Study» STRING, «Hugo_Symbol» STRING, «HGVSp_Short» STRING, «Variant_Classification» STRING, «HGVSc» STRING, «CENTERS» STRING, «FILTER» STRING)

theorem eq (t0 : TableRel EBPP_ADJUSTPANCAN_ILLUMINAHISEQ_RNASEQV2_GENEXP_FILTERED_schema) (t1 : TableRel MC3_MAF_V5_ONE_PER_TUMOR_SAMPLE_schema) :
    (sql%([EBPP_ADJUSTPANCAN_ILLUMINAHISEQ_RNASEQV2_GENEXP_FILTERED_schema, MC3_MAF_V5_ONE_PER_TUMOR_SAMPLE_schema]) "WITH expr AS (SELECT r.\"ParticipantBarcode\", AVG(LOG(10, r.\"normalized_count\" + 1)) AS log_expr, CASE WHEN r.\"ParticipantBarcode\" IN (SELECT DISTINCT \"ParticipantBarcode\" FROM \"PANCANCER_ATLAS_1\".\"PANCANCER_ATLAS_FILTERED\".\"MC3_MAF_V5_ONE_PER_TUMOR_SAMPLE\" WHERE \"Hugo_Symbol\" = 'TP53' AND \"FILTER\" = 'PASS') THEN 1 ELSE 0 END AS is_mutant FROM \"PANCANCER_ATLAS_1\".\"PANCANCER_ATLAS_FILTERED\".\"EBPP_ADJUSTPANCAN_ILLUMINAHISEQ_RNASEQV2_GENEXP_FILTERED\" AS r WHERE r.\"Study\" = 'LGG' AND r.\"Symbol\" = 'DRG2' GROUP BY r.\"ParticipantBarcode\"), totals AS (SELECT SUM(log_expr) AS S, SUM(log_expr * log_expr) AS Q, COUNT(*) AS N, SUM(CASE WHEN is_mutant = 1 THEN log_expr ELSE 0 END) AS S_y, SUM(CASE WHEN is_mutant = 1 THEN log_expr * log_expr ELSE 0 END) AS Q_y, SUM(is_mutant) AS N_y FROM expr), derived AS (SELECT S_y, Q_y, N_y, S - S_y AS S_n, Q - Q_y AS Q_n, N - N_y AS N_n FROM totals), t_calc AS (SELECT CAST(S_y AS DOUBLE PRECISION) / N_y AS g_y, CAST(S_n AS DOUBLE PRECISION) / N_n AS g_n, CAST((Q_y - CAST(S_y * S_y AS DOUBLE PRECISION) / N_y) AS DOUBLE PRECISION) / (N_y - 1) AS s2_y, CAST((Q_n - CAST(S_n * S_n AS DOUBLE PRECISION) / N_n) AS DOUBLE PRECISION) / (N_n - 1) AS s2_n, N_y, N_n FROM derived WHERE N_y >= 10 AND N_n >= 10) SELECT ROUND(CAST(CAST((g_y - g_n) AS DOUBLE PRECISION) / SQRT(CAST(s2_y AS DOUBLE PRECISION) / N_y + CAST(s2_n AS DOUBLE PRECISION) / N_n) AS DECIMAL), 2) AS TSCORE FROM t_calc WHERE s2_y > 0 AND s2_n > 0") t0 t1
  ~= (sql%([EBPP_ADJUSTPANCAN_ILLUMINAHISEQ_RNASEQV2_GENEXP_FILTERED_schema, MC3_MAF_V5_ONE_PER_TUMOR_SAMPLE_schema]) "WITH expr /* Step 1: Get DRG2 gene expression for all LGG participants */ /* Expression = average of log10(normalized_count + 1) per participant */ AS (SELECT \"ParticipantBarcode\", AVG(LOG(10, \"normalized_count\" + 1)) AS gene_expr FROM \"PANCANCER_ATLAS_1\".\"PANCANCER_ATLAS_FILTERED\".\"EBPP_ADJUSTPANCAN_ILLUMINAHISEQ_RNASEQV2_GENEXP_FILTERED\" WHERE \"Symbol\" = 'DRG2' AND \"Study\" = 'LGG' GROUP BY \"ParticipantBarcode\"), mutated /* Step 2: Get TP53-mutated participants in LGG with FILTER = 'PASS' */ AS (SELECT DISTINCT \"ParticipantBarcode\" FROM \"PANCANCER_ATLAS_1\".\"PANCANCER_ATLAS_FILTERED\".\"MC3_MAF_V5_ONE_PER_TUMOR_SAMPLE\" WHERE \"Hugo_Symbol\" = 'TP53' AND \"Study\" = 'LGG' AND \"FILTER\" = 'PASS'), mutated_stats /* Step 3: Compute sums for mutated group (S_y, Q_y, N_y) */ AS (SELECT SUM(e.gene_expr) AS S_y, SUM(e.gene_expr * e.gene_expr) AS Q_y, COUNT(*) AS N_y FROM expr AS e INNER JOIN mutated AS m ON e.\"ParticipantBarcode\" = m.\"ParticipantBarcode\"), total_stats /* Step 4: Compute sums for all (S_total, Q_total, N_total) */ AS (SELECT SUM(gene_expr) AS S_total, SUM(gene_expr * gene_expr) AS Q_total, COUNT(*) AS N_total FROM expr), combined /* Step 5: Combine and compute t-score */ AS (SELECT t.S_total, t.Q_total, t.N_total, m.S_y, m.Q_y, m.N_y, (t.S_total - m.S_y) AS S_n, (t.Q_total - m.Q_y) AS Q_n, (t.N_total - m.N_y) AS N_n, CAST(m.S_y /* Means */ AS DOUBLE PRECISION) / m.N_y AS g_y, CAST((t.S_total - m.S_y) AS DOUBLE PRECISION) / (t.N_total - m.N_y) AS g_n, (CAST(1.0 AS DOUBLE PRECISION) / (m.N_y - 1)) /* Variances */ * (m.Q_y - CAST((m.S_y * m.S_y) AS DOUBLE PRECISION) / m.N_y) AS var_y, (CAST(1.0 AS DOUBLE PRECISION) / ((t.N_total - m.N_y) - 1)) * ((t.Q_total - m.Q_y) - CAST(((t.S_total - m.S_y) * (t.S_total - m.S_y)) AS DOUBLE PRECISION) / (t.N_total - m.N_y)) AS var_n FROM total_stats AS t CROSS JOIN mutated_stats AS m) SELECT ROUND(CAST(CAST((g_y - g_n) AS DOUBLE PRECISION) / SQRT(CAST(var_y AS DOUBLE PRECISION) / N_y + CAST(var_n AS DOUBLE PRECISION) / N_n) AS DECIMAL), 2) AS \"TSCORE\" FROM combined WHERE N_y >= 10 AND N_n >= 10 AND var_y > 0 AND var_n > 0") t0 t1
  := by first | sql_equiv | sorry

end N_sf_bq156_eq_1_2
