import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_bq251 — crossskill equivalence(s)

Question: I want to know the GitHub project URLs for the top 3 most downloaded PyPI packages based on download count. First, extract PyPI package metadata including name, version, and project URLs. Filter these URLs to only include those that link to GitHub repositories. Use a regular expression to clean the GitHub URLs by removing unnecessary parts like 'issues', 'pull', 'blob', and 'tree' paths, keeping only the main repository URL. For packages with multiple versions, use only the most recent version based on upload time. Join this data with download metrics to determine the most downloaded packages. Return only the cleaned GitHub repository URLs (without quotation marks) for the top 3 packages by total download count, ensuring that only packages with valid GitHub URLs are included in the results.

NOTE: uses WITH RECURSIVE / LATERAL / FLATTEN — may not elaborate yet.

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_bq251

CREATE TABLE DISTRIBUTION_METADATA («metadata_version» STRING, «name» STRING, «version» STRING, «summary» STRING, «description» STRING, «description_content_type» STRING, «author» STRING, «author_email» STRING, «maintainer» STRING, «maintainer_email» STRING, «license» STRING, «keywords» STRING, «classifiers» STRING, «platform» STRING, «home_page» STRING, «download_url» STRING, «requires_python» STRING, «requires» STRING, «provides» STRING, «obsoletes» STRING, «requires_dist» STRING, «provides_dist» STRING, «obsoletes_dist» STRING, «requires_external» STRING, «project_urls» STRING, «uploaded_via» STRING, «upload_time» INT, «filename» STRING, «size» INT, «path» STRING, «python_version» STRING, «packagetype» STRING, «comment_text» STRING, «has_signature» BOOL, «md5_digest» STRING, «sha256_digest» STRING, «blake2_256_digest» STRING)
CREATE TABLE FILE_DOWNLOADS («timestamp» INT, «country_code» STRING, «url» STRING, «project» STRING, «file» STRING, «details» STRING, «tls_protocol» STRING, «tls_cipher» STRING)

theorem eq_0_1 : ∀ t,
    (sql%([DISTRIBUTION_METADATA_schema, FILE_DOWNLOADS_schema]) "WITH latest_versions AS (/* For packages with multiple versions, use only the most recent version based on upload time */ SELECT \"name\", \"version\", \"project_urls\", \"upload_time\", ROW_NUMBER() OVER (PARTITION BY \"name\" ORDER BY \"upload_time\" DESC) AS rn FROM \"PYPI\".\"PYPI\".\"DISTRIBUTION_METADATA\"), github_urls AS (/* Extract and clean GitHub URLs from project_urls array */ SELECT DISTINCT lv.\"name\", REGEXP_REPLACE(TRIM(SUBSTRING(CAST(f.value AS TEXT) FROM POSITION(', ' IN CAST(f.value AS TEXT)) + 2)), '/(issues|pull|blob|tree)(/.*)?$', '', 'g') AS github_url FROM latest_versions AS lv, LATERAL UNNEST(input => lv.\"project_urls\") AS f(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE lv.rn = 1 AND CAST(f.value AS TEXT) ILIKE '%github.com%'), downloads AS (/* Count downloads per project */ SELECT \"project\", COUNT(*) AS download_count FROM \"PYPI\".\"PYPI\".\"FILE_DOWNLOADS\" GROUP BY \"project\") SELECT g.github_url AS GITHUB_URL FROM github_urls AS g JOIN downloads AS d ON g.\"name\" = d.\"project\" WHERE NOT g.github_url IS NULL AND g.github_url <> '' ORDER BY d.download_count DESC LIMIT 3") t ~= (sql%([DISTRIBUTION_METADATA_schema, FILE_DOWNLOADS_schema]) "WITH latest_versions AS (/* Get the most recent version per package using upload_time */ SELECT \"name\", \"version\", \"project_urls\", ROW_NUMBER() OVER (PARTITION BY \"name\" ORDER BY \"upload_time\" DESC) AS rn FROM \"PYPI\".\"PYPI\".\"DISTRIBUTION_METADATA\"), latest AS (SELECT \"name\", \"version\", \"project_urls\" FROM latest_versions WHERE rn = 1), github_urls AS (/* Extract and clean GitHub URLs from project_urls array */ /* project_urls entries are in \"Label, URL\" format */ SELECT DISTINCT l.\"name\", TRIM(TRAILING '/' FROM REGEXP_REPLACE(TRIM(REGEXP_EXTRACT(CAST(f.value AS TEXT), ',\\s*(.+)', 1, 1, 'e', 0)), '/(issues|pull|blob|tree)(/.*)?$', '', 'g')) AS cleaned_github_url FROM latest AS l, LATERAL UNNEST(input => l.\"project_urls\") AS f(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE LOWER(CAST(f.value AS TEXT)) LIKE '%github.com%'), downloads AS (/* Count downloads per project */ SELECT \"project\", COUNT(*) AS download_count FROM \"PYPI\".\"PYPI\".\"FILE_DOWNLOADS\" GROUP BY \"project\") SELECT g.cleaned_github_url AS GITHUB_URL FROM github_urls AS g JOIN downloads AS d ON LOWER(g.\"name\") = LOWER(d.\"project\") WHERE NOT g.cleaned_github_url IS NULL AND g.cleaned_github_url <> '' GROUP BY g.cleaned_github_url ORDER BY SUM(d.download_count) DESC LIMIT 3") t := by
  intro t; first | sql_equiv | sorry

theorem eq_0_2 :
    sql%([DISTRIBUTION_METADATA_schema, FILE_DOWNLOADS_schema]) "WITH latest_versions AS (/* For packages with multiple versions, use only the most recent version based on upload time */ SELECT \"name\", \"version\", \"project_urls\", \"upload_time\", ROW_NUMBER() OVER (PARTITION BY \"name\" ORDER BY \"upload_time\" DESC) AS rn FROM \"PYPI\".\"PYPI\".\"DISTRIBUTION_METADATA\"), github_urls AS (/* Extract and clean GitHub URLs from project_urls array */ SELECT DISTINCT lv.\"name\", REGEXP_REPLACE(TRIM(SUBSTRING(CAST(f.value AS TEXT) FROM POSITION(', ' IN CAST(f.value AS TEXT)) + 2)), '/(issues|pull|blob|tree)(/.*)?$', '', 'g') AS github_url FROM latest_versions AS lv, LATERAL UNNEST(input => lv.\"project_urls\") AS f(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE lv.rn = 1 AND CAST(f.value AS TEXT) ILIKE '%github.com%'), downloads AS (/* Count downloads per project */ SELECT \"project\", COUNT(*) AS download_count FROM \"PYPI\".\"PYPI\".\"FILE_DOWNLOADS\" GROUP BY \"project\") SELECT g.github_url AS GITHUB_URL FROM github_urls AS g JOIN downloads AS d ON g.\"name\" = d.\"project\" WHERE NOT g.github_url IS NULL AND g.github_url <> '' ORDER BY d.download_count DESC LIMIT 3" = sql%([DISTRIBUTION_METADATA_schema, FILE_DOWNLOADS_schema]) "WITH latest_versions AS (/* Get the latest version per package */ SELECT \"name\", \"version\", \"project_urls\", \"upload_time\", ROW_NUMBER() OVER (PARTITION BY \"name\" ORDER BY \"upload_time\" DESC) AS rn FROM \"PYPI\".\"PYPI\".\"DISTRIBUTION_METADATA\"), github_urls AS (/* Extract GitHub URLs from project_urls array for latest versions only */ SELECT DISTINCT lv.\"name\" AS project_name, REGEXP_REPLACE(TRIM(SPLIT_PART(CAST(f.value AS TEXT), ', ', 2)), '(https://github\\.com/[^/]+/[^/]+)(/.*)?', '\\1', 'g') AS github_url /* Extract URL part after \", \" and clean it */ FROM latest_versions AS lv, LATERAL UNNEST(input => lv.\"project_urls\") AS f(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE lv.rn = 1 AND CAST(f.value AS TEXT) ILIKE '%github.com%'), downloads AS (/* Count downloads per project */ SELECT \"project\", COUNT(*) AS download_count FROM \"PYPI\".\"PYPI\".\"FILE_DOWNLOADS\" GROUP BY \"project\"), ranked AS (SELECT DISTINCT gu.github_url, d.download_count, ROW_NUMBER() OVER (ORDER BY d.download_count DESC) AS rn FROM github_urls AS gu INNER JOIN downloads AS d ON LOWER(d.\"project\") = LOWER(gu.project_name)) SELECT github_url AS \"github_url\" FROM ranked WHERE rn <= 3 ORDER BY rn" := by
  first | sql_equiv | sorry

theorem eq_0_3 : ∀ t,
    (sql%([DISTRIBUTION_METADATA_schema, FILE_DOWNLOADS_schema]) "WITH latest_versions AS (/* For packages with multiple versions, use only the most recent version based on upload time */ SELECT \"name\", \"version\", \"project_urls\", \"upload_time\", ROW_NUMBER() OVER (PARTITION BY \"name\" ORDER BY \"upload_time\" DESC) AS rn FROM \"PYPI\".\"PYPI\".\"DISTRIBUTION_METADATA\"), github_urls AS (/* Extract and clean GitHub URLs from project_urls array */ SELECT DISTINCT lv.\"name\", REGEXP_REPLACE(TRIM(SUBSTRING(CAST(f.value AS TEXT) FROM POSITION(', ' IN CAST(f.value AS TEXT)) + 2)), '/(issues|pull|blob|tree)(/.*)?$', '', 'g') AS github_url FROM latest_versions AS lv, LATERAL UNNEST(input => lv.\"project_urls\") AS f(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE lv.rn = 1 AND CAST(f.value AS TEXT) ILIKE '%github.com%'), downloads AS (/* Count downloads per project */ SELECT \"project\", COUNT(*) AS download_count FROM \"PYPI\".\"PYPI\".\"FILE_DOWNLOADS\" GROUP BY \"project\") SELECT g.github_url AS GITHUB_URL FROM github_urls AS g JOIN downloads AS d ON g.\"name\" = d.\"project\" WHERE NOT g.github_url IS NULL AND g.github_url <> '' ORDER BY d.download_count DESC LIMIT 3") t ~= (sql%([DISTRIBUTION_METADATA_schema, FILE_DOWNLOADS_schema]) "WITH downloads AS (SELECT \"project\", COUNT(*) AS download_count FROM \"PYPI\".\"PYPI\".\"FILE_DOWNLOADS\" GROUP BY \"project\"), github_urls AS (SELECT DISTINCT dm.\"name\", REGEXP_EXTRACT(TRIM(SPLIT_PART(CAST(f.value AS TEXT), ', ', 2)), 'https://github\\.com/[^/]+/[^/]+', 0) AS github_url FROM \"PYPI\".\"PYPI\".\"DISTRIBUTION_METADATA\" AS dm, LATERAL UNNEST(input => dm.\"project_urls\") AS f(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE CAST(f.value AS TEXT) LIKE '%github.com%'), ranked AS (SELECT g.github_url AS GITHUB_URL, d.download_count, ROW_NUMBER() OVER (ORDER BY d.download_count DESC, g.github_url) AS rn FROM github_urls AS g JOIN downloads AS d ON g.\"name\" = d.\"project\" WHERE NOT g.github_url IS NULL GROUP BY g.github_url, d.download_count) SELECT GITHUB_URL FROM ranked WHERE rn <= 3 ORDER BY rn") t := by
  intro t; first | sql_equiv | sorry

theorem eq_1_2 : ∀ t,
    (sql%([DISTRIBUTION_METADATA_schema, FILE_DOWNLOADS_schema]) "WITH latest_versions AS (/* Get the most recent version per package using upload_time */ SELECT \"name\", \"version\", \"project_urls\", ROW_NUMBER() OVER (PARTITION BY \"name\" ORDER BY \"upload_time\" DESC) AS rn FROM \"PYPI\".\"PYPI\".\"DISTRIBUTION_METADATA\"), latest AS (SELECT \"name\", \"version\", \"project_urls\" FROM latest_versions WHERE rn = 1), github_urls AS (/* Extract and clean GitHub URLs from project_urls array */ /* project_urls entries are in \"Label, URL\" format */ SELECT DISTINCT l.\"name\", TRIM(TRAILING '/' FROM REGEXP_REPLACE(TRIM(REGEXP_EXTRACT(CAST(f.value AS TEXT), ',\\s*(.+)', 1, 1, 'e', 0)), '/(issues|pull|blob|tree)(/.*)?$', '', 'g')) AS cleaned_github_url FROM latest AS l, LATERAL UNNEST(input => l.\"project_urls\") AS f(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE LOWER(CAST(f.value AS TEXT)) LIKE '%github.com%'), downloads AS (/* Count downloads per project */ SELECT \"project\", COUNT(*) AS download_count FROM \"PYPI\".\"PYPI\".\"FILE_DOWNLOADS\" GROUP BY \"project\") SELECT g.cleaned_github_url AS GITHUB_URL FROM github_urls AS g JOIN downloads AS d ON LOWER(g.\"name\") = LOWER(d.\"project\") WHERE NOT g.cleaned_github_url IS NULL AND g.cleaned_github_url <> '' GROUP BY g.cleaned_github_url ORDER BY SUM(d.download_count) DESC LIMIT 3") t ~= (sql%([DISTRIBUTION_METADATA_schema, FILE_DOWNLOADS_schema]) "WITH latest_versions AS (/* Get the latest version per package */ SELECT \"name\", \"version\", \"project_urls\", \"upload_time\", ROW_NUMBER() OVER (PARTITION BY \"name\" ORDER BY \"upload_time\" DESC) AS rn FROM \"PYPI\".\"PYPI\".\"DISTRIBUTION_METADATA\"), github_urls AS (/* Extract GitHub URLs from project_urls array for latest versions only */ SELECT DISTINCT lv.\"name\" AS project_name, REGEXP_REPLACE(TRIM(SPLIT_PART(CAST(f.value AS TEXT), ', ', 2)), '(https://github\\.com/[^/]+/[^/]+)(/.*)?', '\\1', 'g') AS github_url /* Extract URL part after \", \" and clean it */ FROM latest_versions AS lv, LATERAL UNNEST(input => lv.\"project_urls\") AS f(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE lv.rn = 1 AND CAST(f.value AS TEXT) ILIKE '%github.com%'), downloads AS (/* Count downloads per project */ SELECT \"project\", COUNT(*) AS download_count FROM \"PYPI\".\"PYPI\".\"FILE_DOWNLOADS\" GROUP BY \"project\"), ranked AS (SELECT DISTINCT gu.github_url, d.download_count, ROW_NUMBER() OVER (ORDER BY d.download_count DESC) AS rn FROM github_urls AS gu INNER JOIN downloads AS d ON LOWER(d.\"project\") = LOWER(gu.project_name)) SELECT github_url AS \"github_url\" FROM ranked WHERE rn <= 3 ORDER BY rn") t := by
  intro t; first | sql_equiv | sorry

theorem eq_1_3 : ∀ t,
    (sql%([DISTRIBUTION_METADATA_schema, FILE_DOWNLOADS_schema]) "WITH latest_versions AS (/* Get the most recent version per package using upload_time */ SELECT \"name\", \"version\", \"project_urls\", ROW_NUMBER() OVER (PARTITION BY \"name\" ORDER BY \"upload_time\" DESC) AS rn FROM \"PYPI\".\"PYPI\".\"DISTRIBUTION_METADATA\"), latest AS (SELECT \"name\", \"version\", \"project_urls\" FROM latest_versions WHERE rn = 1), github_urls AS (/* Extract and clean GitHub URLs from project_urls array */ /* project_urls entries are in \"Label, URL\" format */ SELECT DISTINCT l.\"name\", TRIM(TRAILING '/' FROM REGEXP_REPLACE(TRIM(REGEXP_EXTRACT(CAST(f.value AS TEXT), ',\\s*(.+)', 1, 1, 'e', 0)), '/(issues|pull|blob|tree)(/.*)?$', '', 'g')) AS cleaned_github_url FROM latest AS l, LATERAL UNNEST(input => l.\"project_urls\") AS f(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE LOWER(CAST(f.value AS TEXT)) LIKE '%github.com%'), downloads AS (/* Count downloads per project */ SELECT \"project\", COUNT(*) AS download_count FROM \"PYPI\".\"PYPI\".\"FILE_DOWNLOADS\" GROUP BY \"project\") SELECT g.cleaned_github_url AS GITHUB_URL FROM github_urls AS g JOIN downloads AS d ON LOWER(g.\"name\") = LOWER(d.\"project\") WHERE NOT g.cleaned_github_url IS NULL AND g.cleaned_github_url <> '' GROUP BY g.cleaned_github_url ORDER BY SUM(d.download_count) DESC LIMIT 3") t ~= (sql%([DISTRIBUTION_METADATA_schema, FILE_DOWNLOADS_schema]) "WITH downloads AS (SELECT \"project\", COUNT(*) AS download_count FROM \"PYPI\".\"PYPI\".\"FILE_DOWNLOADS\" GROUP BY \"project\"), github_urls AS (SELECT DISTINCT dm.\"name\", REGEXP_EXTRACT(TRIM(SPLIT_PART(CAST(f.value AS TEXT), ', ', 2)), 'https://github\\.com/[^/]+/[^/]+', 0) AS github_url FROM \"PYPI\".\"PYPI\".\"DISTRIBUTION_METADATA\" AS dm, LATERAL UNNEST(input => dm.\"project_urls\") AS f(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE CAST(f.value AS TEXT) LIKE '%github.com%'), ranked AS (SELECT g.github_url AS GITHUB_URL, d.download_count, ROW_NUMBER() OVER (ORDER BY d.download_count DESC, g.github_url) AS rn FROM github_urls AS g JOIN downloads AS d ON g.\"name\" = d.\"project\" WHERE NOT g.github_url IS NULL GROUP BY g.github_url, d.download_count) SELECT GITHUB_URL FROM ranked WHERE rn <= 3 ORDER BY rn") t := by
  intro t; first | sql_equiv | sorry

theorem eq_2_3 : ∀ t,
    (sql%([DISTRIBUTION_METADATA_schema, FILE_DOWNLOADS_schema]) "WITH latest_versions AS (/* Get the latest version per package */ SELECT \"name\", \"version\", \"project_urls\", \"upload_time\", ROW_NUMBER() OVER (PARTITION BY \"name\" ORDER BY \"upload_time\" DESC) AS rn FROM \"PYPI\".\"PYPI\".\"DISTRIBUTION_METADATA\"), github_urls AS (/* Extract GitHub URLs from project_urls array for latest versions only */ SELECT DISTINCT lv.\"name\" AS project_name, REGEXP_REPLACE(TRIM(SPLIT_PART(CAST(f.value AS TEXT), ', ', 2)), '(https://github\\.com/[^/]+/[^/]+)(/.*)?', '\\1', 'g') AS github_url /* Extract URL part after \", \" and clean it */ FROM latest_versions AS lv, LATERAL UNNEST(input => lv.\"project_urls\") AS f(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE lv.rn = 1 AND CAST(f.value AS TEXT) ILIKE '%github.com%'), downloads AS (/* Count downloads per project */ SELECT \"project\", COUNT(*) AS download_count FROM \"PYPI\".\"PYPI\".\"FILE_DOWNLOADS\" GROUP BY \"project\"), ranked AS (SELECT DISTINCT gu.github_url, d.download_count, ROW_NUMBER() OVER (ORDER BY d.download_count DESC) AS rn FROM github_urls AS gu INNER JOIN downloads AS d ON LOWER(d.\"project\") = LOWER(gu.project_name)) SELECT github_url AS \"github_url\" FROM ranked WHERE rn <= 3 ORDER BY rn") t ~= (sql%([DISTRIBUTION_METADATA_schema, FILE_DOWNLOADS_schema]) "WITH downloads AS (SELECT \"project\", COUNT(*) AS download_count FROM \"PYPI\".\"PYPI\".\"FILE_DOWNLOADS\" GROUP BY \"project\"), github_urls AS (SELECT DISTINCT dm.\"name\", REGEXP_EXTRACT(TRIM(SPLIT_PART(CAST(f.value AS TEXT), ', ', 2)), 'https://github\\.com/[^/]+/[^/]+', 0) AS github_url FROM \"PYPI\".\"PYPI\".\"DISTRIBUTION_METADATA\" AS dm, LATERAL UNNEST(input => dm.\"project_urls\") AS f(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE CAST(f.value AS TEXT) LIKE '%github.com%'), ranked AS (SELECT g.github_url AS GITHUB_URL, d.download_count, ROW_NUMBER() OVER (ORDER BY d.download_count DESC, g.github_url) AS rn FROM github_urls AS g JOIN downloads AS d ON g.\"name\" = d.\"project\" WHERE NOT g.github_url IS NULL GROUP BY g.github_url, d.download_count) SELECT GITHUB_URL FROM ranked WHERE rn <= 3 ORDER BY rn") t := by
  intro t; first | sql_equiv | sorry

end Bench_sf_bq251
