import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_bq259_eq_0_2

CREATE TABLE ORDERS («order_id» INT, «user_id» INT, «status» STRING, «gender» STRING, «created_at» INT, «returned_at» INT, «shipped_at» INT, «delivered_at» INT, «num_of_item» INT)

theorem eq (t0 : TableRel ORDERS_schema) :
    (sql%([ORDERS_schema]) "WITH orders_converted AS (SELECT \"user_id\", TO_TIMESTAMP(CAST(\"created_at\" AS DOUBLE PRECISION) / 1000000) AS order_ts, DATE_TRUNC('MONTH', TO_TIMESTAMP(CAST(\"created_at\" AS DOUBLE PRECISION) / 1000000)) AS order_month FROM \"THELOOK_ECOMMERCE\".\"THELOOK_ECOMMERCE\".\"ORDERS\" WHERE TO_TIMESTAMP(CAST(\"created_at\" AS DOUBLE PRECISION) / 1000000) <= '2022-12-31 23:59:59'), first_purchase AS (SELECT \"user_id\", MIN(order_month) AS first_month FROM orders_converted GROUP BY \"user_id\"), user_order_months AS (SELECT DISTINCT o.\"user_id\", o.order_month FROM orders_converted AS o), cohort_data AS (SELECT fp.first_month AS cohort_month, fp.\"user_id\", CAST(EXTRACT(year FROM AGE(CAST(uom.order_month AS TIMESTAMP), CAST(fp.first_month AS TIMESTAMP))) * 12 + EXTRACT(month FROM AGE(CAST(uom.order_month AS TIMESTAMP), CAST(fp.first_month AS TIMESTAMP))) AS BIGINT) AS months_since_first FROM first_purchase AS fp JOIN user_order_months AS uom ON fp.\"user_id\" = uom.\"user_id\"), cohort_sizes AS (SELECT cohort_month, COUNT(DISTINCT \"user_id\") AS cohort_size FROM cohort_data GROUP BY cohort_month), cohort_activity AS (SELECT cohort_month, months_since_first, COUNT(DISTINCT \"user_id\") AS active_users FROM cohort_data WHERE months_since_first BETWEEN 0 AND 3 GROUP BY cohort_month, months_since_first) SELECT TO_CHAR(cs.cohort_month, 'YYYY-MM') AS COHORT_MONTH, cs.cohort_size AS COHORT_SIZE, ROUND(CAST(100.0 * COALESCE(m0.active_users, 0) AS DOUBLE PRECISION) / cs.cohort_size, 6) AS PCT_MONTH_1, ROUND(CAST(100.0 * COALESCE(m1.active_users, 0) AS DOUBLE PRECISION) / cs.cohort_size, 6) AS PCT_MONTH_2, ROUND(CAST(100.0 * COALESCE(m2.active_users, 0) AS DOUBLE PRECISION) / cs.cohort_size, 6) AS PCT_MONTH_3, ROUND(CAST(100.0 * COALESCE(m3.active_users, 0) AS DOUBLE PRECISION) / cs.cohort_size, 6) AS PCT_MONTH_4 FROM cohort_sizes AS cs LEFT JOIN cohort_activity AS m0 ON cs.cohort_month = m0.cohort_month AND m0.months_since_first = 0 LEFT JOIN cohort_activity AS m1 ON cs.cohort_month = m1.cohort_month AND m1.months_since_first = 1 LEFT JOIN cohort_activity AS m2 ON cs.cohort_month = m2.cohort_month AND m2.months_since_first = 2 LEFT JOIN cohort_activity AS m3 ON cs.cohort_month = m3.cohort_month AND m3.months_since_first = 3 ORDER BY cs.cohort_month") t0
  ~= (sql%([ORDERS_schema]) "WITH orders_with_ts AS (SELECT \"order_id\", \"user_id\", DATE_TRUNC('MONTH', TO_TIMESTAMP(CAST(\"created_at\" AS DOUBLE PRECISION) / 1000000)) AS order_month FROM \"THELOOK_ECOMMERCE\".\"THELOOK_ECOMMERCE\".\"ORDERS\" WHERE TO_TIMESTAMP(CAST(\"created_at\" AS DOUBLE PRECISION) / 1000000) <= '2022-12-31 23:59:59'), first_purchase AS (SELECT \"user_id\", MIN(order_month) AS cohort_month FROM orders_with_ts GROUP BY \"user_id\"), user_activity AS (SELECT DISTINCT o.\"user_id\", fp.cohort_month, o.order_month, CAST(EXTRACT(year FROM AGE(CAST(o.order_month AS TIMESTAMP), CAST(fp.cohort_month AS TIMESTAMP))) * 12 + EXTRACT(month FROM AGE(CAST(o.order_month AS TIMESTAMP), CAST(fp.cohort_month AS TIMESTAMP))) AS BIGINT) AS month_offset FROM orders_with_ts AS o JOIN first_purchase AS fp ON o.\"user_id\" = fp.\"user_id\"), cohort_sizes AS (SELECT cohort_month, COUNT(DISTINCT \"user_id\") AS cohort_size FROM first_purchase GROUP BY cohort_month), retention AS (SELECT cohort_month, month_offset, COUNT(DISTINCT \"user_id\") AS active_users FROM user_activity WHERE month_offset BETWEEN 0 AND 3 GROUP BY cohort_month, month_offset) SELECT TO_CHAR(cs.cohort_month, 'YYYY-MM') AS \"COHORT_MONTH\", cs.cohort_size AS \"COHORT_SIZE\", ROUND(CAST(100.0 * COALESCE(MAX(CASE WHEN r.month_offset = 0 THEN r.active_users END), 0) AS DOUBLE PRECISION) / cs.cohort_size, 2) AS \"PCT_MONTH_1\", ROUND(CAST(100.0 * COALESCE(MAX(CASE WHEN r.month_offset = 1 THEN r.active_users END), 0) AS DOUBLE PRECISION) / cs.cohort_size, 2) AS \"PCT_MONTH_2\", ROUND(CAST(100.0 * COALESCE(MAX(CASE WHEN r.month_offset = 2 THEN r.active_users END), 0) AS DOUBLE PRECISION) / cs.cohort_size, 2) AS \"PCT_MONTH_3\", ROUND(CAST(100.0 * COALESCE(MAX(CASE WHEN r.month_offset = 3 THEN r.active_users END), 0) AS DOUBLE PRECISION) / cs.cohort_size, 2) AS \"PCT_MONTH_4\" FROM cohort_sizes AS cs LEFT JOIN retention AS r ON cs.cohort_month = r.cohort_month GROUP BY cs.cohort_month, cs.cohort_size ORDER BY cs.cohort_month") t0
  := by first | sql_equiv | sorry

end N_sf_bq259_eq_0_2
