import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_bq461_eq_1_2

CREATE TABLE MBB_PBP_SR («game_id» STRING, «load_timestamp» INT, «season» INT, «status» STRING, «scheduled_date» INT, «venue_id» STRING, «venue_name» STRING, «venue_city» STRING, «venue_state» STRING, «venue_address» STRING, «venue_zip» STRING, «venue_country» STRING, «venue_capacity» INT, «attendance» INT, «neutral_site» BOOL, «conference_game» BOOL, «tournament» STRING, «tournament_type» STRING, «round» STRING, «game_no» STRING, «away_market» STRING, «away_name» STRING, «away_id» STRING, «away_alias» STRING, «away_conf_name» STRING, «away_conf_alias» STRING, «away_division_name» STRING, «away_division_alias» STRING, «away_league_name» STRING, «home_market» STRING, «home_name» STRING, «home_id» STRING, «home_alias» STRING, «home_conf_name» STRING, «home_conf_alias» STRING, «home_division_name» STRING, «home_division_alias» STRING, «home_league_name» STRING, «period» INT, «game_clock» STRING, «elapsed_time_sec» INT, «possession_arrow» STRING, «team_name» STRING, «team_market» STRING, «team_id» STRING, «team_alias» STRING, «team_conf_name» STRING, «team_conf_alias» STRING, «team_division_name» STRING, «team_division_alias» STRING, «team_league_name» STRING, «team_basket» STRING, «possession_team_id» STRING, «player_id» STRING, «player_full_name» STRING, «jersey_num» INT, «event_id» STRING, «timestamp» INT, «event_description» STRING, «event_coord_x» FLOAT, «event_coord_y» FLOAT, «event_type» STRING, «type» STRING, «shot_made» BOOL, «shot_type» STRING, «shot_subtype» STRING, «three_point_shot» BOOL, «points_scored» FLOAT, «turnover_type» STRING, «rebound_type» STRING, «timeout_duration» FLOAT)

theorem eq (t0 : TableRel MBB_PBP_SR_schema) :
    (sql%([MBB_PBP_SR_schema]) "WITH game AS (SELECT \"game_id\" FROM \"NCAA_BASKETBALL\".\"NCAA_BASKETBALL\".\"MBB_GAMES_SR\" WHERE \"h_name\" = 'Wildcats' AND \"a_name\" = 'Fighting Irish' AND \"season\" = 2014 LIMIT 1), scoring_plays AS (SELECT p.\"game_clock\", p.\"team_name\", p.\"event_description\", p.\"points_scored\", p.\"elapsed_time_sec\", p.\"event_id\" FROM \"NCAA_BASKETBALL\".\"NCAA_BASKETBALL\".\"MBB_PBP_SR\" AS p JOIN game AS g ON p.\"game_id\" = g.\"game_id\" WHERE NOT p.\"points_scored\" IS NULL AND p.\"points_scored\" > 0) SELECT \"game_clock\", SUM(CASE WHEN \"team_name\" = 'Wildcats' THEN \"points_scored\" ELSE 0 END) OVER (ORDER BY \"elapsed_time_sec\" ASC, \"event_id\" ASC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS \"WILDCATS_SCORE\", SUM(CASE WHEN \"team_name\" = 'Fighting Irish' THEN \"points_scored\" ELSE 0 END) OVER (ORDER BY \"elapsed_time_sec\" ASC, \"event_id\" ASC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS \"FIGHTING_IRISH_SCORE\", \"team_name\", \"event_description\" FROM scoring_plays ORDER BY \"elapsed_time_sec\" ASC, \"event_id\" ASC") t0
  ~= (sql%([MBB_PBP_SR_schema]) "WITH scoring_plays AS (SELECT \"game_clock\", \"team_name\", \"event_description\", \"points_scored\", \"elapsed_time_sec\", \"event_id\", SUM(CASE WHEN \"team_name\" = 'Wildcats' THEN \"points_scored\" ELSE 0 END) OVER (ORDER BY \"elapsed_time_sec\", \"event_id\" ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS WILDCATS_SCORE, SUM(CASE WHEN \"team_name\" = 'Fighting Irish' THEN \"points_scored\" ELSE 0 END) OVER (ORDER BY \"elapsed_time_sec\", \"event_id\" ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS FIGHTING_IRISH_SCORE_RAW, SUM(CASE WHEN \"team_name\" = 'Fighting Irish' THEN 1 ELSE 0 END) OVER (ORDER BY \"elapsed_time_sec\", \"event_id\" ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS fi_count FROM \"NCAA_BASKETBALL\".\"NCAA_BASKETBALL\".\"MBB_PBP_SR\" WHERE \"game_id\" = '95cda731-b593-42cd-8573-621a3d1369dc' AND \"points_scored\" > 0) SELECT \"game_clock\", WILDCATS_SCORE, CASE WHEN fi_count = 0 THEN NULL ELSE FIGHTING_IRISH_SCORE_RAW END AS FIGHTING_IRISH_SCORE, \"team_name\", \"event_description\" FROM scoring_plays ORDER BY \"elapsed_time_sec\", \"event_id\"") t0
  := by first | sql_equiv | sorry

end N_sf_bq461_eq_1_2
