import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_bq169_eq_1_2

CREATE TABLE CYTOCONVERTED («RefNo» INT, «CaseNo» STRING, «InvNo» INT, «Clone» INT, «Chr» STRING, «ChrOrd» INT, «Start» INT, «End» INT, «Type» STRING, «CellsPresent» STRING)
CREATE TABLE KARYCLONE («RefNo» INT, «CaseNo» STRING, «InvNo» INT, «CloneNo» INT, «ChromoMin» INT, «ChromoMax» INT, «CloneShort» STRING, «CloneLong» STRING, «CloneLength» INT, «Sole» STRING)

theorem eq (t0 : TableRel CYTOCONVERTED_schema) (t1 : TableRel KARYCLONE_schema) :
    (sql%([CYTOCONVERTED_schema, KARYCLONE_schema]) "SELECT DISTINCT c13.\"RefNo\", c13.\"CaseNo\", c13.\"InvNo\", c13.\"Clone\", k.\"CloneShort\" AS \"KaryotypeShortDescription\", c13.\"ChrOrd\" AS \"Chr13_ChrOrd\", c13.\"Start\" AS \"Chr13_Start\", c13.\"End\" AS \"Chr13_End\", c17.\"ChrOrd\" AS \"Chr17_ChrOrd\", c17.\"Start\" AS \"Chr17_Start\", c17.\"End\" AS \"Chr17_End\", c11.\"ChrOrd\" AS \"Chr11_ChrOrd\", c11.\"Start\" AS \"Chr11_Start\", c11.\"End\" AS \"Chr11_End\" FROM \"MITELMAN\".\"PROD\".\"CYTOCONVERTED\" AS c13 JOIN \"MITELMAN\".\"PROD\".\"CYTOCONVERTED\" AS c17 ON c13.\"RefNo\" = c17.\"RefNo\" AND c13.\"CaseNo\" = c17.\"CaseNo\" AND c13.\"InvNo\" = c17.\"InvNo\" AND c13.\"Clone\" = c17.\"Clone\" JOIN \"MITELMAN\".\"PROD\".\"CYTOCONVERTED\" AS c11 ON c13.\"RefNo\" = c11.\"RefNo\" AND c13.\"CaseNo\" = c11.\"CaseNo\" AND c13.\"InvNo\" = c11.\"InvNo\" AND c13.\"Clone\" = c11.\"Clone\" JOIN \"MITELMAN\".\"PROD\".\"KARYCLONE\" AS k ON c13.\"RefNo\" = k.\"RefNo\" AND c13.\"CaseNo\" = k.\"CaseNo\" AND c13.\"InvNo\" = k.\"InvNo\" AND c13.\"Clone\" = k.\"CloneNo\" WHERE c13.\"Chr\" = 'chr13' AND c13.\"Type\" = 'Loss' AND c13.\"Start\" <= 48481890 AND c13.\"End\" >= 48303751 AND c17.\"Chr\" = 'chr17' AND c17.\"Type\" = 'Loss' AND c17.\"Start\" <= 7687490 AND c17.\"End\" >= 7668421 AND c11.\"Chr\" = 'chr11' AND c11.\"Type\" = 'Gain' AND c11.\"Start\" <= 108369102 AND c11.\"End\" >= 108223067 ORDER BY c13.\"RefNo\", c13.\"CaseNo\", c13.\"InvNo\", c13.\"Clone\"") t0 t1
  ~= (sql%([CYTOCONVERTED_schema, KARYCLONE_schema]) "WITH chr13_loss AS (SELECT \"RefNo\", \"CaseNo\", \"InvNo\", \"Clone\", \"ChrOrd\", \"Start\", \"End\" FROM \"MITELMAN\".\"PROD\".\"CYTOCONVERTED\" WHERE \"Type\" = 'Loss' AND \"ChrOrd\" = 13 AND \"Start\" <= 48303751 AND \"End\" >= 48481890), chr17_loss AS (SELECT \"RefNo\", \"CaseNo\", \"InvNo\", \"Clone\", \"ChrOrd\", \"Start\", \"End\" FROM \"MITELMAN\".\"PROD\".\"CYTOCONVERTED\" WHERE \"Type\" = 'Loss' AND \"ChrOrd\" = 17 AND \"Start\" <= 7668421 AND \"End\" >= 7687490), chr11_gain AS (SELECT \"RefNo\", \"CaseNo\", \"InvNo\", \"Clone\", \"ChrOrd\", \"Start\", \"End\" FROM \"MITELMAN\".\"PROD\".\"CYTOCONVERTED\" WHERE \"Type\" = 'Gain' AND \"ChrOrd\" = 11 AND \"Start\" <= 108223067 AND \"End\" >= 108369102) SELECT DISTINCT c13.\"RefNo\" AS \"RefNo\", c13.\"CaseNo\" AS \"CaseNo\", c13.\"InvNo\" AS \"InvNo\", c13.\"Clone\" AS \"Clone\", kc.\"CloneShort\" AS \"KaryotypeShortDescription\", c13.\"ChrOrd\" AS \"Chr13_ChrOrd\", c13.\"Start\" AS \"Chr13_Start\", c13.\"End\" AS \"Chr13_End\", c17.\"ChrOrd\" AS \"Chr17_ChrOrd\", c17.\"Start\" AS \"Chr17_Start\", c17.\"End\" AS \"Chr17_End\", c11.\"ChrOrd\" AS \"Chr11_ChrOrd\", c11.\"Start\" AS \"Chr11_Start\", c11.\"End\" AS \"Chr11_End\" FROM chr13_loss AS c13 JOIN chr17_loss AS c17 ON c13.\"RefNo\" = c17.\"RefNo\" AND c13.\"CaseNo\" = c17.\"CaseNo\" AND c13.\"InvNo\" = c17.\"InvNo\" AND c13.\"Clone\" = c17.\"Clone\" JOIN chr11_gain AS c11 ON c13.\"RefNo\" = c11.\"RefNo\" AND c13.\"CaseNo\" = c11.\"CaseNo\" AND c13.\"InvNo\" = c11.\"InvNo\" AND c13.\"Clone\" = c11.\"Clone\" JOIN \"MITELMAN\".\"PROD\".\"KARYCLONE\" AS kc ON c13.\"RefNo\" = kc.\"RefNo\" AND c13.\"CaseNo\" = kc.\"CaseNo\" AND c13.\"InvNo\" = kc.\"InvNo\" AND c13.\"Clone\" = kc.\"CloneNo\" ORDER BY c13.\"RefNo\", c13.\"CaseNo\", c13.\"InvNo\", c13.\"Clone\"") t0 t1
  := by first | sql_equiv | sorry

end N_sf_bq169_eq_1_2
