import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_bq051_eq_0_2

CREATE TABLE GHCND_2016 («id» STRING, «date» STRING, «element» STRING, «value» FLOAT, «mflag» STRING, «qflag» STRING, «sflag» STRING, «time» STRING, «source_url» STRING, «etl_timestamp» INT)
CREATE TABLE GHCND_STATIONS («id» STRING, «latitude» FLOAT, «longitude» FLOAT, «elevation» FLOAT, «state» STRING, «name» STRING, «gsn_flag» STRING, «hcn_crn_flag» STRING, «wmoid» INT, «source_url» STRING, «etl_timestamp» INT)
CREATE TABLE CITIBIKE_TRIPS («tripduration» INT, «starttime» INT, «stoptime» INT, «start_station_id» INT, «start_station_name» STRING, «start_station_latitude» FLOAT, «start_station_longitude» FLOAT, «end_station_id» INT, «end_station_name» STRING, «end_station_latitude» FLOAT, «end_station_longitude» FLOAT, «bikeid» INT, «usertype» STRING, «birth_year» INT, «gender» STRING)

theorem eq (t0 : TableRel GHCND_2016_schema) (t1 : TableRel GHCND_STATIONS_schema) (t2 : TableRel CITIBIKE_TRIPS_schema) :
    (sql%([GHCND_2016_schema, GHCND_STATIONS_schema, CITIBIKE_TRIPS_schema]) "WITH nearest_station AS (SELECT s.\"id\" AS station_id FROM \"NEW_YORK_GHCN\".\"GHCN_D\".\"GHCND_STATIONS\" AS s JOIN \"NEW_YORK_GHCN\".\"GHCN_D\".\"GHCND_2016\" AS w ON s.\"id\" = w.\"id\" WHERE w.\"element\" = 'PRCP' AND w.\"qflag\" IS NULL AND CAST(ST_DISTANCE(ST_POINT(s.\"longitude\", s.\"latitude\"), ST_POINT(-74.0060, 40.7128)) AS DOUBLE PRECISION) / 1000 <= 50 GROUP BY s.\"id\", s.\"longitude\", s.\"latitude\" ORDER BY ST_DISTANCE(ST_POINT(s.\"longitude\", s.\"latitude\"), ST_POINT(-74.0060, 40.7128)) LIMIT 1), weather AS (SELECT w.\"date\" AS weather_date, CAST(w.\"value\" AS DOUBLE PRECISION) / 10.0 AS precip_mm FROM \"NEW_YORK_GHCN\".\"GHCN_D\".\"GHCND_2016\" AS w JOIN nearest_station AS ns ON w.\"id\" = ns.station_id WHERE w.\"element\" = 'PRCP' AND w.\"qflag\" IS NULL), daily_trips AS (SELECT CAST(TO_TIMESTAMP(CAST(\"starttime\" AS DOUBLE PRECISION) / 1000000) AS DATE) AS trip_date, COUNT(*) AS num_trips FROM \"NEW_YORK_GHCN\".\"NEW_YORK\".\"CITIBIKE_TRIPS\" WHERE CAST(TO_TIMESTAMP(CAST(\"starttime\" AS DOUBLE PRECISION) / 1000000) AS DATE) BETWEEN '2016-01-01' AND '2016-12-31' GROUP BY trip_date) SELECT CASE WHEN w.precip_mm > 5 THEN 'rainy' ELSE 'non-rainy' END AS RAIN_STATUS, AVG(dt.num_trips) AS AVG_DAILY_TRIPS FROM daily_trips AS dt JOIN weather AS w ON dt.trip_date = w.weather_date GROUP BY RAIN_STATUS ORDER BY RAIN_STATUS") t0 t1 t2
  ~= (sql%([GHCND_2016_schema, GHCND_STATIONS_schema, CITIBIKE_TRIPS_schema]) "WITH nearest_station AS (SELECT \"id\", 2 * 6371 * ASIN(SQRT(POWER(SIN(CAST(RADIANS(\"latitude\" - 40.7128) AS DOUBLE PRECISION) / 2), 2) + COS(RADIANS(40.7128)) * COS(RADIANS(\"latitude\")) * POWER(SIN(CAST(RADIANS(\"longitude\" - (-74.0060)) AS DOUBLE PRECISION) / 2), 2))) AS dist_km FROM \"NEW_YORK_GHCN\".\"GHCN_D\".\"GHCND_STATIONS\" HAVING dist_km < 50 ORDER BY dist_km ASC), stations_with_data AS (SELECT ns.\"id\", ns.dist_km FROM nearest_station AS ns WHERE EXISTS(SELECT 1 FROM \"NEW_YORK_GHCN\".\"GHCN_D\".\"GHCND_2016\" AS g WHERE g.\"id\" = ns.\"id\" AND g.\"element\" = 'PRCP' AND (g.\"qflag\" IS NULL OR g.\"qflag\" = '')) ORDER BY ns.dist_km ASC LIMIT 1), weather AS (SELECT g.\"date\", CAST(SUM(g.\"value\") AS DOUBLE PRECISION) / 10.0 AS prcp_mm FROM \"NEW_YORK_GHCN\".\"GHCN_D\".\"GHCND_2016\" AS g JOIN stations_with_data AS s ON g.\"id\" = s.\"id\" WHERE g.\"element\" = 'PRCP' AND (g.\"qflag\" IS NULL OR g.\"qflag\" = '') GROUP BY g.\"date\"), daily_trips AS (SELECT CAST(TO_TIMESTAMP(CAST(\"starttime\" AS DOUBLE PRECISION) / 1000000) AS DATE) AS trip_date, COUNT(*) AS num_trips FROM \"NEW_YORK_GHCN\".\"NEW_YORK\".\"CITIBIKE_TRIPS\" WHERE TO_TIMESTAMP(CAST(\"starttime\" AS DOUBLE PRECISION) / 1000000) >= '2016-01-01' AND TO_TIMESTAMP(CAST(\"starttime\" AS DOUBLE PRECISION) / 1000000) < '2017-01-01' GROUP BY trip_date) SELECT CASE WHEN w.prcp_mm > 5 THEN 'rainy' ELSE 'non-rainy' END AS rain_status, ROUND(CAST(AVG(dt.num_trips) AS DECIMAL), 6) AS avg_daily_trips FROM daily_trips AS dt JOIN weather AS w ON dt.trip_date = w.\"date\" GROUP BY rain_status ORDER BY rain_status DESC") t0 t1 t2
  := by first | sql_equiv | sorry

end N_sf_bq051_eq_0_2
