import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_bq326_eq_0_2

CREATE TABLE POPULATION_BY_COUNTRY («country» STRING, «country_code» STRING, «year_1960» INT, «year_1961» INT, «year_1962» INT, «year_1963» INT, «year_1964» INT, «year_1965» INT, «year_1966» INT, «year_1967» INT, «year_1968» INT, «year_1969» INT, «year_1970» INT, «year_1971» INT, «year_1972» INT, «year_1973» INT, «year_1974» INT, «year_1975» INT, «year_1976» INT, «year_1977» INT, «year_1978» INT, «year_1979» INT, «year_1980» INT, «year_1981» INT, «year_1982» INT, «year_1983» INT, «year_1984» INT, «year_1985» INT, «year_1986» INT, «year_1987» INT, «year_1988» INT, «year_1989» INT, «year_1990» INT, «year_1991» INT, «year_1992» INT, «year_1993» INT, «year_1994» INT, «year_1995» INT, «year_1996» INT, «year_1997» INT, «year_1998» INT, «year_1999» INT, «year_2000» INT, «year_2001» INT, «year_2002» INT, «year_2003» INT, «year_2004» INT, «year_2005» INT, «year_2006» INT, «year_2007» INT, «year_2008» INT, «year_2009» INT, «year_2010» INT, «year_2011» INT, «year_2012» INT, «year_2013» INT, «year_2014» INT, «year_2015» INT, «year_2016» INT, «year_2017» INT, «year_2018» INT, «year_2019» INT)
CREATE TABLE COUNTRY_SUMMARY («country_code» STRING, «short_name» STRING, «table_name» STRING, «long_name» STRING, «two_alpha_code» STRING, «currency_unit» STRING, «special_notes» STRING, «region» STRING, «income_group» STRING, «wb_2_code» STRING, «national_accounts_base_year» STRING, «national_accounts_reference_year» STRING, «sna_price_valuation» STRING, «lending_category» STRING, «other_groups» STRING, «system_of_national_accounts» STRING, «alternative_conversion_factor» STRING, «ppp_survey_year» STRING, «balance_of_payments_manual_in_use» STRING, «external_debt_reporting_status» STRING, «system_of_trade» STRING, «government_accounting_concept» STRING, «imf_data_dissemination_standard» STRING, «latest_population_census» STRING, «latest_household_survey» STRING, «source_of_most_recent_income_and_expenditure_data» STRING, «vital_registration_complete» STRING, «latest_agricultural_census» STRING, «latest_industrial_data» INT, «latest_trade_data» INT)
CREATE TABLE HEALTH_NUTRITION_POPULATION («country_name» STRING, «country_code» STRING, «indicator_name» STRING, «indicator_code» STRING, «value» FLOAT, «year» INT)

theorem eq (t0 : TableRel POPULATION_BY_COUNTRY_schema) (t1 : TableRel COUNTRY_SUMMARY_schema) (t2 : TableRel HEALTH_NUTRITION_POPULATION_schema) :
    (sql%([POPULATION_BY_COUNTRY_schema, COUNTRY_SUMMARY_schema, HEALTH_NUTRITION_POPULATION_schema]) "WITH pop_increase AS (SELECT p.\"country_code\" FROM \"WORLD_BANK\".\"WORLD_BANK_GLOBAL_POPULATION\".\"POPULATION_BY_COUNTRY\" AS p JOIN \"WORLD_BANK\".\"WORLD_BANK_HEALTH_POPULATION\".\"COUNTRY_SUMMARY\" AS cs ON p.\"country_code\" = cs.\"country_code\" AND NOT cs.\"region\" IS NULL AND cs.\"region\" <> '' WHERE NOT p.\"year_2017\" IS NULL AND p.\"year_2017\" > 0 AND NOT p.\"year_2018\" IS NULL AND CAST((p.\"year_2018\" - p.\"year_2017\") AS DOUBLE PRECISION) / p.\"year_2017\" > 0.01), health_increase AS (SELECT h2018.\"country_code\" FROM \"WORLD_BANK\".\"WORLD_BANK_HEALTH_POPULATION\".\"HEALTH_NUTRITION_POPULATION\" AS h2018 JOIN \"WORLD_BANK\".\"WORLD_BANK_HEALTH_POPULATION\".\"HEALTH_NUTRITION_POPULATION\" AS h2017 ON h2018.\"country_code\" = h2017.\"country_code\" AND h2017.\"indicator_code\" = 'SH.XPD.CHEX.PP.CD' AND h2017.\"year\" = 2017 AND NOT h2017.\"value\" IS NULL AND h2017.\"value\" > 0 WHERE h2018.\"indicator_code\" = 'SH.XPD.CHEX.PP.CD' AND h2018.\"year\" = 2018 AND NOT h2018.\"value\" IS NULL AND CAST((h2018.\"value\" - h2017.\"value\") AS DOUBLE PRECISION) / h2017.\"value\" > 0.01) SELECT COUNT(*) AS \"NUM_COUNTRIES\" FROM pop_increase AS p JOIN health_increase AS h ON p.\"country_code\" = h.\"country_code\"") t0 t1 t2
  ~= (sql%([POPULATION_BY_COUNTRY_schema, COUNTRY_SUMMARY_schema, HEALTH_NUTRITION_POPULATION_schema]) "WITH pop AS (SELECT p.\"country_code\", p.\"year_2017\" AS pop_2017, p.\"year_2018\" AS pop_2018 FROM \"WORLD_BANK\".\"WORLD_BANK_GLOBAL_POPULATION\".\"POPULATION_BY_COUNTRY\" AS p WHERE NOT p.\"year_2017\" IS NULL AND NOT p.\"year_2018\" IS NULL), health AS (SELECT d.\"country_code\", MAX(CASE WHEN d.\"year\" = 2017 THEN d.\"value\" END) AS health_2017, MAX(CASE WHEN d.\"year\" = 2018 THEN d.\"value\" END) AS health_2018 FROM \"WORLD_BANK\".\"WORLD_BANK_HEALTH_POPULATION\".\"HEALTH_NUTRITION_POPULATION\" AS d WHERE d.\"indicator_code\" = 'SH.XPD.CHEX.PP.CD' AND d.\"year\" IN (2017, 2018) GROUP BY d.\"country_code\"), country_filter AS (SELECT \"country_code\" FROM \"WORLD_BANK\".\"WORLD_BANK_HEALTH_POPULATION\".\"COUNTRY_SUMMARY\" WHERE NOT \"region\" IS NULL AND \"region\" <> '') SELECT COUNT(*) AS \"NUM_COUNTRIES\" FROM pop AS p JOIN health AS h ON p.\"country_code\" = h.\"country_code\" JOIN country_filter AS cf ON p.\"country_code\" = cf.\"country_code\" WHERE NOT h.health_2017 IS NULL AND NOT h.health_2018 IS NULL AND CAST((p.pop_2018 - p.pop_2017) AS DOUBLE PRECISION) / p.pop_2017 > 0.01 AND CAST((h.health_2018 - h.health_2017) AS DOUBLE PRECISION) / h.health_2017 > 0.01") t0 t1 t2
  := by first | sql_equiv | sorry

end N_sf_bq326_eq_0_2
