import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_bq325_eq_1_3

CREATE TABLE DISEASE_VARIANT_GENE («study_id» STRING, «source» STRING, «pmid» STRING, «pub_date» STRING, «pub_journal» STRING, «pub_title» STRING, «pub_author» STRING, «has_sumstats» BOOL, «trait_reported» STRING, «trait_efos» STRING, «ancestry_initial» STRING, «ancestry_replication» STRING, «n_initial» INT, «n_replication» INT, «n_cases» INT, «trait_category» STRING, «num_assoc_loci» INT, «lead_chrom» STRING, «lead_pos» INT, «lead_ref» STRING, «lead_alt» STRING, «tag_chrom» STRING, «tag_pos» INT, «tag_ref» STRING, «tag_alt» STRING, «overall_r2» FLOAT, «AFR_1000G_prop» FLOAT, «AMR_1000G_prop» FLOAT, «EAS_1000G_prop» FLOAT, «EUR_1000G_prop» FLOAT, «SAS_1000G_prop» FLOAT, «log10_ABF» FLOAT, «posterior_prob» FLOAT, «odds_ratio» FLOAT, «oddsr_ci_lower» FLOAT, «oddsr_ci_upper» FLOAT, «direction» STRING, «beta» FLOAT, «beta_ci_lower» FLOAT, «beta_ci_upper» FLOAT, «pval_mantissa» FLOAT, «pval_exponent» INT, «pval» FLOAT, «gene_id» STRING, «feature» STRING, «type_id» STRING, «source_id» STRING, «fpred_labels» STRING, «fpred_scores» STRING, «fpred_max_label» STRING, «fpred_max_score» FLOAT, «qtl_beta» FLOAT, «qtl_se» FLOAT, «qtl_pval» FLOAT, «qtl_score» FLOAT, «interval_score» FLOAT, «qtl_score_q» FLOAT, «interval_score_q» FLOAT, «d» INT, «distance_score» FLOAT, «distance_score_q» FLOAT)

theorem eq (t0 : TableRel DISEASE_VARIANT_GENE_schema) :
    (sql%([DISEASE_VARIANT_GENE_schema]) "WITH best_per_gene_study AS (SELECT \"gene_id\", \"study_id\", MIN(\"pval_exponent\") AS min_exp FROM \"OPEN_TARGETS_GENETICS_2\".\"OPEN_TARGETS_GENETICS\".\"DISEASE_VARIANT_GENE\" GROUP BY \"gene_id\", \"study_id\"), best_mantissa AS (SELECT d.\"gene_id\", d.\"study_id\", b.min_exp, MIN(d.\"pval_mantissa\") AS min_mantissa FROM \"OPEN_TARGETS_GENETICS_2\".\"OPEN_TARGETS_GENETICS\".\"DISEASE_VARIANT_GENE\" AS d JOIN best_per_gene_study AS b ON d.\"gene_id\" = b.\"gene_id\" AND d.\"study_id\" = b.\"study_id\" AND d.\"pval_exponent\" = b.min_exp GROUP BY d.\"gene_id\", d.\"study_id\", b.min_exp), global_top10 AS (SELECT \"gene_id\", \"study_id\", min_exp, min_mantissa FROM best_mantissa ORDER BY min_exp ASC, min_mantissa ASC LIMIT 10), with_variant AS (SELECT \"gene_id\", \"study_id\", \"CHROM\", \"POS\", \"REF\", \"ALT\", \"pval\" FROM (SELECT t.\"gene_id\", t.\"study_id\", d.\"lead_chrom\" AS \"CHROM\", d.\"lead_pos\" AS \"POS\", d.\"lead_ref\" AS \"REF\", d.\"lead_alt\" AS \"ALT\", d.\"pval\", ROW_NUMBER() OVER (PARTITION BY t.\"gene_id\", t.\"study_id\" ORDER BY d.\"lead_chrom\") AS _w, d.\"lead_chrom\" FROM global_top10 AS t JOIN \"OPEN_TARGETS_GENETICS_2\".\"OPEN_TARGETS_GENETICS\".\"DISEASE_VARIANT_GENE\" AS d ON d.\"gene_id\" = t.\"gene_id\" AND d.\"study_id\" = t.\"study_id\" AND d.\"pval_exponent\" = t.min_exp AND d.\"pval_mantissa\" = t.min_mantissa) AS _t WHERE _w = 1) SELECT \"gene_id\", \"study_id\", \"CHROM\", \"POS\", \"REF\", \"ALT\", \"pval\" FROM with_variant ORDER BY \"gene_id\"") t0
  ~= (sql%([DISEASE_VARIANT_GENE_schema]) "SELECT \"gene_id\", \"study_id\", \"CHROM\", \"POS\", \"REF\", \"ALT\", \"pval\" FROM (/* Strategy: First get each study's variant with lowest pval from VARIANT_DISEASE (22.9M rows), */ /* then join with VARIANT_GENE to get gene mappings, then rank per gene-study. */ /* Step 1: For each study, get all variants - but we want per gene-study. */ /* Since gene comes from VARIANT_GENE, we need to join first, then aggregate. */ /* Optimization: first get the top candidate variants from VARIANT_DISEASE, */ /* then join with VARIANT_GENE for gene mapping. */ WITH top_variants AS (SELECT \"study_id\", \"tag_chrom\", \"tag_pos\", \"tag_ref\", \"tag_alt\", \"pval\" FROM \"OPEN_TARGETS_GENETICS_2\".\"OPEN_TARGETS_GENETICS\".\"VARIANT_DISEASE\" WHERE NOT \"pval\" IS NULL ORDER BY \"pval\" ASC LIMIT 1000), gene_variant_study AS (SELECT vg.\"gene_id\", tv.\"study_id\", tv.\"tag_chrom\" AS \"CHROM\", tv.\"tag_pos\" AS \"POS\", tv.\"tag_ref\" AS \"REF\", tv.\"tag_alt\" AS \"ALT\", tv.\"pval\" FROM top_variants AS tv JOIN \"OPEN_TARGETS_GENETICS_2\".\"OPEN_TARGETS_GENETICS\".\"VARIANT_GENE\" AS vg ON tv.\"tag_chrom\" = vg.\"chr_id\" AND tv.\"tag_pos\" = vg.\"position\" AND tv.\"tag_ref\" = vg.\"ref_allele\" AND tv.\"tag_alt\" = vg.\"alt_allele\") SELECT \"gene_id\", \"study_id\", \"CHROM\", \"POS\", \"REF\", \"ALT\", \"pval\", ROW_NUMBER() OVER (PARTITION BY \"gene_id\", \"study_id\" ORDER BY \"pval\" ASC) AS _w FROM gene_variant_study ORDER BY \"pval\" ASC LIMIT 10) AS _t WHERE _w = 1") t0
  := by first | sql_equiv | sorry

end N_sf_bq325_eq_1_3
