import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_bq053_eq_0_3

CREATE TABLE TREE_CENSUS_1995 («recordid» INT, «address» STRING, «house_number» STRING, «street» STRING, «zip_original» INT, «cb_original» INT, «site» STRING, «species» STRING, «diameter» INT, «status» STRING, «wires» STRING, «sidewalk_condition» STRING, «support_structure» STRING, «borough» STRING, «x» FLOAT, «y» FLOAT, «longitude» FLOAT, «latitude» FLOAT, «cb_new» INT, «zip_new» INT, «censustract_2010» STRING, «censusblock_2010» STRING, «nta_2010» STRING, «segmentid» INT, «spc_common» STRING, «spc_latin» STRING, «location» STRING)
CREATE TABLE TREE_CENSUS_2015 («tree_id» INT, «block_id» INT, «created_at» STRING, «tree_dbh» INT, «stump_diam» INT, «curb_loc» STRING, «status» STRING, «health» STRING, «spc_latin» STRING, «spc_common» STRING, «steward» STRING, «guards» STRING, «sidewalk» STRING, «user_type» STRING, «problems» STRING, «root_stone» STRING, «root_grate» STRING, «root_other» STRING, «trunk_wire» STRING, «trnk_light» STRING, «trnk_other» STRING, «brch_light» STRING, «brch_shoe» STRING, «brch_other» STRING, «address» STRING, «zipcode» INT, «zip_city» STRING, «cb_num» INT, «borocode» INT, «boroname» STRING, «cncldist» INT, «st_assem» INT, «st_senate» INT, «nta» STRING, «nta_name» STRING, «boro_ct» INT, «state» STRING, «latitude» FLOAT, «longitude» FLOAT, «x_sp» FLOAT, «y_sp» FLOAT)
CREATE TABLE TREE_SPECIES («species_scientific_name» STRING, «species_common_name» STRING, «form» STRING, «growth_rate» STRING, «fall_color» STRING, «environmental_tolerances» STRING, «location_tolerances» STRING, «notes_suggested_cultivars» STRING, «tree_size» STRING, «comments» STRING)

theorem eq (t0 : TableRel TREE_CENSUS_1995_schema) (t1 : TableRel TREE_CENSUS_2015_schema) (t2 : TableRel TREE_SPECIES_schema) :
    (sql%([TREE_CENSUS_1995_schema, TREE_CENSUS_2015_schema, TREE_SPECIES_schema]) "WITH sp_1995 AS (SELECT UPPER(\"spc_latin\") AS species_upper, COUNT(*) AS cnt_1995 FROM \"NEW_YORK\".\"NEW_YORK\".\"TREE_CENSUS_1995\" WHERE \"status\" <> 'Dead' AND NOT \"spc_latin\" IS NULL AND \"spc_latin\" <> '' GROUP BY UPPER(\"spc_latin\")), sp_2015 AS (SELECT UPPER(\"spc_latin\") AS species_upper, COUNT(*) AS cnt_2015 FROM \"NEW_YORK\".\"NEW_YORK\".\"TREE_CENSUS_2015\" WHERE \"status\" = 'Alive' AND NOT \"spc_latin\" IS NULL AND \"spc_latin\" <> '' GROUP BY UPPER(\"spc_latin\")), ts AS (SELECT UPPER(\"species_scientific_name\") AS species_upper, \"fall_color\" FROM \"NEW_YORK\".\"NEW_YORK\".\"TREE_SPECIES\") SELECT ts.\"fall_color\", SUM(COALESCE(sp_2015.cnt_2015, 0) - COALESCE(sp_1995.cnt_1995, 0)) AS change FROM ts LEFT JOIN sp_1995 ON ts.species_upper = sp_1995.species_upper LEFT JOIN sp_2015 ON ts.species_upper = sp_2015.species_upper WHERE NOT sp_1995.species_upper IS NULL OR NOT sp_2015.species_upper IS NULL GROUP BY ts.\"fall_color\" ORDER BY change DESC") t0 t1 t2
  ~= (sql%([TREE_CENSUS_1995_schema, TREE_CENSUS_2015_schema, TREE_SPECIES_schema]) "WITH census_1995_counts AS (SELECT UPPER(c.\"spc_latin\") AS species_key, COUNT(*) AS not_dead_count FROM \"NEW_YORK\".\"NEW_YORK\".\"TREE_CENSUS_1995\" AS c WHERE c.\"status\" <> 'Dead' AND NOT c.\"spc_latin\" IS NULL AND c.\"spc_latin\" <> '' GROUP BY UPPER(c.\"spc_latin\")), census_2015_counts AS (SELECT UPPER(c.\"spc_latin\") AS species_key, COUNT(*) AS alive_count FROM \"NEW_YORK\".\"NEW_YORK\".\"TREE_CENSUS_2015\" AS c WHERE c.\"status\" = 'Alive' AND NOT c.\"spc_latin\" IS NULL AND c.\"spc_latin\" <> '' GROUP BY UPPER(c.\"spc_latin\")), species_fall_color AS (SELECT UPPER(\"species_scientific_name\") AS species_key, \"fall_color\" FROM \"NEW_YORK\".\"NEW_YORK\".\"TREE_SPECIES\" WHERE NOT \"species_scientific_name\" IS NULL AND NOT \"fall_color\" IS NULL), grouped AS (SELECT s.\"fall_color\" AS fall_color, SUM(COALESCE(c2015.alive_count, 0) - COALESCE(c1995.not_dead_count, 0)) AS change FROM species_fall_color AS s LEFT JOIN census_1995_counts AS c1995 ON s.species_key = c1995.species_key LEFT JOIN census_2015_counts AS c2015 ON s.species_key = c2015.species_key GROUP BY s.\"fall_color\") SELECT fall_color, change FROM grouped WHERE change > 0 ORDER BY change DESC") t0 t1 t2
  := by first | sql_equiv | sorry

end N_sf_bq053_eq_0_3
