import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_bq305_eq_1_2

CREATE TABLE USERS («id» INT, «display_name» STRING, «about_me» STRING, «age» STRING, «creation_date» INT, «last_access_date» INT, «location» STRING, «reputation» INT, «up_votes» INT, «down_votes» INT, «views» INT, «profile_image_url» STRING, «website_url» STRING)
CREATE TABLE POSTS_ANSWERS («id» INT, «title» STRING, «body» STRING, «accepted_answer_id» STRING, «answer_count» STRING, «comment_count» INT, «community_owned_date» INT, «creation_date» INT, «favorite_count» STRING, «last_activity_date» INT, «last_edit_date» INT, «last_editor_display_name» STRING, «last_editor_user_id» INT, «owner_display_name» STRING, «owner_user_id» INT, «parent_id» INT, «post_type_id» INT, «score» INT, «tags» STRING, «view_count» STRING)
CREATE TABLE POSTS_QUESTIONS («id» INT, «title» STRING, «body» STRING, «accepted_answer_id» INT, «answer_count» INT, «comment_count» INT, «community_owned_date» INT, «creation_date» INT, «favorite_count» INT, «last_activity_date» INT, «last_edit_date» INT, «last_editor_display_name» STRING, «last_editor_user_id» INT, «owner_display_name» STRING, «owner_user_id» INT, «parent_id» STRING, «post_type_id» INT, «score» INT, «tags» STRING, «view_count» INT)

theorem eq (t0 : TableRel USERS_schema) (t1 : TableRel POSTS_ANSWERS_schema) (t2 : TableRel POSTS_QUESTIONS_schema) :
    (sql%([USERS_schema, POSTS_ANSWERS_schema, POSTS_QUESTIONS_schema]) "/* Find top 10 users by combined view counts of questions they are associated with. */ /* A user is associated with a question if ANY of 5 criteria hold. */ /* Use UNION to deduplicate (user_id, question_id) pairs across all criteria. */ WITH associated AS (/* Criterion 1: User owns the question */ SELECT q.\"owner_user_id\" AS user_id, q.\"id\" AS question_id FROM \"STACKOVERFLOW\".\"STACKOVERFLOW\".\"POSTS_QUESTIONS\" AS q WHERE NOT q.\"owner_user_id\" IS NULL UNION /* Criterion 2: User's answer is the accepted answer for the question */ SELECT a.\"owner_user_id\" AS user_id, q.\"id\" AS question_id FROM \"STACKOVERFLOW\".\"STACKOVERFLOW\".\"POSTS_QUESTIONS\" AS q JOIN \"STACKOVERFLOW\".\"STACKOVERFLOW\".\"POSTS_ANSWERS\" AS a ON q.\"accepted_answer_id\" = a.\"id\" WHERE NOT a.\"owner_user_id\" IS NULL UNION /* Criterion 3: User has provided an answer with score > 5 */ SELECT a.\"owner_user_id\" AS user_id, a.\"parent_id\" AS question_id FROM \"STACKOVERFLOW\".\"STACKOVERFLOW\".\"POSTS_ANSWERS\" AS a WHERE a.\"score\" > 5 AND NOT a.\"owner_user_id\" IS NULL UNION /* Criterion 4: Answer score > 20% of total answer scores for the question AND score > 0 */ SELECT a.\"owner_user_id\" AS user_id, a.\"parent_id\" AS question_id FROM \"STACKOVERFLOW\".\"STACKOVERFLOW\".\"POSTS_ANSWERS\" AS a JOIN (SELECT \"parent_id\", SUM(\"score\") AS total_score FROM \"STACKOVERFLOW\".\"STACKOVERFLOW\".\"POSTS_ANSWERS\" GROUP BY \"parent_id\") AS ts ON a.\"parent_id\" = ts.\"parent_id\" WHERE a.\"score\" > 0 AND a.\"score\" > 0.2 * ts.total_score AND NOT a.\"owner_user_id\" IS NULL UNION /* Criterion 5: Answer is among top 3 highest-scoring answers for the question */ SELECT sub.user_id, sub.question_id FROM (SELECT a.\"owner_user_id\" AS user_id, a.\"parent_id\" AS question_id, DENSE_RANK() OVER (PARTITION BY a.\"parent_id\" ORDER BY a.\"score\" DESC) AS rnk FROM \"STACKOVERFLOW\".\"STACKOVERFLOW\".\"POSTS_ANSWERS\" AS a WHERE NOT a.\"owner_user_id\" IS NULL) AS sub WHERE sub.rnk <= 3), user_views /* Sum view counts of distinct associated questions per user */ AS (SELECT assoc.user_id, SUM(q.\"view_count\") AS TOTAL_VIEW_COUNT FROM associated AS assoc JOIN \"STACKOVERFLOW\".\"STACKOVERFLOW\".\"POSTS_QUESTIONS\" AS q ON assoc.question_id = q.\"id\" GROUP BY assoc.user_id) SELECT uv.user_id AS USER_ID, u.\"display_name\", uv.TOTAL_VIEW_COUNT FROM user_views AS uv JOIN \"STACKOVERFLOW\".\"STACKOVERFLOW\".\"USERS\" AS u ON uv.user_id = u.\"id\" ORDER BY uv.TOTAL_VIEW_COUNT DESC LIMIT 10") t0 t1 t2
  ~= (sql%([USERS_schema, POSTS_ANSWERS_schema, POSTS_QUESTIONS_schema]) "WITH answer_stats AS (SELECT a.\"id\" AS answer_id, a.\"owner_user_id\" AS answerer_user_id, a.\"parent_id\" AS question_id, a.\"score\" AS answer_score, SUM(a.\"score\") OVER (PARTITION BY a.\"parent_id\") AS total_answer_score, ROW_NUMBER() OVER (PARTITION BY a.\"parent_id\" ORDER BY a.\"score\" DESC) AS score_rank FROM \"STACKOVERFLOW\".\"STACKOVERFLOW\".\"POSTS_ANSWERS\" AS a), assoc_owner AS (SELECT q.\"owner_user_id\" AS user_id, q.\"id\" AS question_id FROM \"STACKOVERFLOW\".\"STACKOVERFLOW\".\"POSTS_QUESTIONS\" AS q WHERE NOT q.\"owner_user_id\" IS NULL), assoc_accepted AS (SELECT a.\"owner_user_id\" AS user_id, a.\"parent_id\" AS question_id FROM \"STACKOVERFLOW\".\"STACKOVERFLOW\".\"POSTS_ANSWERS\" AS a JOIN \"STACKOVERFLOW\".\"STACKOVERFLOW\".\"POSTS_QUESTIONS\" AS q ON q.\"accepted_answer_id\" = a.\"id\" WHERE NOT a.\"owner_user_id\" IS NULL), assoc_score_gt5 AS (SELECT answerer_user_id AS user_id, question_id FROM answer_stats WHERE answer_score > 5 AND NOT answerer_user_id IS NULL), assoc_score_pct AS (SELECT answerer_user_id AS user_id, question_id FROM answer_stats WHERE answer_score > 0 AND total_answer_score > 0 AND answer_score > 0.2 * total_answer_score AND NOT answerer_user_id IS NULL), assoc_top3 AS (SELECT answerer_user_id AS user_id, question_id FROM answer_stats WHERE score_rank <= 3 AND NOT answerer_user_id IS NULL), all_assoc AS (SELECT user_id, question_id FROM assoc_owner UNION SELECT user_id, question_id FROM assoc_accepted UNION SELECT user_id, question_id FROM assoc_score_gt5 UNION SELECT user_id, question_id FROM assoc_score_pct UNION SELECT user_id, question_id FROM assoc_top3) SELECT a.user_id AS \"USER_ID\", u.\"display_name\" AS \"display_name\", SUM(q.\"view_count\") AS \"TOTAL_VIEW_COUNT\" FROM all_assoc AS a JOIN \"STACKOVERFLOW\".\"STACKOVERFLOW\".\"POSTS_QUESTIONS\" AS q ON a.question_id = q.\"id\" JOIN \"STACKOVERFLOW\".\"STACKOVERFLOW\".\"USERS\" AS u ON a.user_id = u.\"id\" GROUP BY a.user_id, u.\"display_name\" ORDER BY \"TOTAL_VIEW_COUNT\" DESC LIMIT 10") t0 t1 t2
  := by first | sql_equiv | sorry

end N_sf_bq305_eq_1_2
