import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_ga031 — crossskill equivalence(s)

Question: I want to know the user session conversion rate on January 2nd, 2021, using only 'page_view' events. The conversion rate should be calculated as the percentage of user visits that reached both the Home and Checkout Confirmation pages in one session, relative to those that landed on the Home page.

NOTE: uses WITH RECURSIVE / LATERAL / FLATTEN — may not elaborate yet.

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_ga031

CREATE TABLE EVENTS_20210102 («EVENT_DATE» STRING, «EVENT_TIMESTAMP» INT, «EVENT_NAME» STRING, «EVENT_PARAMS» STRING, «EVENT_PREVIOUS_TIMESTAMP» INT, «EVENT_VALUE_IN_USD» FLOAT, «EVENT_BUNDLE_SEQUENCE_ID» INT, «EVENT_SERVER_TIMESTAMP_OFFSET» INT, «USER_ID» STRING, «USER_PSEUDO_ID» STRING, «PRIVACY_INFO» STRING, «USER_PROPERTIES» STRING, «USER_FIRST_TOUCH_TIMESTAMP» INT, «USER_LTV» STRING, «DEVICE» STRING, «GEO» STRING, «APP_INFO» STRING, «TRAFFIC_SOURCE» STRING, «STREAM_ID» INT, «PLATFORM» STRING, «EVENT_DIMENSIONS» STRING, «ECOMMERCE» STRING, «ITEMS» STRING)

HYPOTHESIS hyp0_1_0 : EVENTS_20210102 "\"EVENT_NAME\" = 'page_view'"
HYPOTHESIS hyp0_1_1 : EVENTS_20210102 "e.EVENT_NAME = 'page_view'"
HYPOTHESIS hyp0_1_2 : EVENTS_20210102 "\"USER_PSEUDO_ID\" = e.USER_PSEUDO_ID"
theorem eq_0_1 (t : TableRel EVENTS_20210102_schema) (h0 : hyp0_1_0 t) (h1 : hyp0_1_1 t) (h2 : hyp0_1_2 t) :
    (sql%([EVENTS_20210102_schema]) "WITH event_data AS (SELECT e.\"USER_PSEUDO_ID\", e.\"EVENT_TIMESTAMP\", MAX(CASE WHEN CAST(JSON_EXTRACT_PATH(f.value, 'key') AS TEXT) = 'ga_session_id' THEN CAST(JSON_EXTRACT_PATH(f.value, 'value', 'int_value') AS TEXT) END) AS session_id, MAX(CASE WHEN CAST(JSON_EXTRACT_PATH(f.value, 'key') AS TEXT) = 'page_title' THEN CAST(JSON_EXTRACT_PATH(f.value, 'value', 'string_value') AS TEXT) END) AS page_title, MAX(CASE WHEN CAST(JSON_EXTRACT_PATH(f.value, 'key') AS TEXT) = 'entrances' THEN JSON_EXTRACT_PATH(f.value, 'value', 'int_value') END) AS entrances FROM \"GA4\".\"GA4_OBFUSCATED_SAMPLE_ECOMMERCE\".\"EVENTS_20210102\" AS e, LATERAL UNNEST(input => e.\"EVENT_PARAMS\") AS f(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE e.\"EVENT_NAME\" = 'page_view' GROUP BY e.\"USER_PSEUDO_ID\", e.\"EVENT_TIMESTAMP\"), session_summary AS (SELECT USER_PSEUDO_ID, session_id, MAX(CASE WHEN entrances = 1 AND page_title = 'Home' THEN 1 ELSE 0 END) AS landed_on_home, MAX(CASE WHEN page_title = 'Home' THEN 1 ELSE 0 END) AS has_home, MAX(CASE WHEN page_title = 'Checkout Confirmation' THEN 1 ELSE 0 END) AS has_checkout FROM event_data GROUP BY USER_PSEUDO_ID, session_id) SELECT ROUND(CAST(100.0 * SUM(CASE WHEN landed_on_home = 1 AND has_home = 1 AND has_checkout = 1 THEN 1 ELSE 0 END) AS DOUBLE PRECISION) / NULLIF(SUM(landed_on_home), 0), 6) AS CONVERSION_RATE FROM session_summary") t ~= (sql%([EVENTS_20210102_schema]) "WITH page_views AS (SELECT e.USER_PSEUDO_ID, MAX(CASE WHEN CAST(JSON_EXTRACT_PATH(ep.VALUE, 'key') AS TEXT) = 'ga_session_id' THEN CAST(JSON_EXTRACT_PATH(ep.VALUE, 'value', 'int_value') AS TEXT) END) AS ga_session_id, MAX(CASE WHEN CAST(JSON_EXTRACT_PATH(ep.VALUE, 'key') AS TEXT) = 'page_title' THEN CAST(JSON_EXTRACT_PATH(ep.VALUE, 'value', 'string_value') AS TEXT) END) AS page_title, MAX(CASE WHEN CAST(JSON_EXTRACT_PATH(ep.VALUE, 'key') AS TEXT) = 'entrances' THEN CAST(JSON_EXTRACT_PATH(ep.VALUE, 'value', 'int_value') AS INT) END) AS entrances FROM \"GA4\".\"GA4_OBFUSCATED_SAMPLE_ECOMMERCE\".\"EVENTS_20210102\" AS e, LATERAL UNNEST(input => e.EVENT_PARAMS) AS ep(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE e.EVENT_NAME = 'page_view' GROUP BY e.USER_PSEUDO_ID, e.EVENT_TIMESTAMP, e.EVENT_PARAMS), session_pages AS (SELECT USER_PSEUDO_ID, ga_session_id, MAX(CASE WHEN page_title = 'Home' THEN 1 ELSE 0 END) AS has_home, MAX(CASE WHEN page_title = 'Checkout Confirmation' THEN 1 ELSE 0 END) AS has_checkout, MAX(CASE WHEN page_title = 'Home' AND entrances = 1 THEN 1 ELSE 0 END) AS landed_home FROM page_views GROUP BY USER_PSEUDO_ID, ga_session_id) SELECT ROUND(CAST(SUM(CASE WHEN landed_home = 1 AND has_home = 1 AND has_checkout = 1 THEN 1 ELSE 0 END) * 100.0 AS DOUBLE PRECISION) / NULLIF(SUM(landed_home), 0), 6) AS CONVERSION_RATE FROM session_pages") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp0_2_0 : EVENTS_20210102 "\"EVENT_NAME\" = 'page_view'"
HYPOTHESIS hyp0_2_1 : EVENTS_20210102 "e.EVENT_NAME = 'page_view'"
HYPOTHESIS hyp0_2_2 : EVENTS_20210102 "\"EVENT_TIMESTAMP\" = e.EVENT_TIMESTAMP"
HYPOTHESIS hyp0_2_3 : EVENTS_20210102 "\"USER_PSEUDO_ID\" = e.USER_PSEUDO_ID"
theorem eq_0_2 (t : TableRel EVENTS_20210102_schema) (h0 : hyp0_2_0 t) (h1 : hyp0_2_1 t) (h2 : hyp0_2_2 t) (h3 : hyp0_2_3 t) :
    (sql%([EVENTS_20210102_schema]) "WITH event_data AS (SELECT e.\"USER_PSEUDO_ID\", e.\"EVENT_TIMESTAMP\", MAX(CASE WHEN CAST(JSON_EXTRACT_PATH(f.value, 'key') AS TEXT) = 'ga_session_id' THEN CAST(JSON_EXTRACT_PATH(f.value, 'value', 'int_value') AS TEXT) END) AS session_id, MAX(CASE WHEN CAST(JSON_EXTRACT_PATH(f.value, 'key') AS TEXT) = 'page_title' THEN CAST(JSON_EXTRACT_PATH(f.value, 'value', 'string_value') AS TEXT) END) AS page_title, MAX(CASE WHEN CAST(JSON_EXTRACT_PATH(f.value, 'key') AS TEXT) = 'entrances' THEN JSON_EXTRACT_PATH(f.value, 'value', 'int_value') END) AS entrances FROM \"GA4\".\"GA4_OBFUSCATED_SAMPLE_ECOMMERCE\".\"EVENTS_20210102\" AS e, LATERAL UNNEST(input => e.\"EVENT_PARAMS\") AS f(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE e.\"EVENT_NAME\" = 'page_view' GROUP BY e.\"USER_PSEUDO_ID\", e.\"EVENT_TIMESTAMP\"), session_summary AS (SELECT USER_PSEUDO_ID, session_id, MAX(CASE WHEN entrances = 1 AND page_title = 'Home' THEN 1 ELSE 0 END) AS landed_on_home, MAX(CASE WHEN page_title = 'Home' THEN 1 ELSE 0 END) AS has_home, MAX(CASE WHEN page_title = 'Checkout Confirmation' THEN 1 ELSE 0 END) AS has_checkout FROM event_data GROUP BY USER_PSEUDO_ID, session_id) SELECT ROUND(CAST(100.0 * SUM(CASE WHEN landed_on_home = 1 AND has_home = 1 AND has_checkout = 1 THEN 1 ELSE 0 END) AS DOUBLE PRECISION) / NULLIF(SUM(landed_on_home), 0), 6) AS CONVERSION_RATE FROM session_summary") t ~= (sql%([EVENTS_20210102_schema]) "WITH page_views AS (SELECT e.USER_PSEUDO_ID, e.EVENT_TIMESTAMP, MAX(CASE WHEN CAST(JSON_EXTRACT_PATH(ep.value, 'key') AS TEXT) = 'ga_session_id' THEN CAST(JSON_EXTRACT_PATH(ep.value, 'value', 'int_value') AS INT) END) AS ga_session_id, MAX(CASE WHEN CAST(JSON_EXTRACT_PATH(ep.value, 'key') AS TEXT) = 'page_title' THEN CAST(JSON_EXTRACT_PATH(ep.value, 'value', 'string_value') AS TEXT) END) AS page_title, MAX(CASE WHEN CAST(JSON_EXTRACT_PATH(ep.value, 'key') AS TEXT) = 'entrances' THEN CAST(JSON_EXTRACT_PATH(ep.value, 'value', 'int_value') AS INT) END) AS entrances FROM \"GA4\".\"GA4_OBFUSCATED_SAMPLE_ECOMMERCE\".\"EVENTS_20210102\" AS e, LATERAL UNNEST(input => e.EVENT_PARAMS) AS ep(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE e.EVENT_NAME = 'page_view' GROUP BY e.USER_PSEUDO_ID, e.EVENT_TIMESTAMP), home_landing_sessions AS (SELECT DISTINCT USER_PSEUDO_ID, ga_session_id FROM page_views WHERE page_title = 'Home' AND entrances = 1), session_checkout AS (SELECT DISTINCT USER_PSEUDO_ID, ga_session_id FROM page_views WHERE page_title = 'Checkout Confirmation') SELECT CAST(100.0 * (SELECT COUNT(*) FROM home_landing_sessions AS h INNER JOIN session_checkout AS c ON h.USER_PSEUDO_ID = c.USER_PSEUDO_ID AND h.ga_session_id = c.ga_session_id) AS DOUBLE PRECISION) / NULLIF((SELECT COUNT(*) FROM home_landing_sessions), 0) AS \"CONVERSION_RATE\"") t := by
  first | sql_equiv | sorry

theorem eq_1_2 : ∀ t,
    (sql%([EVENTS_20210102_schema]) "WITH page_views AS (SELECT e.USER_PSEUDO_ID, MAX(CASE WHEN CAST(JSON_EXTRACT_PATH(ep.VALUE, 'key') AS TEXT) = 'ga_session_id' THEN CAST(JSON_EXTRACT_PATH(ep.VALUE, 'value', 'int_value') AS TEXT) END) AS ga_session_id, MAX(CASE WHEN CAST(JSON_EXTRACT_PATH(ep.VALUE, 'key') AS TEXT) = 'page_title' THEN CAST(JSON_EXTRACT_PATH(ep.VALUE, 'value', 'string_value') AS TEXT) END) AS page_title, MAX(CASE WHEN CAST(JSON_EXTRACT_PATH(ep.VALUE, 'key') AS TEXT) = 'entrances' THEN CAST(JSON_EXTRACT_PATH(ep.VALUE, 'value', 'int_value') AS INT) END) AS entrances FROM \"GA4\".\"GA4_OBFUSCATED_SAMPLE_ECOMMERCE\".\"EVENTS_20210102\" AS e, LATERAL UNNEST(input => e.EVENT_PARAMS) AS ep(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE e.EVENT_NAME = 'page_view' GROUP BY e.USER_PSEUDO_ID, e.EVENT_TIMESTAMP, e.EVENT_PARAMS), session_pages AS (SELECT USER_PSEUDO_ID, ga_session_id, MAX(CASE WHEN page_title = 'Home' THEN 1 ELSE 0 END) AS has_home, MAX(CASE WHEN page_title = 'Checkout Confirmation' THEN 1 ELSE 0 END) AS has_checkout, MAX(CASE WHEN page_title = 'Home' AND entrances = 1 THEN 1 ELSE 0 END) AS landed_home FROM page_views GROUP BY USER_PSEUDO_ID, ga_session_id) SELECT ROUND(CAST(SUM(CASE WHEN landed_home = 1 AND has_home = 1 AND has_checkout = 1 THEN 1 ELSE 0 END) * 100.0 AS DOUBLE PRECISION) / NULLIF(SUM(landed_home), 0), 6) AS CONVERSION_RATE FROM session_pages") t ~= (sql%([EVENTS_20210102_schema]) "WITH page_views AS (SELECT e.USER_PSEUDO_ID, e.EVENT_TIMESTAMP, MAX(CASE WHEN CAST(JSON_EXTRACT_PATH(ep.value, 'key') AS TEXT) = 'ga_session_id' THEN CAST(JSON_EXTRACT_PATH(ep.value, 'value', 'int_value') AS INT) END) AS ga_session_id, MAX(CASE WHEN CAST(JSON_EXTRACT_PATH(ep.value, 'key') AS TEXT) = 'page_title' THEN CAST(JSON_EXTRACT_PATH(ep.value, 'value', 'string_value') AS TEXT) END) AS page_title, MAX(CASE WHEN CAST(JSON_EXTRACT_PATH(ep.value, 'key') AS TEXT) = 'entrances' THEN CAST(JSON_EXTRACT_PATH(ep.value, 'value', 'int_value') AS INT) END) AS entrances FROM \"GA4\".\"GA4_OBFUSCATED_SAMPLE_ECOMMERCE\".\"EVENTS_20210102\" AS e, LATERAL UNNEST(input => e.EVENT_PARAMS) AS ep(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE e.EVENT_NAME = 'page_view' GROUP BY e.USER_PSEUDO_ID, e.EVENT_TIMESTAMP), home_landing_sessions AS (SELECT DISTINCT USER_PSEUDO_ID, ga_session_id FROM page_views WHERE page_title = 'Home' AND entrances = 1), session_checkout AS (SELECT DISTINCT USER_PSEUDO_ID, ga_session_id FROM page_views WHERE page_title = 'Checkout Confirmation') SELECT CAST(100.0 * (SELECT COUNT(*) FROM home_landing_sessions AS h INNER JOIN session_checkout AS c ON h.USER_PSEUDO_ID = c.USER_PSEUDO_ID AND h.ga_session_id = c.ga_session_id) AS DOUBLE PRECISION) / NULLIF((SELECT COUNT(*) FROM home_landing_sessions), 0) AS \"CONVERSION_RATE\"") t := by
  intro t; first | sql_equiv | sorry

end Bench_sf_ga031
