import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_local061_eq_0_3

CREATE TABLE COUNTRIES («country_id» INT, «country_iso_code» STRING, «country_name» STRING, «country_subregion» STRING, «country_subregion_id» INT, «country_region» STRING, «country_region_id» INT, «country_total» STRING, «country_total_id» INT)
CREATE TABLE CURRENCY («country» STRING, «year» INT, «month» INT, «to_us» FLOAT)
CREATE TABLE CUSTOMERS («cust_id» INT, «cust_first_name» STRING, «cust_last_name» STRING, «cust_gender» STRING, «cust_year_of_birth» INT, «cust_marital_status» STRING, «cust_street_address» STRING, «cust_postal_code» STRING, «cust_city» STRING, «cust_city_id» INT, «cust_state_province» STRING, «cust_state_province_id» INT, «country_id» INT, «cust_main_phone_number» STRING, «cust_income_level» STRING, «cust_credit_limit» FLOAT, «cust_email» STRING, «cust_total» STRING, «cust_total_id» INT, «cust_src_id» STRING, «cust_eff_from» STRING, «cust_eff_to» STRING, «cust_valid» STRING)
CREATE TABLE TIMES («time_id» STRING, «day_name» STRING, «day_number_in_week» INT, «day_number_in_month» INT, «calendar_week_number» INT, «fiscal_week_number» INT, «week_ending_day» STRING, «week_ending_day_id» INT, «calendar_month_number» INT, «fiscal_month_number» INT, «calendar_month_desc» STRING, «calendar_month_id» INT, «fiscal_month_desc» STRING, «fiscal_month_id» INT, «days_in_cal_month» INT, «days_in_fis_month» INT, «end_of_cal_month» STRING, «end_of_fis_month» STRING, «calendar_month_name» STRING, «fiscal_month_name» STRING, «calendar_quarter_desc» STRING, «calendar_quarter_id» INT, «fiscal_quarter_desc» STRING, «fiscal_quarter_id» INT, «days_in_cal_quarter» INT, «days_in_fis_quarter» INT, «end_of_cal_quarter» STRING, «end_of_fis_quarter» STRING, «calendar_quarter_number» INT, «fiscal_quarter_number» INT, «calendar_year» INT, «calendar_year_id» INT, «fiscal_year» INT, «fiscal_year_id» INT, «days_in_cal_year» INT, «days_in_fis_year» INT, «end_of_cal_year» STRING, «end_of_fis_year» STRING)
CREATE TABLE CHANNELS («channel_id» INT, «channel_desc» STRING, «channel_class» STRING, «channel_class_id» INT, «channel_total» STRING, «channel_total_id» INT)
CREATE TABLE PROMOTIONS («promo_id» INT, «promo_name» STRING, «promo_subcategory» STRING, «promo_subcategory_id» INT, «promo_category» STRING, «promo_category_id» INT, «promo_cost» FLOAT, «promo_begin_date» STRING, «promo_end_date» STRING, «promo_total» STRING, «promo_total_id» INT)
CREATE TABLE SALES («prod_id» INT, «cust_id» INT, «time_id» STRING, «channel_id» INT, «promo_id» INT, «quantity_sold» INT, «amount_sold» FLOAT)

theorem eq (t0 : TableRel COUNTRIES_schema) (t1 : TableRel CURRENCY_schema) (t2 : TableRel CUSTOMERS_schema) (t3 : TableRel TIMES_schema) (t4 : TableRel CHANNELS_schema) (t5 : TableRel PROMOTIONS_schema) (t6 : TableRel SALES_schema) :
    (sql%([COUNTRIES_schema, CURRENCY_schema, CUSTOMERS_schema, TIMES_schema, CHANNELS_schema, PROMOTIONS_schema, SALES_schema]) "WITH monthly_sales AS (SELECT s.\"prod_id\", t.\"calendar_month_number\", t.\"calendar_year\", SUM(s.\"amount_sold\") AS total_sales FROM \"COMPLEX_ORACLE\".\"COMPLEX_ORACLE\".\"SALES\" AS s JOIN \"COMPLEX_ORACLE\".\"COMPLEX_ORACLE\".\"CUSTOMERS\" AS c ON s.\"cust_id\" = c.\"cust_id\" JOIN \"COMPLEX_ORACLE\".\"COMPLEX_ORACLE\".\"COUNTRIES\" AS co ON c.\"country_id\" = co.\"country_id\" JOIN \"COMPLEX_ORACLE\".\"COMPLEX_ORACLE\".\"TIMES\" AS t ON s.\"time_id\" = t.\"time_id\" JOIN \"COMPLEX_ORACLE\".\"COMPLEX_ORACLE\".\"PROMOTIONS\" AS p ON s.\"promo_id\" = p.\"promo_id\" JOIN \"COMPLEX_ORACLE\".\"COMPLEX_ORACLE\".\"CHANNELS\" AS ch ON s.\"channel_id\" = ch.\"channel_id\" WHERE co.\"country_name\" = 'France' AND t.\"calendar_year\" IN (2019, 2020) AND p.\"promo_total_id\" = 1 AND ch.\"channel_total_id\" = 1 GROUP BY s.\"prod_id\", t.\"calendar_month_number\", t.\"calendar_year\"), sales_2019 AS (SELECT \"prod_id\", \"calendar_month_number\", total_sales AS sales_2019 FROM monthly_sales WHERE \"calendar_year\" = 2019), sales_2020 AS (SELECT \"prod_id\", \"calendar_month_number\", total_sales AS sales_2020 FROM monthly_sales WHERE \"calendar_year\" = 2020), projected AS (SELECT s20.\"calendar_month_number\", ((CAST((s20.sales_2020 - s19.sales_2019) AS DOUBLE PRECISION) / s19.sales_2019) * s20.sales_2020) + s20.sales_2020 AS projected_2021 FROM sales_2019 AS s19 INNER JOIN sales_2020 AS s20 ON s19.\"prod_id\" = s20.\"prod_id\" AND s19.\"calendar_month_number\" = s20.\"calendar_month_number\"), with_currency AS (SELECT p.\"calendar_month_number\", p.projected_2021 * cur.\"to_us\" AS projected_usd FROM projected AS p JOIN \"COMPLEX_ORACLE\".\"COMPLEX_ORACLE\".\"CURRENCY\" AS cur ON cur.\"country\" = 'France' AND cur.\"year\" = 2021 AND cur.\"month\" = p.\"calendar_month_number\") SELECT \"calendar_month_number\", AVG(projected_usd) AS \"AVG_PROJECTED_USD_SALES\" FROM with_currency GROUP BY \"calendar_month_number\" ORDER BY \"calendar_month_number\"") t0 t1 t2 t3 t4 t5 t6
  = (sql%([COUNTRIES_schema, CURRENCY_schema, CUSTOMERS_schema, TIMES_schema, CHANNELS_schema, PROMOTIONS_schema, SALES_schema]) "WITH france_sales AS (SELECT s.\"prod_id\", t.\"calendar_year\", t.\"calendar_month_number\", SUM(s.\"amount_sold\") AS total_sales FROM \"COMPLEX_ORACLE\".\"COMPLEX_ORACLE\".\"SALES\" AS s JOIN \"COMPLEX_ORACLE\".\"COMPLEX_ORACLE\".\"TIMES\" AS t ON s.\"time_id\" = t.\"time_id\" JOIN \"COMPLEX_ORACLE\".\"COMPLEX_ORACLE\".\"CUSTOMERS\" AS cu ON s.\"cust_id\" = cu.\"cust_id\" JOIN \"COMPLEX_ORACLE\".\"COMPLEX_ORACLE\".\"COUNTRIES\" AS co ON cu.\"country_id\" = co.\"country_id\" JOIN \"COMPLEX_ORACLE\".\"COMPLEX_ORACLE\".\"PROMOTIONS\" AS p ON s.\"promo_id\" = p.\"promo_id\" JOIN \"COMPLEX_ORACLE\".\"COMPLEX_ORACLE\".\"CHANNELS\" AS ch ON s.\"channel_id\" = ch.\"channel_id\" WHERE co.\"country_name\" = 'France' AND t.\"calendar_year\" IN (2019, 2020) AND p.\"promo_total_id\" = 1 AND ch.\"channel_total_id\" = 1 GROUP BY s.\"prod_id\", t.\"calendar_year\", t.\"calendar_month_number\"), sales_2019 AS (SELECT \"prod_id\", \"calendar_month_number\", total_sales AS sales_19 FROM france_sales WHERE \"calendar_year\" = 2019), sales_2020 AS (SELECT \"prod_id\", \"calendar_month_number\", total_sales AS sales_20 FROM france_sales WHERE \"calendar_year\" = 2020), projected AS (SELECT s20.\"prod_id\", s20.\"calendar_month_number\", s20.sales_20, s19.sales_19, (CAST((s20.sales_20 - s19.sales_19) AS DOUBLE PRECISION) / s19.sales_19) AS growth_rate, (CAST((s20.sales_20 - s19.sales_19) AS DOUBLE PRECISION) / s19.sales_19) * s20.sales_20 + s20.sales_20 AS projected_2021 FROM sales_2020 AS s20 JOIN sales_2019 AS s19 ON s20.\"prod_id\" = s19.\"prod_id\" AND s20.\"calendar_month_number\" = s19.\"calendar_month_number\" WHERE s19.sales_19 > 0), currency_2021 AS (SELECT \"month\", \"to_us\" FROM \"COMPLEX_ORACLE\".\"COMPLEX_ORACLE\".\"CURRENCY\" WHERE \"country\" = 'France' AND \"year\" = 2021) SELECT p.\"calendar_month_number\" AS \"MONTH\", ROUND(CAST(AVG(p.projected_2021 * c.\"to_us\") AS DECIMAL), 2) AS \"PROJECTED_SALES_USD\" FROM projected AS p JOIN currency_2021 AS c ON p.\"calendar_month_number\" = c.\"month\" GROUP BY p.\"calendar_month_number\" ORDER BY p.\"calendar_month_number\"") t0 t1 t2 t3 t4 t5 t6
  := by first | sql_equiv | sorry

end N_sf_local061_eq_0_3
