import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_local132_eq_2_3

CREATE TABLE ENTERTAINERS («EntertainerID» INT, «EntStageName» STRING, «EntSSN» STRING, «EntStreetAddress» STRING, «EntCity» STRING, «EntState» STRING, «EntZipCode» STRING, «EntPhoneNumber» STRING, «EntWebPage» STRING, «EntEMailAddress» STRING, «DateEntered» STRING)
CREATE TABLE ENTERTAINER_STYLES («EntertainerID» INT, «StyleID» INT, «StyleStrength» INT)
CREATE TABLE CUSTOMERS («CustomerID» INT, «CustFirstName» STRING, «CustLastName» STRING, «CustStreetAddress» STRING, «CustCity» STRING, «CustState» STRING, «CustZipCode» STRING, «CustPhoneNumber» STRING)
CREATE TABLE MUSICAL_PREFERENCES («CustomerID» INT, «StyleID» INT, «PreferenceSeq» INT)

theorem eq (t0 : TableRel ENTERTAINERS_schema) (t1 : TableRel ENTERTAINER_STYLES_schema) (t2 : TableRel CUSTOMERS_schema) (t3 : TableRel MUSICAL_PREFERENCES_schema) :
    (sql%([ENTERTAINERS_schema, ENTERTAINER_STYLES_schema, CUSTOMERS_schema, MUSICAL_PREFERENCES_schema]) "WITH ent_styles AS (SELECT es.\"EntertainerID\", es.\"StyleID\", es.\"StyleStrength\", COUNT(*) OVER (PARTITION BY es.\"EntertainerID\") AS style_count FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"ENTERTAINER_STYLES\" AS es), cust_prefs AS (SELECT mp.\"CustomerID\", mp.\"StyleID\", mp.\"PreferenceSeq\", COUNT(*) OVER (PARTITION BY mp.\"CustomerID\") AS pref_count FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\" AS mp), ent_filtered /* Entertainers with up to 3 style strengths */ AS (SELECT \"EntertainerID\", \"StyleID\", \"StyleStrength\" FROM ent_styles WHERE style_count <= 3), cust_filtered /* Customers with up to 3 preferences */ AS (SELECT \"CustomerID\", \"StyleID\", \"PreferenceSeq\" FROM cust_prefs WHERE pref_count <= 3), ent1 /* Entertainer 1st and 2nd styles */ AS (SELECT \"EntertainerID\", \"StyleID\" AS style1 FROM ent_filtered WHERE \"StyleStrength\" = 1), ent2 AS (SELECT \"EntertainerID\", \"StyleID\" AS style2 FROM ent_filtered WHERE \"StyleStrength\" = 2), cust1 /* Customer 1st and 2nd preferences */ AS (SELECT \"CustomerID\", \"StyleID\" AS pref1 FROM cust_filtered WHERE \"PreferenceSeq\" = 1), cust2 AS (SELECT \"CustomerID\", \"StyleID\" AS pref2 FROM cust_filtered WHERE \"PreferenceSeq\" = 2) SELECT DISTINCT e.\"EntStageName\" AS \"StageName\", c.\"CustLastName\" AS \"LastName\" FROM ent1 JOIN ent2 ON ent1.\"EntertainerID\" = ent2.\"EntertainerID\" JOIN cust1 ON 1 = 1 JOIN cust2 ON cust1.\"CustomerID\" = cust2.\"CustomerID\" JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"ENTERTAINERS\" AS e ON ent1.\"EntertainerID\" = e.\"EntertainerID\" JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"CUSTOMERS\" AS c ON cust1.\"CustomerID\" = c.\"CustomerID\" WHERE (cust1.pref1 = ent1.style1 AND cust2.pref2 = ent2.style2) OR (cust1.pref1 = ent2.style2 AND cust2.pref2 = ent1.style1) ORDER BY \"StageName\", \"LastName\"") t0 t1 t2 t3
  ~= (sql%([ENTERTAINERS_schema, ENTERTAINER_STYLES_schema, CUSTOMERS_schema, MUSICAL_PREFERENCES_schema]) "WITH entertainer_style_counts AS (SELECT \"EntertainerID\", COUNT(*) AS style_count FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"ENTERTAINER_STYLES\" GROUP BY \"EntertainerID\" HAVING COUNT(*) <= 3), customer_pref_counts AS (SELECT \"CustomerID\", COUNT(*) AS pref_count FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\" GROUP BY \"CustomerID\" HAVING COUNT(*) <= 3), ent_style1 AS (SELECT es.\"EntertainerID\", es.\"StyleID\" AS style1 FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"ENTERTAINER_STYLES\" AS es WHERE es.\"StyleStrength\" = 1), ent_style2 AS (SELECT es.\"EntertainerID\", es.\"StyleID\" AS style2 FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"ENTERTAINER_STYLES\" AS es WHERE es.\"StyleStrength\" = 2), cust_pref1 AS (SELECT mp.\"CustomerID\", mp.\"StyleID\" AS pref1 FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\" AS mp WHERE mp.\"PreferenceSeq\" = 1), cust_pref2 AS (SELECT mp.\"CustomerID\", mp.\"StyleID\" AS pref2 FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\" AS mp WHERE mp.\"PreferenceSeq\" = 2) SELECT DISTINCT e.\"EntStageName\", c.\"CustLastName\" FROM entertainer_style_counts AS esc JOIN ent_style1 AS es1 ON esc.\"EntertainerID\" = es1.\"EntertainerID\" JOIN ent_style2 AS es2 ON esc.\"EntertainerID\" = es2.\"EntertainerID\" JOIN customer_pref_counts AS cpc ON 1 = 1 JOIN cust_pref1 AS cp1 ON cpc.\"CustomerID\" = cp1.\"CustomerID\" JOIN cust_pref2 AS cp2 ON cpc.\"CustomerID\" = cp2.\"CustomerID\" JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"ENTERTAINERS\" AS e ON e.\"EntertainerID\" = esc.\"EntertainerID\" JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"CUSTOMERS\" AS c ON c.\"CustomerID\" = cpc.\"CustomerID\" WHERE (cp1.pref1 = es1.style1 AND cp2.pref2 = es2.style2) OR (cp1.pref1 = es2.style2 AND cp2.pref2 = es1.style1) ORDER BY e.\"EntStageName\", c.\"CustLastName\"") t0 t1 t2 t3
  := by first | sql_equiv | sorry

end N_sf_local132_eq_2_3
