import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_local008_eq_1_2

CREATE TABLE BATTING («player_id» STRING, «year» INT, «stint» INT, «team_id» STRING, «league_id» STRING, «g» INT, «ab» STRING, «r» STRING, «h» STRING, «double» STRING, «triple» STRING, «hr» STRING, «rbi» STRING, «sb» STRING, «cs» STRING, «bb» STRING, «so» STRING, «ibb» STRING, «hbp» STRING, «sh» STRING, «sf» STRING, «g_idp» STRING)
CREATE TABLE PLAYER («player_id» STRING, «birth_year» STRING, «birth_month» STRING, «birth_day» STRING, «birth_country» STRING, «birth_state» STRING, «birth_city» STRING, «death_year» STRING, «death_month» STRING, «death_day» STRING, «death_country» STRING, «death_state» STRING, «death_city» STRING, «name_first» STRING, «name_last» STRING, «name_given» STRING, «weight» STRING, «height» STRING, «bats» STRING, «throws» STRING, «debut» STRING, «final_game» STRING, «retro_id» STRING, «bbref_id» STRING)

theorem eq (t0 : TableRel BATTING_schema) (t1 : TableRel PLAYER_schema) :
    (sql%([BATTING_schema, PLAYER_schema]) "WITH career_stats AS (SELECT b.\"PLAYER_ID\", SUM(COALESCE(b.\"G\", 0)) AS total_games, SUM(COALESCE(b.\"R\", 0)) AS total_runs, SUM(COALESCE(b.\"H\", 0)) AS total_hits, SUM(COALESCE(b.\"HR\", 0)) AS total_hr FROM \"BASEBALL\".\"BASEBALL\".\"BATTING\" AS b GROUP BY b.\"PLAYER_ID\"), max_games AS (SELECT 'Games Played' AS \"Category\", p.\"NAME_GIVEN\" AS \"Player_Name\", cs.total_games AS \"Batting_Table_Topper\" FROM career_stats AS cs JOIN \"BASEBALL\".\"BASEBALL\".\"PLAYER\" AS p ON cs.\"PLAYER_ID\" = p.\"PLAYER_ID\" ORDER BY cs.total_games DESC LIMIT 1), max_runs AS (SELECT 'Runs' AS \"Category\", p.\"NAME_GIVEN\" AS \"Player_Name\", cs.total_runs AS \"Batting_Table_Topper\" FROM career_stats AS cs JOIN \"BASEBALL\".\"BASEBALL\".\"PLAYER\" AS p ON cs.\"PLAYER_ID\" = p.\"PLAYER_ID\" ORDER BY cs.total_runs DESC LIMIT 1), max_hits AS (SELECT 'Hits' AS \"Category\", p.\"NAME_GIVEN\" AS \"Player_Name\", cs.total_hits AS \"Batting_Table_Topper\" FROM career_stats AS cs JOIN \"BASEBALL\".\"BASEBALL\".\"PLAYER\" AS p ON cs.\"PLAYER_ID\" = p.\"PLAYER_ID\" ORDER BY cs.total_hits DESC LIMIT 1), max_hr AS (SELECT 'Home Runs' AS \"Category\", p.\"NAME_GIVEN\" AS \"Player_Name\", cs.total_hr AS \"Batting_Table_Topper\" FROM career_stats AS cs JOIN \"BASEBALL\".\"BASEBALL\".\"PLAYER\" AS p ON cs.\"PLAYER_ID\" = p.\"PLAYER_ID\" ORDER BY cs.total_hr DESC LIMIT 1) SELECT * FROM max_games UNION ALL SELECT * FROM max_runs UNION ALL SELECT * FROM max_hits UNION ALL SELECT * FROM max_hr") t0 t1
  ~= (sql%([BATTING_schema, PLAYER_schema]) "WITH career_totals AS (SELECT b.\"PLAYER_ID\", SUM(COALESCE(b.\"G\", 0)) AS total_g, SUM(COALESCE(b.\"R\", 0)) AS total_r, SUM(COALESCE(b.\"H\", 0)) AS total_h, SUM(COALESCE(b.\"HR\", 0)) AS total_hr FROM \"BASEBALL\".\"BASEBALL\".\"BATTING\" AS b GROUP BY b.\"PLAYER_ID\"), games_leader AS (SELECT 'Games Played' AS \"Category\", p.\"NAME_GIVEN\" AS \"Player_Name\", ct.total_g AS \"Batting_Table_Topper\" FROM career_totals AS ct JOIN \"BASEBALL\".\"BASEBALL\".\"PLAYER\" AS p ON ct.\"PLAYER_ID\" = p.\"PLAYER_ID\" ORDER BY ct.total_g DESC LIMIT 1), runs_leader AS (SELECT 'Runs' AS \"Category\", p.\"NAME_GIVEN\" AS \"Player_Name\", ct.total_r AS \"Batting_Table_Topper\" FROM career_totals AS ct JOIN \"BASEBALL\".\"BASEBALL\".\"PLAYER\" AS p ON ct.\"PLAYER_ID\" = p.\"PLAYER_ID\" ORDER BY ct.total_r DESC LIMIT 1), hits_leader AS (SELECT 'Hits' AS \"Category\", p.\"NAME_GIVEN\" AS \"Player_Name\", ct.total_h AS \"Batting_Table_Topper\" FROM career_totals AS ct JOIN \"BASEBALL\".\"BASEBALL\".\"PLAYER\" AS p ON ct.\"PLAYER_ID\" = p.\"PLAYER_ID\" ORDER BY ct.total_h DESC LIMIT 1), hr_leader AS (SELECT 'Home Runs' AS \"Category\", p.\"NAME_GIVEN\" AS \"Player_Name\", ct.total_hr AS \"Batting_Table_Topper\" FROM career_totals AS ct JOIN \"BASEBALL\".\"BASEBALL\".\"PLAYER\" AS p ON ct.\"PLAYER_ID\" = p.\"PLAYER_ID\" ORDER BY ct.total_hr DESC LIMIT 1) SELECT * FROM games_leader UNION ALL SELECT * FROM runs_leader UNION ALL SELECT * FROM hits_leader UNION ALL SELECT * FROM hr_leader") t0 t1
  := by first | sql_equiv | sorry

end N_sf_local008_eq_1_2
