import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_local055_eq_1_3

CREATE TABLE TRACKS («TrackId» INT, «Name» STRING, «AlbumId» INT, «MediaTypeId» INT, «GenreId» INT, «Composer» STRING, «Milliseconds» INT, «Bytes» INT, «UnitPrice» FLOAT)
CREATE TABLE ALBUMS («AlbumId» INT, «Title» STRING, «ArtistId» INT)
CREATE TABLE ARTISTS («ArtistId» INT, «Name» STRING)
CREATE TABLE INVOICES («InvoiceId» INT, «CustomerId» INT, «InvoiceDate» STRING, «BillingAddress» STRING, «BillingCity» STRING, «BillingState» STRING, «BillingCountry» STRING, «BillingPostalCode» STRING, «Total» FLOAT)
CREATE TABLE INVOICE_ITEMS («InvoiceLineId» INT, «InvoiceId» INT, «TrackId» INT, «UnitPrice» FLOAT, «Quantity» INT)

theorem eq (t0 : TableRel TRACKS_schema) (t1 : TableRel ALBUMS_schema) (t2 : TableRel ARTISTS_schema) (t3 : TableRel INVOICES_schema) (t4 : TableRel INVOICE_ITEMS_schema) :
    (sql%([TRACKS_schema, ALBUMS_schema, ARTISTS_schema, INVOICES_schema, INVOICE_ITEMS_schema]) "WITH artist_sales AS (SELECT ar.\"ArtistId\", ar.\"Name\", SUM(ii.\"UnitPrice\" * ii.\"Quantity\") AS TotalSales FROM \"CHINOOK\".\"CHINOOK\".\"ARTISTS\" AS ar JOIN \"CHINOOK\".\"CHINOOK\".\"ALBUMS\" AS al ON ar.\"ArtistId\" = al.\"ArtistId\" JOIN \"CHINOOK\".\"CHINOOK\".\"TRACKS\" AS t ON al.\"AlbumId\" = t.\"AlbumId\" JOIN \"CHINOOK\".\"CHINOOK\".\"INVOICE_ITEMS\" AS ii ON t.\"TrackId\" = ii.\"TrackId\" GROUP BY ar.\"ArtistId\", ar.\"Name\"), top_artist AS (SELECT \"ArtistId\" FROM artist_sales ORDER BY TotalSales DESC, \"Name\" ASC LIMIT 1), bottom_artist AS (SELECT \"ArtistId\" FROM artist_sales ORDER BY TotalSales ASC, \"Name\" ASC LIMIT 1), top_customer_spending AS (SELECT c.\"CustomerId\", SUM(ii.\"UnitPrice\" * ii.\"Quantity\") AS spending FROM \"CHINOOK\".\"CHINOOK\".\"CUSTOMERS\" AS c JOIN \"CHINOOK\".\"CHINOOK\".\"INVOICES\" AS i ON c.\"CustomerId\" = i.\"CustomerId\" JOIN \"CHINOOK\".\"CHINOOK\".\"INVOICE_ITEMS\" AS ii ON i.\"InvoiceId\" = ii.\"InvoiceId\" JOIN \"CHINOOK\".\"CHINOOK\".\"TRACKS\" AS t ON ii.\"TrackId\" = t.\"TrackId\" JOIN \"CHINOOK\".\"CHINOOK\".\"ALBUMS\" AS al ON t.\"AlbumId\" = al.\"AlbumId\" WHERE al.\"ArtistId\" = (SELECT \"ArtistId\" FROM top_artist) GROUP BY c.\"CustomerId\"), bottom_customer_spending AS (SELECT c.\"CustomerId\", SUM(ii.\"UnitPrice\" * ii.\"Quantity\") AS spending FROM \"CHINOOK\".\"CHINOOK\".\"CUSTOMERS\" AS c JOIN \"CHINOOK\".\"CHINOOK\".\"INVOICES\" AS i ON c.\"CustomerId\" = i.\"CustomerId\" JOIN \"CHINOOK\".\"CHINOOK\".\"INVOICE_ITEMS\" AS ii ON i.\"InvoiceId\" = ii.\"InvoiceId\" JOIN \"CHINOOK\".\"CHINOOK\".\"TRACKS\" AS t ON ii.\"TrackId\" = t.\"TrackId\" JOIN \"CHINOOK\".\"CHINOOK\".\"ALBUMS\" AS al ON t.\"AlbumId\" = al.\"AlbumId\" WHERE al.\"ArtistId\" = (SELECT \"ArtistId\" FROM bottom_artist) GROUP BY c.\"CustomerId\") SELECT ABS((SELECT AVG(spending) FROM top_customer_spending) - (SELECT AVG(spending) FROM bottom_customer_spending)) AS \"OUTPUT\"") t0 t1 t2 t3 t4
  ~= (sql%([TRACKS_schema, ALBUMS_schema, ARTISTS_schema, INVOICES_schema, INVOICE_ITEMS_schema]) "WITH artist_sales AS (SELECT ar.\"ArtistId\", ar.\"Name\" AS ArtistName, SUM(ii.\"UnitPrice\" * ii.\"Quantity\") AS TotalSales FROM \"CHINOOK\".\"CHINOOK\".\"ARTISTS\" AS ar JOIN \"CHINOOK\".\"CHINOOK\".\"ALBUMS\" AS al ON ar.\"ArtistId\" = al.\"ArtistId\" JOIN \"CHINOOK\".\"CHINOOK\".\"TRACKS\" AS t ON al.\"AlbumId\" = t.\"AlbumId\" JOIN \"CHINOOK\".\"CHINOOK\".\"INVOICE_ITEMS\" AS ii ON t.\"TrackId\" = ii.\"TrackId\" GROUP BY ar.\"ArtistId\", ar.\"Name\"), top_artist AS (SELECT \"ArtistId\" FROM artist_sales ORDER BY TotalSales DESC, ArtistName ASC LIMIT 1), bottom_artist AS (SELECT \"ArtistId\" FROM artist_sales ORDER BY TotalSales ASC, ArtistName ASC LIMIT 1), customer_spending_top AS (SELECT i.\"CustomerId\", SUM(ii.\"UnitPrice\" * ii.\"Quantity\") AS spending FROM \"CHINOOK\".\"CHINOOK\".\"INVOICE_ITEMS\" AS ii JOIN \"CHINOOK\".\"CHINOOK\".\"TRACKS\" AS t ON ii.\"TrackId\" = t.\"TrackId\" JOIN \"CHINOOK\".\"CHINOOK\".\"ALBUMS\" AS al ON t.\"AlbumId\" = al.\"AlbumId\" JOIN \"CHINOOK\".\"CHINOOK\".\"INVOICES\" AS i ON ii.\"InvoiceId\" = i.\"InvoiceId\" WHERE al.\"ArtistId\" = (SELECT \"ArtistId\" FROM top_artist) GROUP BY i.\"CustomerId\"), customer_spending_bottom AS (SELECT i.\"CustomerId\", SUM(ii.\"UnitPrice\" * ii.\"Quantity\") AS spending FROM \"CHINOOK\".\"CHINOOK\".\"INVOICE_ITEMS\" AS ii JOIN \"CHINOOK\".\"CHINOOK\".\"TRACKS\" AS t ON ii.\"TrackId\" = t.\"TrackId\" JOIN \"CHINOOK\".\"CHINOOK\".\"ALBUMS\" AS al ON t.\"AlbumId\" = al.\"AlbumId\" JOIN \"CHINOOK\".\"CHINOOK\".\"INVOICES\" AS i ON ii.\"InvoiceId\" = i.\"InvoiceId\" WHERE al.\"ArtistId\" = (SELECT \"ArtistId\" FROM bottom_artist) GROUP BY i.\"CustomerId\") SELECT ABS((SELECT AVG(spending) FROM customer_spending_top) - (SELECT AVG(spending) FROM customer_spending_bottom)) AS absolute_difference") t0 t1 t2 t3 t4
  := by first | sql_equiv | sorry

end N_sf_local055_eq_1_3
