import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_local170_eq_0_1

CREATE TABLE LEGISLATORS («full_name» STRING, «first_name» STRING, «last_name» STRING, «middle_name» STRING, «nickname» STRING, «suffix» STRING, «other_names_end» STRING, «other_names_middle» STRING, «other_names_last» STRING, «birthday» STRING, «gender» STRING, «id_bioguide» STRING, «id_bioguide_previous_0» STRING, «id_govtrack» INT, «id_icpsr» FLOAT, «id_wikipedia» STRING, «id_wikidata» STRING, «id_google_entity_id» STRING, «id_house_history» FLOAT, «id_house_history_alternate» FLOAT, «id_thomas» FLOAT, «id_cspan» FLOAT, «id_votesmart» FLOAT, «id_lis» STRING, «id_ballotpedia» STRING, «id_opensecrets» STRING, «id_fec_0» STRING, «id_fec_1» STRING, «id_fec_2» STRING)
CREATE TABLE LEGISLATORS_TERMS («id_bioguide» STRING, «term_number» INT, «term_id» STRING, «term_type» STRING, «term_start» STRING, «term_end» STRING, «state» STRING, «district» FLOAT, «class» FLOAT, «party» STRING, «how» STRING, «url» STRING, «address» STRING, «phone» STRING, «fax» STRING, «contact_form» STRING, «office» STRING, «state_rank» STRING, «rss_url» STRING, «caucus» STRING)

theorem eq (t0 : TableRel LEGISLATORS_schema) (t1 : TableRel LEGISLATORS_TERMS_schema) :
    (sql%([LEGISLATORS_schema, LEGISLATORS_TERMS_schema]) "WITH first_terms AS (SELECT \"id_bioguide\", MIN(CAST(\"term_start\" AS DATE)) AS first_term_date FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"LEGISLATORS_TERMS\" GROUP BY \"id_bioguide\"), cohort AS (SELECT DISTINCT lt.\"id_bioguide\", lt.\"state\", l.\"gender\", ft.first_term_date FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"LEGISLATORS_TERMS\" AS lt JOIN \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"LEGISLATORS\" AS l ON lt.\"id_bioguide\" = l.\"id_bioguide\" JOIN first_terms AS ft ON lt.\"id_bioguide\" = ft.\"id_bioguide\"), years AS (SELECT 0 AS yr UNION ALL SELECT 2 UNION ALL SELECT 4 UNION ALL SELECT 6 UNION ALL SELECT 8 UNION ALL SELECT 10), retention_check AS (SELECT c.\"state\", c.\"gender\", y.yr, COUNT(DISTINCT c.\"id_bioguide\") AS cohort_size, COUNT(DISTINCT CASE WHEN EXISTS(SELECT 1 FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"LEGISLATORS_TERMS\" AS t WHERE t.\"id_bioguide\" = c.\"id_bioguide\" AND t.\"state\" = c.\"state\" AND CAST(t.\"term_start\" AS DATE) <= DATE_FROM_PARTS(EXTRACT(YEAR FROM c.first_term_date) + y.yr, 12, 31) AND CAST(t.\"term_end\" AS DATE) >= DATE_FROM_PARTS(EXTRACT(YEAR FROM c.first_term_date) + y.yr, 12, 31)) THEN c.\"id_bioguide\" END) AS retained FROM cohort AS c CROSS JOIN years AS y GROUP BY c.\"state\", c.\"gender\", y.yr), retention_rates AS (SELECT \"state\", \"gender\", yr, CAST(retained * 1.0 AS DOUBLE PRECISION) / cohort_size AS retention_rate FROM retention_check), valid_states AS (SELECT \"state\" FROM retention_rates GROUP BY \"state\" HAVING SUM(CASE WHEN retention_rate > 0 THEN 1 ELSE 0 END) = 12 AND COUNT(DISTINCT \"gender\") = 2) SELECT \"state\" FROM valid_states ORDER BY \"state\"") t0 t1
  ~= (sql%([LEGISLATORS_schema, LEGISLATORS_TERMS_schema]) "/* Cohort retention analysis for legislators by state and gender */ /* A legislator's cohort is defined by their first term (term_number=0) state and gender. */ /* Check retention at 0, 2, 4, 6, 8, 10 years after first term start on Dec 31 of that year. */ /* Return states where BOTH male and female cohorts have non-zero retention at ALL 6 intervals. */ WITH first_terms AS (/* Get each legislator's first term info (cohort assignment) */ SELECT t.\"id_bioguide\", l.\"gender\", t.\"state\", CAST(t.\"term_start\" AS DATE) AS first_term_start, EXTRACT(YEAR FROM CAST(t.\"term_start\" AS DATE)) AS first_year FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"LEGISLATORS_TERMS\" AS t JOIN \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"LEGISLATORS\" AS l ON t.\"id_bioguide\" = l.\"id_bioguide\" WHERE t.\"term_number\" = 0), intervals /* Generate the 6 check intervals */ AS (SELECT column1 AS years_after FROM (VALUES (0), (2), (4), (6), (8), (10))), legislator_checks /* For each legislator, generate check dates at each interval */ AS (SELECT ft.\"id_bioguide\", ft.\"gender\", ft.\"state\", i.years_after, DATE_FROM_PARTS(ft.first_year + i.years_after, 12, 31) AS check_date FROM first_terms AS ft CROSS JOIN intervals AS i), retention /* Check if a legislator is retained (serving on the check date) */ /* A legislator is retained if ANY of their terms covers the check date */ AS (SELECT lc.\"id_bioguide\", lc.\"gender\", lc.\"state\", lc.years_after, MAX(CASE WHEN CAST(t.\"term_start\" AS DATE) <= lc.check_date AND CAST(t.\"term_end\" AS DATE) >= lc.check_date THEN 1 ELSE 0 END) AS is_retained FROM legislator_checks AS lc LEFT JOIN \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"LEGISLATORS_TERMS\" AS t ON lc.\"id_bioguide\" = t.\"id_bioguide\" GROUP BY lc.\"id_bioguide\", lc.\"gender\", lc.\"state\", lc.years_after), state_gender_retention /* Aggregate retention rate per state, gender, and interval */ AS (SELECT \"state\", \"gender\", years_after, SUM(is_retained) AS retained_count, COUNT(*) AS cohort_size, CAST(SUM(is_retained) * 1.0 AS DOUBLE PRECISION) / COUNT(*) AS retention_rate FROM retention GROUP BY \"state\", \"gender\", years_after), qualifying_states /* Find states where BOTH genders have non-zero retention at ALL 6 intervals */ /* Each state needs 2 genders × 6 intervals = 12 rows with retention_rate > 0 */ AS (SELECT \"state\" FROM state_gender_retention WHERE retention_rate > 0 AND \"gender\" IN ('M', 'F') GROUP BY \"state\" HAVING COUNT(DISTINCT \"gender\" || '_' || years_after) = 12) SELECT \"state\" FROM qualifying_states ORDER BY \"state\"") t0 t1
  := by first | sql_equiv | sorry

end N_sf_local170_eq_0_1
