import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_local002_eq_0_2

CREATE TABLE ORDER_ITEMS («order_id» STRING, «order_item_id» INT, «product_id» STRING, «seller_id» STRING, «shipping_limit_date» STRING, «price» FLOAT, «freight_value» FLOAT)
CREATE TABLE PRODUCTS («product_id» STRING, «product_category_name» STRING, «product_name_lenght» FLOAT, «product_description_lenght» FLOAT, «product_photos_qty» FLOAT, «product_weight_g» FLOAT, «product_length_cm» FLOAT, «product_height_cm» FLOAT, «product_width_cm» FLOAT)
CREATE TABLE ORDERS («order_id» STRING, «customer_id» STRING, «order_status» STRING, «order_purchase_timestamp» STRING, «order_approved_at» STRING, «order_delivered_carrier_date» STRING, «order_delivered_customer_date» STRING, «order_estimated_delivery_date» STRING)

theorem eq (t0 : TableRel ORDER_ITEMS_schema) (t1 : TableRel PRODUCTS_schema) (t2 : TableRel ORDERS_schema) :
    (sql%([ORDER_ITEMS_schema, PRODUCTS_schema, ORDERS_schema]) "/* sf_local002: 5-day symmetric moving average of predicted toy sales (price) */ /* Using simple linear regression on daily toy sales from 2017-01-01 to 2018-08-29 */ /* Predictions for Dec 5-8, 2018, then sum the 4 moving averages */ WITH daily_sales AS (SELECT CAST(o.\"order_purchase_timestamp\" AS DATE) AS sale_date, SUM(CAST(oi.\"price\" AS DOUBLE PRECISION)) AS sum_price FROM \"E_COMMERCE\".\"E_COMMERCE\".\"ORDERS\" AS o JOIN \"E_COMMERCE\".\"E_COMMERCE\".\"ORDER_ITEMS\" AS oi ON o.\"order_id\" = oi.\"order_id\" JOIN \"E_COMMERCE\".\"E_COMMERCE\".\"PRODUCTS\" AS p ON oi.\"product_id\" = p.\"product_id\" WHERE p.\"product_category_name\" = 'brinquedos' AND CAST(o.\"order_purchase_timestamp\" AS DATE) BETWEEN '2017-01-01' AND '2018-08-29' GROUP BY CAST(o.\"order_purchase_timestamp\" AS DATE)), all_dates AS (SELECT CAST('2017-01-01' + INTERVAL '1 DAY' * SEQ4() AS DATE) AS sale_date FROM TABLE(GENERATOR(606))), full_data AS (SELECT a.sale_date, (CAST(a.sale_date AS DATE) - CAST('2017-01-01' AS DATE)) + 1 AS day_num, COALESCE(d.sum_price, 0) AS y FROM all_dates AS a LEFT JOIN daily_sales AS d ON a.sale_date = d.sale_date), regression AS (SELECT REGR_SLOPE(y, day_num) AS slope, REGR_INTERCEPT(y, day_num) AS intercept FROM full_data), pred_dates AS (SELECT CAST('2017-01-01' + INTERVAL '1 DAY' * (SEQ4() + (CAST('2018-12-03' AS DATE) - CAST('2017-01-01' AS DATE))) AS DATE) AS pred_date, (CAST('2017-01-01' + INTERVAL '1 DAY' * (SEQ4() + (CAST('2018-12-03' AS DATE) - CAST('2017-01-01' AS DATE))) AS DATE) - CAST('2017-01-01' AS DATE)) + 1 AS day_num FROM TABLE(GENERATOR(8))), predictions AS (SELECT pd.pred_date, pd.day_num, r.slope * pd.day_num + r.intercept AS pred_price FROM pred_dates AS pd, regression AS r), moving_avg AS (SELECT p.pred_date, AVG(p2.pred_price) AS ma_price FROM predictions AS p JOIN predictions AS p2 ON p2.day_num BETWEEN p.day_num - 2 AND p.day_num + 2 WHERE p.pred_date BETWEEN '2018-12-05' AND '2018-12-08' GROUP BY p.pred_date) SELECT SUM(ma_price) AS TOTAL FROM moving_avg") t0 t1 t2
  ~= (sql%([ORDER_ITEMS_schema, PRODUCTS_schema, ORDERS_schema]) "WITH calendar AS (/* Generate all dates from 2017-01-01 to 2018-08-29 (606 days) */ SELECT CAST('2017-01-01' AS DATE) + INTERVAL '1 DAY' * SEQ4() AS sale_date FROM TABLE(GENERATOR(606))), toy_daily_sales AS (SELECT CAST(o.\"order_purchase_timestamp\" AS DATE) AS sale_date, SUM(oi.\"price\") AS daily_sales FROM \"E_COMMERCE\".\"E_COMMERCE\".\"ORDERS\" AS o JOIN \"E_COMMERCE\".\"E_COMMERCE\".\"ORDER_ITEMS\" AS oi ON o.\"order_id\" = oi.\"order_id\" JOIN \"E_COMMERCE\".\"E_COMMERCE\".\"PRODUCTS\" AS p ON oi.\"product_id\" = p.\"product_id\" WHERE p.\"product_category_name\" = 'brinquedos' AND CAST(o.\"order_purchase_timestamp\" AS DATE) BETWEEN '2017-01-01' AND '2018-08-29' GROUP BY CAST(o.\"order_purchase_timestamp\" AS DATE)), daily_data AS (SELECT c.sale_date, COALESCE(t.daily_sales, 0) AS y, (CAST(c.sale_date AS DATE) - CAST('2017-01-01' AS DATE)) AS x FROM calendar AS c LEFT JOIN toy_daily_sales AS t ON c.sale_date = t.sale_date), regression_params AS (SELECT REGR_SLOPE(CAST(y AS DOUBLE PRECISION), CAST(x AS DOUBLE PRECISION)) AS slope, REGR_INTERCEPT(CAST(y AS DOUBLE PRECISION), CAST(x AS DOUBLE PRECISION)) AS intercept FROM daily_data), prediction_dates AS (/* Dec 3 to Dec 10, 2018 (need +-2 days around Dec 5-8) */ SELECT CAST('2018-12-03' AS DATE) + INTERVAL '1 DAY' * SEQ4() AS pred_date FROM TABLE(GENERATOR(8))), predictions AS (SELECT pd.pred_date, rp.slope * (CAST(pd.pred_date AS DATE) - CAST('2017-01-01' AS DATE)) + rp.intercept AS predicted_sales FROM prediction_dates AS pd CROSS JOIN regression_params AS rp), moving_avg AS (SELECT p.pred_date, AVG(p2.predicted_sales) AS ma5 FROM predictions AS p JOIN predictions AS p2 ON p2.pred_date BETWEEN p.pred_date + INTERVAL '-2 DAY' AND p.pred_date + INTERVAL '2 DAY' WHERE p.pred_date BETWEEN '2018-12-05' AND '2018-12-08' GROUP BY p.pred_date) SELECT SUM(ma5) AS \"TOTAL\" FROM moving_avg") t0 t1 t2
  := by first | sql_equiv | sorry

end N_sf_local002_eq_0_2
