import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_local040 — crossskill equivalence(s)

Question: In the combined dataset that unifies the trees data with the income data by ZIP code, filling missing ZIP values where necessary, which three boroughs, restricted to records with median and mean income both greater than zero and a valid borough name, contain the highest number of trees, and what is the average mean income for each of these three boroughs?

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_local040

CREATE TABLE INCOME_TREES («zipcode» INT, «Estimate_Total» INT, «Margin_of_Error_Total» INT, «Estimate_Median_income» INT, «Margin_of_Error_Median_income» INT, «Estimate_Mean_income» INT, «Margin_of_Error_Mean_income» INT)
CREATE TABLE TREES («idx» INT, «tree_id» INT, «tree_dbh» INT, «stump_diam» INT, «status» STRING, «health» STRING, «spc_latin» STRING, «spc_common» STRING, «address» STRING, «zipcode» INT, «borocode» INT, «boroname» STRING, «nta_name» STRING, «state» STRING, «latitude» FLOAT, «longitude» FLOAT)

theorem eq_0_1 : ∀ t,
    (sql%([INCOME_TREES_schema, TREES_schema]) "WITH combined AS (SELECT t.\"boroname\", i.\"Estimate_Mean_income\", i.\"Estimate_Median_income\" FROM \"MODERN_DATA\".\"MODERN_DATA\".\"TREES\" AS t LEFT JOIN \"MODERN_DATA\".\"MODERN_DATA\".\"INCOME_TREES\" AS i ON t.\"zipcode\" = i.\"zipcode\" WHERE i.\"Estimate_Median_income\" > 0 AND i.\"Estimate_Mean_income\" > 0 AND NOT t.\"boroname\" IS NULL AND t.\"boroname\" <> ''), borough_stats AS (SELECT \"boroname\", COUNT(*) AS tree_count, ROUND(CAST(AVG(\"Estimate_Mean_income\") AS DECIMAL), 4) AS mean_income FROM combined GROUP BY \"boroname\" ORDER BY tree_count DESC LIMIT 3) SELECT \"boroname\", mean_income FROM borough_stats ORDER BY mean_income DESC") t ~= (sql%([INCOME_TREES_schema, TREES_schema]) "WITH borough_stats AS (SELECT t.\"boroname\", COUNT(*) AS tree_count, ROUND(CAST(AVG(i.\"Estimate_Mean_income\") AS DECIMAL), 4) AS mean_income FROM \"MODERN_DATA\".\"MODERN_DATA\".\"TREES\" AS t INNER JOIN \"MODERN_DATA\".\"MODERN_DATA\".\"INCOME_TREES\" AS i ON t.\"zipcode\" = i.\"zipcode\" WHERE i.\"Estimate_Median_income\" > 0 AND i.\"Estimate_Mean_income\" > 0 AND NOT t.\"boroname\" IS NULL AND t.\"boroname\" <> '' GROUP BY t.\"boroname\" ORDER BY tree_count DESC LIMIT 3) SELECT \"boroname\", mean_income FROM borough_stats ORDER BY mean_income DESC") t := by
  intro t; first | sql_equiv | sorry

theorem eq_0_2 : ∀ t,
    (sql%([INCOME_TREES_schema, TREES_schema]) "WITH combined AS (SELECT t.\"boroname\", i.\"Estimate_Mean_income\", i.\"Estimate_Median_income\" FROM \"MODERN_DATA\".\"MODERN_DATA\".\"TREES\" AS t LEFT JOIN \"MODERN_DATA\".\"MODERN_DATA\".\"INCOME_TREES\" AS i ON t.\"zipcode\" = i.\"zipcode\" WHERE i.\"Estimate_Median_income\" > 0 AND i.\"Estimate_Mean_income\" > 0 AND NOT t.\"boroname\" IS NULL AND t.\"boroname\" <> ''), borough_stats AS (SELECT \"boroname\", COUNT(*) AS tree_count, ROUND(CAST(AVG(\"Estimate_Mean_income\") AS DECIMAL), 4) AS mean_income FROM combined GROUP BY \"boroname\" ORDER BY tree_count DESC LIMIT 3) SELECT \"boroname\", mean_income FROM borough_stats ORDER BY mean_income DESC") t ~= (sql%([INCOME_TREES_schema, TREES_schema]) "WITH top3 AS (SELECT t.\"boroname\", COUNT(*) AS tree_count, ROUND(CAST(AVG(i.\"Estimate_Mean_income\") AS DECIMAL), 4) AS \"mean_income\" FROM \"MODERN_DATA\".\"MODERN_DATA\".\"TREES\" AS t JOIN \"MODERN_DATA\".\"MODERN_DATA\".\"INCOME_TREES\" AS i ON t.\"zipcode\" = i.\"zipcode\" WHERE i.\"Estimate_Median_income\" > 0 AND i.\"Estimate_Mean_income\" > 0 AND NOT t.\"boroname\" IS NULL AND t.\"boroname\" <> '' GROUP BY t.\"boroname\" ORDER BY tree_count DESC LIMIT 3) SELECT \"boroname\", \"mean_income\" FROM top3 ORDER BY \"mean_income\" DESC") t := by
  intro t; first | sql_equiv | sorry

theorem eq_0_3 : ∀ t,
    (sql%([INCOME_TREES_schema, TREES_schema]) "WITH combined AS (SELECT t.\"boroname\", i.\"Estimate_Mean_income\", i.\"Estimate_Median_income\" FROM \"MODERN_DATA\".\"MODERN_DATA\".\"TREES\" AS t LEFT JOIN \"MODERN_DATA\".\"MODERN_DATA\".\"INCOME_TREES\" AS i ON t.\"zipcode\" = i.\"zipcode\" WHERE i.\"Estimate_Median_income\" > 0 AND i.\"Estimate_Mean_income\" > 0 AND NOT t.\"boroname\" IS NULL AND t.\"boroname\" <> ''), borough_stats AS (SELECT \"boroname\", COUNT(*) AS tree_count, ROUND(CAST(AVG(\"Estimate_Mean_income\") AS DECIMAL), 4) AS mean_income FROM combined GROUP BY \"boroname\" ORDER BY tree_count DESC LIMIT 3) SELECT \"boroname\", mean_income FROM borough_stats ORDER BY mean_income DESC") t ~= (sql%([INCOME_TREES_schema, TREES_schema]) "WITH combined AS (SELECT t.\"boroname\", t.\"zipcode\", i.\"Estimate_Median_income\", i.\"Estimate_Mean_income\" FROM \"MODERN_DATA\".\"MODERN_DATA\".\"TREES\" AS t JOIN \"MODERN_DATA\".\"MODERN_DATA\".\"INCOME_TREES\" AS i ON t.\"zipcode\" = i.\"zipcode\" WHERE i.\"Estimate_Median_income\" > 0 AND i.\"Estimate_Mean_income\" > 0 AND NOT t.\"boroname\" IS NULL), top3_boroughs AS (SELECT \"boroname\" FROM combined GROUP BY \"boroname\" ORDER BY COUNT(*) DESC LIMIT 3) SELECT c.\"boroname\", AVG(c.\"Estimate_Mean_income\") AS \"mean_income\" FROM combined AS c WHERE c.\"boroname\" IN (SELECT \"boroname\" FROM top3_boroughs) GROUP BY c.\"boroname\" ORDER BY \"mean_income\" DESC") t := by
  intro t; first | sql_equiv | sorry

theorem eq_1_2 :
    sql%([INCOME_TREES_schema, TREES_schema]) "WITH borough_stats AS (SELECT t.\"boroname\", COUNT(*) AS tree_count, ROUND(CAST(AVG(i.\"Estimate_Mean_income\") AS DECIMAL), 4) AS mean_income FROM \"MODERN_DATA\".\"MODERN_DATA\".\"TREES\" AS t INNER JOIN \"MODERN_DATA\".\"MODERN_DATA\".\"INCOME_TREES\" AS i ON t.\"zipcode\" = i.\"zipcode\" WHERE i.\"Estimate_Median_income\" > 0 AND i.\"Estimate_Mean_income\" > 0 AND NOT t.\"boroname\" IS NULL AND t.\"boroname\" <> '' GROUP BY t.\"boroname\" ORDER BY tree_count DESC LIMIT 3) SELECT \"boroname\", mean_income FROM borough_stats ORDER BY mean_income DESC" = sql%([INCOME_TREES_schema, TREES_schema]) "WITH top3 AS (SELECT t.\"boroname\", COUNT(*) AS tree_count, ROUND(CAST(AVG(i.\"Estimate_Mean_income\") AS DECIMAL), 4) AS \"mean_income\" FROM \"MODERN_DATA\".\"MODERN_DATA\".\"TREES\" AS t JOIN \"MODERN_DATA\".\"MODERN_DATA\".\"INCOME_TREES\" AS i ON t.\"zipcode\" = i.\"zipcode\" WHERE i.\"Estimate_Median_income\" > 0 AND i.\"Estimate_Mean_income\" > 0 AND NOT t.\"boroname\" IS NULL AND t.\"boroname\" <> '' GROUP BY t.\"boroname\" ORDER BY tree_count DESC LIMIT 3) SELECT \"boroname\", \"mean_income\" FROM top3 ORDER BY \"mean_income\" DESC" := by
  first | sql_equiv | sorry

theorem eq_1_3 : ∀ t,
    (sql%([INCOME_TREES_schema, TREES_schema]) "WITH borough_stats AS (SELECT t.\"boroname\", COUNT(*) AS tree_count, ROUND(CAST(AVG(i.\"Estimate_Mean_income\") AS DECIMAL), 4) AS mean_income FROM \"MODERN_DATA\".\"MODERN_DATA\".\"TREES\" AS t INNER JOIN \"MODERN_DATA\".\"MODERN_DATA\".\"INCOME_TREES\" AS i ON t.\"zipcode\" = i.\"zipcode\" WHERE i.\"Estimate_Median_income\" > 0 AND i.\"Estimate_Mean_income\" > 0 AND NOT t.\"boroname\" IS NULL AND t.\"boroname\" <> '' GROUP BY t.\"boroname\" ORDER BY tree_count DESC LIMIT 3) SELECT \"boroname\", mean_income FROM borough_stats ORDER BY mean_income DESC") t ~= (sql%([INCOME_TREES_schema, TREES_schema]) "WITH combined AS (SELECT t.\"boroname\", t.\"zipcode\", i.\"Estimate_Median_income\", i.\"Estimate_Mean_income\" FROM \"MODERN_DATA\".\"MODERN_DATA\".\"TREES\" AS t JOIN \"MODERN_DATA\".\"MODERN_DATA\".\"INCOME_TREES\" AS i ON t.\"zipcode\" = i.\"zipcode\" WHERE i.\"Estimate_Median_income\" > 0 AND i.\"Estimate_Mean_income\" > 0 AND NOT t.\"boroname\" IS NULL), top3_boroughs AS (SELECT \"boroname\" FROM combined GROUP BY \"boroname\" ORDER BY COUNT(*) DESC LIMIT 3) SELECT c.\"boroname\", AVG(c.\"Estimate_Mean_income\") AS \"mean_income\" FROM combined AS c WHERE c.\"boroname\" IN (SELECT \"boroname\" FROM top3_boroughs) GROUP BY c.\"boroname\" ORDER BY \"mean_income\" DESC") t := by
  intro t; first | sql_equiv | sorry

theorem eq_2_3 : ∀ t,
    (sql%([INCOME_TREES_schema, TREES_schema]) "WITH top3 AS (SELECT t.\"boroname\", COUNT(*) AS tree_count, ROUND(CAST(AVG(i.\"Estimate_Mean_income\") AS DECIMAL), 4) AS \"mean_income\" FROM \"MODERN_DATA\".\"MODERN_DATA\".\"TREES\" AS t JOIN \"MODERN_DATA\".\"MODERN_DATA\".\"INCOME_TREES\" AS i ON t.\"zipcode\" = i.\"zipcode\" WHERE i.\"Estimate_Median_income\" > 0 AND i.\"Estimate_Mean_income\" > 0 AND NOT t.\"boroname\" IS NULL AND t.\"boroname\" <> '' GROUP BY t.\"boroname\" ORDER BY tree_count DESC LIMIT 3) SELECT \"boroname\", \"mean_income\" FROM top3 ORDER BY \"mean_income\" DESC") t ~= (sql%([INCOME_TREES_schema, TREES_schema]) "WITH combined AS (SELECT t.\"boroname\", t.\"zipcode\", i.\"Estimate_Median_income\", i.\"Estimate_Mean_income\" FROM \"MODERN_DATA\".\"MODERN_DATA\".\"TREES\" AS t JOIN \"MODERN_DATA\".\"MODERN_DATA\".\"INCOME_TREES\" AS i ON t.\"zipcode\" = i.\"zipcode\" WHERE i.\"Estimate_Median_income\" > 0 AND i.\"Estimate_Mean_income\" > 0 AND NOT t.\"boroname\" IS NULL), top3_boroughs AS (SELECT \"boroname\" FROM combined GROUP BY \"boroname\" ORDER BY COUNT(*) DESC LIMIT 3) SELECT c.\"boroname\", AVG(c.\"Estimate_Mean_income\") AS \"mean_income\" FROM combined AS c WHERE c.\"boroname\" IN (SELECT \"boroname\" FROM top3_boroughs) GROUP BY c.\"boroname\" ORDER BY \"mean_income\" DESC") t := by
  intro t; first | sql_equiv | sorry

end Bench_sf_local040
