import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_local230 — crossskill equivalence(s)

Question: Determine the top three genres with the most movies rated above 8, and then identify the top four directors who have directed the most films rated above 8 within those genres. List these directors and their respective movie counts.

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_local230

CREATE TABLE GENRE («movie_id» STRING, «genre» STRING)
CREATE TABLE MOVIES («id» STRING, «title» STRING, «year» INT, «date_published» STRING, «duration» INT, «country» STRING, «worlwide_gross_income» STRING, «languages» STRING, «production_company» STRING)
CREATE TABLE DIRECTOR_MAPPING («movie_id» STRING, «name_id» STRING)
CREATE TABLE NAMES («id» STRING, «name» STRING, «height» FLOAT, «date_of_birth» STRING, «known_for_movies» STRING)
CREATE TABLE RATINGS («movie_id» STRING, «avg_rating» FLOAT, «total_votes» INT, «median_rating» FLOAT)

theorem eq_0_1 : ∀ t,
    (sql%([GENRE_schema, MOVIES_schema, DIRECTOR_MAPPING_schema, NAMES_schema, RATINGS_schema]) "WITH top_genres AS (SELECT g.\"genre\", COUNT(DISTINCT g.\"movie_id\") AS movie_count FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" AS g JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" AS r ON g.\"movie_id\" = r.\"movie_id\" WHERE r.\"avg_rating\" > 8 GROUP BY g.\"genre\" ORDER BY movie_count DESC LIMIT 3), director_movies AS (SELECT n.\"name\" AS DIRECTOR, COUNT(DISTINCT dm.\"movie_id\") AS MOVIE_COUNT FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"DIRECTOR_MAPPING\" AS dm JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"NAMES\" AS n ON dm.\"name_id\" = n.\"id\" JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" AS g ON dm.\"movie_id\" = g.\"movie_id\" JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" AS r ON dm.\"movie_id\" = r.\"movie_id\" WHERE r.\"avg_rating\" > 8 AND g.\"genre\" IN (SELECT \"genre\" FROM top_genres) GROUP BY n.\"name\" ORDER BY MOVIE_COUNT DESC, DIRECTOR ASC LIMIT 4) SELECT DIRECTOR, MOVIE_COUNT FROM director_movies ORDER BY DIRECTOR ASC") t ~= (sql%([GENRE_schema, MOVIES_schema, DIRECTOR_MAPPING_schema, NAMES_schema, RATINGS_schema]) "WITH top_genres AS (SELECT g.\"genre\", COUNT(DISTINCT g.\"movie_id\") AS cnt FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" AS g JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" AS r ON g.\"movie_id\" = r.\"movie_id\" WHERE r.\"avg_rating\" > 8 GROUP BY g.\"genre\" ORDER BY cnt DESC LIMIT 3), qualified_movies AS (SELECT DISTINCT g.\"movie_id\" FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" AS g JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" AS r ON g.\"movie_id\" = r.\"movie_id\" JOIN top_genres AS tg ON g.\"genre\" = tg.\"genre\" WHERE r.\"avg_rating\" > 8) SELECT n.\"name\" AS DIRECTOR, COUNT(DISTINCT dm.\"movie_id\") AS MOVIE_COUNT FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"DIRECTOR_MAPPING\" AS dm JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"NAMES\" AS n ON dm.\"name_id\" = n.\"id\" JOIN qualified_movies AS qm ON dm.\"movie_id\" = qm.\"movie_id\" GROUP BY n.\"name\" ORDER BY MOVIE_COUNT DESC, DIRECTOR ASC LIMIT 4") t := by
  intro t; first | sql_equiv | sorry

theorem eq_0_2 : ∀ t,
    (sql%([GENRE_schema, MOVIES_schema, DIRECTOR_MAPPING_schema, NAMES_schema, RATINGS_schema]) "WITH top_genres AS (SELECT g.\"genre\", COUNT(DISTINCT g.\"movie_id\") AS movie_count FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" AS g JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" AS r ON g.\"movie_id\" = r.\"movie_id\" WHERE r.\"avg_rating\" > 8 GROUP BY g.\"genre\" ORDER BY movie_count DESC LIMIT 3), director_movies AS (SELECT n.\"name\" AS DIRECTOR, COUNT(DISTINCT dm.\"movie_id\") AS MOVIE_COUNT FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"DIRECTOR_MAPPING\" AS dm JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"NAMES\" AS n ON dm.\"name_id\" = n.\"id\" JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" AS g ON dm.\"movie_id\" = g.\"movie_id\" JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" AS r ON dm.\"movie_id\" = r.\"movie_id\" WHERE r.\"avg_rating\" > 8 AND g.\"genre\" IN (SELECT \"genre\" FROM top_genres) GROUP BY n.\"name\" ORDER BY MOVIE_COUNT DESC, DIRECTOR ASC LIMIT 4) SELECT DIRECTOR, MOVIE_COUNT FROM director_movies ORDER BY DIRECTOR ASC") t ~= (sql%([GENRE_schema, MOVIES_schema, DIRECTOR_MAPPING_schema, NAMES_schema, RATINGS_schema]) "/* Step 1: Find the top 3 genres with the most movies rated above 8 */ /* Step 2: Among movies in those genres rated above 8, find top 4 directors by movie count */ WITH top_genres AS (SELECT g.\"genre\" FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" AS g JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" AS r ON g.\"movie_id\" = r.\"movie_id\" WHERE r.\"avg_rating\" > 8 GROUP BY g.\"genre\" ORDER BY COUNT(DISTINCT g.\"movie_id\") DESC LIMIT 3) SELECT n.\"name\" AS \"DIRECTOR\", COUNT(DISTINCT g.\"movie_id\") AS \"MOVIE_COUNT\" FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" AS g JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" AS r ON g.\"movie_id\" = r.\"movie_id\" JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"DIRECTOR_MAPPING\" AS dm ON g.\"movie_id\" = dm.\"movie_id\" JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"NAMES\" AS n ON dm.\"name_id\" = n.\"id\" WHERE r.\"avg_rating\" > 8 AND g.\"genre\" IN (SELECT \"genre\" FROM top_genres) GROUP BY n.\"name\" ORDER BY \"MOVIE_COUNT\" DESC, n.\"name\" ASC LIMIT 4") t := by
  intro t; first | sql_equiv | sorry

theorem eq_0_3 : ∀ t,
    (sql%([GENRE_schema, MOVIES_schema, DIRECTOR_MAPPING_schema, NAMES_schema, RATINGS_schema]) "WITH top_genres AS (SELECT g.\"genre\", COUNT(DISTINCT g.\"movie_id\") AS movie_count FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" AS g JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" AS r ON g.\"movie_id\" = r.\"movie_id\" WHERE r.\"avg_rating\" > 8 GROUP BY g.\"genre\" ORDER BY movie_count DESC LIMIT 3), director_movies AS (SELECT n.\"name\" AS DIRECTOR, COUNT(DISTINCT dm.\"movie_id\") AS MOVIE_COUNT FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"DIRECTOR_MAPPING\" AS dm JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"NAMES\" AS n ON dm.\"name_id\" = n.\"id\" JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" AS g ON dm.\"movie_id\" = g.\"movie_id\" JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" AS r ON dm.\"movie_id\" = r.\"movie_id\" WHERE r.\"avg_rating\" > 8 AND g.\"genre\" IN (SELECT \"genre\" FROM top_genres) GROUP BY n.\"name\" ORDER BY MOVIE_COUNT DESC, DIRECTOR ASC LIMIT 4) SELECT DIRECTOR, MOVIE_COUNT FROM director_movies ORDER BY DIRECTOR ASC") t ~= (sql%([GENRE_schema, MOVIES_schema, DIRECTOR_MAPPING_schema, NAMES_schema, RATINGS_schema]) "WITH top_genres AS (SELECT g.\"genre\" FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" AS g JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" AS r ON g.\"movie_id\" = r.\"movie_id\" WHERE r.\"avg_rating\" > 8 GROUP BY g.\"genre\" ORDER BY COUNT(*) DESC LIMIT 3), movies_in_top_genres AS (SELECT DISTINCT g.\"movie_id\" FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" AS g JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" AS r ON g.\"movie_id\" = r.\"movie_id\" WHERE r.\"avg_rating\" > 8 AND g.\"genre\" IN (SELECT \"genre\" FROM top_genres)) SELECT n.\"name\" AS DIRECTOR, COUNT(DISTINCT dm.\"movie_id\") AS MOVIE_COUNT FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"DIRECTOR_MAPPING\" AS dm JOIN movies_in_top_genres AS m ON dm.\"movie_id\" = m.\"movie_id\" JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"NAMES\" AS n ON dm.\"name_id\" = n.\"id\" GROUP BY n.\"name\" ORDER BY MOVIE_COUNT DESC, n.\"name\" ASC LIMIT 4") t := by
  intro t; first | sql_equiv | sorry

theorem eq_1_2 : ∀ t,
    (sql%([GENRE_schema, MOVIES_schema, DIRECTOR_MAPPING_schema, NAMES_schema, RATINGS_schema]) "WITH top_genres AS (SELECT g.\"genre\", COUNT(DISTINCT g.\"movie_id\") AS cnt FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" AS g JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" AS r ON g.\"movie_id\" = r.\"movie_id\" WHERE r.\"avg_rating\" > 8 GROUP BY g.\"genre\" ORDER BY cnt DESC LIMIT 3), qualified_movies AS (SELECT DISTINCT g.\"movie_id\" FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" AS g JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" AS r ON g.\"movie_id\" = r.\"movie_id\" JOIN top_genres AS tg ON g.\"genre\" = tg.\"genre\" WHERE r.\"avg_rating\" > 8) SELECT n.\"name\" AS DIRECTOR, COUNT(DISTINCT dm.\"movie_id\") AS MOVIE_COUNT FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"DIRECTOR_MAPPING\" AS dm JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"NAMES\" AS n ON dm.\"name_id\" = n.\"id\" JOIN qualified_movies AS qm ON dm.\"movie_id\" = qm.\"movie_id\" GROUP BY n.\"name\" ORDER BY MOVIE_COUNT DESC, DIRECTOR ASC LIMIT 4") t ~= (sql%([GENRE_schema, MOVIES_schema, DIRECTOR_MAPPING_schema, NAMES_schema, RATINGS_schema]) "/* Step 1: Find the top 3 genres with the most movies rated above 8 */ /* Step 2: Among movies in those genres rated above 8, find top 4 directors by movie count */ WITH top_genres AS (SELECT g.\"genre\" FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" AS g JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" AS r ON g.\"movie_id\" = r.\"movie_id\" WHERE r.\"avg_rating\" > 8 GROUP BY g.\"genre\" ORDER BY COUNT(DISTINCT g.\"movie_id\") DESC LIMIT 3) SELECT n.\"name\" AS \"DIRECTOR\", COUNT(DISTINCT g.\"movie_id\") AS \"MOVIE_COUNT\" FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" AS g JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" AS r ON g.\"movie_id\" = r.\"movie_id\" JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"DIRECTOR_MAPPING\" AS dm ON g.\"movie_id\" = dm.\"movie_id\" JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"NAMES\" AS n ON dm.\"name_id\" = n.\"id\" WHERE r.\"avg_rating\" > 8 AND g.\"genre\" IN (SELECT \"genre\" FROM top_genres) GROUP BY n.\"name\" ORDER BY \"MOVIE_COUNT\" DESC, n.\"name\" ASC LIMIT 4") t := by
  intro t; first | sql_equiv | sorry

theorem eq_1_3 : ∀ t,
    (sql%([GENRE_schema, MOVIES_schema, DIRECTOR_MAPPING_schema, NAMES_schema, RATINGS_schema]) "WITH top_genres AS (SELECT g.\"genre\", COUNT(DISTINCT g.\"movie_id\") AS cnt FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" AS g JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" AS r ON g.\"movie_id\" = r.\"movie_id\" WHERE r.\"avg_rating\" > 8 GROUP BY g.\"genre\" ORDER BY cnt DESC LIMIT 3), qualified_movies AS (SELECT DISTINCT g.\"movie_id\" FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" AS g JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" AS r ON g.\"movie_id\" = r.\"movie_id\" JOIN top_genres AS tg ON g.\"genre\" = tg.\"genre\" WHERE r.\"avg_rating\" > 8) SELECT n.\"name\" AS DIRECTOR, COUNT(DISTINCT dm.\"movie_id\") AS MOVIE_COUNT FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"DIRECTOR_MAPPING\" AS dm JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"NAMES\" AS n ON dm.\"name_id\" = n.\"id\" JOIN qualified_movies AS qm ON dm.\"movie_id\" = qm.\"movie_id\" GROUP BY n.\"name\" ORDER BY MOVIE_COUNT DESC, DIRECTOR ASC LIMIT 4") t ~= (sql%([GENRE_schema, MOVIES_schema, DIRECTOR_MAPPING_schema, NAMES_schema, RATINGS_schema]) "WITH top_genres AS (SELECT g.\"genre\" FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" AS g JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" AS r ON g.\"movie_id\" = r.\"movie_id\" WHERE r.\"avg_rating\" > 8 GROUP BY g.\"genre\" ORDER BY COUNT(*) DESC LIMIT 3), movies_in_top_genres AS (SELECT DISTINCT g.\"movie_id\" FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" AS g JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" AS r ON g.\"movie_id\" = r.\"movie_id\" WHERE r.\"avg_rating\" > 8 AND g.\"genre\" IN (SELECT \"genre\" FROM top_genres)) SELECT n.\"name\" AS DIRECTOR, COUNT(DISTINCT dm.\"movie_id\") AS MOVIE_COUNT FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"DIRECTOR_MAPPING\" AS dm JOIN movies_in_top_genres AS m ON dm.\"movie_id\" = m.\"movie_id\" JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"NAMES\" AS n ON dm.\"name_id\" = n.\"id\" GROUP BY n.\"name\" ORDER BY MOVIE_COUNT DESC, n.\"name\" ASC LIMIT 4") t := by
  intro t; first | sql_equiv | sorry

theorem eq_2_3 :
    sql%([GENRE_schema, MOVIES_schema, DIRECTOR_MAPPING_schema, NAMES_schema, RATINGS_schema]) "/* Step 1: Find the top 3 genres with the most movies rated above 8 */ /* Step 2: Among movies in those genres rated above 8, find top 4 directors by movie count */ WITH top_genres AS (SELECT g.\"genre\" FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" AS g JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" AS r ON g.\"movie_id\" = r.\"movie_id\" WHERE r.\"avg_rating\" > 8 GROUP BY g.\"genre\" ORDER BY COUNT(DISTINCT g.\"movie_id\") DESC LIMIT 3) SELECT n.\"name\" AS \"DIRECTOR\", COUNT(DISTINCT g.\"movie_id\") AS \"MOVIE_COUNT\" FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" AS g JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" AS r ON g.\"movie_id\" = r.\"movie_id\" JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"DIRECTOR_MAPPING\" AS dm ON g.\"movie_id\" = dm.\"movie_id\" JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"NAMES\" AS n ON dm.\"name_id\" = n.\"id\" WHERE r.\"avg_rating\" > 8 AND g.\"genre\" IN (SELECT \"genre\" FROM top_genres) GROUP BY n.\"name\" ORDER BY \"MOVIE_COUNT\" DESC, n.\"name\" ASC LIMIT 4" = sql%([GENRE_schema, MOVIES_schema, DIRECTOR_MAPPING_schema, NAMES_schema, RATINGS_schema]) "WITH top_genres AS (SELECT g.\"genre\" FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" AS g JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" AS r ON g.\"movie_id\" = r.\"movie_id\" WHERE r.\"avg_rating\" > 8 GROUP BY g.\"genre\" ORDER BY COUNT(*) DESC LIMIT 3), movies_in_top_genres AS (SELECT DISTINCT g.\"movie_id\" FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"GENRE\" AS g JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"RATINGS\" AS r ON g.\"movie_id\" = r.\"movie_id\" WHERE r.\"avg_rating\" > 8 AND g.\"genre\" IN (SELECT \"genre\" FROM top_genres)) SELECT n.\"name\" AS DIRECTOR, COUNT(DISTINCT dm.\"movie_id\") AS MOVIE_COUNT FROM \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"DIRECTOR_MAPPING\" AS dm JOIN movies_in_top_genres AS m ON dm.\"movie_id\" = m.\"movie_id\" JOIN \"IMDB_MOVIES\".\"IMDB_MOVIES\".\"NAMES\" AS n ON dm.\"name_id\" = n.\"id\" GROUP BY n.\"name\" ORDER BY MOVIE_COUNT DESC, n.\"name\" ASC LIMIT 4" := by
  first | sql_equiv | sorry

end Bench_sf_local230
