import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_local286_eq_0_1

CREATE TABLE ORDER_ITEMS («index» INT, «order_id» STRING, «order_item_id» INT, «product_id» STRING, «seller_id» STRING, «shipping_limit_date» STRING, «price» FLOAT, «freight_value» FLOAT)
CREATE TABLE PRODUCT_CATEGORY_NAME_TRANSLATION («index» INT, «product_category_name» STRING, «product_category_name_english» STRING)
CREATE TABLE ORDERS («index» INT, «order_id» STRING, «customer_id» STRING, «order_status» STRING, «order_purchase_timestamp» STRING, «order_approved_at» STRING, «order_delivered_carrier_date» STRING, «order_delivered_customer_date» STRING, «order_estimated_delivery_date» STRING)
CREATE TABLE ORDER_REVIEWS («index» INT, «review_id» STRING, «order_id» STRING, «review_score» INT, «review_comment_title» STRING, «review_comment_message» STRING, «review_creation_date» STRING, «review_answer_timestamp» STRING)
CREATE TABLE PRODUCTS («index» INT, «product_id» STRING, «product_category_name» STRING, «product_name_lenght» FLOAT, «product_description_lenght» FLOAT, «product_photos_qty» FLOAT, «product_weight_g» FLOAT, «product_length_cm» FLOAT, «product_height_cm» FLOAT, «product_width_cm» FLOAT)

theorem eq (t0 : TableRel ORDER_ITEMS_schema) (t1 : TableRel PRODUCT_CATEGORY_NAME_TRANSLATION_schema) (t2 : TableRel ORDERS_schema) (t3 : TableRel ORDER_REVIEWS_schema) (t4 : TableRel PRODUCTS_schema) :
    (sql%([ORDER_ITEMS_schema, PRODUCT_CATEGORY_NAME_TRANSLATION_schema, ORDERS_schema, ORDER_REVIEWS_schema, PRODUCTS_schema]) "WITH seller_items AS (SELECT oi.\"seller_id\", COUNT(*) AS \"TOTAL_QUANTITY_SOLD\", SUM(oi.\"price\") AS \"TOTAL_SALES\", AVG(oi.\"price\") AS \"AVERAGE_ITEM_PRICE\" FROM \"ELECTRONIC_SALES\".\"ELECTRONIC_SALES\".\"ORDER_ITEMS\" AS oi GROUP BY oi.\"seller_id\" HAVING COUNT(*) > 100), seller_reviews AS (SELECT oi.\"seller_id\", AVG(CAST(r.\"review_score\" AS DECIMAL(18, 12))) AS \"AVERAGE_REVIEW_SCORE\" FROM \"ELECTRONIC_SALES\".\"ELECTRONIC_SALES\".\"ORDER_ITEMS\" AS oi JOIN \"ELECTRONIC_SALES\".\"ELECTRONIC_SALES\".\"ORDER_REVIEWS\" AS r ON oi.\"order_id\" = r.\"order_id\" GROUP BY oi.\"seller_id\"), seller_packing AS (SELECT oi.\"seller_id\", AVG(CAST(EXTRACT(epoch FROM CAST(TO_TIMESTAMP(o.\"order_delivered_carrier_date\") AS TIMESTAMP) - CAST(TO_TIMESTAMP(o.\"order_approved_at\") AS TIMESTAMP)) / 3600 AS BIGINT)) AS \"AVERAGE_PACKING_TIME_HOURS\" FROM \"ELECTRONIC_SALES\".\"ELECTRONIC_SALES\".\"ORDER_ITEMS\" AS oi JOIN \"ELECTRONIC_SALES\".\"ELECTRONIC_SALES\".\"ORDERS\" AS o ON oi.\"order_id\" = o.\"order_id\" WHERE o.\"order_approved_at\" <> '' AND o.\"order_delivered_carrier_date\" <> '' GROUP BY oi.\"seller_id\"), seller_category AS (SELECT oi.\"seller_id\", COALESCE(t.\"product_category_name_english\", '') AS category_english, COUNT(*) AS cnt, ROW_NUMBER() OVER (PARTITION BY oi.\"seller_id\" ORDER BY COUNT(*) DESC) AS rn FROM \"ELECTRONIC_SALES\".\"ELECTRONIC_SALES\".\"ORDER_ITEMS\" AS oi LEFT JOIN \"ELECTRONIC_SALES\".\"ELECTRONIC_SALES\".\"PRODUCTS\" AS p ON oi.\"product_id\" = p.\"product_id\" LEFT JOIN \"ELECTRONIC_SALES\".\"ELECTRONIC_SALES\".\"PRODUCT_CATEGORY_NAME_TRANSLATION\" AS t ON p.\"product_category_name\" = t.\"product_category_name\" GROUP BY oi.\"seller_id\", COALESCE(t.\"product_category_name_english\", '')) SELECT si.\"seller_id\" AS \"SELLER_ID\", si.\"TOTAL_QUANTITY_SOLD\", si.\"TOTAL_SALES\", si.\"AVERAGE_ITEM_PRICE\", sr.\"AVERAGE_REVIEW_SCORE\", sp.\"AVERAGE_PACKING_TIME_HOURS\", sc.category_english AS \"TOP_CATEGORIES_ENGLISH\" FROM seller_items AS si LEFT JOIN seller_reviews AS sr ON si.\"seller_id\" = sr.\"seller_id\" LEFT JOIN seller_packing AS sp ON si.\"seller_id\" = sp.\"seller_id\" LEFT JOIN seller_category AS sc ON si.\"seller_id\" = sc.\"seller_id\" AND sc.rn = 1 ORDER BY si.\"TOTAL_SALES\" DESC") t0 t1 t2 t3 t4
  ~= (sql%([ORDER_ITEMS_schema, PRODUCT_CATEGORY_NAME_TRANSLATION_schema, ORDERS_schema, ORDER_REVIEWS_schema, PRODUCTS_schema]) "WITH avg_reviews_per_order AS (SELECT \"order_id\", AVG(\"review_score\") AS avg_score FROM \"ELECTRONIC_SALES\".\"ELECTRONIC_SALES\".\"ORDER_REVIEWS\" GROUP BY \"order_id\"), seller_sales AS (SELECT oi.\"seller_id\", COUNT(*) AS \"TOTAL_QUANTITY_SOLD\", SUM(oi.\"price\") AS \"TOTAL_SALES\", AVG(oi.\"price\") AS \"AVERAGE_ITEM_PRICE\" FROM \"ELECTRONIC_SALES\".\"ELECTRONIC_SALES\".\"ORDER_ITEMS\" AS oi GROUP BY oi.\"seller_id\" HAVING COUNT(*) > 100), seller_reviews AS (SELECT oi.\"seller_id\", CAST(SUM(r.avg_score) AS DOUBLE PRECISION) / CAST(COUNT(*) AS DOUBLE PRECISION) AS \"AVERAGE_REVIEW_SCORE\" FROM \"ELECTRONIC_SALES\".\"ELECTRONIC_SALES\".\"ORDER_ITEMS\" AS oi JOIN avg_reviews_per_order AS r ON oi.\"order_id\" = r.\"order_id\" GROUP BY oi.\"seller_id\"), seller_packing AS (SELECT oi.\"seller_id\", AVG(CAST(EXTRACT(epoch FROM CAST(TO_TIMESTAMP(o.\"order_delivered_carrier_date\") AS TIMESTAMP) - CAST(TO_TIMESTAMP(o.\"order_approved_at\") AS TIMESTAMP)) / 3600 AS BIGINT)) AS \"AVERAGE_PACKING_TIME_HOURS\" FROM \"ELECTRONIC_SALES\".\"ELECTRONIC_SALES\".\"ORDER_ITEMS\" AS oi JOIN \"ELECTRONIC_SALES\".\"ELECTRONIC_SALES\".\"ORDERS\" AS o ON oi.\"order_id\" = o.\"order_id\" WHERE NOT o.\"order_approved_at\" IS NULL AND o.\"order_approved_at\" <> '' AND NOT o.\"order_delivered_carrier_date\" IS NULL AND o.\"order_delivered_carrier_date\" <> '' GROUP BY oi.\"seller_id\"), seller_categories AS (SELECT oi.\"seller_id\", t.\"product_category_name_english\", COUNT(*) AS category_count, ROW_NUMBER() OVER (PARTITION BY oi.\"seller_id\" ORDER BY COUNT(*) DESC) AS rn FROM \"ELECTRONIC_SALES\".\"ELECTRONIC_SALES\".\"ORDER_ITEMS\" AS oi JOIN \"ELECTRONIC_SALES\".\"ELECTRONIC_SALES\".\"PRODUCTS\" AS p ON oi.\"product_id\" = p.\"product_id\" LEFT JOIN \"ELECTRONIC_SALES\".\"ELECTRONIC_SALES\".\"PRODUCT_CATEGORY_NAME_TRANSLATION\" AS t ON p.\"product_category_name\" = t.\"product_category_name\" GROUP BY oi.\"seller_id\", t.\"product_category_name_english\") SELECT ss.\"seller_id\" AS \"SELLER_ID\", ss.\"TOTAL_QUANTITY_SOLD\", ss.\"TOTAL_SALES\", ss.\"AVERAGE_ITEM_PRICE\", sr.\"AVERAGE_REVIEW_SCORE\", sp.\"AVERAGE_PACKING_TIME_HOURS\", sc.\"product_category_name_english\" AS \"TOP_CATEGORIES_ENGLISH\" FROM seller_sales AS ss LEFT JOIN seller_reviews AS sr ON ss.\"seller_id\" = sr.\"seller_id\" LEFT JOIN seller_packing AS sp ON ss.\"seller_id\" = sp.\"seller_id\" LEFT JOIN seller_categories AS sc ON ss.\"seller_id\" = sc.\"seller_id\" AND sc.rn = 1 ORDER BY ss.\"TOTAL_SALES\" DESC") t0 t1 t2 t3 t4
  := by first | sql_equiv | sorry

end N_sf_local286_eq_0_1
