import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_local018 — crossskill equivalence(s)

Question: For the primary collision factor violation category that was the most common cause of traffic accidents in 2021, how many percentage points did its share of annual road incidents in 2021 decrease compared to its share in 2011?

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_local018

CREATE TABLE COLLISIONS («case_id» FLOAT, «jurisdiction» FLOAT, «officer_id» STRING, «reporting_district» STRING, «chp_shift» STRING, «population» STRING, «county_city_location» INT, «county_location» STRING, «special_condition» FLOAT, «beat_type» STRING, «chp_beat_type» STRING, «city_division_lapd» STRING, «chp_beat_class» STRING, «beat_number» STRING, «primary_road» STRING, «secondary_road» STRING, «distance» FLOAT, «direction» STRING, «intersection» FLOAT, «weather_1» STRING, «weather_2» STRING, «state_highway_indicator» FLOAT, «caltrans_county» STRING, «caltrans_district» FLOAT, «state_route» FLOAT, «route_suffix» STRING, «postmile_prefix» STRING, «postmile» FLOAT, «location_type» STRING, «ramp_intersection» STRING, «side_of_highway» STRING, «tow_away» FLOAT, «collision_severity» STRING, «killed_victims» FLOAT, «injured_victims» FLOAT, «party_count» FLOAT, «primary_collision_factor» STRING, «pcf_violation_code» STRING, «pcf_violation_category» STRING, «pcf_violation» FLOAT, «pcf_violation_subsection» STRING, «hit_and_run» STRING, «type_of_collision» STRING, «motor_vehicle_involved_with» STRING, «pedestrian_action» STRING, «road_surface» STRING, «road_condition_1» STRING, «road_condition_2» STRING, «lighting» STRING, «control_device» STRING, «chp_road_type» STRING, «pedestrian_collision» INT, «bicycle_collision» INT, «motorcycle_collision» INT, «truck_collision» INT, «not_private_property» FLOAT, «alcohol_involved» FLOAT, «statewide_vehicle_type_at_fault» STRING, «chp_vehicle_type_at_fault» STRING, «severe_injury_count» INT, «other_visible_injury_count» INT, «complaint_of_pain_injury_count» INT, «pedestrian_killed_count» INT, «pedestrian_injured_count» INT, «bicyclist_killed_count» INT, «bicyclist_injured_count» INT, «motorcyclist_killed_count» INT, «motorcyclist_injured_count» FLOAT, «primary_ramp» STRING, «secondary_ramp» STRING, «latitude» FLOAT, «longitude» FLOAT, «collision_date» STRING, «collision_time» STRING, «process_date» STRING)

HYPOTHESIS hyp0_1_0 : COLLISIONS "LEFT(\"collision_date\", 4) = '2021'"
HYPOTHESIS hyp0_1_1 : COLLISIONS "LEFT(\"collision_date\", 4) IN ('2011', '2021')"
theorem eq_0_1 (t : TableRel COLLISIONS_schema) (h0 : hyp0_1_0 t) (h1 : hyp0_1_1 t) :
    (sql%([COLLISIONS_schema]) "WITH most_common_2021 AS (SELECT \"pcf_violation_category\" FROM \"CALIFORNIA_TRAFFIC_COLLISION\".\"CALIFORNIA_TRAFFIC_COLLISION\".\"COLLISIONS\" WHERE LEFT(\"collision_date\", 4) = '2021' GROUP BY \"pcf_violation_category\" ORDER BY COUNT(*) DESC LIMIT 1), yearly_shares AS (SELECT CAST(LEFT(\"collision_date\", 4) AS INT) AS COLLISION_YEAR, CAST(COUNT(CASE WHEN \"pcf_violation_category\" = (SELECT \"pcf_violation_category\" FROM most_common_2021) THEN 1 END) * 100.0 AS DOUBLE PRECISION) / COUNT(*) AS PERCENTAGE_SHARE FROM \"CALIFORNIA_TRAFFIC_COLLISION\".\"CALIFORNIA_TRAFFIC_COLLISION\".\"COLLISIONS\" WHERE LEFT(\"collision_date\", 4) IN ('2011', '2021') GROUP BY LEFT(\"collision_date\", 4)) SELECT MAX(CASE WHEN COLLISION_YEAR = 2011 THEN PERCENTAGE_SHARE END) - MAX(CASE WHEN COLLISION_YEAR = 2021 THEN PERCENTAGE_SHARE END) FROM yearly_shares") t ~= (sql%([COLLISIONS_schema]) "WITH yearly_counts AS (SELECT LEFT(\"collision_date\", 4) AS COLLISION_YEAR, \"pcf_violation_category\", COUNT(*) AS category_count FROM \"CALIFORNIA_TRAFFIC_COLLISION\".\"CALIFORNIA_TRAFFIC_COLLISION\".\"COLLISIONS\" WHERE LEFT(\"collision_date\", 4) IN ('2011', '2021') GROUP BY LEFT(\"collision_date\", 4), \"pcf_violation_category\"), yearly_totals AS (SELECT COLLISION_YEAR, SUM(category_count) AS total_count FROM yearly_counts GROUP BY COLLISION_YEAR), percentage_shares AS (SELECT CAST(yc.COLLISION_YEAR AS INT) AS COLLISION_YEAR, yc.\"pcf_violation_category\", CAST(100.0 * yc.category_count AS DOUBLE PRECISION) / yt.total_count AS PERCENTAGE_SHARE FROM yearly_counts AS yc JOIN yearly_totals AS yt ON yc.COLLISION_YEAR = yt.COLLISION_YEAR), most_common_2021 AS (SELECT \"pcf_violation_category\" FROM percentage_shares WHERE COLLISION_YEAR = 2021 ORDER BY PERCENTAGE_SHARE DESC LIMIT 1) SELECT MAX(CASE WHEN COLLISION_YEAR = 2011 THEN PERCENTAGE_SHARE END) - MAX(CASE WHEN COLLISION_YEAR = 2021 THEN PERCENTAGE_SHARE END) FROM percentage_shares AS ps JOIN most_common_2021 AS mc ON ps.\"pcf_violation_category\" = mc.\"pcf_violation_category\" WHERE ps.COLLISION_YEAR IN (2011, 2021)") t := by
  first | sql_equiv | sorry

theorem eq_0_2 :
    sql%([COLLISIONS_schema]) "WITH most_common_2021 AS (SELECT \"pcf_violation_category\" FROM \"CALIFORNIA_TRAFFIC_COLLISION\".\"CALIFORNIA_TRAFFIC_COLLISION\".\"COLLISIONS\" WHERE LEFT(\"collision_date\", 4) = '2021' GROUP BY \"pcf_violation_category\" ORDER BY COUNT(*) DESC LIMIT 1), yearly_shares AS (SELECT CAST(LEFT(\"collision_date\", 4) AS INT) AS COLLISION_YEAR, CAST(COUNT(CASE WHEN \"pcf_violation_category\" = (SELECT \"pcf_violation_category\" FROM most_common_2021) THEN 1 END) * 100.0 AS DOUBLE PRECISION) / COUNT(*) AS PERCENTAGE_SHARE FROM \"CALIFORNIA_TRAFFIC_COLLISION\".\"CALIFORNIA_TRAFFIC_COLLISION\".\"COLLISIONS\" WHERE LEFT(\"collision_date\", 4) IN ('2011', '2021') GROUP BY LEFT(\"collision_date\", 4)) SELECT MAX(CASE WHEN COLLISION_YEAR = 2011 THEN PERCENTAGE_SHARE END) - MAX(CASE WHEN COLLISION_YEAR = 2021 THEN PERCENTAGE_SHARE END) FROM yearly_shares" = sql%([COLLISIONS_schema]) "WITH top_category AS (SELECT \"pcf_violation_category\" FROM \"CALIFORNIA_TRAFFIC_COLLISION\".\"CALIFORNIA_TRAFFIC_COLLISION\".\"COLLISIONS\" WHERE LEFT(\"collision_date\", 4) = '2021' GROUP BY \"pcf_violation_category\" ORDER BY COUNT(*) DESC LIMIT 1), yearly_counts AS (SELECT CAST(LEFT(c.\"collision_date\", 4) AS INT) AS COLLISION_YEAR, COUNT(*) AS category_count FROM \"CALIFORNIA_TRAFFIC_COLLISION\".\"CALIFORNIA_TRAFFIC_COLLISION\".\"COLLISIONS\" AS c JOIN top_category AS t ON c.\"pcf_violation_category\" = t.\"pcf_violation_category\" WHERE LEFT(c.\"collision_date\", 4) IN ('2011', '2021') GROUP BY LEFT(c.\"collision_date\", 4)), yearly_totals AS (SELECT CAST(LEFT(\"collision_date\", 4) AS INT) AS COLLISION_YEAR, COUNT(*) AS total_count FROM \"CALIFORNIA_TRAFFIC_COLLISION\".\"CALIFORNIA_TRAFFIC_COLLISION\".\"COLLISIONS\" WHERE LEFT(\"collision_date\", 4) IN ('2011', '2021') GROUP BY LEFT(\"collision_date\", 4)), shares AS (SELECT yc.COLLISION_YEAR, ROUND(CAST(yc.category_count * 100.0 AS DOUBLE PRECISION) / yt.total_count, 2) AS PERCENTAGE_SHARE FROM yearly_counts AS yc JOIN yearly_totals AS yt ON yc.COLLISION_YEAR = yt.COLLISION_YEAR) SELECT MAX(CASE WHEN COLLISION_YEAR = 2011 THEN PERCENTAGE_SHARE END) - MAX(CASE WHEN COLLISION_YEAR = 2021 THEN PERCENTAGE_SHARE END) FROM shares" := by
  first | sql_equiv | sorry

theorem eq_0_3 :
    sql%([COLLISIONS_schema]) "WITH most_common_2021 AS (SELECT \"pcf_violation_category\" FROM \"CALIFORNIA_TRAFFIC_COLLISION\".\"CALIFORNIA_TRAFFIC_COLLISION\".\"COLLISIONS\" WHERE LEFT(\"collision_date\", 4) = '2021' GROUP BY \"pcf_violation_category\" ORDER BY COUNT(*) DESC LIMIT 1), yearly_shares AS (SELECT CAST(LEFT(\"collision_date\", 4) AS INT) AS COLLISION_YEAR, CAST(COUNT(CASE WHEN \"pcf_violation_category\" = (SELECT \"pcf_violation_category\" FROM most_common_2021) THEN 1 END) * 100.0 AS DOUBLE PRECISION) / COUNT(*) AS PERCENTAGE_SHARE FROM \"CALIFORNIA_TRAFFIC_COLLISION\".\"CALIFORNIA_TRAFFIC_COLLISION\".\"COLLISIONS\" WHERE LEFT(\"collision_date\", 4) IN ('2011', '2021') GROUP BY LEFT(\"collision_date\", 4)) SELECT MAX(CASE WHEN COLLISION_YEAR = 2011 THEN PERCENTAGE_SHARE END) - MAX(CASE WHEN COLLISION_YEAR = 2021 THEN PERCENTAGE_SHARE END) FROM yearly_shares" = sql%([COLLISIONS_schema]) "WITH top_category AS (SELECT \"pcf_violation_category\" FROM \"CALIFORNIA_TRAFFIC_COLLISION\".\"CALIFORNIA_TRAFFIC_COLLISION\".\"COLLISIONS\" WHERE LEFT(\"collision_date\", 4) = '2021' GROUP BY \"pcf_violation_category\" ORDER BY COUNT(*) DESC LIMIT 1), share_2011 AS (SELECT CAST(100.0 * SUM(CASE WHEN c.\"pcf_violation_category\" = t.\"pcf_violation_category\" THEN 1 ELSE 0 END) AS DOUBLE PRECISION) / COUNT(*) AS pct FROM \"CALIFORNIA_TRAFFIC_COLLISION\".\"CALIFORNIA_TRAFFIC_COLLISION\".\"COLLISIONS\" AS c CROSS JOIN top_category AS t WHERE LEFT(c.\"collision_date\", 4) = '2011'), share_2021 AS (SELECT CAST(100.0 * SUM(CASE WHEN c.\"pcf_violation_category\" = t.\"pcf_violation_category\" THEN 1 ELSE 0 END) AS DOUBLE PRECISION) / COUNT(*) AS pct FROM \"CALIFORNIA_TRAFFIC_COLLISION\".\"CALIFORNIA_TRAFFIC_COLLISION\".\"COLLISIONS\" AS c CROSS JOIN top_category AS t WHERE LEFT(c.\"collision_date\", 4) = '2021') SELECT s11.pct - s21.pct FROM share_2011 AS s11, share_2021 AS s21" := by
  first | sql_equiv | sorry

HYPOTHESIS hyp1_2_0 : COLLISIONS "LEFT(\"collision_date\", 4) IN ('2011', '2021')"
HYPOTHESIS hyp1_2_1 : COLLISIONS "LEFT(\"collision_date\", 4) = '2021'"
theorem eq_1_2 (t : TableRel COLLISIONS_schema) (h0 : hyp1_2_0 t) (h1 : hyp1_2_1 t) :
    (sql%([COLLISIONS_schema]) "WITH yearly_counts AS (SELECT LEFT(\"collision_date\", 4) AS COLLISION_YEAR, \"pcf_violation_category\", COUNT(*) AS category_count FROM \"CALIFORNIA_TRAFFIC_COLLISION\".\"CALIFORNIA_TRAFFIC_COLLISION\".\"COLLISIONS\" WHERE LEFT(\"collision_date\", 4) IN ('2011', '2021') GROUP BY LEFT(\"collision_date\", 4), \"pcf_violation_category\"), yearly_totals AS (SELECT COLLISION_YEAR, SUM(category_count) AS total_count FROM yearly_counts GROUP BY COLLISION_YEAR), percentage_shares AS (SELECT CAST(yc.COLLISION_YEAR AS INT) AS COLLISION_YEAR, yc.\"pcf_violation_category\", CAST(100.0 * yc.category_count AS DOUBLE PRECISION) / yt.total_count AS PERCENTAGE_SHARE FROM yearly_counts AS yc JOIN yearly_totals AS yt ON yc.COLLISION_YEAR = yt.COLLISION_YEAR), most_common_2021 AS (SELECT \"pcf_violation_category\" FROM percentage_shares WHERE COLLISION_YEAR = 2021 ORDER BY PERCENTAGE_SHARE DESC LIMIT 1) SELECT MAX(CASE WHEN COLLISION_YEAR = 2011 THEN PERCENTAGE_SHARE END) - MAX(CASE WHEN COLLISION_YEAR = 2021 THEN PERCENTAGE_SHARE END) FROM percentage_shares AS ps JOIN most_common_2021 AS mc ON ps.\"pcf_violation_category\" = mc.\"pcf_violation_category\" WHERE ps.COLLISION_YEAR IN (2011, 2021)") t ~= (sql%([COLLISIONS_schema]) "WITH top_category AS (SELECT \"pcf_violation_category\" FROM \"CALIFORNIA_TRAFFIC_COLLISION\".\"CALIFORNIA_TRAFFIC_COLLISION\".\"COLLISIONS\" WHERE LEFT(\"collision_date\", 4) = '2021' GROUP BY \"pcf_violation_category\" ORDER BY COUNT(*) DESC LIMIT 1), yearly_counts AS (SELECT CAST(LEFT(c.\"collision_date\", 4) AS INT) AS COLLISION_YEAR, COUNT(*) AS category_count FROM \"CALIFORNIA_TRAFFIC_COLLISION\".\"CALIFORNIA_TRAFFIC_COLLISION\".\"COLLISIONS\" AS c JOIN top_category AS t ON c.\"pcf_violation_category\" = t.\"pcf_violation_category\" WHERE LEFT(c.\"collision_date\", 4) IN ('2011', '2021') GROUP BY LEFT(c.\"collision_date\", 4)), yearly_totals AS (SELECT CAST(LEFT(\"collision_date\", 4) AS INT) AS COLLISION_YEAR, COUNT(*) AS total_count FROM \"CALIFORNIA_TRAFFIC_COLLISION\".\"CALIFORNIA_TRAFFIC_COLLISION\".\"COLLISIONS\" WHERE LEFT(\"collision_date\", 4) IN ('2011', '2021') GROUP BY LEFT(\"collision_date\", 4)), shares AS (SELECT yc.COLLISION_YEAR, ROUND(CAST(yc.category_count * 100.0 AS DOUBLE PRECISION) / yt.total_count, 2) AS PERCENTAGE_SHARE FROM yearly_counts AS yc JOIN yearly_totals AS yt ON yc.COLLISION_YEAR = yt.COLLISION_YEAR) SELECT MAX(CASE WHEN COLLISION_YEAR = 2011 THEN PERCENTAGE_SHARE END) - MAX(CASE WHEN COLLISION_YEAR = 2021 THEN PERCENTAGE_SHARE END) FROM shares") t := by
  first | sql_equiv | sorry

HYPOTHESIS hyp1_3_0 : COLLISIONS "LEFT(\"collision_date\", 4) IN ('2011', '2021')"
HYPOTHESIS hyp1_3_1 : COLLISIONS "LEFT(\"collision_date\", 4) = '2021'"
theorem eq_1_3 (t : TableRel COLLISIONS_schema) (h0 : hyp1_3_0 t) (h1 : hyp1_3_1 t) :
    (sql%([COLLISIONS_schema]) "WITH yearly_counts AS (SELECT LEFT(\"collision_date\", 4) AS COLLISION_YEAR, \"pcf_violation_category\", COUNT(*) AS category_count FROM \"CALIFORNIA_TRAFFIC_COLLISION\".\"CALIFORNIA_TRAFFIC_COLLISION\".\"COLLISIONS\" WHERE LEFT(\"collision_date\", 4) IN ('2011', '2021') GROUP BY LEFT(\"collision_date\", 4), \"pcf_violation_category\"), yearly_totals AS (SELECT COLLISION_YEAR, SUM(category_count) AS total_count FROM yearly_counts GROUP BY COLLISION_YEAR), percentage_shares AS (SELECT CAST(yc.COLLISION_YEAR AS INT) AS COLLISION_YEAR, yc.\"pcf_violation_category\", CAST(100.0 * yc.category_count AS DOUBLE PRECISION) / yt.total_count AS PERCENTAGE_SHARE FROM yearly_counts AS yc JOIN yearly_totals AS yt ON yc.COLLISION_YEAR = yt.COLLISION_YEAR), most_common_2021 AS (SELECT \"pcf_violation_category\" FROM percentage_shares WHERE COLLISION_YEAR = 2021 ORDER BY PERCENTAGE_SHARE DESC LIMIT 1) SELECT MAX(CASE WHEN COLLISION_YEAR = 2011 THEN PERCENTAGE_SHARE END) - MAX(CASE WHEN COLLISION_YEAR = 2021 THEN PERCENTAGE_SHARE END) FROM percentage_shares AS ps JOIN most_common_2021 AS mc ON ps.\"pcf_violation_category\" = mc.\"pcf_violation_category\" WHERE ps.COLLISION_YEAR IN (2011, 2021)") t ~= (sql%([COLLISIONS_schema]) "WITH top_category AS (SELECT \"pcf_violation_category\" FROM \"CALIFORNIA_TRAFFIC_COLLISION\".\"CALIFORNIA_TRAFFIC_COLLISION\".\"COLLISIONS\" WHERE LEFT(\"collision_date\", 4) = '2021' GROUP BY \"pcf_violation_category\" ORDER BY COUNT(*) DESC LIMIT 1), share_2011 AS (SELECT CAST(100.0 * SUM(CASE WHEN c.\"pcf_violation_category\" = t.\"pcf_violation_category\" THEN 1 ELSE 0 END) AS DOUBLE PRECISION) / COUNT(*) AS pct FROM \"CALIFORNIA_TRAFFIC_COLLISION\".\"CALIFORNIA_TRAFFIC_COLLISION\".\"COLLISIONS\" AS c CROSS JOIN top_category AS t WHERE LEFT(c.\"collision_date\", 4) = '2011'), share_2021 AS (SELECT CAST(100.0 * SUM(CASE WHEN c.\"pcf_violation_category\" = t.\"pcf_violation_category\" THEN 1 ELSE 0 END) AS DOUBLE PRECISION) / COUNT(*) AS pct FROM \"CALIFORNIA_TRAFFIC_COLLISION\".\"CALIFORNIA_TRAFFIC_COLLISION\".\"COLLISIONS\" AS c CROSS JOIN top_category AS t WHERE LEFT(c.\"collision_date\", 4) = '2021') SELECT s11.pct - s21.pct FROM share_2011 AS s11, share_2021 AS s21") t := by
  first | sql_equiv | sorry

theorem eq_2_3 :
    sql%([COLLISIONS_schema]) "WITH top_category AS (SELECT \"pcf_violation_category\" FROM \"CALIFORNIA_TRAFFIC_COLLISION\".\"CALIFORNIA_TRAFFIC_COLLISION\".\"COLLISIONS\" WHERE LEFT(\"collision_date\", 4) = '2021' GROUP BY \"pcf_violation_category\" ORDER BY COUNT(*) DESC LIMIT 1), yearly_counts AS (SELECT CAST(LEFT(c.\"collision_date\", 4) AS INT) AS COLLISION_YEAR, COUNT(*) AS category_count FROM \"CALIFORNIA_TRAFFIC_COLLISION\".\"CALIFORNIA_TRAFFIC_COLLISION\".\"COLLISIONS\" AS c JOIN top_category AS t ON c.\"pcf_violation_category\" = t.\"pcf_violation_category\" WHERE LEFT(c.\"collision_date\", 4) IN ('2011', '2021') GROUP BY LEFT(c.\"collision_date\", 4)), yearly_totals AS (SELECT CAST(LEFT(\"collision_date\", 4) AS INT) AS COLLISION_YEAR, COUNT(*) AS total_count FROM \"CALIFORNIA_TRAFFIC_COLLISION\".\"CALIFORNIA_TRAFFIC_COLLISION\".\"COLLISIONS\" WHERE LEFT(\"collision_date\", 4) IN ('2011', '2021') GROUP BY LEFT(\"collision_date\", 4)), shares AS (SELECT yc.COLLISION_YEAR, ROUND(CAST(yc.category_count * 100.0 AS DOUBLE PRECISION) / yt.total_count, 2) AS PERCENTAGE_SHARE FROM yearly_counts AS yc JOIN yearly_totals AS yt ON yc.COLLISION_YEAR = yt.COLLISION_YEAR) SELECT MAX(CASE WHEN COLLISION_YEAR = 2011 THEN PERCENTAGE_SHARE END) - MAX(CASE WHEN COLLISION_YEAR = 2021 THEN PERCENTAGE_SHARE END) FROM shares" = sql%([COLLISIONS_schema]) "WITH top_category AS (SELECT \"pcf_violation_category\" FROM \"CALIFORNIA_TRAFFIC_COLLISION\".\"CALIFORNIA_TRAFFIC_COLLISION\".\"COLLISIONS\" WHERE LEFT(\"collision_date\", 4) = '2021' GROUP BY \"pcf_violation_category\" ORDER BY COUNT(*) DESC LIMIT 1), share_2011 AS (SELECT CAST(100.0 * SUM(CASE WHEN c.\"pcf_violation_category\" = t.\"pcf_violation_category\" THEN 1 ELSE 0 END) AS DOUBLE PRECISION) / COUNT(*) AS pct FROM \"CALIFORNIA_TRAFFIC_COLLISION\".\"CALIFORNIA_TRAFFIC_COLLISION\".\"COLLISIONS\" AS c CROSS JOIN top_category AS t WHERE LEFT(c.\"collision_date\", 4) = '2011'), share_2021 AS (SELECT CAST(100.0 * SUM(CASE WHEN c.\"pcf_violation_category\" = t.\"pcf_violation_category\" THEN 1 ELSE 0 END) AS DOUBLE PRECISION) / COUNT(*) AS pct FROM \"CALIFORNIA_TRAFFIC_COLLISION\".\"CALIFORNIA_TRAFFIC_COLLISION\".\"COLLISIONS\" AS c CROSS JOIN top_category AS t WHERE LEFT(c.\"collision_date\", 4) = '2021') SELECT s11.pct - s21.pct FROM share_2011 AS s11, share_2021 AS s21" := by
  first | sql_equiv | sorry

end Bench_sf_local018
