import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_local220_eq_0_2

CREATE TABLE PLAYER («id» INT, «player_api_id» INT, «player_name» STRING, «player_fifa_api_id» INT, «birthday» STRING, «height» FLOAT, «weight» INT)
CREATE TABLE MATCH («id» INT, «country_id» INT, «league_id» INT, «season» STRING, «stage» INT, «date» STRING, «match_api_id» INT, «home_team_api_id» INT, «away_team_api_id» INT, «home_team_goal» INT, «away_team_goal» INT, «home_player_X1» FLOAT, «home_player_X2» FLOAT, «home_player_X3» FLOAT, «home_player_X4» FLOAT, «home_player_X5» FLOAT, «home_player_X6» FLOAT, «home_player_X7» FLOAT, «home_player_X8» FLOAT, «home_player_X9» FLOAT, «home_player_X10» FLOAT, «home_player_X11» FLOAT, «away_player_X1» FLOAT, «away_player_X2» FLOAT, «away_player_X3» FLOAT, «away_player_X4» FLOAT, «away_player_X5» FLOAT, «away_player_X6» FLOAT, «away_player_X7» FLOAT, «away_player_X8» FLOAT, «away_player_X9» FLOAT, «away_player_X10» FLOAT, «away_player_X11» FLOAT, «home_player_Y1» FLOAT, «home_player_Y2» FLOAT, «home_player_Y3» FLOAT, «home_player_Y4» FLOAT, «home_player_Y5» FLOAT, «home_player_Y6» FLOAT, «home_player_Y7» FLOAT, «home_player_Y8» FLOAT, «home_player_Y9» FLOAT, «home_player_Y10» FLOAT, «home_player_Y11» FLOAT, «away_player_Y1» FLOAT, «away_player_Y2» FLOAT, «away_player_Y3» FLOAT, «away_player_Y4» FLOAT, «away_player_Y5» FLOAT, «away_player_Y6» FLOAT, «away_player_Y7» FLOAT, «away_player_Y8» FLOAT, «away_player_Y9» FLOAT, «away_player_Y10» FLOAT, «away_player_Y11» FLOAT, «home_player_1» FLOAT, «home_player_2» FLOAT, «home_player_3» FLOAT, «home_player_4» FLOAT, «home_player_5» FLOAT, «home_player_6» FLOAT, «home_player_7» FLOAT, «home_player_8» FLOAT, «home_player_9» FLOAT, «home_player_10» FLOAT, «home_player_11» FLOAT, «away_player_1» FLOAT, «away_player_2» FLOAT, «away_player_3» FLOAT, «away_player_4» FLOAT, «away_player_5» FLOAT, «away_player_6» FLOAT, «away_player_7» FLOAT, «away_player_8» FLOAT, «away_player_9» FLOAT, «away_player_10» FLOAT, «away_player_11» FLOAT, «goal» STRING, «shoton» STRING, «shotoff» STRING, «foulcommit» STRING, «card» STRING, «cross» STRING, «corner» STRING, «possession» STRING, «B365H» FLOAT, «B365D» FLOAT, «B365A» FLOAT, «BWH» FLOAT, «BWD» FLOAT, «BWA» FLOAT, «IWH» FLOAT, «IWD» FLOAT, «IWA» FLOAT, «LBH» FLOAT, «LBD» FLOAT, «LBA» FLOAT, «PSH» FLOAT, «PSD» FLOAT, «PSA» FLOAT, «WHH» FLOAT, «WHD» FLOAT, «WHA» FLOAT, «SJH» FLOAT, «SJD» FLOAT, «SJA» FLOAT, «VCH» FLOAT, «VCD» FLOAT, «VCA» FLOAT, «GBH» FLOAT, «GBD» FLOAT, «GBA» FLOAT, «BSH» FLOAT, «BSD» FLOAT, «BSA» FLOAT)

theorem eq (t0 : TableRel PLAYER_schema) (t1 : TableRel MATCH_schema) :
    (sql%([PLAYER_schema, MATCH_schema]) "WITH player_matches AS (/* Home players in home wins */ SELECT CAST(f.value AS INT) AS player_api_id, 'win' AS result FROM \"EU_SOCCER\".\"EU_SOCCER\".\"MATCH\" AS m, LATERAL UNNEST(ARRAY[m.\"home_player_1\", m.\"home_player_2\", m.\"home_player_3\", m.\"home_player_4\", m.\"home_player_5\", m.\"home_player_6\", m.\"home_player_7\", m.\"home_player_8\", m.\"home_player_9\", m.\"home_player_10\", m.\"home_player_11\"]) AS f(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE m.\"home_team_goal\" > m.\"away_team_goal\" AND NOT f.value IS NULL UNION ALL /* Away players in away wins */ SELECT CAST(f.value AS INT) AS player_api_id, 'win' AS result FROM \"EU_SOCCER\".\"EU_SOCCER\".\"MATCH\" AS m, LATERAL UNNEST(ARRAY[m.\"away_player_1\", m.\"away_player_2\", m.\"away_player_3\", m.\"away_player_4\", m.\"away_player_5\", m.\"away_player_6\", m.\"away_player_7\", m.\"away_player_8\", m.\"away_player_9\", m.\"away_player_10\", m.\"away_player_11\"]) AS f(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE m.\"away_team_goal\" > m.\"home_team_goal\" AND NOT f.value IS NULL UNION ALL /* Home players in home losses */ SELECT CAST(f.value AS INT) AS player_api_id, 'loss' AS result FROM \"EU_SOCCER\".\"EU_SOCCER\".\"MATCH\" AS m, LATERAL UNNEST(ARRAY[m.\"home_player_1\", m.\"home_player_2\", m.\"home_player_3\", m.\"home_player_4\", m.\"home_player_5\", m.\"home_player_6\", m.\"home_player_7\", m.\"home_player_8\", m.\"home_player_9\", m.\"home_player_10\", m.\"home_player_11\"]) AS f(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE m.\"home_team_goal\" < m.\"away_team_goal\" AND NOT f.value IS NULL UNION ALL /* Away players in away losses */ SELECT CAST(f.value AS INT) AS player_api_id, 'loss' AS result FROM \"EU_SOCCER\".\"EU_SOCCER\".\"MATCH\" AS m, LATERAL UNNEST(ARRAY[m.\"away_player_1\", m.\"away_player_2\", m.\"away_player_3\", m.\"away_player_4\", m.\"away_player_5\", m.\"away_player_6\", m.\"away_player_7\", m.\"away_player_8\", m.\"away_player_9\", m.\"away_player_10\", m.\"away_player_11\"]) AS f(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE m.\"away_team_goal\" < m.\"home_team_goal\" AND NOT f.value IS NULL), win_counts AS (SELECT player_api_id, COUNT(*) AS match_count FROM player_matches WHERE result = 'win' GROUP BY player_api_id ORDER BY match_count DESC LIMIT 1), loss_counts AS (SELECT player_api_id, COUNT(*) AS match_count FROM player_matches WHERE result = 'loss' GROUP BY player_api_id ORDER BY match_count DESC LIMIT 1) SELECT 'most_wins' AS CATEGORY, p.\"player_name\" AS PLAYER_NAME, w.match_count AS MATCH_COUNT FROM win_counts AS w JOIN \"EU_SOCCER\".\"EU_SOCCER\".\"PLAYER\" AS p ON w.player_api_id = p.\"player_api_id\" UNION ALL SELECT 'most_losses' AS CATEGORY, p.\"player_name\" AS PLAYER_NAME, l.match_count AS MATCH_COUNT FROM loss_counts AS l JOIN \"EU_SOCCER\".\"EU_SOCCER\".\"PLAYER\" AS p ON l.player_api_id = p.\"player_api_id\"") t0 t1
  ~= (sql%([PLAYER_schema, MATCH_schema]) "WITH unpivoted AS (SELECT u.\"home_team_goal\", u.\"away_team_goal\", u.player_api_id, CASE WHEN u.player_col LIKE 'home%' THEN 'home' ELSE 'away' END AS side FROM \"EU_SOCCER\".\"EU_SOCCER\".\"MATCH\" WHERE u.\"home_team_goal\" <> u.\"away_team_goal\"), player_results AS (SELECT player_api_id, CASE WHEN (side = 'home' AND \"home_team_goal\" > \"away_team_goal\") OR (side = 'away' AND \"away_team_goal\" > \"home_team_goal\") THEN 'win' ELSE 'loss' END AS result FROM unpivoted), win_counts AS (SELECT player_api_id, COUNT(*) AS match_count FROM player_results WHERE result = 'win' GROUP BY player_api_id ORDER BY match_count DESC LIMIT 1), loss_counts AS (SELECT player_api_id, COUNT(*) AS match_count FROM player_results WHERE result = 'loss' GROUP BY player_api_id ORDER BY match_count DESC LIMIT 1) SELECT 'most_wins' AS CATEGORY, pl.\"player_name\" AS PLAYER_NAME, w.match_count AS MATCH_COUNT FROM win_counts AS w JOIN \"EU_SOCCER\".\"EU_SOCCER\".\"PLAYER\" AS pl ON pl.\"player_api_id\" = w.player_api_id UNION ALL SELECT 'most_losses' AS CATEGORY, pl.\"player_name\" AS PLAYER_NAME, l.match_count AS MATCH_COUNT FROM loss_counts AS l JOIN \"EU_SOCCER\".\"EU_SOCCER\".\"PLAYER\" AS pl ON pl.\"player_api_id\" = l.player_api_id ORDER BY CATEGORY DESC") t0 t1
  := by first | sql_equiv | sorry

end N_sf_local220_eq_0_2
