import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_local066_eq_1_3

CREATE TABLE PIZZA_CLEAN_RUNNER_ORDERS («order_id» INT, «runner_id» INT, «pickup_time» STRING, «distance» FLOAT, «duration» FLOAT, «cancellation» STRING)
CREATE TABLE PIZZA_RECIPES («pizza_id» INT, «toppings» STRING)
CREATE TABLE PIZZA_CLEAN_CUSTOMER_ORDERS («order_id» INT, «customer_id» INT, «pizza_id» INT, «exclusions» STRING, «extras» STRING, «order_time» STRING)
CREATE TABLE PIZZA_TOPPINGS («topping_id» INT, «topping_name» STRING)

theorem eq (t0 : TableRel PIZZA_CLEAN_RUNNER_ORDERS_schema) (t1 : TableRel PIZZA_RECIPES_schema) (t2 : TableRel PIZZA_CLEAN_CUSTOMER_ORDERS_schema) (t3 : TableRel PIZZA_TOPPINGS_schema) :
    (sql%([PIZZA_CLEAN_RUNNER_ORDERS_schema, PIZZA_RECIPES_schema, PIZZA_CLEAN_CUSTOMER_ORDERS_schema, PIZZA_TOPPINGS_schema]) "/* For delivered pizzas, summarize total quantity of each ingredient used */ /* Using exclusions/extras columns from PIZZA_CLEAN_CUSTOMER_ORDERS directly */ WITH delivered_orders AS (SELECT \"order_id\" FROM \"MODERN_DATA\".\"MODERN_DATA\".\"PIZZA_CLEAN_RUNNER_ORDERS\" WHERE \"cancellation\" IS NULL OR \"cancellation\" = ''), delivered_pizzas /* Customer orders for delivered pizzas with a unique row number */ AS (SELECT c.\"order_id\", c.\"pizza_id\", c.\"exclusions\", c.\"extras\", ROW_NUMBER() OVER (ORDER BY c.\"order_id\", c.\"pizza_id\") AS pizza_row FROM \"MODERN_DATA\".\"MODERN_DATA\".\"PIZZA_CLEAN_CUSTOMER_ORDERS\" AS c INNER JOIN delivered_orders AS d ON c.\"order_id\" = d.\"order_id\"), base_toppings /* Expand base recipe toppings for each delivered pizza */ AS (SELECT dp.pizza_row, dp.\"order_id\", dp.\"exclusions\", CAST(TRIM(rt.VALUE) AS INT) AS topping_id FROM delivered_pizzas AS dp JOIN \"MODERN_DATA\".\"MODERN_DATA\".\"PIZZA_RECIPES\" AS r ON dp.\"pizza_id\" = r.\"pizza_id\", LATERAL SPLIT_TO_TABLE(r.\"toppings\", ',') AS rt), pizza_exclusions /* Expand exclusions per pizza (split comma-separated exclusions) */ AS (SELECT dp.pizza_row, CAST(TRIM(ex.VALUE) AS INT) AS topping_id FROM delivered_pizzas AS dp, LATERAL SPLIT_TO_TABLE(dp.\"exclusions\", ',') AS ex WHERE NOT dp.\"exclusions\" IS NULL AND dp.\"exclusions\" <> ''), pizza_extras /* Expand extras per pizza (split comma-separated extras) */ AS (SELECT dp.pizza_row, CAST(TRIM(ext.VALUE) AS INT) AS topping_id FROM delivered_pizzas AS dp, LATERAL SPLIT_TO_TABLE(dp.\"extras\", ',') AS ext WHERE NOT dp.\"extras\" IS NULL AND dp.\"extras\" <> ''), all_toppings /* All toppings = base (minus exclusions) + extras */ AS (/* Base toppings minus exclusions */ SELECT b.topping_id FROM base_toppings AS b WHERE NOT EXISTS(SELECT 1 FROM pizza_exclusions AS pe WHERE pe.pizza_row = b.pizza_row AND pe.topping_id = b.topping_id) UNION ALL /* Extra toppings */ SELECT pe.topping_id FROM pizza_extras AS pe) /* Final aggregation */ SELECT t.\"topping_name\" AS \"TOPPING_NAME\", COUNT(*) AS \"TOTAL_QUANTITY\" FROM all_toppings AS a JOIN \"MODERN_DATA\".\"MODERN_DATA\".\"PIZZA_TOPPINGS\" AS t ON a.topping_id = t.\"topping_id\" GROUP BY t.\"topping_name\" ORDER BY t.\"topping_name\"") t0 t1 t2 t3
  = (sql%([PIZZA_CLEAN_RUNNER_ORDERS_schema, PIZZA_RECIPES_schema, PIZZA_CLEAN_CUSTOMER_ORDERS_schema, PIZZA_TOPPINGS_schema]) "/* For each ingredient, count total times used on delivered pizzas */ /* considering base recipe toppings, extras added, and exclusions removed */ WITH delivered_orders AS (SELECT \"order_id\" FROM \"MODERN_DATA\".\"MODERN_DATA\".\"PIZZA_CLEAN_RUNNER_ORDERS\" WHERE \"cancellation\" IS NULL OR \"cancellation\" = ''), delivered_pizzas /* Number the customer order rows within each order to get a unique identifier */ AS (SELECT co.\"order_id\", co.\"pizza_id\", co.\"exclusions\", co.\"extras\", ROW_NUMBER() OVER (PARTITION BY co.\"order_id\" ORDER BY co.\"order_time\", co.\"pizza_id\") AS rn FROM \"MODERN_DATA\".\"MODERN_DATA\".\"PIZZA_CLEAN_CUSTOMER_ORDERS\" AS co INNER JOIN delivered_orders AS d ON co.\"order_id\" = d.\"order_id\"), recipe_toppings /* Split comma-separated recipe toppings into individual rows */ AS (SELECT r.\"pizza_id\", CAST(TRIM(CAST(f.value AS TEXT)) AS INT) AS topping_id FROM \"MODERN_DATA\".\"MODERN_DATA\".\"PIZZA_RECIPES\" AS r, LATERAL UNNEST(input => SPLIT(r.\"toppings\", ',')) AS f(SEQ, KEY, PATH, INDEX, VALUE, THIS)), base_toppings /* Base toppings for each delivered pizza */ AS (SELECT dp.\"order_id\", dp.rn, rt.topping_id FROM delivered_pizzas AS dp INNER JOIN recipe_toppings AS rt ON dp.\"pizza_id\" = rt.\"pizza_id\"), pizza_exclusions /* Parse exclusions per pizza from the customer orders */ AS (SELECT dp.\"order_id\", dp.rn, CAST(TRIM(CAST(f.value AS TEXT)) AS INT) AS topping_id FROM delivered_pizzas AS dp, LATERAL UNNEST(input => SPLIT(dp.\"exclusions\", ','), OUTER => TRUE) AS f(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE NOT dp.\"exclusions\" IS NULL AND dp.\"exclusions\" <> ''), pizza_extras /* Parse extras per pizza from the customer orders */ AS (SELECT dp.\"order_id\", dp.rn, CAST(TRIM(CAST(f.value AS TEXT)) AS INT) AS topping_id FROM delivered_pizzas AS dp, LATERAL UNNEST(input => SPLIT(dp.\"extras\", ','), OUTER => TRUE) AS f(SEQ, KEY, PATH, INDEX, VALUE, THIS) WHERE NOT dp.\"extras\" IS NULL AND dp.\"extras\" <> ''), base_minus_exclusions /* Remove exclusions from base toppings */ AS (SELECT bt.\"order_id\", bt.rn, bt.topping_id FROM base_toppings AS bt LEFT JOIN pizza_exclusions AS exc ON bt.\"order_id\" = exc.\"order_id\" AND bt.rn = exc.rn AND bt.topping_id = exc.topping_id WHERE exc.topping_id IS NULL), all_toppings /* Combine base (minus exclusions) with extras */ AS (SELECT topping_id FROM base_minus_exclusions UNION ALL SELECT topping_id FROM pizza_extras) /* Final aggregation: count per topping */ SELECT t.\"topping_name\" AS \"TOPPING_NAME\", COUNT(*) AS \"TOTAL_QUANTITY\" FROM all_toppings AS a INNER JOIN \"MODERN_DATA\".\"MODERN_DATA\".\"PIZZA_TOPPINGS\" AS t ON a.topping_id = t.\"topping_id\" GROUP BY t.\"topping_name\" ORDER BY t.\"topping_name\"") t0 t1 t2 t3
  := by first | sql_equiv | sorry

end N_sf_local066_eq_1_3
