import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_local132_eq_0_1

CREATE TABLE ENTERTAINERS («EntertainerID» INT, «EntStageName» STRING, «EntSSN» STRING, «EntStreetAddress» STRING, «EntCity» STRING, «EntState» STRING, «EntZipCode» STRING, «EntPhoneNumber» STRING, «EntWebPage» STRING, «EntEMailAddress» STRING, «DateEntered» STRING)
CREATE TABLE ENTERTAINER_STYLES («EntertainerID» INT, «StyleID» INT, «StyleStrength» INT)
CREATE TABLE CUSTOMERS («CustomerID» INT, «CustFirstName» STRING, «CustLastName» STRING, «CustStreetAddress» STRING, «CustCity» STRING, «CustState» STRING, «CustZipCode» STRING, «CustPhoneNumber» STRING)
CREATE TABLE MUSICAL_PREFERENCES («CustomerID» INT, «StyleID» INT, «PreferenceSeq» INT)

theorem eq (t0 : TableRel ENTERTAINERS_schema) (t1 : TableRel ENTERTAINER_STYLES_schema) (t2 : TableRel CUSTOMERS_schema) (t3 : TableRel MUSICAL_PREFERENCES_schema) :
    (sql%([ENTERTAINERS_schema, ENTERTAINER_STYLES_schema, CUSTOMERS_schema, MUSICAL_PREFERENCES_schema]) "WITH ent_styles AS (SELECT es1.\"EntertainerID\", es1.\"StyleID\" AS style1, es2.\"StyleID\" AS style2 FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"ENTERTAINER_STYLES\" AS es1 JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"ENTERTAINER_STYLES\" AS es2 ON es1.\"EntertainerID\" = es2.\"EntertainerID\" WHERE es1.\"StyleStrength\" = 1 AND es2.\"StyleStrength\" = 2), cust_prefs AS (SELECT mp1.\"CustomerID\", mp1.\"StyleID\" AS pref1, mp2.\"StyleID\" AS pref2 FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\" AS mp1 JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\" AS mp2 ON mp1.\"CustomerID\" = mp2.\"CustomerID\" WHERE mp1.\"PreferenceSeq\" = 1 AND mp2.\"PreferenceSeq\" = 2) SELECT e.\"EntStageName\" AS \"StageName\", c.\"CustLastName\" AS \"LastName\" FROM ent_styles AS es JOIN cust_prefs AS cp ON (cp.pref1 = es.style1 AND cp.pref2 = es.style2) OR (cp.pref1 = es.style2 AND cp.pref2 = es.style1) JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"ENTERTAINERS\" AS e ON es.\"EntertainerID\" = e.\"EntertainerID\" JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"CUSTOMERS\" AS c ON cp.\"CustomerID\" = c.\"CustomerID\" ORDER BY e.\"EntStageName\", c.\"CustLastName\"") t0 t1 t2 t3
  ~= (sql%([ENTERTAINERS_schema, ENTERTAINER_STYLES_schema, CUSTOMERS_schema, MUSICAL_PREFERENCES_schema]) "WITH cust_prefs AS (SELECT cp1.\"CustomerID\", cp1.\"StyleID\" AS pref1, cp2.\"StyleID\" AS pref2 FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\" AS cp1 JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\" AS cp2 ON cp1.\"CustomerID\" = cp2.\"CustomerID\" AND cp1.\"PreferenceSeq\" = 1 AND cp2.\"PreferenceSeq\" = 2 WHERE cp1.\"CustomerID\" IN (SELECT \"CustomerID\" FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\" GROUP BY \"CustomerID\" HAVING COUNT(*) <= 3)), ent_strengths AS (SELECT es1.\"EntertainerID\", es1.\"StyleID\" AS str1, es2.\"StyleID\" AS str2 FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"ENTERTAINER_STYLES\" AS es1 JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"ENTERTAINER_STYLES\" AS es2 ON es1.\"EntertainerID\" = es2.\"EntertainerID\" AND es1.\"StyleStrength\" = 1 AND es2.\"StyleStrength\" = 2 WHERE es1.\"EntertainerID\" IN (SELECT \"EntertainerID\" FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"ENTERTAINER_STYLES\" GROUP BY \"EntertainerID\" HAVING COUNT(*) <= 3)) SELECT e.\"EntStageName\" AS \"StageName\", c.\"CustLastName\" AS \"LastName\" FROM cust_prefs AS cp JOIN ent_strengths AS es ON (cp.pref1 = es.str1 AND cp.pref2 = es.str2) OR (cp.pref1 = es.str2 AND cp.pref2 = es.str1) JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"CUSTOMERS\" AS c ON cp.\"CustomerID\" = c.\"CustomerID\" JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"ENTERTAINERS\" AS e ON es.\"EntertainerID\" = e.\"EntertainerID\" ORDER BY e.\"EntStageName\", c.\"CustLastName\"") t0 t1 t2 t3
  := by first | sql_equiv | sorry

end N_sf_local132_eq_0_1
