import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_local297_eq_0_2

CREATE TABLE CUSTOMER_TRANSACTIONS («customer_id» INT, «txn_date» STRING, «txn_type» STRING, «txn_amount» INT)

theorem eq (t0 : TableRel CUSTOMER_TRANSACTIONS_schema) :
    (sql%([CUSTOMER_TRANSACTIONS_schema]) "WITH monthly_net AS (SELECT \"customer_id\", DATE_TRUNC('MONTH', CAST(TO_TIMESTAMP(\"txn_date\", 'YYYY-MM-DD') AS DATE)) AS month_start, SUM(CASE WHEN \"txn_type\" = 'deposit' THEN \"txn_amount\" WHEN \"txn_type\" = 'withdrawal' THEN -\"txn_amount\" ELSE 0 END) AS net_amount FROM \"BANK_SALES_TRADING\".\"BANK_SALES_TRADING\".\"CUSTOMER_TRANSACTIONS\" GROUP BY \"customer_id\", month_start), closing_balance AS (SELECT \"customer_id\", month_start, SUM(net_amount) OVER (PARTITION BY \"customer_id\" ORDER BY month_start) AS closing_bal FROM monthly_net), with_prev AS (SELECT \"customer_id\", month_start, closing_bal, LAG(closing_bal) OVER (PARTITION BY \"customer_id\" ORDER BY month_start) AS prev_closing_bal, ROW_NUMBER() OVER (PARTITION BY \"customer_id\" ORDER BY month_start DESC) AS rn_desc FROM closing_balance), most_recent AS (SELECT \"customer_id\", closing_bal, prev_closing_bal, CASE WHEN prev_closing_bal = 0 THEN closing_bal * 100 ELSE CAST((closing_bal - prev_closing_bal) AS DOUBLE PRECISION) / prev_closing_bal * 100 END AS growth_rate FROM with_prev WHERE rn_desc = 1 AND NOT prev_closing_bal IS NULL) SELECT CAST(100.0 * SUM(CASE WHEN growth_rate > 5 THEN 1 ELSE 0 END) AS DOUBLE PRECISION) / COUNT(*) AS PCT_CUSTOMERS_GROWTH_GT_5 FROM most_recent") t0
  ~= (sql%([CUSTOMER_TRANSACTIONS_schema]) "WITH all_months AS (SELECT DISTINCT \"customer_id\", DATE_TRUNC('MONTH', CAST(TO_TIMESTAMP(\"txn_date\", 'YYYY-MM-DD') AS DATE)) AS month_start FROM \"BANK_SALES_TRADING\".\"BANK_SALES_TRADING\".\"CUSTOMER_TRANSACTIONS\"), monthly_net AS (SELECT a.\"customer_id\", a.month_start, COALESCE(SUM(CASE WHEN t.\"txn_type\" = 'deposit' THEN t.\"txn_amount\" WHEN t.\"txn_type\" = 'withdrawal' THEN -t.\"txn_amount\" END), 0) AS net_amount FROM all_months AS a LEFT JOIN \"BANK_SALES_TRADING\".\"BANK_SALES_TRADING\".\"CUSTOMER_TRANSACTIONS\" AS t ON a.\"customer_id\" = t.\"customer_id\" AND DATE_TRUNC('MONTH', CAST(TO_TIMESTAMP(t.\"txn_date\", 'YYYY-MM-DD') AS DATE)) = a.month_start AND t.\"txn_type\" IN ('deposit', 'withdrawal') GROUP BY a.\"customer_id\", a.month_start), closing_balance AS (SELECT \"customer_id\", month_start, SUM(net_amount) OVER (PARTITION BY \"customer_id\" ORDER BY month_start ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS closing_bal FROM monthly_net), with_prev AS (SELECT \"customer_id\", month_start, closing_bal, LAG(closing_bal) OVER (PARTITION BY \"customer_id\" ORDER BY month_start) AS prev_closing_bal, ROW_NUMBER() OVER (PARTITION BY \"customer_id\" ORDER BY month_start DESC) AS rn FROM closing_balance), most_recent AS (SELECT *, CASE WHEN prev_closing_bal = 0 THEN closing_bal * 100 ELSE (CAST((closing_bal - prev_closing_bal) * 100.0 AS DOUBLE PRECISION) / prev_closing_bal) END AS growth_rate FROM with_prev WHERE rn = 1 AND NOT prev_closing_bal IS NULL) SELECT CAST(100.0 * COUNT(CASE WHEN growth_rate > 5 THEN 1 END) AS DOUBLE PRECISION) / COUNT(*) AS \"PCT_CUSTOMERS_GROWTH_GT_5\" FROM most_recent") t0
  := by first | sql_equiv | sorry

end N_sf_local297_eq_0_2
