import LeanDatabase.Hypothesis
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 8000
set_option sqlEquivLlm.provider "gemini"
set_option sqlEquivLlm.model "gemini-pro-latest"

/-!
# sf_local221 — crossskill equivalence(s)

Question: Tell me top10 teams with the most wins across the league

Each theorem: `first | sql_equiv | sorry` — proved by `sql_equiv` where it closes, else
`sorry`. Data-dependent differences are stated as explicit `HYPOTHESIS` antecedents (sound).
-/

namespace Bench_sf_local221

CREATE TABLE MATCH («id» INT, «country_id» INT, «league_id» INT, «season» STRING, «stage» INT, «date» STRING, «match_api_id» INT, «home_team_api_id» INT, «away_team_api_id» INT, «home_team_goal» INT, «away_team_goal» INT, «home_player_X1» FLOAT, «home_player_X2» FLOAT, «home_player_X3» FLOAT, «home_player_X4» FLOAT, «home_player_X5» FLOAT, «home_player_X6» FLOAT, «home_player_X7» FLOAT, «home_player_X8» FLOAT, «home_player_X9» FLOAT, «home_player_X10» FLOAT, «home_player_X11» FLOAT, «away_player_X1» FLOAT, «away_player_X2» FLOAT, «away_player_X3» FLOAT, «away_player_X4» FLOAT, «away_player_X5» FLOAT, «away_player_X6» FLOAT, «away_player_X7» FLOAT, «away_player_X8» FLOAT, «away_player_X9» FLOAT, «away_player_X10» FLOAT, «away_player_X11» FLOAT, «home_player_Y1» FLOAT, «home_player_Y2» FLOAT, «home_player_Y3» FLOAT, «home_player_Y4» FLOAT, «home_player_Y5» FLOAT, «home_player_Y6» FLOAT, «home_player_Y7» FLOAT, «home_player_Y8» FLOAT, «home_player_Y9» FLOAT, «home_player_Y10» FLOAT, «home_player_Y11» FLOAT, «away_player_Y1» FLOAT, «away_player_Y2» FLOAT, «away_player_Y3» FLOAT, «away_player_Y4» FLOAT, «away_player_Y5» FLOAT, «away_player_Y6» FLOAT, «away_player_Y7» FLOAT, «away_player_Y8» FLOAT, «away_player_Y9» FLOAT, «away_player_Y10» FLOAT, «away_player_Y11» FLOAT, «home_player_1» FLOAT, «home_player_2» FLOAT, «home_player_3» FLOAT, «home_player_4» FLOAT, «home_player_5» FLOAT, «home_player_6» FLOAT, «home_player_7» FLOAT, «home_player_8» FLOAT, «home_player_9» FLOAT, «home_player_10» FLOAT, «home_player_11» FLOAT, «away_player_1» FLOAT, «away_player_2» FLOAT, «away_player_3» FLOAT, «away_player_4» FLOAT, «away_player_5» FLOAT, «away_player_6» FLOAT, «away_player_7» FLOAT, «away_player_8» FLOAT, «away_player_9» FLOAT, «away_player_10» FLOAT, «away_player_11» FLOAT, «goal» STRING, «shoton» STRING, «shotoff» STRING, «foulcommit» STRING, «card» STRING, «cross» STRING, «corner» STRING, «possession» STRING, «B365H» FLOAT, «B365D» FLOAT, «B365A» FLOAT, «BWH» FLOAT, «BWD» FLOAT, «BWA» FLOAT, «IWH» FLOAT, «IWD» FLOAT, «IWA» FLOAT, «LBH» FLOAT, «LBD» FLOAT, «LBA» FLOAT, «PSH» FLOAT, «PSD» FLOAT, «PSA» FLOAT, «WHH» FLOAT, «WHD» FLOAT, «WHA» FLOAT, «SJH» FLOAT, «SJD» FLOAT, «SJA» FLOAT, «VCH» FLOAT, «VCD» FLOAT, «VCA» FLOAT, «GBH» FLOAT, «GBD» FLOAT, «GBA» FLOAT, «BSH» FLOAT, «BSD» FLOAT, «BSA» FLOAT)
CREATE TABLE TEAM («id» INT, «team_api_id» INT, «team_fifa_api_id» FLOAT, «team_long_name» STRING, «team_short_name» STRING)

-- eq_0_1: needs a data hypothesis over multiple tables (not stated); likely `sorry`.
theorem eq_0_1 : ∀ t,
    (sql%([MATCH_schema, TEAM_schema]) "WITH wins AS (/* Home wins: team won as home team */ SELECT \"home_team_api_id\" AS team_api_id FROM \"EU_SOCCER\".\"EU_SOCCER\".\"MATCH\" WHERE \"home_team_goal\" > \"away_team_goal\" UNION ALL /* Away wins: team won as away team */ SELECT \"away_team_api_id\" AS team_api_id FROM \"EU_SOCCER\".\"EU_SOCCER\".\"MATCH\" WHERE \"away_team_goal\" > \"home_team_goal\") SELECT t.\"team_long_name\", COUNT(*) AS TOTAL_WINS FROM wins AS w JOIN \"EU_SOCCER\".\"EU_SOCCER\".\"TEAM\" AS t ON w.team_api_id = t.\"team_api_id\" GROUP BY t.\"team_long_name\" ORDER BY TOTAL_WINS DESC LIMIT 10") t ~= (sql%([MATCH_schema, TEAM_schema]) "WITH wins AS (/* Home wins */ SELECT m.\"home_team_api_id\" AS team_api_id, COUNT(*) AS wins FROM \"EU_SOCCER\".\"EU_SOCCER\".\"MATCH\" AS m WHERE m.\"home_team_goal\" > m.\"away_team_goal\" GROUP BY m.\"home_team_api_id\" UNION ALL /* Away wins */ SELECT m.\"away_team_api_id\" AS team_api_id, COUNT(*) AS wins FROM \"EU_SOCCER\".\"EU_SOCCER\".\"MATCH\" AS m WHERE m.\"away_team_goal\" > m.\"home_team_goal\" GROUP BY m.\"away_team_api_id\") SELECT t.\"team_long_name\", SUM(w.wins) AS TOTAL_WINS FROM wins AS w JOIN \"EU_SOCCER\".\"EU_SOCCER\".\"TEAM\" AS t ON t.\"team_api_id\" = w.team_api_id GROUP BY t.\"team_long_name\" ORDER BY TOTAL_WINS DESC LIMIT 10") t := by
  intro t; first | sql_equiv | sorry

theorem eq_0_2 : ∀ t,
    (sql%([MATCH_schema, TEAM_schema]) "WITH wins AS (/* Home wins: team won as home team */ SELECT \"home_team_api_id\" AS team_api_id FROM \"EU_SOCCER\".\"EU_SOCCER\".\"MATCH\" WHERE \"home_team_goal\" > \"away_team_goal\" UNION ALL /* Away wins: team won as away team */ SELECT \"away_team_api_id\" AS team_api_id FROM \"EU_SOCCER\".\"EU_SOCCER\".\"MATCH\" WHERE \"away_team_goal\" > \"home_team_goal\") SELECT t.\"team_long_name\", COUNT(*) AS TOTAL_WINS FROM wins AS w JOIN \"EU_SOCCER\".\"EU_SOCCER\".\"TEAM\" AS t ON w.team_api_id = t.\"team_api_id\" GROUP BY t.\"team_long_name\" ORDER BY TOTAL_WINS DESC LIMIT 10") t ~= (sql%([MATCH_schema, TEAM_schema]) "SELECT t.\"team_long_name\", COUNT(*) AS \"TOTAL_WINS\" FROM (SELECT \"home_team_api_id\" AS \"team_api_id\" FROM \"EU_SOCCER\".\"EU_SOCCER\".\"MATCH\" WHERE \"home_team_goal\" > \"away_team_goal\" UNION ALL SELECT \"away_team_api_id\" AS \"team_api_id\" FROM \"EU_SOCCER\".\"EU_SOCCER\".\"MATCH\" WHERE \"away_team_goal\" > \"home_team_goal\") AS w JOIN \"EU_SOCCER\".\"EU_SOCCER\".\"TEAM\" AS t ON w.\"team_api_id\" = t.\"team_api_id\" GROUP BY t.\"team_long_name\" ORDER BY \"TOTAL_WINS\" DESC LIMIT 10") t := by
  intro t; first | sql_equiv | sorry

theorem eq_0_3 :
    sql%([MATCH_schema, TEAM_schema]) "WITH wins AS (/* Home wins: team won as home team */ SELECT \"home_team_api_id\" AS team_api_id FROM \"EU_SOCCER\".\"EU_SOCCER\".\"MATCH\" WHERE \"home_team_goal\" > \"away_team_goal\" UNION ALL /* Away wins: team won as away team */ SELECT \"away_team_api_id\" AS team_api_id FROM \"EU_SOCCER\".\"EU_SOCCER\".\"MATCH\" WHERE \"away_team_goal\" > \"home_team_goal\") SELECT t.\"team_long_name\", COUNT(*) AS TOTAL_WINS FROM wins AS w JOIN \"EU_SOCCER\".\"EU_SOCCER\".\"TEAM\" AS t ON w.team_api_id = t.\"team_api_id\" GROUP BY t.\"team_long_name\" ORDER BY TOTAL_WINS DESC LIMIT 10" = sql%([MATCH_schema, TEAM_schema]) "WITH wins AS (/* Home wins */ SELECT m.\"home_team_api_id\" AS \"team_api_id\" FROM \"EU_SOCCER\".\"EU_SOCCER\".\"MATCH\" AS m WHERE m.\"home_team_goal\" > m.\"away_team_goal\" UNION ALL /* Away wins */ SELECT m.\"away_team_api_id\" AS \"team_api_id\" FROM \"EU_SOCCER\".\"EU_SOCCER\".\"MATCH\" AS m WHERE m.\"away_team_goal\" > m.\"home_team_goal\"), team_wins AS (SELECT \"team_api_id\", COUNT(*) AS \"wins\" FROM wins GROUP BY \"team_api_id\") SELECT t.\"team_long_name\", tw.\"wins\" FROM team_wins AS tw JOIN \"EU_SOCCER\".\"EU_SOCCER\".\"TEAM\" AS t ON tw.\"team_api_id\" = t.\"team_api_id\" ORDER BY tw.\"wins\" DESC LIMIT 10" := by
  first | sql_equiv | sorry

-- eq_1_2: needs a data hypothesis over multiple tables (not stated); likely `sorry`.
theorem eq_1_2 : ∀ t,
    (sql%([MATCH_schema, TEAM_schema]) "WITH wins AS (/* Home wins */ SELECT m.\"home_team_api_id\" AS team_api_id, COUNT(*) AS wins FROM \"EU_SOCCER\".\"EU_SOCCER\".\"MATCH\" AS m WHERE m.\"home_team_goal\" > m.\"away_team_goal\" GROUP BY m.\"home_team_api_id\" UNION ALL /* Away wins */ SELECT m.\"away_team_api_id\" AS team_api_id, COUNT(*) AS wins FROM \"EU_SOCCER\".\"EU_SOCCER\".\"MATCH\" AS m WHERE m.\"away_team_goal\" > m.\"home_team_goal\" GROUP BY m.\"away_team_api_id\") SELECT t.\"team_long_name\", SUM(w.wins) AS TOTAL_WINS FROM wins AS w JOIN \"EU_SOCCER\".\"EU_SOCCER\".\"TEAM\" AS t ON t.\"team_api_id\" = w.team_api_id GROUP BY t.\"team_long_name\" ORDER BY TOTAL_WINS DESC LIMIT 10") t ~= (sql%([MATCH_schema, TEAM_schema]) "SELECT t.\"team_long_name\", COUNT(*) AS \"TOTAL_WINS\" FROM (SELECT \"home_team_api_id\" AS \"team_api_id\" FROM \"EU_SOCCER\".\"EU_SOCCER\".\"MATCH\" WHERE \"home_team_goal\" > \"away_team_goal\" UNION ALL SELECT \"away_team_api_id\" AS \"team_api_id\" FROM \"EU_SOCCER\".\"EU_SOCCER\".\"MATCH\" WHERE \"away_team_goal\" > \"home_team_goal\") AS w JOIN \"EU_SOCCER\".\"EU_SOCCER\".\"TEAM\" AS t ON w.\"team_api_id\" = t.\"team_api_id\" GROUP BY t.\"team_long_name\" ORDER BY \"TOTAL_WINS\" DESC LIMIT 10") t := by
  intro t; first | sql_equiv | sorry

-- eq_1_3: needs a data hypothesis over multiple tables (not stated); likely `sorry`.
theorem eq_1_3 : ∀ t,
    (sql%([MATCH_schema, TEAM_schema]) "WITH wins AS (/* Home wins */ SELECT m.\"home_team_api_id\" AS team_api_id, COUNT(*) AS wins FROM \"EU_SOCCER\".\"EU_SOCCER\".\"MATCH\" AS m WHERE m.\"home_team_goal\" > m.\"away_team_goal\" GROUP BY m.\"home_team_api_id\" UNION ALL /* Away wins */ SELECT m.\"away_team_api_id\" AS team_api_id, COUNT(*) AS wins FROM \"EU_SOCCER\".\"EU_SOCCER\".\"MATCH\" AS m WHERE m.\"away_team_goal\" > m.\"home_team_goal\" GROUP BY m.\"away_team_api_id\") SELECT t.\"team_long_name\", SUM(w.wins) AS TOTAL_WINS FROM wins AS w JOIN \"EU_SOCCER\".\"EU_SOCCER\".\"TEAM\" AS t ON t.\"team_api_id\" = w.team_api_id GROUP BY t.\"team_long_name\" ORDER BY TOTAL_WINS DESC LIMIT 10") t ~= (sql%([MATCH_schema, TEAM_schema]) "WITH wins AS (/* Home wins */ SELECT m.\"home_team_api_id\" AS \"team_api_id\" FROM \"EU_SOCCER\".\"EU_SOCCER\".\"MATCH\" AS m WHERE m.\"home_team_goal\" > m.\"away_team_goal\" UNION ALL /* Away wins */ SELECT m.\"away_team_api_id\" AS \"team_api_id\" FROM \"EU_SOCCER\".\"EU_SOCCER\".\"MATCH\" AS m WHERE m.\"away_team_goal\" > m.\"home_team_goal\"), team_wins AS (SELECT \"team_api_id\", COUNT(*) AS \"wins\" FROM wins GROUP BY \"team_api_id\") SELECT t.\"team_long_name\", tw.\"wins\" FROM team_wins AS tw JOIN \"EU_SOCCER\".\"EU_SOCCER\".\"TEAM\" AS t ON tw.\"team_api_id\" = t.\"team_api_id\" ORDER BY tw.\"wins\" DESC LIMIT 10") t := by
  intro t; first | sql_equiv | sorry

theorem eq_2_3 : ∀ t,
    (sql%([MATCH_schema, TEAM_schema]) "SELECT t.\"team_long_name\", COUNT(*) AS \"TOTAL_WINS\" FROM (SELECT \"home_team_api_id\" AS \"team_api_id\" FROM \"EU_SOCCER\".\"EU_SOCCER\".\"MATCH\" WHERE \"home_team_goal\" > \"away_team_goal\" UNION ALL SELECT \"away_team_api_id\" AS \"team_api_id\" FROM \"EU_SOCCER\".\"EU_SOCCER\".\"MATCH\" WHERE \"away_team_goal\" > \"home_team_goal\") AS w JOIN \"EU_SOCCER\".\"EU_SOCCER\".\"TEAM\" AS t ON w.\"team_api_id\" = t.\"team_api_id\" GROUP BY t.\"team_long_name\" ORDER BY \"TOTAL_WINS\" DESC LIMIT 10") t ~= (sql%([MATCH_schema, TEAM_schema]) "WITH wins AS (/* Home wins */ SELECT m.\"home_team_api_id\" AS \"team_api_id\" FROM \"EU_SOCCER\".\"EU_SOCCER\".\"MATCH\" AS m WHERE m.\"home_team_goal\" > m.\"away_team_goal\" UNION ALL /* Away wins */ SELECT m.\"away_team_api_id\" AS \"team_api_id\" FROM \"EU_SOCCER\".\"EU_SOCCER\".\"MATCH\" AS m WHERE m.\"away_team_goal\" > m.\"home_team_goal\"), team_wins AS (SELECT \"team_api_id\", COUNT(*) AS \"wins\" FROM wins GROUP BY \"team_api_id\") SELECT t.\"team_long_name\", tw.\"wins\" FROM team_wins AS tw JOIN \"EU_SOCCER\".\"EU_SOCCER\".\"TEAM\" AS t ON tw.\"team_api_id\" = t.\"team_api_id\" ORDER BY tw.\"wins\" DESC LIMIT 10") t := by
  intro t; first | sql_equiv | sorry

end Bench_sf_local221
