import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_local132_eq_1_3

CREATE TABLE ENTERTAINERS («EntertainerID» INT, «EntStageName» STRING, «EntSSN» STRING, «EntStreetAddress» STRING, «EntCity» STRING, «EntState» STRING, «EntZipCode» STRING, «EntPhoneNumber» STRING, «EntWebPage» STRING, «EntEMailAddress» STRING, «DateEntered» STRING)
CREATE TABLE ENTERTAINER_STYLES («EntertainerID» INT, «StyleID» INT, «StyleStrength» INT)
CREATE TABLE CUSTOMERS («CustomerID» INT, «CustFirstName» STRING, «CustLastName» STRING, «CustStreetAddress» STRING, «CustCity» STRING, «CustState» STRING, «CustZipCode» STRING, «CustPhoneNumber» STRING)
CREATE TABLE MUSICAL_PREFERENCES («CustomerID» INT, «StyleID» INT, «PreferenceSeq» INT)

theorem eq (t0 : TableRel ENTERTAINERS_schema) (t1 : TableRel ENTERTAINER_STYLES_schema) (t2 : TableRel CUSTOMERS_schema) (t3 : TableRel MUSICAL_PREFERENCES_schema) :
    (sql%([ENTERTAINERS_schema, ENTERTAINER_STYLES_schema, CUSTOMERS_schema, MUSICAL_PREFERENCES_schema]) "WITH cust_prefs AS (SELECT cp1.\"CustomerID\", cp1.\"StyleID\" AS pref1, cp2.\"StyleID\" AS pref2 FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\" AS cp1 JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\" AS cp2 ON cp1.\"CustomerID\" = cp2.\"CustomerID\" AND cp1.\"PreferenceSeq\" = 1 AND cp2.\"PreferenceSeq\" = 2 WHERE cp1.\"CustomerID\" IN (SELECT \"CustomerID\" FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\" GROUP BY \"CustomerID\" HAVING COUNT(*) <= 3)), ent_strengths AS (SELECT es1.\"EntertainerID\", es1.\"StyleID\" AS str1, es2.\"StyleID\" AS str2 FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"ENTERTAINER_STYLES\" AS es1 JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"ENTERTAINER_STYLES\" AS es2 ON es1.\"EntertainerID\" = es2.\"EntertainerID\" AND es1.\"StyleStrength\" = 1 AND es2.\"StyleStrength\" = 2 WHERE es1.\"EntertainerID\" IN (SELECT \"EntertainerID\" FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"ENTERTAINER_STYLES\" GROUP BY \"EntertainerID\" HAVING COUNT(*) <= 3)) SELECT e.\"EntStageName\" AS \"StageName\", c.\"CustLastName\" AS \"LastName\" FROM cust_prefs AS cp JOIN ent_strengths AS es ON (cp.pref1 = es.str1 AND cp.pref2 = es.str2) OR (cp.pref1 = es.str2 AND cp.pref2 = es.str1) JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"CUSTOMERS\" AS c ON cp.\"CustomerID\" = c.\"CustomerID\" JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"ENTERTAINERS\" AS e ON es.\"EntertainerID\" = e.\"EntertainerID\" ORDER BY e.\"EntStageName\", c.\"CustLastName\"") t0 t1 t2 t3
  ~= (sql%([ENTERTAINERS_schema, ENTERTAINER_STYLES_schema, CUSTOMERS_schema, MUSICAL_PREFERENCES_schema]) "WITH entertainer_style_counts AS (SELECT \"EntertainerID\", COUNT(*) AS style_count FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"ENTERTAINER_STYLES\" GROUP BY \"EntertainerID\" HAVING COUNT(*) <= 3), customer_pref_counts AS (SELECT \"CustomerID\", COUNT(*) AS pref_count FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\" GROUP BY \"CustomerID\" HAVING COUNT(*) <= 3), ent_style1 AS (SELECT es.\"EntertainerID\", es.\"StyleID\" AS style1 FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"ENTERTAINER_STYLES\" AS es WHERE es.\"StyleStrength\" = 1), ent_style2 AS (SELECT es.\"EntertainerID\", es.\"StyleID\" AS style2 FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"ENTERTAINER_STYLES\" AS es WHERE es.\"StyleStrength\" = 2), cust_pref1 AS (SELECT mp.\"CustomerID\", mp.\"StyleID\" AS pref1 FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\" AS mp WHERE mp.\"PreferenceSeq\" = 1), cust_pref2 AS (SELECT mp.\"CustomerID\", mp.\"StyleID\" AS pref2 FROM \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"MUSICAL_PREFERENCES\" AS mp WHERE mp.\"PreferenceSeq\" = 2) SELECT DISTINCT e.\"EntStageName\", c.\"CustLastName\" FROM entertainer_style_counts AS esc JOIN ent_style1 AS es1 ON esc.\"EntertainerID\" = es1.\"EntertainerID\" JOIN ent_style2 AS es2 ON esc.\"EntertainerID\" = es2.\"EntertainerID\" JOIN customer_pref_counts AS cpc ON 1 = 1 JOIN cust_pref1 AS cp1 ON cpc.\"CustomerID\" = cp1.\"CustomerID\" JOIN cust_pref2 AS cp2 ON cpc.\"CustomerID\" = cp2.\"CustomerID\" JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"ENTERTAINERS\" AS e ON e.\"EntertainerID\" = esc.\"EntertainerID\" JOIN \"ENTERTAINMENTAGENCY\".\"ENTERTAINMENTAGENCY\".\"CUSTOMERS\" AS c ON c.\"CustomerID\" = cpc.\"CustomerID\" WHERE (cp1.pref1 = es1.style1 AND cp2.pref2 = es2.style2) OR (cp1.pref1 = es2.style2 AND cp2.pref2 = es1.style1) ORDER BY e.\"EntStageName\", c.\"CustLastName\"") t0 t1 t2 t3
  := by first | sql_equiv | sorry

end N_sf_local132_eq_1_3
