import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_local072_eq_2_3

CREATE TABLE CITIES («city_id» INT, «city_name» STRING, «latitude» FLOAT, «longitude» FLOAT, «country_code_2» STRING, «capital» INT, «population» FLOAT, «insert_date» STRING)

theorem eq (t0 : TableRel CITIES_schema) :
    (sql%([CITIES_schema]) "WITH target_country AS (/* Find the country with data inserted on exactly 9 different days in January 2022 */ SELECT \"country_code_2\" FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"CITIES\" WHERE \"insert_date\" >= '2022-01-01' AND \"insert_date\" <= '2022-01-31' GROUP BY \"country_code_2\" HAVING COUNT(DISTINCT \"insert_date\") = 9), insert_days AS (/* Get distinct insert dates for that country in January 2022 */ SELECT DISTINCT CAST(c.\"insert_date\" AS DATE) AS insert_day FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"CITIES\" AS c JOIN target_country AS tc ON c.\"country_code_2\" = tc.\"country_code_2\" WHERE c.\"insert_date\" >= '2022-01-01' AND c.\"insert_date\" <= '2022-01-31'), consecutive_groups AS (/* Use row_number gap technique to identify consecutive groups */ SELECT insert_day, insert_day + INTERVAL '1 DAY' * -ROW_NUMBER() OVER (ORDER BY insert_day) AS grp FROM insert_days), longest_period AS (/* Find the longest consecutive period */ SELECT MIN(insert_day) AS period_start, MAX(insert_day) AS period_end, COUNT(*) AS period_length FROM consecutive_groups GROUP BY grp ORDER BY period_length DESC LIMIT 1), period_entries AS (/* Get all entries for the target country within the longest consecutive period */ SELECT c.\"city_name\", c.\"capital\", c.\"insert_date\" FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"CITIES\" AS c JOIN target_country AS tc ON c.\"country_code_2\" = tc.\"country_code_2\" JOIN longest_period AS lp ON CAST(c.\"insert_date\" AS DATE) BETWEEN lp.period_start AND lp.period_end) SELECT ROUND(CAST(SUM(CASE WHEN \"capital\" = 1 THEN 1 ELSE 0 END) AS DECIMAL(38, 0)) / COUNT(*), 2) AS \"percentage_of_capital\" FROM period_entries") t0
  ~= (sql%([CITIES_schema]) "WITH target_country AS (/* Find the country with data inserted on exactly 9 different days in January 2022 */ SELECT cc.\"country_code_2\", cc.\"country_name\" FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"CITIES\" AS c JOIN \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"CITIES_COUNTRIES\" AS cc ON c.\"country_code_2\" = cc.\"country_code_2\" WHERE c.\"insert_date\" >= '2022-01-01' AND c.\"insert_date\" <= '2022-01-31' GROUP BY cc.\"country_code_2\", cc.\"country_name\" HAVING COUNT(DISTINCT c.\"insert_date\") = 9), distinct_days AS (/* Get distinct insert dates for the target country in January 2022 */ SELECT DISTINCT CAST(c.\"insert_date\" AS DATE) AS insert_day FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"CITIES\" AS c JOIN target_country AS tc ON c.\"country_code_2\" = tc.\"country_code_2\" WHERE c.\"insert_date\" >= '2022-01-01' AND c.\"insert_date\" <= '2022-01-31'), day_groups AS (/* Assign a group ID for consecutive days using the gaps-and-islands technique */ SELECT insert_day, insert_day + INTERVAL '1 DAY' * -ROW_NUMBER() OVER (ORDER BY insert_day) AS grp FROM distinct_days), consecutive_periods AS (/* Find consecutive periods and their lengths */ SELECT grp, MIN(insert_day) AS period_start, MAX(insert_day) AS period_end, COUNT(*) AS period_length FROM day_groups GROUP BY grp), longest_period AS (/* Select the longest consecutive period */ SELECT period_start, period_end, period_length FROM consecutive_periods ORDER BY period_length DESC, period_start LIMIT 1), entries_in_period AS (/* Get all entries for the target country within the longest consecutive period */ SELECT c.\"city_name\", c.\"capital\", c.\"insert_date\" FROM \"CITY_LEGISLATION\".\"CITY_LEGISLATION\".\"CITIES\" AS c JOIN target_country AS tc ON c.\"country_code_2\" = tc.\"country_code_2\" JOIN longest_period AS lp ON CAST(c.\"insert_date\" AS DATE) BETWEEN lp.period_start AND lp.period_end) SELECT ROUND(CAST(SUM(CASE WHEN \"capital\" = 1 THEN 1 ELSE 0 END) AS DECIMAL(38, 0)) / COUNT(*), 1) AS percentage_of_capital FROM entries_in_period") t0
  := by first | sql_equiv | sorry

end N_sf_local072_eq_2_3
