import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_sf_local229_eq_1_3

CREATE TABLE PLAYER («player_id» INT, «player_name» STRING, «dob» STRING, «batting_hand» STRING, «bowling_skill» STRING, «country_name» STRING)
CREATE TABLE BATSMAN_SCORED («match_id» INT, «over_id» INT, «ball_id» INT, «runs_scored» INT, «innings_no» INT)
CREATE TABLE BALL_BY_BALL («match_id» INT, «over_id» INT, «ball_id» INT, «innings_no» INT, «team_batting» INT, «team_bowling» INT, «striker_batting_position» INT, «striker» INT, «non_striker» INT, «bowler» INT)
CREATE TABLE MATCH («match_id» INT, «team_1» INT, «team_2» INT, «match_date» STRING, «season_id» INT, «venue» STRING, «toss_winner» INT, «toss_decision» STRING, «win_type» STRING, «win_margin» INT, «outcome_type» STRING, «match_winner» INT, «man_of_the_match» INT)

theorem eq (t0 : TableRel PLAYER_schema) (t1 : TableRel BATSMAN_SCORED_schema) (t2 : TableRel BALL_BY_BALL_schema) (t3 : TableRel MATCH_schema) :
    (sql%([PLAYER_schema, BATSMAN_SCORED_schema, BALL_BY_BALL_schema, MATCH_schema]) "WITH partnerships AS (SELECT b.\"match_id\", LEAST(b.\"striker\", b.\"non_striker\") AS low_player, GREATEST(b.\"striker\", b.\"non_striker\") AS high_player, SUM(CASE WHEN b.\"striker\" = LEAST(b.\"striker\", b.\"non_striker\") THEN bs.\"runs_scored\" ELSE 0 END) AS runs_low, SUM(CASE WHEN b.\"striker\" = GREATEST(b.\"striker\", b.\"non_striker\") THEN bs.\"runs_scored\" ELSE 0 END) AS runs_high, SUM(bs.\"runs_scored\") AS pship_runs FROM \"IPL\".\"IPL\".\"BALL_BY_BALL\" AS b JOIN \"IPL\".\"IPL\".\"BATSMAN_SCORED\" AS bs ON b.\"match_id\" = bs.\"match_id\" AND b.\"over_id\" = bs.\"over_id\" AND b.\"ball_id\" = bs.\"ball_id\" AND b.\"innings_no\" = bs.\"innings_no\" GROUP BY b.\"match_id\", LEAST(b.\"striker\", b.\"non_striker\"), GREATEST(b.\"striker\", b.\"non_striker\")), max_pship AS (SELECT \"match_id\", MAX(pship_runs) AS max_runs FROM partnerships GROUP BY \"match_id\"), best_partnerships AS (SELECT p.\"match_id\", p.low_player, p.high_player, p.runs_low, p.runs_high, p.pship_runs FROM partnerships AS p JOIN max_pship AS m ON p.\"match_id\" = m.\"match_id\" AND p.pship_runs = m.max_runs) SELECT \"match_id\", CASE WHEN runs_high > runs_low THEN high_player WHEN runs_low > runs_high THEN low_player ELSE high_player /* equal scores: higher ID is player1 */ END AS \"PLAYER1_ID\", CASE WHEN runs_high > runs_low THEN low_player WHEN runs_low > runs_high THEN high_player ELSE low_player /* equal scores: lower ID is player2 */ END AS \"PLAYER2_ID\", CASE WHEN runs_high > runs_low THEN runs_high WHEN runs_low > runs_high THEN runs_low ELSE runs_high /* equal */ END AS \"RUNS1\", CASE WHEN runs_high > runs_low THEN runs_low WHEN runs_low > runs_high THEN runs_high ELSE runs_low /* equal */ END AS \"RUNS2\", pship_runs AS \"PSHIP_RUNS\" FROM best_partnerships ORDER BY pship_runs DESC, \"match_id\"") t0 t1 t2 t3
  ~= (sql%([PLAYER_schema, BATSMAN_SCORED_schema, BALL_BY_BALL_schema, MATCH_schema]) "WITH ball_runs AS (SELECT b.\"match_id\", LEAST(b.\"striker\", b.\"non_striker\") AS p_low, GREATEST(b.\"striker\", b.\"non_striker\") AS p_high, b.\"striker\", bs.\"runs_scored\" FROM \"IPL\".\"IPL\".\"BALL_BY_BALL\" AS b JOIN \"IPL\".\"IPL\".\"BATSMAN_SCORED\" AS bs ON b.\"match_id\" = bs.\"match_id\" AND b.\"over_id\" = bs.\"over_id\" AND b.\"ball_id\" = bs.\"ball_id\" AND b.\"innings_no\" = bs.\"innings_no\"), partnership_totals AS (SELECT \"match_id\", p_low, p_high, SUM(CASE WHEN \"striker\" = p_low THEN \"runs_scored\" ELSE 0 END) AS runs_low, SUM(CASE WHEN \"striker\" = p_high THEN \"runs_scored\" ELSE 0 END) AS runs_high, SUM(\"runs_scored\") AS pship_runs FROM ball_runs GROUP BY \"match_id\", p_low, p_high), partnership_with_player_order AS (SELECT \"match_id\", CASE WHEN runs_high >= runs_low THEN p_high ELSE p_low END AS player1_id, CASE WHEN runs_high >= runs_low THEN p_low ELSE p_high END AS player2_id, CASE WHEN runs_high >= runs_low THEN runs_high ELSE runs_low END AS runs1, CASE WHEN runs_high >= runs_low THEN runs_low ELSE runs_high END AS runs2, pship_runs FROM partnership_totals), max_per_match AS (SELECT \"match_id\", MAX(pship_runs) AS max_pship FROM partnership_with_player_order GROUP BY \"match_id\") SELECT p.\"match_id\", p.player1_id AS \"PLAYER1_ID\", p.player2_id AS \"PLAYER2_ID\", p.runs1 AS \"RUNS1\", p.runs2 AS \"RUNS2\", p.pship_runs AS \"PSHIP_RUNS\" FROM partnership_with_player_order AS p JOIN max_per_match AS m ON p.\"match_id\" = m.\"match_id\" AND p.pship_runs = m.max_pship ORDER BY p.pship_runs DESC, p.\"match_id\"") t0 t1 t2 t3
  := by first | sql_equiv | sorry

end N_sf_local229_eq_1_3
