import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace N_182_eq

CREATE TABLE EMP («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL)
CREATE TABLE DEPT («DEPTNO» INT, «NAME» STRING)
CREATE TABLE BONUS («ENAME» STRING, «JOB» STRING, «SAL» INT, «COMM» INT)
CREATE TABLE EMPNULLABLES («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL)
CREATE TABLE EMPNULLABLES_20 («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL)
CREATE TABLE EMP_B («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL, «BIRTHDATE» INT)

theorem eq (t0 : TableRel EMP_schema) (t1 : TableRel DEPT_schema) (t2 : TableRel BONUS_schema) (t3 : TableRel EMPNULLABLES_schema) (t4 : TableRel EMPNULLABLES_20_schema) (t5 : TableRel EMP_B_schema) :
    (sql%([EMP_schema, DEPT_schema, BONUS_schema, EMPNULLABLES_schema, EMPNULLABLES_20_schema, EMP_B_schema]) "SELECT t.DEPTNO, t.NAME, t0.R, t0.EXPR$1 FROM (SELECT DEPTNO, NAME, CAST(NAME AS BIGINT) AS NAME0 FROM DEPT) AS t INNER JOIN (SELECT RANK() OVER (ORDER BY NAME NULLS FIRST) AS R, 1 + 1 AS EXPR$1 FROM DEPT) AS t0 ON t.NAME0 = t0.R") t0 t1 t2 t3 t4 t5
  ~= (sql%([EMP_schema, DEPT_schema, BONUS_schema, EMPNULLABLES_schema, EMPNULLABLES_20_schema, EMP_B_schema]) "SELECT DEPT1.DEPTNO, DEPT1.NAME, t2.R, t2.EXPR$1 FROM DEPT AS DEPT1 INNER JOIN (SELECT RANK() OVER (ORDER BY NAME NULLS FIRST) AS R, 1 + 1 AS EXPR$1 FROM DEPT) AS t2 ON DEPT1.NAME = t2.R") t0 t1 t2 t3 t4 t5
  := by first | sql_equiv | sorry

end N_182_eq
