import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace Calcite_188

CREATE TABLE EMP («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL)
CREATE TABLE DEPT («DEPTNO» INT, «NAME» STRING)
CREATE TABLE BONUS («ENAME» STRING, «JOB» STRING, «SAL» INT, «COMM» INT)
CREATE TABLE EMPNULLABLES («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL)
CREATE TABLE EMPNULLABLES_20 («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL)
CREATE TABLE EMP_B («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL, «BIRTHDATE» INT)

theorem eq :
    sql%([EMP_schema, DEPT_schema, BONUS_schema, EMPNULLABLES_schema, EMPNULLABLES_20_schema, EMP_B_schema]) "SELECT EXPR$0, EXPR$1, SUM(EXPR$1) OVER (PARTITION BY EXPR$0 ORDER BY EXPR$1 NULLS FIRST RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) FROM (SELECT DEPTNO, MIN(EMPNO) AS EXPR$0, SUM(SAL) AS EXPR$1 FROM EMP GROUP BY DEPTNO) AS t0"
  = sql%([EMP_schema, DEPT_schema, BONUS_schema, EMPNULLABLES_schema, EMPNULLABLES_20_schema, EMP_B_schema]) "SELECT MIN(EMPNO), SUM(SAL), SUM(SUM(SAL)) OVER (PARTITION BY MIN(EMPNO) ORDER BY SUM(SAL) NULLS FIRST RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS $2 FROM EMP GROUP BY DEPTNO"
  := by first | sql_equiv | sorry

end Calcite_188
