import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace Calcite_211

CREATE TABLE EMP («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL)
CREATE TABLE DEPT («DEPTNO» INT, «NAME» STRING)
CREATE TABLE BONUS («ENAME» STRING, «JOB» STRING, «SAL» INT, «COMM» INT)
CREATE TABLE EMPNULLABLES («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL)
CREATE TABLE EMPNULLABLES_20 («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL)
CREATE TABLE EMP_B («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL, «BIRTHDATE» INT)

theorem eq :
    sql%([EMP_schema, DEPT_schema, BONUS_schema, EMPNULLABLES_schema, EMPNULLABLES_20_schema, EMP_B_schema]) "SELECT EMP.JOB, t0.MGR, EMP.DEPTNO, MAX(t0.HIREDATE1) AS HIREDATE1, SUM(t0.COMM1) AS COMM1 FROM EMP INNER JOIN (SELECT MGR, SAL, MAX(HIREDATE) AS HIREDATE1, SUM(COMM) AS COMM1 FROM EMP GROUP BY MGR, SAL) AS t0 ON EMP.SAL = t0.SAL GROUP BY EMP.JOB, t0.MGR, EMP.DEPTNO"
  = sql%([EMP_schema, DEPT_schema, BONUS_schema, EMPNULLABLES_schema, EMPNULLABLES_20_schema, EMP_B_schema]) "SELECT t3.JOB, t4.MGR AS MGR0, t3.DEPTNO, MAX(t4.HIREDATE1) AS HIREDATE1, SUM(CAST(t3.$f3 * t4.COMM1 AS INT)) AS COMM1 FROM (SELECT JOB, SAL, DEPTNO, COUNT(*) AS $f3 FROM EMP GROUP BY JOB, SAL, DEPTNO) AS t3 INNER JOIN (SELECT MGR, SAL, MAX(HIREDATE) AS HIREDATE1, SUM(COMM) AS COMM1 FROM EMP GROUP BY MGR, SAL) AS t4 ON t3.SAL = t4.SAL GROUP BY t3.JOB, t3.DEPTNO, t4.MGR"
  := by first | sql_equiv | sorry

end Calcite_211
