import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace Calcite_233

CREATE TABLE EMP («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL)
CREATE TABLE DEPT («DEPTNO» INT, «NAME» STRING)
CREATE TABLE BONUS («ENAME» STRING, «JOB» STRING, «SAL» INT, «COMM» INT)
CREATE TABLE EMPNULLABLES («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL)
CREATE TABLE EMPNULLABLES_20 («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL)
CREATE TABLE EMP_B («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL, «BIRTHDATE» INT)

theorem eq :
    sql%([EMP_schema, DEPT_schema, BONUS_schema, EMPNULLABLES_schema, EMPNULLABLES_20_schema, EMP_B_schema]) "SELECT CAST(NAME AS VARCHAR(128)), CAST(EMPNO AS INT) FROM (SELECT t.DEPTNO, t.NAME, t0.EMPNO, t0.ENAME, t0.JOB, t0.MGR, t0.HIREDATE, t0.SAL, t0.COMM, t0.DEPTNO AS DEPTNO1, t0.SLACKER FROM (SELECT DEPTNO, NAME, CAST(DEPTNO AS INT) AS DEPTNO0 FROM DEPT) AS t INNER JOIN (SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, SLACKER, CAST(DEPTNO AS INT) AS DEPTNO0 FROM EMP) AS t0 ON t.DEPTNO0 = t0.DEPTNO0) AS t1 WHERE CAST(t1.JOB AS VARCHAR(1)) = 'Manager'"
  = sql%([EMP_schema, DEPT_schema, BONUS_schema, EMPNULLABLES_schema, EMPNULLABLES_20_schema, EMP_B_schema]) "SELECT CAST(NAME AS VARCHAR(128)), EMPNO FROM (SELECT t4.DEPTNO, t4.NAME, t5.EMPNO, t5.ENAME, t5.JOB, t5.MGR, t5.HIREDATE, t5.SAL, t5.COMM, t5.DEPTNO AS DEPTNO1, t5.SLACKER FROM (SELECT DEPTNO, NAME, DEPTNO AS DEPTNO0 FROM DEPT) AS t4 INNER JOIN (SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, SLACKER, DEPTNO AS DEPTNO0 FROM EMP) AS t5 ON t4.DEPTNO0 = t5.DEPTNO0) AS t6 WHERE CAST(t6.JOB AS VARCHAR(1)) = 'Manager'"
  := by first | sql_equiv | sorry

end Calcite_233
