import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace Calcite_237

CREATE TABLE EMP («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL)
CREATE TABLE DEPT («DEPTNO» INT, «NAME» STRING)
CREATE TABLE BONUS («ENAME» STRING, «JOB» STRING, «SAL» INT, «COMM» INT)
CREATE TABLE EMPNULLABLES («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL)
CREATE TABLE EMPNULLABLES_20 («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL)
CREATE TABLE EMP_B («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL, «BIRTHDATE» INT)

theorem eq :
    sql%([EMP_schema, DEPT_schema, BONUS_schema, EMPNULLABLES_schema, EMPNULLABLES_20_schema, EMP_B_schema]) "SELECT DEPTNO, SUM(COMM), COUNT(DISTINCT SAL) FILTER(WHERE SAL > 1000) FROM EMP GROUP BY DEPTNO"
  = sql%([EMP_schema, DEPT_schema, BONUS_schema, EMPNULLABLES_schema, EMPNULLABLES_20_schema, EMP_B_schema]) "SELECT DEPTNO, CAST(MIN(EXPR$1) FILTER(WHERE $g_3) AS INT), COUNT(SAL) FILTER(WHERE $g_0_f_2) FROM (SELECT DEPTNO, SAL, SUM(COMM) AS EXPR$1, GROUPING(DEPTNO, SAL, SAL > 1000) = 0 AND SAL > 1000 IS TRUE AS $g_0_f_2, GROUPING(DEPTNO, SAL, SAL > 1000) = 3 AS $g_3 FROM EMP GROUP BY GROUPING SETS ((DEPTNO, SAL, SAL > 1000), DEPTNO)) AS t3 GROUP BY DEPTNO"
  := by first | sql_equiv | sorry

end Calcite_237
