import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace Calcite_380

CREATE TABLE EMP («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL)
CREATE TABLE DEPT («DEPTNO» INT, «NAME» STRING)
CREATE TABLE BONUS («ENAME» STRING, «JOB» STRING, «SAL» INT, «COMM» INT)
CREATE TABLE EMPNULLABLES («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL)
CREATE TABLE EMPNULLABLES_20 («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL)
CREATE TABLE EMP_B («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL, «BIRTHDATE» INT)

theorem eq :
    sql%([EMP_schema, DEPT_schema, BONUS_schema, EMPNULLABLES_schema, EMPNULLABLES_20_schema, EMP_B_schema]) "SELECT EMPNO FROM EMP WHERE EMPNO < CASE WHEN DEPTNO IN (SELECT CASE WHEN TRUE THEN CAST(DEPTNO AS INT) ELSE NULL END FROM EMP WHERE EMPNO < 20) = TRUE THEN 10 WHEN DEPTNO IN (SELECT CASE WHEN TRUE THEN CAST(DEPTNO AS INT) ELSE NULL END FROM EMP WHERE EMPNO < 20) = FALSE THEN 20 ELSE 30 END"
  = sql%([EMP_schema, DEPT_schema, BONUS_schema, EMPNULLABLES_schema, EMPNULLABLES_20_schema, EMP_B_schema]) "SELECT EMP2.EMPNO FROM EMP AS EMP2 CROSS JOIN (SELECT COUNT(*) AS c, COUNT(CASE WHEN TRUE THEN CAST(DEPTNO AS INT) ELSE NULL END) AS ck FROM EMP WHERE EMPNO < 20) AS t7 LEFT JOIN (SELECT CASE WHEN TRUE THEN CAST(t8.DEPTNO AS INT) ELSE NULL END AS $f0, t9.i FROM (SELECT * FROM EMP WHERE EMPNO < 20) AS t8, (VALUES (TRUE)) AS t9(i) GROUP BY CASE WHEN TRUE THEN CAST(t8.DEPTNO AS INT) ELSE NULL END, t9.i) AS t11 ON EMP2.DEPTNO = t11.$f0 WHERE EMP2.EMPNO < CASE WHEN CASE WHEN t7.c = 0 THEN FALSE WHEN NOT t11.i IS NULL THEN TRUE WHEN t7.ck < t7.c THEN NULL ELSE FALSE END = TRUE THEN 10 WHEN CASE WHEN t7.c = 0 THEN FALSE WHEN NOT t11.i IS NULL THEN TRUE WHEN t7.ck < t7.c THEN NULL ELSE FALSE END = FALSE THEN 20 ELSE 30 END"
  := by first | sql_equiv | sorry

end Calcite_380
