import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace Calcite_50

CREATE TABLE EMP («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL)
CREATE TABLE DEPT («DEPTNO» INT, «NAME» STRING)
CREATE TABLE BONUS («ENAME» STRING, «JOB» STRING, «SAL» INT, «COMM» INT)
CREATE TABLE EMPNULLABLES («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL)
CREATE TABLE EMPNULLABLES_20 («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL)
CREATE TABLE EMP_B («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL, «BIRTHDATE» INT)

theorem eq :
    sql%([EMP_schema, DEPT_schema, BONUS_schema, EMPNULLABLES_schema, EMPNULLABLES_20_schema, EMP_B_schema]) "SELECT * FROM (SELECT * FROM (SELECT NAME, DEPTNO FROM (SELECT NAME, DEPTNO, COUNT(*) AS EXPR$2 FROM DEPT GROUP BY NAME, DEPTNO EXCEPT ALL SELECT NAME, DEPTNO, 1 AS $f2 FROM DEPT) AS t2 EXCEPT ALL SELECT NAME, DEPTNO FROM (SELECT NAME, DEPTNO, 1 AS $f2 FROM DEPT EXCEPT ALL SELECT NAME, DEPTNO, COUNT(*) AS EXPR$2 FROM DEPT GROUP BY NAME, DEPTNO) AS t7) AS t9 EXCEPT ALL SELECT NAME, DEPTNO FROM DEPT) AS t12"
  = sql%([EMP_schema, DEPT_schema, BONUS_schema, EMPNULLABLES_schema, EMPNULLABLES_20_schema, EMP_B_schema]) "SELECT NAME, DEPTNO FROM DEPT GROUP BY NAME, DEPTNO EXCEPT ALL SELECT NAME, DEPTNO FROM DEPT EXCEPT ALL SELECT * FROM (SELECT NAME, DEPTNO FROM DEPT EXCEPT ALL SELECT NAME, DEPTNO FROM DEPT GROUP BY NAME, DEPTNO) AS t EXCEPT ALL SELECT NAME, DEPTNO FROM DEPT"
  := by first | sql_equiv | sorry

end Calcite_50
