import LeanDatabase.Parser
import LeanDatabase.SQLSyntax
open LeanDatabase Lean
set_option maxHeartbeats 1000000
set_option maxRecDepth 1000000

namespace Calcite_77

CREATE TABLE EMP («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL)
CREATE TABLE DEPT («DEPTNO» INT, «NAME» STRING)
CREATE TABLE BONUS («ENAME» STRING, «JOB» STRING, «SAL» INT, «COMM» INT)
CREATE TABLE EMPNULLABLES («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL)
CREATE TABLE EMPNULLABLES_20 («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL)
CREATE TABLE EMP_B («EMPNO» INT, «DEPTNO» INT, «ENAME» STRING, «JOB» STRING, «MGR» INT, «HIREDATE» INT, «SAL» INT, «COMM» INT, «SLACKER» BOOL, «BIRTHDATE» INT)

theorem eq :
    sql%([EMP_schema, DEPT_schema, BONUS_schema, EMPNULLABLES_schema, EMPNULLABLES_20_schema, EMP_B_schema]) "SELECT EMP.JOB, MIN(EMP.SAL) AS MIN_SAL, MIN(EMP.DEPTNO) AS MIN_DEPTNO, SUM(EMP.SAL) + 1 AS SUM_SAL_PLUS, MAX(EMP.SAL) AS MAX_SAL, SUM(EMP.SAL) AS SUM_SAL_2, COUNT(*) AS COUNT_SAL, COUNT(EMP.MGR) AS COUNT_MGR FROM EMP INNER JOIN DEPT ON EMP.JOB = DEPT.NAME GROUP BY EMP.JOB, DEPT.NAME"
  = sql%([EMP_schema, DEPT_schema, BONUS_schema, EMPNULLABLES_schema, EMPNULLABLES_20_schema, EMP_B_schema]) "SELECT t2.JOB, t2.MIN_SAL, t2.MIN_DEPTNO, CAST(t2.SUM_SAL_2 * t3.$f1 AS INT) + 1 AS SUM_SAL_PLUS, t2.MAX_SAL, CAST(t2.SUM_SAL_2 * t3.$f1 AS INT) AS SUM_SAL_2, t2.COUNT_SAL * t3.$f1 AS COUNT_SAL, t2.COUNT_MGR * t3.$f1 AS COUNT_MGR FROM (SELECT JOB, MIN(SAL) AS MIN_SAL, MIN(DEPTNO) AS MIN_DEPTNO, SUM(SAL) AS SUM_SAL_2, MAX(SAL) AS MAX_SAL, COUNT(*) AS COUNT_SAL, COUNT(MGR) AS COUNT_MGR FROM EMP GROUP BY JOB) AS t2 INNER JOIN (SELECT NAME, COUNT(*) AS $f1 FROM DEPT GROUP BY NAME) AS t3 ON t2.JOB = t3.NAME"
  := by first | sql_equiv | sorry

end Calcite_77
